### ISSUE TITLE
Assertion in http.c

### ISSUE THREAD

**Issue by artemg** [libevent/libevent#10]
Having some kind of http spider, making a lot of requests, I see sometimes this error:
[err] http.c:1112: Assertion evcon->state == EVCON_WRITING failed in evhttp_write_connectioncb
So evcon->state is overwritten somewhere in bufferevent callbacks. 

Tested on libevent-2.0.19

**Comment by ellzey** [comment]
Is this still an issue.... 3 years later? :-1:
