### ISSUE TITLE
multi-threaded http server & proposal

### ISSUE THREAD

**Issue by julian-zhuang** [libevent/libevent#1001]
I want to realizes a multi-threaded http server.(Just use libevent )

I didn't find a good solution.

I found  evhttp_connection_get_bufferevent
I want use this API get bufferevent,then reset new base pointer,run in another thread.I'm not sure if I should do that.

*^_^*
one more thing.

Maybe in the future we can export some basic APIs used by high frequency.

like this:
bind_socket
make_addrinfo
........

PS:Thank you so much for your support.

**Comment by azat** [comment]
>I found evhttp_connection_get_bufferevent
>I want use this API get bufferevent,then reset new base pointer,run in another thread.I'm not sure if I should do that.

Not sure what you will get with this.

>Maybe in the future we can export some basic APIs used by high frequency.
>
>like this:
>bind_socket
>make_addrinfo

They should be rewritten to be more generic, and then they can be exported.

>I want to realizes a multi-threaded http server.(Just use libevent )
> I didn't find a good solution.

If you need multi-threaded http server, the most sane way to go is:
- create pool of threads
- create base in each thread
- create evhttp handler in each base
- bind to the same port with SO_REUSEPORT in each thread
- and this will work like a charm (otherwise you will get into trouble due to http layer is not thread safe basically)

But with a few notes:
- SO_REUSEPORT is not available on windows (maybe some other platforms)
- in this case you will need to implement some proxy, i.e. create thread for accepting connections and pass them to http worker threads

**Comment by julian-zhuang** [comment]
struct evhttp_connection *  Ev_Connection = evhttp_request_get_connection(request);
        struct bufferevent* Http_Buf = evhttp_connection_get_bufferevent(Ev_Connection);

        struct event_base *base;
        base = event_base_new();
        if (base == nullptr)
        {
            fprintf (stderr, "Couldn't create an event_base: exiting\n");
            return;
        }
        bufferevent_base_set(base, Http_Buf);
        std::thread *Child_Thread = new std::thread(event_base_dispatch, base);
        Child_Thread->detach();        struct evhttp_connection *  Ev_Connection = evhttp_request_get_connection(request);
        struct bufferevent* Http_Buf = evhttp_connection_get_bufferevent(Ev_Connection);

        struct event_base *base;
        base = event_base_new();
        if (base == nullptr)
        {
            fprintf (stderr, "Couldn't create an event_base: exiting\n");
            return;
        }
        bufferevent_base_set(base, Http_Buf);
        std::thread *Child_Thread = new std::thread(event_base_dispatch, base);
        Child_Thread->detach();

**Comment by julian-zhuang** [comment]
struct evhttp_connection *  Ev_Connection = evhttp_request_get_connection(request);
        struct bufferevent* Http_Buf = evhttp_connection_get_bufferevent(Ev_Connection);

        struct event_base *base;
        base = event_base_new();
        if (base == nullptr)
        {
            fprintf (stderr, "Couldn't create an event_base: exiting\n");
            return;
        }
        bufferevent_base_set(base, Http_Buf);
        std::thread *Child_Thread = new std::thread(event_base_dispatch, base);
        Child_Thread->detach();

**Comment by julian-zhuang** [comment]
like this
Assuming that event_base can be released normally,no memory leak.

**Comment by julian-zhuang** [comment]
Like this
Assuming that event_base can be released normally,no memory leak.

**Comment by azat** [comment]
Sorry, I don't understand what you code does

**Comment by okayabc** [comment]
@julian-zhuang , Have you solved the problem?

**Comment by azat** [comment]
Closed for now, @julian-zhuang please reopen if you still have a question
