### ISSUE TITLE
How do disable ssl renegotiation and RC4 algorithm?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#1005]
Is there any interface can prohibit it? thanks!

**Comment by azat** [comment]
Sure, you just need to configure ssl ctx in the right way, i.e.:

```c
    SSL_CTX_set_cipher_list(ctx,
        "!ADH:!aNULL:!DH:!EDH:!eNULL:!LOW:!SSLv2:!EXP:!NULL:!RC4");
```

Also maybe this can be done with `openssl.cnf`, but I'm not sure

P.S. the questions if more related to openssl, not libevent itself.
