### ISSUE TITLE
ci: TEST_EXPORT_SHARED CI variant is broken on all platforms

### ISSUE THREAD

**Issue by nigriMSFT** [libevent/libevent#1007]
This failure is present on all platforms that run this variant. It causes CI failure on linux and macos, but fails silently on windows.

[test-export] use shared library
[test-export] test for build tree
[test-export] fail: link core and run core expects success but gets failure.

**Comment by azat** [comment]
So how this test implemented is that test-export.py invokes cmake with different options and test the test-export probject that it works, but in some cases by some reason it ends up invoking cmake in the root test-export project and this makes cmake write the file to the parent project over build directory

@ygj6 can fix this and maybe even better rewrite this script?

**Comment by azat** [comment]
This test breaks it - `[test-export] test for install tree(in non-system-wide path`
