### ISSUE TITLE
evhttp server that spawns a new thread to handle each connection?

### ISSUE THREAD

**Issue by RokerHRO** [libevent/libevent#1013]
Is it possible to write an evhttp server that handles each TCP connection (which might use Keep-Alive so several requests go over this connection) in a separate thread, so it would not block the whole server when the processing of a request would take more time?

It would be nice if the documentation would contain a simple example server that demonstrate how to do it.

**Comment by ploxiln** [comment]
evhttp is not designed for this. This is an advanced topic. You can see https://github.com/libevent/libevent/issues/991 and https://github.com/libevent/libevent/issues/1001#issuecomment-620866831

**Comment by RokerHRO** [comment]
@ploxiln : Okay. Thank you for your quick answer. It seems I need to switch to libevhtp.
