### ISSUE TITLE
How to route evhttp_send_reply from worker thread to base thread?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#1015]
Currently i plan to create serveral fixed threads which every thread create one event_base and through event_base_dispatch receives http(s) request ceaseless, after received http(s) request i will dispatch it to worker thread to process it, when worker thread finish processing, it will send reply to client. Then how to let base thread know it's time to send evhttp_send_reply(because according to former learned knowledge, evhttp_send_reply must be sent in base thread which receives it)?

**Comment by ploxiln** [comment]
In the "every thread create one event_base" model, every thread is completely independent, and does not interact with other threads at all. They all open the same port concurrently, which is only possible with `SO_REUSEPORT`, and incoming connections are received by a random one of the threads which independently opened and listened on that port.

**Comment by kamenl** [comment]
libevhtp does it like this: it has a single (lightly loaded) listener server thread that receives notifications about incoming connection requests. When it receives one, it passes it to one of a pool of worker threads, each with their own event_base, which remains the owner and handler of this connection till it ends.

The important point here is, one thread listens for connection requests (no SO_REUSEPORT involved) and passes these off to someone else, leaving the accept() call to the other thread

**Comment by okayabc** [comment]
@ploxilin, i see what you said, i mean when one of the base thread receives the request, i need process the request in worker thread in order to achive high concurrency, but when the worker thread finished processing, how can it send the reply to original base thread?

@kamenl, in high concurrency situation, one http request is created with a event base, that means many event base need be created and destoryed.

**Comment by ploxiln** [comment]
In the simplified model that has been suggested in https://github.com/libevent/libevent/issues/1001#issuecomment-620866831, the "base thread" does _not_ receive the request, each worker thread receives the request itself, and responds to the request itself.

You could instead receive requests on a "base thread", and hand them off to other threads to do work, and then the worker threads hand the result back to the "base thread" for it to send the reply. This is a different model. I explained how you need to do this in https://github.com/libevent/libevent/issues/991#issuecomment-606248445 (create a callback function to do the response back on the ioloop thread, allocate an event, allocate a user-data context struct, get the event ready before handing off to the thread, and when the thread is finished it calls [event_active()](http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/event_8h.html#a31d9440cf2b7010e32a05a2142a91525)).

You could instead use what @kamenl mentioned, [libevhtp](https://github.com/criticalstack/libevhtp) which is a different library that works with libevent, and has some different options and capabilities regarding threads.

You could instead limit yourself to non-blocking things using libevent primitives - http requests, raw tcp protocols, and timers, all asynchronous callback based, and use no threads at all.

You could instead use a purely thread-based library, and forget about event loops, I mentioned some in https://github.com/libevent/libevent/issues/991#issuecomment-606301070 - I really think this might be your best bet.

**Comment by kamenl** [comment]
Oh, I think you misunderstood how libevhtp does it. It will create its own 'pool' of server threads, each with its own event_base. When a connection request arrives it will pass it off to a pool thread (it has a very very simple mechanism to try and guess which one has the smallest backlog) and the pool thread would accept() the connection. One pool thread will be serving many connections at any given time. Multithreading would not be enabled on those event bases

**Comment by okayabc** [comment]
@kamenl which libevhtp do you use, https://github.com/haiwen/libevhtp or https://github.com/criticalstack/libevhtp?

**Comment by okayabc** [comment]
@ploxiln, do you think the model i use currently is reasonable?

**Comment by azat** [comment]
> do you think the solution i mentioned in #1015 is reasonable and feasible? currently using this solution the service can run stably. The only difference is that i use one base thread and many work threads.

>after received http(s) request i will dispatch it to worker thread to process it, when worker thread finish processing, it will send reply to client

I don't see the reason for this worker threads, just process the queries from the http callback and done with it, have you tried this? any issues with this solution? (provided that you have multiple htreads for http serving)

>@kamenl which libevhtp do you mention, https://github.com/haiwen/libevhtp or https://github.com/criticalstack/libevhtp?

AFAIK this is official - https://github.com/criticalstack/libevhtp (besides the first one is fork)

P.S. Please don't cross link issues in a such way

**Comment by okayabc** [comment]
> I don't see the reason for this worker threads, just process the queries from the http callback and done with it, have you tried this? any issues with this solution? (provided that you have multiple htreads for http serving)
> 
I see your suggesstion. I haven't tried it.
I use several fixed worker threads in order to gain high throughput。Because if no worker thread only process request in http(s) callback, it will increase response time due to every request  may interact with database. 
Using worker thread i can queue the request and process it one by one. 
Another reason using worker thread is that i need to process the same last digit of ip address in the same thread.
Processing the request in callback, if many requests arrives at the same time, then the callback must be Reentrant, i am not sure whether this is ok?

**Comment by azat** [comment]
I'm confused

>I use several fixed worker threads in order to gain high throughput。Because if no worker thread only process request in http(s) callback, it will increase response time due to every request may interact with database.

Ok, thread poool for interacting with database.

>Using worker thread i can queue the request and process it one by one.

But you wrote that you have a thread pool?

>Another reason using worker thread is that i need to process the same last digit of ip address in the same thread.

Such load balancing can be easily built into your application (by using one thread for accept connections and pass accepted file descriptors to required threads after), or you can also use some load balancer in front of your web server.

>Processing the request in callback, if many requests arrives at the same time, then the callback must be Reentrant, i am not sure whether this is ok? What's more, one request needs one database connection which need many database connections.

I think you misunderstand how http server works, one http server can handle only one request in parallel (since it uses only one thread), it calls your callback and blocking until you will return from it.

So if you have multiple threads with multiple http servers then yes they can execute callbacks in parallel, but this looks like your thread pool above, you just need some context for each thread, or if you want to be it simpler (but less controllable and it is not always good design choice), then you can just use thread-local variables.

**Comment by okayabc** [comment]
> I think you misunderstand how http server works, one http server can handle only one request in parallel (since it uses only one thread), it calls your callback and blocking until you will return from it.

Does parallel should be serially?

>it calls your callback and blocking until you will return from it.
This means if the bussiness logic is very complex, then the next reqeust should wait until the current one executed completely. So i think it will conflict with high throughput.
