### ISSUE TITLE
WolfSSL support

### ISSUE THREAD

**Issue by sbonar** [libevent/libevent#1016]
Any chance of adding support for WolfSSL?

**Comment by azat** [comment]
[Looks](https://www.wolfssl.com/docs/wolfssl-manual/ch13/) like it is pretty easy to do:

>wolfSSL (formerly CyaSSL) provides an OpenSSL compatibility header

But I'm not sure that this is that simple.
Are you interesting in submit a patch for this?

**Comment by sbonar** [comment]
No patch yet as I was seeing if anyone else had completed one.
Even with the compat layer I am getting the following:
error: cannot convert 'ssl_st*' to 'SSL* {aka WOLFSSL*}' in initialization

**Comment by azat** [comment]
>error: cannot convert 'ssl_st*' to 'SSL* {aka WOLFSSL*}' in initialization
>along with:
>include/event2/bufferevent_ssl.h:43:8: note: class type 'ssl_st' is incomplete
>struct ssl_st;

Looks like some `#ifdef` required

> A note - my application is currently using 2.1.5-beta so I know I am behind and if going to the latest release will help I will do that first.

It won't, there were no changes in this place AFAIR

**Comment by azat** [comment]
No progress
