### ISSUE TITLE
How to update evBuffer at a position

### ISSUE THREAD

**Issue by ssubrama-tibco** [libevent/libevent#1020]
We have an existing system that use tcp socket with BSD style API.
We are trying port the server without having to change the client protocol.
The protocol is a Binary ASN.1 based protocol and at a high level is Fixed size header + variable data. The first member of the header is the length. 
As we write to buffer, we first write 0 as the header, and then after serialization the body, the length is computed on the fly, and it is updated on the first position.

I didn't see any API on evBuffer, and further if I have to do it my self, it will be double copy. These buffer can grow large. The second reason using evBuffers is to manage the serialization into manageable fixed chunk size.
Can you suggest any way to overcome or something I am missing without changing the protocol?

**Comment by ssubrama-tibco** [comment]
We are using libevent 2.1.8

**Comment by azat** [comment]
If you really need this data in the evbuffer and in that way, the simplest way will be to use `evbuffer_prepend`, or you already tried and does not satisfied with the performance/memory allocations?

**Comment by ssubrama-tibco** [comment]
We only need  to update 4 bytes. I saw Prepend and it seems to be expensive call.
I did see evbuffer_ptr_set API, it seems only for searching.

The idea was wrap evBuffer around our ASN.1 outputstream

**Comment by ssubrama-tibco** [comment]
I could manipulate the structure. It is 'C' after all, but just wanted to check from the engineers

**Comment by azat** [comment]
Yeah there is no easy and fast way to do this, but you can reserve space for size at the beginning, i.e.:

```c
size_t size = 0;
// reserve space for size
// so that subsequent evbuffer_drain()/evbuffer_prepend() will not create any chains
evbuffer_add(buf, (void *)size, sizeof(size));
// this is your data
evbuffer_add_printf(buf, "foobar");
// calcualte size
size = evbuffer_get_length(buf);
size -= sizeof(size);
// update size
evbuffer_drain(buf, sizeof(size));
evbuffer_prepend(buf, (void *)size, sizeof(size));
``

**Comment by ssubrama-tibco** [comment]
Thanks. That’s neat hack. I see what you have done. Hopefully underneath
the covers drain just did pointer arithmetic and no memmoves within the
chain. We can close the ticket.

**Comment by azat** [comment]
>no memmoves within the chain

yes, there should be any memmove for this case
