### ISSUE TITLE
ctest failures in Windows vs2019 variant are not flagged as CI failures

### ISSUE THREAD

**Issue by nigriMSFT** [libevent/libevent#1022]
Take this example run where the vs2019 LIBRARY_TYPE_STATIC variant ctest detects errors but the workflow is marked as successful. I am not fully educated on github workflows and libevent's usage of it, but I would imagine there is a bug somewhere.

https://github.com/libevent/libevent/runs/688321624?check_suite_focus=true

**Comment by azat** [comment]
Referenced patch does not work, @ygj6 can you take a look?
