### ISSUE TITLE
Release date for 2.2

### ISSUE THREAD

**Issue by fjahr** [libevent/libevent#1024]
Sorry because this is not the right place to ask this but I already tried IRC and did not get a response: Is there any planning for a potential release schedule for 2.2? I was looking for it but could not find any info.

Particularly I am interested in https://github.com/libevent/libevent/pull/578 and/or https://github.com/libevent/libevent/pull/592 because I would like to prevent running out of file descriptors due to too many connections being opened. (increasing system limits is not a solution, I need a robust way to prevent it from taking up all the file descriptors, no matter how many are available).

Thanks!

**Comment by azat** [comment]
Thank you for the reminder!

>Is there any planning for a potential release schedule for 2.2?

I was thinking about this just recently (after a few major bits added)
Does some alpha release will work for you?

>Particularly I am interested in #578 and/or #592 because I would like to prevent running out of file descriptors due to too many connections being opened.

Actually http layer is not under active development, but looking into #592 again and it looks pretty simple - it can be merged, but there is no test yet...

**Comment by fjahr** [comment]
It wouldn't work for a release but it would be a first step and it would make testing a lot easier, so I could give you feedback as well if I encounter issues :)

**Comment by azat** [comment]
Closed in favor of #1094
