### ISSUE TITLE
When remote client shutdown exceptionally, the libevent crash

### ISSUE THREAD

**Issue by generalzzd** [libevent/libevent#1033]
Hi! I'm building a TCP server with libevent-master on Windows7 by using Visual Studio 2015. I got a libevent inner error. Program breakpoint hit on "EnterCriticalSection(lock);" of evthread_win32_lock(unsigned mode, void *lock_) in evthread_win32.c file.

This is my program, I use book "R8: Connection listeners: accepting TCP connections" TCP server example as skeleton. 

This is the connection listener, I also create deamon event that will check all connection status between server and client every 10 seconds.

	struct event_base *base;
	struct evconnlistener *listener;
	struct sockaddr_in sin;

	base = event_base_new();
	if (!base) {
		puts("Couldn't open event base");
		return;
	}

	/* Clear the sockaddr before using it, in case there are extra
	* platform-specific fields that can mess us up. */
	memset(&sin, 0, sizeof(sin));
	/* This is an INET address */
	sin.sin_family = AF_INET;
	/* Listen on 0.0.0.0 */
	sin.sin_addr.s_addr = htonl(0);
	/* Listen on the given port. */
	sin.sin_port = htons(_port);

	listener = evconnlistener_new_bind(base, accept_connection_cb, NULL,
		LEV_OPT_CLOSE_ON_FREE | LEV_OPT_THREADSAFE, -1,
		(struct sockaddr*)&sin, sizeof(sin));
	if (!listener) {
		perror("Couldn't create listener");
		return;
	}
	evconnlistener_set_error_cb(listener, accept_error_cb);
	/*heart beat */
	auto evSessionDeamon = event_new(base, 0, 
		EV_TIMEOUT | EV_PERSIST, ZDTCPEngine::ev_sessionDeamon,
		0);

	//event_priority_set(evSessionDeamon, 0);
	struct timeval ten_seconds = { 10,0 };
	event_add(evSessionDeamon, &ten_seconds);

	event_base_dispatch(base);

	cout << "libevent loop exit" << endl;

This is my accept connection cb function. It will create a new bufferevent for every connection. I also store the *bev pointer in a hashmap.

	/* We got a new connection! Set up a bufferevent for it. */
	struct event_base *base = evconnlistener_get_base(listener);
	struct bufferevent *bev = bufferevent_socket_new(
		base, fd, BEV_OPT_CLOSE_ON_FREE |BEV_OPT_THREADSAFE |BEV_OPT_DEFER_CALLBACKS);

	bufferevent_setcb(bev, session_read_cb, NULL, session_event_cb, NULL);

	bufferevent_enable(bev, EV_READ | EV_WRITE);
        /* store hash map here */
        .......

This is my deamon event callback functions. Every 10 seconds will check the connections status, if a connection less than "my requirement " I will force shutting it down.

```
inline void ev_sessionDeamon(
	evutil_socket_t fd,
	short what,
	void *arg)
{
	auto& sessionBevPool = mSessionBevPool;
	if (sessionBevPool.find((int)it->second.bev)
		!= sessionBevPool.end())
	{
		auto& bevPool = sessionBevPool[(int)it->second.bev];
		if (bevPool.size() > 1)
		{
			string sessionKey = it->second.ip
				+ " " + to_string(it->second.port);
			bevPool.erase(sessionKey);
		}
		else
		{
			bufferevent_free(it->second.bev);
			sessionBevPool.erase((int)it->second.bev);
		}
	}
}
```

I can use bufferevent_free close a connection perfectly when they're not meet my reqirement. However, the problem is that when a remote client disconnection exceptionally, for example, press "stop button in visual studio in the client side", the server side libevent won't detect the disconnection status and when my deamon function go check status and forcing closing it. The program crash on  "EnterCriticalSection(lock);". I search the bev pointer it target on 0xdddddd address. 

Could you please help me solve this problem? Thank you!

**Comment by ploxiln** [comment]
Did you call `evthread_use_windows_threads()`? What exact version of libevent are you using?

**Comment by generalzzd** [comment]
Oh! I solve this problem! I accidentally free my bufferevent pointer in my event_cb callback functions. Thank you ploxiln! :)
