### ISSUE TITLE
VxWorks support

### ISSUE THREAD

**Issue by wiktorinox** [libevent/libevent#1040]
Hi,
I'm sorry if it's not the right place to ask but:
is there any support for VxWorks operating system? If not, is it possible to port libevent to work on it? 
What would that require? Are there any resources that I could use to gauge amount of work needed? 

Thank you.

**Comment by azat** [comment]
>is there any support for VxWorks operating system?

I never heard about someone tries.

>If not, is it possible to port libevent to work on it?

I guess

>What would that require? Are there any resources that I could use to gauge amount of work needed?

You just need to obtain source of libevent from git and try to compile it under this OS (using cmake or autotools) and fix missing bits, if you will have some questions regardless some errors during confgiure/compile, just post it here

**Comment by wiktorinox** [comment]
Thank you for this information. 
Currently I'm only in process of initial investigation for a certain project. What you said should be sufficient for me to make correct decisions about use of this library.
Thanks a lot!
