### ISSUE TITLE
event_rpcgen.py shows "TypeError: super() argument 1 must be type, not classobj"

### ISSUE THREAD

**Issue by emmenlau** [libevent/libevent#1042]
With the latest master branch I get the following error on MSVC (Visual Studio 2019 latest and Visual Studio 2017)

```
FAILED: C:/libevent/test/regress.gen.c C:/libevent/test/regress.gen.h 
 cmd.exe /C "cd /D C:\libevent\test && C:\Python2\python.exe ../event_rpcgen.py --quiet regress.rpc"
 Traceback (most recent call last):
   File "../event_rpcgen.py", line 1925, in <module>
     sys.exit(main(argv=sys.argv[1:]))
   File "../event_rpcgen.py", line 1910, in main
     CommandLine(argv=argv).run()
   File "../event_rpcgen.py", line 1884, in run
     entities = Parse(factory, self.rpc_file)
   File "../event_rpcgen.py", line 1695, in Parse
     entities.extend(ProcessStruct(factory, data))
   File "../event_rpcgen.py", line 1591, in ProcessStruct
     structs.extend(ProcessOneEntry(factory, newstruct, entry))
   File "../event_rpcgen.py", line 1541, in ProcessOneEntry
     newentry = factory.EntryString(entry_type, name, tag)
   File "../event_rpcgen.py", line 1818, in EntryString
     return EntryString(entry_type, name, tag)
   File "../event_rpcgen.py", line 763, in __init__
     super(EntryString, self).__init__(ent_type, name, tag)
 TypeError: super() argument 1 must be type, not classobj
```

**Comment by azat** [comment]
@ngie-eign can you please take a look?

**Comment by ngie-eign** [comment]
This looks like Python 2 breakage around "old-style classes":
```
$ python2 --version; python3 --version
Python 2.7.18
Python 3.7.7
$ python2 ../event_rpcgen.py --quiet regress.rpc
Traceback (most recent call last):
  File "../event_rpcgen.py", line 1925, in <module>
    sys.exit(main(argv=sys.argv[1:]))
  File "../event_rpcgen.py", line 1910, in main
    CommandLine(argv=argv).run()
  File "../event_rpcgen.py", line 1884, in run
    entities = Parse(factory, self.rpc_file)
  File "../event_rpcgen.py", line 1695, in Parse
    entities.extend(ProcessStruct(factory, data))
  File "../event_rpcgen.py", line 1591, in ProcessStruct
    structs.extend(ProcessOneEntry(factory, newstruct, entry))
  File "../event_rpcgen.py", line 1541, in ProcessOneEntry
    newentry = factory.EntryString(entry_type, name, tag)
  File "../event_rpcgen.py", line 1818, in EntryString
    return EntryString(entry_type, name, tag)
  File "../event_rpcgen.py", line 763, in __init__
    super(EntryString, self).__init__(ent_type, name, tag)
TypeError: super() argument 1 must be type, not classobj
$ python3 ../event_rpcgen.py --quiet regress.rpc
```

**Comment by emmenlau** [comment]
Oh, is it better to use Python3? I can try that, just that I also build Qt and (at least until recently) it required Python2.

**Comment by ngie-eign** [comment]
> Oh, is it better to use Python3? I can try that, just that I also build Qt and (at least until recently) it required Python2.

It would work with python 3.

I opened a PR to address the issue: #1043.

**Comment by ngie-eign** [comment]
FWIW, Python 2 is effectively dead/EOLed upstream: https://www.python.org/doc/sunset-python-2/ . I would recommend making items like this WONTFIX items in the future.

This will require working with downstream distro maintainers, though, given that some are continuing to support python 2, but for all intents and purposes I think from a maintenance perspective, libevent should mark things WONTFIX.

**Comment by azat** [comment]
>I opened a PR to address the issue: #1043.

Thanks!

> FWIW, Python 2 is effectively dead/EOLed upstream: https://www.python.org/doc/sunset-python-2/ . I would recommend making items like this WONTFIX items in the future.

Yeah, sadly but I bet that libevent supports tons of EOL stuff, and not only python2

**Comment by ngie-eign** [comment]
> Yeah, sadly but I bet that libevent supports tons of EOL stuff, and not only python2

I understand this, but unless projects move to python 3, they won't be usable by downstream consumers.

Many python projects are ditching python 2 support, if they haven't already.
