### ISSUE TITLE
reuse of old fd bufferevent_enable failed

### ISSUE THREAD

**Issue by kimi8187** [libevent/libevent#1053]
I use libevent like below
thread A is for listening for new connection,
thread B is for data read and processing, 
so when connection is established, the corresponding descriptor fd will be send to thread B from thread A,
then thread B will use bufferevent to monitor the fd.  eg.fd=121

the problem is sometimes err occurred, so I need to close the fd in thread B,
while new connection request comes in immediately, so reuse the fd 121, in this case, when the thread B monitor the fd 121,bufferevent_enable failed with err Bad file descriptor.
It's a little strange, because the reuse of fd 121 need to close the fd first in thread B, and the printf shows as expected, 
But the error returned by bufferevent_enable is something like fd is closed in threadB after accept in thread A.
Please help me figure the reason, thanks a lot!

`[2020/07/14 07:13:05]threadB close fd=121

[2020/07/14 07:13:05]threadA accept new fd=121

[2020/07/14 07:13:05]threadB bufferevent_enable fd=121

[warn] Epoll ADD(1) on fd 121 failed. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none): Bad file descriptor

[2020/07/14 07:13:05]threadB bufferevent_enable fd 121 failed`

**Comment by azat** [comment]
>the problem is sometimes err occurred, so I need to close the fd in thread B,
>while new connection request comes in immediately, so reuse the fd 121, in this case, when the thread B monitor the fd 121,bufferevent_enable failed with err Bad file descriptor.

So this means that the fd already closed in thread B, who did this? Can you provide reproducer?

AFAICS bufferevent closes the descriptor only when all of the follow is true:
- in bufferevent_free
- when the refcount is zero
- BEV_OPT_CLOSE_ON_FREE isset

**Comment by kimi8187** [comment]
I want to close the scoket descriptor in my own proccess not in libevent.
even though I give bufferevent_socket_new param options value 0, the log still shows the descriptor was closed in libevent.
what confused me is bufferevent_free will check options, like you said, BEV_OPT_CLOSE_ON_FREE need to be set, then it will call  evutil_closesocket in be_ops->destruct. 
But I dont give the BEV_OPT_CLOSE_ON_FREE option, why descriptor still be closed by evutil_closesocket?

**Comment by kimi8187** [comment]
I recompile my project, with BEV_OPT_CLOSE_ON_FREE option canceld, the socket descriptor is no more closed by evutil_closesocket. maybe the option modify was not included when compile and work, now it works fine.
thanks for your reply.
