### ISSUE TITLE
How to write data to multiple 'evbuffer' elegantly and ensure atomicity?

### ISSUE THREAD

**Issue by ProjectDInitial** [libevent/libevent#1055]
I want to write data to the output buffer of multiple socket-bufferevent (broadcast) .If one of output buffer write failed, i can't remove the written data from the buffer that I have written data before.

The way I thought of is to create multiple 'evbuffer' and write data to it (evbuffer_add_reference()). then call the 'evbuffer_add_buffer()' move the data (underlying chain) to the output buffer of socket-bufferevent and free the created 'evbuffer'. but I don’t think it’s a good solution because that will generate a lot of small chunk（such as ptmalloc-fastbin). is there a better solution?

**Comment by azat** [comment]
Using temporary evbuffer should not create lot's of pressure on the allocator, since:
- evbuffer chains are aligned (512/1024)
- evbufffer_add_buffer() does not allocates memory for all data from src, it just moves chains

Also you can use evbuffer_add_buffer_reference()
