### ISSUE TITLE
Make create_tmpfile more durable in Windows

### ISSUE THREAD

**Issue by davinci26** [libevent/libevent#1058]
This is the current implementation of `create_tmpfile` in Windows, this implementation can into collisions and thus lead to a failed initialization in `event_base_new`

``` C++
static int
create_tmpfile(char tmpfile[MAX_PATH])
{
	char short_path[MAX_PATH] = {0};
	char long_path[MAX_PATH] = {0};
	char *tmp_file = tmpfile;

	GetTempPathA(MAX_PATH, short_path);
	GetLongPathNameA(short_path, long_path, MAX_PATH);
	if (!GetTempFileNameA(long_path, NULL, 0, tmp_file)) {
		event_warnx("GetTempFileName failed: %d", EVUTIL_SOCKET_ERROR());
		return -1;
	}
	return 0;
}
```

According to the documentation of msdn:

> Due to the algorithm used to generate file names, GetTempFileName can perform poorly when creating a large number of files with the same prefix. In such cases, it is recommended that you construct unique file names based on GUIDs.

Also this leads to an upper limit and competition in the number of temp files that we can generate since we compete with all the other process that create temp files with the default (`NULL`) prefix.

My approach would be to create a GUID and take the first 8-10 chars and use them as the prefix. This will increase the entropy sufficiently and make the function more durable. Any other approaches are also welcomed.

If you are accepting patches and you can give me a code review I can push a PR for it.

**Comment by azat** [comment]
>Due to the algorithm used to generate file names, GetTempFileName can perform poorly when creating a large number of files with the same prefix.

But this is about `GetTempFileName`, is it the same for `GetTempFileNameA`?

>My approach would be to create a GUID and take the first 8-10 chars and use them as the prefix. This will increase the entropy sufficiently and make the function more durable. Any other approaches are also welcomed.

Sounds pretty complex for this task, but I'm ok with it

>If you are accepting patches and you can give me a code review I can push a PR for it.

Sure, please go ahead!

>This is the current implementation of create_tmpfile in Windows, this implementation can into collisions and thus lead to a failed initialization in event_base_new

BTW do you really got this? Or this is just theoretical?

**Comment by davinci26** [comment]
> But this is about GetTempFileName, is it the same for GetTempFileNameA?

The Windows convention is that all the winapi function appear as both `Foo`, `FooA` and `FooW`. A is for Ansi strings as input and output and W is for Unicode input and output. `Foo` based on the system definitions for strings either points to `FooA` or `FooW` and is used to ensure portability between different systems. That's a really long answer to say that they are the same 😃

The upper limit is `65535` 

> BTW do you really got this? Or this is just theoretical? 

I got in a test environment when I was trying to repro a bug and I was running the initialization on while loop and after a point it started crashing with the following:

```
[warn] evsig_init_: socketpair: The file  exists.
[warn] GetTempFileName failed: 80
[warn] event_base_new_with_config: Unable to make base notifiable.
```

After this point this error was persistent and it got solved when I deleted the temp folder. Based on that I assumed that the issue was  `GetTempFileName` failing

**Comment by azat** [comment]
>That's a really long answer to say that they are the same

Ok, thanks! (I like long answers)

>After this point this error was persistent and it got solved when I deleted the temp folder. Based on that I assumed that the issue was GetTempFileName failing

Looks like it is. Ok, waiting for the PR (if you will add a test that will be great!)

**Comment by wrowe** [comment]
Irrespective of how the random name is generated, wouldn't it make more sense to implement this as an mkstemp style function returning the created file handle, and trap and retry with a fresh name on create file failed?

**Comment by davinci26** [comment]
There are two cases that can cause the function to fail:

1. We are out of tmp-xxxxx file names in temp folder in which case retrying wont help
2. There is a TOCTU race in which two processes are trying to create a file tmp-12345 and they both check that this file is available and one fails.

I think that adding a random prefix xxxxxx-tmp-xxxxxxxx where the first random bytes are selected by a random GUID that is specified at random will make any collisions really unlikely. Do you have any edge case in mind that retrying would help us?

Also it will speed up the code by a lot since the function iterates through all the files in the temp folder to makes there is no collision.

**Comment by ploxiln** [comment]
I think you could get 4 random bytes with `evutil_secure_rng_get_bytes()`, convert that to 8 hex chars, and use that as the prefix, to make collisions extremely unlikely.

**Comment by wrowe** [comment]
> I think you could get 4 random bytes with `evutil_secure_rng_get_bytes()`

A typical test suite executes 10's of thousands or greater order of magnitudes more test cases. It's highly improbable 2^32 is sufficient.

**Comment by ploxiln** [comment]
Simultaneously, though? And with the incrementing suffix, a couple of collisions would be just fine. Currently, libevent uses 1 prefix (zero length), 4 billion possible prefixes would be pretty big improvement (and also relatively efficient in both computation and path length, compared to a UUID).

**Comment by ploxiln** [comment]
(with 32 random bits, and 10,000 simultaneous tmpfiles, there is a 1% chance of collision. which incrementing suffix makes just fine. I think the 10,000 is unrealistic though)

**Comment by ploxiln** [comment]
> My approach would be to create a GUID and take the first 8-10 chars and use them as the prefix.

in terms of randomness, that is equivalent to my suggestion, just with the extra step of creating a GUID in the middle

**Comment by wrowe** [comment]
I suspect what we are running into here is the entropy seed, so adding an additional random element will only be effective if the initial state is sufficiently random. Otherwise, collisions are expected even in the face of a couple sources.

**Comment by ploxiln** [comment]
It actually doesn't use any random value, currently:

```
UINT GetTempFileNameA(
  LPCSTR lpPathName,
  LPCSTR lpPrefixString,
  UINT   uUnique,
  LPSTR  lpTempFileName
);
```

> If uUnique is zero, the function attempts to form a unique file name using the current system time. If the file already exists, the number is increased by one and the functions tests if this file already exists. This continues until a unique filename is found; the function creates a file by that name and closes it. Note that the function does not attempt to verify the uniqueness of the file name when uUnique is nonzero.

(libevent is currently using `lpPrefixString=NULL` and `uUnique=0`)

**Comment by ploxiln** [comment]
... it turns out that the max prefix length is 3 characters:

> lpPrefixString: The null-terminated prefix string. The function uses up to the first three characters of this string as the prefix of the file name. This string must consist of characters in the OEM-defined character set.

**Comment by wrowe** [comment]
Still, base 64 encoded that's still 18 more bits of entropy. Might prove sufficient.

**Comment by davinci26** [comment]
I think that they issue is that libevent competes with other programs creating temp files with the default configuration.

This is way I think even a tiny bit of entropy would have really good results.

**Comment by ploxiln** [comment]
Agreed and agreed, but in my attempt I used base32, because windows filesystems are case-insensitive, and some symbols are not allowed (e.g. `:`, '<', '>', '*', '|') so I think it may not be possible to come up with 64 different ascii chars for this.

**Comment by wrowe** [comment]
I agree, we can't get 2^6/char without wide char names (which is possible but not trivial.) What about using DEC RAD-050 (MOD-40) encoding? Three chars, even :) That would be a good place to start.
