### ISSUE TITLE
Build fails on Ubuntu 16.04 LTS due to missing net_sockets.h in libmbedtls-dev

### ISSUE THREAD

**Issue by glitsj16** [libevent/libevent#1059]
Hi, I noticed that a [recent mbedtls commit](https://github.com/libevent/libevent/commit/b28effa95082e468340cc13d274d3a2ea205c174) broke building libevent from git master on Ubuntu 16.04 LTS:

```
$ git clone https://github.com/libevent/libevent.git
$ cd libevent
$ ./autogen.sh
$ ./configure
$ make
[...]
  CC       libevent_mbedtls_la-bufferevent_mbedtls.lo
bufferevent_mbedtls.c:28:10: fatal error: mbedtls/net_sockets.h: No such file or directory
 #include <mbedtls/net_sockets.h>
                 ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [libevent_mbedtls_la-bufferevent_mbedtls.lo] Error 1
make: *** [all] Error 2
Makefile:1926: recipe for target 'libevent_mbedtls_la-bufferevent_mbedtls.lo' failed
make[1]: Leaving directory '/tmp/bz/libevent'
Makefile:1411: recipe for target 'all' failed
make  install-am
make[1]: Entering directory '/tmp/bz/libevent'
  CC       libevent_mbedtls_la-bufferevent_mbedtls.lo
bufferevent_mbedtls.c:28:10: fatal error: mbedtls/net_sockets.h: No such file or directory
 #include <mbedtls/net_sockets.h>
                 ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1926: recipe for target 'libevent_mbedtls_la-bufferevent_mbedtls.lo' failed
make[1]: *** [libevent_mbedtls_la-bufferevent_mbedtls.lo] Error 1
make[1]: Leaving directory '/tmp/bz/libevent'
Makefile:2933: recipe for target 'install' failed
make: *** [install] Error 2
```

```
$ apt-cache policy libmbedtls-dev
libmbedtls-dev:
  Installed: 2.2.1-2ubuntu0.3
  Candidate: 2.2.1-2ubuntu0.3
  Version table:
 *** 2.2.1-2ubuntu0.3 500
        500 http://mirrors.digitalocean.com/ubuntu xenial-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     2.2.1-2 500
        500 http://mirrors.digitalocean.com/ubuntu xenial/universe amd64 Packages
```

Looking at the [libmbedtls-dev package file list](https://packages.ubuntu.com/xenial/amd64/libmbedtls-dev/filelist) confirms the Xenial version does _not_ contain `net_sockets.h`. For now I have used the --disable-mbedtls flag as a workaround. Considering 16.04 is still officially supported, I wonder if/where this should be reported. Just wanted to file this FYI here so users are aware of it.

**Comment by azat** [comment]
>I wonder if/where this should be reported.

Definitely should, thank you!

@okhowang can you take a look?

**Comment by azat** [comment]
>bufferevent_mbedtls.c:28:10: fatal error: mbedtls/net_sockets.h: No such file or directory
> #include <mbedtls/net_sockets.h>
>                 ^~~~~~~~~~~~~~~~~~~~~~~

FWIW I saw this issues on CI too

**Comment by okhowang** [comment]
In old version of mbedtls, `mbedtls_net_context` is located in `mbedtls/net.h`.
but we use newer version, so  `mbedtls_net_context` is located in  `mbedtls/net_sockets.h`.
currently(mbedtls 2.23) `mbedtls/net.h` is usable without `MBEDTLS_DEPRECATED_REMOVED` macro defined.(which is default undefined)

maybe we should add some header test in cmake/autotools for this case?
or use `mbedtls/net.h` directly?

**Comment by azat** [comment]
>In old version of mbedtls, mbedtls_net_context is located in mbedtls/net.h.

How old is it? It is better to support it too, let's add `mbedtls-compact.h` and hide everything here

**Comment by okhowang** [comment]
`mbedtls/net-sockets.h` was created in [2016](https://github.com/ARMmbed/mbedtls/commit/788aa4a81214fa1d13b723e63a1e5b728b614771#diff-e0582cb7dfadc52de4e326236bc44f9d)
from mbedtls [2.4](https://tls.mbed.org/tech-updates/releases/mbedtls-2.4.0-2.1.6-and-1.3.18-released)

I will make an PR to fix it.
