### ISSUE TITLE
Hang in the evmap_io_active_ function

### ISSUE THREAD

**Issue by chen-honggang** [libevent/libevent#1066]
During use, it was found that the EV_READ event has not been triggered. 
After tracking, it was found that it was hangs in the evmap_io_active_ function. ctx->events formed a circular linked list, resulting in an endless loop.
version: libevent-2.1.11-stable

**Comment by azat** [comment]
>After tracking, it was found that it was hangs in the evmap_io_active_ function. ctx->events formed a circular linked list, resulting in an endless loop.

Please answer the following questions:
- do you have threads in your program? if so, have you enabled threads support? (`evthread_use_ptheads()` if you have pthreads + `BEV_OPT_THREADSAFE`/`LEV_OPT_THREADSAFE` if you use buffervents/listeners)
- you don't use event_assign on already added events, right? (you can check this with `event_enable_debug_mode()`)

**Comment by chen-honggang** [comment]
Thank you very much. I do have other threads to call the event_add(), and add evthread_use_ptheads() to solve the problem.
