### ISSUE TITLE
event_base_loop returns wrong value

### ISSUE THREAD

**Issue by khou2020** [libevent/libevent#1067]
According to the manual (http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/event_8h.html#a76e311cff042dab77125e309315a0617),  event_base_loop should return 1 when there is no pending events.

My calls to event_base_loop (base, EVLOOP_ONCE | EVLOOP_NONBLOCK) always returns 0, but non of my event call back function is called.

I reproduced this by replacing the event_base_dispatch call at event_read_fifo.c:151 with:
	while (1) {
		int ret;
		ret = event_base_loop(base, EVLOOP_ONCE | EVLOOP_NONBLOCK);
		if (ret == 1) {
			break;
		}
	}
Since there is no one writing to the fifo, event_base_loop should returns 1. However, it always returns 0.

**Comment by azat** [comment]
>or 1 if we exited because no events were pending or active.

pending - is the events being watched, IOW it will return 1 only if you don't have any events registered in this event_base

**Comment by khou2020** [comment]
So there is no way to tell if any even handler got ran during the event_base_loop call?

**Comment by azat** [comment]
0 return value
