### ISSUE TITLE
arc4random - return code from getrandom not handled correctly

### ISSUE THREAD

**Issue by ggarvey1024** [libevent/libevent#1068]
The return code from getrandom() is (-1) on failure and so is not detected by the existing code. I suspect that is why the additional code about any_set was needed.

diff --git a/arc4random.c b/arc4random.c
index 8729f6b..9a00ea2 100644
--- a/arc4random.c
+++ b/arc4random.c
@@ -176,25 +176,14 @@ static int
 arc4_seed_getrandom(void)
 {
        unsigned char buf[ADD_ENTROPY];
-       size_t len, n;
-       unsigned i;
-       int any_set;
-
-       memset(buf, 0, sizeof(buf));
+       size_t len;
+       ssize_t n = 0;
 
        for (len = 0; len < sizeof(buf); len += n) {
-               n = sizeof(buf) - len;
-
-               if (0 == getrandom(&buf[len], n, 0))
+               n = getrandom(&buf[len], sizeof(buf) - len, 0);
+               if (n < 0)
                        return -1;
        }
-       /* make sure that the buffer actually got set. */
-       for (i=0,any_set=0; i<sizeof(buf); ++i) {
-               any_set |= buf[i];
-       }
-       if (!any_set)
-               return -1;
-
        arc4_addrandom(buf, sizeof(buf));
        evutil_memclear_(buf, sizeof(buf));
        return 0;

**Comment by ggarvey1024** [comment]
[Issue1068-Handle-return-value-from-getrandom.txt](https://github.com/libevent/libevent/files/5011051/Issue1068-Handle-return-value-from-getrandom.txt)

**Comment by ploxiln** [comment]
Try using "fenced code blocks" when including code samples, terminal output, etc in a github issue or comment: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

For convenience, here is your above patch, in a fenced code block:

```diff
From ad3812b6b4b03ffb59190d25ac7c94cdb39807d5 Mon Sep 17 00:00:00 2001
From: Gerry Garvey <ggarvey@gmx.com>
Date: Sat, 1 Aug 2020 14:05:39 +0100
Subject: Handle return value from getrandom()

---
 arc4random.c | 19 ++++---------------
 1 file changed, 4 insertions(+), 15 deletions(-)

diff --git a/arc4random.c b/arc4random.c
index 8729f6b..9a00ea2 100644
--- a/arc4random.c
+++ b/arc4random.c
@@ -176,25 +176,14 @@ static int
 arc4_seed_getrandom(void)
 {
 	unsigned char buf[ADD_ENTROPY];
-	size_t len, n;
-	unsigned i;
-	int any_set;
-
-	memset(buf, 0, sizeof(buf));
+	size_t len;
+	ssize_t n = 0;
 
 	for (len = 0; len < sizeof(buf); len += n) {
-		n = sizeof(buf) - len;
-
-		if (0 == getrandom(&buf[len], n, 0))
+		n = getrandom(&buf[len], sizeof(buf) - len, 0);
+		if (n < 0)
 			return -1;
 	}
-	/* make sure that the buffer actually got set. */
-	for (i=0,any_set=0; i<sizeof(buf); ++i) {
-		any_set |= buf[i];
-	}
-	if (!any_set)
-		return -1;
-
 	arc4_addrandom(buf, sizeof(buf));
 	evutil_memclear_(buf, sizeof(buf));
 	return 0;
-- 
2.25.4
```

For for a suggested diff/patch in particular, you can open a new pull-request :)

**Comment by ploxiln** [comment]
I went ahead and opened the pull-request on your behalf. This helps by running the continuous-integration test suite and such. See https://github.com/libevent/libevent/pull/1070

**Comment by azat** [comment]
@ggarvey1024 @ploxiln thanks, the patch applied!
