### ISSUE TITLE
arc4random - WinCrypt (CryptGenRandom) is deprecated

### ISSUE THREAD

**Issue by ggarvey1024** [libevent/libevent#1069]
The Windows API call CryptGenRandom is deprecated and has been replaced by BCryptGenRandom

**Comment by ggarvey1024** [comment]
[Issue1069-Convert-from-WinCrypt-to-Windows-BCrypt.txt](https://github.com/libevent/libevent/files/5011070/Issue1069-Convert-from-WinCrypt-to-Windows-BCrypt.txt)

**Comment by azat** [comment]
CI - 138a408c771c21668bcc605c2df00d0384d476d8
