### ISSUE TITLE
./configure fails on macOS for 2.1.12-stable

### ISSUE THREAD

**Issue by mattias-lidman** [libevent/libevent#1072]
On macOS Catalina (10.15.6) ./configure fails with:

> configure: error: openssl is a must but can not be found. You should add the directory containing `openssl.pc' to the `PKG_CONFIG_PATH' environment variable, or set `CFLAGS' and `LDFLAGS' directly for openssl, or use `--disable-openssl' to disable support for openssl encryption

2.1.11-stable, on the other hand, configures, builds, and installs correctly. I don't need 2.1.12 myself, just reporting for awareness since there doesn't seem to be an open issue.

**Comment by ploxiln** [comment]
I think this is intentional, to ensure that the person building libevent is aware that openssl support is not enabled (by forcing them to specify `--disable-openssl`): https://github.com/libevent/libevent/pull/921

In libevent-2.1.11 it would relatively quietly skip openssl:

```
...
checking for pkg-config... /usr/local/bin/pkg-config
checking if pkg-config is at least version 0.15.0... yes
checking for library containing SSL_new... no
checking for library containing SSL_new... no
checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
...
```

(but in the linked PR it was simply changed to print that explanation and abort)

**Comment by mattias-lidman** [comment]
I see -- thanks.

What is the behavior with OpenSSL disabled? Does it mean certain features are just not working, or is it potentially a silent security risk by falling back to unencrypted?

**Comment by ploxiln** [comment]
Missing openssl support won't cause any run-time fall-back, it'll cause compile or link errors when building an application that uses libevent and depends on those features or bits.

**Comment by ploxiln** [comment]
(So the motivation may have been just to avoid lots of varied bug reports and confusion of the form "why does this thing I'm trying to compile fail due to libevent?" with the root cause that libevent ./configure could not find openssl headers/libs.)

**Comment by mattias-lidman** [comment]
Makes sense -- I figured as much, but good to have confirmation. I'll close the issue since apparently as is well.
