### ISSUE TITLE
event_base_new fails on Windows without additional info

### ISSUE THREAD

**Issue by davinci26** [libevent/libevent#1076]
Hey folks,

I am observing that `event_base_new` is failing on Windows sometimes but I see any more information on why is this the case.

I am enabling logs with `event_enable_debug_logging(EVENT_DBG_ALL);` but the only thing I see is the following:

```
[warn] event_base_new_with_config: Unable to make base notifiable.
[debug] event_base_free_: 0 events freed
```

What would be the best way to debug that?

**Comment by azat** [comment]
Can you post output of [strace-like](https://stackoverflow.com/a/12861291/328260) tool?

**Comment by davinci26** [comment]
Awesome I did not know about this tool. I will take a stab at debugging it with this tool!

**Comment by davinci26** [comment]
@azat I am not able to get a repro directly from cmd/ps (I was facing the problem when running from within MSYS). 

Feel free to close the issue and I can re-open it if I can collect logs and have some more information.

**Comment by azat** [comment]
Ok, in general looks like some limits reached, but I don't know how windows works, so I don't know which limits exists there
