### ISSUE TITLE
/usr/bin/ld: /usr/local/lib/libssl.a(ssl_lib.o): relocation R_X86_64_PC32 against symbol `ssl_undefined_function' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by pz9042** [libevent/libevent#1077]
when execute make, the error occur, libevent version is 2.1.12 ,and openssl version is OpenSSL 1.1.1,operating system is ubuntu 18,kernal is 5.4.0-42-generic. gcc version is  7.5.0

**Comment by azat** [comment]
You need to compile openssl with -fPIC
