### ISSUE TITLE
when server dose not send "server hello", and server reboot, but client dose not retry connection!

### ISSUE THREAD

**Issue by lan1120** [libevent/libevent#1082]
The client and server establish a TCP connection, then client send a "client hello" and receive an ACK from server.  Then server reboot, but client dose not retry connection, and old TCP connection is existing. What can I do to get the client to reestablish the connection?

**Comment by azat** [comment]
Take a look at [SO_KEEPALIVE](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html)

**Comment by lan1120** [comment]
It doesn't seem to solve my problem. The server does not respond to the Client Hello message from the client due to an exception, but can respond to my heartbeat message. As a result, the SSL connection cannot be created and incorrect connection information cannot be obtained. The server requires me to disconnect and reconnect, but I do not know how to disconnect and when to disconnect. 
![image](https://user-images.githubusercontent.com/24563500/90229961-5c428c00-de4b-11ea-8fff-2f2cf7ab6ac9.png)

**Comment by azat** [comment]
>The server does not respond to the Client Hello message from the client due to an exception

This is a another issue, initially you wrote "Then server reboot, but client dose not retry connection, and old TCP connection is existing"

> but can respond to my heartbeat message

Yes, because the connection is still exists and valid

> The server requires me to disconnect and reconnect, but I do not know how to disconnect and when to disconnect.

If you don't send any packets how do you want to detect that the connection should be closed? If you don't want to bother with sending packet (or closing the socket in the server), than you can set timeout and done with it

**Comment by lan1120** [comment]
I set the error callback. (bufferevent_setcb(bev, ReadCb, NULL, EventCb, conn);) , but the error callback timeout cannot be set.

**Comment by lan1120** [comment]
oh，I know how to fix it.  Actually, I don't need ReadCb. I can set ReadCb timeout, and clear ReadCb timeout when I get an EventCb.

**Comment by lan1120** [comment]
thank you

**Comment by lan1120** [comment]
I understand, right?

**Comment by azat** [comment]
>oh，I know how to fix it. Actually, I don't need ReadCb. I can set ReadCb timeout, and clear ReadCb timeout when I get an EventCb.

I don't understand this, can you elaborate? (plain C code is preferable)

**Comment by lan1120** [comment]
`static void EventCb(struct bufferevent *bev, short events, void *arg)
{
    //No matter what event, cancel timeout
    bufferevent_set_timeouts(bev, NULL, NULL);

    if (events & BEV_EVENT_CONNECTED) {
        // OK
    } else {
        // ERROR
        // Sets the reconnection flag.
    }
}

static void ReadCb(struct bufferevent *bev, void *arg)
{
    // nothing to do
    return;
}

int CreateSslConnection(stcp_async_ctx *ctx, char *ip, unsigned short port)
{
    struct bufferevent *bev = NULL;
    struct bufferevent *bev = NULL;
    // Initialize SSL connection
    bufferevent_setcb(bev, ReadCb, NULL, EventCb, connInfo);
	
    // Set ReadCb timeout
    struct timeval timeout = {30, 0};
    bufferevent_set_timeouts(bev, &timeout, NULL);

    (void)bufferevent_enable(bev, EV_READ | EV_WRITE);
}`

**Comment by lan1120** [comment]
static void EventCb(struct bufferevent *bev, short events, void *arg)
{
    //No matter what event, cancel timeout
    bufferevent_set_timeouts(bev, NULL, NULL);

    if (events & BEV_EVENT_CONNECTED) {
        // OK
    } else {
        // ERROR
        // Sets the reconnection flag.
    }
}

static void ReadCb(struct bufferevent *bev, void *arg)
{
    // nothing to do
    return;
}

int CreateSslConnection(stcp_async_ctx *ctx, char *ip, unsigned short port)
{
    struct bufferevent *bev = NULL;
    struct bufferevent *bev = NULL;
    // Initialize SSL connection
    bufferevent_setcb(bev, ReadCb, NULL, EventCb, connInfo);
	
    // Set ReadCb timeout
    struct timeval timeout = {30, 0};
    bufferevent_set_timeouts(bev, &timeout, NULL);

    (void)bufferevent_enable(bev, EV_READ | EV_WRITE);
}

**Comment by azat** [comment]
Yes, looks ok (although it is better to set write timeout too)
