### ISSUE TITLE
run .configure file  occurs a error

### ISSUE THREAD

**Issue by immortalChensm** [libevent/libevent#1088]
libevent version is 2.0.19 stable
![image](https://user-images.githubusercontent.com/35517798/92347666-616dc080-f103-11ea-98a9-252a928c0cfc.png)

**Comment by azat** [comment]
>libevent version is 2.0.19 stable

2.0.19 had been released 8 years ago, it is better to use at least 2.0.22, but I would recommend even 2.1.12
And also can you tell where did you get it? (archive)

> error: cannot find input file: test/Makefile.in

And the problem is not in `configure` but in:

>test/Makefile.am:22: error: using '$(top_srcdir)' in TESTS is currently broken: '$(top_srcdir)/test/test.sh'

You can just remove that line

P.S. please next time post plain text
