### ISSUE TITLE
EV_READ keeps triggering, but read nothing with version 2.1.11-stable

### ISSUE THREAD

**Issue by yozol** [libevent/libevent#1092]
Hi All.
I use libevent-2.1.11-stable in a network server application. When a client transfers all the data without closing socket, whose communication socket on the server will be kept triggered EV_READ, however the server reads nothing from the socket. EV_ READ triggers very fast, averaging 16 times per millisecond. I'm confused with this phenomena, can anyone help me? Thans a lot.

**Comment by azat** [comment]
Does the server reads everything from that socket? If no, then this is the default behavior, if you need to trigger the even only when new data arrives, take a look at [EV_ET](https://libevent.org/doc/event_8h.html#a01084abbcdd3a58b4068359548a3ea71) (edge-triggered events)

**Comment by bschlinker** [comment]
EV_READ will be triggered if the socket has an error and/or a message is in the socket error queue.

**Comment by azat** [comment]
@yozol can you provide some details?

**Comment by yozol** [comment]
UNIX socket is used for communication between parent and child processes, and this socket is managed by libevent. As long as the child process crashes, the parent process will continue to trigger the read event set before, but calling read function gets nothing except returning negative.

**Comment by azat** [comment]
@yozol can you provide strace output for this case?

**Comment by azat** [comment]
And also it would be great if you can provide reproducer code (I guess it can be minimized to ~100 lines +-)
