### ISSUE TITLE
evhttp_parse_query's behaviour is not confirm standard

### ISSUE THREAD

**Issue by okhowang** [libevent/libevent#1093]
see https://url.spec.whatwg.org/#application/x-www-form-urlencoded
```c
int ret = evhttp_parse_query(”a=b&&c=d", &headers);
// ret should be zero
```
according to spec. we should ignore empty key-value pair silently.
> If bytes is the empty byte sequence, then continue.

**Comment by azat** [comment]
> int ret = evhttp_parse_query(”a=b&&c=d", &headers);
> // ret should be zero

Is [EVHTTP_URI_QUERY_NONCONFORMANT](https://libevent.org/doc/http_8h.html#a64c9b77846e83a6f3d45f4be4b7150de) what you want?

P.S. it is done under flag to avoid breaking compatibility (yes it was wrong before, but someone may depends on this)

**Comment by okhowang** [comment]
It's OK for me.
but `evhttp_parse_query_str_flags` exists on master branch currently.
Is there any plan to release?

**Comment by azat** [comment]
>Is there any plan to release?

Yes, always :)
Actually not a lot of work required to make a 2.2 release I guess (and there are some more or less major features, so that 2.2 can go out).

**Comment by azat** [comment]
Refs: #1094
