### ISSUE TITLE
2.1.12: devel man pages conflict with free(3)

### ISSUE THREAD

**Issue by kloczek** [libevent/libevent#1097]
Looks like it is not possible to use straight generated by doxygen devel man pages asm man3 man pages because conflict with free(3):
```
[root@barrel old]# dnf upgrade libevent\* -y
Last metadata expiration check: 0:05:10 ago on Tue 15 Sep 2020 21:33:40 BST.
Dependencies resolved.
========================================================================================================================================================================================================
 Package                                             Architecture                                Version                                                 Repository                                Size
========================================================================================================================================================================================================
Upgrading:
 libevent                                            x86_64                                      2.1.12-2.2.fc34                                         g2v                                      221 k
 libevent-devel                                      x86_64                                      2.1.12-2.2.fc34                                         g2v                                      305 k

Transaction Summary
========================================================================================================================================================================================================
Upgrade  2 Packages

Total size: 526 k
Downloading Packages:
[SKIPPED] libevent-2.1.12-2.2.fc34.x86_64.rpm: Already downloaded
[SKIPPED] libevent-devel-2.1.12-2.2.fc34.x86_64.rpm: Already downloaded
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/share/man/man3/free.3.gz from install of libevent-devel-2.1.12-2.2.fc34.x86_64 conflicts with file from package man-pages-5.08-2.fc34.noarch
```
IIRC doxygen allows specify name of the man pages file in which documentation will be stored.
Looking on:
```
# rpm -qpl libevent-devel-2.1.12-2.2.fc34.x86_64.rpm  | grep man3 | egrep -v "man3/evutil|man3/event|man3/evthread|man3/evtimer|man3/evtag|man3/evrpc|man3/evsignal|man3/evhttp|man3/evdns|man3/evbuffer|man3/ev_|man3/bufferevent|man3/EV|/man3/BEV|man3/DNS"
/usr/share/man/man3/HTTP_BADMETHOD.3.gz
/usr/share/man/man3/HTTP_BADREQUEST.3.gz
/usr/share/man/man3/HTTP_ENTITYTOOLARGE.3.gz
/usr/share/man/man3/HTTP_EXPECTATIONFAILED.3.gz
/usr/share/man/man3/HTTP_INTERNAL.3.gz
/usr/share/man/man3/HTTP_MOVEPERM.3.gz
/usr/share/man/man3/HTTP_MOVETEMP.3.gz
/usr/share/man/man3/HTTP_NOCONTENT.3.gz
/usr/share/man/man3/HTTP_NOTFOUND.3.gz
/usr/share/man/man3/HTTP_NOTIMPLEMENTED.3.gz
/usr/share/man/man3/HTTP_NOTMODIFIED.3.gz
/usr/share/man/man3/HTTP_OK.3.gz
/usr/share/man/man3/HTTP_SERVUNAVAIL.3.gz
/usr/share/man/man3/INPUT.3.gz
/usr/share/man/man3/LIBEVENT_VERSION.3.gz
/usr/share/man/man3/LIBEVENT_VERSION_NUMBER.3.gz
/usr/share/man/man3/OUTPUT.3.gz
/usr/share/man/man3/_EVENT_LOG_DEBUG.3.gz
/usr/share/man/man3/_EVENT_LOG_ERR.3.gz
/usr/share/man/man3/_EVENT_LOG_MSG.3.gz
/usr/share/man/man3/_EVENT_LOG_WARN.3.gz
/usr/share/man/man3/ai_addr.3.gz
/usr/share/man/man3/ai_addrlen.3.gz
/usr/share/man/man3/ai_canonname.3.gz
/usr/share/man/man3/ai_family.3.gz
/usr/share/man/man3/ai_flags.3.gz
/usr/share/man/man3/ai_next.3.gz
/usr/share/man/man3/ai_protocol.3.gz
/usr/share/man/man3/ai_socktype.3.gz
/usr/share/man/man3/alloc.3.gz
/usr/share/man/man3/alloc_condition.3.gz
/usr/share/man/man3/buffer.h.3.gz
/usr/share/man/man3/buffer_compat.h.3.gz
/usr/share/man/man3/condition_api_version.3.gz
/usr/share/man/man3/deprecated.3.gz
/usr/share/man/man3/dns.h.3.gz
/usr/share/man/man3/dns_compat.h.3.gz
/usr/share/man/man3/encode_int.3.gz
/usr/share/man/man3/encode_int64.3.gz
/usr/share/man/man3/evuser_del.3.gz
/usr/share/man/man3/evuser_initialized.3.gz
/usr/share/man/man3/evuser_new.3.gz
/usr/share/man/man3/evuser_pending.3.gz
/usr/share/man/man3/evuser_trigger.3.gz
/usr/share/man/man3/free.3.gz
/usr/share/man/man3/free_condition.3.gz
/usr/share/man/man3/http.h.3.gz
/usr/share/man/man3/http_compat.h.3.gz
/usr/share/man/man3/internal_.3.gz
/usr/share/man/man3/iov_base.3.gz
/usr/share/man/man3/iov_len.3.gz
/usr/share/man/man3/libevent_global_shutdown.3.gz
/usr/share/man/man3/lock.3.gz
/usr/share/man/man3/lock_api_version.3.gz
/usr/share/man/man3/n_added.3.gz
/usr/share/man/man3/n_deleted.3.gz
/usr/share/man/man3/orig_size.3.gz
/usr/share/man/man3/pos.3.gz
/usr/share/man/man3/rpc.h.3.gz
/usr/share/man/man3/rpc_compat.h.3.gz
/usr/share/man/man3/signal_add.3.gz
/usr/share/man/man3/signal_condition.3.gz
/usr/share/man/man3/signal_del.3.gz
/usr/share/man/man3/signal_initialized.3.gz
/usr/share/man/man3/signal_pending.3.gz
/usr/share/man/man3/signal_set.3.gz
/usr/share/man/man3/supported_locktypes.3.gz
/usr/share/man/man3/tag.h.3.gz
/usr/share/man/man3/tag_compat.h.3.gz
/usr/share/man/man3/thread.h.3.gz
/usr/share/man/man3/timeout_add.3.gz
/usr/share/man/man3/timeout_del.3.gz
/usr/share/man/man3/timeout_initialized.3.gz
/usr/share/man/man3/timeout_pending.3.gz
/usr/share/man/man3/timeout_set.3.gz
/usr/share/man/man3/unlock.3.gz
/usr/share/man/man3/util.h.3.gz
/usr/share/man/man3/wait_condition.3.gz
```
I think that it may be more such conflicts.

**Comment by kloczek** [comment]
Second thought: if libevent really provides `free()` as public ABI symbol it may be as well some symbol clash with other libraries.

**Comment by azat** [comment]
>  file /usr/share/man/man3/free.3.gz from install of libevent-devel-2.1.12-2.2.fc34.x86_64 conflicts with file from package man-pages-5.08-2.fc34.noarch

libevent does not provide this man pages, this is done by the distro (looks like it shipped man pages for all used functions).

**Comment by kloczek** [comment]
Please try to configure source tree with `--enable-doxygen-man --enable-doxygen-doc` and check `ls doxygen/man/man3/free.3` command output.
Because in https://github.com/libevent/libevent/blob/master/doxygen.am#L22 it is:
```
man3_MANS = @DX_DOCDIR@/man/man3/*
```
it causes that after executing `install` target those man pages are installed in two places (in `@DX_DOCDIR@/man/man3/` and in `$(mandir)/man3' (what I've patches for myselfe by:
```
--- a/doxygen.am~       2020-09-14 20:20:51.000000000 +0100
+++ b/doxygen.am        2020-09-14 20:43:46.798120354 +0100
@@ -19,7 +19,7 @@

 if ENABLE_DOXYGEN_MAN
 # integrate doxygen with automake targets
-man3_MANS = @DX_DOCDIR@/man/man3/*
+man3_MANS = $(top_builddir)/doxygen/man/man3/*
 $(man3_MANS): doxygen-doc
 endif ENABLE_DOXYGEN_MAN
--- a/m4/ax_prog_doxygen.m4~    2020-09-14 20:45:04.000000000 +0100
+++ b/m4/ax_prog_doxygen.m4     2020-09-14 20:56:08.578139762 +0100
@@ -411,17 +411,6 @@

 "]],
 [[DX_SNIPPET_chm=""]])
-AS_IF([[test $DX_FLAG_man -eq 1]],
-[[DX_SNIPPET_man="## ------------------------------ ##
-## Rules specific for MAN output. ##
-## ------------------------------ ##
-
-DX_CLEAN_MAN = \$(DX_DOCDIR)/man]dnl
-m4_foreach([DX_i], [m4_shift(DX_loop)], [[\\
-               \$(DX_DOCDIR]DX_i[)/man]])[
-
-"]],
-[[DX_SNIPPET_man=""]])
 AS_IF([[test $DX_FLAG_rtf -eq 1]],
 [[DX_SNIPPET_rtf="## ------------------------------ ##
 ## Rules specific for RTF output. ##
```

**Comment by kloczek** [comment]
Anything except man pages should be just left in build tree and not installed  by `install` target allowing make decision package management software allowing to make decision what and where to install those files.

**Comment by kloczek** [comment]
Without above patch after `install` target you will end up with man pages installed in two directories.

**Comment by azat** [comment]
>Second thought: if libevent really provides free() as public ABI symbol it may be as well some symbol clash with other libraries.

Actually it does not, this is the field from one of the struct.

>Please try to configure source tree with --enable-doxygen-man --enable-doxygen-doc and check ls doxygen/man/man3/free.3 command output.

Thanks! (sorry for missing this)

>Anything except man pages should be just left in build tree and not installed by install target allowing make decision package management software allowing to make decision what and where to install those files.

Not sure that I'm following this, I guess you are saying that only "man pages related to libevent should be installed", agree
Can you verify the attached patch?

**Comment by kloczek** [comment]
Juste tested and 9b270c5 solves that conflict.
Thx.

However still it is not solved two times installing man pages (one time in `@DX_DOCDIR@/man/man3/` and second time in `$(mandir)/man3'.
> Not sure that I'm following this, I guess you are saying that only "man pages related to libevent should be installed"

Will give you example.
I have now almost 2.4k cleaned spec files based on Fedora (kind of base of my own distribution). Simple grep across all those spec files:
```
[tkloczko@barrel SPECS]$ grep do_not_install_some_doc.patch * | wc -l
183
```
For almost 200 packages I'm adding patches which removes installing documentation during `install` target because that documentation is meaningless from pot of end user, it is installed in wrong location or like now in case of libevent it installs exactly the same man pages in two locations. It is very annoying that in so many cases maintainers have kind of wrong impression and forces packages like me to take additional steps to not install some documentation files in sometimes very strange location which do not match to some base directories used by exact distribution. If those files would be just left in build tree situation would be way easier.
What I'm trying to tell is that except when is used `--enable-doxygen-man` in case all other `--enable-doxygen-<foo_format>' documentation should be only generated and left in build tree. I can guarantee you that would make job of any distributions packagers easier :)

**Comment by azat** [comment]
>However still it is not solved two times installing man pages (one time in @DX_DOCDIR@/man/man3/ and second time in `$(mandir)/man3'.

Indeed (the problem is that it is installed not into `$(mandir)` by default)

> It is very annoying that in so many cases maintainers have kind of wrong impression and forces packages like me to take additional steps to not install some documentation files in sometimes very strange location which do not match to some base directories used by exact distribution

I'm open to suggestions (and I'm appreciate for the feedback)

>What I'm trying to tell is that except when is used --enable-doxygen-man in case all other `--enable-doxygen-<foo_format>' documentation should be only generated and left in build tree. I can guarantee you that would make job of any distributions packagers easier :)

But in this case `man event.h` will not show any documentation (since it is not in the default search man path), so what's the point in such documentation?

**Comment by kloczek** [comment]
> But in this case man event.h will not show any documentation (since it is not in the default search man path), so what's the point in such documentation?

This why I wrote previously that better is choose some exact man pages names to generate by adding in comments some exact tokens :) 
I cannot help on choosing such names of the man pages because I'm not familiar with libevent API :/
What I can suggest is use some "name space for that header files like `libevent-<header_file>.h`. With that in shell prompt after typing `man linevent` and pressing two times tab thanks to bash/fish/zsh completion will be displayed all libevent man pages. This will allow as well completely avoid any man pages names clashes with other APIs documentations :)

**Comment by azat** [comment]
>What I can suggest is use some "name space for that header files like libevent-<header_file>.h. With that in shell prompt after typing man linevent and pressing two times tab thanks to bash/fish/zsh completion will be displayed all libevent man pages. This will allow as well completely avoid any man pages names clashes with other APIs documentations :)

Ok, I see, great idea, have same thoughts in 9b270c5e02e47d372ad53e773f98668890b33e9f

>Looks like we should add prefix for each of them...
>But let's see if there will be a problem.

**Comment by azat** [comment]
I've created separate issue for this - #1099

**Comment by kloczek** [comment]
I like that you are opened on that idea :)

I can tell you that in my distribution I'm putting all python module documentation generated using sphing not as html but as man pages with rename those man pages to `pthon-<module_name>`, Effect is a bit funny after type `man python` and press two times tab on my current system I see:
```
[tkloczko@barrel SPECS]$ man python
python3                             python-dulwich                      python-openstackdocstheme           python-py2pack                      python-wheel
python3.8                           python-evdev                        python-packaging                    python-pycodestyle                  python-wikipedia
python-bottle                       python-GitPython.tex                python-parso                        python-pyrad
python-cffi                         python-lazy-object-proxy            python-polib                        python-sphinxcontrib-programoutput
```
I've started tah only few weeks ago so still that list not so long but try to think how usefull it will be in final form :)
