### ISSUE TITLE
Add prefix for generated man pages

### ISSUE THREAD

**Issue by azat** [libevent/libevent#1099]
- avoid overlapping (since there is `util.h.3` page)
- will group everything under some prefix (`man libevent<TAB><TAB>` will show everything)

Refs: 9b270c5e02e47d372ad53e773f98668890b33e9f
Refs: #1097
Cc: @kloczek

**Comment by azat** [comment]
@ygj6 (as the initial author of this doxygen generations during build) unassign yourself if you don't have time for this

**Comment by kloczek** [comment]
FYI: Just in scase if you would need my help on testing somethin just like this time add @kloczek and the hash of the commit.
With exact hash it takes me few seconds to add that patch to my rpm spec files to add it o my build system and test it :)
Just kind of example with this patch:
```
[tkloczko@barrel SPECS]$ rpmbuild -bp libevent.spec --with check
warning: Downloading https://github.com/libevent/libevent//commit/9b270c5e.patch#/libevent-Generate-only-real-man-pages-with-doxygen-MAN_LINKS-NO.patch to /home/tkloczko/rpmbuild/SOURCES/libevent-Generate-only-real-man-pages-with-doxygen-MAN_LINKS-NO.patch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.7YQXOK
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf libevent-2.1.12-stable
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/libevent-2.1.12-stable.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libevent-2.1.12-stable
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libevent-nonettests.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libevent-shebangs.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libevent-build-add-doxygen-to-all.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libevent-build-do-not-try-install-doxygen-man-pages-if-they-were-not.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libevent-fix_man3_MANS.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libevent-do_not_install_some_doc.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libevent-Generate-only-real-man-pages-with-doxygen-MAN_LINKS-NO.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ RPM_EC=0
++ jobs -p
+ exit 0
```

**Comment by azat** [comment]
>FYI: Just in scase if you would need my help on testing somethin just like this time add @kloczek and the hash of the commit.

You can check the referenced (21b9169) patch, thank you in advance!

**Comment by kloczek** [comment]
Tested and it works.
Just a suggestion: I think that more convenient would be use libevent_ prefix instead le_.
With only two characters it would be harder to guess under what kind of name are libevent lvl 3 man pages.
Longer name with bash/fix/zsh tab competition should not be a problem :)

**Comment by azat** [comment]
>Longer name with bash/fix/zsh tab competition should not be a problem :)

Hm, agree, changed
