### ISSUE TITLE
[RFC] listen on errors but not read

### ISSUE THREAD

**Issue by davidsteinsland** [libevent/libevent#111]
is it possible to use `bufferevent` to only listen to errors? That is, I have my own layer around sockets and would prefer to read/write through those instead of using the bufferevents. I'd still like to be able to catch any errors on the file descriptors though.

Is this possible?

**Comment by ellzey** [comment]
>  have my own layer around sockets 

Is it a layer around libevent?

**Comment by ellzey** [comment]
Oh crap, I forgot I already researched this topic a long time ago.

Potential new flags for turning off read but still get errors.


epoll:
```
 EPOLLRDHUP works without EPOLLIN
```
kqueue:
```
EV_SET(&event, infd, EVFILT_READ, EV_ADD|EV_EOF, NOTE_LOWAT, INTMAX_MAX, NULL);
```
That looks like a hack, but it waits for INTMAX_MAX bytes before triggering the event, but still triggers EV_EOF

Would be interesting to look into a (kqueue and epoll) specific flag like "EV_READ_ERROR".

```C
bufferevent_disable(EV_READ);
bufferevent_enable(EV_READ_ERROR);
```

**Comment by azat** [comment]
> Potential new flags for turning off read but still get errors.

Some backends will not support this, and there will be all
why-this-does-not-work questions, though we can have workaround for
others, but does it worth it?

**Comment by ellzey** [comment]
> Some backends will not support this

Like when I said

>>  a (kqueue and epoll) specific flag

Also whats this I hear all about `the various flags specific to event mechanism?

> There will be all why-this-does-not-work questions,

We always get those; just document it and refer it to the libevent-book link.

> but does it worth it?

Yes.. The ability to have read disabled and still get socket errors would help every proxy developer in the world (53242423423.32432E) to be exact.

Joking aside, yes, this is definitely worth it for developers who are constantly unsetting the read side of the descriptor, only to immediately error after enabling.

**Comment by ellzey** [comment]
Replacing and closing this ticket with https://github.com/libevent/libevent/issues/345
