### ISSUE TITLE
why just TAILQ_REMOVE req after failure of evhttp_connection_connect_ in evhttp_make_request without doing evhttp_request_free_auto

### ISSUE THREAD

**Issue by bbqz007** [libevent/libevent#1113]
```c++
/* If the connection object is not connected; make it so */
	if (!evhttp_connected(evcon)) {
		int res = evhttp_connection_connect_(evcon);
		/* evhttp_connection_fail_(), which is called through
		 * evhttp_connection_connect_(), assumes that req lies in
		 * evcon->requests.  Thus, enqueue the request in advance and
		 * remove it in the error case. */
		if (res != 0)
			TAILQ_REMOVE(&evcon->requests, req, next);

		return (res);
	}
```
evhttp_connection_fail_() has been called through evhttp_connection_connect_() when failure.

evhttp_connection_fail_() took care of the TAILQ_FIRST of evcon->requests, and evhttp_request_free_ which called TAILQ_REMOVE and evhttp_request_free_auto.

there may be two problems, 

first,  if the current req passed to evhttp_make_request() was the TAILQ_FIRST of evcon->requests, could it be accessed and TAILQ_REMOVE after being freed by evhttp_connection_fail_?

second, if  the current req passed to evhttp_make_request() was **not** the TAILQ_FIRST of evcon->requests, should i take care of it for freeing, rather than just TAILQ_REMOVE from evcon->requests.

and before evhttp_connection_connect_() in evhttp_make_request() , the req would be freed before returning -1 in failure case.

there is another problem, if it was a not user owned req, i dont know wether it had been freed or not when evhttp_make_request() returns not 0.

**Comment by ploxiln** [comment]
evhttp_make_request() won't return an error if you pass valid arguments. You'll get the error in your callback, later, asynchronously. In this case, you do not need to manually free the request, it is handled automatically after your callback. I have code like this, which I've tested with valgrind under a variety of conditions:

```c
static void reauth_response(struct evhttp_request *req, void *arg)
{
	int response_code = 0;
	const char *uri = "";
	struct evbuffer *bodybuf = NULL;

	if (req) {
		response_code = evhttp_request_get_response_code(req);
		uri = evhttp_request_get_uri(req);
		bodybuf = evhttp_request_get_input_buffer(req);
	}
	if (!req || response_code == 0) {
		log_error("failure to make reauth request ...");
		return;
	}
	if (response_code != 200) {
		log_error("bad response code=%d uri=%s", response_code, uri);
		return;
	}
	// process 200 response

	// after end of callback, req is automatically freed, along with uri and bufbody
}
```

So, I assume you ran into a problem with your code. Can you post a sample of your code, which ran into the problem?

**Comment by azat** [comment]
Closing, due to lack of reply, feel free to reopen
