### ISSUE TITLE
calling event_assign in event_callback_fn causes other socket miss EV_READ react event.

### ISSUE THREAD

**Issue by bbqz007** [libevent/libevent#1116]
i wrote a simple sample of echo server using libevent.
https://github.com/bbqz007/zhelper/blob/master/event/zamples/libevent-reactor.cpp
when i use curl to make 4 requests in background in parrallel, there are two connected sockets miss EV_READ react event, and the event_callback_fn is not fired. every 4 requests, 2 ok and 2 miss EV_READ. if requests are made one by one, 1 ok and 1 miss EV_READ and repeat along.

the sample use main thread to run event loop and do these things：
1. event_assign to EV_READ|EV_PERSIST|EV_ET.
2. EV_READ callback, and read data into buffer, and write. if writing would block, event_assign to EV_READ|EV_WRITE|EV_PERSIST|EV_ET.
3. EV_WRITE callback, write data.  event_assign to EV_READ|EV_PERSIST|EV_ET and mask EV_WRITE until all data has been written.
4. close connection when written data is done.

i wrote samples using libuv and libev, do the same things, just apis are different.  in libuv and libev cases, they work fine. except in libevent case.
https://github.com/bbqz007/zhelper/blob/master/event/zamples/libev-reactor.cpp
https://github.com/bbqz007/zhelper/blob/master/event/zamples/libuv-reactor.cpp

when i just use event_assign only once and not use it change any thing, it works fine.

i doubt if event_assign can not be used to change things more than the first time, and there are no document indicating this situation.

my sample can be made by:
```bash
g++ -std=c++11 libevent-reactor.cpp -levent
g++ -D NO_EVENT_ASSIGN_ISSUE -std=c++11 libevent-reactor.cpp -levent
```
the first command makes the issue version.
the second command makes the fine version.
test command:
```bash
curl http://127.0.0.1:12347 & curl http://127.0.0.1:12347 & curl http://127.0.0.1:12347 & curl http://127.0.0.1:12347 &
```
in linux platform.

**Comment by azat** [comment]
You have an issue in your code, here is worked example - https://gist.github.com/azat/bbfffdddb042aa447412f93d0d821263

The problem is that you are calling `event_assign()` on already added event, and this is illegal, you can enable debug mode to catch such errors (`event_enable_debug_mode()`)
So just add `event_del` before the nested `change_poll` calls.

**Comment by bbqz007** [comment]
```c++
/***
...
  Note that it is NOT safe to call this function on an event that is
  active or pending.  Doing so WILL corrupt internal data structures in
  Libevent, and lead to strange, hard-to-diagnose bugs.  You _can_ use
  event_assign to change an existing event, but only if it is not active
  or pending!
...
*/
EVENT2_EXPORT_SYMBOL
int event_assign(struct event *ev, struct event_base *base, evutil_socket_t fd, short events, event_callback_fn callback, void *callback_arg);
```
