### ISSUE TITLE
code standards

### ISSUE THREAD

**Issue by ColdV** [libevent/libevent#1118]
i'm a noob coder,  i wann knew, why dont judge null point in function when has pointer param? thanks

**Comment by azat** [comment]
I'm not sure that i'm following, can you give an example in C? And is it libevent related?

**Comment by ColdV** [comment]
such as in libevent's function "event_base_loop", before use "event_base" pointer, why dont judge null?  maybe not libevent related, but i wanna know why can be designed like this, in my C's understanding，before use pointer must judge.

**Comment by azat** [comment]
What do you mean by "dont judge null"? Check against NULL, i.e. `if (event_base == NULL) return err;` ?

Then in this case it depends on how you assume user will use your API, and in case of event_base_loop() passing NULL there is just nonsense (plus long time ago it was written that way that it uses global event_base if any as a fallback if event_base==NULL, but this had been deprecated long time ago).
And this is not a common practice in the language (C), but instead there may be some conventions per-project (check against NULL or not), for example `strlen`, it does not check against NULL.
