### ISSUE TITLE
libevent compile on FreeRTOS Linux 

### ISSUE THREAD

**Issue by hrishi77** [libevent/libevent#1119]
How to compile libevent on freeRTOS Linux

**Comment by azat** [comment]
You can go one of the two ways:
- [cmake](https://github.com/libevent/libevent/blob/master/Documentation/Building.md#building-on-unix-cmake)
- [autotools](https://github.com/libevent/libevent/blob/master/Documentation/Building.md#autoconf)

Have you tried? Do you have any errors?

**Comment by hrishi77** [comment]
Not tried ,i did not get how to cmake on freeRTOS (steps) ? Is there need to change in make file of libevent ?

**Comment by azat** [comment]
> Is there need to change in make file of libevent ?

You will never know until you tried
