### ISSUE TITLE
 Transfer a lot of data

### ISSUE THREAD

**Issue by ColdV** [libevent/libevent#1124]
after read libevent,  I also try to develop a network library by cpp,  now i have some problems, when i transfer data like 10M, client's and server's  RWIN(remaining receive buffer) is zero, cause remaining data unable trans.  but using libevent as the server，not such problem then i went to read libevent's code, still no answer has been found. so sir, can you teach me?

**Comment by azat** [comment]
Not sure that I understand you correctly, but I will do my best guess.

>after read libevent

So firstly you look at libevnt

>I also try to develop a network library by cpp

After you was trying to write you own library for client/server

> now i have some problems, when i transfer data like 10M

10m is 10 megabytes?

>, client's and server's RWIN(remaining receive buffer) is zero, cause remaining data unable trans

There is nothing I can help with until I will see code.
Can you post sources? (But in a way that I can compile and/or read)

> but using libevent as the server，not such problem then i went to read libevent's code, still no answer has been found. so sir,

By the way what type of server? TCP/HTTP?

Can you provide more details? i.e. "I run THIS, and got THIS, while I was expecting THIS"

**Comment by ColdV** [comment]
I have figured out some problems. thank you!
