### ISSUE TITLE
Please make the rpc framework transport agnostic.

### ISSUE THREAD

**Issue by ytrezq** [libevent/libevent#1125]
More and more rpc servers uses a websocket instead of plain http. This is something obvious.

But in the case of some cryptocurrencies the concept is pushed higher. A client can also send the same request over plain tcp or unix domain with the later providing the best option in terms of latency for responding to trades.

Instead of implementing many backends, the best option is of course to be transport agnostic. Though this would be better expressed under languages like modern C++.

**Comment by azat** [comment]
Indeed, right now you cannot use http (and hence rpc) for websockets, and this is very welcome feature.
AFAIR it needs only few callbacks to get ad-hoc support

But it is unlikely that I will find time for this, maybe you are interesting in contributing this?

**Comment by ytrezq** [comment]
I wrote this issue because I barely understand how to do this without the rpc library.

**Comment by azat** [comment]
websockets supports had been added in https://github.com/libevent/libevent/pull/1322
