### ISSUE TITLE
[SOS] How to send Transfer-Encoding:chunked as  http-client by libevent

### ISSUE THREAD

**Issue by Andy6Loda** [libevent/libevent#1131]
These are just used on server:
evhttp_send_reply_start(struct evhttp_request *req)
evhttp_send_reply_chunk(struct evhttp_request *req, struct evbuffer *databuf)
evhttp_send_reply_end(struct evhttp_request *req)`.

But, now i need send to other service large file, How can i do this?

**Comment by azat** [comment]
This is not supported by the http layer (only receiving chunks in the client is supported now), but you can do this using raw bufferevents, see the referenced commit for an example

**Comment by Andy6Loda** [comment]
@azat Thank you very much. I'll try it later
