### ISSUE TITLE
A frozen input evbuffer of bufferevent may cause undefined error, for the conflict cast convertion between the return value of bufferevent_read() and evbuffer_remove()，int(-1)->size_t(An undefined maximum).

### ISSUE THREAD

**Issue by sclei** [libevent/libevent#1132]
A frozen input evbuffer of bufferevent may cause undefined error, for the conflict cast convertion between the return value of bufferevent_read() and evbuffer_remove().

Bug：int(-1)->size_t(An undefined maximum) , it is likely triggered;

```c
int
evbuffer_remove(struct evbuffer *buf, void *data_out, size_t datlen) 
{
    ev_ssize_t n;
    ....
    if (n > 0) {
        if (evbuffer_drain(buf, n)<0) 
            n = -1; 
    }
    ....
    return (int)n;
}
...
size_t
bufferevent_read(struct bufferevent *bufev, void *data, size_t size)
{
    return (evbuffer_remove(bufev->input, data, size));     
}
```

We can modify the implement of bufferevent_read to return 0 when evbuffer_remove is -1. or modify the  type of bufferevent_read's return type.

**Comment by azat** [comment]
>Bug：int(-1)->size_t(An undefined maximum) , it is likely triggered;

Right

>We can modify the implement of bufferevent_read to return 0 when evbuffer_remove is -1. or modify the type of bufferevent_read's return type.

Ok, let's return 0 in case of evbuffer_remove returns an error and update documentation section for bufferevent_read.
Can you send a patch/pull request?

But `bufferevent_read()` should propagate an error somehow, so long-term solution is:
- evbuffer should be converted to `size_t`/`ev_ssize_t`
- bufferevent_read may be converted to `ev_ssize_t`

The problem with this is that this breaks ABI, so either we should start breaking it, or add a function with another name...

**Comment by sclei** [comment]
> Ok, let's return 0 in case of evbuffer_remove returns an error and update documentation section for bufferevent_read.
Can you send a patch/pull request?

I will send a pull request.
