### ISSUE TITLE
[Compile Error] "release-2.1.12-stable" is failed to compile in VS2012

### ISSUE THREAD

**Issue by mkckr0** [libevent/libevent#1135]
https://github.com/libevent/libevent/blob/5df3037d10556bfcb675bc73e516978b75fc7bc7/evutil_time.c#L96
VS2012 has a bug, see example code below:
```c
int main()
{
    int i = 0;
    ++i;
    static int x = 1;
}
```
VS2012 will report an error: "error C2143：语法错误 ：缺少“;”（在"类型"前面）"
But VS2019 has no bug.
So the `static variable definition` must be put before `non-definition statement` in VS2012.

**Comment by azat** [comment]
@mkckr0 thanks for the report, can you send a patch (pull request)?
