### ISSUE TITLE
libevent 2.1.12 doesn't detect custom paths for OpenSSL libraries

### ISSUE THREAD

**Issue by jumde** [libevent/libevent#1136]
```
./configure \
              LDFLAGS="-L$PWD/../openssl-1.1.1i/root" \
              CPPFLAGS="-I$PWD/../oppenssl-1.1.1i/include" \
              --prefix=$PWD/install \
              --disable-shared \
              --enable-static \
              --with-pic
```

works well with libevent 2.1.11

but, gives an error

```
configure: error: openssl is a must but can not be found. You should add the directory containing `openssl.pc' to the `PKG_CONFIG_PATH' environment variable, or set `CFLAGS' and `LDFLAGS' directly for openssl, or use `--disable-openssl' to disable support for openssl encryption
```

with libevent 2.1.12

**Comment by ploxiln** [comment]
hmm, should probably be fixed, but you may be able to get it working with something like

```
./configure PKG_CONFIG_PATH=../openssl-1.1.1i/lib/pkgconfig --prefix=...
```

**Comment by azat** [comment]
>libevent 2.1.12 doesn't detect custom paths for OpenSSL libraries #1136

Cannot confirm this:

```sh
$ docker pull debian:testing
$ docker run --rm --name le -it debian:testing

$ apt-get install build-essential libtool automake autoconf git wget
$ mkdir /src

$ cd /src
$ git clone https://github.com/openssl/openssl.git
$ cd openssl
$ ./config
$ ./make -j
$ find . -name libssl.a -or -name libssl.so
./libssl.a
./libssl.so

$ cd /src
$ wget https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
$ tar -xf libevent-2.1.12-stable.tar.gz
$ ./configure --prefix=$PWD/install --disable-shared --enable-static --with-pic LDFLAGS=-L/src/openssl CPPFLAGS=-I/src/openssl/include
...
checking for pkg-config... no
checking for library containing SSL_new... -lssl
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
...
$ make -j
$ LD_LIBRARY_PATH=/src/openssl ./sample/https-client -crt /etc/ssl/certs/ca-certificates.crt -url https://kernel.org
https server 'kernel.org' has this certificate, which looks good to me:
/CN=*.kernel.org
Response line: 301 Moved Permanently
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
$ LD_LIBRARY_PATH=/src/openssl ldd ./sample/https-client
        linux-vdso.so.1 (0x00007ffff7fd0000)
        libssl.so.3 => /src/openssl/libssl.so.3 (0x00007ffff7eee000)
        libcrypto.so.3 => /src/openssl/libcrypto.so.3 (0x00007ffff7aae000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffff7a88000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffff78c3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffff78bd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffff7fd2000)
```

**Comment by ploxiln** [comment]
Hmm yeah works for me too. Maybe `LDFLAGS="-L$PWD/../openssl-1.1.1i/root"` should instead be `LDFLAGS="-L../openssl-1.1.1i/lib"` or `LDFLAGS="-L../openssl-1.1.1i/root/lib"` (depending on where and how you built your custom openssl)

**Comment by dgbttn** [comment]
Got the same error as @jumde 's with libevent 2.1.12, on MacOS 12.4, M1.

Even when I set the `PKG_CONFIG_PATH` value:
```
./configure PKG_CONFIG_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1o/lib/pkgconfig --prefix=/usr/local
```

**Comment by AlbusArcher** [comment]
In my project, I had sloved it.
1. you should install pkg-config
2. you need export PKG_CONFIG_PATH that contains libssl compile directory into current environment
3. modify path of libdir and includedir in libssl.pc and libcrypto.pc in libssl compile directory

**Comment by azat** [comment]
>Got the same error as @jumde 's with libevent 2.1.12, on MacOS 12.4, M1.
>Even when I set the PKG_CONFIG_PATH value:
>./configure PKG_CONFIG_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1o/lib/pkgconfig --prefix=/usr/local

Please try the following:

```sh
export PKG_CONFIG_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1o/lib/pkgconfig
./configure --prefix=/usr/local
```

**Comment by ploxiln** [comment]
also, a bit more future-proof:

```
export PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@1.1/lib/pkgconfig
./configure --prefix=/usr/local
```

**Comment by link3280** [comment]
Same problem here. I've tried the all approaches suggested above, but still getting the error on M1 Mac.

**Comment by yayayahei** [comment]
> In my project, I had sloved it.
> 
> 1. you should install pkg-config
> 2. you need export PKG_CONFIG_PATH that contains libssl compile directory into current environment
> 3. modify path of libdir and includedir in libssl.pc and libcrypto.pc in libssl compile directory

@link3280  I've met the same error on M1 Mac, and resolved as the following step:
* must install pkg-config and run
`./configure PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@1.1/lib/pkgconfig --prefix=/usr/local`
