### ISSUE TITLE
How can I use libevent to read request body streams?

### ISSUE THREAD

**Issue by ababo** [libevent/libevent#1138]
I need to read request stream in chunks via callback rather than to read the full request body at once. How can I achieve that?

**Comment by azat** [comment]
Take a look at `evhttp_request_set_chunked_cb`

**Comment by ababo** [comment]
AFAIK this works only on a client side.

**Comment by azat** [comment]
Right, server does not support reading body by chunks, you can take a look at libevhtp for this.

**Comment by dfedorin** [comment]
> Right, server does not support reading body by chunks, you can take a look at libevhtp for this.

It kind of does. You can call evhttp_request_set_chunked_cb from new request callback

**Comment by GITmhj** [comment]
why libevent missing terminator while receiving compressed file?
