### ISSUE TITLE
 evhttp: fd leak on connection timeout

### ISSUE THREAD

**Issue by KseniyaYakil** [libevent/libevent#1143]
Hi!

libevent master version has fd leak while using evhttp and receiving request timeout:
- create evhttp connection
- call evhttp_make_request and event_base_dispatch
- make remote server to be stopped
- fd leak on client side

It looks like fd has to be closed before setting fd=-1 to evcon->bufev->ev_read->fd.

In the last libevent master (00b92f42b69af29a) I suppose the following stack of function calls:
evhttp_error_cb -> evhttp_connection_fail_ -> evhttp_connection_reset_(evcon, 1); -> evhttp_connection_reset_hard_ -> bufferevent_setfd(evcon->bufev, -1); fd is not closed before setting it to -1

In the last stable version (libevent-release-2.1.12-stable) there is a check and correct close:
evhttp_error_cb -> evhttp_connection_fail_ -> evhttp_connection_reset_ ->
evcon->fd = bufferevent_getfd(evcon->bufev);  -> shutdown(evcon->fd, EVUTIL_SHUT_WR);  evutil_closesocket(evcon->fd); -> err = bufferevent_setfd(evcon->bufev, -1);

To reproduce this bug:
1) build binary from code https://gist.github.com/KseniyaYakil/f48e6e4781c715b21013afc3e92681f1#file-libevent_master_fd_leak_reproduce-c

For example:
For master built version
gcc -std=gnu11 -g -O3 -ggdb3  -I<path to libevent master headers> -c -o fd_leak libevent_master_fd_leak_reproduce.c 
gcc -o reproduce fd_leak <path to libevent master libevent.a>

The same for libevent-release-2.1.12-stable

2) run local http server
For example, php -S 0.0.0.0:8888
3) run ./reproduce 0.0.0.0 8888 
4) send kill -STOP to server pid
5) lsof -Pp <pid of reproduce process>

You will see increasing number of fds from reproduce process to 0.0.0.0 8888 
If you repeat these actions with libevent-release-2.1.12-stable, there won't be fd leak

Please, fix this problem in libevent master

**Comment by azat** [comment]
@KseniyaYakil thanks for detailed report!

The bug was introduced in afa66ea4200a018bfc59abef8c2ffa11ef2b8363, during eliminating various file descriptors manipulations (that should be encapsulated by the bufferevent at least), fixed in the referenced commit.

**Comment by KseniyaYakil** [comment]
Thank you =)
