### ISSUE TITLE
Error on autogen and configure

### ISSUE THREAD

**Issue by L1NKD34D** [libevent/libevent#1149]
Linux xxx 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

After issuing autogen and attempting to configure, encountered  a syntax error on 13904 and 14379 of the configure file.  28f0fe6 related? 

```
./configure: line 13904: syntax error near unexpected token `arpa/inet.h'
./configure: line 13904: `  arpa/inet.h'
```

```
./configure: line 14379: syntax error near unexpected token `accept4'
./configure: line 14379: `  accept4'
```

remediated by modifying both loop occurrences in configure as 
```
for ac_header in \
  arpa/inet.h \
  fcntl.h \
  ifaddrs.h \
...
  afunix.h
do :
...
```

**Comment by azat** [comment]
>After issuing autogen and attempting to configure, encountered a syntax error on 13904 and 14379 of the configure file. 28f0fe6 related?

Thanks, right I broke it there, although it works with autoconf 2.71+
