### ISSUE TITLE
Snippet to do bufferevent_flush() with openssl

### ISSUE THREAD

**Issue by thefallentree** [libevent/libevent#1163]
it's currently not implemented. 
```
      auto *ssl = bufferevent_openssl_get_ssl(ev_buffer);
      auto *output = bufferevent_get_output(ev_buffer);
      auto len = evbuffer_get_length(output);
      if (len > 0) {
        evbuffer_unfreeze(output, 1);
        auto *data = evbuffer_pullup(output, len);
        auto wrote = SSL_write(ssl, data, len);
        if (wrote > 0) {
          evbuffer_drain(output, wrote);
        }
        evbuffer_freeze(output, 1);
        return wrote > 0;
```

**Comment by thefallentree** [comment]
Actually, this was a question:  for some reason, this snippet will cause duplicate messages to be sent out through SSL, could you help with why? 

On the contrary ,  this snippet for flushing socket based bufferevent seems to be working well:

```
  auto fd = bufferevent_getfd(ip->ev_buffer);
      if (fd == -1) {
        return 0;
      }
      auto output = bufferevent_get_output(ip->ev_buffer);
      auto total = evbuffer_get_length(output);
      if (total > 0) {
        evbuffer_unfreeze(output, 1);
        auto wrote = evbuffer_write(output, fd);
        evbuffer_freeze(output, 1);
        return wrote != -1;
      }
```

as you can see, the only thing changed was  evbuffer_write() to SSL_write()

**Comment by azat** [comment]
>Actually, this was a question: for some reason, this snippet will cause duplicate messages to be sent out through SSL, could you help with why?

Have you checked the exit code of the evbuffer_drain() it is likely fails because the buffer is freezed.

>Snippet to do bufferevent_flush() with openssl

It is pretty easy to do, do you mind taking a look and submitting a PR?

https://github.com/libevent/libevent/blob/990bcfc28e720ba34f7f14a2bc257c210e45e699/bufferevent_ssl.c#L928

**Comment by azat** [comment]
>Actually, this was a question: for some reason, this snippet will cause duplicate messages to be sent out through SSL, could you help with why?

Have you checked the exit code of the evbuffer_drain() it is likely fails because the buffer is freezed.

>Snippet to do bufferevent_flush() with openssl

It is pretty easy to do, do you mind taking a look and submitting a PR?

https://github.com/libevent/libevent/blob/990bcfc28e720ba34f7f14a2bc257c210e45e699/bufferevent_ssl.c#L928

**Comment by thefallentree** [comment]
> > Actually, this was a question: for some reason, this snippet will cause duplicate messages to be sent out through SSL, could you help with why?
> 
> Have you checked the exit code of the evbuffer_drain() it is likely fails because the buffer is freezed.
> 
> > Snippet to do bufferevent_flush() with openssl
> 
> It is pretty easy to do, do you mind taking a look and submitting a PR?
> 
> https://github.com/libevent/libevent/blob/990bcfc28e720ba34f7f14a2bc257c210e45e699/bufferevent_ssl.c#L928
> 
> (but it should be covered with a unit test somehow, see https://github.com/libevent/libevent/blob/master/test/regress_ssl.c https://github.com/libevent/libevent/blob/master/test/regress_mbedtls.c https://github.com/libevent/libevent/blob/master/test/regress_openssl.c)

evbuffer_drain() was done before after the unfreeze()  but before freeze() , was that wrong? I thought drain means just delete message without sending them

**Comment by azat** [comment]
>evbuffer_drain() was done before after the unfreeze() but before freeze() , was that wrong? I thought drain means just delete message without sending them

your code does not have freeze/unfreeze bufferever uses then internally, so you should check exit code of evbuffer_drain(), it will fail if the buffer is freezed.

**Comment by thefallentree** [comment]
> > evbuffer_drain() was done before after the unfreeze() but before freeze() , was that wrong? I thought drain means just delete message without sending them
> 
> your code does not have freeze/unfreeze bufferever uses then internally, so you should check exit code of evbuffer_drain(), it will fail if the buffer is freezed.

do you mean this? 

```
        evbuffer_unfreeze(output, 1);
        auto *data = evbuffer_pullup(output, len);
        auto wrote = SSL_write(ssl, data, len);
        if (wrote > 0) {
          evbuffer_drain(output, wrote);
        }
        evbuffer_freeze(output, 1);
```
as you can see it definitely does, yet the result is still double sending, I will add some code to check the return code for evbuffer_drain .

**Comment by azat** [comment]
>as you can see it definitely does

Sorry, missed that bit (let's blame the night)
Then it is likely should work, BTW I've just tried the same - it works.
Can you share simple reproducer w/o any extra depenedencies?

>On the contrary , this snippet for flushing socket based bufferevent seems to be working well:

But this will not encrypt the data.

**Comment by thefallentree** [comment]
Reporting back : This snippet doesn't work. I don't know why, but the end result is that after the flush snippet, bufferevent_openssl will repeat sending the last message over and over again (whatever it is), I think there might be something weird going on with evbuffer_get_length calculations.

**Comment by azat** [comment]
>Then it is likely should work, BTW I've just tried the same - it works.

This is what I've tried - https://github.com/azat/libevent/commit/15a1aa2a335fe363a49d424df1d55cfd47aeec82

BTW from which place you are doing manual flush?

**Comment by azat** [comment]
FWIW The problem with flush is that it may require read in SSL layer, so it is not possible to do true non-blocked flush.

**Comment by thefallentree** [comment]
I have figured out why:  

https://github.com/libevent/libevent/blob/fabbf3b31074ed74b9f0657299836fe40e4e365a/bufferevent_ssl.c#L388

Didn't check the return code for drain , and most importantly, didn't evbuffer_unfreeze the output before drain,  in my snippet it was freeze after the drain, making the subsequent calls keep sending the data.  a simple fix is to add unfreeze and also check the return code of the evbuffer_drain here.

**Comment by azat** [comment]
>Didn't check the return code for drain , and most importantly, didn't evbuffer_unfreeze the output before drain, in my snippet it was freeze after the drain, making the subsequent calls keep sending the data. a simple fix is to add unfreeze and also check the return code of the evbuffer_drain here.

I've added the missing check, but I'm not sure that it should have evbuffer_unfreeze there, since ssl layer does not freeze it.
Why do you need to freeze it?

Also am I understand correctly that [in the second example](https://github.com/libevent/libevent/issues/1163#issuecomment-830511871) it will not be encrypted?

**Comment by thefallentree** [comment]
> I've added the missing check, but I'm not sure that it should have evbuffer_unfreeze there, since ssl layer does not freeze it.
Why do you need to freeze it?

I think we need to call evbuffer_freeze()/evbuffer_unfreeze in bufferevent_ssl? If not won’t we have an race condition on evbuffer_peek here?  

 For my second snippet it was meant to show the similar routine works for bufferevent, it is not used in ssl stuff.

**Comment by azat** [comment]
>I think we need to call evbuffer_freeze()/evbuffer_unfreeze in bufferevent_ssl? If not won’t we have an race condition on evbuffer_peek here?

Here - where? If you are talking about https://github.com/libevent/libevent/blob/048907a501e2ee106cd9dabf6686697f3b73b562/bufferevent_ssl.c#L336 then it is not possible to run it concurrently

**Comment by thefallentree** [comment]
Why? Even if do_write()  / consider_writing() can't get called concurrently, it is possible for the  underlying evbuffer to be used concurrently, right?

**Comment by azat** [comment]
>Why? Even if do_write() / consider_writing() can't get called concurrently, it is possible for the underlying evbuffer to be used concurrently, right?

If it is possible you should create bufferevent with `BEV_OPT_THREADSAFE`, this will guard bufferevent **and** evbuffer with the same lock (and you should be very careful when you are trying to intercept with the bufferevent code)
