### ISSUE TITLE
Unable to find libevent.a libevent libevent_core.a

### ISSUE THREAD

**Issue by skundan183** [libevent/libevent#1169]
![image](https://user-images.githubusercontent.com/46713590/120203345-3ef97580-c245-11eb-98bf-405d9bd9987e.png)

Unable to find these files for arm64 android from libevent library. Where I can get these files?

**Comment by azat** [comment]
Can you please explain how you are building llibevent?
There is one cmake variable that controls this - `EVENT__LIBRARY_TYPE`, check it.

**Comment by skundan183** [comment]
Hi Azat,
I am building using configure and make command. Refer the below script for better understanding...

![image](https://user-images.githubusercontent.com/46713590/124454406-144f8f00-dda6-11eb-81a2-598b99227e49.png)

**Comment by azat** [comment]
>Unable to find these files for arm64 android from libevent library. Where I can get these files?

The the answer will be - `.libs` directory

**Comment by skundan183** [comment]
Hi Azat, Now I am able to generate libevent.a file but when I try to link this file with SO file using Android make, NDK build return "**libevent.a: error adding symbols: File format not recognized**". Is there any way I can check, Is something wrong with libevent.a file?

**Comment by azat** [comment]
>libevent.a: error adding symbols: File format not recognized

Looks like you did not correctly cross compile libevent.
And there is nothing much I can help with since I don't cross compile libevent for arm.
But AFAIR I did it once, but with cmake.

**Comment by skundan183** [comment]
Hi Azat, Can you help me or share the script how did you cross compile with cmake? I have things working for 32 bit but now I need it for ARM64 (64 bit). Thanks.

**Comment by azat** [comment]
I don't have them already (I did it only once, and only to dig into the reported issue).

But if you will search over issues, you will find:
- https://github.com/libevent/libevent/issues/968#issuecomment-604738609
- https://github.com/libevent/libevent/issues/475#issuecomment-284256518
