### ISSUE TITLE
Is it thread safe to call evhttp_make_request on other thread?

### ISSUE THREAD

**Issue by zty0** [libevent/libevent#1178]
Our project is based on the newest commit of libevent, the commit hash is 3d48c7563c0585856cd8681435c1555fe13b0859.

We use libevent to run client http/https connections. The event_base is running on a background thread and we dispatch http/https request from main thread. We process http response on the background thread and dispatch result back to main thread. I've checked the source, it seems that it is thread safe to call evhttp_make_request on different thread. Current version of libevent will check if current thread is the thread on which event_base is running, if not, it will notify the event loop. I've set some breakpoints to see what is happening along the code path, I see that libevent does lock.

So just want to be sure, is it thread safe? thanks

**Comment by ploxiln** [comment]
No, evhttp is not multi-thread-safe and there is no option to make it so. You must call evhttp functions only on the event-loop thread.

https://github.com/libevent/libevent/issues/1052
https://github.com/libevent/libevent/issues/1023
https://github.com/libevent/libevent/issues/1015

There are options to make basic events, and "bufferevents", thread-safe, but not evhttp stuff.

**Comment by zty0** [comment]
> No, evhttp is not multi-thread-safe and there is no option to make it so. You must call evhttp functions only on the event-loop thread.
> 
> #1052
> #1023
> #1015
> 
> There are options to make basic events, and "bufferevents", thread-safe, but not evhttp stuff.

ok, thanks. Then is it ok to configure evhttp connection on main thread and dispatch request on the event loop thread?
