### ISSUE TITLE
Immediate send to TCP socket bufferevent_write bufferevent libevent

### ISSUE THREAD

**Issue by sayedmomeen** [libevent/libevent#1180]
I have application which send data event 10messsages in gap 5second every 5minuts, Buffer size can in 10KB. its non blocking connection. For that reason i have used bufferevent. But I am not able to achieve the same. all 10 messages ill get together.
[LibEvClient.txt](https://github.com/libevent/libevent/files/6776701/LibEvClient.txt)
[LibEvServer.txt](https://github.com/libevent/libevent/files/6776704/LibEvServer.txt)

**Comment by ploxiln** [comment]
please use "fenced code blocks" for posting code samples in a more convenient to view way: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by azat** [comment]
The problem is in `sleep(5)` in your client code, you should never use such things with async programming.

Here is a patch for you client.c:

```patch
-void fnTimeExpired(evutil_socket_t listener, short event, void *arg)
+void fnTimeExpired(evutil_socket_t fd, short ev, void *arg)
 {
     char buffer[iMesssageSize + 10];
     memset(buffer, 'A', sizeof(buffer));
@@ -40,11 +40,15 @@ void fnTimeExpired(evutil_socket_t listener, short event, void *arg)
     uint64_t exp;
     read(iTimerFd, &exp, sizeof(uint64_t));
 
-    for (int iCount = 0; iCount < iNoOfMessage; iCount++)
+    static int iCount;
+    if (iCount++ < iNoOfMessage)
     {
         bufferevent_write(bev, buffer, iMesssageSize);
-        bufferevent_flush(bev, EV_WRITE, BEV_FLUSH);
-        sleep(5);
+
+        timeval tv;
+        tv.tv_sec = 5;
+        tv.tv_usec = 0;
+        event_base_once(base, fd, ev, fnTimeExpired, arg, &tv);
     }
 }

```

**Comment by sayedmomeen** [comment]
@azat Sleep of 5seconds will be my part of code will be in milliseconds. I want that bufferevent_write immediately as soon come out of that bufferevent_write

**Comment by azat** [comment]
>@azat Sleep of 5seconds will be my part of code will be in milliseconds. I want that bufferevent_write immediately as soon come out of that bufferevent_write

Then just don't use sleep, in a true async world you do not have guarantee that all data had been sent, you need to implement these using callbacks, i.e. you set write callback and once everything had been written your write callback will be called.
