### ISSUE TITLE
Is it thread safe to configure evhttp connection on main thread and then dispatch requests on event loop thread?

### ISSUE THREAD

**Issue by zty0** [libevent/libevent#1181]
My last issue was closed: #1178

If it is not ok to dispatch on other threads than event loop thread, then is it ok to configure evhttp connections on other thread?

We are now creating mbedtls based buffer events and evhttp connections on main thread, and will dispatch requests on the event loop thread. I want to know if this is thread safe.

**Comment by azat** [comment]
I'm not sure that I will understand correctly what "configure evhttp connectoins" means, but I would say that you should create/configure/use it from the same thread if you want to avoid possible issues.

You can share your code and I may take a look.

**Comment by zty0** [comment]
Thanks.
What we are doing is a cross platform mobile app framework, we use libevent to do networking. on main thread, for example, user hits a button which causes a HTTP request to be fired. So on main thread:
```
// this is a c++ member method, base is created on background thread and keep running with EVLOOP_NO_EXIT_ON_EMPTY flag on
struct mbedtls_ssl_context* ssl = nullptr;
struct bufferevent* bev = nullptr;
struct evhttp_connection* con = nullptr;
struct evhttp_request* req = nullptr;
XXXRequest* request = nullptr; // ignore the class name, I made it up. We use this wrapper class to manage evhttp req objects
ssl = reinterpret_cast<mbedtls_ssl_context*>(calloc(1, sizeof(struct mbedtls_ssl_context)));
// configure ssl....
bev = bufferevent_mbedtls_socket_new(base, -1, ssl,
			BUFFEREVENT_SSL_CONNECTING,
			BEV_OPT_CLOSE_ON_FREE | BEV_OPT_THREADSAFE | BEV_OPT_DEFER_CALLBACKS);
// parse passed in url argument to get host and port....
con = evhttp_connection_base_bufferevent_new(base, nullptr, bev, host, port);

evhttp_connection_set_family(con, AF_UNSPEC);
evhttp_connection_set_timeout(con, 20);
evhttp_connection_free_on_completion(con);
req = evhttp_request_new(nullptr, nullptr);
evhttp_request_own(req);
request = new XXXRequest(req);
req->cb = http_request_done; // we have to include the http_struct.h header because we must create req first, current version of evhttp doesn't have access method to set cb_arg and cb fields
req->cb_arg = request;
return request;
```
and the request object returned from upper code snippet is passed to another function, still on main thread:
```
// XXXHTTPContext class manage event_base object
void XXXHTTPContext::dispatchRequest(XXXRequest* request)
{
// dispatch request to event loop thread
	struct event* ev = event_new(m_eb, -1, 0, _dispatch_request, request);
	event_active(ev, 0, 0);
}

// this will be executed on the event loop thread
static void _dispatch_request(evutil_socket_t sock, short which, void* arg) {
	XXXRequest* request = reinterpret_cast<XXXRequest*>(arg);
	request->sendRequest();
}

void XXXRequest::sendRequest()
{
	struct evkeyvalq* output_headers = evhttp_request_get_output_headers(m_req);
	evhttp_add_header(output_headers, "Host", evhttp_uri_get_host(m_uri));
	evhttp_add_header(output_headers, "Connection", "keep-alive");

// copied from the https_client example in libevent repo
	char uri[256];
	const char* query = evhttp_uri_get_query(m_uri);
	const char* path = evhttp_uri_get_path(m_uri);
	if (query == NULL) {
		snprintf(uri, sizeof(uri) - 1, "%s", path);
	}
	else {
		snprintf(uri, sizeof(uri) - 1, "%s?%s", path, query);
	}
	uri[sizeof(uri) - 1] = '\0';

	evhttp_make_request(m_con, m_req, m_method, uri);
}
```
I have read source code of libevent intensely recent, I think it is thread safe from my understanding. But a confirm from the developer would be appreciated.
> I'm not sure that I will understand correctly what "configure evhttp connectoins" means, but I would say that you should create/configure/use it from the same thread if you want to avoid possible issues.
> 
> You can share your code and I may take a look.

**Comment by azat** [comment]
Sorry for the delay

>req->cb = http_request_done; // we have to include the http_struct.h header because we must create req first, current version of evhttp doesn't have access method to set cb_arg and cb fields

But why `evhttp_make_request` is not used?

>and the request object returned from upper code snippet is passed to another function, still on main thread:

Than what code is executed from another thread?

But in general evhttp layer is not thread safe, you may hit some hard to debug issues, for the reference you may take a look at:

#1052
#1023
#1015

So it is better and safer for you to defer the job for creating http connections to another thread using some thread-safe/lock-free queue or similar.
