### ISSUE TITLE
What's the function of address 18.244.0.188 and 1.2.3.4 in source code?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#1185]
May i replace them with 127.0.0.1 or other address? thanks!

**Comment by azat** [comment]
>May i replace them with 127.0.0.1 or other address? thanks!

No, since it requires non host and non link-local interface.
Do you have any problems with this code?

https://github.com/libevent/libevent/blob/c29f1dbe116c88434e77721ca215b8d2082b247f/evutil.c#L980

**Comment by okayabc** [comment]
Can replace 18.244.0.188 with other address not 127.0.0.1 due to some safety problem?

And for another address 1.2.3.4, i find it in test_for_getaddrinfo_hacks interface and it's a testing function, does libevent provide some make option to forbid compile this function?

**Comment by azat** [comment]
>Can replace 18.244.0.188 with other address not 127.0.0.1 due to some safety problem?

Can you elaborate which problems do you have?
This address is never used actually.

>And for another address 1.2.3.4, i find it in test_for_getaddrinfo_hacks interface and it's a testing function, does libevent provide some make option to forbid compile this function?

You can disable tests, `cmake -DEVENT__DISABLE_TESTS=ON`

**Comment by okayabc** [comment]
Because i use some open source scanning software scan the code, it report this address is an constant and maybe exist safety problem.

**Comment by azat** [comment]
Usually such tools has suppressions, maybe your tool also has it?
You can modify it but then you will have custom libevent, and just changing one constant in the code does not looks like it worth it.

**Comment by okayabc** [comment]
Btw, if my service link .a of openssl1.1.1k but libevent not compile with openssl1.1.1k, in order to use openssl1.1.1k, should i recompile libevent with  openssl1.1.1k?

**Comment by azat** [comment]
>Btw, if my service link .a of openssl1.1.1k but libevent not compile with openssl1.1.1k, in order to use openssl1.1.1k, should i recompile libevent with openssl1.1.1k?

It depends, libevent should be compiled with binary compatible version of openssl, so if you program compiled with openssl1.1.1 then I guess it is OK

P.S. please don't mix questions in issues, it is better to use [gitter](https://gitter.im/libevent/libevent) for such questions.

**Comment by azat** [comment]
@okayabc Do you have any further questions on this issue?
