### ISSUE TITLE
On the win32, CreateFileMapping is double call in evbuffer_add_file

### ISSUE THREAD

**Issue by wuhuangpeng** [libevent/libevent#1186]
I have the same promble as #999 .
when i call evbuffer_add_file(), the evbuffer_file_segment_materialize() function will double call, and so CreateFileMapping will double call, but CloseHandle only call once in evbuffer_file_segment_free, this causes the file to be occupied and cannot be deleted.
```
	if (seg->contents)
		return 0; /* already materialized */
```
evbuffer_file_segment_materialize use "seg->contents" to check it has already materialized, and prevent double call CreateFileMapping. But seg->contents is not set on win32, i think  "seg->is_mapping" also means materialize success. So, the right way to prevent double call CreateFileMapping is as follows:

```
	if (seg->contents || seg->is_mapping)
		return 0;
```

**Comment by azat** [comment]
Thanks for the details! Fixed.
