### ISSUE TITLE
minheap-internal.h: error C2065: 'UINT32_MAX': undeclared identifier with MSVC2019

### ISSUE THREAD

**Issue by emmenlau** [libevent/libevent#1189]
I try to build Apache thrift on MSVC2019, which requires libevent. However the build fails with the error that can be seen here: https://ci.appveyor.com/project/ApacheSoftwareFoundation/thrift/builds/40247460/job/lns1a3x5n2ke8e16

The relevant part seems to be:
```
c:\projects\thrift\thirdparty\libevent-2.1.12-stable\minheap-internal.h(73): error C2065: 'UINT32_MAX': undeclared identifier
buffer.c
c:\projects\thrift\thirdparty\libevent-2.1.12-stable\minheap-internal.h(73): error C2065: 'UINT32_MAX': undeclared identifier
buffer.c(3120): warning C4244: 'function': conversion from '__int64' to 'unsigned int', possible loss of data
bufferevent.c
c:\projects\thrift\thirdparty\libevent-2.1.12-stable\minheap-internal.h(73): error C2065: 'UINT32_MAX': undeclared identifier
```

Some other users commented in https://www.programmersought.com/article/64085863527/ that the solution is to add `#include <stdint.h>` in this file `minheap-internal.h`.

**Comment by azat** [comment]
Ok, let's do this, it will not hurt, do you mind send a patch?
