### ISSUE TITLE
evconnlistener_new_bind issue with IPV6_V6ONLY on windows

### ISSUE THREAD

**Issue by edo9300** [libevent/libevent#1191]
Libevent introduced the ``LEV_OPT_BIND_IPV6ONLY`` to pass to ``evconnlistener_new_bind`` to make it automatically set the underlying socket as accepting ipv6 requests. This works fine on posix compliant platforms as by the standard every new ``AF_INET6`` socket is created as both supporting ipv6 and ipv4 connections. But on windows the default is the opposite, with the flag ``IPV6_V6ONLY `` being always enabled by default.
This makes creating a listener to supports both protocols a bit more tricky as winsock doesn't allow changing this flag after ``evconnlistener_new_bind`` does all the initial setup because as stated in the docs, you can't change it after the sonnect connected, so one would have to manually create the socket beforehand and set the flag and then call evconnlistener_new with the socket itself.
It would be nice to have libevent keep a consistent behaviour across the platforms in this scenario, maybe or by making it always set ``IPV6_V6ONLY `` to false unless ``LEV_OPT_BIND_IPV6ONLY`` is passed, in which case it's set to true, or add another flag to forcefully set it to false and keep the system dependent behaviour as default.

This would accept both ipv4 and ipv6 connections on a posix system.
```cpp
	event_base* net_evbase = event_base_new();
	sockaddr_in6 sin;
	memset(&sin, 0, sizeof(sin));
	sin.sin6_family = AF_INET6;
	evutil_inet_pton(AF_INET6, "::", &sin.sin6_addr);
	sin.sin6_port = htons(7911);
	listener = evconnlistener_new_bind(net_evbase, ServerAccept, nullptr,
									   LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE, -1, (sockaddr*)&sin, sizeof(sin));
```

On windows the initial manual setup would be needed instead to achieve the same result
```cpp
	event_base* net_evbase = event_base_new();
	sockaddr_in6 sin;
	memset(&sin, 0, sizeof(sin));
	sin.sin6_family = AF_INET6;
	evutil_inet_pton(AF_INET6, "::", &sin.sin6_addr);
	sin.sin6_port = htons(7911);
	int on = 1;
	int off = 0;
	evutil_socket_t fd = socket(AF_INET6, SOCK_STREAM, 0);
	evutil_make_socket_nonblocking(fd);
	setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (char*)&on, sizeof(on));
	evutil_make_listen_socket_reuseable(fd);
	setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, (char*)&off, (ev_socklen_t)sizeof(off));
	bind(fd, (sockaddr*)&sin, sizeof(sin));
	listener = evconnlistener_new(net_evbase, ServerAccept, nullptr,
									   LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE, -1, fd);
```

Doing this on windows instead will error out
```cpp
	event_base* net_evbase = event_base_new();
	sockaddr_in6 sin;
	memset(&sin, 0, sizeof(sin));
	sin.sin6_family = AF_INET6;
	evutil_inet_pton(AF_INET6, "::", &sin.sin6_addr);
	sin.sin6_port = htons(7911);
	listener = evconnlistener_new_bind(net_evbase, ServerAccept, nullptr,
									   LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE, -1, (sockaddr*)&sin, sizeof(sin));
	evutil_socket_t fd = evconnlistener_get_fd(listener);
	int off = 0;
	setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, (char*)&off, (ev_socklen_t)sizeof(off));
```

**Comment by azat** [comment]
>It would be nice to have libevent keep a consistent behaviour across the platforms in this scenario

Agree.

> maybe or by making it always set IPV6_V6ONLY to false unless LEV_OPT_BIND_IPV6ONLY is passed

Let's do this, i.e. make behavior under windows the same as under linux right now. Can you send a patch?
