### ISSUE TITLE
Windows libevent deadlocks using pthread

### ISSUE THREAD

**Issue by X-Crack** [libevent/libevent#1192]
Development IDE: vs2019
Development platform: windows 10
libevent version: release-2.1.12-stable
Error function: static void
accepted_socket_invoke_user_cb(struct event_callback *dcb, void *arg)
Open macro settings: #define EVENT__HAVE_PTHREADS 1
Code file: listener.c Number of lines: 622 lines
-----------------------------------------------------

Third-party libraries used: https://sourceforge.net/projects/pthreads4w/files/pthreads4w-code-v3.0.0.zip/download

At present, in the above line of code, a deadlock situation has occurred, and it stays at WAIT_OBJECT_0 != WaitForSingleObject (mx->event, INFINITE)

Can't windows use pthread(windows) version library?

**Comment by ploxiln** [comment]
I hadn't heard of "pthreads4w" before, likely nobody used it with libevent before. You would probably have to debug it yourself, and submit patches to both "pthreads4w" and libevent, which might be accepted if they are clean and make sense. Anyway, on windows you should use [`evthread_use_windows_threads()`](http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/thread_8h.html#a1b0fe36dcb033da2c679d39ce8a190e2) instead. Or, don't use threads, stick to pure event-based code :)

**Comment by X-Crack** [comment]
> I hadn't heard of "pthreads4w" before, likely nobody used it with libevent before. You would probably have to debug it yourself, and submit patches to both "pthreads4w" and libevent, which might be accepted if they are clean and make sense. Anyway, on windows you should use [`evthread_use_windows_threads()`](http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/thread_8h.html#a1b0fe36dcb033da2c679d39ce8a190e2) instead. Or, don't use threads, stick to pure event-based code :)

I cannot reach the author of the library.

This pthread windows version of the library began in 2002.

Please help contact and fix the error!

https://sourceware.org/pthreads-win32/
