### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by Mingli-Yu** [libevent/libevent#1193]
```
# ./test.sh
Running tests:
EVPORT 
Skipping test
KQUEUE 
Skipping test
EPOLL 
 test-eof: OKAY
 test-dumpevents: OKAY (output not checked)
 regress: 
  FAIL ../libevent-2.1.12-stable/test/regress_util.c:1478: assert(diff.tv_sec == 0): 1 vs 0 util/monotonic_prc_fallback: 
  [monotonic_prc_fallback FAILED]
1/312 TESTS FAILED. (33 skipped)
FAILED
 regress_debug: 
  FAIL ../libevent-2.1.12-stable/test/regress_util.c:1478: assert(diff.tv_sec == 0): 1 vs 0 util/monotonic_prc_fallback: 
  [monotonic_prc_fallback FAILED]
1/312 TESTS FAILED. (33 skipped)
FAILED
DEVPOLL 
Skipping test
POLL 
 test-eof: OKAY
 test-dumpevents: OKAY (output not checked)
[snip]
```

**Comment by azat** [comment]
This is a known flaky test issue, that is time related

**Comment by azat** [comment]
Do you have something specific in your env? Does it fails always? Increasing timeout on the asserted lines fixes the issue?

**Comment by Mingli-Yu** [comment]
No, don't set specific env and it always fails.

**Comment by Mingli-Yu** [comment]
The libevent version is 2.1.12.

**Comment by Mingli-Yu** [comment]
Hi @azat, 
Any hint to resolve the issue? Thanks,

**Comment by azat** [comment]
>The libevent version is 2.1.12.

Ok, the code is - https://github.com/libevent/libevent/blob/release-2.1.12-stable/test/regress_util.c#L1478
So looks like a great inaccuracy in your system.

Some of tests that uess test_evutil_monotonic_prc had been marked with TT_RETRIABLE in 6ea1ec68cedbc8ae64b, but these will not help you.

Ok, what is your environment and your system?
Also can you post output of strace-like output for `regress/test --no-fork monotonic_prc_fallback`

**Comment by Mingli-Yu** [comment]
# ./regress --no-fork monotonic_prc_fallback
No such test as monotonic_prc_fallback!

\# ls -l
total 924
-rwxr-xr-x 1 root root  14376 Aug 31 08:42 bench
-rwxr-xr-x 1 root root  14384 Aug 31 08:42 bench_cascade
-rwxr-xr-x 1 root root  14376 Aug 31 08:42 bench_http
-rwxr-xr-x 1 root root  14384 Aug 31 08:42 bench_httpclient
-rwxr-xr-x 1 root root 722896 Aug 31 08:42 regress
-rwxr-xr-x 1 root root  14384 Aug 31 08:42 test-changelist
-rwxr-xr-x 1 root root  14392 Aug 31 08:42 test-closed
-rwxr-xr-x 1 root root  14384 Aug 31 08:42 test-dumpevents
-rwxr-xr-x 1 root root  14400 Aug 31 08:42 test-eof
-rwxr-xr-x 1 root root  14376 Aug 31 08:42 test-fdleak
-rwxr-xr-x 1 root root  14376 Aug 31 08:42 test-init
-rwxr-xr-x 1 root root  22968 Aug 31 08:42 test-ratelim
-rwxr-xr-x 1 root root  14376 Aug 31 08:42 test-time
-rwxr-xr-x 1 root root  14384 Aug 31 08:42 test-weof

**Comment by azat** [comment]
># ./regress --no-fork monotonic_prc_fallback

```
./regress --no-fork util/monotonic_prc_fallback
```

**Comment by Mingli-Yu** [comment]
\# ls
bench	       bench_http	 regress	  test-closed	   test-eof	test-init     test-time
bench_cascade  bench_httpclient  test-changelist  test-dumpevents  test-fdleak	test-ratelim  test-weof

\# ./regress --no-fork util/monotonic_prc_fallback
util/monotonic_prc_fallback: OK
1 tests ok.  (0 skipped)

\# cd ..
\# ls -a
.  ..  .libs  test.sh

\# ./test.sh
Running tests:
EVPORT 
Skipping test
KQUEUE 
Skipping test
EPOLL 
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY (output not checked)
 regress: 
  FAIL ../libevent-2.1.12-stable/test/regress_util.c:1478: assert(diff.tv_sec == 0): 1 vs 0util/monotonic_prc_fallback: 
  [monotonic_prc_fallback FAILED]
1/312 TESTS FAILED. (33 skipped)
FAILED
 regress_debug: 
  FAIL ../libevent-2.1.12-stable/test/regress_util.c:1478: assert(diff.tv_sec == 0): 1 vs 0util/monotonic_prc_fallback: 
  [monotonic_prc_fallback FAILED]

**Comment by azat** [comment]
```
# ./regress --no-fork util/monotonic_prc_fallback
util/monotonic_prc_fallback: OK
1 tests ok. (0 skipped)
```

Good, it does not fails when it is executed separately.
And also it does not fails under POLL.
Let's try these - 04fcd7c6df158bb65261867de4b9ec8439696934 (I though that it has been marked TT_RETRIABLE already, but that was another test)

**Comment by azat** [comment]
Refs: #776

**Comment by azat** [comment]
>Let's try these - 04fcd7c (I though that it has been marked TT_RETRIABLE already, but that was another test)

@Mingli-Yu can you check does retries helped or not? (also there is a `--retries` and `--retries-delay` arguments)

**Comment by Mingli-Yu** [comment]
@azat  Thanks very much for your follow-up!
After apply https://github.com/libevent/libevent/commit/04fcd7c6df158bb65261867de4b9ec8439696934, the test result as below:
\# ./test.sh 
Running tests:
EVPORT 
Skipping test
KQUEUE 
Skipping test
EPOLL 
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY (output not checked)
 regress: OKAY
 regress_debug: OKAY
DEVPOLL 
Skipping test
POLL 
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY (output not checked)
 regress: 
  FAIL ../libevent-2.1.12-stable/test/regress_util.c:1478: assert(diff.tv_sec == 0): 1 vs 0util/monotonic_prc_fallback: 
  [monotonic_prc_fallback FAILED]

  [RETRYING monotonic_prc_fallback (3)]
OKAY
 regress_debug: OKAY
SELECT 
 test-eof: OKAY
 test-closed: [warn] event_base_new_with_config: no event mechanism available
OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY (output not checked)
 regress: OKAY
 regress_debug: OKAY
WIN32 
Skipping test

**Comment by azat** [comment]
So now it works, right? (since the first failure is ok, it had been retried after)

**Comment by Mingli-Yu** [comment]
https://www.mail-archive.com/openembedded-core@lists.openembedded.org/msg153389.html

**Comment by tprrt** [comment]
Hi,
I also applied this proposed patch and unfortunately the issue is still occurring, but the occurrence is lower.

**Comment by kanavin** [comment]
I think the output from the test suite needs to be adjusted, specifically this bit:
```
regress:
FAIL ../libevent-2.1.12-stable/test/regress_util.c:1478: assert(diff.tv_sec == 0): 1 vs 0util/monotonic_prc_fallback:
[monotonic_prc_fallback FAILED]

[RETRYING monotonic_prc_fallback (3)]
OKAY
```
It should not say that something failed, until it really has - if something is going to be retried, just be quiet.

**Comment by tprrt** [comment]
Then the same issue can occurs with all tests that use the flag TT_RETRIABLE.

I think also the output should be adjusted, retriable tests should be marked failed only when all attempts have failed.
