### ISSUE TITLE
evbuffer_add_reference()  allocate unnecessary memory

### ISSUE THREAD

**Issue by moonlightsh** [libevent/libevent#1198]
Hello, 
When `evbuffer_add_reference()` was called by user, a new `evbuffer chain` was created by `evbuffer_chain_new(sizeof(struct evbuffer_chain_reference))`. `evbuffer_chain_new()` then will alloc `MIN_BUFFER_SIZE`(512 on x86 and 1024 on x64) bytes. And then the reference chain will not use when the user add new data user `evbuffer_add()` event if `evbuffer_add_reference()`.  
I think it will allocate too much memory when  plenty of references and to the buffer.

https://github.com/libevent/libevent/blob/7459407701e89f11688194ce6baa4c66a381cb00/buffer.c#L2930-L2945

https://github.com/libevent/libevent/blob/7459407701e89f11688194ce6baa4c66a381cb00/buffer.c#L152-L172

**Comment by azat** [comment]
@moonlightsh seems you are right, can you send a PR with a patch that will address these? it is pretty simple - don't do any allocations over for read-only chains
