### ISSUE TITLE
How to handle "slow client read" properly?

### ISSUE THREAD

**Issue by t7ko-seagate** [libevent/libevent#1211]
Hi @azat,

Can you clarify this statement below?  You commented in some of older issues.

I'm hitting this exact scenario: I have asynchronous data source, which I have to pipe to client.  Clients are sometimes slow, i.e. reading out slower than data source provides the data.  So the data piles up in RAM.

After reading docs, I found watermark callbacks -- which seems to solve the issue perfectly.  Flow would be: once data source provides next chunk of data -- check how much is accumulated in outgoing buffer.  If too much already -- put source on pause.  Subscribe to low watermark callback.  Once outgoing buffer is below the watermark, i.e. callback is triggered -- un-pause data source and start reading next chunk.

But now I'm confused by this comment you made, where you discourage using watermark callbacks.  If watermark is not OK to use -- which method do you recommend then?

Thanks in advance.

>> Could you please explain why cllient slow read is related to the problem?
>
>If the client reads the data slowly, but server always adds new data, then server will need to keep in memory.
>
> There is `bufferevent_setwatermark()`, but I guess that it will introduce more problem then it solves for the http layer. So I'm not recommending it.

_Originally posted by @azat in https://github.com/libevent/libevent/issues/862#issuecomment-517479726_

**Comment by azat** [comment]
Hi @t7ko-seagate 

>There is bufferevent_setwatermark(), but I guess that it will introduce more problem then it solves for the http layer. So I'm not recommending it.

Actually thinking about this a little bit more deeply and I guess it is a good use case for watermarks (I was not recommended to use it with http layer in particular, but even this should be fine).

You will need to use buferevent_pair_new to add dependency between different bufferevents.

If you will have further questions you can write a simple demo that will proxy the data using this pattern and post it here and I will take a look.

**Comment by t7ko-seagate** [comment]
ok thanks for confirming.  I'll close this issue for now, and will re-open if I have anything to add.  Thanks!
