### ISSUE TITLE
Do I have the option of generating package config (*.pc) files when building from source?

### ISSUE THREAD

**Issue by mbilyanov** [libevent/libevent#1215]
Hi,

How to get the `./configure` script also generate the PKG_CONFIG entries for libevent when building from source?

Into here:
`PKG_CONFIG_PATH=$HOME/locals/lib/pkgconfig`

Thanks,
Milen

**Comment by mbilyanov** [comment]
Ah, I can see the `*.cp` files are placed within the library's lib folder:

`/home/me/locals/lib64/libevent-2.1.12-gcc-9.3.0/lib/pkgconfig`

So we simply manually copy them to the global `PKG_CONFIG` repository path, which in my case is:
`PKG_CONFIG_PATH=$HOME/locals/lib/pkgconfig`
?

**Comment by ploxiln** [comment]
If you ran configure with `--prefix=$HOME/locals` then the pkg-config files would be installed to `$HOME/locals/lib/pkgconfig`. But it looks like you ran configure with `--prefix=$HOME/locals/libevent-2.1.12-gcc-9.3.0`. Having built it that way, you could theoretically build multiple versions of libevent, or with different compilers, and then choose between them with `PKG_CONFIG_PATH=$HOME/locals/libevent-$VERSION-$COMPILER/lib/pkgconfig:$PKG_CONFIG_PATH` ...

Go ahead and copy around the .pc files from the install dir you chose to your shared locals dir if you want, that should be fine.

**Comment by mbilyanov** [comment]
Thank you for the helpful and clear explanation.
