### ISSUE TITLE
evdns crashes in parse_request on malformed DNS packets

### ISSUE THREAD

**Issue by konstk1** [libevent/libevent#1231]
When a malformed DNS packet or some random data is received on port 53, `parse_request()`, `GET16` macros can jump to `err` label. The code in `err` label tries to access `server_req->base.questions`. However, at the point where `GET16` macros get used, `server_req` has not been allocated it. This causes a segmentation fault.

**Comment by azat** [comment]
Thanks, there was a report in #382 from some static analyzer (`µchex`), that was wrong, I've reverted that patch.
