### ISSUE TITLE
Windows unresolved external reference Build Errors

### ISSUE THREAD

**Issue by avlec** [libevent/libevent#1232]
I am including libevent in a Visual Sudio CMake project via the following as part of my CMakeLists.txt. However, I am getting the following errors. Building the project by itself in Visual Studio with the same settings (below) used in the CMake project seems to work just fine.

```
event_core.lib(event.c.obj) : error LNK2019: unresolved external symbol __imp__strdup referenced in function event_mm_strdup_
event_core.lib(evutil.c.obj) : error LNK2019: unresolved external symbol __imp__getpid referenced in function evutil_weakrand_seed_
event_core.lib(evutil_rand.c.obj) : error LNK2001: unresolved external symbol __imp__getpid
event_core.lib(evutil.c.obj) : error LNK2019: unresolved external symbol __imp___stdio_common_vsscanf referenced in function _vsscanf_l
event_core.lib(evutil.c.obj) : error LNK2019: unresolved external symbol __imp__fstat64 referenced in function evutil_read_file_
event_core.lib(evutil_time.c.obj) : error LNK2019: unresolved external symbol __imp__time64 referenced in function evutil_date_rfc1123
event_core.lib(log.c.obj) : error LNK2019: unresolved external symbol __imp_strerror referenced in function event_err
```
```cmake
set(EVENT__LIBRARY_TYPE "STATIC")
set(EVENT__DISABLE_BENCHMARK ON)
set(EVENT__DISABLE_REGRESS ON)
set(EVENT__DISABLE_SAMPLES ON)
set(EVENT__DISABLE_TESTS ON)
add_subdirectory(libevent)
```

Edit: I will not I am linking this to a C++ project.

**Comment by azat** [comment]
Hi!

I'm not a windows expert, but I guess that this issues is not libevent-specific, and pretty generic, so you can google it.
BTW if you try shared build, does it works?

**Comment by avlec** [comment]
I was looking around for several hours earlier and found the solution. This msvc compiler option seemed to resolve the issue https://docs.microsoft.com/en-us/cpp/build/reference/zl-omit-default-library-name?view=msvc-170. When I compile my project without libevent using that flag I get many linker errors from my projects side, which means there's some weird inter-dependencies somehow. I am not familiar enough with the build process to understand what could be going wrong there.
