### ISSUE TITLE
Problems with OpenSSL 3.0

### ISSUE THREAD

**Issue by Destroyinator69420** [libevent/libevent#1233]
"sample/le-proxy.c: In function ‘eventcb’:
sample/le-proxy.c:116:9: warning: ‘ERR_func_error_string’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  116 |         ERR_func_error_string(err);
      |         ^~~~~~~~~~~~~~~~~~~~~
In file included from sample/le-proxy.c:35:
/usr/local/include/openssl/err.h:447:35: note: declared here
  447 | OSSL_DEPRECATEDIN_3_0 const char *ERR_func_error_string(unsigned long e);
      |                                   ^~~~~~~~~~~~~~~~~~~~~"
and,
"In file included from test/regress.h:35,
                 from test/regress_buffer.c:64:
test/regress_buffer.c: In function ‘test_evbuffer_pullup_with_empty’:
test/tinytest_macros.h:116:15: warning: cast from function call of type ‘unsigned char *’ to non-matching type ‘long int’ [-Wbad-function-cast]
  116 |  type val1_ = (type)(a);      \
      |               ^
test/tinytest_macros.h:144:2: note: in expansion of macro ‘tt_assert_test_fmt_type’
  144 |  tt_assert_test_fmt_type(a,b,str_test,type,test,type,fmt, \
      |  ^~~~~~~~~~~~~~~~~~~~~~~
test/tinytest_macros.h:158:2: note: in expansion of macro ‘tt_assert_test_type’
  158 |  tt_assert_test_type(a,b,#a" "#op" "#b,long,(val1_ op val2_), \
      |  ^~~~~~~~~~~~~~~~~~~
test/regress_buffer.c:444:2: note: in expansion of macro ‘tt_int_op’
  444 |  tt_int_op(evbuffer_pullup(buf, -1), ==, NULL);
      |  ^~~~~~~~~
  CC       test/regress-regress_bufferevent.o
  CC       test/regress-regress_dns.o
^Cmake[1]: *** [Makefile:1988: test/regress-regress_dns.o] Interrupt
make: *** [Makefile:2801: install] Interrupt"

 I compiled on debian bullseye for x86-64, all other files compiled normally.

All the best,
Destroyinator69420

Edit: I was using the latest GCC ten in the debain package repository.

**Comment by ploxiln** [comment]
libevent needs changes to work with openssl-3.0
see also #1212
