### ISSUE TITLE
Problems with debain bullseye, openssl 1.1.1l, and gcc 10

### ISSUE THREAD

**Issue by Destroyinator69420** [libevent/libevent#1234]
In file included from test/regress.h:35,
                 from test/regress_buffer.c:64:
test/regress_buffer.c: In function ‘test_evbuffer_pullup_with_empty’:
test/tinytest_macros.h:116:15: warning: cast from function call of type ‘unsigned char *’ to non-matching type ‘long int’ [-Wbad-function-cast]
  116 |  type val1_ = (type)(a);      \
      |               ^
test/tinytest_macros.h:144:2: note: in expansion of macro ‘tt_assert_test_fmt_type’
  144 |  tt_assert_test_fmt_type(a,b,str_test,type,test,type,fmt, \
      |  ^~~~~~~~~~~~~~~~~~~~~~~
test/tinytest_macros.h:158:2: note: in expansion of macro ‘tt_assert_test_type’
  158 |  tt_assert_test_type(a,b,#a" "#op" "#b,long,(val1_ op val2_), \
      |  ^~~~~~~~~~~~~~~~~~~
test/regress_buffer.c:444:2: note: in expansion of macro ‘tt_int_op’
  444 |  tt_int_op(evbuffer_pullup(buf, -1), ==, NULL);
      |  ^~~~~~~~~"

and

In file included from test/regress.h:35,
                 from test/regress_buffer.c:64:
test/regress_buffer.c: In function ‘test_evbuffer_pullup_with_empty’:
test/tinytest_macros.h:116:15: warning: cast from function call of type ‘unsigned char *’ to non-matching type ‘long int’ [-Wbad-function-cast]
  116 |  type val1_ = (type)(a);      \
      |               ^
test/tinytest_macros.h:144:2: note: in expansion of macro ‘tt_assert_test_fmt_type’
  144 |  tt_assert_test_fmt_type(a,b,str_test,type,test,type,fmt, \
      |  ^~~~~~~~~~~~~~~~~~~~~~~
test/tinytest_macros.h:158:2: note: in expansion of macro ‘tt_assert_test_type’
  158 |  tt_assert_test_type(a,b,#a" "#op" "#b,long,(val1_ op val2_), \
      |  ^~~~~~~~~~~~~~~~~~~
test/regress_buffer.c:444:2: note: in expansion of macro ‘tt_int_op’
  444 |  tt_int_op(evbuffer_pullup(buf, -1), ==, NULL);
      |  ^~~~~~~~~
  CC       test/regress-regress_bufferevent.o
  CC       test/regress-regress_dns.o
test/regress_dns.c: In function ‘test_bufferevent_connect_hostname’:
test/regress_dns.c:1391:9: warning: ‘be[0]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1391 |   if (be[i])
      |       ~~^~~
test/regress_dns.c:1391:9: warning: ‘be[0]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  CC       test/regress-regress_et.o
  CC       test/regress-regress_finalize.o
  CC       test/regress-regress_http.o
In file included from test/regress.h:35,
                 from test/regress_buffer.c:64:
test/regress_buffer.c: In function ‘test_evbuffer_pullup_with_empty’:
test/tinytest_macros.h:116:15: warning: cast from function call of type ‘unsigned char *’ to non-matching type ‘long int’ [-Wbad-function-cast]
  116 |  type val1_ = (type)(a);      \
      |               ^
test/tinytest_macros.h:144:2: note: in expansion of macro ‘tt_assert_test_fmt_type’
  144 |  tt_assert_test_fmt_type(a,b,str_test,type,test,type,fmt, \
      |  ^~~~~~~~~~~~~~~~~~~~~~~
test/tinytest_macros.h:158:2: note: in expansion of macro ‘tt_assert_test_type’
  158 |  tt_assert_test_type(a,b,#a" "#op" "#b,long,(val1_ op val2_), \
      |  ^~~~~~~~~~~~~~~~~~~
test/regress_buffer.c:444:2: note: in expansion of macro ‘tt_int_op’
  444 |  tt_int_op(evbuffer_pullup(buf, -1), ==, NULL);
      |  ^~~~~~~~~  CC       test/regress-regress_listener.o
^Cmake[1]: *** [Makefile:2044: test/regress-regress_listener.o] Interrupt
make: *** [Makefile:2801: install] Interrupt

All the best,
Destroyinator69420

**Comment by azat** [comment]
>test/regress_dns.c:1391:9: warning: ‘be[0]’ may be used uninitialized in this function [-Wmaybe-uninitialized]

This has been fixed in 2338f27e694f7
What is the version of libevent that you are trying to build?

>test/tinytest_macros.h:116:15: warning: cast from function call of type ‘unsigned char *’ to non-matching type ‘long int’ [-Wbad-function-cast]
>444 | tt_int_op(evbuffer_pullup(buf, -1), ==, NULL);

This has been fixed in 53e53b018bd6ac967b5
