### ISSUE TITLE
remove suffix suffix shared library

### ISSUE THREAD

**Issue by manang** [libevent/libevent#1240]
is it a way to remove the version suffix?
I think about a cmake config parameter.
Thanks a lot
Angelo

**Comment by manang** [comment]
I compiled the libs for android, when I generate the apk, the sdk put inside two libs per every type, with and without the version.
but, as output of the compilation of libevent I obtain the library with the version as suffix and a symlink without the version.
I want to avoid to copy twice the lib in my final app.
Thanks

**Comment by azat** [comment]
Maybe you can switch to static library? They don't have versions.

>the sdk put inside two libs

I think that this is pretty generic case and it should be resolved in android env somehow, but I don't have any experience here.

**Comment by manang** [comment]
I want to avoid to have a big library, it needs time to load.
thanks for you help
