### ISSUE TITLE
A potential memory leak

### ISSUE THREAD

**Issue by ryancaicse** [libevent/libevent#1242]
It seems the memory (Line 1678) is leaked when going to Line 1685 and returning at Line 1697
https://github.com/libevent/libevent/blob/048907a501e2ee106cd9dabf6686697f3b73b562/test/regress_http.c#L1678-L1697

**Comment by ploxiln** [comment]
If it's in a unit test that fails, that seems like not a real problem.

**Comment by ryancaicse** [comment]
Thank you for your reply. Yes, that's not a serious problem.

**Comment by azat** [comment]
Yes, it is a not real problem, but let's fix it anyway.
P.S. the tests that using this code is not reliable though.
