### ISSUE TITLE
EVLOOP_ONCE - does not wait for events

### ISSUE THREAD

**Issue by Latorius** [libevent/libevent#1244]
Sorry, please, let me ask a question - I still could not understand - this is a mistake or the correct behavior:

From the training book it says: https://www.seul.org/~nickm/libevent-book/Ref3_eventloop.html

> f EVLOOP_ONCE is set, then the loop will wait until some events become active, then run active events until there are no more to run, then return.

But this simple code says that the flag does not work as stated (for Windows/VS2019) - it does not wait for events, and if there are none, it ends immediately: 

```
   #include <iostream>

   #include <event2/bufferevent.h>
   #include <event2/buffer.h>
   #include <event2/event.h>
 
 
    //include Windows DDL-lib:
   #pragma comment(lib, "Normaliz.lib")
   #pragma comment(lib, "Ws2_32.lib")
   #pragma comment(lib, "Wldap32.lib")
   #pragma comment(lib, "Crypt32.lib")
   #pragma comment(lib, "advapi32.lib")
   #pragma comment(lib, "Iphlpapi.lib")
 
 
 
    int main()
    {
       //----------------------------------------------------------------
        WORD my_version_Winsock = MAKEWORD(2, 2);
        WSADATA my_wsadata_struct;
 
        int my_WSAStartup = WSAStartup(my_version_Winsock, &my_wsadata_struct);  
        //----------------------------------------------------------------
 
 
        struct event_base* Event_base = event_base_new();        
 
        event_base_loop(Event_base, EVLOOP_ONCE ); //we start a loop, which theoretically, if I understood correctly, should wait for at least one event.

        //However, event_base_loop does not wait for any events and ends immediately.

        event_base_free(Event_base);  
    }
```

Moreover, if I change the EVLOOP_ONCE flag to EVLOOP_NO_EXIT_ON_EMPTY, then the loop spins endlessly, as stated for the EVLOOP_NO_EXIT_ON_EMPTY flag.
But the EVLOOP_ONCE flag does not wait for events, but exits immediately. It turns out that EVLOOP_ONCE is not working correctly, not as stated in the documentation?

I ask you to excuse me in advance if I misunderstood how the EVLOOP_ONCE flag should work.

**Comment by azat** [comment]
Sorry for the delay.

>But the EVLOOP_ONCE flag does not wait for events, but exits immediately

Yes, this is correct behaviour.

https://github.com/libevent/libevent/blob/78fa3971be892194aa168c04fc34bf5f2cd99b99/include/event2/event.h#L807-L809

"Block until we have an active event" in other words if there are no active events, it will exit, here:

https://github.com/libevent/libevent/blob/78fa3971be892194aa168c04fc34bf5f2cd99b99/event.c#L2008

You can get more details by enable debug logging:

```c
#include <event2/event.h>

int main()
{
    struct event_base *base = event_base_new();
    event_enable_debug_logging(EVENT_DBG_ALL);
    event_base_loop(base, EVLOOP_ONCE);
    event_base_free(base);
    return 0;
}
```

```sh
$ gcc -levent_core -o /tmp/le-test /tmp/le-test.c
$ /tmp/le-test
[debug] event_base_loop: no events registered.
[debug] event_base_free_: 0 events freed
```
