### ISSUE TITLE
SSL_shutdown for evhttp_connection

### ISSUE THREAD

**Issue by snaami** [libevent/libevent#1247]
Hello All, I was using `evhttp_connection/evhttp_request`  API to implement a simple HTTPS client, what I found that when the request detect (Connection:close) in the HTTP packet it will close the TCP connection, but the issue is it send TCP-FIN without shutting down the SSL connection on the socket, I was trying to figure out how to do this myself, but it seems the connection is closed before even calling the user callback, so there is no possibility to use `SSL_shutdown` in the user code and trying to cleanly close the connection (I don't even know if that is possible), In my case the server treat this as a lost connection.

**Comment by azat** [comment]
Hi!

> In my case the server treat this as a lost connection.

Yes, sounds pretty bad.

But right now it is not possible.
There was some discussion about this in https://github.com/libevent/libevent/issues/943#issuecomment-580313812

**Comment by snaami** [comment]
Thank you for the reply,  I tried also to do some dirty hacks and do the ssl_shutdown in the evhttp_connection closecb, and it was a total randomness It sometimes works. After many trial and error I decided to use libwebsockets for the http stuff and keep libevent for eventlooping only (sad I found the libevent approach more convenient to me).

**Comment by azat** [comment]
Ok, let's close it, there is already issues for this anyway.
