### ISSUE TITLE
automake scripts were recently broken by mbedtls fix

### ISSUE THREAD

**Issue by saurik** [libevent/libevent#1251]
In 78fa3971be892194aa168c04fc34bf5f2cd99b99 from https://github.com/libevent/libevent/pull/1241#commitcomment-63865496 a new "if MBEDTLS" block was added to include/include.am. This is not parsed by automake as it isn't on the first column, resulting in a subsequent error in the build.

https://www.gnu.org/software/automake/manual/html_node/Usage-of-Conditionals.html

> The if, else, and endif statements should not be indented, i.e., start on column one.

The following patch fixes this issue:

```diff
diff --git a/include/include.am b/include/include.am
index 93f32f1a..8a5bd026 100644
--- a/include/include.am
+++ b/include/include.am
@@ -36,9 +36,9 @@ EVENT2_EXPORT = \
 if OPENSSL
 EVENT2_EXPORT += include/event2/bufferevent_ssl.h
 else
-    if MBEDTLS
-    EVENT2_EXPORT += include/event2/bufferevent_ssl.h
-    endif
+if MBEDTLS
+EVENT2_EXPORT += include/event2/bufferevent_ssl.h
+endif
 endif

 ## Without the nobase_ prefixing, Automake would strip "include/event2/" from
```

**Comment by azat** [comment]
Thanks, patch applied!
