### ISSUE TITLE
Working with serial port windows

### ISSUE THREAD

**Issue by bash098** [libevent/libevent#1252]
I am creating and initialize serial com port next:

```c
int InitFd()
	{
	    printf("com %s\n", comDev.c_str());
	    HANDLE hSerial = CreateFile(comDev.c_str(), // COM2
					GENERIC_READ | GENERIC_WRITE,
					0,
					0,
					OPEN_EXISTING,
					FILE_ATTRIBUTE_DEVICE,
					0);

	    if(hSerial == INVALID_HANDLE_VALUE)
	    {
		if(GetLastError() == ERROR_FILE_NOT_FOUND)
		    printf("serial port does not exist. Inform user.\n");

		return -1;
	    }

	    DCB dcbSerialParams;
	    dcbSerialParams.DCBlength = sizeof(dcbSerialParams);
	    if(!GetCommState(hSerial, &dcbSerialParams))
	    {
		printf("error getting state\n");
		return -1;
	    }

	    dcbSerialParams.BaudRate = CBR_9600;
	    dcbSerialParams.ByteSize = 8;
	    dcbSerialParams.Parity = NOPARITY;
	    dcbSerialParams.StopBits = ONESTOPBIT;
	    if(!SetCommState(hSerial, &dcbSerialParams))
	    {
		printf("error setting serial port state\n");
		return -1;
	    }

	    int fd = _open_osfhandle((intptr_t) hSerial, O_RDWR | O_BINARY);
	    bufferevent_setfd(bev.get(), fd);

	    return fd;
	}
```

But after writing data, dispatch break.

```c
DWORD feedback;
// if(WriteFile((HANDLE)_get_osfhandle(bufferevent_getfd(bev.get())), data, size, &feedback, 0))
if(bufferevent_write_buffer(bev, evb) == 0)
{
		PrintBuffer(data, size, "-->");

		bufferevent_enable(bev, EV_READ);

		bufferevent_setwatermark(bev, EV_READ, 1, 256);

		struct timeval tv = {1, 0};
		bufferevent_set_timeouts(bev, &tv, NULL);
	    }
}
```

May be I initialized com port wrong?

**Comment by azat** [comment]
I don't familiar with COM ports and how they differs from regular socket (if any).
For example are the poll'able (`select()`) ?
And you can also check yourself by replacing com port with regular socket and see if it will work.

**Comment by bash098** [comment]
At the linux, working with /dev/ser is good, I can open port, like a file and select it for read/write/error. 
At the windows, there are some mechanism for select com ports.

Sockets at windows work good.

Понедельник, 28 февраля 2022, 8:15 +03:00 от Azat Khuzhin ***@***.***>:
>I don't familiar with COM ports and how they differs from regular socket (if any).
>For example are the poll'able (select()) ?
>And you can also check yourself by replacing com port with regular socket and see if it will work.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <libevent/libevent/issues/1252/1053898957 @ github . com>

--
Эльдар Карамышев
Отправлено из Почты  Mail.ru

**Comment by azat** [comment]
Is there any strace-like analog on windows? It can show the problem.
Also you can enable debug logging in libevent, `event_enable_debug_logging(EVENT_DBG_ALL)`.

**Comment by bash098** [comment]
I will try enable debug logging.
Idk about strace.

Понедельник, 28 февраля 2022, 8:29 +03:00 от Azat Khuzhin ***@***.***>:
>Is there any strace-like analog on windows? It can show the problem.
>Also you can enable debug logging in libevent, event_enable_debug_logging(EVENT_DBG_ALL).
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <libevent/libevent/issues/1252/1053905340 @ github . com>

--
Эльдар Карамышев
Отправлено из Почты  Mail.ru

**Comment by ploxiln** [comment]
On Windows, `select()` only works on sockets. It doesn't work on handles from regular files, pipes (e.g. stdin/stdout/stderr), devices, or anything else. Only sockets. This also applies to `WSAPoll` and "wepoll", they only work with sockets.

IOCP _can_ work with regular files, and with serial ports, apparently: https://stackoverflow.com/questions/673896/serial-comms-via-iocp (but I'm not sure how limited libevent's support for IOCP is ... it is a very different model which is difficult to adapt ...)

**Comment by bash098** [comment]
[debug] event_add: event: 00000000007D1AC0 (fd -1),    EV_TIMEOUT call 00000000004081D0
[debug] event_add: event 00000000007D1AC0, timeout in 1 seconds 0 useconds, call 00000000004081D0
[debug] event_active: 00000000007D6F40 (fd -1), res 0, callback 0000000000408350
[debug] event_del: 00000000007D6F40 (fd -1), callback 0000000000408350
[debug] event_process_active: event: 00000000007D6F40,    call 0000000000408350
[debug] event_del: 00000000007D1BA0 (fd -1), callback 0000000067ECFB90
[debug] event_del: 00000000007D1C18 (fd -1), callback 0000000067ECF720
[debug] event_add: event: 00000000007D1C18 (fd 3),  EV_WRITE   call 0000000067ECF720
[debug] win32_add: adding event for 3
[debug] event_add: event: 00000000007D1BA0 (fd 3), EV_READ    call 0000000067ECFB90
[debug] win32_add: adding event for 3
[debug] event_add: event: 00000000007D1BA0 (fd 3), EV_READ    call 0000000067ECFB90
[debug] event_add: event: 00000000007D1BA0 (fd 3), EV_READ   EV_TIMEOUT call 0000000067ECFB90
[debug] event_add: event 00000000007D1BA0, timeout in 1 seconds 0 useconds, call 0000000067ECFB90
[debug] event_remove_timer_nolock: event: 00000000007D1C18
[debug] timeout_next: event: 00000000007D1AC0, in 0 seconds, 999972 useconds
[debug] win32_dispatch: select returned -1
[debug] win32_dispatch: [WinError 10038] an operation was attempted on something that is not a socket
[debug] event_base_loop: dispatch returned unsuccessfully.
[debug] event_callback_finalize_many_: 3 events finalizing
[debug] event_del: 00000000007D1BA0 (fd 3), callback 0000000067ECFB90
[debug] win32_del: Removing event for 3
[debug] event_del: 00000000007D1C18 (fd 3), callback 0000000067ECF720
[debug] win32_del: Removing event for 3
[debug] event_del: 00000000007D1BA0 (fd 3), callback 0000000067ECFB90
[debug] event_del: 00000000007D1AC0 (fd -1), callback 00000000004081D0
[debug] event_del: 00000000007D6F40 (fd -1), callback 0000000000408350
[debug] event_del: 00000000007D1BA0 (fd 3), callback 0000000067ECB870
[debug] event_base_free_: 1 events freed
[debug] event_base_free_: 0 events freed
[debug] event_base_free_: 1 events were still set in base

**Comment by bash098** [comment]
I see, that creating a fd via CreateFile(...) and bufferevent_setfd(fd); is bad idea. This fd can't be select like socket.
@ploxiln wrote correct things about WSAPoll. Thanks for your answers.
