### ISSUE TITLE
is event_base_loop() function thread safe even if called on different event_base variables

### ISSUE THREAD

**Issue by harryl2021** [libevent/libevent#1255]
Recently I checked my code base that make use of **libevent** library for any synchronization errors. In the **helgrind** log it's been reported that there exists a data race of size 4 bytes for when one thread calls **event_base_loop(base_pub, EVLOOP_NONBLOCK);** and another thread calls **event_base_loop(base_sub, 0);**. The address where the data race is reported is part of **BSS**. Can somebody explain whether this data race really exists?

**Comment by azat** [comment]
Hi.

If you have `event_base` per thread it should be thread safe.

Can you share the helgrind report?
