### ISSUE TITLE
 Import of C++ module 'libevent.evutil' appears within extern "C" language linkage specification

### ISSUE THREAD

**Issue by Syedh30** [libevent/libevent#1263]
Pod -> libevent - >  @file event.h line 55

#include <evutil.h>

**If I move it out of the C extern it works fine.** 

<img width="1158" alt="Screenshot 2022-03-23 at 4 28 48 PM" src="https://user-images.githubusercontent.com/102017499/159684699-afff7ef8-2593-465e-b4c6-80fd1f772011.png">
>

Any Solutions.? I don't wanna do it on every pod install.

**Comment by Syedh30** [comment]
Any Solution?

**Comment by Syedh30** [comment]
@azat replacing `evutil.h` with `event2/util.h ` is working fine.

**Comment by azat** [comment]
Great. Can you please submit a PR?

**Comment by Syedh30** [comment]
Please check and update thanks
#1274

**Comment by Syedh30** [comment]
[https://github.com/libevent/libevent/pull/1274](url)

**Comment by Syedh30** [comment]
#1274 
@azat Please check and update

**Comment by mohakwathare** [comment]
wondering how you implemented the updated PR?? I am getting the following error when I try to installing the pod from the commit - 

```
[!] There are multiple dependencies with different sources for `libevent` in `Podfile`:

- libevent (from `https://github.com/libevent/libevent.git`, commit `e339880`)
- libevent (~> 2.1.12)
```

Fetching it like so - `pod 'libevent', :git => 'https://github.com/libevent/libevent.git', :commit => 'e339880'`
