### ISSUE TITLE
how many timer support in one thread (event_base)?

### ISSUE THREAD

**Issue by JackYangzg** [libevent/libevent#1270]
how many timer support in one thread (event_base)

**Comment by azat** [comment]
I would say that it can be as much, as you have events, so 1KK will work fine for example.
Note, that there is minheap for timeouts.

**Comment by JackYangzg** [comment]
> I would say that it can be as much, as you have events, so 1KK will work fine for example. Note, that there is minheap for timeouts.

We meet a problem, In one thread we register about 20w timer . we found the system call  cost about 99% cpu (do_syscall_64 cost about 60%)
When we stop the input data and unrefister all of the timer event, the cpu is still busy. we get the stacktrace, it show on epoll_dispatch.

**Comment by azat** [comment]
Sorry for the delay.

>20w timer

How many timers this is?

>When we stop the input data and unrefister all of the timer event, the cpu is still busy. we get the stacktrace, it show on epoll_dispatch

Interesting, this means that you constantly get some new activity.
You can try to use `event_base_dump_events` to see what is in the event base and with what timeouts.

**Comment by azat** [comment]
No answer. Closing.
