### ISSUE TITLE
HTTP client post caused a lot of "CLOSE_WAIT"

### ISSUE THREAD

**Issue by yongce** [libevent/libevent#1272]
We use libevent to execute HTTP post tasks. In the main thread, we call 'event_base_dispatch' to handle the events. In other threads, we use to libevent to create HTTP requests. For every HTTP post, we create a evhttp_connection object to do the job and then free the connection after the work done. But we found the sockets were not closed at all and there were a lot of "CLOSE_WAIT".

I used the 'lsof' command to check the process and found a lot of 'CLOSE_WAIT':
xx  11817 root   11u     IPv4 1883593243      0t0        TCP xian15:40516->121.14.47.29:http (CLOSE_WAIT)
xx  11817 root   12u     IPv4 1883626187      0t0        TCP xian15:41192->121.14.47.29:http (CLOSE_WAIT)
xx  11817 root   13u     IPv4 1883939644      0t0        TCP xian15:41980->121.14.47.29:http (CLOSE_WAIT)
xx  11817 root   14u     IPv4 1884116822      0t0        TCP xian15:42862->121.14.47.29:http (CLOSE_WAIT)
xx  11817 root   15u     IPv4 1884294347      0t0        TCP xian15:43514->121.14.47.29:http (CLOSE_WAIT)
....

**Comment by yongce** [comment]
I use the version 2.1.11.

When I execute the command "make verify", it failed:

[manage@xian15 libevent]$ make verify
make  check-am
make[1]: Entering directory `/home/manage/libevent'
make  check-TESTS
make[2]: Entering directory `/home/manage/libevent'
make[3]: Entering directory `/home/manage/libevent'
./test/test.sh -b EPOLL
Running tests:
EPOLL
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY
 regress:
  FAIL test/regress_http.c:3155: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3155: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/339 TESTS FAILED. (35 skipped)
FAILED
 regress_debug:

  FAIL test/regress_http.c:3155: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3155: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/339 TESTS FAILED. (35 skipped)
FAILED
make[3]: *** [test_runner_epoll] Error 1
make[3]: Leaving directory `/home/manage/libevent'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/home/manage/libevent'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/manage/libevent'
make: *** [check] Error 2

**Comment by loqs** [comment]
Are you using OpenSSL 3.0 as that would explain the test failures?  See #1250

**Comment by azat** [comment]
>We use libevent to execute HTTP post tasks. In the main thread, we call 'event_base_dispatch' to handle the events. In other threads, we use to libevent to create HTTP requests. 

Have you enabled thread safety for event_base?
Also note that this is kind of an anti-pattern, that said that it is better to use local event_base that is attached to this thread.

>For every HTTP post, we create a evhttp_connection object to do the job and then free the connection after the work done. But we found the sockets were not closed at all and there were a lot of "CLOSE_WAIT".

This means that close() was not called.
Can you share a small reproducer?

**Comment by yongce** [comment]
@azat I found that we used libevent 2.2.0-alpha-dev and reproduced this issue. After I rebuilt libevent 2.1.11-stable and this issue was gone.

**Comment by azat** [comment]
May I ask you to bisect (git bisect) and find the culprit commit?
Since eventually 2.2 will be the official stable release and the bug will be there.

**Comment by yongce** [comment]
I'll have a try.

**Comment by yongce** [comment]
I built the latest master branch and failed to reproduce this issue. I guess this issue was caused by some build env problems.

**Comment by azat** [comment]
Got it, thanks!
