### ISSUE TITLE
compile libevent with mbedtls problems

### ISSUE THREAD

**Issue by DamonChaos** [libevent/libevent#1273]
I tried to compile newest libevent with mbedtls.
my step is:
sh autogen.sh
./configure --prefix=$PWD/tmp --enable-mbedtls=yes MBEDTLS_INCS=-I../mbedtls-2.16.5/include MBEDTLS_LIBS="-L../mbedtls-2.16.5/tmp/x86_64 -lmbedtls -lmbedcrypto -lmbedx509" --enable-shared=no  CC=gcc --disable-openssl --disable-thread-support
make && make install

finally, no libevent_mbedtls.a in $PWD/tmp
anyone knows where am i wrong?

**Comment by azat** [comment]
@DamonChaos Hi.
Can you share full build log?
Also can you try to build using cmake build system?

**Comment by DamonChaos** [comment]
I'll try to build using cmake,here is my full build log:
============================================
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:26: installing 'build-aux/compile'
configure.ac:30: installing 'build-aux/config.guess'
configure.ac:30: installing 'build-aux/config.sub'
configure.ac:17: installing 'build-aux/install-sh'
configure.ac:17: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether ln -s works... yes
checking for a sed that does not truncate output... /bin/sed
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for library containing inet_ntoa... none required
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking for library containing clock_gettime... none required
checking for clock_gettime... yes
checking for library containing sendfile... none required
checking for WIN32... no
checking for MIDIPIX... no
checking for CYGWIN... no
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/local/mips32el--uclibc--stable-2018.11-1/bin/pkg-config
checking pkg-config is at least version 0.15.0... yes
checking for library containing mbedtls_ssl_init... no
checking mbedtls/ssl.h usability... no
checking mbedtls/ssl.h presence... no
checking for mbedtls/ssl.h... no
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking ifaddrs.h usability... yes
checking ifaddrs.h presence... yes
checking for ifaddrs.h... yes
checking mach/mach_time.h usability... no
checking mach/mach_time.h presence... no
checking for mach/mach_time.h... no
checking mach/mach.h usability... no
checking mach/mach.h presence... no
checking for mach/mach.h... no
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/in6.h usability... no
checking netinet/in6.h presence... no
checking for netinet/in6.h... no
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking port.h usability... no
checking port.h presence... no
checking for port.h... no
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking sys/devpoll.h usability... no
checking sys/devpoll.h presence... no
checking for sys/devpoll.h... no
checking sys/epoll.h usability... yes
checking sys/epoll.h presence... yes
checking for sys/epoll.h... yes
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
checking sys/eventfd.h usability... yes
checking sys/eventfd.h presence... yes
checking for sys/eventfd.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/queue.h usability... yes
checking sys/queue.h presence... yes
checking for sys/queue.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/sendfile.h usability... yes
checking sys/sendfile.h presence... yes
checking for sys/sendfile.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/timerfd.h usability... yes
checking sys/timerfd.h presence... yes
checking for sys/timerfd.h... yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking sys/random.h usability... yes
checking sys/random.h presence... yes
checking for sys/random.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking afunix.h usability... no
checking afunix.h presence... no
checking for afunix.h... no
checking for TAILQ_FOREACH in sys/queue.h... yes
checking for timeradd in sys/time.h... yes
checking for timercmp in sys/time.h... yes
checking for timerclear in sys/time.h... yes
checking for timerisset in sys/time.h... yes
checking for inline... inline
checking for accept4... yes
checking for arc4random... no
checking for arc4random_buf... no
checking for arc4random_addrandom... no
checking for eventfd... yes
checking for epoll_create1... yes
checking for fcntl... yes
checking for getegid... yes
checking for geteuid... yes
checking for getifaddrs... yes
checking for gettimeofday... yes
checking for issetugid... no
checking for mach_absolute_time... no
checking for mmap... yes
checking for nanosleep... yes
checking for pipe... yes
checking for pipe2... yes
checking for putenv... yes
checking for sendfile... yes
checking for setenv... yes
checking for setrlimit... yes
checking for sigaction... yes
checking for signal... yes
checking for strsignal... yes
checking for strlcpy... no
checking for strsep... yes
checking for strtok_r... yes
checking for strtoll... yes
checking for sysctl... yes
checking for timerfd_create... yes
checking for umask... yes
checking for unsetenv... yes
checking for usleep... yes
checking for getrandom... yes
checking for getnameinfo... yes
checking for getprotobynumber... yes
checking for getservbyname... yes
checking for inet_ntop... yes
checking for inet_pton... yes
checking for getaddrinfo... yes
checking for F_SETFD in fcntl.h... yes
checking for select... yes
checking for poll... yes
checking for epoll_ctl... yes
checking for port_create... no
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint64_t... yes
checking for uint32_t... yes
checking for uint16_t... yes
checking for uint8_t... yes
checking for uintptr_t... yes
checking for fd_mask... yes
checking size of long long... 8
checking size of long... 8
checking size of int... 4
checking size of short... 2
checking size of size_t... 8
checking size of void *... 8
checking size of off_t... 8
checking size of time_t... 8
checking for struct in6_addr... yes
checking for struct sockaddr_in6... yes
checking for struct sockaddr_un... yes
checking for sa_family_t... yes
checking for struct addrinfo... yes
checking for struct sockaddr_storage... yes
checking for struct in6_addr.s6_addr32... yes
checking for struct in6_addr.s6_addr16... yes
checking for struct sockaddr_in.sin_len... no
checking for struct sockaddr_in6.sin6_len... no
checking for struct sockaddr_storage.ss_family... yes
checking for struct sockaddr_storage.__ss_family... no
checking for struct linger... yes
checking for socklen_t... yes
checking whether our compiler supports __func__... yes
checking whether our compiler supports __FUNCTION__... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -fno-strict-aliasing... yes
checking whether C compiler accepts -W... yes
checking whether C compiler accepts -Waddress... yes
checking whether C compiler accepts -Wbad-function-cast... yes
checking whether C compiler accepts -Wdeclaration-after-statement... yes
checking whether C compiler accepts -Wfloat-equal... yes
checking whether C compiler accepts -Winit-self... yes
checking whether C compiler accepts -Wlogical-op... yes
checking whether C compiler accepts -Wmissing-declarations... yes
checking whether C compiler accepts -Wmissing-field-initializers... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wnormalized=id... yes
checking whether C compiler accepts -Woverride-init... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wstrict-prototypes... no
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -Wno-unused-parameter... yes
checking whether C compiler accepts -Wno-void-pointer-to-enum-cast... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libevent.pc
config.status: creating libevent_mbedtls.pc
config.status: creating libevent_openssl.pc
config.status: creating libevent_pthreads.pc
config.status: creating libevent_core.pc
config.status: creating libevent_extra.pc
config.status: creating config.h
config.status: creating evconfig-private.h
config.status: executing depfiles commands
config.status: executing libtool commands
  GEN      test/rpcgen-attempted
  GEN      include/event2/event-config.h
make  all-am
make[1]: Entering directory '/home/damon/workcode/ssl_test/src/lib/libevent-master'
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_filter.lo
bufferevent_filter.c: In function ‘be_filter_readcb’:
bufferevent_filter.c:517:22: warning: unused variable ‘bev’ [-Wunused-variable]
  struct bufferevent *bev = downcast(bevf);
                      ^~~
bufferevent_filter.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-void-pointer-to-enum-cast’
  CC       bufferevent_pair.lo
  CC       bufferevent_ratelim.lo
  CC       bufferevent_sock.lo
  CC       event.lo
  CC       evmap.lo
  CC       evthread.lo
  CC       evutil.lo
  CC       evutil_rand.lo
  CC       evutil_time.lo
  CC       watch.lo
  CC       listener.lo
  CC       log.lo
  CC       strlcpy.lo
  CC       select.lo
  CC       poll.lo
  CC       epoll.lo
  CC       signal.lo
  CC       evdns.lo
  CC       event_tagging.lo
  CC       evrpc.lo
  CC       http.lo
  CCLD     libevent.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     libevent_core.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     libevent_extra.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       sample/dns-example.o
  CCLD     sample/dns-example
  CC       sample/event-read-fifo.o
  CCLD     sample/event-read-fifo
  CC       sample/hello-world.o
  CCLD     sample/hello-world
  CC       sample/http-server.o
  CCLD     sample/http-server
  CC       sample/http-connect.o
  CCLD     sample/http-connect
  CC       sample/signal-test.o
  CCLD     sample/signal-test
  CC       sample/time-test.o
  CCLD     sample/time-test
  CC       sample/watch-timing.o
  CCLD     sample/watch-timing
  CC       test/bench.o
  CCLD     test/bench
  CC       test/bench_cascade.o
  CCLD     test/bench_cascade
  CC       test/bench_http.o
  CCLD     test/bench_http
  CC       test/bench_httpclient.o
  CCLD     test/bench_httpclient
  CC       test/test-changelist.o
  CCLD     test/test-changelist
  CC       test/test-dumpevents.o
  CCLD     test/test-dumpevents
  CC       test/test-eof.o
  CCLD     test/test-eof
  CC       test/test-closed.o
  CCLD     test/test-closed
  CC       test/test-fdleak.o
  CCLD     test/test-fdleak
  CC       test/test-init.o
  CCLD     test/test-init
  CC       test/test-ratelim.o
  CCLD     test/test-ratelim
  CC       test/test-time.o
  CCLD     test/test-time
  CC       test/test-weof.o
  CCLD     test/test-weof
  CC       test/test_regress-regress.o
  CC       test/test_regress-regress.gen.o
  CC       test/test_regress-regress_buffer.o
  CC       test/test_regress-regress_bufferevent.o
  CC       test/test_regress-regress_dns.o
  CC       test/test_regress-regress_et.o
  CC       test/test_regress-regress_finalize.o
  CC       test/test_regress-regress_http.o
  CC       test/test_regress-regress_listener.o
  CC       test/test_regress-regress_main.o
  CC       test/test_regress-regress_minheap.o
  CC       test/test_regress-regress_rpc.o
  CC       test/test_regress-regress_testutils.o
  CC       test/test_regress-regress_util.o
  CC       test/test_regress-regress_watch.o
  CC       test/test_regress-tinytest.o
  CCLD     test/regress
make[1]: Leaving directory '/home/damon/workcode/ssl_test/src/lib/libevent-master'
make  install-am
make[1]: Entering directory '/home/damon/workcode/ssl_test/src/lib/libevent-master'
make[2]: Entering directory '/home/damon/workcode/ssl_test/src/lib/libevent-master'
 /bin/mkdir -p '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/bin'
 /usr/bin/install -c event_rpcgen.py '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/bin'
 /bin/mkdir -p '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libevent.la libevent_core.la libevent_extra.la '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib'
libtool: install: /usr/bin/install -c .libs/libevent.lai /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent.la
libtool: install: /usr/bin/install -c .libs/libevent_core.lai /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_core.la
libtool: install: /usr/bin/install -c .libs/libevent_extra.lai /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_extra.la
libtool: install: /usr/bin/install -c .libs/libevent.a /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent.a
libtool: install: chmod 644 /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent.a
libtool: install: ranlib /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent.a
libtool: install: /usr/bin/install -c .libs/libevent_core.a /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_core.a
libtool: install: chmod 644 /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_core.a
libtool: install: ranlib /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_core.a
libtool: install: /usr/bin/install -c .libs/libevent_extra.a /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_extra.a
libtool: install: chmod 644 /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_extra.a
libtool: install: ranlib /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/libevent_extra.a
libtool: finish: PATH="/usr/local/mips/bin:/usr/local/mips32el--uclibc--stable-2018.11-1/bin:/usr/local/mips64-n32--uclibc--stable-2018.11-1/bin:/usr/local/arm_openwrt/bin:/usr/local/mips_openwrt_34c/OpenWrt-Toolchain-ar71xx-for-mips_34kc-gcc-4.8-linaro_uClibc-0.9.33.2/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin:/usr/local/mips32el--uclibc--stable-2018.11-1/bin:/usr/local/mips64-n32--uclibc--stable-2018.11-1/bin:/usr/local/arm_openwrt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin" ldconfig -n /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/include'
 /usr/bin/install -c -m 644 include/evdns.h include/event.h include/evhttp.h include/evrpc.h include/evutil.h '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/include'
 /bin/mkdir -p '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/include/event2'
 /usr/bin/install -c -m 644 include/event2/buffer.h include/event2/buffer_compat.h include/event2/bufferevent.h include/event2/bufferevent_compat.h include/event2/bufferevent_struct.h include/event2/dns.h include/event2/dns_compat.h include/event2/dns_struct.h include/event2/event.h include/event2/event_compat.h include/event2/event_struct.h include/event2/watch.h include/event2/http.h include/event2/http_compat.h include/event2/http_struct.h include/event2/keyvalq_struct.h include/event2/listener.h include/event2/rpc.h include/event2/rpc_compat.h include/event2/rpc_struct.h include/event2/tag.h include/event2/tag_compat.h include/event2/thread.h include/event2/util.h include/event2/visibility.h '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/include/event2'
 /bin/mkdir -p '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/include/event2'
 /usr/bin/install -c -m 644 include/event2/event-config.h '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/include/event2'
 /bin/mkdir -p '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/pkgconfig'
 /usr/bin/install -c -m 644 libevent.pc libevent_core.pc libevent_extra.pc '/home/damon/workcode/ssl_test/src/lib/libevent-master/tmp/x86_64/lib/pkgconfig'
make[2]: Leaving directory '/home/damon/workcode/ssl_test/src/lib/libevent-master'
make[1]: Leaving directory '/home/damon/workcode/ssl_test/src/lib/libevent-master'

**Comment by DamonChaos** [comment]
@azat Take a look if you have time, Thanks!

**Comment by azat** [comment]
```
checking for library containing mbedtls_ssl_init... no
checking mbedtls/ssl.h usability... no
checking mbedtls/ssl.h presence... no
checking for mbedtls/ssl.h... no
```

mbedTLS is not found as you can see from the logs.

> ```
> ./configure --prefix=$PWD/tmp --enable-mbedtls=yes MBEDTLS_INCS=-I../mbedtls-2.16.5/include MBEDTLS_LIBS="L../mbedtls-2.16.5/tmp/x86_64 -lmbedtls -lmbedcrypto -lmbedx509" --enable-shared=no CC=gcc --disable-openssl --disable-thread-support
> ```

You cannot modify MBEDTLS_INCS/MBEDTLS_LIBS, they will be replaced.
You can use CFLAGS/LDFLAGS however but this is a hack.

We should provide pkg-config support, this will be done in #1259

In the meantime, you can either try to use CFLAGS/LDFLAGS:

```
./configure --prefix=$PWD/tmp --enable-mbedtls=yes MBEDTLS_INCS=-I../mbedtls-2.16.5/include MBEDTLS_LIBS="L../mbedtls-2.16.5/tmp/x86_64 -lmbedtls -lmbedcrypto -lmbedx509" --enable-shared=no CC=gcc --disable-openssl --disable-thread-support
```

Or try `cmake`:

```
cmake -DMBEDTLS_ROOT_DIR=../mbedtls-2.16.5/
```

**Comment by azat** [comment]
mbedTLS does not provide pkg-config support, so you have to use one of provide above ways.

libevent uses the following for CI

https://github.com/libevent/libevent/blob/acb7ef9819c3fe8b3c52e01c2c89b47fbc38b25d/.github/workflows/macos.yml#L142-L143
