### ISSUE TITLE
can not build against libressl-3.5

### ISSUE THREAD

**Issue by Felixixix** [libevent/libevent#1277]
Hi
libevent-2.1.12-stable regulary builds well against libressl on FreeBSD. It worked fine including libressl-3.4.3. 

But it fails with libressl-3.5.1 (-devel):

bufferevent_openssl.c:124:7: error: incomplete definition of type 'struct bio_st'
if (BIO_get_init(b) && BIO_get_data(b))
    ^~~~~~~~~~~~~~~
./openssl-compat.h:44:28: note: expanded from macro 'BIO_get_init'
#define BIO_get_init(b) (b)->init
                        ~~~^
/usr/local/include/openssl/ossl_typ.h:111:16: note: forward declaration of 'struct bio_st'
typedef struct bio_st BIO;
               ^
1 error generated.
*** Error code 1

Can it be that libevent does currently not like libressl-3.5 (or openssl-1.1.1) ? 
Those two libraries offer i.e. a different "struct bio_st" definition than the lower version.

Seems like a duplicate to
https://github.com/libevent/libevent/issues/1212
https://github.com/libevent/libevent/issues/1233

Cheers, Felix

**Comment by botovq** [comment]
You want the patch in https://github.com/libevent/libevent/pull/1227

**Comment by Felixixix** [comment]
Yes, I wanted that. It compiles now, thanks a lot.
