### ISSUE TITLE
EXC_BAD_ACCESS with buffevent_write in pair

### ISSUE THREAD

**Issue by JeremyOuyang** [libevent/libevent#1279]
![image](https://user-images.githubusercontent.com/7115471/169482064-7a0d6a64-220a-4f23-908a-c5f525570380.png)
Hi，I want to use pair to achieve multithreaded one-way read/write communication pipeline, pair[0] write pair[1] read data, but generated null pointer, may cause the pair is not thread safe？
It crash here，ch is null.
![image](https://user-images.githubusercontent.com/7115471/169482824-68fdf7a3-e8bc-4418-a565-4976b54a3020.png)

**Comment by azat** [comment]
Have you enabled multi-threading support?

```c
evthread_use_windows_threads(); // for win32
// evthread_use_pthreads(); // for linux

```

And you should use `BEV_OPT_THREADSAFE` while creating bufferevent.

**Comment by JeremyOuyang** [comment]
I understand that buffEvent pair can be used as a channel for simplex communication in multiple threads. It is thread-safe like pair[0] write, pair[1] write.

**Comment by azat** [comment]
No it is not actually, since it uses internal buffer, and concurrent access should be protected with mutex.
