### ISSUE TITLE
getaddrinfo_async fails for CNAME length > 63

### ISSUE THREAD

**Issue by sghiocel** [libevent/libevent#1280]
using https://github.com/libevent/libevent/commit/41239c9dac70ed90187fb287f214e1b106f52c83 with a patch to test large CNAME `1111111111111111111111111111111111111.both-canonical.example.com`:
```
diff --git a/test/regress_dns.c b/test/regress_dns.c
index 2c4973ae..5f5020d5 100644
--- a/test/regress_dns.c
+++ b/test/regress_dns.c
@@ -1264,7 +1264,7 @@ be_getaddrinfo_server_cb(struct evdns_server_request *req, void *data)
                                added_any = 1;
                        }
                        evdns_server_request_add_cname_reply(req, qname,
-                           "both-canonical.example.com", 1000);
+                           "1111111111111111111111111111111111111.both-canonical.example.com", 1000);
                } else if (!evutil_ascii_strcasecmp(qname,
                        "v4only.example.com") ||
                    !evutil_ascii_strcasecmp(qname, "v4assert.example.com")) {
@@ -1885,7 +1885,7 @@ test_getaddrinfo_async(void *arg)
        tt_assert(a);
        test_ai_eq(a, "[80ff::bbbb]:8000", SOCK_STREAM, IPPROTO_TCP);
        tt_assert(a_out[0].ai->ai_canonname);
-       tt_str_op(a_out[0].ai->ai_canonname, ==, "both-canonical.example.com");
+       tt_str_op(a_out[0].ai->ai_canonname, ==, "1111111111111111111111111111111111111.both-canonical.example.com");
 
        /* 1: v4only.example.com */
        tt_int_op(a_out[1].err, ==, 0);
```

```
mkdir build && cd build
cmake -DEVENT__DISABLE_MBEDTLS=ON -DEVENT__DISABLE_OPENSSL=ON ../
make regress
./bin/regress
```

```
dns/getaddrinfo_async: [forking] 
  FAIL /home/sean/Documents/Work/libevent_test/libevent_upstream/libevent/test/regress_dns.c:1877: assert(a_out[0].err == 0): -4 vs 0
```

`HOST_NAME_MAX` is set to 64 from:
`#define HOST_NAME_MAX		64 `
in /usr/include/x86_64-linux-gnu/bits/local_lim.h

so it is not defined as 255 in evdns.c
https://github.com/libevent/libevent/blob/41239c9dac70ed90187fb287f214e1b106f52c83/evdns.c#L125-L127

so the array `cname` size here is 64:
https://github.com/libevent/libevent/blob/41239c9dac70ed90187fb287f214e1b106f52c83/evdns.c#L1396-L1404

which does not have enough size to contain `1111111111111111111111111111111111111.both-canonical.example.com` and fails in `name_parse()`:
https://github.com/libevent/libevent/blob/41239c9dac70ed90187fb287f214e1b106f52c83/evdns.c#L1251

**Comment by ploxiln** [comment]
Nice find, interesting. The limit for a single component of a dns name is 64=(63 + `\0`) and this applies to hostnames without dot separators. The limit for the whole dns name is 255=(253 + `.` + `\0`) and that shouldn't be platform dependent, so the define being used is probably not exactly the right one to use. Instead evdns should probably `#define EVDNS_NAME_MAX 255` and use that.

**Comment by azat** [comment]
@sghiocel thanks for the detailed report! Fixed in upstream.
