### ISSUE TITLE
Concurrency issues with HTTP request callbacks

### ISSUE THREAD

**Issue by Mangomm** [libevent/libevent#1281]
Hello, when I use Libevent to process various HTTP requests, if one request takes a long time to process, it will affect the next request. For example, it takes 3s for connection 1 to request url=http://127.0.0.1:8000/. In this 3s time, connection 2 also requests the url=http://127.0.0.1:8000/, so connection 2 can only process request 2 after connection 1 takes 3 seconds to complete. Is there any way to simultaneously process them? Instead of connecting 2 and waiting 3 seconds.

**Comment by azat** [comment]
libevent http client is asynchronous, so it should not wait until request finished, if you have separate connections for them.

Take a look at our http client example here - https://github.com/libevent/libevent/blob/master/sample/https-client.c

All you need to do is `evhttp_connection_base_bufferevent_new`+`evhttp_request_new`+`evhttp_make_request` for each URL

**Comment by Mangomm** [comment]
Sorry, you may have misunderstood my meaning, I am using the server side, the reference file is libevent-2.1.12-stable\sample\http-server.c. 
I mean when the server has a callback interface called 
EVENT2_EXPORT_SYMBOL
int evhttp_set_cb(struct evhttp *http, const char *path,
void (*cb)(struct evhttp_request *, void *), void *cb_arg); 
When the same connection is made, assume that the client requests two times and the server takes a long time to process the first request. As a result, the second request cannot be processed until the first request is processed. So WHAT I mean is: is there a way for Libevent to enable multi-threading when the server receives multiple requests for the same connection?


My current solution is to use Linux's "\reuseport\" to enable multiple processes and let the kernel automatically allocate requests to different processes for me. Of course it would be nice if Libevent had something like that, or something like that but I don't know, so I'm here to ask.

**Comment by azat** [comment]
Ok, now I got you.

>When the same connection is made, assume that the client requests two times and the server takes a long time to process the first request. As a result, the second request cannot be processed until the first request is processed. So WHAT I mean is: is there a way for Libevent to enable multi-threading when the server receives multiple requests for the same connection?

multiple requests for the same connection out of the box - no
you can take a look at libevhtp for this.

>My current solution is to use Linux's "\reuseport" to enable multiple processes and let the kernel automatically allocate requests to different processes for me. Of course it would be nice if Libevent had something like that, or something like that but I don't know, so I'm here to ask

Yes, I agree that it will be nice to have, but libevent's http layer is pretty simple/dumb and there is no plans to extend it.

**Comment by Mangomm** [comment]
Ok, thanks for your patience, hahhh
