### ISSUE TITLE
1 millisecond timer triggered much later under linux mint 19.3

### ISSUE THREAD

**Issue by zdyang** [libevent/libevent#1286]
Hi

I was using libevent to set up a 1 millisecond timer for some callback function but it turned out that the timer was trigger roughly 3-5 milliseconds.

Here is my test code

```c
#include <event2/event.h>
#include <event2/event_struct.h>
#include <sys/time.h>
#include <stdio.h>

static struct timeval g_tv;
static void timer_cb(evutil_socket_t fd, short event, void *arg)
{
	gettimeofday(&g_tv, NULL);
	printf("[%ld.%06ld] timer_cb\n", g_tv.tv_sec%100, g_tv.tv_usec);
}

int main(){
	struct event_base   *evbase = NULL;
	evbase = event_base_new();
	if(evbase == NULL) return -1;
	struct timeval tv = {0, 1000};
	struct  event *ev = event_new(evbase, -1, EV_PERSIST, timer_cb, NULL);
	event_add(ev, &tv);

	event_base_dispatch(evbase);

	event_base_free(evbase);

	return 0;
}
```

and this was my output
![1](https://user-images.githubusercontent.com/6711024/173575365-f3716032-516e-44de-8c3a-0d0a91a8cf1e.png)

the screenshot showed that timer period was about 4 ms. 

My testing envornment
```
Linux Server 5.4.0-113-generic #127~18.04.1-Ubuntu SMP Wed May 18 15:40:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

For libevent, I had tried libevent-2.1-6 which was brought by my distribution and the lastest libevent-2.1.12

The test code above worked as expected in Ubuntu 16.04 with libevent 2.0 but i hoped to work on a much recent OS

Perphas I had made a stupid mistake but after searching google and github, I cound not find an answer.

Thanks for your attention and help.

**Comment by azat** [comment]
Hi!

You need to use [`EVENT_BASE_FLAG_PRECISE_TIMER`](https://libevent.org/doc/event_8h.html#acfef69af45abee54725f40f7f29986c5af6080f1d7c5067868cbc749d1cfe56e9), you can test you sample by simply setting `EVENT_PRECISE_TIMER` env variable (libevent by default parses some settings from environment).

**Comment by azat** [comment]
@zdyang please reopen if this will not help.

**Comment by zdyang** [comment]
@azat Thank you. Adding `EVENT_BASE_FLAG_PRECISE_TIMER` solved my problem.
