### ISSUE TITLE
Provide a callback for when the event loop is ready

### ISSUE THREAD

**Issue by tristan957** [libevent/libevent#1292]
I am creating an HTTP server for an embedded library. I do all the event loop setup on the main thread in a function called `start_server()`, and then in a new thread, I run `event_base_dispatch()`.

If my `stop_server()` function which calls `event_base_loopbreak()`, gets called before the event loop is completely setup, my library will sit at `pthread_join()` forever because `event_base_dispatch()` will never return.

I could be missing something here though.

**Comment by azat** [comment]
>If my stop_server() function which calls event_base_loopbreak(), gets called before the event loop is completely setup, my library will sit at pthread_join() forever because event_base_dispatch() will never return.

Yes, this is because `event_break` is reset to `0` at start and only after checked:

https://github.com/libevent/libevent/blob/1bc62ce1718c720fd64e6e2db408bfb07d04b88e/event.c#L1979-L1990

You can use `event_base_loopexit` instead, it stops loop from the loop, so it should not have such problem.

**Comment by tristan957** [comment]
Very interesting. I thought loobreak() was the same as loopexit() with a NULL tv.
