### ISSUE TITLE
EVENT_READING | EVENT_ERROR after bufferevent_enable but before bufferevent_socket_connect

### ISSUE THREAD

**Issue by NeoProg2013** [libevent/libevent#1295]
I have a simple TCP client.

Event loop working in thread `#1` use `event_base_loop(base, EVLOOP_ONCE)`.

TCP connection starting in thread `#2`:
- Create socket socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)
- call evutil_make_socket_nonblocking
- Fill sockaddr_in strcture
- call bufferevent_socket_new with BEV_OPT_THREADSAFE flag
- call bufferevent_setcb with read and event callbacks. Write callback is NULL
- call bufferevent_enable with EV_READ flag
<------ Here libevent call my event callback with BEV_EVENT_READING | BEV_EVENT_ERROR
- call bufferevent_socket_connect

Its normal behavior? I don't expect events before call bufferevent_socket_connect

**Comment by azat** [comment]
>Its normal behavior? I don't expect events before call bufferevent_socket_connect

AFAICS it should not happen.
This sounds like a simple and reproducible issue.
Can you show a code sample?

**Comment by NeoProg2013** [comment]
Oops. I can't reproduce it now. When it starts again I will try to collect more information.

Source code
`#include <iostream>
#include <atomic>
#include <thread>
#include <cstring>
#include <signal.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <event2/thread.h>
#include <event2/bufferevent.h>
#include <event2/listener.h>

bufferevent* tcp_server_bev = nullptr;
bufferevent* tcp_connect_bev = nullptr;
event_base* base = nullptr;
int tcpsock_fd = -1;

std::atomic<bool> is_start_connect(false);
std::atomic<bool> exit_flag(false);


//
// TCP server part
//
void tcp_server_read_callback(bufferevent* bev, void*) {
    std::cout << "call tcp_server_read_callback" << std::endl;
    char buffer[512] = {0};
    bufferevent_read(bev, buffer, 512);
    is_start_connect = true;

    // Something actions
}
void tcp_server_event_callback(bufferevent* bev, short events, void*) {
    std::cout << "call tcp_server_event_callback" << std::endl;
    // Something actions
}
void tcp_accept_connection_callback(evconnlistener* listener, evutil_socket_t fd, sockaddr* address, int socklen, void*) {
    std::cout << "call tcp_accept_connection_callback" << std::endl;

    event_base* base = evconnlistener_get_base(listener);
    bufferevent* bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE | BEV_OPT_THREADSAFE);
    bufferevent_setcb(bev, tcp_server_read_callback, nullptr, tcp_server_event_callback, NULL);
    bufferevent_enable(bev, EV_READ | EV_WRITE);

    tcp_server_bev = bev;
}

//
// TCP client part
//
void tcp_client_read_callback(bufferevent* bev, void*) {
    std::cout << "call tcp_client_read_callback" << std::endl;
    // Something actions
}
void tcp_client_event_callback(bufferevent* bev, short events, void*) {
    std::cout << "call tcp_client_event_callback: " << events << std::endl;
    if (events & BEV_EVENT_CONNECTED) {
        std::cout << "BEV_EVENT_CONNECTED" << std::endl;
    }
    if (events & BEV_EVENT_ERROR) {
        std::cout << "BEV_EVENT_ERROR" << std::endl;
    }
    if (events & BEV_EVENT_EOF) {
        std::cout << "BEV_EVENT_EOF" << std::endl;
    }
    if (events & BEV_EVENT_TIMEOUT) {
        std::cout << "BEV_EVENT_TIMEOUT" << std::endl;
    }
    if (events & BEV_EVENT_WRITING) {
        std::cout << "BEV_EVENT_WRITING" << std::endl;
    }
    if (events & BEV_EVENT_READING) {
        std::cout << "BEV_EVENT_READING" << std::endl;
    }
}
void client_connect() {
    std::cout << "Client thread is ready" << std::endl;
    while (!is_start_connect) {
        if (exit_flag) {
            return;
        }
    }

    std::string msg("START CONNECT");
    bufferevent_write(tcp_server_bev, msg.c_str(), msg.size());

    tcpsock_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    evutil_make_socket_nonblocking(tcpsock_fd);

    sockaddr_in addr;
    memset(&addr, 0, sizeof(sockaddr_in));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = inet_addr("10.0.0.169");
    addr.sin_port = htons(8080);

    tcp_connect_bev = bufferevent_socket_new(bufferevent_get_base(tcp_server_bev), tcpsock_fd, BEV_OPT_THREADSAFE);

    bufferevent_setcb(tcp_connect_bev, tcp_client_read_callback, NULL, tcp_client_event_callback, 0);
    bufferevent_enable(tcp_connect_bev, EV_READ);

    bufferevent_socket_connect(tcp_connect_bev, reinterpret_cast<sockaddr*>(&addr), sizeof(addr));

}





void signal_handler(int signum) {
    if (signum == SIGTERM || signum == SIGINT || signum == SIGHUP) {
        printf("Signal %d received!\n", signum);
        exit_flag = true;
        event_base_loopexit(base, NULL);
    }
}

int main() {
    std::cout << "Starting..." << std::endl;
    signal(SIGTERM, signal_handler);
    signal(SIGHUP, signal_handler);
    signal(SIGINT, signal_handler);

    evthread_use_pthreads();
    base = event_base_new();

    sockaddr_in listener_addr;
    memset(&listener_addr, 0, sizeof(listener_addr));
    listener_addr.sin_family = AF_INET;
    listener_addr.sin_addr.s_addr = inet_addr("127.0.0.1");
    listener_addr.sin_port = 0;

    evconnlistener* listener = evconnlistener_new_bind(base, tcp_accept_connection_callback,
            NULL, LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE | LEV_OPT_THREADSAFE, -1,
            reinterpret_cast<sockaddr*>(&listener_addr), sizeof(listener_addr));
    evutil_socket_t listener_socket = evconnlistener_get_fd(listener);
    evutil_make_socket_nonblocking(listener_socket);

    sockaddr_in addr;
    socklen_t len = sizeof(addr);
    getsockname(listener_socket, reinterpret_cast<sockaddr*>(&addr), &len);
    std::cout << "TCP port: " << htons(addr.sin_port) << std::endl;

    std::thread th(client_connect);

    std::cout << "Start event loop" << std::endl;
    while (!exit_flag) {
        event_base_loop(base, EVLOOP_ONCE);
    }
    th.join();
}
`

**Comment by NeoProg2013** [comment]
I reproduce it. Output from "libevent-src.zip"

`Starting...
TCP port: 40487
Start event loop
Client thread is ready
call tcp_accept_connection_callback
call tcp_server_read_callback
call tcp_client_event_callback: 33
BEV_EVENT_ERROR
BEV_EVENT_READING
call tcp_client_event_callback: 128
BEV_EVENT_CONNECTED
`

Step by step:
- Build example source code: g++ libevent-src.cpp -lpthread -levent -levent_core -levent_pthreads
- Run binary
- Connect to TCP port using telnet tool
- Send any message

Reproducing is not 100%

**Comment by azat** [comment]
>How i can enable max logging for libevent library without rebuild?

`event_enable_debug_logging(EVENT_DBG_ALL)`

>[libevent-src.zip](https://github.com/libevent/libevent/files/9077855/libevent-src.zip)

Thanks. You code has some issues, but this should not affect.

>I reproduce it. 

Can you provide strace log for such failure?
i.e. run program like this `strace -s 1000 -f -tt -o strace.log /path/to/bin`

And also separate output with `event_enable_debug_logging(EVENT_DBG_ALL)` but w/o strace.

**Comment by NeoProg2013** [comment]
> You code has some issues, but this should not affect.
Could you tell me more, please?

> Can you provide strace log for such failure
Of course. I will let you know how the results are.

**Comment by NeoProg2013** [comment]
I modify src code for fast reproduce -- each data read we starting new connection. After 3-4 times issue is reproduce.
[libevent-update-1.zip](https://github.com/libevent/libevent/files/9082538/libevent-update-1.zip)

Problem signature in logs:
> 21128 12:11:17.231254 write(1, "call tcp_client_event_callback: 33\n", 35) = 35
> 21128 12:11:17.231437 write(1, "BEV_EVENT_ERROR\n", 16) = 16
> 21128 12:11:17.231607 write(1, "BEV_EVENT_READING\n", 18) = 18
[strace.zip](https://github.com/libevent/libevent/files/9082541/strace.zip)

**Comment by azat** [comment]
Like I thought the problem that you've enabled EV_READ before connect, you should not do so, since you can read from unconnected socket.

**Comment by azat** [comment]
>Could you tell me more, please?

Sure.
Although maybe it is just a test sample and I should not be so critial.

Anyway here are some comments after a brief look:

Basic anti patterns:
- you are using busy loops for waiting of the event
- global variables

libevent anti patterns:
- you are using separate thread for the event_base, it is better to have event_base per thread
- you don't need to call evutil_make_socket_nonblocking() manually you can just pass -1 as fd and this will be done automatically
- it is better to use EV_SIGNAL in programs that are using libevent, that way you will be able to use non-signal-safe functions in signal handlers, also note, that event_base_loopexit() is not signal safe
