### ISSUE TITLE
libevent 2.1.12 "make" error

### ISSUE THREAD

**Issue by cicieun** [libevent/libevent#1309]
Hello,
I'm nervous because it's my first time writing.
Please understand that my English is not good enough.

While installing libevent 2.1.12 this error comand appeared.
`./configure` was successful but aborted while running `make`.

> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [test/regress] Error 1
> make: *** [all] Error 2

There was no such error until libevent 2.1.8, but it occurred from 2.1.9. How do I solve this?
I tried the openssl for 1.1 and 3.0.5, but the same error occurred, so I don't think it's an openssl problem.

I need libevent_core-2.1.7 now.

I'll attach some of the commands below.

>   GEN      test/rpcgen-attempted
> env: python: No such file or directory
> Could not generate regress.gen.\[ch\] using event_rpcgen.sh
> No Python installed; stubbing out RPC test.
>   GEN      include/event2/event-config.h
> /Library/Developer/CommandLineTools/usr/bin/make  all-am
>   CC       sample/dns-example.o

....

> 6 warnings generated.
>   CCLD     libevent_extra.la
>   CC       evthread_pthread.lo
>   CCLD     libevent_pthreads.la
>   CCLD     test/regress
> Undefined symbols for architecture x86_64:
>   "_SSL_get1_peer_certificate", referenced from:
>       _eventcb in regress-regress_ssl.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [test/regress] Error 1
> make: *** [all] Error 2

**Comment by azat** [comment]
Hi!

>I tried the openssl for 1.1 and 3.0.5, but the same error occurred, so I don't think it's an openssl problem.

I'm pretty sure that you trying to use headers for openssl 3 both times, since [`SSL_get1_peer_certificate`](https://www.openssl.org/docs/manmaster/man3/SSL_get1_peer_certificate.html) had been added in openssl 3.0

And note that 2.1.12 is not compatible with openssl 3.0, this had been fixed only recently so you should use upstream if you want to use libevent with openssl 3.0 (see #1288 for the reference)

**Comment by cicieun** [comment]
Thanks for your answer.
I changed the version of openssl to 1.1.1 according to your advice.

But... the same error as before appears.
Even include `SSL_get1_peer_certificate`.
Do I have to go through a specific processing after installing openssl?
As soon as I installed it, I went into the libevent-2.1.12 folder and `./congure`, `make`.

**Comment by azat** [comment]
You are still using headers from openssl 3.0.
Likely it is installed into the system, while openssl 1.0 is not, and so it uses headers from it, ensure which headers is used by libevent. I would suggest you to use docker for clean builds (or at least remove system-wide installation of openssl)

>Do I have to go through a specific processing after installing openssl?

It is better not to build from sources but using shipped in distro openssl version.

**Comment by cicieun** [comment]
I'm sorry to bother you...

I tried to reinstall openssl as you advised,
Before that, I installed libevent 2.1.8 as a test and it went well.
I don't know why it can't be installed from version 2.1.9.

To explain the situation in more detail, I am currently using Mac 12.4 and using rosetta to install the x86_64 architecture version. The openssl and libevent of arm64 architecture are installed in the /opt path.

**Comment by azat** [comment]
>(I want libevent_core-2.1.7, so I think I need to install a version higher than libevent-2.1.8. Because when I installed 2.1.8 and checked, core-2.1.6 was installed.)

VERSION_INFO of the library differs from the release.

>I tried to reinstall openssl as you advised,

Please post all the commands from the scratch (`brew` and so on), also you can try to use cmake for compiling libevent, you can configure openssl location with `OPENSSL_ROOT_DIR`

**Comment by cicieun** [comment]
Hello!

The problem has been solved.
I think it was a version issue of openssl.
When I tried to configure it again, the phrase "export the path of openssl.pc" popped up, so I put the path of version 1.1.1 and it was installed.
Fortunately, there was core-2.1.7.

Thanks for your help :)
