### ISSUE TITLE
There may be a bug in "ht-internal.h"

### ISSUE THREAD

**Issue by AClumsyDog** [libevent/libevent#1312]
In function 'HT_GROW', there may be a bug.
```c++
    do {                                                                \
      new_len = name##_PRIMES[++prime_idx];                             \
      new_load_limit = (unsigned)(load*new_len);                        \
    } while (new_load_limit <= size &&                                  \
             prime_idx < (int)name##_N_PRIMES);    
```
When `prime_idx` grows to `N_PRIMES - 1`,next `prime_idx` becomes `N_PRIMES`. This is a problem with  visiting `PRIMES`.

**Comment by azat** [comment]
Indeed, nice catch!
Can you send a PR with a patch (it will be great if you will add some regression test for this, see `test/` directory for examples)?
