### ISSUE TITLE
Add postfix `d` for libraries of Debug configuration.

### ISSUE THREAD

**Issue by hwhsu1231** [libevent/libevent#1313]
## Descriptions

I noticed that the Libevent doesn't add postfix `d` for libraries of **Debug** config. Therefore, if I first install **Debug** config and then **Release** config:

```cmd
cmake --install . --config Debug
cmake --install . --config Release
```

Then, it will only remain one version, which is the latter, because the former will be overwritten by the latter.

Is there any reason why Libevent doesn't add postfix `d` for **Debug** config? If not, I suggest that it add postfix `d`. For example, using [`CMAKE_DEBUG_POSTFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_DEBUG_POSTFIX.html):

```cmake
set(CMAKE_DEBUG_POSTFIX d)
```

## Screenshots

![image](https://user-images.githubusercontent.com/71438617/181750523-bac6c055-e8a4-4bc7-a1df-404efbe8d41d.png)

**Comment by azat** [comment]
>Is there any reason why Libevent doesn't add postfix d for Debug config? If not, I suggest that it add postfix d. For example, using [CMAKE_DEBUG_POSTFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_DEBUG_POSTFIX.html):

Yes, let's do this. Can you submit a PR?

**Comment by jiangteck** [comment]
seems adding CMAKE_DEBUG_POSTFIX with CACHE would influence external project, all debug products would add 'd' postfix
[related commit](https://github.com/libevent/libevent/commit/dd610b778146f1425cd6ee0ad51d4b7916cff873)

could CMAKE_DEBUG_POSTFIX just set but not cache? 
```
set(CMAKE_DEBUG_POSTFIX d)
```

**Comment by azat** [comment]
> Based on my experiences with the Boost libraries, multiple library names cause problems for downstream builds (it broke mine, thus https://github.com/libevent/libevent/pull/1391).

What use case it broke for you?

> And as has already been found, it does not fit well with the assumptions of pkg-config either.

You mean this one? https://github.com/libevent/libevent/pull/1458 But it had been fixed already

Personally I don't think that this is useful, since except for the libraries there can be different headers as well, and I just create new build folder for each build type, so I'm not against reverting the original change, but the reasoning should be strong enough to do this.
