### ISSUE TITLE
why evbuffer_get_length(input) > 0 but evbuffer_pullup(bev->input, -1) returns null?

### ISSUE THREAD

**Issue by tilongzs** [libevent/libevent#1330]
What could cause this?
```
struct evbuffer* input = bufferevent_get_input(bev);
size_t bufSize = evbuffer_get_length(input);
uint8_t* buf = evbuffer_pullup(bev->input, bufSize);
//...
evbuffer_drain(bev->input, bufSize);
```
bufSize>0 but buf is null.

**Comment by azat** [comment]
If the buffer has pinned chain, or if there was a race, i.e. `bufSize > evbuffer_get_length(input)` at the time of calling `evbuffer_pullup` although this one is unlikely

**Comment by tilongzs** [comment]
This seems to be because the buffer has pinned chain, but I don't know why this happens on the 4th time after receiving 10KB each time.
`evbuffer_remove()` solves this problem, but` evbuffer_remove() `requires creating an extra buffer, so I try not to use it.

**Comment by azat** [comment]
Can you share a simple reproducer?

**Comment by tilongzs** [comment]
bufferevent_read_buffer() can also meet the requirements.

**Comment by tilongzs** [comment]
bufferevent_read_buffer() can also meet the requirements.

**Comment by tilongzs** [comment]
close

**Comment by tilongzs** [comment]
close
