### ISSUE TITLE
Cmake build: redundant _GNU_SOURCE definition

### ISSUE THREAD

**Issue by francoisk** [libevent/libevent#1333]
`_GNU_SOURCE` is defined in the private config header but also on the compiler command-line for every object.

https://github.com/libevent/libevent/blob/b19af675c7601a7867f26c33072cda7ea125adb2/CMakeLists.txt#L399-L402

https://github.com/libevent/libevent/blob/b19af675c7601a7867f26c33072cda7ea125adb2/evconfig-private.h.cmake#L8-L10

**Comment by azat** [comment]
Refs #460
