### ISSUE TITLE
when I use EVLOOP_NO_EXIT_ON_EMPTY then http request timeout won't trigger any callback

### ISSUE THREAD

**Issue by sukidou** [libevent/libevent#1335]
Hi, I'm writing my http-client, here's some issues I met.
1. First, I init everything and set connection timeout to 3s, then let `event_base_loop` run with EVLOOP_NO_EXIT_ON_EMPTY in another thread.
2. Then I make one request with bad url which set with error callback and response callback. But even after long time no any callback will be called.
3. If I change bad url to good url, response callback will be trigger normally. 
4. OR if I change event_base_loop+EVLOOP_NO_EXIT_ON_EMPTY  to event_base_dispath after request or in a while(1) loop in another thread, then timeout will trigger response callback normally too.
Could you take a look on this?

**Comment by sukidou** [comment]
The version I use is `release-2.1.12-stable`

**Comment by azat** [comment]
Sounds odd. Can you share an example? But I would not recommend to run event base in a different thread, it is not recommended.

**Comment by sukidou** [comment]
Since I wanna use it like python asycio run_forever() and then create_task() to loop. Here below is simple code.
```cpp
//create connection and set timeout
evhttp_connection_set_retries(mEvCon, 1);
evhttp_connection_set_timeout(mEvCon, 3);
//create and run loop thread
mLoopThread = std::thread([&] {
	event_base_loop(mBase, EVLOOP_NO_EXIT_ON_EMPTY);
});
...
//make http req like example
struct evhttp_request *req = evhttp_request_new(http_request_done, mBev);
evhttp_make_request(mEvCon, req, data ? EVHTTP_REQ_POST : EVHTTP_REQ_GET, path.data());
```
response callback won't trigger when I in put bad url, but good url is fine.
OR if I change event_base_loop+EVLOOP_NO_EXIT_ON_EMPTY to event_base_dispath after request or in a while(1) loop with std::thread::yield() in another thread, then timeout will trigger response callback normally too.

**Comment by sukidou** [comment]
BTW, I just only change some codes in sample/https-client.c to use by my case. Most of the creation process is original.

**Comment by sukidou** [comment]
This loop case works fine with another thread in my tests.
```cpp
while(1) {
	event_base_loop(mBase, EVLOOP_ONCE | EVLOOP_NONBLOCK);
	std::this_thread::yield();
}
```

**Comment by sukidou** [comment]
evthread_use_pthreads
