### ISSUE TITLE
Libevent as http client and run in asynchronous mode, can send many requests immediately not wait reponse ?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#1336]

**Comment by okayabc** [comment]
Currently it needs wait response and send next request in turn. If response exist delay and may cause many requests stored in libevent which will cause out of memory.

**Comment by azat** [comment]
Libevent does not support [HTTP/1.1 pipelining](https://en.wikipedia.org/wiki/HTTP_pipelining), so right now it is not possible.
But this can be archived with websockets, that will be ready once #1322 will be merged.
