### ISSUE TITLE
[err] event_queue_insert_inserted: 0x5601a5c9a010(fd 17) already inserted

### ISSUE THREAD

**Issue by warpos-1017** [libevent/libevent#1345]
Hi, 
I got an error message as titled - [err] event_queue_insert_inserted: 0x5601a5c9a010(fd 17) already inserted. No pthread is used in my program.  Did anyone have encountered the same situation? and any suggestions. 

libevent 2.1.12-stable

Thanks,

**Comment by azat** [comment]
Hello!

Please shared the minimal reproducer, otherwise it is not possible to help you.
