### ISSUE TITLE
ws-chat-server.c not working

### ISSUE THREAD

**Issue by blackhat-a** [libevent/libevent#1347]
the ws code see not working, my steps are:
1.run ws-chat-server
2.open chrome
3.input http://127.0.0.1:8080/ then see the page
now, the server can't receice the ws connection from the page, the page should connect ws onload, what is the problem?
thank you

**Comment by blackhat-a** [comment]
ws-chat.html ws do not working, I use other ws code client is ok, so the problem is the ws-chat.html

**Comment by widgetii** [comment]
To understand what's going on, it would be very helpful to have JS console logs from Chrome

**Comment by blackhat-a** [comment]
I don't know how to debug js, but the ws server is ok, so i close this issue
