### ISSUE TITLE
Compilation error with old CMake due to broken endianness detection

### ISSUE THREAD

**Issue by widgetii** [libevent/libevent#1348]
Just found an issue on CMake 3.15.5:
```
[ 61%] Building C object CMakeFiles/event_static.dir/sha1.c.o
[ 62%] Building C object CMakeFiles/event_static.dir/evrpc.c.o
<command-line>: error: macro names must be identifiers
/home/paul/src/firmware/output/build/libevent-openipc-e8313084f9e8b064433cb10eb9a79bf87407fab6/sha1.c:39:2: error: #error "Endianness not defined!"
 #error "Endianness not defined!"
  ^~~~~
```

It turns out we're using [CMAKE_LANG_BYTE_ORDER](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_BYTE_ORDER.html) to [define endianness for sha1.c](https://github.com/libevent/libevent/blob/master/sha1.c#L32) that was introduced only in CMake 3.20 (libevent's minimal version is `3.1.2`)

What I have to do to fix it properly?
1. Bump minimal version in CMakeLists.txt
2. Use some kind of handwritten code to determine endianness

**Comment by azat** [comment]
I wish we can bump minimal cmake version, but it has not been included into debian stable yet (though libevent supports way more older envs), even though it has been released in 2021.03

So let's add a manual check in cmake.

**Comment by widgetii** [comment]
I could replace `CMAKE_<LANG>_BYTE_ORDER` by [TestBigEndian](https://cmake.org/cmake/help/latest/module/TestBigEndian.html), but it's deprecated since version 3.20 in favor of (surprise!) `CMAKE_<LANG>_BYTE_ORDER`

**Comment by azat** [comment]
Let's use TestBigEndian on cmake < 3.20, and `CMAKE_<LANG>_BYTE_ORDER` on newer cmake then
