### ISSUE TITLE
build libevent with cmake for android

### ISSUE THREAD

**Issue by blackhat-a** [libevent/libevent#1351]
is there a solution for build for android platform?  thank you

**Comment by azat** [comment]
Sometime ago I had [built](https://github.com/libevent/libevent/issues/475#issuecomment-284256518) libevent for android using one of the docker images, I don't know is this helpful or not, but this is all I have (since I haven't used android-studio).

**Comment by azat** [comment]
@blackhat-a you can take a look at https://github.com/libevent/libevent/pull/1353#issuecomment-1265997118 for the instruction, I hope this will help!

**Comment by blackhat-a** [comment]
yes, it works for me, thank you, it is very helpful!
