### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [libevent/libevent#1365]
Dear @libevent team,

It is possible to have a new release build after more two years?

The last 2.1.12 (2020-07-05):
- https://github.com/libevent/libevent/releases

Thanks in advance.

**Comment by Coeur** [comment]
There is a pinned thread: https://github.com/libevent/libevent/issues/1094

**Comment by Neustradamus** [comment]
Thanks @Coeur but it exist since 13th September 2020.
We are more two years after, 11th November 2022.

**Comment by azat** [comment]
Yes, this is in my todo list.

P.S. new issue will not help with to make some progress here, ping in #1094 is enough.

**Comment by Neustradamus** [comment]
@azat: Any progress about 2.2 version?
- https://github.com/libevent/libevent/issues/1365
- https://github.com/libevent/libevent/issues/1512
- https://github.com/libevent/libevent/issues/1760

We are 2025-10-29, 5 years and 4 months since 2.1.12 version.
