### ISSUE TITLE
http://www.wangafu.net/~nickm/libevent-book/01_intro.html is unable to access

### ISSUE THREAD

**Issue by rickyrick2002** [libevent/libevent#1370]
I was reading the manual 2 weeks ago and today I found it's unaccessiable. May someone fix the site?

**Comment by SunnyPaprika** [comment]
Here is the repo for the book:

https://github.com/nmathewson/libevent-book

**Comment by azat** [comment]
Hm, let's ping @nmathewson (it is his own site)
In the meantime I will take a look at deploy this book into libevent.org web site.

**Comment by azat** [comment]
BTW book now available at @nmathewson web site - http://www.wangafu.net/~nickm/libevent-book/

**Comment by azat** [comment]
And now we have it on libevent.org website too - https://libevent.org/libevent-book/
