### ISSUE TITLE
CMake cache CMAKE_DEBUG_POSTFIX influence external project

### ISSUE THREAD

**Issue by jiangteck** [libevent/libevent#1371]
According to #1313, seems adding CMAKE_DEBUG_POSTFIX with CACHE would influence external project, all debug products would add 'd' postfix, which not compatible for some platform
[related commit](https://github.com/libevent/libevent/commit/dd610b778146f1425cd6ee0ad51d4b7916cff873)

could CMAKE_DEBUG_POSTFIX just set but not cache?
```
set(CMAKE_DEBUG_POSTFIX d)
```

**Comment by azat** [comment]
Can you please share the cmake rules?

I've tried to reproduce it with the following and `CMAKE_DEBUG_POSTFIX` in libevent does not affects the outer project.

```sh
touch lib.c
```

```cmake
add_subdirectory(/src/le/libevent libevent EXCLUDE_FROM_ALL)
add_library(lib lib.c)
```

```
mkdir .cmake
cmake -G Ninja ..
ninja
$ ls *.a
liblib.a
```

**Comment by jiangteck** [comment]
our cmake use fetchContent to manage external project, can reproduce the problem:
```
set(DOWNLOAD_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
set(LIBEVENT_DOWNLOAD
        GIT_REPOSITORY https://github.com/libevent/libevent.git
        GIT_TAG ${LIBEVENT_COMMIT_ID})
include(FetchContent)
set(LIBEVENT_DOWNLOAD ${LIBEVENT_DOWNLOAD} DOWNLOAD_DIR "${DOWNLOAD_DIR}/_deps/libevent-download")
FetchContent_Declare(
        libevent ${LIBEVENT_DOWNLOAD}
)
FetchContent_GetProperties(libevent)
if (NOT libevent_POPULATED)
    FetchContent_Populate(libevent)
    add_subdirectory(${libevent_SOURCE_DIR} ${libevent_BINARY_DIR} EXCLUDE_FROM_ALL)
endif ()
```

**Comment by azat** [comment]
Doh, I forgot to pass pass `-DCMAKE_BUILD_TYPE=debug`. Fixed!
