### ISSUE TITLE
httpserver for Keep-Alive

### ISSUE THREAD

**Issue by blackhat-a** [libevent/libevent#1383]
how to write a keep-alive httpserver by using libevent?
no write data complete callback func on evhttp? 
for example:
void
bufferevent_setcb(struct bufferevent *bufev,
    bufferevent_data_cb readcb, bufferevent_data_cb writecb,
    bufferevent_event_cb eventcb, void *cbarg)

**Comment by azat** [comment]
For keep-alive you need the client to:
- have persistent connection
- do not send `Connection: close`
- it should send `Keep-alive` header (for http/1.0)

Server do not need any special support for libevent.

You can take a look at `http-server` example.

```sh
$ strace -e/accept http-server -p 8080 .
strace: Process 7534 attached
accept4(4, {sa_family=AF_INET, sin_port=htons(45828), sin_addr=inet_addr("127.0.0.1")}, [128 => 16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 6
accept4(4, 0x7fffffffc8a0, [128], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
```

```
$ curl -v 127.1:8080 127.1:8080 |& grep -e Connected -e Re-using
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Re-using existing connection #0 with host 127.0.0.1
```
