### ISSUE TITLE
Issues compiling with gcc 12 on fedora linux 37

### ISSUE THREAD

**Issue by Destroyinator69420** [libevent/libevent#1384]
Here is a copy of my terminal output with all that went well and all that didn't.
"""
[************@fedora libevent-2.1.12-stable]$ sudo make install
  GEN      test/rpcgen-attempted
  GEN      include/event2/event-config.h
make  install-am
make[1]: Entering directory '/home/jknapp1208/Downloads/libevent-2.1.12-stable'
  CC       sample/dns-example.o
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_filter.lo
  CC       bufferevent_pair.lo
  CC       bufferevent_ratelim.lo
  CC       bufferevent_sock.lo
  CC       event.lo
event.c: In function ‘event_signal_closure’:
event.c:1362:32: warning: storing the address of local variable ‘ncalls’ in ‘*ev.ev_.ev_signal.ev_pncalls’ [-Wdangling-pointer=]
 1362 |                 ev->ev_pncalls = &ncalls;
      |                 ~~~~~~~~~~~~~~~^~~~~~~~~
event.c:1356:15: note: ‘ncalls’ declared here
 1356 |         short ncalls;
      |               ^~~~~~
event.c:1356:15: note: ‘ev’ declared here
  CC       evmap.lo
  CC       evthread.lo
  CC       evutil.lo
evutil.c:213:21: warning: argument 4 of type ‘int[2]’ with mismatched bound [-Warray-parameter=]
  213 |     evutil_socket_t fd[2])
In file included from evutil.c:85:
./include/event2/util.h:310:25: note: previously declared as ‘int[]’
  310 | #define evutil_socket_t int
util-internal.h:306:47: note: in expansion of macro ‘evutil_socket_t’
  306 | int evutil_ersatz_socketpair_(int, int , int, evutil_socket_t[]);
      |                                               ^~~~~~~~~~~~~~~
  CC       evutil_rand.lo
  CC       evutil_time.lo
  CC       listener.lo
  CC       log.lo
  CC       strlcpy.lo
  CC       select.lo
  CC       poll.lo
  CC       epoll.lo
  CC       signal.lo
  CC       evdns.lo
  CC       event_tagging.lo
  CC       evrpc.lo
  CC       http.lo
  CCLD     libevent.la
  CCLD     sample/dns-example
  CC       sample/event-read-fifo.o
  CCLD     sample/event-read-fifo
  CC       sample/hello-world.o
  CCLD     sample/hello-world
  CC       sample/http-server.o
  CCLD     sample/http-server
  CC       sample/http-connect.o
  CCLD     sample/http-connect
  CC       sample/signal-test.o
  CCLD     sample/signal-test
  CC       sample/time-test.o
  CCLD     sample/time-test
  CC       sample/le_proxy-le-proxy.o
sample/le-proxy.c: In function ‘eventcb’:
sample/le-proxy.c:116:37: warning: ‘ERR_func_error_string’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  116 |                                     ERR_func_error_string(err);
      |                                     ^~~~~~~~~~~~~~~~~~~~~
In file included from sample/le-proxy.c:35:
/usr/local/include/openssl/err.h:459:35: note: declared here
  459 | OSSL_DEPRECATEDIN_3_0 const char *ERR_func_error_string(unsigned long e);
      |                                   ^~~~~~~~~~~~~~~~~~~~~
  CC       libevent_openssl_la-bufferevent_openssl.lo
  CCLD     libevent_openssl.la
  CCLD     sample/le-proxy
  CC       sample/https_client-https-client.o
  CC       sample/https_client-hostcheck.o
  CC       sample/https_client-openssl_hostname_validation.o
  CCLD     sample/https-client
  CC       test/bench.o
  CCLD     test/bench
  CC       test/bench_cascade.o
  CCLD     test/bench_cascade
  CC       test/bench_http.o
  CCLD     test/bench_http
  CC       test/bench_httpclient.o
  CCLD     libevent_core.la
  CCLD     test/bench_httpclient
  CC       test/test-changelist.o
  CCLD     test/test-changelist
  CC       test/test-dumpevents.o
  CCLD     test/test-dumpevents
  CC       test/test-eof.o
  CCLD     test/test-eof
  CC       test/test-closed.o
  CCLD     test/test-closed
  CC       test/test-fdleak.o
  CCLD     test/test-fdleak
  CC       test/test-init.o
  CCLD     test/test-init
  CC       test/test-ratelim.o
  CCLD     test/test-ratelim
  CC       test/test-time.o
  CCLD     test/test-time
  CC       test/test-weof.o
  CCLD     test/test-weof
  CC       test/regress-regress.o
  CC       test/regress-regress.gen.o
  CC       test/regress-regress_buffer.o
In file included from test/regress.h:35,
                 from test/regress_buffer.c:64:
test/regress_buffer.c: In function ‘test_evbuffer_pullup_with_empty’:
test/tinytest_macros.h:116:22: warning: cast from function call of type ‘unsigned char *’ to non-matching type ‘long int’ [-Wbad-function-cast]
  116 |         type val1_ = (type)(a);                                         \
      |                      ^
test/tinytest_macros.h:144:9: note: in expansion of macro ‘tt_assert_test_fmt_type’
  144 |         tt_assert_test_fmt_type(a,b,str_test,type,test,type,fmt,        \
      |         ^~~~~~~~~~~~~~~~~~~~~~~
test/tinytest_macros.h:158:9: note: in expansion of macro ‘tt_assert_test_type’
  158 |         tt_assert_test_type(a,b,#a" "#op" "#b,long,(val1_ op val2_), \
      |         ^~~~~~~~~~~~~~~~~~~
test/regress_buffer.c:444:9: note: in expansion of macro ‘tt_int_op’
  444 |         tt_int_op(evbuffer_pullup(buf, -1), ==, NULL);
      |         ^~~~~~~~~
  CC       test/regress-regress_bufferevent.o
  CC       test/regress-regress_dns.o
  CC       test/regress-regress_et.o
  CC       test/regress-regress_finalize.o
  CC       test/regress-regress_http.o
  CC       test/regress-regress_listener.o
  CC       test/regress-regress_main.o
  CC       test/regress-regress_minheap.o
  CC       test/regress-regress_rpc.o
  CC       test/regress-regress_testutils.o
  CC       test/regress-regress_util.o
  CC       test/regress-tinytest.o
  CC       test/regress-regress_thread.o
  CC       test/regress-regress_zlib.o
  CC       test/regress-regress_ssl.o
  CCLD     libevent_extra.la
  CC       evthread_pthread.lo
  CCLD     libevent_pthreads.la
  CCLD     test/regress
make[2]: Entering directory '/home/jknapp1208/Downloads/libevent-2.1.12-stable'
 /usr/bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c event_rpcgen.py '/usr/local/bin'
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libevent.la libevent_core.la libevent_extra.la libevent_pthreads.la libevent_openssl.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libevent-2.1.so.7.0.1 /usr/local/lib/libevent-2.1.so.7.0.1
libtool: install: (cd /usr/local/lib && { ln -s -f libevent-2.1.so.7.0.1 libevent-2.1.so.7 || { rm -f libevent-2.1.so.7 && ln -s libevent-2.1.so.7.0.1 libevent-2.1.so.7; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libevent-2.1.so.7.0.1 libevent.so || { rm -f libevent.so && ln -s libevent-2.1.so.7.0.1 libevent.so; }; })
libtool: install: /usr/bin/install -c .libs/libevent.lai /usr/local/lib/libevent.la
libtool: install: /usr/bin/install -c .libs/libevent_core-2.1.so.7.0.1 /usr/local/lib/libevent_core-2.1.so.7.0.1
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_core-2.1.so.7.0.1 libevent_core-2.1.so.7 || { rm -f libevent_core-2.1.so.7 && ln -s libevent_core-2.1.so.7.0.1 libevent_core-2.1.so.7; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_core-2.1.so.7.0.1 libevent_core.so || { rm -f libevent_core.so && ln -s libevent_core-2.1.so.7.0.1 libevent_core.so; }; })
libtool: install: /usr/bin/install -c .libs/libevent_core.lai /usr/local/lib/libevent_core.la
libtool: install: /usr/bin/install -c .libs/libevent_extra-2.1.so.7.0.1 /usr/local/lib/libevent_extra-2.1.so.7.0.1
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_extra-2.1.so.7.0.1 libevent_extra-2.1.so.7 || { rm -f libevent_extra-2.1.so.7 && ln -s libevent_extra-2.1.so.7.0.1 libevent_extra-2.1.so.7; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_extra-2.1.so.7.0.1 libevent_extra.so || { rm -f libevent_extra.so && ln -s libevent_extra-2.1.so.7.0.1 libevent_extra.so; }; })
libtool: install: /usr/bin/install -c .libs/libevent_extra.lai /usr/local/lib/libevent_extra.la
libtool: install: /usr/bin/install -c .libs/libevent_pthreads-2.1.so.7.0.1 /usr/local/lib/libevent_pthreads-2.1.so.7.0.1
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_pthreads-2.1.so.7.0.1 libevent_pthreads-2.1.so.7 || { rm -f libevent_pthreads-2.1.so.7 && ln -s libevent_pthreads-2.1.so.7.0.1 libevent_pthreads-2.1.so.7; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_pthreads-2.1.so.7.0.1 libevent_pthreads.so || { rm -f libevent_pthreads.so && ln -s libevent_pthreads-2.1.so.7.0.1 libevent_pthreads.so; }; })
libtool: install: /usr/bin/install -c .libs/libevent_pthreads.lai /usr/local/lib/libevent_pthreads.la
libtool: install: /usr/bin/install -c .libs/libevent_openssl-2.1.so.7.0.1 /usr/local/lib/libevent_openssl-2.1.so.7.0.1
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_openssl-2.1.so.7.0.1 libevent_openssl-2.1.so.7 || { rm -f libevent_openssl-2.1.so.7 && ln -s libevent_openssl-2.1.so.7.0.1 libevent_openssl-2.1.so.7; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libevent_openssl-2.1.so.7.0.1 libevent_openssl.so || { rm -f libevent_openssl.so && ln -s libevent_openssl-2.1.so.7.0.1 libevent_openssl.so; }; })
libtool: install: /usr/bin/install -c .libs/libevent_openssl.lai /usr/local/lib/libevent_openssl.la
libtool: install: /usr/bin/install -c .libs/libevent.a /usr/local/lib/libevent.a
libtool: install: chmod 644 /usr/local/lib/libevent.a
libtool: install: ranlib /usr/local/lib/libevent.a
libtool: install: /usr/bin/install -c .libs/libevent_core.a /usr/local/lib/libevent_core.a
libtool: install: chmod 644 /usr/local/lib/libevent_core.a
libtool: install: ranlib /usr/local/lib/libevent_core.a
libtool: install: /usr/bin/install -c .libs/libevent_extra.a /usr/local/lib/libevent_extra.a
libtool: install: chmod 644 /usr/local/lib/libevent_extra.a
libtool: install: ranlib /usr/local/lib/libevent_extra.a
libtool: install: /usr/bin/install -c .libs/libevent_pthreads.a /usr/local/lib/libevent_pthreads.a
libtool: install: chmod 644 /usr/local/lib/libevent_pthreads.a
libtool: install: ranlib /usr/local/lib/libevent_pthreads.a
libtool: install: /usr/bin/install -c .libs/libevent_openssl.a /usr/local/lib/libevent_openssl.a
libtool: install: chmod 644 /usr/local/lib/libevent_openssl.a
libtool: install: ranlib /usr/local/lib/libevent_openssl.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin:/sbin" ldconfig -n /usr/local/lib
"""
I hope that a bug fix is released soon.
All the best,
Destroyer

**Comment by zltl** [comment]
Seems install success. Any problem when linking libevent_xxxx.a?

**Comment by azat** [comment]
Those are just warnings, that are likely already fixed in upstream.

**Comment by azat** [comment]
As for ERR_func_error_string likely libevent compiled with headers from 1.0, since there are proper checks for this:

https://github.com/libevent/libevent/blob/92ea8476b4749b75d866cec6f5f59ffb6a89b594/sample/le-proxy.c#L116-L124
