### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by fusionneur** [libevent/libevent#1403]
~/.../libevent/build $ make
[ 10%] Built target event_core_static
[ 21%] Built target event_core_shared
[ 24%] Built target event_extra_static
[ 28%] Built target event_extra_shared
[ 30%] Built target event_openssl_static
[ 31%] Built target event_openssl_shared
[ 33%] Built target event_mbedtls_static
[ 34%] Built target event_mbedtls_shared
[ 35%] Built target event_pthreads_static
[ 36%] Built target event_pthreads_shared
[ 49%] Built target event_static
[ 62%] Built target event_shared
[ 63%] Built target event-read-fifo
[ 64%] Built target hello-world
[ 65%] Built target signal-test
[ 66%] Built target http-connect
[ 67%] Built target time-test
[ 68%] Built target watch-timing
[ 70%] Built target https-client
[ 71%] Built target le-proxy
[ 71%] Built target becat
[ 72%] Built target https-client-mbedtls
[ 73%] Built target ssl-client-mbedtls
[ 74%] Built target dns-example
[ 75%] Built target ws-chat-server
[ 76%] Built target http-server
[ 77%] Built target bench_http
[ 78%] Built target bench_httpclient
[ 79%] Built target bench
[ 80%] Built target bench_cascade
[ 80%] Linking C executable bin/regress
ld.lld: error: undefined symbol: evthread_use_pthreads
>>> referenced by regress_dns.c
>>>               CMakeFiles/regress.dir/test/regress_dns.c.o:(getaddrinfo_race_gotresolve_test)

ld.lld: error: undefined symbol: evthread_use_pthreads_with_flags
>>> referenced by regress_main.c
>>>               CMakeFiles/regress.dir/test/regress_main.c.o:(basic_test_setup)
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/regress.dir/build.make:440: bin/regress] Error 1
make[1]: *** [CMakeFiles/Makefile2:997: CMakeFiles/regress.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by azat** [comment]
Can you please share the following:
- the exact `cmake` command
- attach cmake logs/cache somewhere
- your env (os, libc, ...)

**Comment by azat** [comment]
Thank you for the logs, now I see the problem, referenced PR should fix it.
