### ISSUE TITLE
Do a third-part connection in a callback

### ISSUE THREAD

**Issue by poor1017** [libevent/libevent#1409]
Hi all

I am a http server. I want to send a message to a new address (not client address) in a callback. 

```
struct evhttp_connection *conn;
struct evhttp_request *req;

conn = evhttp_connection_base_new(base, NULL, "0.0.0.0", 8484);
req = evhttp_request_new(http_request_done, base);

evhttp_add_header(req->output_headers, "Host", "localhost");

evhttp_make_request(conn, req, EVHTTP_REQ_POST, "/idx?id=1");
```

The code above does not work. It ends at `EVBASE_ACQUIRE_LOCK(base, th_base_lock);`

What should I do?

Thanks.

**Comment by azat** [comment]
Hi @poor1017 

It should not, before calling callbacks from the event loop this lock will be released - https://github.com/libevent/libevent/blob/4dee61c02cc777c306227cd8378767ad544ce8bf/event.c#L1656

Also if this will be a bufferevent lock, it is recursive, so it should not be a problem either.

So please provide a reproducer.
