### ISSUE TITLE
Send a message to the server through curl

### ISSUE THREAD

**Issue by songguanqing** [libevent/libevent#1411]
I built a server through libevent, but there is a problem with me.When I did the security test, I found that when the message I sent to the server with curl meets the condition that the content-length is greater than the true length of the message body, the server cannot reply, and the connection will not be interrupted for a long time. This causes the server to be attacked. Secondly, it seems that this blocking does not occur in my code, but in the libevent-related library. So I want to ask if there is any solution to this problem? Can I break this connection in my business logic code? want to ask if there is any solution to this problem? Can I break this connection in my business logic code?

**Comment by azat** [comment]
@songguanqing if the client sending `Content-Length` bigger the the body size and you (client) do not close the connection, then there is no way for HTTP to detect that the request had been ended, so likely this is why the libevent waits for more bytes in the socket to be available.

**Comment by songguanqing** [comment]
Thank you for your answer. What I want to ask is exactly what you said. In this case, how should I set a timeout to disconnect it?That is to say, even if the content-length is greater than the length of the real message body, don't keep waiting.
