### ISSUE TITLE
CI: Set minimal permissions on GitHub Workflows

### ISSUE THREAD

**Issue by diogoteles08** [libevent/libevent#1421]
Hello!

I'd like to suggest the addition of minimal permissions on your workflows, as it would harden your security agains supply-chain attacks.

The idea is to define top-level minimal permissions, like read-only, that would be inherited by all jobs with unspecified permissions; and then use job-level permissions for any job that might need other specific permissions -- like your [coverage-job](https://github.com/libevent/libevent/blob/master/.github/workflows/master.yml#L10) that requires a `checks: write` to be able to create new checks. By setting limited permissions you would be secured against erroneous or malicious actions from external jobs you call from your workflow. It's specially important in the case they get compromised, for example.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

I'd be happy to raise a PR with the changes if you agree.

#### Context
I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) suggesting and implementing security changes on widely used open source projects 😊

**Comment by azat** [comment]
>I'd be happy to raise a PR with the changes if you agree.

Yes this will be very welcome patch, please submit a PR!

**Comment by azat** [comment]
Closed in 99a4b1a7865fdfb965868901701463b1a0ee7174
