### ISSUE TITLE
bufferevent_ssl.h not found with VCPKG 

### ISSUE THREAD

**Issue by achour-oussama** [libevent/libevent#1443]
Hello everyone, to use the nghttp2 library I need libevent. 

However, after installing it with vcpkg I noticed that the file “bufferevent_ssl.h” is not reachable. When I go to the includes installed in my vcpkg repo I see that the file is not there… I tried to reinstall it and even install it under 2 versions x64 and x86 but without success. I also tried to install it with cmake but the installation fails. Do you have any idea what could be causing the problem? 

Sincerely, Achour Oussama

**Comment by azat** [comment]
This file is included into the release archive:

```
$ tar -tf libevent-2.2.0-alpha-dev.tar.gz | grep bufferevent_ssl
libevent-2.2.0-alpha-dev/bufferevent_ssl.c
libevent-2.2.0-alpha-dev/include/event2/bufferevent_ssl.h
```

So likely the problem with vcpkg (I'm not familiar with it, so it is better to submit an issues to this project I guess).

**Comment by achour-oussama** [comment]
Hello, to begin with, I would like to thank you for your response.

And what do you means by adding an issue ?

**Comment by azat** [comment]
Create an issue in VCPKG project - https://github.com/microsoft/vcpkg

But I don't see anything strange there - https://github.com/microsoft/vcpkg/tree/master/ports/libevent
So I would double check first.
