### ISSUE TITLE
Call the event_free process stops unexpectedly.

### ISSUE THREAD

**Issue by LLLLLChen** [libevent/libevent#1444]
### I did this
call event_free function in my code

Occasionally, the process terminates abnormally due to signal 11. Check the call stack information. It is found that the EVLOCK_LOCK macro is accessing evthread_lock_fns_.lock.

### The call sequence is as follows:

EVLOCK_LOCK
EVBASE_ACQUIRE_LOCK
event_del_
event_del
event_free

### I expected the following
Check whether the lock is empty to prevent abnormal program termination.

### libevent version
2.1.12

**Comment by widgetii** [comment]
Please, attach your code and use GitHub repo to share it
