### ISSUE TITLE
How to increase max single read?

### ISSUE THREAD

**Issue by thuantr-dek** [libevent/libevent#1446]
I try to change following macros to 32K to increase max single read bytes.
```
# I changed these macros and compile libevent
EVBUFFER_MAX_READ, READ_DEFAULT, MAX_SINGLE_READ_DEFAULT
```
But my app (as client using libevent-2.1.12) always get callbacks (set via `evhttp_request_set_chunked_cb`)
with just maximum 16K bytes per each callback invoke.

What am I missing? Please, thank you.

**Comment by zltl** [comment]
It seems that if "Transfer-Encoding: chunked" header have been seted, libevent will call your `chunked_cb` when every chunked being received completely, then clear the input buffer. Libevent does not buffer chunked body.

https://github.com/libevent/libevent/blob/9203d98ff8f8f0a37d4d06d986ce75c299ed6444/http.c#L1078-L1085

You may move datas from input buffer to your 32K self defined array in `chunked_cb` callbacks, or request the sender to construct larger chunks.

**Comment by thuantr-dek** [comment]
But the server send data without "Transfer-Encoding: chunked" in header.

**Comment by thuantr-dek** [comment]
I use https-client sample with add chunk callback.
I think I found where causing problem, it is below block code.
```
static int
do_read(struct bufferevent_openssl *bev_ssl, int n_to_read) {
   ....
	atmost = bufferevent_get_read_max_(&bev_ssl->bev);
	if (n_to_read > atmost)
		n_to_read = atmost;

	n = evbuffer_reserve_space(input, n_to_read, space, 2);
	if (n < 0)
		return OP_ERR;

	for (i=0; i<n; ++i) {
		if (bev_ssl->bev.read_suspended)
			break;
		ERR_clear_error();
		r = SSL_read(bev_ssl->ssl, space[i].iov_base, space[i].iov_len);
```
How big `n_to_read` this function only get `n` = 1 and SSL_read() just get 1 TLS record (max 16k).

**Comment by thuantr-dek** [comment]
I try to fix this as below change
```
diff --git a/buffer.c b/buffer.c
index 0eb0425b..b9c65dfd 100644
--- a/buffer.c
+++ b/buffer.c
@@ -688,7 +688,7 @@ evbuffer_reserve_space(struct evbuffer *buf, ev_ssize_t size,
                EVUTIL_ASSERT(size<0 || (size_t)vec[0].iov_len >= (size_t)size);
                n = 1;
        } else {
-               if (evbuffer_expand_fast_(buf, size, n_vecs)<0)
+               if (evbuffer_expand_fast_(buf, 16384, n_vecs)<0)
                        goto done;
                n = evbuffer_read_setup_vecs_(buf, size, vec, n_vecs,
                                &chainp, 0);
@@ -2060,9 +2060,14 @@ evbuffer_expand_fast_(struct evbuffer *buf, size_t datlen, int n)
        if (chain == NULL || (chain->flags & EVBUFFER_IMMUTABLE)) {
                /* There is no last chunk, or we can't touch the last chunk.
                 * Just add a new chunk. */
-               chain = evbuffer_chain_new(datlen);
-               if (chain == NULL)
-                       return (-1);
+               for (int i = 0; i < n; i++)
+               {
+                       tmp = evbuffer_chain_new(datlen);
+                       if (tmp == NULL)
+                               return (-1);
+                       tmp->next = chain;
+                       chain = tmp;
+               }
 
                evbuffer_chain_insert(buf, chain);
                return (0);
```
Also increase `READ_DEFAULT, MAX_SINGLE_READ_DEFAULT` to 32K then got `n = 2` and SSL_read() twice.
Is there anything wrong with this idea?

**Comment by thuantr-dek** [comment]
Refer https://github.com/libevent/libevent/pull/1454
