### ISSUE TITLE
Running production binaries in an isolated test environment

### ISSUE THREAD

**Issue by asheplyakov** [libevent/libevent#1455]
(This is somewhat similar to #1155)

 I'd like to run production binaries in a (semi-) isolated test environment where /etc/resolv.conf might be missing/empty. However the very same binary must fail if /etc/resolv.conf is missing in the production environment.

It's possible to achieve this (via LD_PRELOAD) tricks but it would be nice to make it simpler, i.e. either set a special environment variable, or a config file knob, etc.

**Comment by azat** [comment]
@asheplyakov hi

Does a comment by @ploxiln - https://github.com/libevent/libevent/issues/1155#issuecomment-1554645836 resolves you problem?

**Comment by asheplyakov** [comment]
> @asheplyakov hi
> 
> Does a comment by @ploxiln - [#1155 (comment)](https://github.com/libevent/libevent/issues/1155#issuecomment-1554645836) resolves you problem?

Nope. My application uses libevent indirectly (via Qt and libldap). Patching and rebuilding Qt and openldap does not sound like a practical approach.

**Comment by azat** [comment]
Ok, then I'm ok with adding some env for this, but it should describe the purpose very well.

**Comment by azat** [comment]
No progress - closing
