### ISSUE TITLE
Regression tests for 2.2.1-alpha fails due to wrong version being set

### ISSUE THREAD

**Issue by diizzyy** [libevent/libevent#1457]
```
          9 - regress__SELECT (Failed)
         10 - regress__SELECT_debug (Failed)
         19 - regress__POLL (Failed)
         20 - regress__POLL_debug (Failed)
         29 - regress__KQUEUE (Failed)
         30 - regress__KQUEUE_debug (Failed)
```
All shows following error in logfile:
```FAIL /usr/ports/devel/libevent/work/libevent-release-2.2.1-alpha/test/regress.c:2632: assert((vint&0xffffff00) == ((major<<24)|(minor<<16)|(patch<<8))): 33685760 vs 33685504main/version: 1/383 TESTS FAILED.```

During configuration I noticed that wrong version were reported.
```--         ---( Libevent 2.2.0-alpha-dev )---``` 

This is due to https://github.com/libevent/libevent/blob/release-2.2.1-alpha/cmake/VersionViaGit.cmake#L26

I can also verify that all tests complete on 13.2-RELEASE (amd64)

**Comment by azat** [comment]
Hi @diizzyy 

Thank you for the report!
Fixed in https://github.com/libevent/libevent/commit/abc114e3c8b57f071ea07e06d3a3e6f35ad5b6be
