### ISSUE TITLE
bufferevent's write-callback did't triggered any more while system was overloading.

### ISSUE THREAD

**Issue by dongsf** [libevent/libevent#1466]
Hi, I'm using bufferevent_write() to forward bust of data, and libevent sending the cached data when socket is writable.
But, While the system was overloading, the auto-write processing of bufferevent did 't  work any more, and it won't work again while the load of system go down . The bufferevent_free did't deallocate the cached data aslo, this caused a lot of memory link in my case.

**Comment by azat** [comment]
Likely this is due to starvation of the event that should do writing.

You can do multiple things here:
- play with event priorities - `event_priority_set`
- play with base settings - `event_config_set_max_dispatch_interval`
- but the **most prominent is to simply use watermarks** - `bufferevent_setwatermark`

**Comment by dongsf** [comment]
Use high watermarks for writing is not guarded by libevent, we can  push data to bufferevent even it's over high-watermarks.
I have tracked the writecb of bufferevent , and the associated socket will never trigger a write event in my case even the system's load goes down. 
bufferevent_free failed to deallocate the cached data aslo.

**Comment by azat** [comment]
>The bufferevent_free did't deallocate the cached data aslo, this caused a lot of memory link in my case

It should, but it uses finalizers, so it need to enter the event loop to finally clean everything

>Use high watermarks for writing is not guarded by libevent, we can push data to bufferevent even it's over high-watermarks.

You should set the same watermarks for the socket that reads the data initially, then your buffers should not grow.

> I have tracked the writecb of bufferevent , and the associated socket will never trigger a write event in my case even the system's load goes down.

This should not happen, please provide a simpler compilable reproducer.

>ATTENTION. Calling event_base_priority_init is very important, because the default event_base only have one priority

Indeed.
