### ISSUE TITLE
wepoll.c not using libevent specific memory functions (mm_*)

### ISSUE THREAD

**Issue by SunnyPaprika** [libevent/libevent#1467]
Hi,

the wepoll.c file uses malloc instead of mm_malloc. It looks like that wepoll.c is external code that was integrated into libevent. Should it be changed to use the libevent mm_* functions?

**Comment by azat** [comment]
Yes, let's do this. Can you submit a patch? (And it would be perfect to upstream-first this patch)

**Comment by SunnyPaprika** [comment]
> Yes, let's do this. Can you submit a patch? (And it would be perfect to upstream-first this patch)

Yes, can do.
