### ISSUE TITLE
Boost Asio strand equivalent in libevent

### ISSUE THREAD

**Issue by avairavan** [libevent/libevent#1468]
We are considering to migrate from Boost to libevent. Boost libraries provides strand which enables the user to execute the code without explicitly using locks. Does libevent provides similar capabilities or should we implement our own mutex to synchronizes multiple threads spawned based on the vents?

**Comment by azat** [comment]
Hi @avairavan 

It is actually a poor design approach when you need to use locks for events, thought it is still possible with libevent, for this take a look at
- `evthreads_use_pthreads()`
- `BEV_OPT_THREADSAFE`
- `evbuffer_enable_locking`
- `LEV_OPT_THREADSAFE`

But I would strongly recommend you, to use event base per thread, to minimize the locks usage, for example consider balancing events between threads on the accept stage if you have some kind of TCP server.

**Comment by avairavan** [comment]
Thank @azat Yes, we decided to use an event base per thread to avoid using te locks.

**Comment by azat** [comment]
Yes, this is a wise choice!
