### ISSUE TITLE
libevent is not friendly to C++ projects

### ISSUE THREAD

**Issue by MilesChan** [libevent/libevent#147]
libevent is not friendly to C++ projects

such as :
1 there is a member "u16 class;" in  "struct server_reply_item",which will cause compile error.
also, there is a local variable named "u16 type, class;" in "static int
reply_parse(struct evdns_base *base, u8 *packet, int length)" 

2 more .h .c files shoud add 
#ifdef __cplusplus
extern "C" {
#endif 
//code
#ifdef __cplusplus
}
#endif

such as : 
win32select.c "struct eventop win32ops" will be complied as "_win32ops" and then cause link error
log-internal.h "event_warnx" will be compile as "_event_warnx" and then cause link error

3 Type-Cast Conversions shoud be explicit defined 
such as : 
struct deferred_reply_callback *d = mm_calloc(1, sizeof(*d));
shoud be
struct deferred_reply_callback *d = (struct deferred_reply_callback *)mm_calloc(1, sizeof(*d));

4 #define inline EVENT__inline will cause "error C4005: 'inline' : macro redefinition"
luckily,this can be fixed by add Preprocessor Definitions "_XKEYCHECK_H"

**Comment by ellzey** [comment]
C != C++. /me slams the gavel.
