### ISSUE TITLE
The libevent TCP server cannot receive all the data sent by the client.

### ISSUE THREAD

**Issue by yangxq5858** [libevent/libevent#1482]
When I sent more than 4096 bytes of data to the libevent TCP server in a single request from the client, why doesn't libevent receive all of it? After reading 4096 bytes at once, there is no more available data in the buffer.

**Comment by yangxq5858** [comment]
void accept_conn_cb(evconnlistener* listener, evutil_socket_t fd, sockaddr* address, int socklen, void* ctx)
{
    event_base* base = evconnlistener_get_base(listener);

 
    char client_ip[INET_ADDRSTRLEN];
    sockaddr_in* sin = reinterpret_cast<sockaddr_in*>(address);
    const char* ip = evutil_inet_ntop(AF_INET, &(sin->sin_addr), client_ip, sizeof(client_ip));

    printf("Client connected: %s\n", ip);

  
    bufferevent* bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE);

    // 设置读取回调函数
    bufferevent_setcb(bev, [](bufferevent* bev, void* ctx) {
        char headBuf[sizeof(ReqHeader)];
        size_t len_h = bufferevent_read(bev, headBuf, sizeof(headBuf));
        if (len_h == sizeof(ReqHeader)) {
            ReqHeader header;
            memcpy(&header, headBuf, sizeof(ReqHeader));

            // Receive data in the request here.
            int dataLen = header.size - sizeof(ReqHeader);
            char* buffer = new char[dataLen];
            int totalReceived = 0;

            // Loop to receive data until it is received completely.
            while (totalReceived < dataLen) {
                int remaining = dataLen - totalReceived;
				//The data packet sent by the client is 8760 bytes, but here only 4096-8 bytes are received //because the request header, which is 8 bytes in size, has already been read before
                int received = bufferevent_read(bev, buffer + totalReceived, remaining);
                //Here, 'received' does not capture the complete data sent by the client.  
                if (received <= 0) {
                    printf("Failed to receive data or connection closed.\n");
                    delete[] buffer;
                    return;
                }

                totalReceived += received;
            }

            // Process the received complete data.
            handleData(bev, buffer, dataLen, header.msgId);
            printf("Request data size: %d\n", dataLen);



        }
    }, nullptr, nullptr, nullptr);

    
    bufferevent_enable(bev, EV_READ);
}

**Comment by yangxq5858** [comment]
The data packet sent by the client is 8760 bytes, but here only 4096-8 bytes are received .because the request header, which is 8 bytes in size, has already been read before

**Comment by SunnyPaprika** [comment]
The data may not be delivered by the operating system / driver / network card yet. Network buffers might be to small. Can you validate with wireshark/tcpdump if everything is sent in one packet? (Also UDP might be better for "all in one packet" transmission).

You can also work with the watermark feature from libevent so that the read event only gets triggered if there is amount X of data available.

**Comment by azat** [comment]
@yangxq5858 there is no guarantee that it will be delivered at once, so your code is not correct, `bufferevent_read` removes the data that it reads, so the next time you will not have that data.

So you need to modify you program to verify `evbuffer` has enough data (`evbuffer_get_length() >= header.size`), also you can use watermarks for this.

And if you are sending data correctly then the server should receive it, check the client and fix the server accept function.

Also in addition to @SunnyPaprika comment, you can also use `strace` to verify what the server/client send/receive as well, it is simpler then using tcpdump-like tools.

**Comment by yangxq5858** [comment]
I have identified the issue, thank you everyone.
