### ISSUE TITLE
ws.c evws_send function need change

### ISSUE THREAD

**Issue by MBeanwenshengming** [libevent/libevent#1483]
```
void
evws_send(struct evws_connection *evws, const char *packet_str, size_t str_len)
{
	struct evbuffer *output;

	bufferevent_lock(evws->bufev);
	output = bufferevent_get_output(evws->bufev);
	make_ws_frame(output, TEXT_FRAME, (unsigned char *)packet_str, str_len);
	bufferevent_unlock(evws->bufev);
}
```

this function need add a param WebSocketFrameType

make_ws_frame(output, TEXT_FRAME, (unsigned char *)packet_str, str_len);  only send TEXT_FRAME

when i call evws_send send binary data, the C# client will throw exception, so evws_send need add frame type 

like this
void evws_send(struct evws_connection *evws, WebSocketFrameType frametype, const char *packet_str, size_t str_len)

thank you!!

**Comment by azat** [comment]
Thanks for the report.

@widgetii can you take a look please? We may change the function signature I guess since there wasn't any stable release with websockets yet

**Comment by widgetii** [comment]
Sure, take a look ASAP

**Comment by widgetii** [comment]
@MBeanwenshengming, Could you please check this PR, will it resolve your issue?

**Comment by widgetii** [comment]
I just thought: maybe we can use two separate functions `evws_send_text` and `evws_send_binary` to improve WS usage for end-user and get rid of `size_t str_len` argument for text version (although it will not be possible to pass "string slices" from the middle of a buffer)

**Comment by MBeanwenshengming** [comment]
Thank you very much, it solved my problem. You can modify the interface as you think, I agree with your idea, very good.
Thanks again!!!
