### ISSUE TITLE
Suggest Adoption of Scorecard GitHub Action

### ISSUE THREAD

**Issue by diogoteles08** [libevent/libevent#1485]
Hey, I'm Diogo and I've raised the issues #1421 and #1461 contributing with some security enhancements. I'll happily continue contributing with such improvements (it's literally my job, see [my profile](https://github.com/diogoteles08/diogoteles08/blob/main/README.md#about-gosst-ghost)), but this time I come to suggest the tool that I used myself to find those security issues.

I'd like to suggest that the project add the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action). The OpenSSF Scorecard uses GitHub's public API to gather public informations about your project and runs a sort of "meta-analysis" of the project's security posture. The Action then populates the project's [Security Panel](https://github.com/libevent/libevent/security) with possible improvements to its security posture. It's specially helpful to ensure you won't regress on the security measures you have already adopted 😄.

Additionally, the tool integrates with the [OSV Scanner](https://security.googleblog.com/2022/12/announcing-osv-scanner-vulnerability.html), which evaluates a project's transitive dependencies looking for known vulnerabilities.

When working on the Security enhancements pointed by Scorecard, you're also able to apply for the [OpenSSF's Secure Open Source Rewards](http://sos.dev/) program, which financially rewards developers for improving the security of important open source projects

This tool is developed by the OpenSSF [in partnership with GitHub](https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/) and it's already been adopted by 1800+ projects, including [Tensorflow](https://github.com/tensorflow/tensorflow), [PyTorch](https://github.com/pytorch/pytorch), [Angular](https://github.com/angular/angular), and [Flutter](https://github.com/flutter/flutter).

If you're interested, let me know and I'll send a PR!

**Comment by azat** [comment]
Hello Diogo!

Yes, why not, let's try!
By the way maybe you have some examples of how the reports will looks like?

>When working on the Security enhancements pointed by Scorecard, you're also able to apply for the [OpenSSF's Secure Open Source Rewards](http://sos.dev/) program, which financially rewards developers for improving the security of important open source projects

Who pays for this?

**Comment by diogoteles08** [comment]
> Yes, why not, let's try!

Awesome! I'll raise a PR with it


> By the way maybe you have some examples of how the reports will looks like?

Sure, as an example, you'll have screens like those on your Security Panel:
![image](https://github.com/libevent/libevent/assets/23556840/50fa9f93-936b-421d-ac32-a083fc5347c1)
![image](https://github.com/libevent/libevent/assets/23556840/5bf04570-ff91-4f58-b3fa-cde5550fbace)

You can also have a preview of libevent report [here](https://securityscorecards.dev/viewer/?uri=github.com/libevent/libevent) -- but note that some of the checks will be present only after you use the Scorecard Action, due to lack of permissions. By the preview, your project scores a overall 8.0/10, which puts libevent at the top 5% of relevant projects =D 

> Who pays for this?

It's paid by the Linux Foundation, with initial sponsorship from the Google Open Source Security Team (GOSST).
