### ISSUE TITLE
EVDNS_BASE_DISABLE_WHEN_INACTIVE applies too late

### ISSUE THREAD

**Issue by gysevvlad** [libevent/libevent#1488]
I faced with strange problem: event loop doesn't exit after dns resolving with `EVDNS_BASE_DISABLE_WHEN_INACTIVE`.

Stand:
- Ubuntu 22;
- libevent release-2.1.12-stable
- `resolve.conf` contains 2 nameservers;
- I use `evdns_base_new` with `EVDNS_BASE_DISABLE_WHEN_INACTIVE | EVDNS_BASE_INITIALIZE_NAMESERVERS` to avoid OS specific code.

After small investigation, look like events related with dns sockets added to event_base before `evdns->disable_when_inactive` was initialized. `libevent` did epoll_ctl(DEL) after resolving completed on the first socket, but the second socket remained in the `epoll` interest list.

I suggest small patch to solve the issue:
```C
diff --git a/evdns.c b/evdns.c
index a5b31a3..5cd83fe 100644
--- a/evdns.c
+++ b/evdns.c
@@ -4023,6 +4023,10 @@ evdns_base_new(struct event_base *event_base, int flags)
        }
 #undef EVDNS_BASE_ALL_FLAGS
 
+       if (flags & EVDNS_BASE_DISABLE_WHEN_INACTIVE) {
+               base->disable_when_inactive = 1;
+       }
+
        if (flags & EVDNS_BASE_INITIALIZE_NAMESERVERS) {
                int r;
                int opts = DNS_OPTIONS_ALL;
@@ -4040,9 +4044,6 @@ evdns_base_new(struct event_base *event_base, int flags)
                        return NULL;
                }
        }
-       if (flags & EVDNS_BASE_DISABLE_WHEN_INACTIVE) {
-               base->disable_when_inactive = 1;
-       }
 
        EVDNS_UNLOCK(base);
        return base;
```

**Comment by azat** [comment]
Thanks for the report, your patch looks good. Can you submit it as a pull request? And it will be great if you could write a unit test (in test/regress_dns.c).

**Comment by gysevvlad** [comment]
Please check #1493 

I linked PR with 1457 issue by mistake.
