### ISSUE TITLE
Incorrect CMAKE_INSTALL_RPATH

### ISSUE THREAD

**Issue by mdavidsaver** [libevent/libevent#1499]
Updating to 6db587dedb8197804e0ab760a4d86786450c7488 (and #1498) I see incorrect computation of `CMAKE_INSTALL_RPATH`.
```
cmake  -DCMAKE_INSTALL_PREFIX:PATH="/home/runner/work/.../usr/linux-x86_64" ... \
     -DCMAKE_MACOSX_RPATH=ON -DCMAKE_SKIP_INSTALL_RPATH=OFF ...
...
  -- CMAKE_SKIP_RPATH:         NO
  -- CMAKE_SKIP_INSTALL_RPATH: OFF
  -- CMAKE_INSTALL_RPATH:      /home/runner/work/.../usr/linux-x86_64
```

Note that `CMAKE_INSTALL_RPATH` is missing a trailing `/lib`.

Looking at 41a7393f3ecd1e9f58331df4653dac2e6739304e the reason seems clear enough.  `/lib` is removed from line 188/189 but not from line 185/186.  Reverting that commit brings back the `/lib`.  Also appending `/lib` to 188/189.

With 41a7393f3ecd1e9f58331df4653dac2e6739304e, was the goal to handle alternate installation layouts?  eg. multi-arch setups where `/usr/include` goes with `/usr/lib/x86_64-linux-gnu/`?

**Comment by azat** [comment]
@mdavidsaver Thanks for detailed report!

> With https://github.com/libevent/libevent/commit/41a7393f3ecd1e9f58331df4653dac2e6739304e, was the goal to handle alternate installation layouts? eg. multi-arch setups where /usr/include goes with /usr/lib/x86_64-linux-gnu/?

Yes, exactly (this was part of https://github.com/libevent/libevent/pull/1397)
Can you please submit a PR?
