### ISSUE TITLE
http.c evhttp_make_request can`t send message by vrf network

### ISSUE THREAD

**Issue by hnnrr1024** [libevent/libevent#1505]
I didn't find a function in http.h that would allow me to specify a network adapter for sending messages.
On the Linux network, the socket can use the `setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, "device", len)` function to bind a socket to send messages from a specified network adapter. This allows me to send tcp requests in the vrf network.
So when I tried to let the `evhttp_make_request` function send messages using my custom socket, I set fd in the `evhttp_connection` parameter passed in by the function, but I found that the function did not use the socket I passed in. Requests sent to other devices on the VRF network fail to be sent.
I can't find a place where I can set parameters for the fd created by the function itself after the socket is created by `evhttp_make_request` and before the connection is established.
So I tried to modify the `bufferevent_socket_connect` function in bufferevent_sock.c.
```
int
bufferevent_socket_connect(struct bufferevent *bev,
    const struct sockaddr *sa, int socklen)
{
	struct bufferevent_private *bufev_p = BEV_UPCAST(bev);

	evutil_socket_t fd;
	int r = 0;
	int result=-1;
	int ownfd = 0;

	bufferevent_incref_and_lock_(bev);

	fd = bufferevent_getfd(bev);
	if (fd < 0) {
		if (!sa)
			goto done;
		fd = evutil_socket_(sa->sa_family,
		    SOCK_STREAM|EVUTIL_SOCK_NONBLOCK, 0);
		if (fd < 0)
			goto freesock;
		ownfd = 1;
	}
```
        // Bind the device to the socket used for sending messages.
	setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, "vrf-inner", 10);
```
if (sa) {
......
```
After the compilation, HTTP requests can be sent to the VRF network, but cannot be sent to the network where other network adapters are located. Can the libevent be added as the HTTP client to specify the network adapter sending logic?

**Comment by azat** [comment]
You should not play with fd, especially on non upstream, since it does not includes #795 

But I guess you can try to use `evhttp_connection_base_bufferevent_new`, and pass `bufferevent` with `fd` that you configured.

**Comment by hnnrr1024** [comment]
> You should not play with fd, especially on non upstream, since it does not includes #795
> 
> But I guess you can try to use `evhttp_connection_base_bufferevent_new`, and pass `bufferevent` with `fd` that you configured.

I tried this, but it didn't work. So I found this when I searched again for why it didn't work.  
```
evhttp_make_request(struct evhttp_connection *evcon,
    struct evhttp_request *req,
    enum evhttp_cmd_type type, const char *uri)
{
	......
	/* If the connection object is not connected; make it so */
	if (!evhttp_connected(evcon)) {
		int res = evhttp_connection_connect_(evcon);
		/* evhttp_connection_fail_(), which is called through
		 * evhttp_connection_connect_(), assumes that req lies in
		 * evcon->requests.  Thus, enqueue the request in advance and
		 * remove it in the error case. */
		if (res != 0)
			TAILQ_REMOVE(&evcon->requests, req, next);

		return (res);
	}
......
```
In `evhttp_make_request`, the `evhttp_connection` I passed in must be a link that is not transmitting data, so when this function executes to `if (!evhttp_connected(evcon))`, I go into it.
```
int
evhttp_connection_connect_(struct evhttp_connection *evcon)
{
	......

       // No matter whether the judgment is successful or not, the bufferevent fd in the evcon is updated.
	if (evcon->bind_address || evcon->bind_port) {
		evcon->fd = bind_socket(
			evcon->bind_address, evcon->bind_port, 0 /*reuse*/);
		if (evcon->fd == -1) {
			event_debug(("%s: failed to bind to \"%s\"",
				__func__, evcon->bind_address));
			return (-1);
		}

		if (bufferevent_setfd(evcon->bufev, evcon->fd))
			return (-1);
	} else {
		if (bufferevent_setfd(evcon->bufev, -1))
			return (-1);
	}
......
```
But in the next `evhttp_connection_connect_(evcon)`, no matter what I do, it will overwrite the `fd` in the `bufferevent` I passed in the `evhttp_connection_base_bufferevent_new`.
So my pre-configured fd is not used in the actual connection.

**Comment by hnnrr1024** [comment]
> > You should not play with fd, especially on non upstream, since it does not includes #795
> > But I guess you can try to use `evhttp_connection_base_bufferevent_new`, and pass `bufferevent` with `fd` that you configured.
> 
> I tried this, but it didn't work. So I found this when I searched again for why it didn't work.
> 
> ```
> evhttp_make_request(struct evhttp_connection *evcon,
>     struct evhttp_request *req,
>     enum evhttp_cmd_type type, const char *uri)
> {
> 	......
> 	/* If the connection object is not connected; make it so */
> 	if (!evhttp_connected(evcon)) {
> 		int res = evhttp_connection_connect_(evcon);
> 		/* evhttp_connection_fail_(), which is called through
> 		 * evhttp_connection_connect_(), assumes that req lies in
> 		 * evcon->requests.  Thus, enqueue the request in advance and
> 		 * remove it in the error case. */
> 		if (res != 0)
> ......
> ```
> 
> In `evhttp_make_request`, the `evhttp_connection` I passed in must be a link that is not transmitting data, so when this function executes to `if (!evhttp_connected(evcon))`, I go into it.
> 
> ```
> int
> evhttp_connection_connect_(struct evhttp_connection *evcon)
> {
> 	......
> 
>        // No matter whether the judgment is successful or not, the bufferevent fd in the evcon is updated.
> 	if (evcon->bind_address || evcon->bind_port) {
> 		evcon->fd = bind_socket(
> 			evcon->bind_address, evcon->bind_port, 0 /*reuse*/);
> 		if (evcon->fd == -1) {
> 			event_debug(("%s: failed to bind to \"%s\"",
> 				__func__, evcon->bind_address));
> 			return (-1);
> 		}
> 
> 		if (bufferevent_setfd(evcon->bufev, evcon->fd))
> 			return (-1);
> 	} else {
> 		if (bufferevent_setfd(evcon->bufev, -1))
> 			return (-1);
> 	}
> ......
> ```
> 
> But in the next `evhttp_connection_connect_(evcon)`, no matter what I do, it will overwrite the `fd` in the `bufferevent` I passed in the `evhttp_connection_base_bufferevent_new`. So my pre-configured fd is not used in the actual connection.

**Comment by hnnrr1024** [comment]
A guess for the foregoing implementation manner is as follows: The user-defined `fd` may fail to meet the requirements of the EVHTTP due to insufficient parameters. but the `fd` can be modified by the user. Therefore, except for the FDs that are being connected, in other cases, the `fd` does not meet the requirements, you need to create an `fd` that meets the evhttp running configuration. You can find many places for configuring the FD in the `evhttp_connection_connect_` .

So I would prefer to add option configurations to the `fd` that has not yet established a connection in a possible location, rather than letting the user customize the `fd` for use.

**Comment by azat** [comment]
Which version of the sources you are referring to?

```
	} else {
		if (bufferevent_setfd(evcon->bufev, -1))
			return (-1);
	}
```

There is no such code anymore - https://github.com/libevent/libevent/blob/master/http.c#L2817-L2828

**Comment by hnnrr1024** [comment]
> evhttp_connection_connect_

> Which version of the sources you are referring to?
> 
> ```
> 	} else {
> 		if (bufferevent_setfd(evcon->bufev, -1))
> 			return (-1);
> 	}
> ```
> 
> There is no such code anymore -
> 
> https://github.com/libevent/libevent/blob/c9ec6aafb6a025f03636ae2ae7c18a2d4b8a7ed8/http.c#L2817-L2828



> Which version of the sources you are referring to?
> 
> ```
> 	} else {
> 		if (bufferevent_setfd(evcon->bufev, -1))
> 			return (-1);
> 	}
> ```
> 
> There is no such code anymore -
> 
> https://github.com/libevent/libevent/blob/c9ec6aafb6a025f03636ae2ae7c18a2d4b8a7ed8/http.c#L2817-L2828

The 2.1.12-stable version I use

**Comment by hnnrr1024** [comment]
> 

The 2.1.12-stable version I use

**Comment by azat** [comment]
Please try upstream/master.

**Comment by hnnrr1024** [comment]
> > So I would prefer to add option configurations to the fd that has not yet established a connection in a possible location, rather than letting the user customize the fd for use
> 
> The problem with adding separate option for this is that there are too much possible options. Plus if you create bufferevent by yourself it should work.
> 
> Also about your case, doesn't binding to the interface address (using `evhttp_connection_set_local_address`) does not work to make outgoing connection via specific interface?

Using` evhttp_connection_set_local_address` to bind the IP address of a specifiedinterface does not take effect. It cannot work on a specified interface.

**Comment by hnnrr1024** [comment]
The master branch solved my problem. Thanks.
