### ISSUE TITLE
Support for `visionos` as a platform

### ISSUE THREAD

**Issue by mojavad** [libevent/libevent#1507]
Hi! 

Cocoapods is set to release visionos support as a platform in v1.13 (this has already been merged to master and can be used with the unreleased version of Cocoapods). It would be good to support VisionOS with RN's pods. https://github.com/CocoaPods/CocoaPods/issues/11961

Currently, when pointing to the unreleased version of cocoapods, for React Native, `libevent` comes up as a dependency pod that  doesn't support `xros`. 

What is the process for getting it added as a platform?

**Comment by mojavad** [comment]
@azat Happy to take a look with the emulator and see if I can get it up and running (it might just be as simple as updating the pod for it)

**Comment by gabrieldonadel** [comment]
@priteshrnandgaonkar can you update the Spec here ->  https://github.com/CocoaPods/Specs/blob/master/Specs/0/9/9/libevent/2.1.12/libevent.podspec.json

**Comment by okwasniewski** [comment]
Hey! I've opened a PR to add support in this library Podspec here: https://github.com/CocoaPods/Specs/pull/14593

**Comment by azat** [comment]
No progress - closing for now, please reopen in case of any progress.
