### ISSUE TITLE
Warnings reported by Infer

### ISSUE THREAD

**Issue by zpxue** [libevent/libevent#1516]
[Infer](https://github.com/facebook/infer) is a static analyzer by facebook (last release had been done on 2021)

1. bug_type: NULL_DEREFERENCE, qualifier: pointer `bev_p` last assigned on line 308 could be null and is dereferenced at line 311, column 7., severity: ERROR, line: 311, column: 7, procedure: be_pair_flush, procedure_start_line: 304, file: libevent/bufferevent_pair.c
2. bug_type: NULL_DEREFERENCE, qualifier: pointer `bev_p` last assigned on line 267 could be null and is dereferenced at line 269, column 6., severity: ERROR, line: 269, column: 6, procedure: be_pair_unlink, procedure_start_line: 264, file: libevent/bufferevent_pair.c
3. bug_type: UNINITIALIZED_VALUE, qualifier: The value read from ss.ss_family was never initialized., severity: ERROR, line: 88, column: 6, procedure: regress_get_socket_port, procedure_start_line: 81, file: libevent/test/regress_testutils.c
4. bug_type: NULL_DEREFERENCE, qualifier: pointer `bevf` last assigned on line 609 could be null and is dereferenced at line 611, column 7., severity: ERROR, line: 611, column: 7, procedure: be_filter_ctrl, procedure_start_line: 597, file: libevent/bufferevent_filter.c
5. bug_type: NULL_DEREFERENCE, qualifier: pointer `lock` last assigned on line 404 could be null and is dereferenced at line 407, column 3., severity: ERROR, line: 407, column: 3, procedure: evthread_setup_global_lock_, procedure_start_line: 365, file: libevent/evthread.c

**Comment by azat** [comment]
New report:

```sh
$ infer run --compilation-database build/compile_commands.json
```

```
Capturing using compilation database...
Starting linting, translating 81 files
81/81 [##############################################################################] 100% 2.701s

Found 81 source files to analyze in /src/le/libevent/.cmake-debug/infer-out
81/81 [##############################################################################] 100% 46.997s

/src/le/libevent/test/regress_timer_timeout.c:33: error: Null Dereference
  pointer `cfg` last assigned on line 30 could be null and is dereferenced by call to `event_config_free()` at line 33, column 3.
  31.           event_config_set_flag(cfg, flags);
  32.           test->eb = event_base_new_with_config(cfg);
  33.           event_config_free(cfg);
        ^
  34.   } else {
  35.           test->eb = event_base_new();

/src/le/libevent/sample/http-connect.c:42: error: Null Dereference
  pointer `null` is dereferenced by call to `evhttp_uri_set_userinfo()` at line 42, column 2.
  40.   path = evhttp_uri_parse(buffer);
  41.   evhttp_uri_set_scheme(path, NULL);
  42.   evhttp_uri_set_userinfo(path, 0);
       ^
  43.   evhttp_uri_set_host(path, NULL);
  44.   evhttp_uri_set_port(path, -1);

/src/le/libevent/test/regress_watch.c:57: error: Dead Store
  The value written to &print_ (type long) is never used.
  55.   /* prepare_callback_1 should always fire before prepare_callback_2, and
  56.    * before both check callbacks */
  57.   tt_int_op(prepare_callback_1_count, >, prepare_callback_2_count);
       ^
  58.   tt_int_op(prepare_callback_1_count, >, check_callback_1_count);
  59.   tt_int_op(prepare_callback_1_count, >, check_callback_2_count);

/src/le/libevent/test/regress_watch.c:58: error: Dead Store
  The value written to &print_ (type long) is never used.
  56.    * before both check callbacks */
  57.   tt_int_op(prepare_callback_1_count, >, prepare_callback_2_count);
  58.   tt_int_op(prepare_callback_1_count, >, check_callback_1_count);
       ^
  59.   tt_int_op(prepare_callback_1_count, >, check_callback_2_count);
  60.

/src/le/libevent/test/regress_watch.c:59: error: Dead Store
  The value written to &print_ (type long) is never used.
  57.   tt_int_op(prepare_callback_1_count, >, prepare_callback_2_count);
  58.   tt_int_op(prepare_callback_1_count, >, check_callback_1_count);
  59.   tt_int_op(prepare_callback_1_count, >, check_callback_2_count);
       ^
  60.
  61.   /* if we've just scheduled the timeout event at the beginning of the


Found 1199 issues (console output truncated to 5, see '/src/le/libevent/.cmake-debug/infer-out/report.txt' for the full list)
                Issue Type(ISSUED_TYPE_ID): #
                    Dead Store(DEAD_STORE): 1118
        Null Dereference(NULL_DEREFERENCE): 43
  Uninitialized Value(UNINITIALIZED_VALUE): 36
              Resource Leak(RESOURCE_LEAK): 2
```

**Comment by azat** [comment]
So I've fixed every non false-positive warnings here - https://github.com/libevent/libevent/pull/1554

However issues may appears again, what will be interesting is to add this infer into our CI, are you interested?

BTW why you were running infer instead of [clang analyzer](https://clang-analyzer.llvm.org/)? Last infer release had been done in 2021...
