### ISSUE TITLE
Suggest hash-pin GitHub Actions with sensitive permissions and a Dependency-Update-Tool

### ISSUE THREAD

**Issue by diogoteles08** [libevent/libevent#1523]
Hi, I'm Diogo and I raised the issue #1421 suggesting you to set minimal permissions to your workflows. Now I'm coming back to  suggest a modification that would provide extra safety for the workflows that yet require dangerous permissions (e.g., `contents: write` or `checks: write`).

### Problem

Your workflows [master.yml](https://github.com/libevent/libevent/blob/master/.github/workflows/master.yml) is using dangerous permissions permissions while running external dependencies pinned only by tag. Those patterns could be dangerous because if any of those actions get hijacked (and at the end they're all repositories and are susceptible to attacks like any other), an attacker could change the code that your tags point to, gaining access to your secrets and/or write permissions to your repository.

### Proposed Solution

A simple solution for this problem would be to hash-pin those sensitive actions, pointing the actions to the very specific commit of that release. It follows and example of the change:
```
- uses: r-lib/actions/pr-fetch@v2 
would become
- uses: r-lib/actions/pr-fetch@11a22a908006c25fe054c4ef0ac0436b1de3edbe # v1.3.1
```
And this would enforce that your action is always running at the expected code.

The only downsize of this solution is that it gets trickier to manually update the version of the actions as they get out-of-date, but that can be solved by using a Dependency-Update-Tool (like dependabot or renovatebot. They can be configured to send PRs updating the dependencies on the pace that is most convenient for you (which can also be "never", and you'd only get PRs in case of security updates). For the case of the hash-pinning, the PRs would still keep a comment with the human-readable version used =).

### Conclusion
Let me know what you think of these solutions and I'd be happy to send a PR hash-pinning the relevant actions and/or adding the Dependency-Update-Tool of your preference.

Thanks!

**Comment by azat** [comment]
Hi @diogoteles08 

I see you point, but I don't want to maintain this deps manually.
How serious this flaw is in your opinion?

P.S. libevent uses more or less trusted plugins

**Comment by diogoteles08** [comment]
Hi @azat!

First, answering your question: 
According to [Scorecard Documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies), Pinning your dependencies is a measure of Medium priority. Considering your specific case, I'd also say it'd fit as a flaw of medium risk, considering that you indeed have dangerous permissions with unpinned deps, but those deps are quite trustful (e.g. the ones from github itself).

Now complementing my answer:

I'm not sure I understood what you meant by "maintain the deps manually", but are you considering the help from the Dependency-Update-Tools? They would make sure to automatically create PRs updating your dependencies at the pace that conveys to your demands. I.e., we can configure it to create PRs only updating major versions, only minors, only security updates, etc. 

That said, having a Dependency-Update-Tool is also a [requirement from Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool), and one of High priority (mostly for making sure you'd have access to security updates as soon as they're released). So I'd suggest that you consider this, independently of your decision around hash-pinning the dependencies =).

Let me know your thoughts and I can act on a PR with whatever you decide.

**Comment by azat** [comment]
>I'm not sure I understood what you meant by "maintain the deps manually", but are you considering the help from the Dependency-Update-Tools? They would make sure to automatically create PRs updating your dependencies at the pace that conveys to your demands. I.e., we can configure it to create PRs only updating major versions, only minors, only security updates, etc.

To be honest, I don't see the difference in this case, from my point of view, it will improve the security only if someone will take a look at the plugins/changes before update, if some bot will do this, then it does not looks better then simply using official tags.

**Comment by diogoteles08** [comment]
Hi @azat, That's a very valid concern and we have even created the issue https://github.com/ossf/scorecard/issues/3549 to clarify this differences (we're still pending to update the issue with our conclusions). 

The main advantage is that by hashpinning dependencies and using a Dependency-Update-Tools, your dependencies won't be updated right after the new version is released. So you have a larger time period to ensure any malicious releases are detected by the community before they're consumed by your project.

As an example, consider [this attack on python ecosystem](https://python-security.readthedocs.io/pypi-vuln/index-2022-05-24-ctx-domain-takeover.html). In summary, the `ctx` python package was compromised and the project reference in pypi was replaced by a malicious version -- i.e., every project that installed this dependency without proper pinning had the malicious version installed. This `ctx` problem was detected by the community ~1 week after the attack.

Considering the example, if the dependency was pinned and a Dependency-Update-Tool was used, there would be considerabe changes that the problem would be detected before the new version was suggested to you and/or you merged the Dependabot PR. That's even clearer when you consider that Dependabot doesn't suggest updates to version that has a CVE registered, and you could also choose to update your versions only after some time the new version was released.

**Comment by azat** [comment]
Okay, I misread your initial report, apparently dependabot could update github actions as well, then I'm OK with this approach (I hope that there will be not a lot of changes, since I don't want extra PR noise for this project, since it may force people to think that it is under "active development" which is far from true).

So please submit a PR, I will take a look.

P.S. sorry for the delay, I don't have lots of spare time for libevent this days...

**Comment by azat** [comment]
To be honest, I'm not sure that we have capacity to pin actions, sadly but, libevent is not under active development

**Comment by diogoteles08** [comment]
Hi! Sorry for the delay on getting back here. 

I can configure dependabot to raise monthly PRs updating all the relevant GitHub actions in a single PR -- and in case of any important security updates, they'd be raised separately and immediately. Do you think that would be something you'd be able to maintain?

As you said libevent is not under active development anymore, I'd understand if you say you don't want to take this responsability. If that is the case, I think it'd be better to keep the version as they are -- this would make the project vulnerable to unwanted (or malicious) updates, but at least we'd be sure the actions would get the last updates(and any security updates, if they happen).

**Comment by azat** [comment]
>I can configure dependabot to raise monthly PRs updating all the relevant GitHub actions in a single PR -- and in case of any important security updates, they'd be raised separately and immediately. Do you think that would be something you'd be able to maintain?

Let's try
