### ISSUE TITLE
Which version is currently most suitable for libevent？

### ISSUE THREAD

**Issue by XYQ202** [libevent/libevent#1524]
We need to use the Libevent library. Currently, we have checked the source code of the master branch that has been being modified on GitHub. Additionally, there is a stable version 2.1.12 from 3 years ago, but we want to use the latest stable version. Can we use the source code of the master branch? When will a new stable version of the source code be updated?

**Comment by XYQ202** [comment]
We need to use the Libevent library. Currently, we have checked the source code of the master branch that has been being modified on GitHub. Additionally, there is a stable version 2.1.12 from 3 years ago, but we want to use the latest stable version. Can we use the source code of the master branch? When will a new stable version of the source code be updated?

**Comment by widgetii** [comment]
We use latest master branch in production on hundred thousands IP cameras in openipc.org project and didn't find anything bad yet, so it's considered stable now
