### ISSUE TITLE
libevent debugging

### ISSUE THREAD

**Issue by yungjenhung** [libevent/libevent#1528]
We are running [fluent-bit ](https://github.com/fluent/fluent-bit) on Windows AKS clusters. However, the fluent-bit process sometime experiences high CPU usage. It seems like one thread is stuck while processing events, `event_base_loop` of libevent, and leads to high CPU usage. 

```
ntoskrnl!ObpReferenceObjectByHandleWithTag
ntoskrnl!ObReferenceObjectByHandle
afd!AfdPoll64
afd!AfdPoll
afd!AfdDispatchDeviceControl
ntoskrnl!IofCallDriver
ntoskrnl!IopSynchronousServiceTail
ntoskrnl!IopXxxControlFile
ntoskrnl!NtDeviceIoControlFile
ntoskrnl!KiSystemServiceCopyEnd
ntdll!NtDeviceIoControlFile
mswsock!WSPSelect
ws2_32!select
fluent-bit!win32_dispatch
fluent-bit!event_base_loop
fluent-bit!_mk_event_wait_with_flags
fluent-bit!_mk_event_wait_2
fluent-bit!mk_event_wait
fluent-bit!flb_engine_start
fluent-bit!flb_lib_worker
fluent-bit!pthread_create_wrapper
fluent-bit!thread_start<unsigned int (__cdecl*)(void *), System.__Canon>
kernel32!BaseThreadInitThunk
ntdll!RtlUserThreadStart
```

Additionally, the memory dump shows that the timeout value of select, `tv_p`, was set to zero, which means select will return immediately, be called it in a tight loop, and explains why thread is taking the high CPU.

https://github.com/fluent/fluent-bit/blob/9b9c800d76f6310ab0241b253a783ea6283dff2c/lib/monkey/mk_core/deps/libevent/event.c#L1947C1-L1948C1
```
                res = evsel->dispatch(base, tv_p);
```

And the timeout value of top event from timeheap is already passed, that why the timeout value was cleared.
https://github.com/fluent/fluent-bit/blob/9b9c800d76f6310ab0241b253a783ea6283dff2c/lib/monkey/mk_core/deps/libevent/event.c#L3109C1-L3110C1
```
	if (evutil_timercmp(&ev->ev_timeout, &now, <=)) {
		evutil_timerclear(tv);
		goto out;
	}
```

However, we don't know how it was triggered and what was the possible cause. What is your recommendation for debugging libevent?

**Comment by azat** [comment]
You can:
- try to upgrade libevent (even to upstream, the only reason there  is no stable release is the lack of time)
- enable debugging capatibilities - `event_enable_debug_mode`
- enable debug logging - `event_enable_debug_logging` - but this will produce tons of longs and it is hard to debug

I think that it will be better to hack some code around to print debugging information when such event occurs, or even just attach with debugging and print i.e. `event_base_dump_events`
