### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation) make[1]: *** [sample/le-proxy] Error 1

### ISSUE THREAD

**Issue by a1270107629** [libevent/libevent#1531]
hello, when I use 
./configure PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@1.1/lib/pkgconfig --prefix=/usr/local 
generate Makefile,and then  "make". It gets some problem   
ld: warning: -undefined suppress is deprecated
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CCLD     sample/dns-example
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CC       sample/event-read-fifo.o
  CCLD     sample/event-read-fifo
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CC       sample/hello-world.o
  CCLD     sample/hello-world
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CC       sample/http-server.o
  CCLD     sample/http-server
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CC       sample/http-connect.o
  CCLD     sample/http-connect
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CC       sample/signal-test.o
  CCLD     sample/signal-test
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CC       sample/time-test.o
  CCLD     sample/time-test
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
  CC       sample/le_proxy-le-proxy.o
  CC       libevent_openssl_la-bufferevent_openssl.lo
  CCLD     libevent_openssl.la
ld: warning: -undefined suppress is deprecated
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
ld: warning: ignoring file '/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libssl.1.1.dylib': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libcrypto.1.1.dylib': found architecture 'arm64', required architecture 'x86_64'
  CCLD     sample/le-proxy
ld: warning: search path '/opt/homebrew/Cellar/qt/6.1.3/lib' not found
ld: warning: ignoring file '/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libssl.1.1.dylib': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libcrypto.1.1.dylib': found architecture 'arm64', required architecture 'x86_64'
ld: Undefined symbols:
  _ERR_func_error_string, referenced from:
      _eventcb in le_proxy-le-proxy.o
  _ERR_lib_error_string, referenced from:
      _eventcb in le_proxy-le-proxy.o
  _ERR_reason_error_string, referenced from:
      _eventcb in le_proxy-le-proxy.o
  _RAND_poll, referenced from:
      _main in le_proxy-le-proxy.o
  _SSL_CTX_new, referenced from:
      _main in le_proxy-le-proxy.o
  _SSL_new, referenced from:
      _accept_cb in le_proxy-le-proxy.o
      _accept_cb in le_proxy-le-proxy.o
  _TLS_method, referenced from:
      _main in le_proxy-le-proxy.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [sample/le-proxy] Error 1
make: *** [all] Error 2

**Comment by azat** [comment]
>ld: warning: ignoring file '/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/libssl.1.1.dylib': found architecture 'arm64', required architecture 'x86_64'

This is the problem, you need to install openssl for x86_64
