### ISSUE TITLE
How to deal with bufferevent pointer when used externally?

### ISSUE THREAD

**Issue by Xuzhangxin** [libevent/libevent#1560]
I have a question. When using bufferevent, if I save the bufferevent pointer to my own user program, such as m_bufferEvent, when I need to send data, I directly use bufferevent_write(m_bufferEvent, data, dataLen);, then this m_bufferEvent , do I need to use a lock to manage it myself? If I don't add a lock myself, when concurrent access occurs (bufferevent_free and write occur at the same time), it seems that the program will hang.

**Comment by Xuzhangxin** [comment]
please

**Comment by azat** [comment]
Take a look at event_use_pthreads and BEV_OPT_THREADSAFE.

**Comment by azat** [comment]
After calling `bufferevent_free` you should not use the bufferevent, it is your responsibility.

I would recommend you to wrap `bufferent *` into `shared_ptr` with custom deleter as `bufferevent_free` and this will work like a charm.

**Comment by Xuzhangxin** [comment]
okay, thank you very much. I understand what you mean!
