### ISSUE TITLE
Problem building when MACOSX_DEPLOYMENT_TARGET set on maxOS

### ISSUE THREAD

**Issue by jsquyres** [libevent/libevent#1571]
Per https://github.com/open-mpi/ompi/issues/12168 and https://github.com/open-mpi/ompi/issues/12358, we've noticed that the Libevent 2.1.12 tarball build fails on macOS when the `MACOSX_DEPLOYMENT_TARGET` environment variable is set.

For example:

```
wget https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
tar xf libevent-2.1.12-stable.tar.gz
cd libevent-2.1.12-stable
export MACOSX_DEPLOYMENT_TARGET=11.0
./configure --disable-openssl --prefix=/tmp/bogus
...snipped output...
make
...snipped output...
  CCLD     libevent_core.la
  CCLD     libevent.la
  CCLD     libevent_extra.la
  CCLD     libevent_pthreads.la
1 warning generated.
Undefined symbols for architecture arm64:
  "_EVUTIL_ISALNUM_", referenced from:
      _evhttp_uri_parse_with_flags in http.o
      _evhttp_uri_set_scheme in http.o
  "_EVUTIL_ISALPHA_", referenced from:
      _request_new in evdns.o
      _evhttp_uri_parse_with_flags in http.o
      _evhttp_uri_set_scheme in http.o
...many more similar errors
```

However, if we unset `MACOX_DEPLOYMENT_TARGET` and re-`configure` / re-`make`, everything is fine.

One of our users noticed that if they have modern GNU Autotools installed and re-run `autogen.sh`, then setting `MACOX_DEPLOYMENT_TARGET` does not cause any problems.  Hence, the problem could simply be the old versions of the GNU Autotools that were used to bootstrap the Libevent 2.1.12 tarball.

Per #1512, is there any ETA when Libevent 2.2.0 -- assumedly bootstrapped with modern versions of the GNU Autotools -- will be available?  Or even a 2.1.13 (even if the only change is being re-bootstrapped with modern versions of the GNU Autotools?)

Thank you for Libevent!

**Comment by azat** [comment]
Thanks for the report.

> Per https://github.com/libevent/libevent/issues/1512, is there any ETA when Libevent 2.2.0

It should be done long time ago... So I don't want to give any ETA .
But basically there is almost zero blockers

> Or even a 2.1.13 (even if the only change is being re-bootstrapped with modern versions of the GNU Autotools?)

2.1 is unsupported

**Comment by azat** [comment]
Also, can you compile from sources (from master branch), will it work?

**Comment by azat** [comment]
And verify which minimal autotools  version is required, this will really helps.

Also note, that I want to deprecated autotools build system, cmake should be used instead. Can you also give cmake a try?

**Comment by jsquyres** [comment]
> It should be done long time ago... So I don't want to give any ETA .
> But basically there is almost zero blockers

Fair enough.

> 2.1 is unsupported

What versions are supported?

> Also, can you compile from sources (from master branch), will it work?

Compiling on my Mac with all the latest Autotools, both master and the v2.1.12 tarball compile+link fine.

```
$ autoconf --version | head -n 1; automake --version | head -n 1; glibtool --version | head -n 1                               
autoconf (GNU Autoconf) 2.72
automake (GNU automake) 1.16.5
glibtool (GNU libtool) 2.4.7
```

> And verify which minimal autotools version is required, this will really helps.

I can install / try older versions of the Autotools, but that will take a little time.  Is there a reason to use something other than the most recent versions?

> Also note, that I want to deprecated autotools build system, cmake should be used instead. Can you also give cmake a try?

For what it's worth: cmake would not be preferred for us.  Open MPI (and associated projects) are all 100% Autotools.

**Comment by jsquyres** [comment]
To close the loop on this already-closed issue -- I haven't been able to find the time to comprehensively test older versions of the Autotools to find the minimal versions that work.  I don't know if that matters, though.  If there's a reason to use something other than the latest versions (which we know do work properly), let me know and I'll try to find the time.

**Comment by azat** [comment]
Thanks for the follow up!

>If there's a reason to use something other than the latest versions

@jsquyres no reasons, this is just to increase compatibility, likely, libevent could be used with lots of old toolchains, but unlikely they need MACOSX_DEPLOYMENT_TARGET, so it is ok to do nothing here :)
