### ISSUE TITLE
 📚  Where is documentation?

### ISSUE THREAD

**Issue by derskythe** [libevent/libevent#1584]
Hi, 
I tried for two days, but this link to docs gives timeout: http://www.wangafu.net/~nickm/libevent-book/

Does anybody have copy of this site or some other saved documents?

**Comment by azat** [comment]
Book - https://libevent.org/libevent-book/

Reference - https://libevent.org/doc/

Official web site that contains all proper links - https://libevent.org/

**Comment by derskythe** [comment]
> Official web site that contains all proper links - https://libevent.org/

I am sorry, but no.

![image](https://github.com/libevent/libevent/assets/31771569/b77ba2bf-1e2c-4dd1-ac74-52b979d6d24c)

**Comment by azat** [comment]
Doc only for the latest release is located on libevent.org
For older releases on the @nmathewson web site, and it works to me:

```
$ curl --location --head http://www.wangafu.net/~nickm/libevent-2.0/doxygen/html
HTTP/1.1 301 Moved Permanently
Date: Sat, 30 Mar 2024 14:31:19 GMT
Server: Apache/2.4.57 (Debian)
Location: http://www.wangafu.net/~nickm/libevent-2.0/doxygen/html/
Connection: close
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Sat, 30 Mar 2024 14:31:19 GMT
Server: Apache/2.4.57 (Debian)
Last-Modified: Fri, 03 Mar 2017 09:05:51 GMT
ETag: "32b7-549cfda2d19c0"
Accept-Ranges: bytes
Content-Length: 12983
Vary: Accept-Encoding
Connection: close
Content-Type: text/html; charset=UTF-8
```

So looks like some issues on your side (some firewall in the middle)

**Comment by derskythe** [comment]
@azat Thanks, I think it depends on the country 🇦🇿 . Tried it on home, work and mobile Internet
