### ISSUE TITLE
Potential NULL pointer dereference

### ISSUE THREAD

**Issue by icy17** [libevent/libevent#1591]
I'm not sure how to fix these potential bugs because I don't know which value should be returned...

1. In evdns.c: 3328, calling [evdns_base_nameserver_add](https://github.com/libevent/libevent/blob/master/evdns.c#L3328) without checking the parameter 1 might cause null dereference.  
2. In evdns.c: 3380, calling [evdns_base_nameserver_ip_add](https://github.com/libevent/libevent/blob/master/evdns.c#L3380) without checking the parameter 1 might cause null dereference.  
3. In evdns.c: 4429, calling [evdns_base_set_option](https://github.com/libevent/libevent/blob/master/evdns.c#L4429) without checking the parameter 1 might cause null dereference.  
4. In evdns.c: 4581, calling [evdns_base_resolv_conf_parse](https://github.com/libevent/libevent/blob/master/evdns.c#L4581) without checking the parameter 1 might cause null dereference.  

I'd be glad to submit a patch via a pull request if you could specify the appropriate return value for an error.

**Comment by azat** [comment]
This is deprecated API and should not be used (API without passing base explicitly and that uses global base instead is a poor design choice and had been deprecated).

If you are interested, you can add deprecated attribute for this API, until 2.2 releasted
