### ISSUE TITLE
Potential Null pointer dereference in bufferevent_openssl.c

### ISSUE THREAD

**Issue by icy17** [libevent/libevent#1599]
1. In libevent/bufferevent_openssl.c:183, calling [bufferevent_get_input](https://github.com/libevent/libevent/blob/master/bufferevent_openssl.c#L183) without checking the parameter 1 might cause null dereference.
2. In libevent/bufferevent_openssl.c:186, calling [bufferevent_get_output](https://github.com/libevent/libevent/blob/master/bufferevent_openssl.c#L186) without checking the parameter 1 might cause null dereference.

**Comment by azat** [comment]
It should never be NULL, but it is ok to add an `EVUTIL_ASSERT`
