### ISSUE TITLE
Potential Null pointer dereference in regress_ws.c

### ISSUE THREAD

**Issue by icy17** [libevent/libevent#1604]
1. In test/regress_ws.c: 354, calling [bufferevent_setcb](https://github.com/libevent/libevent/blob/master/test/regress_ws.c#L354) without checking the parameter 1 might cause null dereference.
2. In test/regress_ws.c: 372, calling [bufferevent_setcb](https://github.com/libevent/libevent/blob/master/test/regress_ws.c#L372) without checking the parameter 1 might cause null dereference.

**Comment by azat** [comment]
Let's add an `tt_ptr_op`/`tt_assert`
