### ISSUE TITLE
Potential Null pointer dereference in time-test.c

### ISSUE THREAD

**Issue by icy17** [libevent/libevent#1608]
1. In libevent/sample/time-test.c:109, calling [event_add](https://github.com/libevent/libevent/blob/master/sample/time-test.c#L109) without checking the parameter 1 might cause null dereference.
2. In libevent/sample/time-test.c:110, calling [event_add](https://github.com/libevent/libevent/blob/master/sample/time-test.c#L110) without checking the parameter 1 might cause null dereference.

**Comment by azat** [comment]
Ok, let's add normal error path
