### ISSUE TITLE
An enhancement request

### ISSUE THREAD

**Issue by user1020** [libevent/libevent#161]
I have to make huge number of calls to function evbuffer_readln(...),  I would have free the pointer returned from this function afterwards.  This is very wasteful.

wonder if it's possible to supply a buffer as a parameter to this function so that it can put the returned data in this buffer instead of having to mallocing a buffer internally and expect caller to free it?

Thanks.

**Comment by ellzey** [comment]
The answer seems to be supplied. Closing; reopen if you figure otherwise.
