### ISSUE TITLE
Undefined symbols for architecture after building libevent

### ISSUE THREAD

**Issue by pickDefault** [libevent/libevent#1620]
Platform: OSX Mac M1, Sonoma 23.4.0

I'm running into an "undefined symbols" error when trying to compile a simple program with libevent:
```c
#include <event2/event.h>

int main() {
    struct event_base* base = event_base_new();
}
```
```
$ clang -I/opt/homebrew/Cellar/libevent/2.1.12_1/include main.c
Undefined symbols for architecture arm64:
  "_event_base_new", referenced from:
      _main in main-e671ab.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Originally I installed libevent via `brew`, which yielded this error.
I removed the brew installation and downloaded `libevent-2.1.12-stable.tar`, and installed using `autoconf.sh`, `./configure` and `sudo make install`.
This installed the library files at `/usr/local/include`, but compiling the above program with the command
```bash
$ clang -I/usr/local/include main.c
```
yielded the same error as above.

I uploaded the output of each command here:
[autogen_log.txt](https://github.com/libevent/libevent/files/15037018/autogen_log.txt)
[clang_log.txt](https://github.com/libevent/libevent/files/15037019/clang_log.txt)
[configure_log.txt](https://github.com/libevent/libevent/files/15037020/configure_log.txt)
[make_verify_log.txt](https://github.com/libevent/libevent/files/15037021/make_verify_log.txt)
[sudo_make_install_log.txt](https://github.com/libevent/libevent/files/15037023/sudo_make_install_log.txt)

I did notice that `autogen` said "You should run autoupdate" multiple times, but when I did run `autoupdate` before `autogen`, I get the following syntax error when running `./configure`:
```sh
./configure: line 5551: syntax error near unexpected token `newline'
./configure: line 5551: `yes:'
```
This is the script after `autoupdate`:
[configure.txt](https://github.com/libevent/libevent/files/15037207/configure.txt)

I would really appreciate help on this as I'm lost on what to do.

**Comment by widgetii** [comment]
You don't link libraries, so that's the root cause of the issue

You may use `clang $(pkg-config --cflags --libs libevent) main.c` instead

**Comment by pickDefault** [comment]
Thanks!

**Comment by pickDefault** [comment]
Thanks!
