### ISSUE TITLE
MacOS CI is broken

### ISSUE THREAD

**Issue by azat** [libevent/libevent#1632]
### autotools

```
ld: warning: search path '/usr/local/opt/mbedtls@2/lib' not found
ld: library 'ssl' not found
```

### cmake flaky tests

```
49/64 Test #49: regress__KQUEUE .....................***Failed   90.19 sec
[warn] evbuffer_file_segment_materialize: mmap(4, 0, 0) failed: Invalid argument
[Lost connection!] 1/353 TESTS FAILED. (41 skipped)

      Start 50: regress__KQUEUE_debug
50/64 Test #50: regress__KQUEUE_debug ...............***Failed   90.26 sec
[warn] evbuffer_file_segment_materialize: mmap(4, 0, 0) failed: Invalid argument
[Lost connection!] 1/353 TESTS FAILED. (41 skipped)
```

**Comment by Coeur** [comment]
You do:
https://github.com/libevent/libevent/blob/64decd48e20f6d20d6f510aa75ab05861fd3d51c/.github/workflows/build.yml#L554

Then you wrongly assume the path:
https://github.com/libevent/libevent/blob/64decd48e20f6d20d6f510aa75ab05861fd3d51c/.github/workflows/build.yml#L586

The actual path is dependent on whether the machine is Intel or Apple Silicon. On recent macOS, GitHub will mostly use Apple Silicon, so path should be `/opt/homebrew/opt/mbedtls@2` instead. And for OpenSSL, it should be `/opt/homebrew/opt/openssl`

**Comment by azat** [comment]
Hm, didn't knew that github actions provides apple silicon support now (previously it was only for paid users), great!

**Comment by azat** [comment]
The issue is not fixed completely, only first steps

**Comment by Coeur** [comment]
I ran the tests locally on my Mac:
```
      Start 50: regress__KQUEUE

50/65 Test #50: regress__KQUEUE .....................   Passed   96.63 sec

      Start 51: regress__KQUEUE_debug

51/65 Test #51: regress__KQUEUE_debug ...............   Passed   96.81 sec
```

So I'm proposing an improvement in the failure message for further debugging: #1662

**Comment by Coeur** [comment]
The results of the log improvements from https://github.com/libevent/libevent/pull/1662 show that we're passing 0 to the length argument of mmap, which is not allowed: https://man7.org/linux/man-pages/man2/mmap.2.html
So backtracking, it means `seg->length` and `seg->file_offset` were both 0.

**Comment by Coeur** [comment]
@nmathewson would you know why in GitHub Actions, `evbuffer_file_segment_materialize` is called with length and file_offset of 0 in regress__KQUEUE, while locally on my Mac that never happens?

**Comment by azat** [comment]
>The results of the log improvements from https://github.com/libevent/libevent/pull/1662 show that we're passing 0 to the length argument of mmap, which is not allowed: [man7.org/linux/man-pages/man2/mmap.2.html](https://man7.org/linux/man-pages/man2/mmap.2.html)

Yes, but I was needed this for the test - https://github.com/libevent/libevent/pull/1559

**Comment by Coeur** [comment]
Maybe a coincidence, but with #1682, all the mac pipelines are passing.

**Comment by theoden8** [comment]
I'm getting this on regress__SELECT:

```
mbedtls/bufferevent_renegotiate_socketpair: [forking] [warn] BUG: Unexpected mbedtls error code -30464: SSL - An unexpected message was received from our peer
[warn] BUG: Unexpected mbedtls error code -29312: SSL - The connection indicated an EOF

  FAIL libevent/test/regress_ssl.c:403: assert(test_is_done == 1)
  [FAILED mbedtls/bufferevent_renegotiate_socketpair (0 retries)]
mbedtls/bufferevent_renegotiate_filter: [forking] [warn] BUG: Unexpected mbedtls error code -30464: SSL - An unexpected message was received from our peer

  FAIL libevent/test/regress_ssl.c:403: assert(test_is_done == 1)
  [FAILED mbedtls/bufferevent_renegotiate_filter (0 retries)]
mbedtls/bufferevent_socketpair_startopen: [forking] OK
mbedtls/bufferevent_filter_startopen: [forking] OK
mbedtls/bufferevent_socketpair_dirty_shutdown: [forking] OK
mbedtls/bufferevent_filter_dirty_shutdown: [forking] OK
mbedtls/bufferevent_renegotiate_socketpair_dirty_shutdown: [forking] [warn] BUG: Unexpected mbedtls error code -30464: SSL - An unexpected message was received from our peer
[warn] BUG: Unexpected mbedtls error code -29312: SSL - The connection indicated an EOF

  FAIL libevent/test/regress_ssl.c:403: assert(test_is_done == 1)
  [FAILED mbedtls/bufferevent_renegotiate_socketpair_dirty_shutdown (0 retries)]
mbedtls/bufferevent_renegotiate_filter_dirty_shutdown: [forking] [warn] BUG: Unexpected mbedtls error code -30464: SSL - An unexpected message was received from our peer

  FAIL libevent/test/regress_ssl.c:403: assert(test_is_done == 1)
  [FAILED mbedtls/bufferevent_renegotiate_filter_dirty_shutdown (0 retries)]
```

**Comment by theoden8** [comment]
This is the failing block according to latest CI:

https://github.com/libevent/libevent/blob/b2192269825b09bbb4496cc843938108eeb1bdfb/test/regress.c#L1047-L1087

**Comment by azat** [comment]
>However, if I run these in a while loop locally it passes each time.

Going to merge this workaround for now https://github.com/libevent/libevent/pull/1737

No clue why it happens though, but you can try it on your own - `yes signal/simple_signal | head -n 1000 | xargs -I{} -P10 sh -c 'EVENT_DEBUG_LOGGING_ALL= bin/regress --timeout 0 --verbose {} >& /tmp/test.$SECONDS.$RANDOM.log'` it reproduces pretty stable

**Comment by theoden8** [comment]
That's probably why these random fails don't occur when you disable all other tests and only enable signal-related ones.
