### ISSUE TITLE
feature request: http/3 client

### ISSUE THREAD

**Issue by liudongmiao** [libevent/libevent#1650]
There is udp request on libevent. Now, it's the time for udp and quic.

For client, there would be two parts:
- udp client
- quic over udp client, requires ssl library, and maybe nghttp3

For server, there would be two parts:
- udp server
- quic over udp server, requires ssl library -- do we need to support this?

In the low-level view, udp is nothing different from tcp in the event of libevent.
However, if we want to offer extra `bufferevent` like `bufferevent_socket_new` / `bufferevent_socket_connect` for tcp, we should offer.

**Comment by liudongmiao** [comment]
[LiteSpeed QUIC](https://github.com/litespeedtech/lsquic) is a quic library, and use libevent in examples.

**Comment by liudongmiao** [comment]
@azat IMO, libevent don't have to offer something like bufferevent_sock_udp, or even make bufferevent_openssl support quic. However, libevent should return the size of bufferevent_private, so that bufferevent can be extend like bufferevent_openssl (or buffereent_ssl in master), bufferevent_filter, bufferevent_pair, etc.

If we have no `bufferevent_private`, then most functions of `bufferevent_xxx` cannot be used, as most of them requires the bufferevent is `bufferevent_private` (the lock).

In the way of implementing openssl quic / http3, I use the `bufferevent_socket` (core part of `bufferevent_private`), then rewrite the callback of `ev_write` and `ev_read`, and store the extend part like `bufferevent_filter` / `bufferevent_openssl` as bufferevent_context in watermark read / write low, as I found they are only be called in `ev_write` / `ev_read` callback, and as I rewrite the callback, so I can use it. (size_t have the same size of void *).

BTW, I use the same trick to implement socket udp (udp socket have special recv and send, and for server, we use the same sock to recv), and implement a simple http2, and websocket over http2, of course, and websocket over http3.

**Comment by azat** [comment]
>However, libevent should return the size of bufferevent_private, so that bufferevent can be extend like bufferevent_openssl (or buffereent_ssl in master), bufferevent_filter, bufferevent_pair

This sounds very ad-hoc.

It will be great to see this as part of libevent, as a separate bufferevent layer.
