### ISSUE TITLE
windows socks5 combo mbedtls client:  [warn] BUG: Unexpected mbedtls error code -29184: SSL - An invalid SSL record was received

### ISSUE THREAD

**Issue by j421037** [libevent/libevent#1651]
I completed the handshake verification of socks5 using Bufferevent， and use bufferevent_mbedtls_filter_new(g_base, bev, ssl, BUFFEREVENT_SSL_CONNECTING, BEV_OPT_CLOSE_ON_FREE | BEV_OPT_DEFER_CALLBACKS) create a new ssl bufferevent. but request failed

log message:  [warn] BUG: Unexpected mbedtls error code -29184: SSL - An invalid SSL record was received
mbedtls version: 2.26.0
libevent version: master branch

**Comment by j421037** [comment]
The same situation applies when I use bufferevent_openssl_filter_new create a openssl bufferevent.
log message:  
      some request failed - no idea which one though!
      socket error = 在一个非套接字上尝试了一个操作。 (10038)

**Comment by azat** [comment]
libevent just uses MbedTLS, and it is hard to say without libevent related sample that will produce this error.

But one thing that pops up - ensure that you have one MbedTLS version in the binary, you can read comments here https://github.com/libevent/libevent/pull/1719 for more context
