### ISSUE TITLE
bufferevent_write deadlock

### ISSUE THREAD

**Issue by happybanban** [libevent/libevent#1670]
Hello,
bufferevent_write may be deadlocked sometimes. It can not be returned sometimes.

I have already called evthread_use_pthreads.

It's under ubuntu 16.04

Any ideas?

Thanks!

**Comment by azat** [comment]
Please check you program under [TSan](https://clang.llvm.org/docs/ThreadSanitizer.html) and also with [ASan](https://clang.llvm.org/docs/AddressSanitizer.html)

If you will not find the problem you may submit minimal reproducer here

**Comment by aFoxWithDream** [comment]
I am facing the same problem:
m_pBev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE | BEV_OPT_THREADSAFE);
the base i created in another thread;
when i use like this
	void Send(std::string& data)
	{

               std::lock_guard<std::mutex> l(lock);
		if (!m_bConnect || !m_bLogon || m_pBev == NULL)
			return;	
		bufferevent_write(m_pBev, data.c_str(), data.size());	
	}
Send are used by multithread.
then bufferevent_write dead lock.  i used evthread_use_pthreads(); 
The version is libevent-2.0.20-stable.

Any ideas?
Thanks!

**Comment by aFoxWithDream** [comment]
i found the problem is： maybe i used Send on recv_cb。

**Comment by happybanban** [comment]
> i found the problem is： maybe i used Send on recv_cb。

Thanks for your share! But I do not call bufferevent_write on recv_cb callback.  I only call bufferevent_write on my new thread. Now I add a dead-lock checking on my code,  If dead lock happened , I restart my programe.

**Comment by azat** [comment]
>The version is libevent-2.0.20-stable.

Please use fresh libevent version

**Comment by azat** [comment]
And please, use TSan to find deadlocks

**Comment by azat** [comment]
bufferevent_write is too generic, it is impossible to debug without details/reproducer.

**Comment by cucxbd** [comment]
> i found the problem is： maybe i used Send on recv_cb。

Hello, have you solved this problem? I also had the similar problem : i read bufferevent A in thread A  read callback，and try to write bufferevent B; But at the same time, bufferevent B read callback is also triggered in thread B,  the B read callback try to write bufferevent A.  I found the flag BEV_OPT_UNLOCK_CALLBACKS, but not sure if it is useful
