### ISSUE TITLE
Websocket connection fails with 404 for request header "Connection: keep-alive, Upgrade" (Firefox)

### ISSUE THREAD

**Issue by chme** [libevent/libevent#1694]
I started playing around with the websocket server support in libevent and ran into the issue, that it is working when using Chromium, but it is failing when using Firefox 128 (Linux).

This issue is reproducible with the `ws-chat-server.c` example.

I tracked the issue down to the different "Connection" header values Chromium and Firefox are using:

- Chromium: `"Connection: Upgrade"`
- Firefox: `"Connection: keep-alive, Upgrade"`

The problem is the check for this header in `evws_new_session(...)`:

https://github.com/libevent/libevent/blob/7f23b5b5aa61f5496627c2651fd6d8185f34ffde/ws.c#L388-L390

I am uncertain, whether the "keep-alive" should be simply ignored or if this will require more changes.

**Comment by azat** [comment]
@widgetii can you take a look please?

**Comment by widgetii** [comment]
I'd fix that using as simple as possible way:

1) Replace `evutil_ascii_strcasecmp` by string find function to ensure that header value has `Upgrade` somewhere
or
2) Compare end of header value string with `Upgrade`

What do you think?

**Comment by azat** [comment]
>Replace evutil_ascii_strcasecmp by string find function to ensure that header value has Upgrade somewhere

I like this one

**Comment by chme** [comment]
Thanks a lot! I did a quick test and it works as expected.
