### ISSUE TITLE
Hard coding of unknown IP addresses（1.2.3.4 and 18.244.0.188）

### ISSUE THREAD

**Issue by yubin9** [libevent/libevent#1698]
Introduction
Hard coding of unknown IP addresses（1.2.3.4 and 18.244.0.188）

Details
18.244.0.188 - related code, for example
![image](https://github.com/user-attachments/assets/3fea5568-dfa3-4d1e-9244-4bd497a0d932)

1.2.3.4 - related code, for example
![image](https://github.com/user-attachments/assets/aea7f9a5-d79b-448d-b2bc-53cade461c5d)

Discussion points
What is the purpose of these two IP addresses? Whether data is uploaded to the preceding servers？

**Comment by azat** [comment]
1. has very decent comment that states that there will be no connection to this addresses, it is used to test some features

2. libevent is written in C there cannot be any `BOOST_TEST`, but we do have 1.2.3.4 here - https://github.com/libevent/libevent/blob/9848df54ccd819e3614667bbb97103ed701b0434/evutil.c#L1457-L1460, here the address is also not important, it is used only to detect features of `getaddrinfo`

P.S. Please post code snippets not screenshots.
