### ISSUE TITLE
Support 16KB page size devices 

### ISSUE THREAD

**Issue by jstewart5000** [libevent/libevent#1708]
#### Description:
In Android 15 [support for 16KB page sizes has been announced](https://developer.android.com/about/versions/15/behavior-changes-all#16-kb).

However,`libevent_core-2.1.so` / `libevent-2.1.so` / `libevent_extra-2.1.so` ELF segments are not aligned (`UNALIGNED (212)`) using 16 KB ELF alignment. This results in runtime crash when loading `libevent_core-2.1.so` / `libevent-2.1.so` / `libevent_extra-2.1.so` on emulator that is configured to use 16KB page size:
```
/tmp/my_apk_out/lib/arm64-v8a/libevent_core-2.1.so: UNALIGNED (212)
/tmp/my_apk_out/lib/arm64-v8a/libevent-2.1.so: UNALIGNED (212)
/tmp/my_apk_out/lib/arm64-v8a/libevent_extra-2.1.so: UNALIGNED (212)
```

#### How To Reproduce:

- This can also be verified by preparing and running `alignment.sh` script [as described in the documentation](https://developer.android.com/guide/practices/page-sizes#test).
- The solution is to compile `libevent_core-2.1.so` / `libevent-2.1.so` / `libevent_extra-2.1.so`  with 16KB ELF alignment as described [here](https://developer.android.com/guide/practices/page-sizes#compile-16-kb-alignment).

##### Environment
- Android Emulator 35.1.4
- Google APIs Experimental 16k Page Size arm64 System Image - API Level VanillaIceCream - Revision 1

**Comment by azat** [comment]
Hello.

Actually we do not provide artifacts for Android, so I guess you can simply compile with `cmake -DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,max-page-size=16384`

But let's see https://github.com/libevent/libevent/pull/1731

If CI will happy I'm OK with merging it.

**Comment by SunnyPaprika** [comment]
@azat This is highly architecture / system dependent. For instance, default ld/lld/gold value of this for ARM64 is 64K. I presume setting this to 16K for all ELF/*nix systems is going to break something somewhere?

**Comment by azat** [comment]
I don't think that 16k alignment will harm any system, @SunnyPaprika do you when it can be a problem?

To be honest I'm not sure that something should be done for this support on Android at all, since this alignment will be set automatically there...
