### ISSUE TITLE
Configure without SSL/TLS support in cmake

### ISSUE THREAD

**Issue by ahuj9** [libevent/libevent#1711]
https://github.com/libevent/libevent/blob/628f39bb908a032bc12ec5361723b1592022186e/cmake/LibeventConfig.cmake.in#L43

Is it possible to change to something like the following?

```cmake
if(DEFINED EVENT__HAVE_MBEDTLS)
    find_dependency(MbedTLS)
endif()
if(DEFINED EVENT__HAVE_OPENSSL)
    find_dependency(OpenSSL)
endif()
```

**Comment by azat** [comment]
Yes, sounds good - https://github.com/libevent/libevent/pull/1726
