### ISSUE TITLE
Experts, may I ask when the current open source libraries will undergo version iteration and upgrade？

### ISSUE THREAD

**Issue by LittleTimeCc** [libevent/libevent#1713]
Experts, may I ask when the current open source libraries will undergo version iteration and upgrade？

**Comment by azat** [comment]
Hello.

It is very sad, but I don't have enough time for libevent right now, and was hoping to make a release long time ago, but still hadn't made non-rc-alpha release yet... Hope will get back to it.

This is the main issue for tracking progress - https://github.com/libevent/libevent/issues/1512
