### ISSUE TITLE
Memory leaks when using the evhttp_set_cb and evhttp_set_gencb functions

### ISSUE THREAD

**Issue by alsestudio** [libevent/libevent#1738]
The other day, I was looking into why our application with an HTTP server has a memory leak. It was found that the function `evhttp_set_gencb` and `evhttp_set_cb` have a memory leak when calling the API method from 10 to 20 times.

The memory leak was checked using the command `cat /proc/{pid}/status` with the parameter `VmRSS`.  Interestingly, the amount of memory increased by 4 bytes (no more and no less) each time
```
VmRSS:      1248 kB
VmRSS:      1252 kB
VmRSS:      1256 kB
```

Has anyone encountered this problem?
If so, what solution can there be?

<br>

Basic server example
```
void process_request(struct evhttp_request *req, void *arg){
    struct evbuffer *buf = evbuffer_new();
    if (buf == NULL)
        return;

    evbuffer_add_printf(buf, "Requested: %s\n", evhttp_request_uri(req));
    evhttp_send_reply(req, HTTP_OK, "OK", buf);
}

int main () {
    struct event_base *base = event_init();
    if (base == NULL)
        return -1;

    struct evhttp *httpd = evhttp_new(base);
    if (httpd == NULL)
        return -1;

    if (evhttp_bind_socket(httpd, "0.0.0.0", 8080) != 0)
        return -1;

    evhttp_set_cb(httpd, "/test", process_request, NULL);
    
    event_base_dispatch(base);
    return 0;
}
```

**Comment by widgetii** [comment]
You should call `evbuffer_free(buf)` when you don't need the buffer anymore. Check examples in Libevent book

**Comment by alsestudio** [comment]
Теперь я еще раз перепроверил пример, и, похоже, в нем нет утечки памяти... Я пошел еще раз проверить наш код. Спасибо
