### ISSUE TITLE
found a bug,but uncertain

### ISSUE THREAD

**Issue by boycuijg** [libevent/libevent#1741]
event.c   line: 1926
int
event_base_loop(struct event_base *base, int flags)
{
&nbsp;&nbsp;&nbsp; struct timeval tv;    &nbsp;&nbsp; **=> &nbsp;&nbsp; struct timeval tv = {}; because the default value is not 0** 
&nbsp;&nbsp;&nbsp; .....
}

**Comment by azat** [comment]
Thank you.
Everything is OK there, but this will make it cleaner - https://github.com/libevent/libevent/pull/1745
