### ISSUE TITLE
I wrote a http server startup and shutdown, I wonder if it is correct?

### ISSUE THREAD

**Issue by boycuijg** [libevent/libevent#1742]
**To prevent blocking and exiting, a EV_PERSIST timer event is added；**

```
    void HttpServer::Start() {
        if (!m_running) {
            m_running = true;

            m_evhttp = evhttp_new(m_evbase);
            evhttp_set_gencb(m_evhttp, svr_default_request_cb, this);
            evhttp_bind_socket(m_evhttp,m_listen_addr.ip.c_str(), m_listen_addr.port);

            m_evtimer = event_new(m_evbase, -1, EV_PERSIST,
                                  [](evutil_socket_t fd, short event, void *arg) {}, nullptr);
            timeval tv = {};
            evutil_timerclear(&tv);
            tv.tv_sec = 0;
            tv.tv_usec = 1000;
            event_add(m_evtimer, &tv);

            m_th_svr = new std::thread([this](){
                event_base_dispatch(m_evbase);
            });
        }
    }

    void HttpServer::Stop() {
        if (m_running) {
            m_running = false;

            event_free(m_evtimer);
            evhttp_free(m_evhttp);
            event_base_loopbreak(m_evbase);

            if (m_th_svr != nullptr && m_th_svr->joinable()) {
                m_th_svr->join();
            }
            delete m_th_svr;
            m_th_svr = nullptr;
        }
    }
```

**Comment by azat** [comment]
Hello.

You don't need timer, since event base will contain one event already - listener.

Also note that evhttp layer does not supports handling events from different threads, you can create evhttp/event_base in a separate thread, but all events should be handled there.

**Comment by boycuijg** [comment]
> Hello.
> 
> You don't need timer, since event base will contain one event already - listener.
> 
> Also note that evhttp layer does not supports handling events from different threads, you can create evhttp/event_base in a separate thread, but all events should be handled there.

**I want to be able to exit the loop at any time**
1. if I use event_base_dispatch(m_evbase)，it will block indefinitely in the kevent function (kqueue.c line:315), and I can't exit the  event loop using event_base_loopbreak(m_evbase) 
2. Using event_base_loop(m_evbase, EVLOOP_NONBLOCK) will not block, but I need to create my own loop:
```
while (true) {
  event_base_loop(m_evbase, EVLOOP_NONBLOCK);
  std::this_thread::sleep_for(...);
}
```

**Comment by azat** [comment]
Apparently you are calling `event_base_loopbreak` from another thread, you need to enable threading support for notifying base from another thread - `evthread_use_pthreads`
