### ISSUE TITLE
unable to listen to windows console standard input events

### ISSUE THREAD

**Issue by ac169** [libevent/libevent#1743]
```
...
    #define STDIN_FILENO 0
...
    struct event_base *base = event_base_new();
    struct bufferevent *bev = bufferevent_socket_new(base, sockfd, BEV_OPT_CLOSE_ON_FREE);

    struct event *event_input = event_new(base, STDIN_FILENO, EV_READ | EV_PERSIST, input_cb, (void *) bev);

    event_add(event_input, NULL);

    bufferevent_setcb(bev, read_cb, NULL, error_cb, (void *) event_input);
    bufferevent_enable(bev, EV_READ | EV_PERSIST);

    event_base_dispatch(base);
...
```
the above code compiles and runs normally on Linux, but it ends directly after compilation on Windows, and there is no process of waiting for input on the terminal.

**Comment by azat** [comment]
This is a windows problem - https://stackoverflow.com/questions/23222202/using-select-with-stdin-on-windows

Though there are some possible options - https://www.reddit.com/r/cprogramming/comments/lixmuu/nonblocking_check_if_stdin_readyhas_input_with/?rdt=34778

But libevent does not support them.

**Comment by ac169** [comment]
> This is a windows problem - https://stackoverflow.com/questions/23222202/using-select-with-stdin-on-windows
> 
> Though there are some possible options - https://www.reddit.com/r/cprogramming/comments/lixmuu/nonblocking_check_if_stdin_readyhas_input_with/?rdt=34778
> 
> But libevent does not support them.

The reason is actually known. I want to try my best to be unified as a third-party library for cross-platform positioning, or to have a special summary and explanation of the differences!
