### ISSUE TITLE
http.h line636 lose EVENT2_EXPORT_SYMBOL

### ISSUE THREAD

**Issue by CruiseYoung** [libevent/libevent#176]
http.h line636 lose EVENT2_EXPORT_SYMBOL

/**
 * Set family hint for DNS requests.
 */
void evhttp_connection_set_family(struct evhttp_connection *evcon,
	int family);

**Comment by ellzey** [comment]
Can you be a little more verbose about the problem?

**Comment by azat** [comment]
I guess that this is just this -- https://github.com/azat/libevent/commit/1520453edbb3b9edea9625fab99fce2c778b92b6.patch

**Comment by CruiseYoung** [comment]
see file regress_http.c line980 

Dynamic Link Library

**Comment by CruiseYoung** [comment]
same  [win32] unit tests for http fail · Issue #243 · libevent/libevent
https://github.com/libevent/libevent/issues/243

**Comment by ellzey** [comment]
yeah I'm on top of #243 (I wrote up the issue). 

will export the symbol mentioned here in a bit.
