### ISSUE TITLE
option "EVENTBUILD_SHARED_LIBRARIES" compilation bug

### ISSUE THREAD

**Issue by CruiseYoung** [libevent/libevent#177]
option(EVENT__BUILD_SHARED_LIBRARIES "Define if libevent should be built with shared libraries instead of archives" ON)
option(EVENT__DISABLE_TESTS "If tests should be compiled or not" OFF) option(EVENT__DISABLE_REGRESS "Disable the regress tests" OFF) option(EVENT__DISABLE_SAMPLES "Disable sample files" OFF)

test compilation:
26>------ Build started: Project: test-ratelim, Configuration: Release x64 ------
26>  Building Custom Rule E:/Projects/compile/libevent-master/CMakeLists.txt
26>  CMake does not need to re-run because E:\Projects\compile\libevent-master\bld_release_x64_cmake\CMakeFiles\generate.stamp is up-to-date.
26>  test-ratelim.c
26>..\test\test-ratelim.c(424): warning C4244: 'initializing' : conversion from 'uint64_t' to 'double', possible loss of data
26>..\test\test-ratelim.c(583): warning C4244: '*=' : conversion from 'double' to 'int', possible loss of data
26>..\test\test-ratelim.c(584): warning C4244: '*=' : conversion from 'double' to 'int', possible loss of data
26>test-ratelim.obj : error LNK2019: unresolved external symbol evutil_weakrand_seed_ referenced in function main
26>test-ratelim.obj : error LNK2019: unresolved external symbol evutil_weakrand_ referenced in function loud_writecb
26>E:\Projects\compile\libevent-master\bld_release_x64_cmake\bin\Release\test-ratelim.exe : fatal error LNK1120: 2 unresolved externals

27>------ Build started: Project: test-time, Configuration: Release x64 ------
27>  Building Custom Rule E:/Projects/compile/libevent-master/CMakeLists.txt
27>  CMake does not need to re-run because E:\Projects\compile\libevent-master\bld_release_x64_cmake\CMakeFiles\generate.stamp is up-to-date.
27>  test-time.c
27>test-time.obj : error LNK2019: unresolved external symbol evutil_weakrand_seed_ referenced in function main
27>test-time.obj : error LNK2019: unresolved external symbol evutil_weakrand_ referenced in function main
27>E:\Projects\compile\libevent-master\bld_release_x64_cmake\bin\Release\test-time.exe : fatal error LNK1120: 2 unresolved externals

In the test compile the same problems exist in the following 3 files：
test-dumpevents.c
test-ratelim.c
test-time.c

The same situation also appears in regress compilation of the following documents:
regress.c
regress_buffer.c
regress_bufferevent.c
regress_et.c
regress_finalize.c
regress_http.c
regress_iocp.c
regress_listener.c
regress_main.c
regress_minheap.c
regress_thread.c
regress_util.c

**Comment by azat** [comment]
Hi @CruiseYoung

Can you check again (after pulling changes from upstream)?
I think that #314 must fix the issue.

Thanks,
Azat.

**Comment by azat** [comment]
@CruiseYoung Closing this one for now, if it still fails with latest (from git) version, please reopen
