### ISSUE TITLE
port should use uint16_t instead of unsigned short

### ISSUE THREAD

**Issue by pphaneuf** [libevent/libevent#178]
@benlaurie pointed this out to me:

https://codereview.appspot.com/156040043/#msg4

According to him, it should be uint16_t, and I would tend to agree, after having looked up the sockaddr_in on Linux and Mac OS X.

**Comment by miniupnp** [comment]
I think on all platforms where libevent2 compiles short are 16bits
so commit f5b67119613ce9687e73477c39a3289fdb5201b4 should be safe...

**Comment by ellzey** [comment]
+1 on this.

@nmathewson ?

**Comment by azat** [comment]
I'm going to rebase mentioned patch a little bit and merge it, since that `unsigned short -> ev_uint16_t` is already started in 6bf1ca78.
