### ISSUE TITLE
[HURRY] libevent got DEAD LOOP

### ISSUE THREAD

**Issue by badnoodle** [libevent/libevent#181]
when i use libevent in my application, i got a read event in a tcp connection, and in the event callback named CB i got socket error, so i want to close and destroy some resource such as remove read event and write event in event set, all of these are in CB, so when i call event_del to remove read event I found the app got into DEAD LOOP and the CPU usage is high.
I don't know why ? can some one can explain ?

**Comment by GeekCome** [comment]
I also got this problem,but I can not find what the error is.
In the program I used bufferevent to manage the event and data buffer.But in some case,it got a dead loop. I have not find the case to cause this problem.

Through strace and gdb I found epoll_wait returns a active event,but in libevent evmap the event_list is null,but the var nread=1. So it goes into a dead loop and cpu 100% loop.
Sometimes the epoll_wait has no active event but the libevent N_ACTIVE_CALLBACKS(base) returns it has a active event, so call the epoll_wait with timeout 0, then is goes into a dead loop too.

**Comment by nmathewson** [comment]
Have you tried running your program under valgrind, or with libevent's debugging mode turned on?

**Comment by GeekCome** [comment]
the valgrind check ok and the strace output as follows:

futex(0x6d57c0, FUTEX_WAKE, 1) = 1
epoll_ctl(10, EPOLL_CTL_MOD, 368, {EPOLLIN|EPOLLOUT, {u32=368, u64=368}}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}, {EPOLLOUT, {u32=368, u64=368}}}, 32, 989) = 2
clock_gettime(CLOCK_MONOTONIC, {9670484, 296463066}) = 0
writev(368, [{"\0\0\0\0\5\\360\26route\0\0\0\0\0\0\0\0\0\0\0\224\223"..., 173}], 1) = 173
epoll_ctl(10, EPOLL_CTL_MOD, 368, {EPOLLIN, {u32=368, u64=368}}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 986) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 297741800}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 985) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 298371750}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 984) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 298965814}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 983) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 299660077}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 983) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 300400392}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 982) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 301029189}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 981) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 301556771}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 981) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 302130445}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 980) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 302659287}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 980) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 303326556}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 979) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 303965529}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 978) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 304634925}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 978) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 305284220}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 977) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 305812017}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 977) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 306455827}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 976) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 306960246}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 975) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 307515717}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32

The libevent got a event from epoll_wait, but in the `evmap_io_active(base, events[i].data.fd, ev | EV_ET);` the tail was null `TAILQ_FOREACH(ev, &ctx->events, ev_io_next)`

**Comment by GeekCome** [comment]
ps: the ev_base is owned by only one thread.

**Comment by azat** [comment]
Which tool do you use while checking under valgrind?

**Comment by ellzey** [comment]
@YongMan so you are saying it's easy to reproduce, something like:

1. Make a bunch of connections and do IO
2. Randomly disconnect the network, wait for a few of the clients to start timing out / failing
3. Reconnect the network
4. :pray: for this condition

?

**Comment by ellzey** [comment]
bump @YongMan

**Comment by YongMan** [comment]
@ellzey Sorry about the delay. We use libevent version 2.0.19.
The condition happend in production env. This is a little probabilty event to happen, and especially in network shake. We use libevent to manage connections to upstream and downstream. And we use hiredis (hiredis 0.10.1, now we use version 0.12.1) to connect downstream redis server, which always have this problem in bad network conditon. After updating the hiredis and libevent to latest stable version, the problem dose not happend agian in the connection to downstream. But the problem still happen in the connection with upstream, in which the thread just be responsiable for accept new connetions(this evbase used only in this thread).
P.S. Accroding the changelog of hiredis, I can see one log `Remove possiblity of multiple close on same fd`, this can triger the libevent bug? The problem still confusing me, just in a lower rating.

**Comment by YongMan** [comment]
@ellzey We used to try to replay the bug in dev env,  simulating the network shake and sending request to stress. But we can not replay in dev env. 

In my view, this is a libevent bug. Because in the evmap_io structure,`the events list is null but nread and nwrite is not 0`, evmap_io just not in a consistent state.

**Comment by ellzey** [comment]
Nick asks: [Is this a multithreaded application?](https://github.com/libevent/libevent/issues/181#issuecomment-59926360)
You respond: [no](https://github.com/libevent/libevent/issues/181#issuecomment-60023742)

Then you mention [there are threads involved](https://github.com/libevent/libevent/issues/181#issuecomment-102266137)

>  But the problem still happen in the connection with upstream, in which the thread just be responsiable for accept new connetions(this evbase used only in this thread).

I'm confused, so there is absolutely ZERO network activity in other threads?

**Comment by YongMan** [comment]
This is a multithreaded application, every thread has its owe eventbase.
when one eventbase have the cpu deadloop, other thread works well.
And this thread can also handle the event happened in it, just own one event can not handle and be left in the evbase forever.

**Comment by ellzey** [comment]
Do you have some code I can reproduce this with?

**Comment by ellzey** [comment]
no response since 2015, closing.

**Comment by Johnnyloong** [comment]
Have you solved this bug now? my program  got this problem like you do

**Comment by azat** [comment]
@Johnnyloong 

- what version do you have?
- is you program multi threaded? if so, did you enable pthread (or win32 threads) support for libevent?
- did you tried to run libevent with `event_enable_debug_mode()` (but first check that it is not compiled out in you version) ?
- did you tried to run under valgrind?
- can you provide simple reproducer? is it easy to reproduce?

**Comment by zidian666** [comment]
Resolved.
I have been trouble in this problem for two days.
When my program was in pressure test, it always loop in evmap_io_active() with cpu 100% usage or SIGSEGV here.
Then I run program with event_enable_debug_mode() and event_enable_debug_logging(), the log shows that I should use evthread_use_pthreads() before everything.
I did so.
And the problem no longer exists.
