### ISSUE TITLE
evdns round-robins nameservers

### ISSUE THREAD

**Issue by AngerM** [libevent/libevent#185]
Nameservers are generally configured in as a priority based list. The first name server should always be used unless it is 'down' after which secondary nameservers should be used. Libevent always round-robins nameservers and this is incorrect behavior.
See: 
http://technet.microsoft.com/en-us/library/cc754152.aspx
```
Listed alternate DNS servers are contacted and used when the preferred server is not available. For this reason, it is important that the preferred DNS server be appropriate for continuous client use under normal conditions.
```

http://manpages.ubuntu.com/manpages/jaunty/man5/resolv.conf.5.html
```
              If there are multiple servers, the resolver library queries them in
              the order listed.  If no nameserver  entries  are  present,  the
              default  is  to  use the name server on the local machine.  (The
              algorithm used is to try a name server, and if the  query  times
              out, try the next, until out of name servers, then repeat trying
              all the name servers until  a  maximum  number  of  retries  are
              made.)
```
I have created a pull to fix this:
https://github.com/libevent/libevent/pull/184

**Comment by azat** [comment]
Closed, since we have #184
