### ISSUE TITLE
can't complie

### ISSUE THREAD

**Issue by CNMan** [libevent/libevent#199]
mingw32 on windows server 2012 r2

Administrator@WIN-QS24SR833AQ ~/libevent-2.0.21-stable
$ make
test -d include/event2 || /bin/mkdir -p include/event2
/bin/sed -f ./make-event-config.sed < config.h > include/event2/event-config.hT
mv -f include/event2/event-config.hT include/event2/event-config.h
make  all-recursive
make[1]: Entering directory `/home/Administrator/libevent-2.0.21-stable'
Making all in .
make[2]: Entering directory `/home/Administrator/libevent-2.0.21-stable'
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I./compat
-I./include -I./include    -g -O2 -Wall -fno-strict-aliasing  -MT event.lo -MD -
MP -MF .deps/event.Tpo -c -o event.lo event.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./compat -I./include -I./include -g
 -O2 -Wall -fno-strict-aliasing -MT event.lo -MD -MP -MF .deps/event.Tpo -c even
t.c -o event.o
In file included from minheap-internal.h:35,
                 from event-internal.h:38,
                 from event.c:60:
util-internal.h:222: error: field `ss_sin' has incomplete type
util-internal.h:223: error: field `ss_sin6' has incomplete type
make[2]: *** [event.lo] Error 1
make[2]: Leaving directory `/home/Administrator/libevent-2.0.21-stable'
make[1]: *** [all-recursive] Error 1

      *** [all] Error 2
                              ~/libevent-2.0.21-stable

**Comment by nmathewson** [comment]
Does including "include winsock2.h" earlier near the start of util.h fix this for you?

**Comment by ellzey** [comment]
@CNMan bump, ping?

**Comment by ellzey** [comment]
Closing due to no response
