### ISSUE TITLE
bufferevent_incref/decref

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#202]
A feature request; it would be handy if bufferevent_incref/decref were exported. When passing bufferevents around (particularly when threading) the user often has to implement reference counting. However, bufferevents already have nice reference counting, it's just not available to call.

Is there any reason not to export incref/decref?

**Comment by nmathewson** [comment]
Seems reasonable to me; I'd take a patch for this.

**Comment by ellzey** [comment]
Fully understanding the needs for this when working with @ghazel, I will be plopping the patches in tonight.
