### ISSUE TITLE
question with evhttp_make_request error handling

### ISSUE THREAD

**Issue by pphaneuf** [libevent/libevent#216]
With the stable (2.0) version, when a number of things go wrong with an HTTP connection, the callback gets called with a NULL. For most errors, that's okay, but the timeout case annoys me a little bit... Specifically, if there's a timeout while waiting for this specific request, that would be an interesting thing to know about! I'm hiding libevent's HTTP client a bit, to provide a slightly higher level API (follow redirects, retry low-level errors, etc), so what matters to me is whether my wrapper should retry the request or not. If it's some random problem with the connection, I would retry, but I feel that a timeout with the request itself would be good to report back?

Is that possible, in some way that I might have missed? Thanks in advance!

**Comment by pphaneuf** [comment]
Notably, getting the request callback called with a NULL works rather badly when combined with ```evhttp_request_own```! At the moment, it sorts of "work", because the request gets freed anyway: :wink: 

https://github.com/libevent/libevent/blob/patches-2.0/http.c#L737

**Comment by JohnOhl** [comment]
I've had the same conundrum with figuring out how to detect a timeout vs other errors. If you look at the https-client.c sample; it helps discover SSL errors and general socket errors.

I've sort of been using a similar setup to check for SSL errors, followed by socket errors and assuming that if there are no OpenSSL errors and `errno` is 0, it means we had a timeout. Although this may be catching some edge cases incorrectly.

If you don't mind, I can play around with it a bit and see if I can come up /w an idea or PR that would give some more insight into these types of errors (don't want to step on your toes if you're already working on a PR). I think others besides us may find it useful ;-)

**Comment by pphaneuf** [comment]
I wasn't going to do anything about this particular issue, especially as this would require changing the interface somewhat (returning non-NULL where it returns NULL at the moment?), just asking for ideas to see if there's some way to work around this problem.

I'll take a look at the ```https-client.c``` sample, thanks!

**Comment by JohnOhl** [comment]
I was poking around for a solution and found @azat has already added an interface for detecting connection failures and their reasons in https://github.com/libevent/libevent/commit/7b077194cc8fd38808e3f210fc090aedb5df25d5 it's in there already as part of the 2.1.3 releases.

For older versions it looks like we're stuck with checking that the request parameter is NULL and looking at errno to detect a timeout.

**Comment by azat** [comment]
@pphaneuf do you need this functionality for *2.0*?

**Comment by pphaneuf** [comment]
We've switched the HTTP client we use in our project (http://github.com/google/certificate-transparency) to libevhtp (which uses libevent, and we're still using the HTTP server from libevent at the moment), so we do not need this specifically in any version.

We *would* like to reduce our dependencies, but it looks like future versions of libevent might include libevhtp? So we should be okay in the longer term as well.

**Comment by azat** [comment]
Hm, I don't want to dissuade you from using libevhtp as http client, but libevent http layer have this feature via `error_cb` in *2.1*, I guess that this is not a problem for you to use *2.1* instead of *2.0*?

**Comment by pphaneuf** [comment]
We're trying to work with versions of libevent already packaged by distributions. Since we're now needing libevhtp (which is not packaged on a number of popular distributions), we considered biting the bullet and requiring 2.1, but some were scared off by the "alpha". :wink:

**Comment by azat** [comment]
**2.1** shouldn't be something *scary*, since right now 99.9% of patches are bugfixes.

**Comment by azat** [comment]
If you will need this in **2.0**, please reopen.
