### ISSUE TITLE
event-config.h and CMakeLists.txt don't agree on same version string

### ISSUE THREAD

**Issue by NewEraCracker** [libevent/libevent#227]
See: 683f5568ab0ce47b0492aa75dd3015e72f130f81

In CMakeLists.txt
```
set(EVENT_VERSION "${EVENT_VERSION_MAJOR}.${EVENT_VERSION_MINOR}.${EVENT_VERSION_PATCH}-alpha${EVENT_VERSION_DEVTAG}")
```

In event-config.h
```
#define EVENT__VERSION "2.1.5-beta"
```

As you can see, the version string is no longer an alpha one.

This causes a minor issue in a 3rdparty project that relies on libevent, where the two version strings are compared (header and lib) and a notice is emitted if they differ.

Regards,
NewEraCracker

**Comment by azat** [comment]
I guess that, you can feel free to send a patch for this.

But which is more important is that for new releases you need to change version string in *so many places* (see mentioned commit).
Why we couldn't teach `cmake` to generate needable const in header? This will be a good choice (IMHO, and also could append git commit there for alpha/beta/rc, but not for release), however we also have `autoconf`, could we get rid of this build system entirely (even if we need to fix some issues, we could do this for cmake, and then drop `autoconf`) ? @nmathewson ?

**Comment by NewEraCracker** [comment]
removing `-alpha` from line 39 at CMakeLists.txt should do the trick.

**Comment by ellzey** [comment]
There are a lot of odd things that don't match up with the autotools variant, I intend on fixing this. The CMake version is not compatible with older code (i.e., it doesn't generate bufferevent_ssl, etc. Which is a bit of a letdown.

**Comment by ellzey** [comment]
OK, check out https://github.com/libevent/libevent/compare/master...ellzey:cmake_updates

more specifically the parts that mention `EVENT__STAGE_VERSION`

```diff
+# only a subset of names can be used, defaults to "beta"
+set(EVENT__STAGE_VERSION "beta"
+	CACHE STRING "set EVENT_STAGE_VERSION")
+
+# a list that defines what can set for EVENT_STAGE_VERSION
+set(EVENT__ALLOWED_STAGE_NAMES
+	beta
+	alpha
+	rc
+	release)
+
+# attempt to find the EVENT__STAGE_VERSION in the allowed list
+# of accepted stage names, the return value is stord in
+# EVENT__STAGE_RET
+list(FIND
+	EVENT__ALLOWED_STAGE_NAMES
+	${EVENT__STAGE_VERSION}
+	EVENT__STAGE_RET)
+
+# if EVENT__STAGE_RET is -1, the name was not
+# found, so we fall back to "beta".
+set(EVENT_STAGE_VERSION "beta")
+
+if (EVENT__STAGE_RET EQUAL "-1")
+	message(WARNING "${EVENT__STAGE_VERSION} invalid, defaulting to ${EVENT_STAGE_VERSION}")
+else()
+	set(EVENT_STAGE_VERSION ${EVENT__STAGE_VERSION})
+endif()
+
+set(EVENT_VERSION "${EVENT_VERSION_MAJOR}.${EVENT_VERSION_MINOR}.${EVENT_VERSION_PATCH}-${EVENT_STAGE_VERSION}")
```

That *should* clear things up, as long as we set the proper flag "-DVENT__STAGE_VERSION:STRING", which for now will default to "beta".

**Comment by ellzey** [comment]
reef https://github.com/libevent/libevent/pull/300
