### ISSUE TITLE
event_deferred_cb_schedule_ comment doesn't match implementation

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#229]
The comment for `event_deferred_cb_schedule_` says:

```
Activate a struct event_callback if it is not currently scheduled in an event_base.

Return true iff it was not previously scheduled.
```

However, the implementation seems to be a little different:

```c
#define MAX_DEFERREDS_QUEUED 32
int
event_deferred_cb_schedule_(struct event_base *base, struct event_callback *cb)
{
	int r = 1;
	if (!base)
		base = current_base;
	EVBASE_ACQUIRE_LOCK(base, th_base_lock);
	if (base->n_deferreds_queued > MAX_DEFERREDS_QUEUED) {
		event_callback_activate_later_nolock_(base, cb);
	} else {
		++base->n_deferreds_queued;
		r = event_callback_activate_nolock_(base, cb);
	}
	EVBASE_RELEASE_LOCK(base, th_base_lock);
	return r;
}
```

Notice that `if (base->n_deferreds_queued > MAX_DEFERREDS_QUEUED)`, the return value is 1, regardless of whether it was previously scheduled. In the other case, `n_deferreds_queued` is increased even if the callback was previously scheduled, which seems wrong.

Found while debugging #228, and may be related.

**Comment by nmathewson** [comment]
Yes, that does look incorrect.  Think you can write a patch for this?

**Comment by nmathewson** [comment]
Ah, never mind, I see you did!  (Pull request #119 over on another repository)

**Comment by azat** [comment]
I also have a patch for this -- #208 -- https://github.com/azat/libevent/commit/a5c1f9fde92795bdf6763b96a0a69efeca82dae1

But it fixes more than just `event_deferred_cb_schedule_`
