### ISSUE TITLE
[Hurry] Libevent evmap different with epoll cause a dead loop, CPU 100%

### ISSUE THREAD

**Issue by YongMan** [libevent/libevent#230]
I also got this problem,but I can not find what the error is.
In the program I used bufferevent to manage the event and data buffer.But in some case,it got a dead loop. I have not found out the case to cause this problem.

Through strace and gdb I found `epoll_wait` returns a active event,but in libevent evmap the event_list is null,but the var `nread=1`. So it goes into a dead loop and cpu 100% loop.
Sometimes the `epoll_wait` has no active event but the libevent `N_ACTIVE_CALLBACKS(base)` returns it has a active event, so call the epoll_wait with timeout 0, then is goes into a dead loop too.

**Comment by GeekCome** [comment]
the strace output as follows:
`
futex(0x6d57c0, FUTEX_WAKE, 1)          = 1
epoll_ctl(10, EPOLL_CTL_MOD, 368, {EPOLLIN|EPOLLOUT, {u32=368, u64=368}}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}, {EPOLLOUT, {u32=368, u64=368}}}, 32, 989) = 2
clock_gettime(CLOCK_MONOTONIC, {9670484, 296463066}) = 0
writev(368, [{"\0\0\0\0\5\\\360\26route\0\0\0\0\0\0\0\0\0\0\0\224\223"..., 173}], 1) = 173
epoll_ctl(10, EPOLL_CTL_MOD, 368, {EPOLLIN, {u32=368, u64=368}}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 986) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 297741800}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 985) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 298371750}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 984) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 298965814}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 983) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 299660077}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 983) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 300400392}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 982) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 301029189}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 981) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 301556771}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 981) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 302130445}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 980) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 302659287}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 980) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 303326556}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 979) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 303965529}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 978) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 304634925}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 978) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 305284220}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 977) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 305812017}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 977) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 306455827}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 976) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 306960246}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32, 975) = 1
clock_gettime(CLOCK_MONOTONIC, {9670484, 307515717}) = 0
epoll_wait(10, {{EPOLLIN|EPOLLOUT, {u32=814, u64=814}}}, 32
`

**Comment by GeekCome** [comment]
The debug screenshot as follows:（The event_list is null and the nread=1 nwrite=1. How did this happened?）
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/3875656/6864316/83600a3a-d49a-11e4-9991-21e16cb17c73.png)

**Comment by ellzey** [comment]
Sorry for the delay. Do you happen to have some code to reproduce this issue?

**Comment by YongMan** [comment]
I make the reply in issue https://github.com/libevent/libevent/issues/181

**Comment by ellzey** [comment]
I don't know why you're switching in and out of this issue to another issue,but whatever, I'll close this one, and continue in #181

**Comment by YongMan** [comment]
ok
