### ISSUE TITLE
Broken archive link for packaging

### ISSUE THREAD

**Issue by Socolin** [libevent/libevent#231]
The link for 2.0.22 is not working on github download

Working: 
~~~
https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz
~~~
Not working: 
~~~
https://github.com/downloads/libevent/libevent/libevent-2.0.22-stable.tar.gz
~~~

Can you add this ?

**Comment by ellzey** [comment]
You may have caught github at the wrong time (still packaging, it's an auto-github thing). When in doubt get your links from https://github.com/libevent/libevent/releases

**Comment by ramestica** [comment]
from where can I grab your public gpg key to verify downloads from links like those shown above?

**Comment by azat** [comment]
On public GPG key server, `gpg --verify /path/to/.asc`/`gpg --list-packets` will show you the key with which the file is signed.

For example this particular (2.0.22) is signed with [this](https://pgp.key-server.io/search/0x910397D88D29319A) key.
