### ISSUE TITLE
http + filter isn't working as expected (release-2.1.5-beta)

### ISSUE THREAD

**Issue by LudwigOrtmann** [libevent/libevent#237]
On https://github.com/libevent/libevent/tree/release-2.1.5-beta, I am trying to use `evhttp_set_bevcb` to set up a bufferevent filter.
Doing so results in the filter callbacks not being called.
The http callbacks are not being called either - events just get stuck/disappear somewhere.
When not inserting the filter (i.e. just returning a plain socket bufferevent), `evhttp_set_bevcb` appears to work however.

Code: https://gist.github.com/LudwigOrtmann/ff255b1dcbfe53bbc934

**Comment by ellzey** [comment]
Thanks for pointing this out. This is a neat edge-case. When you setup the filter, the bufferevent control callback becomes `be_filter_ctrl`, which without filtering is `be_socket_ctrl`. The difference is: be_socket_ctrl assigns all the proper read and write events on the fd. `be_filter_ctrl` does nothing.

@nmathewson does this logic make sense to you for bufferevent_filter:

```C
diff --git a/bufferevent_filter.c b/bufferevent_filter.c
index 4d9be43..a072f38 100644
--- a/bufferevent_filter.c
+++ b/bufferevent_filter.c
@@ -536,10 +536,15 @@ be_filter_ctrl(struct bufferevent *bev, enum bufferevent_ctrl_op op,
                bevf = upcast(bev);
                data->ptr = bevf->underlying;
                return 0;
-       case BEV_CTRL_GET_FD:
        case BEV_CTRL_SET_FD:
+               bevf = upcast(bev);
+
+               return bevf->underlying->be_ops->ctrl(bevf->underlying, op, data);
+       case BEV_CTRL_GET_FD:
        case BEV_CTRL_CANCEL_ALL:
        default:
                return -1;
        }
```

May want to do the same for GET_FD too.

**Comment by LudwigOrtmann** [comment]
@ellzey Thank you for the quick response!
An initial test worked well on my side too.

**Comment by LudwigOrtmann** [comment]
Hm, there's more problems:
Data doesn't make it through to the `output_filter` while the `input_filter` works fine. It's the same when setting the `output_filter` to `NULL`.
Also: `NULL` as an `input_filter` does not work, i.e. no data passes through.

**Comment by LudwigOrtmann** [comment]
I pushed the changes (payload in reply, `evbuffer_remove_buffer`) to the gist.

**Comment by ellzey** [comment]
Getting on a plane right now, will debug during my 7 hour flight. Thanks for waiting.

**Comment by LudwigOrtmann** [comment]
Heh, have a good flight =)

**Comment by ellzey** [comment]
Can you try out the latest master branch for the fix? (works for me). remember you need to `evbuffer_remove_buffer(src, dst, evbuffer_get_length(src));`  for both of your in and out filters to avoid an infinite loop.

**Comment by LudwigOrtmann** [comment]
I'm on it.

**Comment by LudwigOrtmann** [comment]
Now, the [test code](https://gist.github.com/LudwigOrtmann/ff255b1dcbfe53bbc934) does not crash anymore but still does not work.

When opening a connection, libevent hangs, apparently waiting for a socket to become ready:
```
)                 = 7
write(1, "filter activated\n", 17filter activated
)      = 17
accept4(6, 0x7fff3891c880, [128], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(3, 
```

BTW:
The same (waiting for socket to become ready) also happens with my own libevent based http + filter implementation which worked with the pre-patch version of libevent.

**Comment by LudwigOrtmann** [comment]
This is a pre-patch strace of the relevant passage in my own implementation:
```
{{EPOLLIN, {u32=7, u64=7}}}, 32, -1) = 1
accept4(7, {sa_family=AF_INET6, sin6_port=htons(34614), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28], SOCK_NONBLOCK) = 14
write(1, "bev_cb\n", 7bev_cb
)                 = 7
write(1, "created bev: 0x161cfb0\n", 23created bev: 0x161cfb0
) = 23
write(1, "created fbev: 0x161f6b0\n", 24created fbev: 0x161f6b0
) = 24
epoll_ctl(3, EPOLL_CTL_ADD, 14, {EPOLLOUT, {u32=14, u64=14}}) = 0
epoll_ctl(3, EPOLL_CTL_MOD, 14, {EPOLLIN|EPOLLOUT, {u32=14, u64=14}}) = 0
accept4(7, 0x7fffa1d2dfc0, [128], SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(3, {{EPOLLIN|EPOLLOUT, {u32=14, u64=14}}}, 32, -1) = 1
ioctl(14, FIONREAD, [83])               = 0
readv(14, [{"GET /fooo HTTP/1.1\r\nHost: local"..., 83}], 1) = 83
```

**Comment by LudwigOrtmann** [comment]
Ah, I was confused, sorry, I did not test the master branch but the release tag...

**Comment by LudwigOrtmann** [comment]
On master my test as well as my own http implementation are working.

**Comment by LudwigOrtmann** [comment]
OK, from my point of view the bug is fixed.
The release tagged version still contains it, so I'm not clicking the "close" button...

Thank you for tending to this issue!

**Comment by ellzey** [comment]
I'm closing this issue since it's technically fixed; just have to wait for next release (I dislike having fixed things in the issues queue). I will notify you for next beta..
