### ISSUE TITLE
Refactor cmake

### ISSUE THREAD

**Issue by ellzey** [libevent/libevent#246]
It is pretty apparent that the conversion to cmake from the autotools was not 100% successful. 

There are many problems, the biggest one being the fact that the output from using `./configure && make; make verify` does not equal the output of `mkdir build; cd build; cmake .. ; cmake --build .; ctest`

I _personally_ find cmake as the future building foundation for the product, but for right now it needs a heavy review and refactor. (More to come)

**Comment by azat** [comment]
@ellzey do you want this for **2.1**?

**Comment by azat** [comment]
Closing this one, since some differences already eliminated and anyway there are no details here what differs.
