### ISSUE TITLE
[win32] IOCP on bench_http has broken down

### ISSUE THREAD

**Issue by zeliard** [libevent/libevent#255]
bench_http.c works well by using select() multiplexer on Windows.
But, when running with IOCP mode (-i option), it does not work.

When I checked what the problem was, 
I found that there were no issuing WSARecv() calls when new connections accepted.

**Comment by azat** [comment]
Hi @zeliard 

Should be fixed by 3d815cf22074792f31274fd6d810a94984661dbf.
Can you please verify and reopen if you still see the problem?
