### ISSUE TITLE
memory leaks in evconnlistener_new_bind with IOCP enabled

### ISSUE THREAD

**Issue by tim-le** [libevent/libevent#257]
Detected memory leaks!
Dumping objects ->
{2311} normal block at 0x00A5A0A8, 155 bytes long.
 Data: <` &             > 60 8D 26 00 FF FF FF FF 00 00 00 00 00 00 00 00 
{2310} normal block at 0x00A59FD0, 155 bytes long.
 Data: < I&             > 18 49 26 00 FF FF FF FF 00 00 00 00 00 00 00 00 
{2309} normal block at 0x00A60E68, 155 bytes long.
 Data: < x&             > C8 78 26 00 FF FF FF FF 00 00 00 00 00 00 00 00 
{2308} normal block at 0x00A60D90, 155 bytes long.
 Data: < t&             > F8 74 26 00 FF FF FF FF 00 00 00 00 00 00 00 00 
{2307} normal block at 0x00A60D40, 16 bytes long.  
 Data: <    h           > 90 0D A6 00 68 0E A6 00 D0 9F A5 00 A8 A0 A5 00 
{2306} normal block at 0x00A60CE8, 24 bytes long.
 Data: < t&             > C0 74 26 00 FF FF FF FF 00 00 00 00 00 00 00 00 
{2305} normal block at 0x00A60C70, 60 bytes long.
 Data: <                > BC 84 E5 00 E8 0C A6 00 00 00 00 00 00 00 00 00 
# Object dump complete.

I have called evconnlistener_free(listener);   and even evdns_base_free event_base_free libevent_global_shutdown.
after exe terminated. the dump shown.

I just have confirmed just one block=0x00A60D40 is "struct evconnlistener_iocp->struct accepting_socket **accepting"

**Comment by ellzey** [comment]
Sorry for the delay:

Can we get some code to reproduce this issue?

**Comment by azat** [comment]
https://github.com/nmathewson/Libevent/issues/112

**Comment by azat** [comment]
Closed in favor to #414
