### ISSUE TITLE
libevent incorrectly detects HAVE_WORKING_KQUEUE 0 when cross-compiling

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#260]
Presumably since the `configure` test can't properly run on the target to detect whether it works, libevent sets `HAVE_WORKING_KQUEUE` to `0` when cross-compiling. In the very common and very obvious case of iOS on ARM (iPhone, iPad, etc) `HAVE_WORKING_KQUEUE` should be `1`.

**Comment by ghazel** [comment]
last parameter, `action-if-cross-compiling` here: https://github.com/libevent/libevent/blob/1dbb55da324f2ba0ad562d0668dccb34b6c720f8/configure.ac#L547

**Comment by azat** [comment]
Does building with cmake and it's cache pre-load with `cmake -C` will work for you?
