### ISSUE TITLE
[RFC] Libevhtp integration

### ISSUE THREAD

**Issue by errzey** [libevent/libevent#261]
_This has been something we wanted to do for, crap, 5 or 6 years._ 
# The Plan (unfinished)

A quick overview of my vision, for replacing the current HTTP API in Libevent.
# Why?

Because the current `evhttp` server API has issues. most of the recent patches and tickets as of late have been related to `evhttp`.
#### Note: `evhttp` will monospaced, and `evhtp` will be bold to avoid naming confusion.
1. Break out the current `evhttp` into two files: `evhttp_server.c` & `evhttp_client.c`. Redundant code will be `evhttp-private.c`, and the public `evhttp` header will remain the same. The reasoning for this is **evhtp** was written primarily for server operations. Most, if not all of the client API were patches submitted from the OSS community, for which I am grateful for (hi @sodabrew & @adamel!). 
   Swapping out the server API from **evhtp** into `evhttp` will be much easier; while making the transition to the client API over time. **And most of those changes will be very minor, optional, and completely separate functions** (other than transitioning to the **evhtp** parser).
2.  **evhtp** comes default with thread support (must be manually enabled). Any function which calls any portion of of the threading API must be moved into it's own library: i.e., , `event2/http_thread.h`, and `libevent_http_thread.so`.
3. The same logic as http threading must be applied to **evhtp**'s builtin SSL support.
4. The same logic as the above must also be applied to **evhtp**'s builtin regex support.
5. All functionality currently supported in `evhttp` must be implemented and stable in **evhtp**
6. All current unit tests and examples for these changes must pass without any modifications to the code. This assures complete backwards compatibility. 
7. All **new** functionality from **evhtp** must have 100% test coverage.
8. Most, if not all of the exposed structs in **evhtp** will not be exposed to the user (unless currently exposed in `event2/http.h`)
9. Obviously the **evhtp** function prefixes would be replaced.
10. Much of the **evhtp** code should take advantage of the current structures and functions not not exported or exposed.
11. **evhtp** must be optimized for less `evbuffer` copies and move usage, (something that needs to be done in **evhtp** now anyway. Reduce those chains!)
12. where possible **evhtp** should use internal structures and up/downcasts in lieu of straight up `bufferevents`

**Comment by gj12** [comment]
I'm using libevent/evhttp 80% for client stuff. I first tried Libevhtp, but the client functionality in libevent was better and working. I don't know how much the client API differs, but it would be epic to have the best from both libs merged together.

**Comment by nmathewson** [comment]
1: Looking at this, I'm not clear whether it means that the old evhttp API, though deprecated, will still work, and the old evhttp unit tests will still pass.  IMO that's a solid requirement: We never want to break running code that uses an existing API as documented.

2: Might it make sense to stabilize 2.1 first and try to get this into 2.2 ?

**Comment by ellzey** [comment]
@nmathewson to your first point, read entries 5, 6, and 7.

> All functionality currently supported in evhttp must be implemented and stable in evhtp
> All current unit tests for the new API must pass.
> All new functionality from evhtp must have 100% test coverage.

Waiting for 2.2 is OK with me, thinking on it now, recently many of the reported issues have been around the evhttp api - but a complete replacement could cause trouble if I miss something. 

I think point 12 may is confusing:

> it would be pretty epic if we were able to keep backwards compatibility with the evhtp (optionally)

__Removing that__.

@gj12

> I'm using libevent/evhttp 80% for client stuff. I first tried Libevhtp, but the client functionality in libevent was better and working.

Yes, I agree! evhtp has been, for many years, 99.999% focused on server side. Client has always been neglected.

This is covered in detail in the very first point, maybe I worded it poorly?  The tl;dnr is the current evhttp client api will not be touched (at first); splitting up the files allows for us to slowly start adding the more "advanced" features over time. And most of those changes will be very minor, optional, and completely separate functions. _modifying that to be more clear_.

**Comment by ddiss** [comment]
Like @gj12, I'm using libevent's excellent http[s] client functionality in version 2.1.5-beta so would also appreciate if the libevhtp merge would tread lightly on the **client** API. Otherwise, I'm very much looking forward to seeing both code bases come together

**Comment by nschloe** [comment]
I found this bug by digging out [why transmission doesn't have IPv6 support](https://trac.transmissionbt.com/ticket/2236). Perhaps that's already been on your radar.

**Comment by slokhorst** [comment]
@nschloe I don't think that this is needed for IPv6 support in Tranmission. See [Transmission#59](https://github.com/transmission/transmission/issues/59).

**Comment by ddiss** [comment]
Any updates on the integration plan here? I'm still looking forward to seeing a 2.2 release, preferably with HTTP client functionality similar to 2.1.

**Comment by azat** [comment]
@ddiss firstly we need release *2.1 stable* (I hope that this will be in a month) and then we will work on *2.2*

**Comment by azat** [comment]
Sadly, but it is not available by from [ellzey repo](https://github.com/ellzey/libevhtp). Closing.

**Comment by lnicola** [comment]
https://github.com/criticalstack/libevhtp/

**Comment by azat** [comment]
Well I had a copy/fork too, but this is not about where we can get sources, but about who will do this and who will support libevhtp, but repo from criticalstack looks more alive then others, I need to take a look at it, but at diff stats looks huge (though most of changes are noise -- renames, e.t.c.):

     39 files changed, 3822 insertions(+), 7625 deletions(-)

**Comment by azat** [comment]
@NathanFrench are you still into this?
