### ISSUE TITLE
Happy Eyeballs (RFC 6555)

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#263]
https://tools.ietf.org/html/rfc6555

`bufferevent_socket_connect_hostname` currently resolves both addresses first, and then tries to connect (to the first addrinfo, no less), which can take very long time for IPv6 resolution to time out. RFC 6555 is the fairly standard way to address this.

**Comment by ellzey** [comment]
This is awesome, there's a ticket open on sf specifically about this issue.
