### ISSUE TITLE
if must call event_assign before event_add ?

### ISSUE THREAD

**Issue by badnoodle** [libevent/libevent#264]
see the title.
for the same event instance, before call event_add  if it is must call event_assign again ?

**Comment by nmathewson** [comment]
no.  Once you have created an event with event_assign() or event_new(), you do not need to call event_assign on it again.

**Comment by ellzey** [comment]
And try to keep away from event_assign in general.

**Comment by nmathewson** [comment]
Yup.  event_new() is much safer.

**Comment by ellzey** [comment]
Run dissas from gdb for both functions, the number of instructions that have to be executed to do assign versus new; you understand why we push for new. 

That and exposing the event structure may go away some day in the future.
