### ISSUE TITLE
libevent 2.1.5 beta evdns write-after-free causing heap corruption on Windows

### ISSUE THREAD

**Issue by akrieger** [libevent/libevent#269]
If you free an evdns object while a request is pending it causes heap corruption by writing to the free'd evdns object while finishing pending requests. Trace captured using Dr. Memory after observing reproducible crashes.

         Error #2: UNADDRESSABLE ACCESS of freed memory: writing 4 byte(s)
         request_finished
             c:\[redacted]\third_party\libevent-release-2.1.5-beta\evdns.c(662):
         evdns_base_free_and_unlock
             c:\[redacted]\third_party\libevent-release-2.1.5-beta\evdns.c(4022):
         evdns_base_free
             c:\[redacted]\third_party\libevent-release-2.1.5-beta\evdns.c(4062):
         [stack redacted]
         Note: refers to 296 byte(s) into memory that was freed here:
               replace_free   
                   d:\drmemory_package\common\alloc_replace.c(2507):
               evdns_nameserver_free
                   c:[redacted]\third_party\libevent-release-2.1.5-beta\evdns.c(3995):
               [stack redacted]

**Comment by azat** [comment]
Is it reproducible? Could you provide reproducer? Is it multi threaded? Which version do you use (including git commit sha1)?

**Comment by akrieger** [comment]
It was 100% reproducible by me at the time, but our code is fairly complex so generating minimal repro code from our code will be difficult. Also, given it is a race condition, by its very nature it is difficult to reproduce.

In our code, when I was just doing some testing, we setup an http server, a socket listener, and a pair of sockets, one of which we wait on. Before starting the main libevent loop, I 'queue' up data on one end of the paired sockets, such that the first thing that happens in the loop is reading data off that socket. In response to reading that data, we call event_base_loopbreak(). So, something like this.

```
struct event_base* base;
struct evdns_base* dnsbase;

void function_that_calls_event_base_loopbreak(struct bufferevent* bev, void* ctx) {
  event_base_loopbreak(base);
}

int main() {
  // Setup event base
  base = event_base_new();
  dnsbase = evdns_base_new(base, 1);

  // Setup socket listener
  evutil_socket_t sockets[2] = { 0, 0 };
  int error = evutil_socketpair(AF_INET, SOCK_STREAM, 0, sockets);

  evutil_socket_t mainSocket = sockets[0];
  evutil_socket_t otherSocket = sockets[1];

  evutil_make_socket_nonblocking(mainSocket);
  struct bufferevent *mainBEV = bufferevent_socket_new(base, mainSocket, BEV_OPT_CLOSE_ON_FREE);
  bufferevent_setcb(mainBEV, &function_that_calls_event_base_loopbreak, NULL, NULL, (void*)otherSocket);
  bufferevent_setwatermark(mainBEV, EV_READ, 0, 0);
  bufferevent_enable(mainBEV, EV_READ);

  send(otherSocket, "hello", 6, 0); // send to the socket before running the loop

  event_base_dispatch(base); // Immediately quits because of 'queued' quit command.
  
  evdns_base_free(dnsbase, true);
  event_base_free(base);

  // Don't forget to clean up sockets[]
}
```

**Comment by akrieger** [comment]
I can figure out the git hashes later, sorry.

**Comment by akrieger** [comment]
The changelog file in our copy of libevent says `version 2.1.5-beta (5 January 2015)`. I can't figure out the git hash :/

**Comment by akrieger** [comment]
It is identical to what is currently available at http://libevent.org/ under the Download-Alpha releases section.

**Comment by azat** [comment]
@akrieger thanks for additional info!

As for example, it doesn't use evdns at all, or I'm missing something?

Also maybe you could try the latest libevent version (from this repository) and plus a little patch https://github.com/azat/libevent/commit/8f240d54f17a38a19e89d0cd0fc3d7b82c48eb94 ?

**Comment by akrieger** [comment]
I'm not sure my sample code will 100% reproduce the issue. It is possible that I missed some small step that actually uses the dns (perhaps an http get somewhere). However, this is the minimal amount of code as I see it that can possibly reproduce it. Perhaps simply initializing the dns servers is enough if you exit 'fast enough.'

I will try newer code tomorrow after confirming it still reproduces in our code currently.

**Comment by akrieger** [comment]
I confirmed that I still get the heap corruption issue with our current code. I will try updating to latest libevent and your patch and will report back.

**Comment by azat** [comment]
Hi @akrieger 

Today I fixed some issues with `evdns_base_free(, fail_requests = true)`, can you please test the following branch?
https://github.com/azat/libevent/tree/dns-related-fixes-v4

i.e.
```
git clone --branch dns-related-fixes-v4 https://github.com/azat/libevent.git
```

Thanks,
Azat.

**Comment by akrieger** [comment]
Hi Azat, sorry for not getting back to you before. Work is taking up a lot of time :) I will test as soon as I can. Thank you!

**Comment by akrieger** [comment]
@azat I do not reliably reproduce heap corruption issues with the given branch and repo. Thank you!

**Comment by azat** [comment]
@akrieger thanks for testing!
