### ISSUE TITLE
Fatal error event_assign called on an already added event

### ISSUE THREAD

**Issue by jcoffland** [libevent/libevent#273]
This seems to be closely related to #258.  In my case there is only a single thread involved and it's happening on an SSL connection error.  Otherwise the stack trace looks very similar.

```
Event: event_assign called on an already added event 0x2af64df036b0 (events: 0x52, fd: 24, flags: 0x82)
Fatal error in event system -559030611: #0 0x009ee7a7 in 
#1 0x00c190d4 in event_exit at log.c
#2 0x00c194b1 in event_warnx
#3 0x00c01e48 in event_assign
#4 0x00bec94b in set_handshake_callbacks at bufferevent_openssl.c
#5 0x00bed131 in be_openssl_ctrl at bufferevent_openssl.c
#6 0x00bea675 in bufferevent_setfd
#7 0x00c1126e in evhttp_connection_reset_
#8 0x00c113b6 in evhttp_connection_cb_cleanup at http.c
#9 0x00c116d2 in evhttp_error_cb at http.c
#10 0x00c118ed in evhttp_connection_cb at http.c
#11 0x00be89c2 in bufferevent_run_deferred_callbacks_locked at bufferevent.c
#12 0x00c00d27 in event_process_active_single_queue at event.c
#13 0x00c0121a in event_process_active at event.c
#14 0x00c0191a in event_base_loop
#15 0x00c012a0 in event_base_dispatch
. . .
```

In #258 it is suggested to add code like the following:

```
if (event_initialized(&bev->ev_read)) event_del(&bev->ev_read);
if (event_initialized(&bev->ev_write)) event_del(&bev->ev_write);
```

I will trying adding this code in ``set_handshake_callbacks`` just before the ``event_assign()`` calls.

This error is happening only rarely.  On one run it took 50k transactions before it occurred but it is occurring with some regularity.

**Comment by azat** [comment]
Hi @jcoffland could you please test next patch?
bb997c0bc794c9f900e0346b3a420e39d3f47d87

**Comment by jcoffland** [comment]
The change I said I would try out above did eliminate the problem for me.  I'll try out your patch when I get a chance to look at this again but it may be awhile.  It's not easy for me to test because the error only occurs occasionally and I cannot afford to put it on a live server where it's likely to happen.

**Comment by azat** [comment]
Okay, thanks.
I updated patch (previous one have some bugs), you will find new version in this comment https://github.com/libevent/libevent/issues/258#issuecomment-136856603
Maybe it will be better to close this one, in favor to #258? (since I can forget to post here updates)

**Comment by jcoffland** [comment]
I suppose it's the same underlying problem, manifested differently and the title of #258 is sufficiently generic to cover my problem as well.  I'll close this as a duplicate of #258.
