### ISSUE TITLE
how del event successfully when fd got socket error

### ISSUE THREAD

**Issue by badnoodle** [libevent/libevent#277]
I have such a scene, one thread is processing the event, and the other thread register a event of the same fd, but in the first thread the fd got socket error, so i want to remove all event of the fd.

But what i got when I call event_del is "Epoll MOD(4) on fd 13 failed.  Old events were 6; read change was 2 (del); write change was 0 (none): Bad file descriptor"

so the struct event in the internal event queue were not remove successfully, so if I delete the event struct may cause memory leak problem.

What should I do ?

**Comment by azat** [comment]
Hi @badnoodle ,

Even when `event_del()` failed because of this, libevent must free event's internal state, IOW leaks mustn't be (also maybe you need to run `event_free()`).

But if you will find some, please create an issue here.

**Comment by badnoodle** [comment]
thank you for your reply
But I still be confuses.
Firstly, I read the code of evmap_io_del, the follows are piece of code:

             if (res) {
                 void *extra = ((char*)ctx) + sizeof(struct evmap_io);
                 if (evsel->del(base, ev->ev_fd, old, res, extra) == -1)
                        return (-1);
                retval = 1;
            }
            ctx->nread = nread;
            ctx->nwrite = nwrite;
            TAILQ_REMOVE(&ctx->events, ev, ev_io_next);
            return (retval);

if evsel->del failed then return immediately, and TAILQ_REMOVE will not be called, so the event struct will be always in ctx->events queue.

Secondly the event struct is hold by myself which is not come from event_new, so call event_free does not work.

So in my scene, how del event properly?

**Comment by azat** [comment]
Which version do you have?

After 9b5a527f libevent have:
```
        void *extra = ((char*)ctx) + sizeof(struct evmap_io);
        if (evsel->del(base, ev->ev_fd, old, res, extra) == -1) {
            retval = -1;                                                                                                                                                                                                                                                          
        } else {
            retval = 1; 
        }
```

**Comment by badnoodle** [comment]
libevent-2.0.21-stable

**Comment by azat** [comment]
Could you try [2.1.5-beta](http://sourceforge.net/projects/levent/files/libevent/libevent-2.1/libevent-2.1.5.beta.tar.gz/download) or master branch of this repo?

**Comment by badnoodle** [comment]
ok, thank you. I will update and try again
