### ISSUE TITLE
Libevent makefile for DJGPP

### ISSUE THREAD

**Issue by iw2evk** [libevent/libevent#279]
Hi,
can you add to next distro a makefile for build libraries under DJGPP (gcc porting for DOS)?
Many thanks
Regards
Roberto iw2evk

**Comment by azat** [comment]
Hi @iw2evk 
dos is pretty dead platform, and libevent already supports too many build systems, so I guess that this will not be done (discussed with @nmathewson).

**Comment by ellzey** [comment]
cmake should really be fixed.
