### ISSUE TITLE
regress_bufferevent doesn't build on arm

### ISSUE THREAD

**Issue by proppy** [libevent/libevent#284]
Because of the inline asm x86 instructions:
https://github.com/libevent/libevent/blob/3f749e93db4f6bf10beb73d8d5d523d0e3b036e3/test/regress_bufferevent.c#L248

**Comment by azat** [comment]
@proppy nice catch, thanks (that one left from debugging times)!

**Comment by proppy** [comment]
@azat thanks for the quick turnaround! I hope it didn't bring bad debugging memories :)
