### ISSUE TITLE
DNS poisoning prevention code is wrong

### ISSUE THREAD

**Issue by madmaxoft** [libevent/libevent#288]
The DNS poisoning prevention code seems wrong to me. Namely, lines
https://github.com/libevent/libevent/blob/master/evdns.c#L1073-L1078 seem to have their conditions swapped - if the random-casing is enabled, the response is checked case-sensitive, which, at least for me, always fails.

For request `github.com` I get a request with `GItHUb.cOM` as the requested name and the answer contains `github.com`, so there's no match and an "unknown error" is reported.

**Comment by azat** [comment]
@madmaxoft nice catch!
Fixed (and regression test added for this).

Thanks.

**Comment by madmaxoft** [comment]
I really wasn't sure about this, because I didn't know the exact reasons for implementing this, nor the implementation details, and I thought I couldn't be the first one noticing this problem - I'm using the DNS in a fairly default-ish manner, setting no extra options.
