### ISSUE TITLE
[RFC] Alternative TLS implementation

### ISSUE THREAD

**Issue by deleisha** [libevent/libevent#290]
Will libevent be interested in another TLS implementation, which will coexist with the current implementation.
Would like to integrate with libevent with evt-tls( https://github.com/deleisha/evt-tls ). evt-tls is based on Bio pair of OpenSSL as of now, But will add for other libary like mbedtls.

If libevent is interested, I can start working on the integration. 

Sorry , if this is the wrong forum, I have missed to see libevent-dev list

**Comment by ellzey** [comment]
On 10/19, deleisha wrote:
> Will be libevent be interested in another TLS implementation, 

Yes, as long as the license of the implementation does not conflict with
the BSD license that libevent uses.

> which will coexist with the current implementation.
> Would like to integrate with libevent with evt-tls( https://github.com/deleisha/evt-tls ). evt-tls is based on Bio pair of OpenSSL as of now, But will add for other libary like mbedtls.

This isn't a new implementation of TLS, it's just a wrapper around
OpenSSL using BIOs. 

BIO's suck; We tried it, and I hope we got rid of it.

>
> If libevent is interested, I can start working on the integration.

Abstracting SSL for interchangeable functionality has been something I've
been thinking about for over a year. The question is, what are all of
the standard functions we would need to satisfy the core needs.

For example, I have some code that uses OpenSSL specific functions while
still using bufferevent_openssl; In my case it would be looking for the
SNI. Do we make abstractions around all of those types of functions?


>
> Sorry , if this is the worong forum, I have missed to see libevent-dev list
>

Perfectly fine.

**Comment by deleisha** [comment]
Nice to hear Mark

evt-tls will be based on MIT license, So hope that it will not be an issue.

mbedtls is something we have been pondering, Thanks for pointing out the mbedtls license issue. 
Currently, They seem to have moved to Apache, Need to explore more 
https://github.com/ARMmbed/mbedtls/blob/development/LICENSE

mbedtls is not yet in evt-tls, that was something which was in wish list

evt-tls is using OpenSSL backend ONLY currently. Well BIO pair is not our custom BIO it is one of the `standard BIO` exposed by OpenSSL. Feels like BIO pair is a goot approach to use OpenSSL as a state machine as it remove maitaining our own BIO implementation. This seems to be a good way for all networking lib like libevent where we want to handle netwoking on our own. We feed whatever data we receive and let the abstraction call us back with user registered callback 

Currently, The abstractions are done for (normal operations apart from some API for ctx setup)
`evt_tls_connect <-------------------> SSL_connect`
`evt_tls_accept<----------------------> SSL_accept`
`evt_tls_read<-------------------------> SSL_read`
`evt_tls_write<-------------------------> SSL_write`
`evt_tls_cose<-------------------------> SSl_shutdown`

`SNI` is not currently coded, that is something that we will be adding soon in evt-tls.
If would could give your wish list, We can discuss and add them

**Comment by ellzey** [comment]
At a second glance we do use bio's for the betas *shudder*. 

I would like to get a list of what functionality users need to properly abstract to the point where they can swap in their ssl/tls implementation of their choice (e.g., how we do threads).

Would be a good research topic.

**Comment by ellzey** [comment]
I did a bit of researching (googling), and I found that libcurl has a decent enough hooking api for ssl. Though it's not table based, it has to be done at compile time (was hoping to have a vtable which has all the right functions on would need to do such a thing)

That aside, I've been working on a libress (libtls) addition, as it touts a much easier-to-use non-blocking api.
