### ISSUE TITLE
Version `GLIBC_2.7' not found when accessing from rsync

### ISSUE THREAD

**Issue by xywei** [libevent/libevent#292]
Not sure if this is the right place to ask this question:

 In order use ``tmux`` on a remote server where I don't have root access, I compiled libevent from source, installed it under $HOME, and added libevent-2.0-so.5 to $LD_PRELOAD. After that, I was able to ssh into that server, and ``tmux`` works fine; however, I can no longer use other approaches to access the server. For example, ``rsync`` complains:

``/lib64/libc.so.6: version `GLIBC_2.7' not found (required by ***/libevent/lib/libevent-2.0.so.5).``

The same thing happens when I tried ``scp`` and ``sftp``. 

The output of ``ldd --version`` shows I do have glibc installed:
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by azat** [comment]
On Sun, Nov 08, 2015 at 07:33:48PM -0800, Xiaoyu WEI wrote:
> Not sure if this is the right place to ask this question:

This is not libevent issue, but let's go ahead:

>  In order use ``tmux`` on a remote server where I don't have root access, I compiled libevent from source, installed it under $HOME, and added libevent-2.0-so.5 to $LD_PRELOAD. After that, I was able to ssh into that server, and ``tmux`` works fine; however, I can no longer use other approaches to access the server. For example, ``rsync`` complains:

Can you just use LD_LIBRARY_PATH instead? (I think this must works,
since tmux requires libevent 2.0). In this case libevent will not be
loaded for every program.

Also maybe you have ControlPath/ControlMaster setting in ssh?
This means that your ssh server can/will reuse existing connection.

> ``/lib64/libc.so.6: version `GLIBC_2.7' not found (required by ***/libevent/lib/libevent-2.0.so.5).``
> 
> The same thing happens when I tried ``scp`` and ``sftp``. 
> 
> The output of ``ldd --version`` shows I do have glibc installed:

Can you post here rsync.log (run it from that server)?
$ LD_DEBUG=all LD_OUTPUT=rsync.log rsync ...

**Comment by xywei** [comment]
Thanks for your concern!

> Can you just use LD_LIBRARY_PATH instead? (I think this must works,
> since tmux requires libevent 2.0). In this case libevent will not be
> loaded for every program.

Using LD_LIBRARY_PATH saved my day! (I started wondering why fellows on [this thread](http://unix.stackexchange.com/questions/17907/why-cant-gcc-find-libevent-when-building-tmux-from-source) all seem to prefer setting LD_PRELOAD). 

Btw, I just realised that one can bypass this issue by recompiling tmux with -static.

> Also maybe you have ControlPath/ControlMaster setting in ssh?
> This means that your ssh server can/will reuse existing connection.

Not I am aware of (at least not under my $HOME directory).

> Can you post here rsync.log (run it from that server)?
> $ LD_DEBUG=all LD_OUTPUT=rsync.log rsync ...

Seems that I can only post image files here (the full log is too long to include inline). Here are a few lines I think might be relevant (glibc2.2.5 is being binded?): 

```
...
    32140:	checking for version `LIBPOPT_0' in file /lib64/libpopt.so.0 [0] required by file rsync [0]
     32140:	checking for version `ACL_1.0' in file /lib64/libacl.so.1 [0] required by file rsync [0]
     32140:	checking for version `GLIBC_2.4' in file /lib64/libc.so.6 [0] required by file rsync [0]
     32140:	checking for version `GLIBC_2.8' in file /lib64/libc.so.6 [0] required by file rsync [0]
     32140:	checking for version `GLIBC_2.3' in file /lib64/libc.so.6 [0] required by file rsync [0]
     32140:	checking for version `GLIBC_2.3.4' in file /lib64/libc.so.6 [0] required by file rsync [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file rsync [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/librt.so.1 [0] required by file /(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	checking for version `GLIBC_2.7' in file /lib64/libc.so.6 [0] required by file /(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	checking for version `GLIBC_2.3.2' in file /lib64/libc.so.6 [0] required by file /(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	checking for version `ATTR_1.0' in file /lib64/libattr.so.1 [0] required by file /lib64/libacl.so.1 [0]
     32140:	checking for version `GLIBC_2.4' in file /lib64/libc.so.6 [0] required by file /lib64/libacl.so.1 [0]
     32140:	checking for version `GLIBC_2.3.4' in file /lib64/libc.so.6 [0] required by file /lib64/libacl.so.1 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /lib64/libacl.so.1 [0]
     32140:	checking for version `GLIBC_2.4' in file /lib64/libc.so.6 [0] required by file /lib64/libpopt.so.0 [0]
     32140:	checking for version `GLIBC_2.3' in file /lib64/libc.so.6 [0] required by file /lib64/libpopt.so.0 [0]
     32140:	checking for version `GLIBC_2.3.4' in file /lib64/libc.so.6 [0] required by file /lib64/libpopt.so.0 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /lib64/libpopt.so.0 [0]
     32140:	checking for version `GLIBC_PRIVATE' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libc.so.6 [0]
     32140:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libc.so.6 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libpthread.so.0 [0] required by file /lib64/librt.so.1 [0]
     32140:	checking for version `GLIBC_PRIVATE' in file /lib64/libpthread.so.0 [0] required by file /lib64/librt.so.1 [0]
     32140:	checking for version `GLIBC_2.3.2' in file /lib64/libc.so.6 [0] required by file /lib64/librt.so.1 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /lib64/librt.so.1 [0]
     32140:	checking for version `GLIBC_PRIVATE' in file /lib64/libc.so.6 [0] required by file /lib64/librt.so.1 [0]
     32140:	checking for version `GLIBC_2.4' in file /lib64/libc.so.6 [0] required by file /lib64/libattr.so.1 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /lib64/libattr.so.1 [0]
     32140:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libpthread.so.0 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libpthread.so.0 [0]
     32140:	checking for version `GLIBC_PRIVATE' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /lib64/libpthread.so.0 [0]
     32140:	checking for version `GLIBC_2.3.2' in file /lib64/libc.so.6 [0] required by file /lib64/libpthread.so.0 [0]
     32140:	checking for version `GLIBC_PRIVATE' in file /lib64/libc.so.6 [0] required by file /lib64/libpthread.so.0 [0]
     32140:	checking for version `GLIBC_2.2.5' in file /lib64/libc.so.6 [0] required by file /lib64/libpthread.so.0 [0]
     32140:	
     32140:	prelink checking: failed
     32140:	
     32140:	relocation processing: /lib64/libpthread.so.0 (lazy)
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=rsync [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/lib64/libacl.so.1 [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/lib64/libpopt.so.0 [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/lib64/libc.so.6 [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/lib64/librt.so.1 [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/lib64/libattr.so.1 [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
     32140:	symbol=_Jv_RegisterClasses;  lookup in file=/lib64/libpthread.so.0 [0]
     32140:	symbol=errno;  lookup in file=rsync [0]
     32140:	symbol=errno;  lookup in file=/(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	symbol=errno;  lookup in file=/lib64/libacl.so.1 [0]
     32140:	symbol=errno;  lookup in file=/lib64/libpopt.so.0 [0]
     32140:	symbol=errno;  lookup in file=/lib64/libc.so.6 [0]
     32140:	binding file /lib64/libpthread.so.0 [0] to /lib64/libc.so.6 [0]: normal symbol `errno' [GLIBC_PRIVATE]
     32140:	symbol=__libc_stack_end;  lookup in file=rsync [0]
     32140:	symbol=__libc_stack_end;  lookup in file=/(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	symbol=__libc_stack_end;  lookup in file=/lib64/libacl.so.1 [0]
     32140:	symbol=__libc_stack_end;  lookup in file=/lib64/libpopt.so.0 [0]
     32140:	symbol=__libc_stack_end;  lookup in file=/lib64/libc.so.6 [0]
     32140:	symbol=__libc_stack_end;  lookup in file=/lib64/librt.so.1 [0]
     32140:	symbol=__libc_stack_end;  lookup in file=/lib64/libattr.so.1 [0]
     32140:	symbol=__libc_stack_end;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
     32140:	binding file /lib64/libpthread.so.0 [0] to /lib64/ld-linux-x86-64.so.2 [0]: normal symbol `__libc_stack_end' [GLIBC_2.2.5]
     32140:	symbol=__cxa_finalize;  lookup in file=rsync [0]
     32140:	symbol=__cxa_finalize;  lookup in file=/(path-to-libevent)/libevent/lib/libevent-2.0.so.5 [0]
     32140:	symbol=__cxa_finalize;  lookup in file=/lib64/libacl.so.1 [0]
     32140:	symbol=__cxa_finalize;  lookup in file=/lib64/libpopt.so.0 [0]
     32140:	symbol=__cxa_finalize;  lookup in file=/lib64/libc.so.6 [0]
     32140:	binding file /lib64/libpthread.so.0 [0] to /lib64/libc.so.6 [0]: normal symbol `__cxa_finalize' [GLIBC_2.2.5]
...
```

**Comment by azat** [comment]
On Mon, Nov 09, 2015 at 06:12:55AM -0800, Xiaoyu WEI wrote:
> Btw, I just realised that one can bypass this issue by recompiling tmux with -static.

Sure!

> > Can you post here rsync.log (run it from that server)?
> > $ LD_DEBUG=all LD_OUTPUT=rsync.log rsync ...
> 
> Seems that I can only post image files here (the full log is too long to include inline). Here are a few lines I think might be relevant (glibc2.2.5 is being binded?): 

You can use gist.github.com, and post here full log (since this snippet
doesn't helps a lot), for next programs:
- rsync
- tmux

**Comment by xywei** [comment]
Sorry I cannot reproduce exactly the same stuff since I recompiled libevent and tmux with gcc 5.2. However the issue with LD_PRELOAD persists. Here are the logs AFTER the changes produced by 
``
LD_DEBUG=all LD_DEBUG_OUTPUT=rsync.log rsync ~/test
``
where ``test`` is an empty directory.
- [with LD_PRELOAD setting](https://gist.github.com/xywei/ab50059b09132ce192d5)
- [with LD_LIBRARY_PATH](https://gist.github.com/xywei/0a76387cede2c875a07a)

**Comment by azat** [comment]
On Wed, Nov 18, 2015 at 07:28:06PM -0800, Xiaoyu WEI wrote:
> Sorry I cannot reproduce exactly the same stuff since I recompiled libevent and tmux with gcc 5.2. However the issue with LD_PRELOAD persists. Here are the logs AFTER the changes produced by 

In this case can you also attach LD_PRELOAD with tmux? (i.e. when it
works).

Thanks,
Azat.

**Comment by azat** [comment]
> Sorry I cannot reproduce exactly the same stuff since I recompiled libevent and tmux with gcc 5.2. However the issue with LD_PRELOAD persists. Here are the logs AFTER the changes produced by 

And also:
$ readelf -a /lib64/libc.so.6

**Comment by azat** [comment]
Closing this one, to avoid noise in bug list (but if you want to understand, please post info here).
