### ISSUE TITLE
SSL sockets are getting left behind in CLOSE_WAIT state

### ISSUE THREAD

**Issue by 98tango** [libevent/libevent#294]
We are using 2.1.5-beta and we are seeing a bunch of SSL sockets getting leaked on the client side. Based on the lsof output, they are all in CLOSE_WAIT state and they never get closed. 

I did a bunch of debugging to narrow down the problem and I'll try to include as much as possible below but if you need more info, please let me know. I'm sorry I just don't have a small standalone testcase for it. 

First, I looked at strace -tt and this is the sequence of calls I see for the leaked FDs (ip obfuscated)

```
20:56:24.655718 socket(PF_INET, SOCK_STREAM|SOCK_NONBLOCK, IPPROTO_IP) = 3522
20:56:24.655851 connect(3522, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("X.X.X.X")}, 16) = -1 EINPROGRESS (Operation now in progress)
20:56:24.655973 epoll_ctl(6, EPOLL_CTL_ADD, 3522, {EPOLLOUT, {u32=3522, u64=3522}}) = 0
20:56:24.663131 epoll_wait(6, {{EPOLLOUT, {u32=3522, u64=3522}}}, 2048, 172) = 1
20:56:24.669775 epoll_ctl(6, EPOLL_CTL_DEL, 3522, {EPOLLOUT, {u32=3522, u64=3522}}) = 0
```
and nothing more after that. Before that the same socket fd was used for a different connection and was properly shutdown()'d and close()'d.

Next, I rebuilt libevent with USE_DEBUG and a few more debug statements as I found the need for them. Here's a snippet of the debug log of the relevant evcon & bufferevent structures. 

```
[http_manager.cpp:498] making request to X.X.X.X on evcon=0x253c3a0, req=0x2686150
[debug] evhttp_connection_reset_ : evcon=0x253c3a0, fd=-1
[debug] event_del: 0x253bc10 (fd -1), callback 0x57b1f0
[debug] event_del: 0x253bc90 (fd -1), callback 0x57b2ac
[debug] event_add: event: 0x253bc90 (fd -1),  EV_WRITE  EV_TIMEOUT call 0x57b2ac
[debug] event_add: event 0x253bc90, timeout in 45 seconds 0 useconds, call 0x57b2ac
[debug] event_del: 0x253bc90 (fd -1), callback 0x57b2ac
[debug] event_del: 0x253bc10 (fd -1), callback 0x57b1f0
[debug] event_add: event: 0x253bc90 (fd -1),  EV_WRITE  EV_TIMEOUT call 0x57b2ac
[debug] event_add: event 0x253bc90, timeout in 45 seconds 0 useconds, call 0x57b2ac
[debug] event_del: 0x253bc10 (fd -1), callback 0x57b1f0
[debug] event_del: 0x253bc90 (fd -1), callback 0x57b2ac
[debug] event_add: event: 0x253bc90 (fd 305),  EV_WRITE  EV_TIMEOUT call 0x57b2ac
[debug] Epoll ADD(4) on fd 305 okay. [old events were 0; read change was 0; write change was 1; close change was 0]
[debug] event_add: event 0x253bc90, timeout in 45 seconds 0 useconds, call 0x57b2ac
[debug] event_add: event: 0x253bc90 (fd 305),  EV_WRITE  EV_TIMEOUT call 0x57b2ac
[debug] event_add: event 0x253bc90, timeout in 45 seconds 0 useconds, call 0x57b2ac
[debug] event_active: 0x253bc90 (fd 305), res 4, callback 0x57b2ac
[debug] event_process_active: event: 0x253bc90,  EV_WRITE  call 0x57b2ac
[debug] event_add: event: 0x253bc90 (fd 305),  EV_WRITE  EV_TIMEOUT call 0x57b2ac
[debug] event_add: event 0x253bc90, timeout in 8365947 seconds 475578 useconds, call 0x57b2ac
[debug] be_openssl_writeeventcb: fd=305, read_event=0x253bc10, read_fd=305, write_event=0x253bc90, write_fd=305 what=4
[debug] consider_writing: no outbuf space, read_fd=305
[debug] event_del: 0x253bc90 (fd 305), callback 0x57b2ac
[debug] Epoll DEL(4) on fd 305 okay. [old events were 4; read change was 0; write change was 2; close change was 0]
[http_manager.cpp:307] request_timeout_cb called for evcon=0x253c3a0, req=0x2686150
[debug] evhttp_cancel_request : evcon=0x253c3a0, req=0x2686150
[debug] evhttp_cancel_request : connection_fail codepath for evcon=0x253c3a0, req=0x2686150
[debug] event_del: 0x253bc10 (fd 305), callback 0x57b1f0
[debug] event_del: 0x253bc90 (fd 305), callback 0x57b2ac
[debug] evhttp_connection_reset_ : evcon=0x253c3a0, fd=-1
[debug] event_del: 0x253bc10 (fd 305), callback 0x57b1f0
[debug] event_del: 0x253bc90 (fd 305), callback 0x57b2ac
```

What's happening here is that we had an evcon which was connected and used successfully for a bunch of requests but it got disconnected for whatever reason and we notice that when we try to reuse it to issue a new request. At that point, libevent resets the evcon and attempts to establish a new connection. However the event callback went to be_openssl_writeeventcb even though we are still in the process of establishing a new connection on a new socket here. I suspect we should have had the callbacks setup to point to be_openssl_handshakeeventcb. 

I updated be_openssl_ctrl() as follows and it seems to have slowed down the rate at which we leak these sockets but there is still a pending leak that I'm still looking into. 

```
diff --git a/bufferevent_openssl.c b/bufferevent_openssl.c
index b30f90f..3745496 100644
--- a/bufferevent_openssl.c
+++ b/bufferevent_openssl.c
@@ -1276,8 +1276,10 @@ be_openssl_ctrl(struct bufferevent *bev,
                        SSL_set_bio(bev_ssl->ssl, bio, bio);
                        bev_ssl->fd_is_set = 1;
                }
-               if (data->fd == -1)
+               if (data->fd == -1) {
                        bev_ssl->fd_is_set = 0;
+                       bev_ssl->state = BUFFEREVENT_SSL_CONNECTING;
+               }
                if (bev_ssl->state == BUFFEREVENT_SSL_OPEN)
                        return set_open_callbacks(bev_ssl, data->fd);
                else {
```

In the meantime, I wanted to get an opinion from libevent experts on the above issue/patch to see if there is a more appropriate place to reset the bufferevent's state so that it uses the handshake callbacks instead of the open callbacks during the next reconnect attempt.

**Comment by azat** [comment]
Hi @98tango,

Thanks for detailed debugging information, however in the upstream there
is no `fd_is_set`, plus there are some other fixes related to
`bufferevent_ssl`, can you please give them a try? (i.e. get the latest
sources and compile libevent).

Thanks,
Azat.

**Comment by 98tango** [comment]
Thanks for the response. I see the following commit

```
commit e8a2da96e3fedc3ebf7d322df0fac155dfb41717
Author: Azat Khuzhin <a3at.mail@gmail.com>
Date:   Wed Sep 2 14:19:16 2015 +0300

    be_openssl: don't call set_open_callbacks() if fd == -1

    This must be illegal, firstly we must do set_do handshake and only after this
    we could read/write.
```

which makes a very similar fix to what I mentioned above. I'll build the latest code from this github repo and report back.

**Comment by ellzey** [comment]
`bufferevent_openssl_set_allow_dirty_shutdown` may be a good place to look too. Otherwise known as:

``C
SSL_set_shutdown(ssl_context, SSL_RECEIVED_SHUTDOWN);
SSL_shutdown(ssl_contxt);
```

**Comment by 98tango** [comment]
I'm happy to report that we've run on SHA 809bb39b2b7b632c86337877b483520d997cd5db for about 16 hours and we don't have any sockets in CLOSE_WAIT state whereas earlier we were leaking 10's of sockets per hour. So, I think we can consider this issue resolved.

**Comment by azat** [comment]
Great, @98tango thanks for testing!
