### ISSUE TITLE
[RFC] why all the different make files

### ISSUE THREAD

**Issue by ellzey** [libevent/libevent#298]
That are windows only..

cmake can easily generate the same cross-compatible variants for all these systems.

**Comment by nmathewson** [comment]
Feel free to kill 'em IMO

**Comment by ellzey** [comment]
I'm right in the middle of un-fucking cmake.

**Comment by ellzey** [comment]
like errmagersh: https://github.com/libevent/libevent/compare/master...ellzey:cmake_updates?expand

**Comment by ellzey** [comment]
blowing up things, boom, pow, bang

**Comment by ellzey** [comment]
ref https://github.com/libevent/libevent/issues/246

**Comment by azat** [comment]
Closing this one, since some differences already eliminated and anyway there are no details here what differs.
