### ISSUE TITLE
[RFC] Transfer ownership to the Libevent organization.

### ISSUE THREAD

**Issue by ellzey** [libevent/libevent#304]
@nmathewson when you get a chane, read over https://help.github.com/articles/transferring-a-repository/
 so we can unfork ourselves.

### reasoning

The compare branches section defaults to nmathewson/xxxx...yyyy, the results of which are very slow based on how far behind the original repository is.

I've not looked, but there may be issues and requests that were sen there instead.

**Comment by nmathewson** [comment]
I just tried, but it told me that I couldn't, because a repository named libevent/Libevent already exists.

**Comment by nmathewson** [comment]
In the meantime, I've given you and azat push access to nmathewson/Libevent

**Comment by ellzey** [comment]
OK, I will do some moving around in the next few days.

**Comment by ellzey** [comment]
It still needs full ownership to be official. But for now I made it a mirror instead of a fork.

**Comment by azat** [comment]
>It still needs full ownership to be official
Done
