### ISSUE TITLE
2.1.5-beta, signals and event_reinit

### ISSUE THREAD

**Issue by nicm** [libevent/libevent#307]
http://sourceforge.net/p/levent/bugs/350/

event_reinit isn't doing the right thing for non-reinit backends.

It only closes the signal socketpair fds and recreates them if signals have been added, but this is wrong - the parent could add signals AFTER event_reinit is called in the child.

For non-reinit backends, this will use the same socketpair because the child didn't create a new one (because there were no signals added before event_reinit).

So event_reinit should ALWAYS call evsig_init_ for non-reinit backends (reinit backends will do it anyway in their init function).

Also, for non-reinit backends, event_reinit removes the event, but only evsig_add puts it back. So it seems as if any signals set up before event_reinit will be ignored until another signal is added.

Only the first part affects tmux but this diff fixes them both: http://pastebin.ca/raw/3298450

**Comment by nicm** [comment]
[event.c.diff.txt](https://github.com/libevent/libevent/files/70624/event.c.diff.txt)

**Comment by nicm** [comment]
First test program demonstrates the first problem (signals added in parent after child calls event_reinit):

$ ./test-reinit2
sending signal
child signal
^C
$ ./test-reinit2
sending signal
child signal
^C
$ ./test-reinit2
sending signal
PARENT signal
^C
$
[test-reinit2.c.txt](https://github.com/libevent/libevent/files/70625/test-reinit2.c.txt)

**Comment by nicm** [comment]
Second test program s
[test-reinit3.c.txt](https://github.com/libevent/libevent/files/70627/test-reinit3.c.txt)
hows the second problem, if signals are added in the parent before fork, they are not received in the child after event_reinit. The diff above also fixes this.
Wrong output:
$ ./test-reinit3
sending signal
^C
$
Correct output:
$ ./test-reinit3
sending signal
PARENT signal
^C
$
(Note even though it says PARENT the signal is being sent to and the callback is being fired in the child; it just sets the signal event up in the parent.)

**Comment by azat** [comment]
Actually libevent's signal layer is pretty dumb, and I'm going to rewrite it (refs #105)

**Comment by nicm** [comment]
Great, but please note that tmux will not work properly with libevent 2.1 on Linux (where we can't use epoll) or OS X and FreeBSD (where we can't use kqueue) if it is released with this problem, so I would be keen to see a fix or a rewrite before 2.1 or I will have lots of users complaining.

A signalfd implementation should fix Linux, but I believe it is not present on OS X or FreeBSD.

**Comment by azat** [comment]
@nicm thanks for pointing this out, I will take a closer look a little bit later (Even though linux without epoll is pretty uncommon).

**Comment by nicm** [comment]
Thanks. tmux does not use epoll on Linux because it is not supported on common devices like /dev/null.

**Comment by azat** [comment]
@nicm I've splitted your patch into two (since indeed there are two different issues, like you pointed out) and update messages, wrote regressions (`regress main/fork`) for both of fixes.
Right now I need some more time for testing and after I will merge them.

Many thanks for detailed report!

Also if you want to, you can test next branch (just in case, but I would appreciate it):
```
git clone --branch event_reinit-for-signals-v2 git@github.com:azat/libevent.git
```

Cheers,
Azat.

**Comment by nicm** [comment]
Many thanks Azat
