### ISSUE TITLE
Cannot build with VS12 - missing definition for ssize_t

### ISSUE THREAD

**Issue by homerocda** [libevent/libevent#311]
Hi,

I'm having a hard time building libevent on Visual Studio 12 2013. I've downloaded the master branch and generated build files for Nmake and Visual Studio solutions. In either configurations, the build fails because of a definition for ssize_t.

This is the error message I get upon build for several files:

    C:\libevent-master\include\event2/buffer.h(117) : error C2016: C requires that a struct or union has at least one member
    C:\libevent-master\include\event2/buffer.h(117) : error C2061: syntax error : identifier 'ssize_t'
    C:\libevent-master\include\event2/buffer.h(125) : error C2059: syntax error : '}'

This is the offending code:
    struct evbuffer_ptr {
        ev_ssize_t pos;

        /* Do not alter or rely on the values of fields: they are for internal
         * use */
        struct {
            void *chain;
            size_t pos_in_chain;
        } internal_;
    };

ev_ssize_t is defined in util.h as:

    #ifdef EVENT__ssize_t
    #define ev_ssize_t EVENT__ssize_t
    #else
    #define ev_ssize_t ssize_t
    #endif

and EVENT__ssize_t is defined in event-config.h as

    /* Define to `int' if <sys/types.h> does not define. */
    #define EVENT__ssize_t ssize_t

But there is no definition of ssize_t anywere.

I can build the library with linking warnings if i define ssize_t to int, however I get linking errors when building any of the tests.

Is this a bug or some other issue in my environment?

**Comment by azat** [comment]
On Thu, Jan 07, 2016 at 04:53:55AM -0800, Homero Cardoso de Almeida wrote:
> Hi,
> 
> I'm having a hard time building libevent on Visual Studio 12 2013 I've downloaded the master branch and generated build files for Nmake and Visual Studio solutions In either configurations, the build fails because of a definition for ssize_t

Hi,

Seems that you are using cmake?

**Comment by homerocda** [comment]
Yes, I'm using CMake.

**Comment by azat** [comment]
> Yes, I'm using CMake.

After a first glance, can you try referenced patch?

**Comment by homerocda** [comment]
It did not work, I'm still getting the same message.

Just a note: I have openssl in my system, whose headers are inside a PostgreSQL dir. Looks like these are being fetched by CMake in config and in one of them there's a definition for ssize_t, although it doesn't have anything to do with the ssize_t expected in sys/types.h. Maybe this definition is messing up CMake's build?

**Comment by azat** [comment]
On Thu, Jan 07, 2016 at 07:20:01AM -0800, Homero Cardoso de Almeida wrote:
> It did not work, I'm still getting the same message.

Can you try latest referenced patch? (from -v2)
It must works for you, but only for ssize_t issue, the linking part
still not fixed, you can try to workaround this by building shared
libraries instead of static.

> Just a note: I have openssl in my system, whose headers are inside a PostgreSQL dir. Looks like these are being fetched by CMake in config and in one of them there's a definition for ssize_t, although it doesn't have anything to do with the ssize_t expected in sys/types.h. Maybe this definition is messing up CMake's build?

Nope, I don't think that pgsql is related to this.

**Comment by homerocda** [comment]
Thanks, the latter patch worked for the ssize_t issue.

As for building shared libraries, you mean by toggling EVENT__BUILD_SHARED_LIBRARIES in CMake?

**Comment by azat** [comment]
> As for building shared libraries, you mean by toggling EVENT__BUILD_SHARED_LIBRARIES in CMake?

Yep, this must fix the linking issue (but sure we need to fix this for
static libraries too).

**Comment by homerocda** [comment]
Ok, got it. I get the exceptions only when building project "event_extra_static" now.

Thanks a lot for your help.

**Comment by azat** [comment]
@homerocda can you please create new issue with static linking on win32 and close this one?

**Comment by homerocda** [comment]
@azat just opened #314 for that.
