### ISSUE TITLE
Problem with downloading 1.4.15-stable libevent tar

### ISSUE THREAD

**Issue by mail2pr** [libevent/libevent#312]
It looks like libevent 1.4.15-stable link has been updated on libevent.org. https://github.com/downloads/libevent/libevent/libevent-1.4.15-stable.tar.gz is not working. 

let me know the new location.

Thanks

**Comment by azat** [comment]
@mail2pr after some migrations from sf.net and others, release has been lost, me searching for it.

**Comment by ellzey** [comment]
It looks like we used up our 2GB limit. https://help.github.com/articles/about-releases/

I think I'm going to buy us a new account.

**Comment by azat** [comment]
@ellzey according to this page:
```
We don't limit the total size of your binary release files, nor the bandwidth used to deliver them. However, each individual file must be under 2GB in size
```

So seems that we don't need new account, since limit for *individual file*, so, do we?

**Comment by ellzey** [comment]
ah ok.

fixed: https://github.com/libevent/libevent/archive/release-1.4.5-stable.tar.gz

**Comment by azat** [comment]
Yep, I've just pushed this tag, though we need to update links, on it

**Comment by mail2pr** [comment]
But I was facing problem for 1.4.15 not 1.4.5

**Comment by azat** [comment]
@mail2pr fixed in the referenced commit.

**Comment by azat** [comment]
@mail2pr IOW you can just download them from http://libevent.org (but links is differs from the attached in the issue).

**Comment by ellzey** [comment]
On the website? Hrm. Most of the inks on libevent.org are still going to sf.

**Comment by ellzey** [comment]
Also, I pushed *ALL* of our releases.

**Comment by azat** [comment]
@ellzey you also pushed debug tags (like this https://github.com/libevent/libevent/tree/status), that is why I didn't do:
``` git push --tags origin ```

And did this instead:
``` git push origin refs/tags/release-1.4.15-stable ```

More interesting questions, "who deleted tags?"

**Comment by mail2pr** [comment]
Thanks, its working now.

**Comment by ellzey** [comment]
@azat I always considered tags as releases. I'm editing them now.

**Comment by azat** [comment]
@ellzey all tags are available as releases automatically, no need to manually create a release for them, or I am missing something?

**Comment by ellzey** [comment]
@azat when you do a release, you tag it. The release versus tags is the same, one just references the sha hash, the other has details and release notes.

**Comment by ellzey** [comment]
going to delete all the alpha's that aren't the most recent.

**Comment by azat** [comment]
@ellzey maybe it is better to keep them (what if somebody refers to particular tag, I understand pros/cons bust still)? Just without releases.

**Comment by ellzey** [comment]
I think I can un-annotate the tags, and push them back up, and they wouldn't be a release, but the tag remains.... I think.
