### ISSUE TITLE
[BUG] Potential badness in evhttp 

### ISSUE THREAD

**Issue by ellzey** [libevent/libevent#313]
https://github.com/libevent/libevent/blob/master/http.c#L437-L439

or

```C
	/* Generate request line */
	method = evhttp_method(req->type);
	evbuffer_add_printf(bufferevent_get_output(evcon->bufev),
	    "%s %s HTTP/%d.%d\r\n",
	    method, req->uri, req->major, req->minor);
```

is bad, what if` evhttp_method` returns NULL, this would segfault. 

We might need to add a new flag to propagate this error.

The best solution is to use either one of the established `EVHTP_` flags for errors, or create a new flag. This means that every part of the chain needs to check for that flag before anything else.

**Comment by miniupnp** [comment]
no segfault here, but (null) printed : 
```
0000  f4 ca e5 45 5e 1a 00 1a 6b d2 d0 7b 08 00 45 00   ...E^...k..{..E.
0010  00 80 85 a6 40 00 40 06 1e 15 c0 a8 0a 6e c0 a8   ....@.@......n..
0020  0a fe ca 1d 16 2e 88 68 24 36 7b 4f 65 91 80 18   .......h$6{Oe...
0030  01 c9 97 2f 00 00 01 01 08 0a 00 4d a1 9a 1a 4e   .../.......M...N
0040  0e f1 28 6e 75 6c 6c 29 20 2f 64 65 73 63 2f 72   ..(null) /desc/r
0050  6f 6f 74 20 48 54 54 50 2f 31 2e 31 0d 0a 48 6f   oot HTTP/1.1..Ho
0060  73 74 3a 20 31 39 32 2e 31 36 38 2e 31 30 2e 32   st: 192.168.10.2
0070  35 34 3a 35 36 37 38 0d 0a 43 6f 6e 6e 65 63 74   54:5678..Connect
0080  69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 0d 0a         ion: close....
```

**Comment by miniupnp** [comment]
but of course it depends on the libc, evutil_vsnprintf() is called which calls vsnprintf() : 
https://github.com/libevent/libevent/blob/master/evutil.c#L1824

**Comment by miniupnp** [comment]
I think a check could be added in evhttp_make_header_request() :
`if (method == NULL) method = "INVALID";` as there is no way to return an error from there...

**Comment by ellzey** [comment]
stupid fix applied here https://github.com/libevent/libevent/commit/17cc6362239469638a4afc971314ab12ad4ea624
