### ISSUE TITLE
Errors in Static Build in VS12 + Win 7

### ISSUE THREAD

**Issue by homerocda** [libevent/libevent#314]
Static build of master branch is failing in Visual Studio 2013 under Windows 7 64-bit. Active build platform is Win32.

Libevent compiles with several warnings regarding linkage (e.g., `C4273: 'evbuffer_write' : inconsistent dll linkage`) and no tests or examples build at all due to linking errors (`LNK2019: unresolved external symbol __imp__bufferevent_get_output referenced in function _conn_writecb`).

The VS solution was generated from CMake 3.4.1 with benchmark, openssl and regression tests options disabled.

**Comment by azat** [comment]
> Static build of master branch is failing in Visual Studio 2013 under Windows 7 64-bit Active build platform is Win32

Hi,

Can you please test next version:
  $ git clone --branch win32-vs2013-static-build-fix git://github.com/azat/libevent.git

Or regular zip archive:
https://github.com/azat/libevent/archive/win32-vs2013-static-build-fix.zip

Thanks,
Azat.

**Comment by ellzey** [comment]
Just for the sake of saying it, there was, and still are lot's of issues of the cmake implementation. I have been working on it, there were lot's of misconceptions of where to use `#define` or `#cmakedefine`

So if anyone cares to know _why_....

Let's say you have this in your cmakelists.txt

```CMake
set(VERSION_MAJOR 1)
set (VERSION_MINOR 0)
```

and in the .in file you have

```C
#cmakedefine VERSION_MINOR @VERSION_MINOR@
```
will result in

```C
#undef VERSION_MINOR
```
`${VERSION_MINOR}`, the value of which is 0, is evaluated as false, thus undefined.

But if you use
```C
#define VERSION_MINOR @VERSION_MINOR@
```
you see what you want: 

`#define VERSION_MINOR 0`

Just sayin'

**Comment by ellzey** [comment]
So just make sure `set(EVENT__NEED_DLLIMPORT 1)` in the CMakeLists.txt is right.

**Comment by homerocda** [comment]
The fix solved the issue.

**Comment by azat** [comment]
> So just make sure `set(EVENT__NEED_DLLIMPORT 1)` in the CMakeLists.txt is right.

@ellzey
I know that cmake rules are fare from perfect.
But, are you against referenced patch?

**Comment by azat** [comment]
@ellzey thoughts?

**Comment by homerocda** [comment]
@azat I guess he should be fine with the patch, judging by "Anyway, yeah, it's being used correctly with the patch."

**Comment by azat** [comment]
Okay, picket to 49bd79047bc9aca3ca43fb79eac3901e7805c0df, @homerocda thanks!
