### ISSUE TITLE
Call event_reinit() from parent or from child?

### ISSUE THREAD

**Issue by dilyanpalauzov** [libevent/libevent#319]
The documentation of event_reinit() is unclear, whether the function shall be called after fork() form the child process, or from the parent process.  In particular it is unclear, whether the function shall be called at all, if the child process makes immediately after the fork execlp().

**Comment by azat** [comment]
On Wed, Jan 27, 2016 at 09:29:48AM -0800, dilyanpalauzov wrote:
> The documentation of event_reinit() is unclear, whether the function shall be called after fork() form the child process, or from the parent process  In particular it is unclear, whether the function shall be called at all, if the child process makes immediately after the fork execlp()

event_reinit(3) should be called from child OR parent, and you don't
need it if you run execve(2) just after fork(2)

You can also take a look at #307.

Thanks,
Azat.

**Comment by ellzey** [comment]
no response.
