### ISSUE TITLE
SleepConditionVariableCS, not SleepConditionVariable

### ISSUE THREAD

**Issue by nmathewson** [libevent/libevent#32]
There's some as-yet-unused windows code for condition variables that calls "LOAD(SleepConditionVariable)".  That's not right -- it needs to load SleepConditionVariableCS.

**Comment by ellzey** [comment]
Please elaborate.

**Comment by azat** [comment]
@nmathewson have this been fixed by 7e45739e?

**Comment by ellzey** [comment]
Closed due to inactivity.
