### ISSUE TITLE
Missing <windows.h> in tinytest_demo.c

### ISSUE THREAD

**Issue by gvanem** [libevent/libevent#325]
AFAICS, there is no `<windows.h>` in the compilation unit for `test/tinytest_demo.c`. 
This was the link-errors from [TDM-gcc](http://tdm-gcc.tdragon.net/):
```
tinytest_demo.c: In function 'test_timeout':
tinytest_demo.c:179:2: warning: implicit declaration of function 'Sleep' [-Wimplicit-function-declaration]
  Sleep(5000);
  ^
Warning: resolving _Sleep by linking to _Sleep@4
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
`_Sleep' referenced in section `.text' of MingW_obj/tinytest_demo.o: defined in discarded section `.text' of F:/MingW32/TDM-gcc/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/lib/../lib32/libkernel32.a(dgvms01140.o)
```

But this simple patch fixed that:
```
--- a/test/tinytest_demo.c 2016-02-15 20:44:31
+++ b/test/tinytest_demo.c 2016-02-15 23:03:05
@@ -36,7 +36,9 @@
 #include <string.h>
 #include <errno.h>
 #include <time.h>
-#ifndef _WIN32
+#ifdef _WIN32
+#include <windows.h>
+#else
 #include <unistd.h>
 #endif
```

How else is `<windows.h>` supposed to be included? What am I missing?

**Comment by azat** [comment]
@gvanem thanks for catching this, can you send this as a pull-request of as a patch?

**Comment by gvanem** [comment]
"*pull-request*"? The patch is above. Not so hard....

**Comment by azat** [comment]
@gvanem there are reasons for *pull-request* over *issue*
- it includes a patch, and I can just merge it
- we have build-bots (travis-ci/appveyor) that automatically runs over *pull-requests*, so we will know that there are no regressions

This time I picked you patch, thanks!
