### ISSUE TITLE
Attempting to install via brew is failing

### ISSUE THREAD

**Issue by jeff-phillips-18** [libevent/libevent#330]
Doing a 'brew install libevent' fails with:

==> Downloading https://downloads.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libevent"
Download failed: https://downloads.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz

**Comment by ellzey** [comment]
```ruby
class Libevent < Formula
  desc "Asynchronous event library"
  homepage "http://libevent.org"
  url "https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz"
  sha256 "71c2c49f0adadacfdbe6332a372c38cf9c8b7895bb73dabeaa53cdcc1d4e1fa3"
```

run ```brew update```. We moved away from SF & homebrew returns the right stuff.

optionally you may run `brew edit libevent`

* `brew edit libevent`.
* Change the `url` value with [this](https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz).
* write and quit
* brew install libevent

**Comment by jeff-phillips-18** [comment]
Thanks, that fixed it.

**Comment by bravekingzhang** [comment]
thanks you

**Comment by osktgui** [comment]
Thanks you
