### ISSUE TITLE
libevent evhttp cannot get http get request with '#' character

### ISSUE THREAD

**Issue by BrentHuang** [libevent/libevent#337]
my http get request is "http://127.0.0.1/?opt=1&data=a#b", but I get "/?opt=1&data=a" by evhttp_request_get_uri, you can see than things after '#' is mising.
Is there anything wrong or how to do it? 
thanks a lot~

**Comment by BrentHuang** [comment]
I found the reason is libcurl version. sorry~

**Comment by azat** [comment]
So I can close this? (Or you close it by yourself).

**Comment by BrentHuang** [comment]
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
is ok to send '#', 
curl 7.45.0 (x86_64-unknown-linux-gnu) libcurl/7.45.0 OpenSSL/1.0.1f zlib/1.2.8 is not.
