### ISSUE TITLE
evbuffer chunks are never expanded as of libevent 2.0.22

### ISSUE THREAD

**Issue by adamel** [libevent/libevent#340]
The lines 1803-1804 in commit 20d6d445 makes the if-statement always true, which I doubt was the intention. This part of the commit should either be reverted or fixed. The same fix needs to be applied to 2.1 master as well.

**Comment by ellzey** [comment]
Fixing CVE's always results in something else breaking.

**Comment by ellzey** [comment]
Fix dropping tonight.

**Comment by ellzey** [comment]
After looking at it for about a half hour, I have no idea what this logic was supposed to do. There is nothing here that is bound checking (which the patch was all about).

Will keep looking.

**Comment by ellzey** [comment]
@azat any thoughts on this? This doesn't look like any bounds checking here, or needs to be. Do you think we should just take out that last conditional that was introduced for that CVE?

**Comment by azat** [comment]
@ellzey actually that check is wrong AFAICS, in the references there are two patches, first one is a regression for overflows that fails now, and the second is a fix for it, please take a look.

(But yes the logic is not so simple).

**Comment by azat** [comment]
@adamel are you okay with the fix (latest attached commit -- a3f4ccd)?

Regards,
Azat.

**Comment by adamel** [comment]
Yes, looks fine to me.

**Comment by azat** [comment]
@adamel cool, thanks!
