### ISSUE TITLE
Mutex never unlocked on accept() error

### ISSUE THREAD

**Issue by lacombar** [libevent/libevent#341]
Some of our server has been triggering an error during accept(), resulting in the following log:

```
[warn] Error from accept() call
```

However, this code path does not release the lock, leading all subsequent operation on the listener to deadlock. The following change (untested) might provide a fix for this issue:

```
--- a/listener.c
+++ b/listener.c
@@ -439,10 +439,10 @@ listener_read_cb(evutil_socket_t fd, short what, void *p)
                UNLOCK(lev);
                errorcb(lev, user_data);
                LOCK(lev);
-               listener_decref_and_unlock(lev);
        } else {
                event_sock_warn(fd, "Error from accept() call");
        }
+       listener_decref_and_unlock(lev);
 }
```

**Comment by azat** [comment]
@lacombar thanks for details! Indeed you are right, but we don't need to decref, just unlock, I will push the fix ASAP

**Comment by azat** [comment]
@lacombar I've just pushed patch and a regression.Thanks again for the report!

**Comment by lacombar** [comment]
Attribution about the reporter of the issue would have been appreciated, but thanks to have fixed this.

**Comment by azat** [comment]
> Attribution about the reporter of the issue would have been appreciated, but thanks to have fixed this.

There is "Refs/Fixes: #341", but I will add
"Reported-by: @github-user-name" next time!

**Comment by lacombar** [comment]
Thanks.

Btw, why does this path does not need the decref but the one calling `errorcb()`  does ?

**Comment by azat** [comment]
> Btw, why does this path does not need the decref but the one calling `errorcb()`  does ?

Since AFAICS there is no ++refcnt for that branch, so we don't need to
decref it, otherwise we will mess up with refcnt accounting.

**Comment by lacombar** [comment]
if I'm not mistaken, there is no ++refcnt in the other branch of the conditional either, and `listener_decref_and_unlock(...)` is explicitly used.

**Comment by azat** [comment]
https://github.com/libevent/libevent/blob/master/listener.c#L435
```c
	if (lev->errorcb != NULL) {
		++lev->refcnt;
		errorcb = lev->errorcb;
		user_data = lev->user_data;
		UNLOCK(lev);
		errorcb(lev, user_data);
		LOCK(lev);
		listener_decref_and_unlock(lev);
	} else {
		event_sock_warn(fd, "Error from accept() call");
		UNLOCK(lev);
	}
```

There is `++lev->refcnt`

**Comment by lacombar** [comment]
True, then that decref make sense, my bad.

I was looking for some kind of `listerner_incref(lev)` and not open coding of the increment :-)
