### ISSUE TITLE
libevent depends on sys/queue.h which is not present on all systems

### ISSUE THREAD

**Issue by cac04** [libevent/libevent#343]
libevent uses `sys/queue.h` in most of its backends. This is not part of any standard. It is not part of an ISO C standard nor is it part of POSIX. Some version of that file is present on most BSDs and any system using the GNU glibc. However, it is not part of every libc implementation. Notably, it is not present on any Linux system that uses musl libc.

Now that the official Docker images are switching to a musl libc Linux distribution, there are more and more Linux systems around that do not have `sys/queue.h`.

From the [musl libc FAQ](http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_sys.2Fqueue.h_not_included_.3F):
> sys/queue.h is a full library implemented in a header file, and there's no
> reason for it to be part of libc; the file is completely self-contained and
> independent. musl aims not to have code/significant, copyrightable content
> in public header files (i.e. significant content that's not straight interface definitions).

For this reason, logrotate [now includes its own copy of queue.h](https://github.com/logrotate/logrotate/commit/0aa8958a130a0e1459a820e64c566cc2cff9c3de). Is there any chance libevent could do the same?

This would also simplify `event-internal.h`, which already includes implementations of some macros that might be missing from `sys/queue.h`. Since `sys/queue.h` is not part of any standard, you can't be sure what you'll get.

**Comment by ellzey** [comment]
https://github.com/libevent/libevent/tree/master/compat/sys

**Comment by cac04** [comment]
Ah, it's not your fault at all then :)

I came across this through the build of `libevent` bundled with Mozilla. Their build system does not seem to include the `compat` directory on the include path.

It looks like your build just relies on the `compat/sys/queue.h` having the same include guard as the system's `sys/queue.h` - is that right?

`$ac_cv_header_sys_queue_h` is used to trigger a test for `TAILQ_FOREACH` but doesn't seem to affect the include path used.

I see a test for `sys/queue/h` in `CMakeLists.txt` but the result doesn't seem to be used anywhere. (Shouldn't the test for `TAILQ_FOREACH` be conditional on that, like in the `configure` script?)

**Comment by cac04** [comment]
For reference, here's the relevant bug for Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1261567

**Comment by ellzey** [comment]
Cool, can't you do ```CFLAGS="-I/path/to/libevent/compat" ./configure```?

**Comment by cac04** [comment]
I've attached a patch to that Mozilla bug which fixes it. It's just a case of adding `compat` to the list of include directories in the `mozbuild` file. I don't think any change to `libevent` is needed at all.

**Comment by ellzey** [comment]
Closing, seems as if this was fixed.
