### ISSUE TITLE
bufferevent_socket_new Memory leak  .. libevent2.1.5

### ISSUE THREAD

**Issue by yangmin26** [libevent/libevent#344]
struct bufferevent *bufev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE）;
.......
bufferevent_free(bufev); //Memory leak ... Not free the memory.

bufferevent_free. No function to implement the free memory
void
bufferevent_free(struct bufferevent *bufev)
{
BEV_LOCK(bufev);
bufferevent_setcb(bufev, NULL, NULL, NULL, NULL);
bufferevent_cancel_all_(bufev);
bufferevent_decref_and_unlock_(bufev);
}
mm_free????

**Comment by ellzey** [comment]
Never seen this before:
----------------

Do you hold a reference to the bev? 

If not, are you able to gdb it and check the reference count (e.g., `break bufferevent_free` and once you hit the breakpoint -  `print *bufev`. Other than that, maybe valgrind would be of help.
