### ISSUE TITLE
[RFC] Support sock errors even if read / write is disabled.

### ISSUE THREAD

**Issue by errzey** [libevent/libevent#345]
Been on my back-burner for a while. 

The idea is to allow a user to turn off both read and write on a fd, but still have the ability to get socket error conditions.

This is kqueue and epoll specific, but useful still.

``` C
/* kqueue */
EV_SET(&event, infd, EVFILT_READ, EV_ADD|EV_EOF, NOTE_LOWAT, INTMAX_MAX, NULL);
```

This waits for `INTMAX_MAX` bytes before triggering the event.

For epoll, we should look into `EPOLLRDHUP` if it exists.

**Comment by ellzey** [comment]
See: https://github.com/libevent/libevent/issues/345 too

**Comment by azat** [comment]
Close in favor on #1038
