### ISSUE TITLE
Make fails: bufferevent_openssl.c error: dereferencing pointer to incomplete type 

### ISSUE THREAD

**Issue by sanket28** [libevent/libevent#346]
I'm trying to build libevent 2.0.22 and when I run make it fails. I have attached the output of both ./configure and make
[libevent_make.txt](https://github.com/libevent/libevent/files/207471/libevent_make.txt)

**Comment by azat** [comment]
On Wed, Apr 06, 2016 at 03:48:45PM -0700, Sanket Deshpande wrote:
> I'm trying to build libevent 2.0.22 and when I run make it fails. I have attached the output of both ./configure and make
> [libevent_make.txt](https://github.com/libevent/libevent/files/207471/libevent_make.txt)

Seems you are on debian, can you please post next:
$ dpkg -l libssl*

(P.S. I hope that you are using libssl from repo).

**Comment by sanket28** [comment]
Here you go:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                          Version             Architecture        Description
+++-=============================-===================-===================-================================================================
ii  libssl-dev:amd64              1.0.1k-3+deb8u4     amd64               Secure Sockets Layer toolkit - development files
ii  libssl-doc                    1.0.1k-3+deb8u4     all                 Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64             1.0.1k-3+deb8u4     amd64               Secure Sockets Layer toolkit - shared libraries

```

**Comment by azat** [comment]
On Wed, Apr 06, 2016 at 03:48:45PM -0700, Sanket Deshpande wrote:
> I'm trying to build libevent 2.0.22 and when I run make it fails. I have attached the output of both ./configure and make
> [libevent_make.txt](https://github.com/libevent/libevent/files/207471/libevent_make.txt)

Do you have '#include <openssl/bio.h>' in you bufferevent_openssl.c?
And can you post <openssl/bio.h> in this case?

**Comment by sanket28** [comment]
It worked! I had the 1.1.0 version of openssl installed. Removed that and tried to build again and it worked!
