### ISSUE TITLE
No stable release since 2.0.22?

### ISSUE THREAD

**Issue by david-holonet** [libevent/libevent#348]
And which version can we use in production?

**Comment by azat** [comment]
@david-holonet are you interesting in *2.0* only?

**Comment by azat** [comment]
Refs: #285

**Comment by david-holonet** [comment]
What I want is the newest stable one, not only 2.0.
Thanks!
No release for a long time from last stable release.

**Comment by ellzey** [comment]
Let me work with azat who has been a critical asset during my absence; I have some catching up to do.

**Comment by gpaulsen** [comment]
IBM is interested in a new stable libevent also.
