### ISSUE TITLE
The function 'evbuffer_prepend' in libevent/buffer.c have a bug

### ISSUE THREAD

**Issue by luoming1224** [libevent/libevent#349]
In the function 'evbuffer_prepend' of libevent/buffer.c have a bug, the code of the line 1884-1886 is
```
memcpy(tmp->buffer + tmp->misalign, data, datlen);
buf->total_len += datlen;
buf->n_add_for_cb += (size_t)chain->misalign;
```

The code of the line 1886 is error, the right code is 
```
buf->n_add_for_cb += datlen;
````

In the situation, the first chain can fit some of the data, `chain->misalign` identically equal to zero. so the 
code (`buf->n_add_for_cb += (size_t)chain->misalign;`) is error.

**Comment by ellzey** [comment]
What version?

**Comment by azat** [comment]
Looks like latest from git

**Comment by azat** [comment]
@luoming1224 thanks for pointing this out! You are right. I'm going to finish some testing (and a regression test) after this I'm going to push you fix along with test.
