### ISSUE TITLE
ERR_clear_error missing, causing random problems on iOS

### ISSUE THREAD

**Issue by CapSel** [libevent/libevent#350]
In bufferevent_openssl.c, right before SSL_read, a function ERR_clear_error(); should be called to clear any prevoius error.
Without this there is a randomly occuring problem in https client connections on iOS, and possibly others.
HTTPS connections are closed before entire content is received. Number of bytes sent is random and the error from openssl is:
 "error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table"

**Comment by azat** [comment]
Hi @CapSel, thanks for report, do you have a reproducer?

**Comment by CapSel** [comment]
No, sorry. I could not narrow it. It seems random and short connections are ok. Adding this function stopped random errors. It seems that some consider this problem as OpenSSL problem.

--
Kacper Kopczyński

**Comment by azat** [comment]
Anyway, @CapSel thanks for the report! I've just pushed fix to the upstream (doh global stack for errors), if this will not fix the issue for you, please go ahead and reopen the issue.
