### ISSUE TITLE
libevent 2.0.22-stable test failures on 64-bit Solaris

### ISSUE THREAD

**Issue by syehk** [libevent/libevent#352]
After building libevent 2.0.22 stable, I'm seeing the multiple instances of the following test failure for 64-bit Solaris. 
```
util/integers: 
  FAIL regress_util.c:727: assert(ssize < 0)
  [integers FAILED]
```

I noticed Windows had 64-bit guards in event-config.h. If I add a _LP64 guard in event-config.h, these failures go away. 
```
/* The size of `size_t', as computed by sizeof. */
#ifdef _LP64
#define _EVENT_SIZEOF_SIZE_T 8
#else
#define _EVENT_SIZEOF_SIZE_T 4
#endif

/* The size of `void *', as computed by sizeof. */
#ifdef _LP64
#define _EVENT_SIZEOF_VOID_P 8
#else
#define _EVENT_SIZEOF_VOID_P 4
#endif
```

I've noticed other Linux distros don't seem to run into this issue, which made me curious as to whether I'm missing something. Perhaps a modification to the generation script for event-config.h is needed?

**Comment by azat** [comment]
On Wed, May 04, 2016 at 12:44:25PM -0700, syehk wrote:
> After building libevent 2.0.22 stable, I'm seeing the multiple instances of the following test failure for 64-bit Solaris. 
> ```
> util/integers: 
>   FAIL regress_util.c:727: assert(ssize < 0)
>   [integers FAILED]
> ```

Hi,

I've just checked this and I can't reproduce this with *5.11*.

I'm not the fan of solaris, but can you send me output of next commands:
- uname -a
- isainfo -kv
- psrinfo -pv

- gcc -v -dM -E -xc /dev/null | fgrep SIZE_T

- file /sbin/init
- file /path/to/libevent/test/.libs/regress

> 
> I noticed Windows had 64-bit guards in event-config.h. If I add a _LP64 guard in event-config.h, these failures go away. 
> ```
> /* The size of `size_t', as computed by sizeof. */
> #ifdef _LP64
> #define _EVENT_SIZEOF_SIZE_T 8
> #else
> #define _EVENT_SIZEOF_SIZE_T 4
> #endif
> 
> /* The size of `void *', as computed by sizeof. */
> #ifdef _LP64
> #define _EVENT_SIZEOF_VOID_P 8
> #else
> #define _EVENT_SIZEOF_VOID_P 4
> #endif
> ```
> 
> I've noticed other Linux distros don't seem to run into this issue, which made me curious as to whether I'm missing something. Perhaps a modification to the generation script for event-config.h is needed?

**Comment by syehk** [comment]
uname -a: 
`SunOS strax 5.12 s12_97 i86pc i386 i86pc`

isainfo -kv:
`64-bit amd64 kernel modules`

psrinfo -pv:
`The physical processor has 12 cores and 24 virtual processors (0-11,24-35)
  The core has 2 virtual processors (0,24)
  The core has 2 virtual processors (1,25)
  The core has 2 virtual processors (2,26)
  The core has 2 virtual processors (3,27)
  The core has 2 virtual processors (4,28)
  The core has 2 virtual processors (5,29)
  The core has 2 virtual processors (6,30)
  The core has 2 virtual processors (7,31)
  The core has 2 virtual processors (8,32)
  The core has 2 virtual processors (9,33)
  The core has 2 virtual processors (10,34)
  The core has 2 virtual processors (11,35)
    x86 (GenuineIntel 306E4 family 6 model 62 step 4 clock 2693 MHz)
      Intel(r) Xeon(r) CPU E5-2697 v2 @ 2.70GHz
The physical processor has 12 cores and 24 virtual processors (12-23,36-47)
  The core has 2 virtual processors (12,36)
  The core has 2 virtual processors (13,37)
  The core has 2 virtual processors (14,38)
  The core has 2 virtual processors (15,39)
  The core has 2 virtual processors (16,40)
  The core has 2 virtual processors (17,41)
  The core has 2 virtual processors (18,42)
  The core has 2 virtual processors (19,43)
  The core has 2 virtual processors (20,44)
  The core has 2 virtual processors (21,45)
  The core has 2 virtual processors (22,46)
  The core has 2 virtual processors (23,47)
    x86 (GenuineIntel 306E4 family 6 model 62 step 4 clock 2693 MHz)
      Intel(r) Xeon(r) CPU E5-2697 v2 @ 2.70GHz`

gcc -v -dM -E -xc /dev/null | fgrep SIZE_T:
`Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-pc-solaris2.12
Configured with: /builds/hudson/workspace/nightly-s12/build/i386-s12/components/gcc53/gcc-5.3.0/configure --prefix=/usr/gcc/5.3 --mandir=/usr/gcc/5.3/share/man --bindir=/usr/gcc/5.3/bin --sbindir=/usr/gcc/5.3/sbin --libdir=/usr/gcc/5.3/lib --infodir=/usr/gcc/5.3/share/info --libexecdir=/usr/gcc/5.3/lib --enable-languages=c,c++,fortran,objc --enable-shared --enable-initfini-array --disable-rpath --with-system-zlib --with-build-config=no --with-gmp-include=/usr/include/gmp --with-mpfr-include=/usr/include/mpfr --without-gnu-ld --with-ld=/usr/bin/ld --with-gnu-as --with-as=/usr/gnu/bin/as 'BOOT_CFLAGS=-g -O2' x86_64-pc-solaris2.12
Thread model: posix
gcc version 5.3.0 (GCC) 
COLLECT_GCC_OPTIONS='-v' '-dM' '-E' '-mtune=generic' '-march=x86-64'
 /usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/cc1 -E -quiet -v /dev/null -mtune=generic -march=x86-64 -dM
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/../../../../x86_64-pc-solaris2.12/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/include
 /usr/gcc/5.3/include
 /usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/include-fixed
 /usr/include
End of search list.
#define __SIZEOF_SIZE_T__ 8
#define __SIZE_TYPE__ long unsigned int
COMPILER_PATH=/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/:/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/:/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/:/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/:/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/:/usr/ccs/bin/
LIBRARY_PATH=/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/:/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/../../../amd64/:/lib/amd64/:/usr/lib/amd64/:/usr/gcc/5.3/lib/gcc/x86_64-pc-solaris2.12/5.3.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-dM' '-E' '-mtune=generic' '-march=x86-64'`

file /sbin/init:
`/sbin/init:   ELF 64-bit LSB dynamic lib AMD64 Version 1 [SSE2 SSE], position-independent executable, dynamically linked, not stripped, no debugging information available`

file /path/to/libevent/test/.libs/regress:
`test/.libs/regress:   ELF 32-bit LSB executable 80386 Version 1 [SSE2 SSE], dynamically linked, not stripped`

**Comment by azat** [comment]
On Tue, May 10, 2016 at 10:04:11AM -0700, syehk wrote:
> gcc -v -dM -E -xc /dev/null | fgrep SIZE_T:
...
> #define __SIZEOF_SIZE_T__ 8
> #define __SIZE_TYPE__ long unsigned int

Okay, finally I reproduced this, after upgrading gcc to 5.3.

Indeed with gcc 5.3 the default type for size_t is 8, while with 4.8 it
was 4, and only with -m64 it was 8.

**Comment by azat** [comment]
On Wed, May 11, 2016 at 02:33:34PM +0300, Azat Khuzhin wrote:
> On Tue, May 10, 2016 at 10:04:11AM -0700, syehk wrote:
> > gcc -v -dM -E -xc /dev/null | fgrep SIZE_T:
> ...
> > #define __SIZEOF_SIZE_T__ 8
> > #define __SIZE_TYPE__ long unsigned int
> 
> Okay, finally I reproduced this, after upgrading gcc to 5.3.
> 
> Indeed with gcc 5.3 the default type for size_t is 8, while with 4.8 it
> was 4, and only with -m64 it was 8.

And this happens because of stalled autoconf cache (since with gcc 4.8
sizeof(size_t) is 4, and with gcc 5.3 sizeof(size_t) is 8, and
<event-config.h> wasn't regenerated when you updated you gcc, while
binaries did compile again.

IOW simple:
  gmake clean; ./autogen.sh; gmake -j
Must fix the issue:
  test/regress --verbose util/integers

Does it work for you?

Thanks,
Azat.

**Comment by syehk** [comment]
Yes, this seems to have resolved the issue. Thanks for your help. :)
