### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [libevent/libevent#353]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [EVENT_LOG_…](https://github.com/libevent/libevent/blob/f2645f80c135b44a9e82f809662da4bef93e8726/include/event2/event.h#L703)
* [HTTP_…](https://github.com/libevent/libevent/blob/9fde5189df2722bf58041f03a9d0b69c87dffa8b/include/event2/http.h#L55)

**Comment by azat** [comment]
On Mon, May 09, 2016 at 03:35:30AM -0700, Markus Elfring wrote:
> Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
> * [EVENT_LOG_…](https://github.com/libevent/libevent/blob/f2645f80c135b44a9e82f809662da4bef93e8726/include/event2/event.h#L703)
> * [HTTP_…](https://github.com/libevent/libevent/blob/9fde5189df2722bf58041f03a9d0b69c87dffa8b/include/event2/http.h#L55)

Basically it is a good thing, but not a major one.

**Comment by azat** [comment]
@elfring but feel free to send a patch!

**Comment by ellzey** [comment]
Closing; enums are great for catching defaults, but we would have to change all the other aliases too.

**Comment by ellzey** [comment]
Closing this for now, we can investigate this in the future.
