### ISSUE TITLE
Compiling 'test/regress_http.c' on Windows fails

### ISSUE THREAD

**Issue by nntrab** [libevent/libevent#361]
Trying to compile the latest version of test/regress_http.c using Visual Studio 2015 results in the following compile errors:

`regress_http.c(1428): error C2059: syntax error: ':'`
`regress_http.c(1477): error C2059: syntax error: ':'`
`regress_http.c(1497): error C2059: syntax error: ':'`

The lines in question appear to be using a gcc extension to the conditional operator that permits the middle expression to be omitted. The code appears to have been introduced in commit [334340d](https://github.com/libevent/libevent/commit/334340da51dcfe51bc6cc049983a0e6eb4c0ed0f#diff-924026dc3880d731886271e852bbd55a).

**Comment by azat** [comment]
@nntrab thanks for reporting this.

I will try to add vs2015 builds into appveryor (to avoid regressions) in the nearest feature and after this will submit a patch for this issue.
