### ISSUE TITLE
Data stuck in input buffer of bufferevent filter's underlying

### ISSUE THREAD

**Issue by EMPanisset** [libevent/libevent#362]
Suppose we have bufferevent filter attached to bufferevent socket.
Read high watermark for bufferevent filter is configured to 4096 bytes.
Socket receives 4343 bytes. Due to watermark, 4096 bytes are transferred from socket input buffer to filter input buffer and 247 bytes are left in bufferevent socket. 
Suppose that no more data is received through socket.

At this point 247 bytes will sit forever in input buffer of bufferevent socket.
The patch attached solves this issue registering read callback to filter's input buffer if it reaches its read high water mark and data was left in corresponding underlying's input buffer.

This read callback calls filter process input function as soon as filter input buffer falls below its read high watermark and there still is data left in underlying input buffer. Callback is deregistered as soon as filter input buffer falls below its read high watermark.

I tested this solution and it works fine to me, no storm of events or another side effects.

Please check this issue and proposed solution.

PS: Updated patch with removal of callbacks in filter's destruct function.

Thanks,
Eduardo Panisset
[bufferevent_filter-data-stuck-input-underlying.txt](https://github.com/libevent/libevent/files/313557/bufferevent_filter-data-stuck-input-underlying.txt)

.

**Comment by azat** [comment]
On Sat, Jun 11, 2016 at 03:13:09AM -0700, Eduardo Moura Panisset wrote:
> [bufferevent_filter-data-stuck-input-underlying.txt](https://github.com/libevent/libevent/files/310181/bufferevent_filter-data-stuck-input-underlying.txt)

Hi,

Thanks for the patch and details, at first glance look good, but can you
please:
- convert it to pull request
- add unit test?

Regards,
Azat.

**Comment by azat** [comment]
Closing this one in favor to #365
