### ISSUE TITLE
vs2015 builds on appveyor

### ISSUE THREAD

**Issue by azat** [libevent/libevent#364]
So right now we have same matrix for appveyor like we have for travis-ci.

Refs: #361

**Comment by azat** [comment]
`git@github.com:azat/libevent.git appveyor-cmake`

**Comment by azat** [comment]
https://ci.appveyor.com/project/azat/libevent/build/2.1.5.5

**Comment by azat** [comment]
@ellzey thoughts? (But autotools may not work right now, but I'm working on it. And yes it takes a lot of time, because it is not so good with parallel builds there -- /me in doubt)

**Comment by azat** [comment]
https://ci.appveyor.com/project/azat/libevent/history

**Comment by ellzey** [comment]
autotools has been funky on with windows for a while now; the best way to do windows is via cmake. I pay for the appveyor service, so the build should be a higher priority with better hardware.

I'm guessing most of these long-running builds are mostly crunching on unit tests.

**Comment by azat** [comment]
For sure `cmake` is better, but it will be nice to have both, to avoid compilation-errors regressions.

**Comment by azat** [comment]
And finally [working build](https://ci.appveyor.com/project/azat/libevent/build/2.1.5.66)

**Comment by azat** [comment]
@ellzey I've finished this one, do you have any objections from merging it?
