### ISSUE TITLE
when I compile my code, I get this error:field ‘ev1’ has incomplete type

### ISSUE THREAD

**Issue by endfighting** [libevent/libevent#369]
```cpp
//demo.c
#include <event2/event.h>
#include <stdio.h>
struct sock_pair{
    struct event ev1;
    struct event ev2;
};
int main() {
    printf("%ld", sizeof(struct sock_pair));
    return 0;
}
```
when I compile my source code with "gcc -o main demo.c -levent", I got this:
demo.c:4:18: error: field ‘ev1’ has incomplete type
     struct event ev1;
                  ^
demo.c:5:18: error: field ‘ev2’ has incomplete type
     struct event ev2;

Then I simplify it
```cpp
#include <event2/event.h>
#include <stdio.h>
int main() {
    printf("%ld", sizeof(struct event));
    return 0;
}
```
I got this:
demo.c: In function ‘main’:
demo.c:4:28: error: invalid application of ‘sizeof’ to incomplete type ‘struct event’
     printf("%ld\n", sizeof(struct event));
Somtimes, I certainly need to get the size of the structs, so how do I solve this problem;
That's all, I hope someone can help me.

**Comment by ellzey** [comment]
struct event is no longer exposed, this is legacy. Please use `struct event * ev1 = event_new(..);` instead.

Legacy apps can still `#include <event2/event_struct.h>` for backwards compatibility, but do not assume this will be a valid (matching the internal `struct event;`) for the future.

**Comment by endfighting** [comment]
Ok, I think I got it, think you ellzey.
