### ISSUE TITLE
Stable 2.0.22 - Android with r11 and r12 NDK - missing arc4random_addrandom

### ISSUE THREAD

**Issue by smarek** [libevent/libevent#370]
Hi,

i had to solve the issue, where arc4random_addrandom is not checked to be available, when building https://github.com/smarek/android-unbound-dns for Android with NDK versions r11 and r12 (this function was effectivelly never implemented, but was falsely visible as available in r10 and lower)

Would you consider adding this in the 2.0.23 stable, if it will be ever released?
Original patch file can be found here: https://github.com/smarek/android-unbound-dns/blob/master/libevent-2.0.22-stable.patch

``` diff
diff --git a/configure.ac b/configure.ac
index d42edd8..f66af10 100644
--- a/configure.ac
+++ b/configure.ac
@@ -290,7 +290,7 @@ AC_HEADER_TIME

 dnl Checks for library functions.
 AC_CHECK_FUNCS([gettimeofday vasprintf fcntl clock_gettime strtok_r strsep])
-AC_CHECK_FUNCS([getnameinfo strlcpy inet_ntop inet_pton signal sigaction strtoll inet_aton pipe eventfd sendfile mmap splice arc4random arc4random_buf issetugid geteuid getegid getprotobynumber setenv unsetenv putenv sysctl])
+AC_CHECK_FUNCS([getnameinfo strlcpy inet_ntop inet_pton signal sigaction strtoll inet_aton pipe eventfd sendfile mmap splice arc4random arc4random_addrandom arc4random_buf issetugid geteuid getegid getprotobynumber setenv unsetenv putenv sysctl])
 AC_CHECK_FUNCS([umask])

 AC_CACHE_CHECK(
diff --git a/evutil_rand.c b/evutil_rand.c
index 284341c..255e940 100644
--- a/evutil_rand.c
+++ b/evutil_rand.c
@@ -171,10 +171,11 @@ evutil_secure_rng_get_bytes(void *buf, size_t n)
    ev_arc4random_buf(buf, n);
 }

+#ifdef HAVE_ARC4RANDOM_ADDRANDOM
 void
 evutil_secure_rng_add_bytes(const char *buf, size_t n)
 {
    arc4random_addrandom((unsigned char*)buf,
        n>(size_t)INT_MAX ? INT_MAX : (int)n);
 }
-
+#endif
diff --git a/include/event2/util.h b/include/event2/util.h
index dde9113..e55c8b4 100644
--- a/include/event2/util.h
+++ b/include/event2/util.h
@@ -690,6 +690,7 @@ int evutil_secure_rng_init(void);
  */
 int evutil_secure_rng_set_urandom_device_file(char *fname);

+#ifdef HAVE_ARC4RANDOM_ADDRANDOM
 /** Seed the random number generator with extra random bytes.

     You should almost never need to call this function; it should be
@@ -705,6 +706,7 @@ int evutil_secure_rng_set_urandom_device_file(char *fname);
     @param datlen the number of bytes to read from datlen
  */
 void evutil_secure_rng_add_bytes(const char *dat, size_t datlen);
+#endif

 #ifdef __cplusplus
 }
```

**Comment by ellzey** [comment]
I will look over this tonight.

**Comment by hepengfei** [comment]
This solve problem for me. Thanks @smarek

**Comment by rvandermeulen** [comment]
This is something we have to workaround in Mozilla code too. Would be great if this could be included in 2.1.x eventually.

**Comment by azat** [comment]
Refs: android-ndk/ndk#48

**Comment by azat** [comment]
Can somebody post here detailed reports? For [latest libevent](26f416c1a5b9b39782e89b9670c796fa182bc011)

And in the mean time I will try to create env with android ndk to test it by myself.

**Comment by azat** [comment]
@smarek I fixed this (you can take a look into attached patch), it a little bit differs from your patch:
- cmake support
- arc4-less systems (linux), implicit decl warning

**Comment by azat** [comment]
@smarek can you try 2.1?

**Comment by azat** [comment]
From:

    https://github.com:azat/libevent cmake-configure-fixes

**Comment by smarek** [comment]
Looks cool, will ressurrect the project over the upcoming weekend, and give out test results. Thank you @azat

**Comment by azat** [comment]
@smarek any news?

**Comment by smarek** [comment]
hey @azat , yup, I've tried, just pushed my prepared update to https://github.com/smarek/android-unbound-dns/tree/development

What is not working currently, there is no way to use pre-compiled openssl (1.0.2k currently) with libevent, as configure accepts only "--enable-openssl / --disable-openssl" and not something like "--with-ssl /absolute/path/to/openssl-1.0.2k/build/"

Could you advise? Thank you!

**Comment by azat** [comment]
@smarek take a look at [this](https://github.com/libevent/libevent/issues/401#issuecomment-251006022)

**Comment by smarek** [comment]
Ok, that fixed the issue, with no patch applied, libevent compiled correctly against Android sysroot
Please see https://github.com/smarek/android-unbound-dns/commit/2f849e41ad4cf0f82363e76daed4496769c556c4

I consider this ticket to be done. Close if you will.

**Comment by azat** [comment]
Great, thanks for checking it!
