### ISSUE TITLE
core dumped in evhttp_uri_get_query() after feeding evhttp_uri_parse() a string containing blank chars

### ISSUE THREAD

**Issue by lanyuliuyun** [libevent/libevent#374]
It's libevent-2.0.22-stable. 
the following code piece will cause a segment fault in evhttp_uri_get_query()
```C
const char *url = "http://192.168.1.124/file.png  ";
struct evhttp_uri* uri = evhttp_uri_parse(url);
const char *query = evhttp_uri_get_query(uri);
evhttp_uri_free(uri);
```

In fact, the fatal blank chars can be placed in the query part like the following
```C
const char *url = "http://192.168.1.124/file.png?  string"
const char *url = "http://192.168.1.124/file.png?string  "
```

And my compiler and OS is
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
Linux cloud2 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by azat** [comment]
On Thu, Jul 07, 2016 at 02:25:08AM -0700, lanyuliuyun wrote:
> It's libevent-2.0.22-stable. 
> the following code piece will cause a segment fault in evhttp_uri_get_query()
> ```C
> const char *url = "http://192.168.1.124/file.png  ";
> struct evhttp_uri* uri = evhttp_uri_parse(url);
> const char *query = evhttp_uri_get_query(uri);
> evhttp_uri_free(uri);
> ```

Hi,

I guess that this is because evhttp_uri_parse() return's NULL, for such
urls (the one that doesn't properly encoded) you can use
EVHTTP_URI_NONCONFORMANT flag for evhttp_uri_parse_with_flags().

Regards,
Azat.

**Comment by lanyuliuyun** [comment]
@azat Thanks for your answer ! 
evhttp_uri_parse() does return NULL with that bad url and the segment fault is caused by the misuse of evhttp_uri_parse().
