### ISSUE TITLE
input and output buffers

### ISSUE THREAD

**Issue by fade2black** [libevent/libevent#375]
I posted this question to stackoverflow 15 days ago but got no answer so far. So, sorry if this is not the right place to as such questions.

I am trying to figure out the design logic behind the libevent. The only source about this library is this book. In particular my question is about bufferevents. The documentation says that

Every bufferevent has an input buffer and an output buffer. These are of type "struct evbuffer". When you have data to write on a bufferevent, you add it to the output buffer; when a bufferevent has data for you to read, you drain it from the input buffer.

What it says, in fact, is quite clear to me, but rather abstract.

Q1: Does bufferevent have some kind of intermidiate (between my app and actual socket/transport) buffer (evbuffer in terms of libevent) maintained by the library? If yes,

Q2: When I want to write to a socket I call bufferevent_write which writes to the evbuffer without the blocking. So when data is written to underlying socket my write_callback is invoked indicating that some data is sent to a peer through the socket. Thus I just push some data and don't bother about being blocked, and just wait for being notified about sent data or doing other work (dealing with another bufferevent for example). In other words, evbuffer is between me and the socket for reading from and writing to. Am I right?

**Comment by azat** [comment]
q1: it doesn't have any other intermediate buffer, then output buffer. IOW the buffer where you writes your data is intermediate buffer, it will drain from it when it will write part of data to the underlying socket.
q2: yep

**Comment by azat** [comment]
As for SO, personally I don't have enough time to monitor it

**Comment by azat** [comment]
@fade2black closing this for now, if you will need more info on this you can always reopen it.
