### ISSUE TITLE
make verify fails with some dns test in 2.0.21

### ISSUE THREAD

**Issue by shakaran** [libevent/libevent#38]
Running make verify I get this in a Centos 6.3 machine:

<pre>
Running tests:
EVPORT
Skipping test
KQUEUE
Skipping test
EPOLL
 test-eof: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 regress: [Error code 3] 
  FAIL regress_dns.c:188: assert(dns_ok == DNS_PTR): 0 vs 2dns/gethostbyaddr: 
  FAIL regress_main.c:332: Legacy unit test failed
  [gethostbyaddr FAILED]
[Error code 3] 
  FAIL regress_dns.c:213: assert(dns_ok == DNS_PTR): 0 vs 2dns/resolve_reverse: 
  [resolve_reverse FAILED]

  FAIL regress_dns.c:1147: assert(n_dns == 2): 4 vs 2dns/bufferevent_connect_hostname: 
  [bufferevent_connect_hostname FAILED]
3/179 TESTS FAILED. (0 skipped)
FAILED
EPOLL (changelist)
 test-eof: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 regress: [Error code 3] 
  FAIL regress_dns.c:188: assert(dns_ok == DNS_PTR): 0 vs 2dns/gethostbyaddr: 
  FAIL regress_main.c:332: Legacy unit test failed
  [gethostbyaddr FAILED]
[Error code 3] 
  FAIL regress_dns.c:213: assert(dns_ok == DNS_PTR): 0 vs 2dns/resolve_reverse: 
  [resolve_reverse FAILED]

  FAIL regress_dns.c:1147: assert(n_dns == 2): 4 vs 2dns/bufferevent_connect_hostname: 
  [bufferevent_connect_hostname FAILED]
3/179 TESTS FAILED. (0 skipped)
FAILED
DEVPOLL
Skipping test
POLL
 test-eof: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 regress: [Error code 3] 
  FAIL regress_dns.c:188: assert(dns_ok == DNS_PTR): 0 vs 2dns/gethostbyaddr: 
  FAIL regress_main.c:332: Legacy unit test failed
  [gethostbyaddr FAILED]
[Error code 3] 
  FAIL regress_dns.c:213: assert(dns_ok == DNS_PTR): 0 vs 2dns/resolve_reverse: 
  [resolve_reverse FAILED]

  FAIL regress_dns.c:1147: assert(n_dns == 2): 4 vs 2dns/bufferevent_connect_hostname: 
  [bufferevent_connect_hostname FAILED]
3/179 TESTS FAILED. (0 skipped)
FAILED
SELECT
 test-eof: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 regress: [Error code 3] 
  FAIL regress_dns.c:188: assert(dns_ok == DNS_PTR): 0 vs 2dns/gethostbyaddr: 
  FAIL regress_main.c:332: Legacy unit test failed
  [gethostbyaddr FAILED]
[Error code 3] 
  FAIL regress_dns.c:213: assert(dns_ok == DNS_PTR): 0 vs 2dns/resolve_reverse: 
  [resolve_reverse FAILED]

  FAIL regress_dns.c:1147: assert(n_dns == 2): 4 vs 2dns/bufferevent_connect_hostname: 
  [bufferevent_connect_hostname FAILED]
3/179 TESTS FAILED. (0 skipped)
FAILED
WIN32
Skipping test
FAIL: ../test/test.sh
==================
1 of 1 test failed
</pre>

**Comment by benlaurie** [comment]
You say this is disabled, yet I still see the same failure in 2.0.22.

**Comment by ellzey** [comment]
One of the problems I noticed with anything client-dns test related is that we rely on our systems to be online and have a proper recursive setup somewhere.

**Comment by ellzey** [comment]
@benlaurie I think he's talking about in his project.

**Comment by azat** [comment]
AFAIU **2.1** doesn't have this issue, can we close this or we want this fixed in **2.0**?

**Comment by azat** [comment]
Closing this one, if somebody thinks that this must be fixed in *2.0*, please reopen!
