### ISSUE TITLE
What's the minimum time interval for evtimer_add()?

### ISSUE THREAD

**Issue by tangwuquan** [libevent/libevent#381]
if I set the second parameter of evtimer_add() as:
struct timeval tv1 = {0, 1};
Can the timer be triggered after 1/1000000 second?

**Comment by azat** [comment]
On Tue, Jul 19, 2016 at 08:28:55PM -0700, tangwuquan wrote:
> if I set the second parameter of evtimer_add() as:
> struct timeval tv1 = {0, 1};
> Can the timer be triggered after 1/1000000 second?

Yep, but note that it can vary a little.

**Comment by tangwuquan** [comment]
thanks
