### ISSUE TITLE
µchex warnings: some pointers are null checked after they have already been dereferenced

### ISSUE THREAD

**Issue by cpeterso** [libevent/libevent#382]
These warnings in libevent were reported by µchex, a static analysis tool described in the paper ["How to Build Static Checking Systems Using Orders of Magnitude Less Code"](https://web.stanford.edu/~mlfbrown/paper.pdf) (Fraser Brown, Andres Nötzli, Dawson Engler):

That these pointers are null checked suggests null is a valid value and µchex warns that the pointers are dereferenced _before_ the null checks:
- [ ] In bufferevent_openssl.c, pointer `wm` is dereferenced on [line 871](https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/bufferevent_openssl.c#L871) _before_ it is null checked on [line 873](https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/bufferevent_openssl.c#L873).
- [ ] In evrpc.c, pointer `req` is dereferenced on [line 881](https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/evrpc.c#L881) _before_ it is null checked on [line 894](https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/evrpc.c#L894).
- [ ] In evdns.c, pointer `server_req` is null checked on [line 1289](https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/evdns.c#L1289) _after_ it is dereferenced above. Since `server_req` was already null checked above on [line 1243](https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/evdns.c#L1243), there is no risk of crashing and the only bug is the redundant null check (and indentation) on [line 1289](https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/evdns.c#L1289).

**Comment by azat** [comment]
1) covered with `target`, though it is not readable

**Comment by azat** [comment]
2) covered with https://github.com/libevent/libevent/blob/df6f99e5b51a3c0786f54cb9822604ec63385400/evrpc.c#L871

**Comment by azat** [comment]
Ops, you are reporting about that they are redundant, okay, they will be eliminated.

**Comment by azat** [comment]
Thanks for you report (with details about lines and links to them)!

**Comment by bugwelle** [comment]
For readers coming from Google (by searching for `µchex`): The paper can now be found at https://mlfbrown.com/paper.pdf
