### ISSUE TITLE
whether missing connect error indicate

### ISSUE THREAD

**Issue by joyhope** [libevent/libevent#389]
In the 2.0.22 code, it seems  HOOK_CONN_RUN is manually disabled. I think the macro needs to be called in the  _evhtp_connection_error_hook.  

Am I right? 

static inline evhtp_res
_evhtp_connection_error_hook(evhtp_connection_t * connection, evhtp_error_flags errtype) {
    if (connection == NULL) {
        return EVHTP_RES_FATAL;
    }

    if (connection->request != NULL) {
        _evhtp_error_hook(connection->request, errtype);
    }

    HOOK_CONN_RUN(connection, on_connection_error, errtype);  <<== missing callback

    return EVHTP_RES_OK;
}

**Comment by azat** [comment]
You should open this issue in [libevhtp](https://github.com/ellzey/libevhtp)
