### ISSUE TITLE
libevent: Reading all bytes from buffer

### ISSUE THREAD

**Issue by kaushik90** [libevent/libevent#390]
I have following read callback function `readcb` which is invoked on read event. My issue is, `bufferevent_get_input` is reading only 4096 bytes from the underlying buffer. How can I make it to read all bytes. I have used a variant also, given below as `readcb_variant`. It also reads only 4096 bytes and exists with n = 0, means no more bytes to read.

```
void readcb(struct bufferevent *bev, void *ctx){
    size_t bytesread;
    char buf[10000];
    struct evbuffer *input, *output;
    input = bufferevent_get_input(bev);

    bytesread = evbuffer_get_length(input);
    evbuffer_remove(input, buf, bytesread);

    printf("%zu\n", bytesread ); // prints 4096 for long (> 4096) byte stream
    do_some_cool_stuff(buf);
}


void readcb_variant(struct bufferevent *bev, void *ctx){
    char tmp[1000], buf[10000];
    size_t n, bytesread = 0;
    char *runner = buf;

    while(1){
        n = bufferevent_read(bev, tmp, sizeof(tmp));
        if (n <= 0){
            printf("%zu\n", n); // prints '0';
            break;
        }
        memcpy(runner, tmp, n);
        runner += n;
        bytesread += n;
    }
    printf("%zu\n", bytesread ); // prints 4096 for long (> 4096) byte stream
    do_some_cool_stuff(buf);
}
```

**Comment by ploxiln** [comment]
You need to return from the function to let the event loop run, so it can read more into the bufferevent's buffer. Your callback will be called multiple separate times with more bytes.

**Comment by kaushik90** [comment]
Found this` #define EVBUFFER_MAX_READ   4096` in `buffer.c`. I was not aware of this enforced limit. Closing the issue
