### ISSUE TITLE
issue compiling on windows with CMAKE Visual Studio 2014

### ISSUE THREAD

**Issue by Sweetkubuni** [libevent/libevent#393]
the EVENT__DISABLE_OPENSSL is default OFF instead of ON. not really sure if it is a big deal. lol

**Comment by azat** [comment]
Hi @Sweetkubuni 

Well actually you can compile it with *openssl*, you can take a look at [https://ci.appveyor.com/project/nmathewson/libevent/build/job/ajt5r1tcc46jf1nx](successful story) and it's [https://github.com/libevent/libevent/blob/master/appveyor.yml](setup)

And the only reason for me to make *openssl option* is backward compatibility.

So I'm closing this one, if you have other thoughts please reopen.

Thanks!
