### ISSUE TITLE
Consider setting IPV6_V6ONLY on IPv6 sockets to prevent automatic dual-stack binding

### ISSUE THREAD

**Issue by raybellis** [libevent/libevent#394]
Using the HTTP server under Linux, the `evhttp_bind_socket()` function with a host parameter of `::` will by default on many distributions make the socket dual-stack, meaning that a subsequent attempt to `bind()` to `0.0.0.0` will fail.   On other O/S it's necessary to bind the IPv4 and IPv6 sockets separately.

In my `evldns` package I avoid this by calling `setsockopt(s, IPPROTO_IPV6, IPV6_V6ONLY, ...)` on sockets that are about to be bound on IPv6.  I understand that OpenSSH does the same.

**Comment by azat** [comment]
@raybellis thanks for the report!

One thing that bother me is that some users can already depends from the old behavior, very unlikely I guess, but still.

**Comment by raybellis** [comment]
@slokhorst that's right - you have to call `setsockopt()` before the `bind()` call happens.  I don't use libevent's own socket creation functions myself, but I still think making this change is the right thing.  It's much easier for people whose systems rely on this behaviour to add an explicit IPv4 and/or IPv6 binding than to remove one that's automatically created for you by the library.

**Comment by slokhorst** [comment]
@azat (or any other libevent folks), do you have any suggestion how to handle this in the meantime? I need to be able to support this usecase:
````C
evhttp_bind_socket (http, "127.0.0.1", port);
evhttp_bind_socket (http, "::", port);
````
(Bind on all IPv6 addresses, but just a single IPv4 one. This is currently not possible.)

Is the only solution to implement `evhttp_bind_socket()` myself?

**Comment by azat** [comment]
@slokhorst there is `sysctl` for this:

```
bindv6only - BOOLEAN
	Default value for IPV6_V6ONLY socket option,
	which restricts use of the IPv6 socket to IPv6 communication
	only.
		TRUE: disable IPv4-mapped address feature
		FALSE: enable IPv4-mapped address feature

	Default: FALSE (as specified in RFC3493)
```

You can set it to TRUE as a solution, but I agree that libevent should support this somehow.
But there is little issue with this, we can break backward compatibility if we will change behaviour of `evhttp_bind_socket()`, and besides there is also other similar API's (like `evconnlistener_new_bind`)

**Comment by azat** [comment]
After #640 we have `LEV_OPT_BIND_IPV6ONLY`, so you can use something like this:

```c
listener = evconnlistener_new(base, cb, 0, LEV_OPT_BIND_IPV6ONLY, -1, fd);
evhttp_bind_listener(http, listener);
```
(@raybellis I guess that this is not totally what you want, since you do not want to bother with creating listener?)

As for adding it by default into http, I do think that it is worth it.
(I don't mind to change my opinion if you have some strong arguments on this one).
