### ISSUE TITLE
Configure misidentifies clock_gettime and getentropy on macOS Sierra/XCode8 when compiling for iOS 8

### ISSUE THREAD

**Issue by rainwolf** [libevent/libevent#398]
libSystem.dylib provides clock_gettime from iOS 10 onward but not below but the configure script does not detect that. Even with the `-Wl,-no_weak_imports` linker flag. The only way I managed to compile for iOS8 and iOS9 on macOS Sierra with XCode8 was to patch out detection of clock_gettime from the configure script. This is less-than-ideal but the only fix I know.

This is the patch I used
```
--- configure.orig	2016-09-21 13:24:02.000000000 +0200
+++ configure	2016-09-21 13:24:22.000000000 +0200
@@ -13164,7 +13164,7 @@
 fi
 
 
-for ac_func in gettimeofday vasprintf fcntl clock_gettime strtok_r strsep
+for ac_func in gettimeofday vasprintf fcntl strtok_r strsep
 do :
   as_ac_var=`$as_echo "ac_cv_func_$ac_func" | $as_tr_sh`
 ac_fn_c_check_func "$LINENO" "$ac_func" "$as_ac_var"
```

**Comment by Shchvova** [comment]
I made a pull request, adding new option `--disable-clock-gettime` #400

**Comment by azat** [comment]
So let me close this one, and take a look at #400
