### ISSUE TITLE
libevent built on macOS 10.12 Sierra is not portable to older OS

### ISSUE THREAD

**Issue by Shchvova** [libevent/libevent#399]
I have an app which uses `libevent`. Since macOS 10.12 Sierra it has `clock_gettime`. Problem is, older versions of OS X doesn't have it, so when I build library on my mac, clients of older OS would get crash with `Symbol not found: _clock_gettime`.

I solved the problem by deleting `clock_gettime` from `configure.ac`, but I don't think this is a proper solution.

Can we have a flag or a switch to disable `clock_gettime`, and it would be nice to document this somewhere.

UPDATE: this is resolved by my pull request #400. I made it after creating this issue when realized that it isn't hard to add a `./configure` switch.

**Comment by Shchvova** [comment]
I believe this option would be crucial to anyone using macOS and delivering applications to users, so I created an option to configure, so now I build `libevent` for my app like follows:
```
./configure  CFLAGS=" -mmacosx-version-min=10.8  "  --disable-shared --disable-openssl --enable-static --disable-debug-mode  --disable-clock-gettime  --prefix="$(pwd)/../libs"
```

**Comment by azat** [comment]
@Shchvova thanks for the report and the patch, let me close this one at take a look at #400
