### ISSUE TITLE
Compile against non-system ssl?

### ISSUE THREAD

**Issue by DigiAngel** [libevent/libevent#401]
Topic says it...I have libressl in /opt/libressl.  I've tried passing flags, but pkg-config always points to the system ssl.  How do I compile libevent against /opt/libressl?  Thank you.

**Comment by azat** [comment]
I guess you can change next lines:
- https://github.com/libevent/libevent/blob/master/m4/libevent_openssl.m4#L13
- https://github.com/libevent/libevent/blob/master/m4/libevent_openssl.m4#L20

Or add some switch for `autoconf`

**Comment by DigiAngel** [comment]
Thanks....got this figured out with the below:
~~~
CPPFLAGS="-I/opt/libressl/include" LDFLAGS="-L/opt/libressl/lib" ./configure --prefix=/opt/libevent
~~~

then drop a file with that contains "/opt/libressl/lib" in /etc/ld.so.conf.d/, do an ldconfig, and away you.  Thank you.
