### ISSUE TITLE
cmake version looks wrong 

### ISSUE THREAD

**Issue by sburke56** [libevent/libevent#404]
This is what I see when I run cmake.  I'm guessing the major, minor, & patch revisions are not set correctly?  And this is causing an error when I try to "make event".

How am I supposed to fix this correctly? 

```
--         ---( Libevent magic_software_6.0
.magic_software_6.0
.magic_software_6.0
-beta )---
```

Error after running make event

```
/home/sburke/sandbox/libevent-release-2.1.6-beta/include/event2/event-config.h:14:32: warning: missing terminating " character
 #define EVENT__PACKAGE_VERSION "magic_software_6.0
```

**Comment by azat** [comment]
How did you change it?
Anyway here is the sample from cmake rules:
```
set(EVENT_PACKAGE_VERSION                                                                                                                                      
    "${EVENT_VERSION_MAJOR}.${EVENT_VERSION_MINOR}.${EVENT_VERSION_PATCH}")
```

And all of this variables (`EVENT_VERSION_*`) should be int

**Comment by azat** [comment]
@sburke56 any news?
