### ISSUE TITLE
Is library name during Cmake alpha build on windows correct?

### ISSUE THREAD

**Issue by fquinner** [libevent/libevent#405]
If I run the following in a build subdirectory inside the source tree of the 2.1.6 beta release (tarball downloaded from site):

```
cmake -DEVENT__DISABLE_OPENSSL:BOOL=ON -G "Visual Studio 14 2015" ..
cmake --build . --config Release --target install
```

It seems to create `event.lib`, `event_core.lib` and `event_extra.lib` rather than the traditional `libevent.lib`, `libevent_core.lib` and `libevent_extra.lib`. Is this intentional or an oversight? I.e. will it look like this going forward?

**Comment by azat** [comment]
Hm, interesting, `add_library()` does this [in purpose](https://cmake.org/cmake/help/v3.4/command/add_library.html).

I guess that this is how it suppose to work on win32 (but this is just a guess).

If you need this "lib" prefix you can try adding next hunk into `CMakeLists.txt`
```cmake
SET_TARGET_PROPERTIES(event PROPERTIES PREFIX "lib")
SET_TARGET_PROPERTIES(event_core PROPERTIES PREFIX "lib")
SET_TARGET_PROPERTIES(event_extra PROPERTIES PREFIX "lib")
```

**Comment by azat** [comment]
So I guess that this is the correct behavior otherwise I don't think that `find_library` can find this library without help.

@fquinner what do you think?

**Comment by fquinner** [comment]
Thanks for the good answer and another good question :). Yeah I think on windows, bare makes more sense, its something I'm struggling with myself on other projects too but on balance if cmake has it as a default, its probably a pretty sensible default.

**Comment by azat** [comment]
Same here, thanks!
