### ISSUE TITLE
libevent ignores body received for method GET and others

### ISSUE THREAD

**Issue by gonzus** [libevent/libevent#408]
Function evhttp_method_may_have_body() is used to determine which methods may include a body. The standard is not very clear about how to deal with bodies in GET, but many other languages / frameworks / implementations allow it. Probably too for other methods.

**Comment by azat** [comment]
Hm, looking through [rfc2616](https://www.ietf.org/rfc/rfc2616.txt), and cannot find nothing about body for GET, but I guess that that fact that GET request doesn't adds any meaning for request-body (according to 4.3) that we SHOULD ignore it.

Well and here is [so[(http://stackoverflow.com/a/983458) answer that thinks just like this.

But tested `php` builtin server:
```php
# get.php
<?php

var_dump($_SERVER['REQUEST_METHOD']);
var_dump($_POST);
```

`php -S 0.0.0.0:8080 get.php`
```bash
$ echo -e "POST / HTTP/1.0\r\nContent-Length: 8\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\nfoobar=1" | nc 127.1 8080
HTTP/1.0 200 OK
Connection: close
X-Powered-By: PHP/7.0.11
Content-type: text/html; charset=UTF-8

string(4) "POST"
array(1) {
  ["foobar"]=>
  string(1) "1"
}
$ echo -e "GET / HTTP/1.0\r\nContent-Length: 8\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\nfoobar=1" | nc 127.1 8080
HTTP/1.0 200 OK
Connection: close
X-Powered-By: PHP/7.0.11
Content-type: text/html; charset=UTF-8

string(3) "GET"
array(0) {
}
```

**Comment by ploxiln** [comment]
The popular ElasticSearch database started the odd trend of accepting a query description in the body of a GET request. But these requests can be POST requests instead, because many libraries and tools understandably do not expect to ever include a body in a GET request. [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html)

IMHO it's fine for libevent to decide it always ignores body in GET request.

**Comment by gonzus** [comment]
As I mentioned when I opened the ticket, there seems to be no universal 
agreement on this. As a counterexample, take a look at what Go does with 
GET bodies: 
http://stackoverflow.com/questions/17676334/how-to-parse-http-get-request-body-in-a-go-http-server

I would argue more on the "why not" side. If the client wants to send a 
body with a GET request, why not accept it? And leave the "business 
logic" code deal with it as it sees fit? Right now, there simply is no 
choice.

**Comment by azat** [comment]
So I checked nginx implementation and it allows reading body for GET/DELETE/OPTIONS/CONNECT, so I pushed a patch that allows the same for libevent's http server.

**Comment by ghazel** [comment]
This patch had the effect of printing:

```
[libevent] 2 evhttp_get_body_length: we got no content length, but the server wants to keep the connection open: keep-alive.
```

for simple GET requests, because they contain no `Content-Length`.

**Comment by azat** [comment]
I already have a patch for this in my tree
