### ISSUE TITLE
listener.c 853 line memory leak

### ISSUE THREAD

**Issue by fettliu** [libevent/libevent#414]
lev->accepting = mm_calloc(lev->n_accepting, sizeof(struct accepting_socket *));

I found 32bytes memory leaks on my os(windows) that using IOCP.

**Comment by FettLuo** [comment]
#define _EVENT_VERSION "2.0.22-stable"

**Comment by azat** [comment]
Refs: #257

**Comment by azat** [comment]
@FettLuo I guess you tried `2.1.7-rc` and don't see any leak there?

**Comment by FettLuo** [comment]
I am not running 2.1.7-RC.
But I did not see free Lev->accepting in the listener.c, except err_free_accepting in the iocp_listener_disable_impl().

**Comment by azat** [comment]
So you are using 2.0.22, and here is how it looks freeing of memory for listener:

https://github.com/libevent/libevent/blob/release-2.0.22-stable/listener.c#L874-L881

So it does free `lev->accepting`, but not `lev->accepting[i]` I guess you are talking about them?
