### ISSUE TITLE
evthread_use_windows_threads memory leak

### ISSUE THREAD

**Issue by FettLuo** [libevent/libevent#415]
![image](https://cloud.githubusercontent.com/assets/14716316/20054117/67771612-a516-11e6-92b4-1fef30890f56.png)

Perhaps not a problem. But I do not know how to release it!

**Comment by FettLuo** [comment]
#define _EVENT_VERSION "2.0.22-stable"

**Comment by azat** [comment]
Can you try next:
- libevent 2.1.7-rc
- `libevent_global_shutdown()`

?

**Comment by FettLuo** [comment]
nice
