### ISSUE TITLE
evhttp_request->uri isn't a uri...

### ISSUE THREAD

**Issue by TheRook** [libevent/libevent#42]
A Uniform Resource Identifier consists of the [following components](http://docs.oracle.com/javase/6/docs/api/java/net/URI.html):
[scheme:][//authority][path][?query][#fragment]

evhttp_request->uri returns the  [path] and [?query] components concatenated together...  This is annoying because  If you try to access an evhttp by typing the following URI in the address bar of a browser:
http://localhost:1234/?key=var

Then evhttp_request->uri returns "/?key=var" which causes the following code to return a dictionary with the key element "/?key" instead of "key":
evhttp_parse_query_str(req->uri, &GET);

The solution is probably to remove evhttp_request->uri entirely and replace it with evhttp_request->path and evhttp_request->query. 

For example to obtain the GET prams you could use this:
evhttp_parse_query_str(req->query, &GET);

And if you wanted to work with the path:
if(strcmp(req->path,'/index.html')==0){
     ...
}

Or another option is to have evhttp_parse_query_str() deal with the [path] part of a URI in an elegant way,  I think we can all agree that turning the path into a key is a bug.

**Comment by ellzey** [comment]
Oh neat, I already responded to this. The above is old, you can check out libevhtp's version, it's actually faster now.

I'm closing this since we plan on merging evhtp with evhttp in the alpha.
