### ISSUE TITLE
Need user-triggered events

### ISSUE THREAD

**Issue by pprindeville** [libevent/libevent#420]
I'd like to see truly native user-triggered events that aren't a subversion of timers.

I'm happy to implement this myself, but was hoping for some high-level guidance before I start coding this.

**Comment by nmathewson** [comment]
Does constructing an event and then calling event_active() on it not work for you?

**Comment by pprindeville** [comment]
> Does constructing an event and then calling event_active() on it not work for you?

How, specifically?  I was looking at the one example I have from an email that Bill Vaughn sent out, where he says:

```
Hi Philip,

Here is a simple example of how I create events that I want to fire explicitly (ie: user triggered). I just happen to be working on this code right now. I do this sort of thing all over the place. Especially useful to wakeup a base on a different thread (assuming you are set up for thread safe operation).

// this is the callback that does the work
void udp_check_txq(int fd, short event, void *arg)
{
   UdpChan_t *udp = (UdpChan_t *)arg;
   process_tx_queues(udp);  // my function not shown here
}

// arm the "user event" to be executed 'now'
void udp_arm_check_txq(UdpChan_t *udp)
{
   // add the event with a 0 timeval 
  // it will be called on next event loop 
   struct timeval tv={0,0};
   evtimer_add(udp->check_txq_ev, &tv); 
}

// Create the event in some init code

if ( !(udp->check_txq_ev = event_new(base, -1, 0, udp_check_txq, udp)) )
{
    break;
}

// Call udp_arm_check_txq() when you want to make the event immediately ready
// It will called on the very next event loop

udp_arm_check_txq(udp);

-Bill
```

So are we talking about adding a timer event with immediate expiration?  Or is there a better way to do things than this?

**Comment by azat** [comment]
Here is a simple [example]
(https://gist.github.com/azat/d76de36a8980b888e111a267666b1794)

Is it what you want to do? @pprindeville

**Comment by pprindeville** [comment]
@azat thanks for that example.  In fact, the EV_READ doesn't seem to be necessary, you can pass 0 per the header file comments:

> If events contains none of those flags, then the event can be triggered only by a timeout or by manual activation with event_active(): In this case, fd must be -1.

**Comment by azat** [comment]
Indeed, you don't even need `EV_READ`

So can you close this?

**Comment by pprindeville** [comment]
> So can you close this?

Not yet.  I was thinking about adding a dedicated type.  I've done a little work and can do a PR, but that's for sharing purposes so far.  It's still a work-in-progress.

**Comment by azat** [comment]
Closing this one in favor to #423
