### ISSUE TITLE
Support mbedtls

### ISSUE THREAD

**Issue by ghost** [libevent/libevent#421]
I'd like to request support for mbedtls (https://tls.mbed.org/) or information on how to integrate with libevent.

We have to use mbedtls (for... reasons)

**Comment by azat** [comment]
Basically all you need is to make new `bufferevent_openssl.c` -- `bufferevent_mbedtls` (but please do not just copy-paste it and then substitute `SSL_*` to `mbedtls_*` analogs) + some changes to `cmake`/`autoconf` so that it can detect which openssl library is.

**Comment by bl4ck5un** [comment]
Anyone working on this? I have the same request and I think I can contribute. Just want to make sure I won't be reinventing something that has been done.

**Comment by azat** [comment]
Please, go ahead!

P.S. AFAIK nobody works on this

**Comment by hardening** [comment]
I'm interested too, if nobody's on it I will eventually have a look.

**Comment by boytm** [comment]
I have finished a prototype just now.  Currently, only tested with a simple https client.
https://github.com/boytm/libevent/commit/4e393b027ba05fab87bbd087278a3360059a4088

**Comment by azat** [comment]
>I have finished a prototype just now.

Great! Nice to hearing from you!

>Currently, only tested with a simple https client

I will take a look at your patch
