### ISSUE TITLE
What results in build error `util.h:139:26: error: operator '==' has no left operand #elif EVENT__SIZEOF_LONG == 4`?

### ISSUE THREAD

**Issue by JandunCN** [libevent/libevent#424]
I built libevent via `cmake xxxxx; make; make install` on Centos7.2_x64, but I encountered many errors like the following tip:
> libevent/include/event2/util.h:130:2: error: #error "No way to define ev_uint64_t"
 #error "No way to define ev_uint64_t"
  ^
libevent/include/event2/util.h:139:26: error: operator '==' has no left operand
 #elif EVENT__SIZEOF_LONG == 4

**./cmake --version**
> cmake version 3.7.0

**gcc --version**
> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

**Comment by azat** [comment]
@JandunCN can you send commit hash (just in case)?

**Comment by azat** [comment]
Checked on `centos/7` with latest upstream and it works with:
```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
```
```
$ uname -a
Linux localhost.localdomain 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64
GNU/Linux
```
```
$ cmake --version
cmake version 2.8.11
```

**Comment by JandunCN** [comment]
@azat Thank you for your reply. It had nothing to do with my gcc version.  I built the latest version just now with gcc6.2.0, but failed either.  My latest build is based on `ca591c5b1b8c4506c258a96e1fd5d8dafdb6234f`. So what's the the point?

**Comment by azat** [comment]
Okay, than since it works for me (as you can see I've added centos/7 vagrant box, and I'd tested on it - and it works, and even passes all tests), can you post:
- CMakeCache.txt
- full cmake output
- full make output

**Comment by azat** [comment]
And it is wrong to build with `cmake & make & make install` since it run all this commands in parallel, i.e. `cmake &` `make` & `make install`.
But I guess that you have `cmake && make && make install` since otherwise it should fail earlier, since there will be no `Makefile` for `make`

**Comment by JandunCN** [comment]
My `cmake & make & make install`  means cmake, then make, then make install. I should use `cmake; make; make install` instead.

My VPS provider has something wrong now, I can't get `CMakeCache.txt, full cmake output, full make output` right now. I will upload them to my 'github repo' as soon as possible for your reading.

Thank you again.

**Comment by JandunCN** [comment]
Yeah. There is no need to upload to my github repo. 
[CMakeCache.txt](https://github.com/libevent/libevent/files/601461/CMakeCache.txt)
[cmake.output.txt](https://github.com/libevent/libevent/files/601462/cmake.output.txt)
[make.output.txt](https://github.com/libevent/libevent/files/601463/make.output.txt)

**Comment by azat** [comment]
This is not the full output for `cmake`, you need to clean cache first, so can you reattach all 3 files after cleaning cache? (simply run `cmake ..` from another build directory)

**Comment by azat** [comment]
Hm, most of `TRY_COMPILE` fails, can you please attach `CMakeFiles/CMakeError.log` too

**Comment by azat** [comment]
Maybe you will have some cmake warnings for some changes in it's policy

**Comment by azat** [comment]
Can you also upload the whole folder for the next simple `cmake`?

```
# CMakeLists.txt

project(cmake-test)
cmake_minimum_required(VERSION 3.7)

include(CheckTypeSize)
check_type_size(size_t sizeof_size_t)
message("size_t size: ${sizeof_size_t}")
```

**Comment by JandunCN** [comment]
@azat Thanks for your detailed tutorial. I will rebuild with your tips and analyse the errors carefully. I will update the result if I succeed. I am busy with my work nowadays.

**Comment by azat** [comment]
Plus your can try to use autoconf/automake instead.

**Comment by JandunCN** [comment]
I just want to know why. Maybe I have much work to do, such as cmake basis. In fact, the first build error is something like the following code snippet shows.  
```
#include <stdio.h>

/* Case 1:
 * Result in build error: operator '==' has no left operand
 * #if EVENT__SIZEOF_LONG_LONG == 8. */
/* #define EVENT__SIZEOF_LONG_LONG */

/* Case 2:
 * Build well. */
#define EVENT__SIZEOF_LONG_LONG 1

#if EVENT__SIZEOF_LONG_LONG == 8
#define _OK_ 1
#endif

int main(){
        printf("This is a test.\n");

        return 0;.
}
```
Maybe it just has something to do with one gcc flag that I have no idea.

PS: I upload the whole folder hoping that you can figure something out.
[CMakeFiles.zip](https://github.com/libevent/libevent/files/614806/CMakeFiles.zip)

**Comment by azat** [comment]
@JandunCN it doesn't work because you need to include `<event2/event-config.h>`

Also can you please provide *output of the cmake* and the *whole cmake folder* for [this](https://github.com/libevent/libevent/issues/424#issuecomment-261719640) minimal example, since that archive is too large, it will be better to have minimal amount.

**Comment by azat** [comment]
Plus, that `CMakeFiles` is a little bit icky, since there is no `Makefile` there is only:
- `Makefile2`
- `Makefile.cmake`

**Comment by azat** [comment]
@JandunCN any news?

**Comment by JandunCN** [comment]
Sorry about long silence. Today I build it the second time, and It succeeds. My advice is that maybe `gcc4.8.5` doesn't support `#if EVENT__SIZEOF_LONG_LONG == 8`. 

Last time I changed `CC` system environment variable to `gcc6.2.0`, but I didn't affect my `libevent` build. 
I linked `/usr/bin/cc` to `gcc6.2.0`, and build newest `libevent` source code successfully .

**Comment by JandunCN** [comment]
close as above.
