### ISSUE TITLE
Time to release v2.0.23

### ISSUE THREAD

**Issue by ghost** [libevent/libevent#426]
Version 2.0.23 has been a Release Candidate for 5 months now without changes.

Isn't it time to make this an actual release?

**Comment by azat** [comment]
Indeed, see #348 for the reference.
But let me ask a minor question, could you use 2.1 instead (when it will be released)?

**Comment by a168290** [comment]
> ...could you use 2.1 instead (when it will be released)?

My primary interest is in using it with Tor.  Is/will v2.1 be compatible with the current Tor versions?

**Comment by azat** [comment]
@nmathewson ?

**Comment by a168290** [comment]
Please don't let this topic languish due to lack of response by nmathewson.

**Comment by azat** [comment]
I was asking about tor, current priority for me is 2.1.
Are you waiting some bug to be fixed in the next 2.0 release, if so, what bug?

**Comment by hhakimi53** [comment]
Thanks first of all the work that's put in for the libevent.

Is there a timeline for release stable candidate for 2.1? 2.1.7 seems to much better for SSL functionality as compared to 2.0.22. Thanks

**Comment by azat** [comment]
2.0.23-beta is released in 4294867c
