### ISSUE TITLE
Custom HTTP methods support

### ISSUE THREAD

**Issue by kiler129** [libevent/libevent#427]
While strict HTTP prohibits custom method many implementations in the wild are using them. I've seen many implementations slightly bending HTTP protocol by adding custom methods (e.g. Apple proprietary HomeKit uses `EVENT` method).

Sadly I'm not proficient enough in C to suggest any solutions or even look at the possibilities of custom methods implementation. Is it even possible without breaking BC on libevent?

**Comment by azat** [comment]
@kiler129 take a look at #327

**Comment by kiler129** [comment]
@azat: Thank you for the reference. I see it's marked as 2.2, but we're not even at 2.1 and PR itself wasn't updated for almost a year :(

I can rebake it onto current master and use, but I'm not sure if this API will change or will it stay as is.

**Comment by azat** [comment]
Yeah we are working on 2.1 stable release, and only after this we can start with 2.2.

If you need this API then you have to compile libevent by yourself. Yes this API **is not stable** but I don't think that it will be changed, maybe some minor hunks, anyway I'm sure that it shouldn't be a problem for you if you can compile libevent by yourself (i.e. some projects depend on what distros provides, but I guess that this is not your case).

**Comment by kiler129** [comment]
Looking at the 2.1 milestone it doesn't look far away, so I will follow your suggestion and I'll just use custom version for my app ;)

I think since we have #327 this issue is a duplicate, so it can be closed.
