### ISSUE TITLE
win32: http server asynchronous hand, the first request will be block until other request in.

### ISSUE THREAD

**Issue by lastorder** [libevent/libevent#429]
I create a thread in "evhttp_set_gencb" callback to hand the evhttp_request.
In win32, the first request will be block until other request in. The thread in the callback was ran normally, and called evhttp_send_reply.

If I use openssl to set https server in win32, there is no block.

In solaris, both http and https is OK.

**Comment by azat** [comment]
Can you provide a reproducer?

**Comment by lastorder** [comment]
I cannot up load the code file in my office area.

        if (bAsynMode)
        {
            evhttp_set_gencb(http_tmp, asyn_reply_hand, this);
        }
        else
        {
            evhttp_set_gencb(http_tmp, server_reply_cb, this);
        }

void httpsServer::asyn_reply_hand(struct evhttp_request *req, void *arg)
{
    NETSTAR_AGENT_TRACE_D("asyn_reply_hand in !");
    struct reply_agrs * args = new struct reply_agrs();
    args->req = req;
    args->arg = arg;
    int ret = ACE_Thread_Manager::instance()->spawn(ACE_THR_FUNC(httpsServer::worker), args, THR_NEW_LWP|THR_DETACHED);
    NETSTAR_AGENT_TRACE_D("asyn_reply_hand out ! ret :" << ret);
}


void* httpsServer::worker(void *arg) 
{
    struct reply_agrs * args = (struct reply_agrs *)arg;
    server_reply_cb(args->req,args->arg);
    delete args;
    //ACE_Thread::exit();
    return NULL; 
} 

server_reply_cb is similar as the demo.

**Comment by lastorder** [comment]
void httpsServer::server_reply_cb(struct evhttp_request *req, void *arg)
{
    ......

    httpsServer *ptr = (httpsServer *)arg;
    HTTP_RESPOND resp = ptr->handRespond((NetStarHttpOpt)type,strPath,mapParam,payload);
    evbuffer_add_printf(evb,"%s",resp.second.c_str());

    evhttp_add_header(evhttp_request_get_output_headers(req),
        "Content-Type", "application/json");

    evhttp_send_reply(req, resp.first, "OK", evb);

    NETSTAR_AGENT_TRACE_D("evhttp_send_reply !");
    evbuffer_free(evb);
}

**Comment by azat** [comment]
This doesn't make anything clearer, so I will try to take a look somehow (but firstly I need to create env for this).

P.S. **please use markdown for code**

**Comment by lastorder** [comment]
I changed  event_base_loop 
to 
    while(1)
    {
        (void)event_base_loop((struct event_base *)arg,EVLOOP_NONBLOCK|EVLOOP_NO_EXIT_ON_EMPTY);
        ACE_OS::sleep(ACE_Time_Value(0, 10000)); //暂停10毫秒
    }

the problem will be ok.

**Comment by azat** [comment]
@lastorder Do you mean that the problem goes away?

**Comment by lastorder** [comment]
@azat yes, the block problem goes away.

But there is new problem. 
In pressure test, the asyn pattern( new thread in server_reply_cb and call evhttp_send_reply in new thread)  low probability crash. (win32)

I changed code to  create multiple event base , and start event_loop in multiple thread , there is no crash.


Is libevent don't supply asynchronous hand in evhttp_set_gencb callback fuction?

**Comment by lastorder** [comment]
Because some operate in http hand callback is time-consuming, I want to new a thread for each request.

One event_base one thread, will limit the concurrent.

**Comment by azat** [comment]
Did you enable threading support?

**Comment by azat** [comment]
If no, you need to enable pthreads (somewhere globally):
```c
    evthread_use_pthreads();
```

And enable `BEV_OPT_THREADSAFE` for every `bufferevent`:
```c
    int flags = BEV_OPT_THREADSAFE;
    struct bufferevent *bev = bufferevent_socket_new(base, -1, flags);
    evhttp_connection_base_bufferevent_new(base, NULL, bev, "127.0.0.1", 80);
```

**Comment by lastorder** [comment]
I http server mode, I don't create bufferevent by myself. I just uesd it like the demo.

        struct event_base * eventBase = event_base_new();
        if (!eventBase) {
            NETSTAR_AGENT_TRACE_D("Couldn't create an event_base!");
            continue;
        }

        struct evhttp *http_tmp = evhttp_new(eventBase);
        if (!http_tmp) {
            NETSTAR_AGENT_TRACE_D("couldn't create evhttp. Exiting.");
            continue;
        }
        if (NULL == socket)
        {
            struct evhttp_bound_socket *handle = evhttp_bind_socket_with_handle(http_tmp,m_address.c_str(),m_port);
            if (!handle) {
                NETSTAR_AGENT_TRACE_D("couldn't bind to :"<<m_address.c_str()<<":"<<m_port);
                return ;
            }
            socket = evhttp_bound_socket_get_fd(handle);
            if(evutil_make_socket_nonblocking(socket)!=0)
            {
                NETSTAR_AGENT_TRACE_D("evutil_make_socket_nonblocking failed!! ");
            }
        } 



How should I create bufferevent by myself ?  In 'evhttp_set_bevcb' call back fuction ?

**Comment by lastorder** [comment]
I already set threadsafe.

#ifdef _WIN32
    if(0 == evthread_use_windows_threads())
    {
        NETSTAR_AGENT_TRACE_D ("evthread_use_windows_threads success !");
    }
    else
    {
        NETSTAR_AGENT_TRACE_D ("evthread_use_windows_threads failed !");
    }
#else
    if(0 == evthread_use_pthreads())
    {
        NETSTAR_AGENT_TRACE_D ("evthread_use_pthreads success !");
    }
    else
    {
        NETSTAR_AGENT_TRACE_D ("evthread_use_pthreads failed !");
    }
#endif

**Comment by lastorder** [comment]
I used 2.0.22 version, there is no 'evhttp_set_bevcb'.
How can I create the bufferevent in http server?

**Comment by azat** [comment]
Can you try 2.1 (there is stable release already)?

**Comment by azat** [comment]
@lastorder ping

**Comment by lastorder** [comment]
@azat 

sorry, there is no bug. I don,t set thread safe properly.
Please close the essue.

**Comment by banmoy** [comment]
@lastorder 

> I don't set thread safe properly.
I have a similar scenario. Could you share the final settings about the thread safe? Thanks.

**Comment by lastorder** [comment]
@banmoy I have already forgot all about this. Maybe you can find something you need in this repo:  https://github.com/lastorder/cpp_restful

**Comment by sfhacker** [comment]
This issue is from 2016!

**Comment by banmoy** [comment]
@lastorder Thanks for your reply

**Comment by banmoy** [comment]
@sfhacker 

> 
This issue is from 2016!

What do you mean by it? Should I open a new issue for my question?
