### ISSUE TITLE
bev_async_consider_reading/writing call the eventcb directly

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#43]
A bit surprisingly, this code can crash:

```c
struct bufferevent *bev;
int fd = socket(PF_INET, SOCK_STREAM, 0);
evutil_make_socket_nonblocking(fd);
bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE);
bufferevent_setcb(bev, NULL, NULL, eventcb, NULL);
bufferevent_enable(bev, EV_READ|EV_WRITE);
bufferevent_socket_connect(bev, addr, sizeof(addr));
```

I know the `bufferevent_enable` call is superfluous, but it seems like it should also be safe (particularly since reading is already enabled!) Instead, it can cause `bev_async_consider_reading` to call the `eventcb`, which frees the bufferevent on error. Then, the call to `bufferevent_socket_connect` will crash.

**Comment by azat** [comment]
Hm, this could be fixed with `BEV_OPT_DEFER_CALLBACKS`, no?

**Comment by azat** [comment]
Actually there is a check against `bev_async->ok`, so it mustn't call `bev_async_consider_reading`
https://github.com/libevent/libevent/blob/571dbac81af7a378d6fad0728c3eb3d7be89785f/bufferevent_async.c#L325

**Comment by azat** [comment]
I'm closing this, since there is a unit test that passes, please reopen if you will find problems.
