### ISSUE TITLE
How to close fds/resources registered in event_base during destroy

### ISSUE THREAD

**Issue by lysu** [libevent/libevent#433]
Hi~ 

I’m writing an application that support hot-reload logic(just..load some module and unload some module on the fly without restart program)..

So, I try to destroy event_base use `event_base_free()' during unload logic, but the document said “this function will not close any fds or free any memory passed to event_new as the argument to callback.”

http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/event_8h.html

but is there any other recommand ways to handle this… close fd/free memory that registered to event_base, before destroy event_base…

thanks~~all

**Comment by azat** [comment]
So, IOW you don't store all events somewhere and you want to extract them from libevent?
Then you can use `event_base_foreach_event()`.
To get fd you can use `event_get_fd()`.
For argument passed to `event_assign()` use `event_get_callback_arg()`

**Comment by lysu** [comment]
oh~ thx @azat 

I have store events in other place, and do loop on it, before see your reply - -~~

and I also notice that `event_base_foreach_event` must not modify event base, but we maybe need that in future..so we choose store events in other place finally.

thank azat~ ^ ^
