### ISSUE TITLE
Https Server with Mixed Content Security warning

### ISSUE THREAD

**Issue by spartucus** [libevent/libevent#434]
os: Windows 10 x64
env: libevent-2.1.7rc, openssl-1.1.0c, chrome-55, self-signed CA certificate

I implemented a https server with libevent. and listened on a local port 8421, when browser made request, such as "https://127.0.0.1:8421", server send a reply. Browser recieved response and display it.

When reply message is simple, everything went well cause I add Root certificate of 127.0.0.1 to system, and browser shows the recieved message and the lock is green, it says

> The page is secure(valid HTTPS).
![simple](https://cloud.githubusercontent.com/assets/6071887/21602527/be6148ea-d1cf-11e6-8be4-65586e93cd08.png)

 While  reply message is html that come from a real site(https://www.baidu.com), browser shows html well but no safe lock, it says

> This page is not secure. Mixed Content. The site includes HTTP resources.
![real](https://cloud.githubusercontent.com/assets/6071887/21602526/be2194a2-d1cf-11e6-8038-c54dea4498c1.png)

some code I think is related:
```
evhttp_set_bevcb(http, bev_callback, ctx);
evhttp_set_gencb(http, gen_request_callback, base);
```
```
bufferevent * bev_callback(event_base * base, void * arg)
{
	bufferevent *r = NULL;
	SSL_CTX *ctx = (SSL_CTX*)arg;
	r = bufferevent_openssl_socket_new(base, -1, SSL_new(ctx), BUFFEREVENT_SSL_ACCEPTING, BEV_OPT_CLOSE_ON_FREE);
	return r;
}
```

```
void gen_request_callback(evhttp_request * req, void * arg)
{
	evbuffer *evbuf = NULL;
	evhttp_cmd_type cmd_type = EVHTTP_REQ_GET;
	cmd_type = evhttp_request_get_command(req);
	if (cmd_type == EVHTTP_REQ_GET)
	{
		evbuf = evbuffer_new();
		if (!evbuf) return;
		
		evbuffer_add_printf(evbuf, "%s\n", "Recieved"); //here add simple message or REAL html
		evhttp_send_reply(req, HTTP_OK, "OK", evbuf);	
	}
}
```
Am I doing something wrong? or there're bugs in here. Any advice would be greatly appreciated.

**Comment by ploxiln** [comment]
This has nothing to do with libevent, this is caused by the html content.

It has a link to http://s1.bdstatic.com/... probably for an image or css file. A page loaded over https:// with a link to http:// is mixed content. This can be a complicated topic, it depends on the browser, the version of the browser, the type of resource, the way that it was referenced, javascript logic, etc. In any case, not related to libevent.

**Comment by azat** [comment]
[Indeed](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content)

**Comment by spartucus** [comment]
@ploxiln Thanks a lot.

**Comment by spartucus** [comment]
@ploxiln Thanks a lot
