### ISSUE TITLE
How to set socket's property to TCP NO_DELAY on a evhttp_connection?

### ISSUE THREAD

**Issue by tg0428** [libevent/libevent#435]
i want to disable Nagle algorithm on TCP socket, but i didn't find a interface in http.h. Is there having a method to solve this problem?

**Comment by azat** [comment]
There is no API for this, but you can do something like this:

```
int evhttp_setsockopt(struct evhttp_connection *evcon, int key, int value)
{
  int fd = -1;
  struct bufferevent *bufev = evhttp_connection_get_bufferevent(evcon);
  if (!bufev)
    return -1;
  fd = bufferevent_getfd(bufev);
  if (fd < 0)
    return -1;
  return setsockopt(fd, SOL_TCP, key, &value, sizeof(value));
}

// ...

assert(!evhttp_setsockopt(evcon, TCP_NODELAY, 1));
```

*P.S. Totally untested.*

**Comment by tg0428** [comment]
@azat i think this method just suits for the situation which you have excuted "evhttp_make_request" API before,  so here is another problem , how to make sure the socket without Nagle  algorithm for the first time when you make request to remote server?

**Comment by tg0428** [comment]
@azat i modify the source code.
`/* Create a non-blocking socket and bind it */
/* todo: rename this function */
static evutil_socket_t
bind_socket_ai(struct evutil_addrinfo *ai, int reuse)
{
	evutil_socket_t fd;

	int on = 1, r;
	int serrno;

	/* Create listen socket */
	fd = socket(ai ? ai->ai_family : AF_INET, SOCK_STREAM, 0);
	if (fd == -1) {
			event_sock_warn(-1, "socket");
			return (-1);
	}

	if (evutil_make_socket_nonblocking(fd) < 0)
		goto out;
	if (evutil_make_socket_closeonexec(fd) < 0)
		goto out;

	if (setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (void *)&on, sizeof(on))<0)
		goto out;
	if (setsockopt(fd, SOL_SOCKET, TCP_NODELAY, (void *)&on, sizeof(on))<0)
		goto out;
	if (reuse) {
		if (evutil_make_listen_socket_reuseable(fd) < 0)
			goto out;
	}

	if (ai != NULL) {
		r = bind(fd, ai->ai_addr, (ev_socklen_t)ai->ai_addrlen);
		if (r == -1)
			goto out;
	}

	return (fd);

 out:
	serrno = EVUTIL_SOCKET_ERROR();
	evutil_closesocket(fd);
	EVUTIL_SET_SOCKET_ERROR(serrno);
	return (-1);
}`

P.S. code version libevent-2.0.21-stable

**Comment by azat** [comment]
Indeed, you don't have `fd` after `evhttp_connection_base_new()`, but here is another solution:

```
int on = 1;
int fd = socket(AF_INET, SOCK_STREAM|SOCK_NONBLOCK, 0); // be sure that you do have SOCK_NONBLOCK
assert(fd >= 0);
assert(!setsockopt(fd, SOL_SOCKET, TCP_NODELAY, (void *)&on, sizeof(on)));
struct bufferevent *bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE | BEV_OPT_DEFER_CALLBACKS);
struct evhttp_connection *evcon = evhttp_connection_base_bufferevent_new(base, NULL, bev, "foobar.com", 80);
```

**Comment by tg0428** [comment]
@azat thanks a lot, however it seems not work, at the first time , libevent attempts  to connect to remote server, fd will be covered by the new fd. see evhttp_connection_connect
```
int
evhttp_connection_connect_(struct evhttp_connection *evcon)
{
	int old_state = evcon->state;
	const char *address = evcon->address;
	const struct sockaddr *sa = evhttp_connection_get_addr(evcon);
	int ret;

	if (evcon->state == EVCON_CONNECTING)
		return (0);

	evhttp_connection_reset_(evcon);

	EVUTIL_ASSERT(!(evcon->flags & EVHTTP_CON_INCOMING));
	evcon->flags |= EVHTTP_CON_OUTGOING;

	if (evcon->bind_address || evcon->bind_port) {
		evcon->fd = bind_socket(
			evcon->bind_address, evcon->bind_port, 0 /*reuse*/);
		if (evcon->fd == -1) {
			event_debug(("%s: failed to bind to \"%s\"",
				__func__, evcon->bind_address));
			return (-1);
		}

		bufferevent_setfd(evcon->bufev, evcon->fd);
	} else {
		bufferevent_setfd(evcon->bufev, -1);
	}
...
}
```

**Comment by azat** [comment]
@tg0428 seems that you are right, this games with `fd` is not pleasant, it introduces  [problems](https://github.com/libevent/libevent/issues/440).
