### ISSUE TITLE
"invalid integer constant expression" when building on Windows 64

### ISSUE THREAD

**Issue by jeffsaremi** [libevent/libevent#436]
I followed the instructions in the read me and created a Solution file like below. Howver the solution fails to build immediately because of lines like this in util.h:
#elif EVENT__SIZEOF_VOID_P <= 4
which produces the error in the title.
Below is some notable output from Cmake:

```
cmake -G "Visual Studio 14 2015 Win64"
-- Check size of struct addrinfo
-- Check size of struct addrinfo - failed
-- Check size of struct in6_addr
-- Check size of struct in6_addr - failed
-- Check size of sa_family_t
-- Check size of sa_family_t - failed
-- Check size of struct sockaddr_in6
-- Check size of struct sockaddr_in6 - failed
-- Check size of struct sockaddr_storage
-- Check size of struct sockaddr_storage - failed
-- Found OpenSSL: D:/local/openssl/lib/libssl.lib;D:/local/openssl/lib/libcrypto.lib (found version "1.1.0c")
-- OpenSSL include: D:/local/openssl/include
-- OpenSSL lib: D:/local/openssl/lib/libssl.lib;D:/local/openssl/lib/libcrypto.lib
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Looking for ERR_remove_thread_state
-- Looking for ERR_remove_thread_state - not found
-- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE)
CMake Warning at CMakeLists.txt:1030 (message):
  No suitable Python interpreter found, cannot generate regress tests!
CMake Warning at CMakeLists.txt:1148 (message):
  test-dumpevents will be run without output check since python was not
  found!
Call Stack (most recent call first):
  CMakeLists.txt:1193 (add_backend_test)

-- C:\cmake-3.7.1-win64-x64\bin\ctest.exe
--
--         ---( Libevent 2.1.7-beta )---
--
-- Available event backends: WIN32
-- CMAKE_BINARY_DIR:         D:/repos/libevent
-- CMAKE_CURRENT_BINARY_DIR: D:/repos/libevent
-- CMAKE_SOURCE_DIR:         D:/repos/libevent
-- CMAKE_CURRENT_SOURCE_DIR: D:/repos/libevent
-- PROJECT_BINARY_DIR:       D:/repos/libevent
-- PROJECT_SOURCE_DIR:       D:/repos/libevent
-- CMAKE_MODULE_PATH:        D:/repos/libevent/cmake/
-- CMAKE_COMMAND:            C:/cmake-3.7.1-win64-x64/bin/cmake.exe
-- CMAKE_ROOT:               C:/cmake-3.7.1-win64-x64/share/cmake-3.7
-- CMAKE_SYSTEM:             Windows-10.0.14393
-- CMAKE_SYSTEM_NAME:        Windows
-- CMAKE_SYSTEM_VERSION:     10.0.14393
-- CMAKE_SYSTEM_PROCESSOR:   AMD64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:            /DWIN32 /D_WINDOWS /W3
-- CMAKE_BUILD_TYPE:         Release
-- CMAKE_C_COMPILER:         C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- CMAKE_AR:
-- CMAKE_RANLIB:
--
-- Configuring done
-- Generating done
-- Build files have been written to: D:/repos/libevent

D:\repos\libevent>start libevent.sln
```

**Comment by azat** [comment]
Hi @jeffsaremi 

Can you post full clean cmake? I.e.:
```
mkdir .cmake
cmake ..
```

And also full error message?

**Comment by jeffsaremi** [comment]
Guys I'm embarrassed. Please close this issue.
As i was trying to reproduce the issue I noticed that I had not opened the right VS command window.
The right window to try for a 64bit build is "VS2015 x64 Native Tools Command Prompt". Once I did that, the resulting sln compiled without a glitch.

**Comment by lingyphone** [comment]
Hello, Here

Even I have read this ticket and make sure I started the build with a correct VS command windows of Visual studio 15 2017, I still see this issue on my Windows 10 x64 Home for both x64 and x86 builds. The cmake output listed as below.

Please help!


C:\WorkRepo\libevent\build64>cmake -G "Visual Studio 15 2017 Win64" -D EVENT__DISABLE_OPENSSL="true" -D EVENT__DISABLE_MBEDTLS="true" ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
CMake Error at CMakeLists.txt:47 (project):
  Generator

    Visual Studio 15 2017 Win64

  does not support platform specification, but platform

    x64

  was specified.


-- Configuring incomplete, errors occurred!
See also "C:/WorkRepo/libevent/build64/CMakeFiles/CMakeOutput.log".

C:\WorkRepo\libevent\build64>cmake -G "Visual Studio 15 2017 Win64" -D EVENT__DISABLE_OPENSSL="true" -D EVENT__DISABLE_MBEDTLS="true" ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
-- The C compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.27.0.windows.1")
-- Looking for __GNU_LIBRARY__
-- Looking for __GNU_LIBRARY__ - not found
-- Looking for _GNU_SOURCE
-- Looking for _GNU_SOURCE - not found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include files fcntl.h, inttypes.h
-- Looking for include files fcntl.h, inttypes.h - found
-- Looking for 3 include files fcntl.h, ..., memory.h
-- Looking for 3 include files fcntl.h, ..., memory.h - found
-- Looking for 4 include files fcntl.h, ..., signal.h
-- Looking for 4 include files fcntl.h, ..., signal.h - found
-- Looking for 5 include files fcntl.h, ..., stdarg.h
-- Looking for 5 include files fcntl.h, ..., stdarg.h - found
-- Looking for 6 include files fcntl.h, ..., stddef.h
-- Looking for 6 include files fcntl.h, ..., stddef.h - found
-- Looking for 7 include files fcntl.h, ..., stdint.h
-- Looking for 7 include files fcntl.h, ..., stdint.h - found
-- Looking for 8 include files fcntl.h, ..., stdlib.h
-- Looking for 8 include files fcntl.h, ..., stdlib.h - found
-- Looking for 9 include files fcntl.h, ..., string.h
-- Looking for 9 include files fcntl.h, ..., string.h - found
-- Looking for 10 include files fcntl.h, ..., errno.h
-- Looking for 10 include files fcntl.h, ..., errno.h - found
-- Looking for 11 include files fcntl.h, ..., unistd.h
-- Looking for 11 include files fcntl.h, ..., unistd.h - not found
-- Looking for 11 include files fcntl.h, ..., time.h
-- Looking for 11 include files fcntl.h, ..., time.h - found
-- Looking for 12 include files fcntl.h, ..., sys/types.h
-- Looking for 12 include files fcntl.h, ..., sys/types.h - found
-- Looking for 13 include files fcntl.h, ..., sys/stat.h
-- Looking for 13 include files fcntl.h, ..., sys/stat.h - found
-- Looking for 14 include files fcntl.h, ..., sys/time.h
-- Looking for 14 include files fcntl.h, ..., sys/time.h - not found
-- Looking for 14 include files fcntl.h, ..., sys/param.h
-- Looking for 14 include files fcntl.h, ..., sys/param.h - not found
-- Looking for 14 include files fcntl.h, ..., io.h
-- Looking for 14 include files fcntl.h, ..., io.h - found
-- Looking for 15 include files fcntl.h, ..., winsock2.h
-- Looking for 15 include files fcntl.h, ..., winsock2.h - found
-- Looking for 16 include files fcntl.h, ..., ws2tcpip.h
-- Looking for 16 include files fcntl.h, ..., ws2tcpip.h - found
-- Looking for 17 include files fcntl.h, ..., afunix.h
-- Looking for 17 include files fcntl.h, ..., afunix.h - found
-- Looking for 18 include files fcntl.h, ..., sys/sysctl.h
-- Looking for 18 include files fcntl.h, ..., sys/sysctl.h - not found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - not found
-- Looking for getnameinfo
-- Looking for getnameinfo - not found
-- Looking for getprotobynumber
-- Looking for getprotobynumber - not found
-- Looking for getservbyname
-- Looking for getservbyname - not found
-- Looking for gethostbyname
-- Looking for gethostbyname - not found
-- Looking for inet_ntop
-- Looking for inet_ntop - not found
-- Looking for inet_pton
-- Looking for inet_pton - not found
-- Looking for gettimeofday
-- Looking for gettimeofday - not found
-- Looking for signal
-- Looking for signal - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for splice
-- Looking for splice - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strsep
-- Looking for strsep - not found
-- Looking for strtok_r
-- Looking for strtok_r - not found
-- Looking for vasprintf
-- Looking for vasprintf - not found
-- Looking for timerclear
-- Looking for timerclear - found
-- Looking for timercmp
-- Looking for timercmp - found
-- Looking for timerisset
-- Looking for timerisset - found
-- Looking for timeradd
-- Looking for timeradd - not found
-- Looking for nanosleep
-- Looking for nanosleep - not found
-- Looking for putenv
-- Looking for putenv - found
-- Looking for umask
-- Looking for umask - found
-- Looking for clock_gettime
-- Looking for clock_gettime - not found
-- Looking for _gmtime64_s
-- Looking for _gmtime64_s - found
-- Looking for _gmtime64
-- Looking for _gmtime64 - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of struct sockaddr_un
-- Check size of struct sockaddr_un - done
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of unsigned
-- Check size of unsigned - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Looking for __func__
-- Looking for __func__ - found
-- Looking for __FUNCTION__
-- Looking for __FUNCTION__ - found
-- Looking for TAILQ_FOREACH
-- Looking for TAILQ_FOREACH - not found
-- Performing Test EVENT__HAVE_DECL_CTL_KERN
-- Performing Test EVENT__HAVE_DECL_CTL_KERN - Failed
-- Looking for CTL_KERN - not found
-- Performing Test EVENT__HAVE_DECL_KERN_ARND
-- Performing Test EVENT__HAVE_DECL_KERN_ARND - Failed
-- Looking for KERN_ARND - not found
-- Looking for F_SETFD
-- Looking for F_SETFD - not found
-- Check size of fd_mask
-- Check size of fd_mask - failed
-- Check size of size_t
-- Check size of size_t - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of ssize_t
-- Check size of ssize_t - failed
-- Check size of SSIZE_T
-- Check size of SSIZE_T - done
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Check size of pid_t
-- Check size of pid_t - failed
-- Check size of pthread_t
-- Check size of pthread_t - failed
-- Check size of uintptr_t
-- Check size of uintptr_t - done
-- Check size of void *
-- Check size of void * - done
-- Check size of time_t
-- Check size of time_t - done
-- Check size of struct addrinfo
-- Check size of struct addrinfo - done
-- Check size of struct in6_addr
-- Check size of struct in6_addr - done
-- Check size of sa_family_t
-- Check size of sa_family_t - failed
-- Check size of struct sockaddr_in6
-- Check size of struct sockaddr_in6 - done
-- Check size of struct sockaddr_storage
-- Check size of struct sockaddr_storage - done
-- Check size of struct linger
-- Check size of struct linger - done
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Found PythonInterp: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe (found suitable version "3.6.6", minimum required is "3")
-- Generating regress tests...
-- C:\Program Files\CMake\bin\ctest.exe
--
--         ---( Libevent 2.1.12-stable )---
--
-- Available event backends: WIN32
-- CMAKE_BINARY_DIR:         C:/WorkRepo/libevent/build64
-- CMAKE_CURRENT_BINARY_DIR: C:/WorkRepo/libevent/build64
-- CMAKE_SOURCE_DIR:         C:/WorkRepo/libevent
-- CMAKE_CURRENT_SOURCE_DIR: C:/WorkRepo/libevent
-- PROJECT_BINARY_DIR:       C:/WorkRepo/libevent/build64
-- PROJECT_SOURCE_DIR:       C:/WorkRepo/libevent
-- CMAKE_MODULE_PATH:        C:/WorkRepo/libevent/cmake/
-- CMAKE_COMMAND:            C:/Program Files/CMake/bin/cmake.exe
-- CMAKE_ROOT:               C:/Program Files/CMake/share/cmake-3.18
-- CMAKE_SYSTEM:             Windows-10.0.19041
-- CMAKE_SYSTEM_NAME:        Windows
-- CMAKE_SYSTEM_VERSION:     10.0.19041
-- CMAKE_SYSTEM_PROCESSOR:   AMD64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:
-- CMAKE_BUILD_TYPE:         Release
-- CMAKE_C_COMPILER:         C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe (id , clang 0, GNUC 0)
-- CMAKE_AR:                 C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/lib.exe
-- CMAKE_RANLIB:
--
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    EVENT__DISABLE_MBEDTLS


-- Build files have been written to: C:/WorkRepo/libevent/build64

C:\WorkRepo\libevent\build64>cmake --build . --config Release
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/WorkRepo/libevent/CMakeLists.txt
  buffer.c
C:\WorkRepo\libevent\include\event2/util.h(184): fatal error C1017: invalid integer constant expression [C:\WorkRepo\libevent\build64\event_core_sha
red.vcxproj]
  bufferevent.c
C:\WorkRepo\libevent\include\event2/util.h(184): fatal error C1017: invalid integer constant expression [C:\WorkRepo\libevent\build64\event_core_sha
red.vcxproj]
  bufferevent_filter.c
C:\WorkRepo\libevent\include\event2/util.h(184): fatal error C1017: invalid integer constant expression [C:\WorkRepo\libevent\build64\event_core_sha
red.vcxproj]
  bufferevent_pair.c
C:\WorkRepo\libevent\include\event2/util.h(184): fatal error C1017: invalid integer constant expression [C:\WorkRepo\libevent\build64\event_core_sha
red.vcxproj]
  bufferevent_ratelim.c
C:\WorkRepo\libevent\include\event2/util.h(184): fatal error C1017: invalid integer constant expression [C:\WorkRepo\libevent\build64\event_core_sha
red.vcxproj]
  bufferevent_sock.c
C:\WorkRepo\libevent\include\event2/util.h(184): fatal error C1017: invalid integer constant expression [C:\WorkRepo\libevent\build64\event_core_sha
red.vcxproj]
  event.c
C:\WorkRepo\libevent\include\event2/util.h(184): fatal error C1017: invalid integer constant expression [C:\WorkRepo\libevent\build64\event_core_sha
red.vcxproj]

**Comment by azat** [comment]
@lingyphone Can you attach an archive that will include:
- `CMakeCache.txt`
- `CMakeFiles/CMakeError.log`
- `CMakeFiles/CMakeOutput.log`
(Hope that names are correct)

**Comment by lingyphone** [comment]
[CMakeCache.txt](https://github.com/libevent/libevent/files/5163905/CMakeCache.txt)
[CMakeError.log](https://github.com/libevent/libevent/files/5163907/CMakeError.log)
[CMakeOutput.log](https://github.com/libevent/libevent/files/5163908/CMakeOutput.log)
both HEAD on master and patches-2.1 branch have been tried.

**Comment by lingyphone** [comment]
[event-config.txt](https://github.com/libevent/libevent/files/5164144/event-config.txt)

**Comment by azat** [comment]
There should be `./CMakeFiles/CheckTypeSize/EVENT__SIZEOF_VOID_P.bin`, what it prints?

**Comment by azat** [comment]
Plus there are some warnings (for each check):

```
Determining size of void * passed with the following output:
Change Dir: C:/WorkRepo/libevent/build64/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe cmTC_e1f90.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27040 for x64
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  cl /c /W1 /WX- /diagnostics:classic /O2 /D _WIN32_WINNT=0x0600 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e1f90.dir\Debug\\" /Fd"cmTC_e1f90.dir\Debug\vc141.pdb" /Gd /TC /FIwinsock2.h /FIws2tcpip.h /errorReport:queue C:\WorkRepo\libevent\build64\CMakeFiles\CheckTypeSize\EVENT__SIZEOF_VOID_P.c
  EVENT__SIZEOF_VOID_P.c
  
LINK : warning LNK4044: unrecognized option '/lws2_32.lib'; ignored [C:\WorkRepo\libevent\build64\CMakeFiles\CMakeTmp\cmTC_e1f90.vcxproj]
LINK : warning LNK4044: unrecognized option '/lshell32.lib'; ignored [C:\WorkRepo\libevent\build64\CMakeFiles\CMakeTmp\cmTC_e1f90.vcxproj]
LINK : warning LNK4044: unrecognized option '/ladvapi32.lib'; ignored [C:\WorkRepo\libevent\build64\CMakeFiles\CMakeTmp\cmTC_e1f90.vcxproj]
  cmTC_e1f90.vcxproj -> C:\WorkRepo\libevent\build64\CMakeFiles\CMakeTmp\Debug\cmTC_e1f90.exe
```

Does not looks ok

**Comment by lingyphone** [comment]
> There should be `./CMakeFiles/CheckTypeSize/EVENT__SIZEOF_VOID_P.bin`, what it prints?

It print empty, nothing displayed

**Comment by azat** [comment]
>It print empty, nothing displayed. Not only SIZEOF_VOID_P

Can you dig why?

**Comment by lingyphone** [comment]
Recently I am able to build this project magically, what I did in the past after my last comment is removed MSVC built-in CMake, reinstalled Windows 10 SDK, installed CMAKE x86 version from kitware.com. And tried to build libevent at that time. it doesn't work either even after rebooted windows. But don't know why yesterday it passed the build in the same windows environment after about three weeks.
