### ISSUE TITLE
Extremely high latency when network gets busy, TCP

### ISSUE THREAD

**Issue by std-vector** [libevent/libevent#437]
In our C/S based online game project, we use TCP for network transmission. We include Libevent, utilise a bufferevent for each connection to handling with the network I/O automatically.

It works well before，but the lagging problem comes to the surface recently. When I do some stress testing to make the network busier, the latency becomes extremely high, several seconds or more. The server sinks into a confusing state:
- the average CPU usage decreased (0%-60%-0%-60% repeat, waiting something?)
- the net traffic decreased (nethogs)
- the clients connected to server still alive (netstat & tcpdump)
It looks like something magically slowed all system down, but new connection to server responded quit in time.

When I changed the protocol to UDP (without bufferevent), it works well on the same situation: no obvious latency, the system runs fast. Net traffic is around 3M/S.

The project is running on an Intranet. I also tested the max download speed, nearly 18M/S.

I studied part of Libevent's header files and ducumentations, tried to setup a rate limit to all connections. It did some improvements, but not completely resolved the problem even though I had tried several different configurations. Here is my parameters: read_rate 163840, read_burst 163840, write_rate 163840, write_burst 163840, tick_len 500ms.

Thank you for your help!

**Comment by ploxiln** [comment]
This is why action games use UDP instead of TCP. The waiting and rate control is in the operating system kernel - one unlucky packet loss during one tiny fraction of a second can cause a second or so of delay due to TCP ack / retransmit / window mechanisms. It's mostly not avoidable.
