### ISSUE TITLE
Problem with http client + filter

### ISSUE THREAD

**Issue by van491018** [libevent/libevent#440]
Hi, I tried to create a special http client with libevent-2.1.7-rc but it doesn't work. I need to wrap http protocol within some proprietary protocol so I implemented this proprietary protocol as a filtering bufferevent and called evhttp_connection_base_bufferevent_new() with this bufferevent as argument. I used netcat as server for debugging purpose and no header sent from my program. After some investigation, I found two code fragments in evhttp_connection_cb():
```c
	if (evcon->fd == -1)
		evcon->fd = bufferevent_getfd(bufev);
```

```c
	if (evcon->fd == -1) {
		event_debug(("%s: bufferevent_getfd returned -1",
			__func__));
		goto cleanup;
	}
```
evcon->fd will be -1 because bufferevent_getfd() can't get file descriptor from filtering bufferevent and code related to callback registeration is not executed. Can anyone tell me whether I has misused this library or it's a bug?

**Comment by azat** [comment]
Yep, it is a bug, and it definitely should be fixed, though there [talks](#361) about merging libevhtp, but it is for 2.2

**Comment by van491018** [comment]
Thank you!

**Comment by ghazel** [comment]
I submitted a pull request for this issue: https://github.com/libevent/libevent/pull/611

**Comment by azat** [comment]
patch from #611 (by @ghazel) should fix this (though http code shouldn't have any fd anyway).
@van491018 could you verify that this fixes the issue for you? If so, please close this issue, since fd in http layer is another big story.

**Comment by azat** [comment]
Closed due to inactivity
