### ISSUE TITLE
Building with Cmake does not install pkg-config files

### ISSUE THREAD

**Issue by fornwall** [libevent/libevent#443]
Could something like https://mailman.videolan.org/pipermail/x265-devel/2013-October/001697.html be added?

**Comment by azat** [comment]
Certainly! Right now cmake is [not the for production](https://github.com/libevent/libevent/#cmake-windows-1) but we definitely want it to be it.

> (Note that autoconf is currently the most mature and supported build enviroment for libevent; the cmake instructions here are new and experimental, though they should be solid. We hope that cmake will still be supported in future versions of Libevent, and will try to make sure that happens.)

Ugh, I guess that this can be unnoticed, we should make it more obvious (also `README` looks a bit huge).

P.S. I've added a milestone for `cmake`
