### ISSUE TITLE
Long running test suite due to DNS timeouts

### ISSUE THREAD

**Issue by peterpramb** [libevent/libevent#455]
Running the 2.1.8 test suite takes a long time due to repeated DNS timeouts:

    [msg] Nameserver 127.0.0.1:48550 has failed: request timed out.
    [msg] All nameservers have failed

This is probably due to my build server not being allowed to directly reach other name servers.

Is there an easy way to skip DNS tests requiring external access?

**Comment by peterpramb** [comment]
Note that there is no test failure caused by this, just the test suite takes long to run.

**Comment by azat** [comment]
Hi @peterpramb, this tests use local nameservers (and "127.0.0.1:48550" address confirms this), so this is not because server not allowed to reach other name servers.

**Comment by peterpramb** [comment]
Hm, ok - I thought the test suite would spawn a local resolver which times out.

Have to further check for the root cause...

**Comment by peterpramb** [comment]
Ok, one step further - from the test log:

    http/cancel_by_host_no_ns: [forking]
        OK test/regress_http.c:1431: assert(regress_dnsserver(data->base, &portnum, search_table))
        OK test/regress_http.c:1434: assert(dns_base)
        OK test/regress_http.c:1469: assert(evcon)
             OK test/regress_http.c:1490: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/delay") != -1): 0 vs -1
             OK test/regress_http.c:1501: assert(test_ok == 2): 2 vs 2
             OK test/regress_http.c:1521: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
    [msg] Nameserver 127.0.0.1:42727 has failed: request timed out.
    [msg] All nameservers have failed
        OK test/regress_http.c:1300: assert(!req)
             OK test/regress_http.c:1541: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
        OK test/regress_http.c:1300: assert(!req)

    http/cancel_by_host_no_ns_inactive_server: [forking]
        OK test/regress_http.c:1431: assert(regress_dnsserver(data->base, &portnum, search_table))
        OK test/regress_http.c:1434: assert(dns_base)
        OK test/regress_http.c:1469: assert(evcon)
             OK test/regress_http.c:1490: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/delay") != -1): 0 vs -1
             OK test/regress_http.c:1501: assert(test_ok == 2): 2 vs 2
             OK test/regress_http.c:1521: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
    [msg] Nameserver 127.0.0.1:41585 has failed: request timed out.
    [msg] All nameservers have failed
        OK test/regress_http.c:1300: assert(!req)
             OK test/regress_http.c:1541: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
        OK test/regress_http.c:1300: assert(!req)

    http/cancel_by_host_ns_timeout: [forking]
        OK test/regress_http.c:1431: assert(regress_dnsserver(data->base, &portnum, search_table))
        OK test/regress_http.c:1434: assert(dns_base)
        OK test/regress_http.c:1469: assert(evcon)
             OK test/regress_http.c:1490: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/delay") != -1): 0 vs -1
             OK test/regress_http.c:1501: assert(test_ok == 2): 2 vs 2
             OK test/regress_http.c:1521: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
    [msg] Nameserver 127.0.0.1:43121 has failed: request timed out.
    [msg] All nameservers have failed
        OK test/regress_http.c:1300: assert(!req)
             OK test/regress_http.c:1541: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
        OK test/regress_http.c:1300: assert(!req)

    http/cancel_by_host_ns_timeout_inactive_server: [forking]
        OK test/regress_http.c:1431: assert(regress_dnsserver(data->base, &portnum, search_table))
        OK test/regress_http.c:1434: assert(dns_base)
        OK test/regress_http.c:1469: assert(evcon)
             OK test/regress_http.c:1490: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/delay") != -1): 0 vs -1
             OK test/regress_http.c:1501: assert(test_ok == 2): 2 vs 2
             OK test/regress_http.c:1521: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
    [msg] Nameserver 127.0.0.1:40686 has failed: request timed out.
    [msg] All nameservers have failed
        OK test/regress_http.c:1300: assert(!req)
             OK test/regress_http.c:1541: assert(evhttp_make_request(evcon, req, EVHTTP_REQ_GET, "/test") != -1): 0 vs -1
        OK test/regress_http.c:1300: assert(!req)

    dns/disable_when_inactive_no_ns: [forking]
        OK test/regress_dns.c:978: assert(inactive_base)
        OK test/regress_dns.c:981: assert(regress_dnsserver(inactive_base, &portnum, search_table))
        OK test/regress_dns.c:985: assert(!evdns_base_nameserver_ip_add(dns, buf))
        OK test/regress_dns.c:986: assert(! evdns_base_set_option(dns, "timeout:", "0.1"))
    [msg] Nameserver 127.0.0.1:49258 has failed: request timed out.
    [msg] All nameservers have failed
             OK test/regress_dns.c:994: assert(n_replies_left == 0): 0 vs 0
             OK test/regress_dns.c:996: assert(r.result == DNS_ERR_TIMEOUT): 67 vs 67
             OK test/regress_dns.c:997: assert(r.count == 0): 0 vs 0
             OK test/regress_dns.c:998: assert(r.addrs == NULL): (nil) vs (nil)

**Comment by azat** [comment]
This tests checks behavior when nameserver is not available - to check that everything works as expected even if is not available (i.e. evdns will fail the request in the end), also some of them enable nameserver after some period and validates that evdns will resolv hostname correctly when nameserver will became available, so this messages about "request timed out" and "All nameservers have failed" expected.

**Comment by peterpramb** [comment]
Ok, seems like the long running test suite is not caused by DNS timeouts - will try to identify the long running tests.

Closing this issue, thx.

**Comment by azat** [comment]
Well some long-running tests indeed because of DNS timeouts, but they are meant to be there, but I'm pretty sure that some of them, we can reduce using evdns options.
