### ISSUE TITLE
wrong output so's version

### ISSUE THREAD

**Issue by BrentHuang** [libevent/libevent#456]
I build libevent-2.1.8-stable.tar.gz, but the output is 'libevent-2.1.so.6.0.2'. Version not match.

**Comment by azat** [comment]
Yeah it is a bit confusing, but according to [libtool](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html) it is the right way [to do](https://github.com/libevent/libevent/blob/ffbce578c40a06491ce6585ab2d82ebb69a52d30/Makefile.am#L31).

P.S. 2.0.x also has the same `VERSION_INFO`
