### ISSUE TITLE
how to get server's ip 

### ISSUE THREAD

**Issue by liudf0716** [libevent/libevent#459]
when  simulated http client using libevent, I can not find method to get http server's ip. does someone meet the same problem as me.  or  can someone give me advise? thanks

**Comment by azat** [comment]
You can use [`evhttp_connection_get_addr()`](http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/http_8h.html#ae0097ea31d96c509962b3d3df5ca6958)

But there is some trickiness, you don't have connection when request completed (`evhttp_request_get_connection()` returns `NULL`), so you should save it somewhere else.

**Comment by liudf0716** [comment]
thanks, I will report the result after trying this api.

**Comment by liudf0716** [comment]
I think I have tried this api, but I get address 0.0.0.0. maybe I use this api in wrong position
