### ISSUE TITLE
arc4random compiled/linked in on SmartOS

### ISSUE THREAD

**Issue by jurajlutter** [libevent/libevent#463]
Hi,

there is a problem compiling *libevent-2.1.8-stable* under SmartOS:

```
[builder@sosbuild02 /opt/pkgsrc/devel/libevent]$ bmake
=> Bootstrap dependency digest>=20010302: found digest-20160304
===> Building for libevent-2.1.8
--- evconfig-private.h ---
--- all ---
/opt/local/bin/bmake  all-am
--- evconfig-private.h ---
--- sample/dns-example ---
--- sample/event-read-fifo ---
--- sample/dns-example ---
  CCLD     sample/dns-example
--- sample/event-read-fifo ---
  CCLD     sample/event-read-fifo
Undefined                       first referenced
--- sample/dns-example ---
Undefined                       first referenced
--- sample/event-read-fifo ---
 symbol                             in file
--- sample/dns-example ---
 symbol                             in file
--- sample/event-read-fifo ---
arc4random_addrandom                ./.libs/libevent.so
--- sample/dns-example ---
arc4random_addrandom                ./.libs/libevent.so
--- sample/event-read-fifo ---
ld: fatal: symbol referencing errors. No output written to sample/.libs/event-read-fifo
--- sample/dns-example ---
ld: fatal: symbol referencing errors. No output written to sample/.libs/dns-example
--- sample/event-read-fifo ---
collect2: error: ld returned 1 exit status
--- sample/dns-example ---
collect2: error: ld returned 1 exit status
*** [sample/dns-example] Error code 1
```

arc4random.c is not being compiled and linked where it should be.

How this can be fixed? I'm not an GNU autotools magician :-)

**Comment by azat** [comment]
Refs #370

**Comment by azat** [comment]
@jurajlutter can you try compile libevent from the next url?

    https://github.com:azat/libevent cmake-configure-fixes

**Comment by jurajlutter** [comment]
Something around `epoll` is being misdetected.

```
[builder@sosbuild02 ~/build/src/libevent/libevent]$ bmake
[  1%] Building C object CMakeFiles/event_extra.dir/epoll_sub.c.o
/home/builder/build/src/libevent/libevent/epoll_sub.c: In function 'epoll_create':
/home/builder/build/src/libevent/libevent/epoll_sub.c:47:18: error: '__NR_epoll_create' undeclared (first use in this function)
  return (syscall(__NR_epoll_create, size));
                  ^
/home/builder/build/src/libevent/libevent/epoll_sub.c:47:18: note: each undeclared identifier is reported only once for each function it appears in
/home/builder/build/src/libevent/libevent/epoll_sub.c: In function 'epoll_ctl':
/home/builder/build/src/libevent/libevent/epoll_sub.c:55:18: error: '__NR_epoll_ctl' undeclared (first use in this function)
  return (syscall(__NR_epoll_ctl, epfd, op, fd, event));
                  ^
/home/builder/build/src/libevent/libevent/epoll_sub.c: In function 'epoll_wait':
/home/builder/build/src/libevent/libevent/epoll_sub.c:64:18: error: '__NR_epoll_wait' undeclared (first use in this function)
  return (syscall(__NR_epoll_wait, epfd, events, maxevents, timeout));
                  ^
/usr/include/sys/epoll.h: In function 'epoll_create':
/home/builder/build/src/libevent/libevent/epoll_sub.c:49:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/usr/include/sys/epoll.h: In function 'epoll_ctl':
/home/builder/build/src/libevent/libevent/epoll_sub.c:56:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/usr/include/sys/epoll.h: In function 'epoll_wait':
/home/builder/build/src/libevent/libevent/epoll_sub.c:66:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
*** Error code 1
```

**Comment by azat** [comment]
Can you please share (gists is preferable I guess):
- `CMakeCache.txt`
- `include/event2/event-config.h`
- `include/evconfig-private.h`

**Comment by ploxiln** [comment]
hmm, epoll() is linux specific, but SmartOS has "LX branded zones" aka linux syscall emulation zones, is it possible that is confusing the configure step? (are you running in some kind of zone?)

**Comment by azat** [comment]
According to nanomsg/nanomsg#431 epoll added to smartos, and no special headers required, so we need config headers and cmake caches to investigate this.

**Comment by azat** [comment]
And according to some logs there are no syscall numbers for epoll. More interesting thing is that before you don't have such error, @jurajlutter maybe you updated something?

**Comment by azat** [comment]
I think that at first time you are used autoconf/automake to build, but now you are using cmake, am I right?


- `sample/.libs` from the first message, is relevant for `autotools`
- `CMakeFiles/event_extra.dir` is relevant for `cmake`

**Comment by jurajlutter** [comment]
OK, so, using autoconf (created from within autogen,sh) it works, compiles and runs.

Using CMake there still is an error:

`/home/builder/build/src/libevent/libevent/epoll_sub.c:64:18: error: '__NR_epoll_wait' undeclared (first use in this function)
  return (syscall(__NR_epoll_wait, epfd, events, maxevents, timeout));`

This is linux-specific library call, which is, for obvious reasons, not available on SmartOS. On SmartOS, there is `epoll.h` header file with apropriate epoll() functions, etc.

Using CMake, some conditional defines are not being initialized properly, causing the subsequent `make`  think that it's being compiled on Linux.

**Comment by jurajlutter** [comment]
When compiling on SmartOS, one should include system-wide `epoll.h` and NOT include `epoll_sub.c` from libevent. This is the reason why the build using CMake fails.

**Comment by jurajlutter** [comment]
Or, conditionally check in epoll_sub.c presence of needed #defines.

**Comment by azat** [comment]
Finally I successfully started smartos in vagrant, to check this, and indeed everything works without wrappers (I was worried not about `epoll_sub.c` - most of the OS'es/libc's have wrappers for epoll, but about some other things which can be broken, but `make verify` passed).

That said, I just pushed this changes to master. @jurajlutter Please go and test this.

**Comment by jurajlutter** [comment]
I approve! 👍

**Comment by azat** [comment]
Great, thanks!
