### ISSUE TITLE
maintain different user supplied pointer at pass it on the API of set callbacks of evconlistener and evbufferevent

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#464]
hi,
i have created a struct type pointer and i am passing it on 
void bufferevent_setcb(struct bufferevent *bufev,
    bufferevent_data_cb readcb, bufferevent_data_cb writecb,
    bufferevent_event_cb eventcb, void *cbarg);  
 in this cbarg pointer i get the last updated value but not value as passed in the callback attached as a context.Is there a way to achieve that 
Thanks,
Kushal

**Comment by azat** [comment]
If I understand you correctly, than the answer will be now, since it accept *pointer*, but you can modify your program so that it will allocate that argument every time you need new *value*.

**Comment by kushal4** [comment]
actually what i want is suppose when some read callback is called i want to pass the corresponding sock_fd  on the pointer(as struct ) and i want to get that on every read callback i tried allocating new value  to it but it gives the last updated value not the value running in its context as the callback does

**Comment by azat** [comment]
There is no context for callbacks besides your `arg` (since they are called from the event loop). Can you post an example (~50 lines) of what you trying to do?

**Comment by azat** [comment]
I wrote two examples:

### [basic case](https://gist.github.com/azat/298b62d4a1290270f4dd721b6cfb54f4#file-be-arg-c)
```
read_cb(i)=1
write_cb(i)=2
read_cb(i)=3
write_cb(i)=4
```

### [and malloc every time](https://gist.github.com/azat/298b62d4a1290270f4dd721b6cfb54f4#file-be-arg-val-c)
```
read_cb(i)=1
write_cb(i)=1
read_cb(i)=1
write_cb(i)=1
```

But I'm not sure that this is the desired, plus it is very easy to for pointers to leak in this example (and I do not clean them).

**Comment by kushal4** [comment]
ok 
for example 
i have struct of format
struct info {
    string name;
    size_t sock_fd;
};
this code below is on a normal function 
struct info *info1;

    info1 = new info();
    buf_count=buf_count+1;
    info1->name = string("buffer ")+(to_string(buf_count));
    info1->sock_fd = 0;
then i am passing is info1 to evconnlistener_new_bind  with the onAccept callback and within the onAccept callback  -:
struct info* info1=(struct info*)cbarg;
    info1->sock_fd= fd ;
    cout<<"THE ACCEPTED SOCK FD USER POINTER IS"<<info1->sock_fd<<endl;
where cbarg is the pointer passed along with the onAccept callback
again this info1 is passed to  bufferevent_setcb as the pointer and i expect this pointer's sockfd from within the readcallback to be the same as the sock_fd fetched from the readcallback

**Comment by kushal4** [comment]
to be more clear i am using libevent  to build mqtt broker so when normal CONNECT packet is recieved by broker it is ok but suppose the existing sockets (may be random one) recieves any control packet then on the read callback i should expect the value of the sock_fd given by readcallback and the value from the userpointer's sockfd must be same but i am getting the last updated value which was done on onAccept callback

**Comment by azat** [comment]
Of course you got the last value since it is **pointer**, you should allocate new `struct info` in `acceptcb` if you need a copy of it in `readcb` (and if I understand you correctly that you need new structure).

**Comment by kushal4** [comment]
ok i am making these changes now and letting u know :)

**Comment by kushal4** [comment]
its working thankx :)   hope my next subsequent tasks works now :)
