### ISSUE TITLE
bufferevent_openssl.c:66:10: fatal error: 'openssl/bio.h' file not found

### ISSUE THREAD

**Issue by jakobsen9** [libevent/libevent#465]
Hello,

I get this error when installing: `bufferevent_openssl.c:66:10: fatal error: 'openssl/bio.h' file not found`. First I run `./configure` without problems, then `make`, which gives me the error.

I have tried the two latest stable releases, and getting the same problem. Using OS X.

**Comment by azat** [comment]
Hi @jakobsen9 , please take a look at [this comment](https://github.com/libevent/libevent/issues/360#issuecomment-279690784)

**Comment by jakobsen9** [comment]
I did that @azat, but still not helping. `error: unable to open output file
      '.libs/libevent_openssl_la-bufferevent_openssl.o': 'Permission denied'`
I ran it as admin/sudo.

**Comment by azat** [comment]
What did you run under `sudo`? Can you post all executed commands (from scratch)?

**Comment by jakobsen9** [comment]
@azat first o downloaded the libevent-2.1.8-stable.tar.gz from libevent.org.

cd libevent-2.1.8-stable
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib
sudo ./configure
sudo make // bufferevent_openssl.c:66:10: fatal error: 'openssl/bio.h' file not found

then tried:
sudo PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig ./configure && make // error: unable to open output file
      '.libs/libevent_openssl_la-bufferevent_openssl.o': 'Permission denied'

**Comment by azat** [comment]
The second command, `make` executed from regular user not from `root`, and BTW you don't need root to compile libevent, so just remove current unpacked dir, unpack again and do not use `sudo`, then there shouldn't be any `permissions denied` errors

**Comment by azat** [comment]
Also can you please confirm that `/usr/local/opt/openssl/include` contains `openssl/bio.h` ?

**Comment by jakobsen9** [comment]
@azat what path is that, where is it?

**Comment by azat** [comment]
In your file system, where you should have `openssl/bio.h`, so can you post output of:
```shell
ls -l /usr/local/opt/openssl/include/openssl/
```

**Comment by jakobsen9** [comment]
Is that supposed to be an existing path in OS X? I can't find it...

**Comment by azat** [comment]
Then you don't have installed openssl libraries, you can use `brew` for this, i.e.:
```sh
brew install openssl
```

**Comment by bhirbec** [comment]
Had the same issue. Solve this by installing [openssl](https://www.openssl.org/source/). I just followed instructions in the INSTALL:

```
  on Unix:

    $ ./config
    $ make
    $ make test
    $ make install
```

**Comment by azat** [comment]
@jakobsen9 should I close this issue or you still have problems with building libevent with openssl?

**Comment by kylezhang** [comment]
解决办法： 
在`bash_profile`中配置环境变量加上下面两行 
```
export CPPFLAGS=-I/usr/local/opt/openssl/include 
export LDFLAGS=-L/usr/local/opt/openssl/lib 
```
再重新`make`即可
