### ISSUE TITLE
issues when adding multiple bufferevent flags 

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#467]
The thing i am transferring the data which is read from server via socket to multiple threads so i am setting bufferevent flags like 
```c
 int flags = BEV_OPT_THREADSAFE | BEV_OPT_CLOSE_ON_FREE;
  bufferevent_setcb(be, readcb, writecb, eventcb, cbarg);
```
when i am doing this i am getting some error that ' failed to create libevent bufferevent and the server program stops receiving from the client '.Could you please tell me where am i going wrong? Is it the correct way to set multiple flags?

**Comment by kushal4** [comment]
when i only set the second flag only it works well for joinable threads but when i use it for parrallel thread the data is not well read from the socket i mean i dont recieve the desired characters send from the client end to server but in the wireshark i see the client sends the character properly even when using parrallel thread

**Comment by kushal4** [comment]
how to enable thread support for bufferevent

**Comment by azat** [comment]
Can you please reduce you program to 100 lines reproducer (or something like this) and post it here or [here](gist.github.com) ?

**Comment by kushal4** [comment]
hi,
This issue has been solved for now will update here if any problem crops up anytime 
Thanks ,
Kushal

**Comment by kushal4** [comment]
i am using smart pointers now and due to that the problem is not occuring till now
