### ISSUE TITLE
About DPDK

### ISSUE THREAD

**Issue by armman475** [libevent/libevent#471]
I would like to use libevent on the DPDK(Data Plane Development Kit) platform.Have any ideas and suggestions?

**Comment by azat** [comment]
Can you give some details on this?

**Comment by armman475** [comment]
In this article [Understand DPDK](http://www.slideshare.net/garyachy/dpdk-44585840?related=1), DPDK requires a userspace TCP/IP stack.
So, I would like to know whether libevent's socket needs to be modified.

**Comment by azat** [comment]
So I looked at DPDK, and it is *not a networking userspace* (so does libevent).

But there is a [tcp/ip stack for dpdk](https://github.com/opendp/dpdk-ans) and if you want to use libevent over `dpdk-ans` then you need to replace `read`/`write`/... with `ans_read`/`ans_write`/.. and there is an example of modifying [nginx](https://github.com/opendp/dpdk-nginx)/[redis](https://github.com/opendp/dpdk-redis) for `dpdk-ans`

And this is just how it looks like for me (after first look at dpdk).

So the question is, what will libevent do there?

**Comment by armman475** [comment]
Thanks @azat.
DPDK can improve performance quickly. Does Libevent consider supporting development on the DPDK platform?

**Comment by azat** [comment]
I'm not sure that I can answer to this question right now, since I didn't use dpdk, but who knows. Actually during looking into this a few days ago, I though that this can be implemented with preloading some library but not sure that it will be a good generic decision.

**Comment by liudf0716** [comment]
libevent depends on tcp/ip stack, but DPDK build their own tcp/ip stack. I don't think need to do that job.

**Comment by pprindeville** [comment]
> libevent depends on tcp/ip stack, but DPDK build their own tcp/ip stack. I don't think need to do that job.

This is a specious argument.  There's HTTP and SSL support baked into `libevent`, without having to write either from scratch.  You just link in the appropriate dependencies.

DPDK would be no different.
