### ISSUE TITLE
https-client.c: no need to SSL_free when HTTPS

### ISSUE THREAD

**Issue by liudf0716** [libevent/libevent#472]
In https-client.c of sample, I noticed the following code : 
cleanup:
```c
	if (evcon)
		evhttp_connection_free(evcon);
	if (http_uri)
		evhttp_uri_free(http_uri);
	event_base_free(base);

	if (ssl_ctx)
		SSL_CTX_free(ssl_ctx);
	if (type == HTTP && ssl)                                           // <-- here
		SSL_free(ssl);
#if (OPENSSL_VERSION_NUMBER < 0x10100000L) || defined(LIBRESSL_VERSION_NUMBER)
	EVP_cleanup();
	ERR_free_strings();
 ```
that means when in https mode, no need to do SSL_free, we don't need to worry about memory leak here ?

**Comment by azat** [comment]
Yep, because:
- `SSL_new()` called regardless it is http or https request
- but if it is **https** then it will be freed [by libevent](https://github.com/libevent/libevent/blob/cc0e04d798643b76ce1874213cb6cc3b2c6b5ac4/bufferevent_openssl.c#L1238) because of `BEV_OPT_CLOSE_ON_FREE`

**Comment by liudf0716** [comment]
@azat  thanks. In fact, I have tried to free it, but encounter segment fault.
