### ISSUE TITLE
what's the difference between libevent2, libevent2-extra, libevent2-core, libevent2-openssl and libevent_pthread

### ISSUE THREAD

**Issue by liudf0716** [libevent/libevent#473]
why there are so many library? what kind scenario which one should be used?
I noticed libevent2-core also need libcrypto,  so why also define libevent2-openssl?
when I submitted pull request for LEDE project, many reviewer asked me why set depends openssl for libevent2-core, I must explain  if not , it can not be compiled. anyway, I must admit it really looks ugly, since we have defined libevent2-openssl , but we must add depend openssl for libevent2-core, It looks unreanonable.
Ps:
I think no need to define so many library, it will confuse developer and not good for our project spreading.

**Comment by liudf0716** [comment]
here is my PR
https://github.com/lede-project/source/pull/848

**Comment by ploxiln** [comment]
I did a quick check of libevent 2.0.x installed from the standard package on ubuntu 16.04, and libevent_core does not link to openssl:

```
$ readelf -d /usr/lib/x86_64-linux-gnu/libevent_*.so.5.1.9 | grep '^File\|(NEEDED)'
File: /usr/lib/x86_64-linux-gnu/libevent_core-2.0.so.5.1.9
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
File: /usr/lib/x86_64-linux-gnu/libevent_extra-2.0.so.5.1.9
 0x0000000000000001 (NEEDED)             Shared library: [libevent_core-2.0.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
File: /usr/lib/x86_64-linux-gnu/libevent_openssl-2.0.so.5.1.9
 0x0000000000000001 (NEEDED)             Shared library: [libevent_core-2.0.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libssl.so.1.0.0]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.0.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
File: /usr/lib/x86_64-linux-gnu/libevent_pthreads-2.0.so.5.1.9
 0x0000000000000001 (NEEDED)             Shared library: [libevent_core-2.0.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

**Comment by ploxiln** [comment]
and for what it's worth, libevent-2.0.22 installed via homebrew on OS X, libevent_core does not link to libpthread either:

```
$ otool -L /usr/local/lib/libevent_*-2.0.5.dylib
/usr/local/lib/libevent_core-2.0.5.dylib:
	/usr/local/lib/libevent_core-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
/usr/local/lib/libevent_extra-2.0.5.dylib:
	/usr/local/lib/libevent_extra-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
/usr/local/lib/libevent_openssl-2.0.5.dylib:
	/usr/local/lib/libevent_openssl-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
/usr/local/lib/libevent_pthreads-2.0.5.dylib:
	/usr/local/lib/libevent_pthreads-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

That's the reason for the different libraries - avoid the need to link to other libraries when not needed for a particular application.

**Comment by liudf0716** [comment]
@ploxiln  please check version 2.1.8-stable.
I can understand  "avoid the need to link to other libraries when not need for a particular application"
but for a libevent beginner, did u know which library u should use? libevent2 or libevent2-core or libevent2-extra, by the end, maybe u will link them all.

**Comment by ploxiln** [comment]
I see that in libevent-2.1.8 (installed with homebrew on OS X) libevent_core does link to libcrypto. I'm pretty sure that's a bug in the build process.

Regarding "beginners", the manual says:
> Every program that uses Libevent must include the <event2/event.h> header, and pass the -levent flag to the linker. (You can instead link -levent_core if you only want the main event and buffered IO-based code, and don't want to link any protocol code.)

That's pretty clear. Beginners can just use `-levent` when linking.

**Comment by ploxiln** [comment]
It's a bug in `configure.ac` (or possibly `libevent_openssl.m4` I guess, this stuff is cryptic to me). `LIBS = -lcrypto` ends up in `Makefile`.

I wonder if this part of `configure.ac` causes it:

```
if test "x$enable_openssl" = "xyes"; then
      AC_SEARCH_LIBS([ERR_remove_thread_state], [crypto eay32],
              [AC_DEFINE(HAVE_ERR_REMOVE_THREAD_STATE, 1, [Define to 1 if you have ERR_remove_thread_stat().])])
fi
```

If I remove that from `configure.ac`, libevent builds successfully, and libevent_core does not link to libcrypto. Tested on both macOS and Linux.

**Comment by liudf0716** [comment]
@ploxiln  I totally agree with what u say. but u known, when u firstly use a library, do u known exactly which api u should use? of course, for an experienced one ,it's ok.  that why I say it will not help spreading libevent for developer.

**Comment by liudf0716** [comment]
in fact, all libevent library depends libcrypto

**Comment by azat** [comment]
So in a nutshell:
- event_core: all basic stuff
- event_pthreads: libevent pthread support
- event_openssl: linked with openssl
- event_extra: event_tagging/http/dns/rpc

And **"event" is a deprecated** library (it may go away in future versions, and I guess that it should already, since it only introduces more questions), it is better to use event_core instead, and if you need something more linking with more libraries.

> I think no need to define so many library, it will confuse developer and not good for our project spreading.

If we will link with openssl (ssl/crypto) everytime then if application uses it's own version of openssl it will have bugs (though many linkers will notice that binary has two versions of ssl), but:

> libevent library depends libcrypto

Indeed there is a bug, and it will be fixed ASAP.

Hope this helps.

P.S. right now cmake build differs from autotools, and autotools is more production (cmake is the latest added), see #246

**Comment by liudf0716** [comment]
@azat thanks for your wonderful explanation!
