### ISSUE TITLE
select return immediately on win32 platform

### ISSUE THREAD

**Issue by ideal-miao** [libevent/libevent#474]
I'm new to this library and get a problem with `libevent/samples/hello-world.c`
I don't need to use bufferevent, so I changed the code to this:

```c
static void conn_testcb(evutil_socket_t fd, short event, void * ptr) {
	printf("event=%d\n", event);
}

static void
listener_cb(struct evconnlistener *listener, evutil_socket_t fd,
    struct sockaddr *sa, int socklen, void *user_data) {
	struct event * test_event = event_new(base, fd, EV_READ | EV_WRITE | EV_PERSIST | EV_FINALIZE, conn_testcb, event_self_cbarg());
	event_add(test_event, NULL);
}

int main() {
	....
	listener = evconnlistener_new_bind(base, listener_cb, (void *)base,
	    LEV_OPT_REUSEABLE|LEV_OPT_CLOSE_ON_FREE, -1,
	    (struct sockaddr*)&sin,
	    sizeof(sin));
	....
}
```

after the program have started, use command `nc ip port` to connect the server, it turns out `function conn_testcb()` will be called infinitely  even if the client has been terminated. I step into the code, and find the deep reason is `select()` always return immediately.
this problem bother me several days, any suggestion will be appreciated.

**Comment by azat** [comment]
How do you detect that client is gone?

The original code has:
```
static void
conn_eventcb(struct bufferevent *bev, short events, void *user_data)
{
    if (events & BEV_EVENT_EOF) {
        printf("Connection closed.\n");
    } else if (events & BEV_EVENT_ERROR) {
        printf("Got an error on the connection: %s\n",
            strerror(errno));/*XXX win32*/
    }
    /* None of the other events can happen here, since we haven't enabled
     * timeouts */
    bufferevent_free(bev);
}
```

If you doesn't want to use bufferevents, that you should check it by your self, using something like this in your callback:
```c
static void conn_testcb(evutil_socket_t fd, short event, void *arg)
{
    if (event & EV_READ) {
        char buf;
        /* it is better to read all available buffer here */
        int len = recv(fd, &buf, sizeof(buf), 0);
        if (!len)
            event_del(arg);
    }
}
```

**Comment by azat** [comment]
@ideal-miao any update on this?

**Comment by ideal-miao** [comment]
@azat thanks for you advice, i understand how to control the life cycle of the socket file descriptor now.
And i want to ask another related question: i  add EV_READ | EV_WRITE | EV_PERSIST when creating new event,  but in my application, read frequency is much more higher than write,  so when the socket is available to write, the write_cb is called repeatedly but do nothing valuable，is there a common used mechanism to avoid this CPU load?
My solution for now is to invoke send() function directly when output buffer is already, and avoid EV_WRITE  flag when creating new event.

**Comment by azat** [comment]
I'm not sure I follow you, there is no writecb for `event` (it is only for `bufferevent`).

If you have (for the same fd) more reads then writes, then no problem your callback will be called for read/write.

> when output buffer is already
already what?

**Comment by ideal-miao** [comment]
my source code looks something like this:`#define REG_EV_WRITE 0
class Session {
public :
	void onEventCallback(evutil_socket_t fd, short events) {
		if (events & EV_READ) {
			//read and save into m_iInBufferQueue;
			...
		}
		
#if REG_EV_WRITE
		if (events & EV_WRITE) {
			flush();
		}
#else
		flush();
#endif
	}
		
	void flush() {
		//send data if m_iOutBufferQeueue is not empty
		while (!m_iOutBufferQeueue->empty()) {
			//dequeue from m_iOutBufferQeueue and send
			auto buffer = m_iOutBufferQeueue.begin();
			int ret = send(fd, buffer.raw(), buffer.size(), 0);
			....
		}
	}
private:
	std::queue<MBuffer> m_iInBufferQueue;
	std::queue<MBuffer> m_iOutBufferQeueue;
}

void _listener_cb(struct evconnlistener * listener, evutil_socket_t fd, struct sockaddr * addr, int socklen, void *args) {
#if REG_EV_WRITE
	event * ev = event_new(m_pEventBase, fd, EV_READ | EV_WRITE | EV_PERSIST, _event_callback, session.get());
#else
	event * ev = event_new(m_pEventBase, fd, EV_READ | EV_PERSIST, _event_callback, session.get());
#endif
	event_add(ev, NULL);
}

void _event_callback(evutil_socket_t fd, short events, void * user_data) {
	Session * session = (Session *)user_data;
	session->onEventCallback(fd, events);
}` 
if #define REG_EV_WRITE 1,flush() function will be called many times but send nothing mostly in my application; if #define REG_EV_WRITE 0,data will be send unless flush() function is called manually or triggered by EV_READ.
As for now, the second way seems suitable for me. thanks for your help again.

**Comment by azat** [comment]
Aha, I see what is going on here, and the reason for this is then socket is always ready for writing, you should use separate event for `EV_WRITE` without `EV_PERSIST` (on the same fd) and add it into event_base only when you need it.
Also take a look at `EV_ET` (edge-triggered events, but this is not the `select()` case)

**Comment by ideal-miao** [comment]
That's seems better than call flush() manually, i will try this way.
