### ISSUE TITLE
Failed to build with Android NDK (CMake)

### ISSUE THREAD

**Issue by semigodking** [libevent/libevent#475]
I was trying to build libevent with Android NDK.  CMake can generate Makefile. 

`
cmake -d -DCMAKE_TOOLCHAIN_FILE=~/ndk/android-ndk-r13b/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=gcc -DOPENSSL_INCLUDE_DIR=~/openssl-1.1.0e/include -DOPENSSL_SSL_LIBRARY=~/openssl-1.1.0e/  -DOPENSSL_CRYPTO_LIBRARY=~/openssl-1.1.0e/ ..
`

Compilation fails with the following errors.

`[ 13%] Building C object CMakeFiles/event_extra.dir/evthread_pthread.c.o
/home/ubuntu/ndk/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  --sysroot=/home/ubuntu/ndk/android-ndk-r13b/platforms/android-9/arch-arm -DHAVE_CONFIG_H -DTINYTEST_LOCAL -I/home/ubuntu/libevent/build/include -I/home/ubuntu/libevent/include -I/home/ubuntu/libevent/compat -I/home/ubuntu/libevent -I/home/ubuntu/openssl-1.1.0e/include  -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wswitch -fno-strict-aliasing -Os -DNDEBUG    -std=gnu99 -o CMakeFiles/event_extra.dir/evthread_pthread.c.o   -c /home/ubuntu/libevent/evthread_pthread.c
/home/ubuntu/libevent/evthread_pthread.c: In function 'evthread_posix_get_id':
/home/ubuntu/libevent/evthread_pthread.c:90:29: error: operator '>' has no left operand
 #if EVENT__SIZEOF_PTHREAD_T > EVENT__SIZEOF_LONG
                             ^
/home/ubuntu/libevent/evthread_pthread.c:96:29: error: operator '<' has no left operand
 #if EVENT__SIZEOF_PTHREAD_T < EVENT__SIZEOF_LONG
                             ^
CMakeFiles/event_extra.dir/build.make:566: recipe for target 'CMakeFiles/event_extra.dir/evthread_pthread.c.o' failed
make[2]: *** [CMakeFiles/event_extra.dir/evthread_pthread.c.o] Error 1
make[2]: Leaving directory '/home/ubuntu/libevent/build'
CMakeFiles/Makefile2:725: recipe for target 'CMakeFiles/event_extra.dir/all' failed
make[1]: *** [CMakeFiles/event_extra.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/libevent/build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by semigodking** [comment]
By checking logs, I found pthread_t check failed. The generated EVENT__SIZEOF_PTHREAD_T.c does not have pthread.h included. 

/usr/bin/make -f CMakeFiles/cmTC_2ffea.dir/build.make CMakeFiles/cmTC_2ffea.dir/build
make[1]: Entering directory '/home/ubuntu/libevent/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2ffea.dir/EVENT__SIZEOF_PTHREAD_T.c.o
/home/ubuntu/ndk/android-ndk-r14-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  --sysroot=/home/ubuntu/ndk/android-ndk-r14-beta2/platforms/android-9/arch-arm   -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wswitch -fno-strict-aliasing  -O0    -o CMakeFiles/cmTC_2ffea.dir/EVENT__SIZEOF_PTHREAD_T.c.o   -c /home/ubuntu/libevent/build/CMakeFiles/CheckTypeSize/EVENT__SIZEOF_PTHREAD_T.c
/home/ubuntu/libevent/build/CMakeFiles/CheckTypeSize/EVENT__SIZEOF_PTHREAD_T.c:23:22: error: 'pthread_t' undeclared here (not in a function)
 #define SIZE (sizeof(pthread_t))
                      ^
/home/ubuntu/libevent/build/CMakeFiles/CheckTypeSize/EVENT__SIZEOF_PTHREAD_T.c:25:12: note: in expansion of macro 'SIZE'
   ('0' + ((SIZE / 10000)%10)),
            ^
CMakeFiles/cmTC_2ffea.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_2ffea.dir/EVENT__SIZEOF_PTHREAD_T.c.o' failed
make[1]: *** [CMakeFiles/cmTC_2ffea.dir/EVENT__SIZEOF_PTHREAD_T.c.o] Error 1
make[1]: Leaving directory '/home/ubuntu/libevent/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_2ffea/fast' failed
make: *** [cmTC_2ffea/fast] Error 2


Blow is generated checking code.
`
/home/ubuntu/libevent/build/CMakeFiles/CheckTypeSize/EVENT__SIZEOF_PTHREAD_T.c:
#include <sys/types.h>
#include <stdint.h>
#include <stddef.h>
#include "sys/types.h"
#include "sys/socket.h"
#include "netinet/in.h"
#include "netinet/in6.h"
#include "fcntl.h"
#include "sys/time.h"


#undef KEY
#if defined(__i386)
# define KEY '_','_','i','3','8','6'
#elif defined(__x86_64)
# define KEY '_','_','x','8','6','_','6','4'
#elif defined(__ppc__)
# define KEY '_','_','p','p','c','_','_'
#elif defined(__ppc64__)
# define KEY '_','_','p','p','c','6','4','_','_'
#endif

#define SIZE (sizeof(pthread_t))
char info_size[] =  {'I', 'N', 'F', 'O', ':', 's','i','z','e','[',
  ('0' + ((SIZE / 10000)%10)),
  ('0' + ((SIZE / 1000)%10)),
  ('0' + ((SIZE / 100)%10)),
  ('0' + ((SIZE / 10)%10)),
  ('0' +  (SIZE    % 10)),
  ']',
#ifdef KEY
  ' ','k','e','y','[', KEY, ']',
#endif
  '\0'};

#ifdef __CLASSIC_C__
int main(argc, argv) int argc; char *argv[];
#else
int main(int argc, char *argv[])
#endif
{
  int require = 0;
  require += info_size[argc];
  (void)argv;
  return require;
}                                                                         
`

**Comment by liudf0716** [comment]
I have tested in LEDE, cmake can not work either

**Comment by azat** [comment]
Hi @semigodking 

Sorry for the delay (I just wanted to create env for ndk, maybe it will be useful in the future). 

So can you try attached patch? Or (and this one is more convenient) the whole patch set:

    https://github.com:azat/libevent cmake-configure-fixes

P.S. @liudf0716 can you test it too?

**Comment by azat** [comment]
BTW it works for me (but without openssl, but the problem is not there):
```
$ docker run -v $PWD/libevent:/libevent:rw -it bitriseio/android-ndk-alpha:v2017_03_03-03_32-b390 bash

$ apt install cmake
$ cd /libevent
$ cmake -d -DCMAKE_TOOLCHAIN_FILE=/opt/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=gcc -DEVENT__DISABLE_OPENSSL=ON ..
$ cmake
$ make
...
[100%] Built target test-init
```

P.S. I have to run cmake twice, because of #482 
P.P.S. there are some warnings, I'm going to fix them too, and some issues with shared libraries and 'arc4random_addrandom'

**Comment by azat** [comment]
Just force-pushed into `cmake-configure-fixes`, please update and test again, everything should compile without any issues (except for warnings about date overflow in tests).

**Comment by semigodking** [comment]
@azat Thank you! The fix works.
