### ISSUE TITLE
bufferevent_write succeeds on a dead tcp connection

### ISSUE THREAD

**Issue by cdprashanth** [libevent/libevent#477]
Hi
server machine went unreachable and tcp connnection to server remained 'established'.
in this scenario, i see that bufferevent_write still succeeds.
It should fail. right ?
if this is expected behavior , then how do i detect a dead tcp connection ?
Regards

**Comment by azat** [comment]
Replied [here](http://archives.seul.org/libevent/users/Mar-2017/msg00003.html).
