### ISSUE TITLE
Libevent queue in single-thread

### ISSUE THREAD

**Issue by SimarglFox** [libevent/libevent#478]
Can't find answer on my question, i am add event function wirh evtimer_add, 8 times in single-thread application. Did this function called 8 times one by one, or lib can pause fucntion for another execution? Can some one give link to doc with description of queue work?

**Comment by azat** [comment]
Libevent uses event loop, so if you are not calling `event_base_loop()` from your timer callback, than it can't pause your function (this is not the kernel), IOW timers callbacks will be called sequentially.
