### ISSUE TITLE
sleep in event_base_loop()

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#484]
I Have seen that the event_base_loop() api function sets up infinite loop inorder receive active and inactive callbacks.The question is does this infinte while loop has some some sleep() given to it for any certain time interval i am planning to spawn some threads  in the main thread and use it for communicating with other threads

**Comment by kushal4** [comment]
by see in the event.c fole i somewhat figured out that theres some timeout related to the event callbacks am i interprting it clearly?

**Comment by azat** [comment]
I'm not sure that I fully understand you, but event loop has timeouts (see timeout argument in select/epoll/kqueue/...), it is a minimal timeout for all added events (so that we don't miss anything).

**Comment by kushal4** [comment]
thanks  i  was  trying  to  understand in which way  libevent  was mainting  the  delay  in  its infinite  while  loop

**Comment by azat** [comment]
So does it means that everything is clear? Can you close this issue then?

**Comment by kushal4** [comment]
yes its clear now .I am closing this issue.
