### ISSUE TITLE
event_process_deferred_callbacks

### ISSUE THREAD

**Issue by lirunlong** [libevent/libevent#487]
```c
while((cb=TAILQ_FIRST(&queue->deferred_cb_list))) {
       .......
       UNLOCK_DEFERRED_QUEUE(queue):
       cb->cb(cb, cb->args);
       LOCK_DEFERRED_QUEUE(queue);
       ...........
}
```

When the first time to enter the while loop, the queue is locked? Where is the lock?

**Comment by azat** [comment]
Hi @lirunlong 

This looks like fec8bae2673966325eeaabc3fc1af60b584abb1a (2.1.1).

So `queue.lock` [here](https://github.com/libevent/libevent/blob/745a63dba33c53440064908f086bb739aa9c4bb3/event.c#L685) is `base->th_base_lock`

The call stack for `event_process_deferred_callbacks()` (where this loops located) is:
- event_process_deferred_callbacks()
- event_process_active()
- event_base_loop()

And `th_base_lock` is acquired [here](https://github.com/libevent/libevent/blob/745a63dba33c53440064908f086bb739aa9c4bb3/event.c#L1723).

In the mean time, I suggest you to switch to 2.1.8-stable.
