### ISSUE TITLE
guarding re: arc4random_addrandom() breaks backwards compat

### ISSUE THREAD

**Issue by fackgithab** [libevent/libevent#488]
commit 6541168d7037457b8e5c51cc354f11bd94e618b6 specifically walls off the prototype for evutil_secure_rng_add_bytes() unless the platform has been detected to have arc4random_addrandom() which seems off considering that libevent has a copy of the function in arc4random.c
please see https://trac.torproject.org/projects/tor/ticket/21796

**Comment by azat** [comment]
For which os did you compile `tor`?

**Comment by azat** [comment]
Forget it, just fixed it, can you please check with:
    https://github.com/azat/libevent.git master

Thanks for catching!

**Comment by fackgithab** [comment]
i'm not sure that addresses the issue as i wasn't building using cmake but instead autotools.
also, i think since arc4random_addrandom is built into libevent if the system lacks it means that exutil_secure_rng_add_bytes() is unconditionally available and so should be it's prototype
i think the solution is just to remove the guards around the prototype in util.h

**Comment by azat** [comment]
It is not about `cmake` it is about declaration availability, and according to link to the ticket it is the only error, i.e. it didn't tried to link, plus I successfully built tor with that patch in libevent yesterday.

As for prototype availability, when I was looking at the patch in question (6541168) I wasn't happy about `#ifdef`, but in some cases when we have all arc4 functions except `arc4random_addrandom()` then we if we will provide it from our compat (`arc4random.c`) as is `arc4random_addrandom()` will fill internal structure that is not used by any other `arc4*` functions, it is unlikely I guess, but still.

**Comment by fackgithab** [comment]
i was wrong, you were right, that works

**Comment by azat** [comment]
Great! Thanks for taking a look, I will push it ASAP.
