### ISSUE TITLE
Disconnected from the remote host

### ISSUE THREAD

**Issue by jtlkm** [libevent/libevent#492]
Hi,
bufferevent_setcb(bev, readcb, writecb, eventcb, session_data);  
At the beginning eventcb received BEV_EVENT_CONNECTED, Then I sent a request, the request was successful, after a few seconds disconnect and eventcb received BEV_EVENT_EOF. why？
What is the problem？

**Comment by ploxiln** [comment]
There is no way for anyone to know, with so little information to work with.

**Comment by jtlkm** [comment]
Hi  @ploxiln  @azat 
 I use nghttp2 library, I use the http2 protocol to connect AVS.
 request:
 nghttp2_nv hdrs[] = {
 MAKE_NV2(":method", "GET"),
 MAKE_NV2(":scheme","https"),
 MAKE_NV2(":path","/v20160207/directives"),
 MAKE_NV2("authorization","Bearer Atza|IwEBIO64ezexgTyd1jNfasksuW42slGru0CWGdv8vhDQG5RJdHf3ZPXj_6GCm73zPsln7miEc97z-jzrSskSOcjGiC-qwNdMF7yPRtwM_431Kk9VN7nSqHic1pv5wjiU-E7-pyHemAt0AFhRjkPKiPL4mMFW-UgIra_8gViyP9H6nR89mneeKMIu4NStwG5Pgr7qWxiKLU1FuM8BBTyYjNaQ_wsvO658Ry4t82C7_Z5TcPF9_fn-OHmwNyNT8bWv5mQiYCTrF6vtChOo_IGkgcqgGWRuPsWGpntUdAnU6-1-3p2YPL7dk7MsT5MmvgKr5NHqopEOmfEdtm-atneLiDMguyCWtUIr5SBeVBfGXtev03Q3oWULbZ7PU0EvPVzVU2bK5eChMCF_fe-EMqr9g94EyJylUdM9V0MDQx55rz9q9QYSRcZFUiW3UxvxQIaQjumm4X3Xx69k00ohdwCpucClgKh5azVcRVnPgzYvyWSv7OOsshLKTZ1SfANrUyW0G76M4N_Df-EbhA8TQ4ScynMRffMPnlCHkDVz4orfNd-8348-fgfmEnc0i-Y17bcUVxrD1Rw"),
 };
 stream_id = nghttp2_submit_request(session_data->session, NULL, hdrs,ARRLEN(hdrs), NULL,stream_data);
 response:
 :status: 200
 access-control-allow-origin: *
 x-amzn-requestid: 0e0f55fffe053c3c-000070d9-000301e3-49948381c86f4659-d452715c-1
 content-type: multipart/related; boundary=------abcde123; type=application/json
 All headers received

But after a few seconds eventcb received BEV_EVENT_EOF （Disconnected from the remote host）。
Why the server will automatically disconnect, what needs to set up? Is it not a long connection?
 I refer to the libevent-client.c file, The other parts of the code have not been changed.

**Comment by jtlkm** [comment]
Added, the main code is as follows:

static void **submit_request**(http2_session_data *session_data) {
  int32_t stream_id;
  http2_stream_data *stream_data = session_data->stream_data;
  const char *uri = stream_data->uri;
  const struct http_parser_url *u = stream_data->u;
  nghttp2_nv hdrs[] = {
      MAKE_NV2(":method", "GET"),
      MAKE_NV2(":scheme","https"),
      MAKE_NV2(":path","/v20160207/directives"),
      MAKE_NV2("authorization","Bearer Atza|IwEBIO64ezexgTyd1jNfasksuW42slGru0CWGdv8vhDQG5RJdHf3ZPXj_6GCm73zPsln7miEc97z-jzrSskSOcjGiC-qwNdMF7yPRtwM_431Kk9VN7nSqHic1pv5wjiU-E7-pyHemAt0AFhRjkPKiPL4mMFW-UgIra_8gViyP9H6nR89mneeKMIu4NStwG5Pgr7qWxiKLU1FuM8BBTyYjNaQ_wsvO658Ry4t82C7_Z5TcPF9_fn-OHmwNyNT8bWv5mQiYCTrF6vtChOo_IGkgcqgGWRuPsWGpntUdAnU6-1-3p2YPL7dk7MsT5MmvgKr5NHqopEOmfEdtm-atneLiDMguyCWtUIr5SBeVBfGXtev03Q3oWULbZ7PU0EvPVzVU2bK5eChMCF_fe-EMqr9g94EyJylUdM9V0MDQx55rz9q9QYSRcZFUiW3UxvxQIaQjumm4X3Xx69k00ohdwCpucClgKh5azVcRVnPgzYvyWSv7OOsshLKTZ1SfANrUyW0G76M4N_Df-EbhA8TQ4ScynMRffMPnlCHkDVz4orfNd-8348-fgfmEnc0i-Y17bcUVxrD1Rw"),
};
  printf("Request headers size: %d\n",ARRLEN(hdrs));
  stream_id = nghttp2_submit_request(session_data->session, NULL, hdrs,
                                     ARRLEN(hdrs), NULL, stream_data);
  if (stream_id < 0) {
    errx(1, "Could not submit HTTP request: %s", nghttp2_strerror(stream_id));
  }
 
  stream_data->stream_id = stream_id;
}

static void **readcb**(struct bufferevent *bev, void *ptr) {
  http2_session_data *session_data = (http2_session_data *)ptr;
  ssize_t readlen;
  struct evbuffer *input = bufferevent_get_input(bev);
  size_t datalen = evbuffer_get_length(input);
  unsigned char *data = evbuffer_pullup(input, -1);

  readlen = nghttp2_session_mem_recv(session_data->session, data, datalen);
  if (readlen < 0) {
    warnx("Fatal error: %s", nghttp2_strerror((int)readlen));
    delete_http2_session_data(session_data);
    return;
  }
  if (evbuffer_drain(input, (size_t)readlen) != 0) {
    warnx("Fatal error: evbuffer_drain failed");
    delete_http2_session_data(session_data);
    return;
  }
  if (session_send(session_data) != 0) {
  	printf("........readcb send data is failed..........\n");
    delete_http2_session_data(session_data);
    return;
  }
}

static void **eventcb**(struct bufferevent *bev, short events, void *ptr) {
  http2_session_data *session_data = (http2_session_data *)ptr;
  if (events & BEV_EVENT_CONNECTED) {
    int fd = bufferevent_getfd(bev);
    int val = 1;
	char keep_alive = 1;
    const unsigned char *alpn = NULL;
    unsigned int alpnlen = 0;
    SSL *ssl;
	
    fprintf(stderr, "Connected\n");

    ssl = bufferevent_openssl_get_ssl(session_data->bev);

    SSL_get0_next_proto_negotiated(ssl, &alpn, &alpnlen);
#if OPENSSL_VERSION_NUMBER >= 0x10002000L
    if (alpn == NULL) {
      SSL_get0_alpn_selected(ssl, &alpn, &alpnlen);
    }
#endif // OPENSSL_VERSION_NUMBER >= 0x10002000L

    if (alpn == NULL || alpnlen != 2 || memcmp("h2", alpn, 2) != 0) {
      fprintf(stderr, "h2 is not negotiated\n");
      delete_http2_session_data(session_data);
      return;
    }
    setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, (char *)&val, sizeof(val));
	
    initialize_nghttp2_session(session_data);
    send_client_connection_header(session_data);
    submit_request(session_data);

    if (session_send(session_data) != 0) {
      delete_http2_session_data(session_data);
    }
	return;
  }
  if (events & BEV_EVENT_EOF) {
    warnx("Disconnected from the remote host");
  } else if (events & BEV_EVENT_ERROR) {
    warnx("Network error");
  } else if (events & BEV_EVENT_TIMEOUT) {
    warnx("Timeout");
  }
  delete_http2_session_data(session_data);
}

static void **writecb**(struct bufferevent *bev, void *ptr) {
  int read_ret=0,write_ret=0;
  http2_session_data *session_data = (http2_session_data *)ptr;
  read_ret = nghttp2_session_want_read(session_data->session);
  write_ret = nghttp2_session_want_write(session_data->session);
  
  if ((read_ret == 0) &&
      (write_ret == 0)&&
      evbuffer_get_length(bufferevent_get_output(session_data->bev)) == 0) {
	delete_http2_session_data(session_data);
  }
}

static void **initiate_connection**(struct event_base *evbase, SSL_CTX *ssl_ctx,
                                const char *host, uint16_t port,
                                http2_session_data *session_data) {
  int rv;
  struct bufferevent *bev;
  SSL *ssl;
  ssl = create_ssl(ssl_ctx);
  bev = bufferevent_openssl_socket_new(
      evbase, -1, ssl, BUFFEREVENT_SSL_CONNECTING,
      BEV_OPT_DEFER_CALLBACKS | BEV_OPT_CLOSE_ON_FREE);
  bufferevent_setcb(bev, readcb, writecb, eventcb, session_data);

  rv = bufferevent_socket_connect_hostname(bev, session_data->dnsbase,
                                        AF_UNSPEC, host, port);
  if (rv != 0) {
    errx(1, "Could not connect to the remote host %s", host);
  }
  session_data->bev = bev;
}

static void **run**(const char *uri) {
  struct http_parser_url u;
  char *host;
  uint16_t port;
  int rv;
  SSL_CTX *ssl_ctx;
  struct event_base *evbase;
  http2_session_data *session_data;
  /* Parse the |uri| and stores its components in |u| */
  rv = http_parser_parse_url(uri, strlen(uri), 0, &u);
  if (rv != 0) {
    errx(1, "Could not parse URI %s", uri);
  }
  host = strndup(&uri[u.field_data[UF_HOST].off], u.field_data[UF_HOST].len);
  if (!(u.field_set & (1 << UF_PORT))) {
    port = 443;
  } else {
    port = u.port;
  }

  ssl_ctx = create_ssl_ctx();
  evbase = event_base_new();

  session_data = create_http2_session_data(evbase);
  session_data->stream_data = create_http2_stream_data(uri, &u);

  initiate_connection(evbase, ssl_ctx, host, port, session_data);
  free(host);
  host = NULL;
  event_base_loop(evbase, 0);
  event_base_free(evbase);
  SSL_CTX_free(ssl_ctx);
}


int **start_http2**(const char *url) {
  struct sigaction act;
  memset(&act, 0, sizeof(struct sigaction));
  act.sa_handler = SIG_IGN;
  sigaction(SIGPIPE, &act, NULL);

  SSL_load_error_strings();
  SSL_library_init();
  run(url);
  return 0;
}

**Comment by ploxiln** [comment]
When pasting code, use fenced code blocks https://help.github.com/articles/creating-and-highlighting-code-blocks/

But this sounds more like intentional AWS behavior. I found this other comment: https://github.com/aws/aws-sdk-go/issues/829#issuecomment-245726691

> connections may be closed server side if they are not reused within a short duration

**Comment by jtlkm** [comment]
Hi  @ploxiln 
How to modify the code to achieve long connection？

**Comment by azat** [comment]
> How to modify the code to archieve long connection

I don't see any timeout in your code, so if it does not have it them I would say the remote server closes the connection.
(actually http layer in libevent has default timeouts, 50 seconds for read/write, but AFAICS you do not use it, only bufferevents which doesn't have any default timeouts)

So I'm Closing it due to outdated, @jtlkm feel free to reopen if you still observe such behaviour and have more details (for example proof that this is the libevent fault).
