### ISSUE TITLE
libevent hides POLLERR

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#495]
libevent masks the existence of `POLLERR` (or `EPOLLERR`, etc), and replaces it with `EV_READ|EV_WRITE`. For use-cases like `MSG_ERRQUEUE` on a UDP socket (https://tools.ietf.org/id/draft-martinsen-tram-stuntrace-00.html#rfc.appendix.A.2.2), this is very inconvenient. A user would need to call both `recvmsg(..., MSG_ERRQUEUE ...)` and `recvfrom(...)` for each `EV_READ` event.

Instead, if libevent passed `EV_ERROR` (or something), the callback could identify that is was a `*POLLERR`. (not sure about `select`).

**Comment by azat** [comment]
But you can check for `((events & EV_READ) && (events & EV_WRITE))`, no (yes it will be the same for `POLLNVAL` and `POLLHUP` but I guess that number of such errors will be less then `POLLIN/POLLOUT`)?

As for introducing some marker or `POLLERR/EPOLLERR/...` seems that this can be useful, but `EV_ERROR` is reserved by kqueue, and `EV_ERR` in some win32 stuff.

Maybe we should just OR'ing it with something to distinguish `POLLERR` from other errors?

**Comment by ghazel** [comment]
How are `EV_ERROR` and `EV_ERR` reserved for event loops I'm not using?

**Comment by azat** [comment]
EV_ERROR/EV_ERR are not reserved by libevent, but:
- [EV_ERROR reserved by kqueue](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2)
- [EV_ERR some win32 stuff (not sure here)](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363435(v=vs.85).aspx)

**Comment by ghazel** [comment]
Closing since https://github.com/libevent/libevent/issues/1038 covers this issue.
