### ISSUE TITLE
Error cause on  reconnect on the same connection 

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#503]
Why am i getting this warning and later error ?
 Epoll ADD(1) on fd 714 failed. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none): Bad file descriptor

**Comment by azat** [comment]
One of the reasons is that you trying to add already closed descriptor, you can check this `strace` for example or just enable libevent debug logging (`event_enable_debug_logging()`)

**Comment by kushal4** [comment]
hi,
Do i have to put this at the top of the program?

**Comment by azat** [comment]
Yep

**Comment by kushal4** [comment]
thanks :)

**Comment by kushal4** [comment]
Hi,
when i am using 800 connections the the flow is working fine but when 900 connections are opened ,and the client closes the connection i see this phenomeno frequently.Could you please enlighten this issue :(

**Comment by azat** [comment]
I guess that this is the same issue with limit for number of opened files (you already posted it sometime ago), and seems that you don't check that fd is valid always.

Like I already said, you can use `strace` to catch this errors, i.e. `strace -fff <your command> |& fgrep EBADF`, you will get `open` syscall (or `pipe2` or something else), then you can use `gdb` and install breakpoint with condition to find the place where you are using bad fd, i.e. `break event_new if fd == -1` for example (and you need debug symbols for libevent in this case).

Or just add asserts into your sources, so that it will bail once it get invalid fd.

**Comment by kushal4** [comment]
ok thanks am doing this :)

**Comment by kushal4** [comment]
hi,
Is there a way to know that a particular sock fd is invalid or not i mean is there an api function in libevemt which would tell me that i am aboutto use a closed fd or not?

**Comment by kushal4** [comment]
Now its working fine.I am closing the connection totally whenever i the event callback of the bufferevent is called and thus now i am not going through adding the already closed file descriptor .I dont know why it was added ,the flow isnt supposed to add the already closed descripotr on the libevent.But i will debugging deep through it

**Comment by azat** [comment]
> Is there a way to know that a particular sock fd is invalid or not i mean is there an api function in libevemt which would tell me that i am aboutto use a closed fd or not?

It is not the libevent business.

You can use something like `fcntl(fd, F_GETFD)`. But this is not 100% correct (because you can have `close`/`open` between), suppose you have next flow:
```
open # == 3
close(3) # 0
<you cached 3 fd here>
open # == 3
<you are using 3 fd, but it is another file/socket/... already
```

**Comment by azat** [comment]
> Now its working fine

So can you close then?

**Comment by kushal4** [comment]
hi,
When i am making around  1600 connections throught libevent  at some later point,suppose i have closed a connection and when i am trying to reconnect  i am getting this behaviour again.All the functionalities of epoll is done by libevent itself and i am not doing anything here

**Comment by kushal4** [comment]
If i remove the flag LEV_OPT_REUSEABLE from the evconlistener function would it prevent this issue since i am guessing that it is tryingto reuse the socket here am i guessing it right here?

**Comment by kushal4** [comment]
whenever  thecallback from libevent calls the  abnormality callback (which detects  either eof of socket or any  abnormalities  on  the socket  reading  the  packet) i am closing  the connection.How do i ensure that the client  later  doesnt  send any  packet  on that closed socket ?

**Comment by kushal4** [comment]
libevent  is  used  to build the server  so  its  working  on  theserver  side

**Comment by azat** [comment]
I don't think that we can help based on your problem description, so please provide reproducer, but it looks like you are doing something wrong with sockets.

> If i remove the flag LEV_OPT_REUSEABLE from the evconlistener function would it prevent this issue since i am guessing that it is tryingto reuse the socket here am i guessing it right here?

No, this is for `listen()`

> How do i ensure that the client later doesnt send any packet on that closed socket ?

If you closed the socket already, then you can't know does client will send more data or not, and in fact this is not possible under normal circumstances.
