### ISSUE TITLE
Proxy-Connection header is removed from HTTP requests

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#507]
When submitting an http request to a proxy, the `Proxy-Connection: keep-alive` header is stripped. Here: https://github.com/libevent/libevent/blob/e9837124563d6d4bb871d0620e9b02550f796c43/http.c#L435

Sample code seems to expect it will work:
https://github.com/libevent/libevent/blob/0abe4eba83c45c1145df4f7756a69258134601b4/sample/http-connect.c#L105

**Comment by azat** [comment]
@ghazel thanks, nice catch, will fix later.

**Comment by ghazel** [comment]
There's more mishandling of `Proxy-Connection`:

https://github.com/libevent/libevent/blob/e9837124563d6d4bb871d0620e9b02550f796c43/http.c#L464

That closes the connection if the `Proxy-Connection` header is not present, which is not the default for HTTP/1.1.

There's no official spec for `Proxy-Connection`, but it was originally meant to be handled just like `Connection`. These days, it is recommended not to use `Proxy-Connection` at all (https://tools.ietf.org/html/rfc7230), so perhaps the right answer is to scrub it from Libevent entirely.
