### ISSUE TITLE
evhttp_send_reply_start crashes when evcon is NULL

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#509]
When and incoming http request has `evcon` set to NULL (see `EVREQ_HTTP_TIMEOUT` handling), calling `evhttp_send_reply_start` crashes eventually because `evcon` is used.

The other `evhttp_send*` functions check for this case and return, which seems like the right thing to do.

Also, it would be nice to notify the user when the `evcon` is set to NULL. I think calling the request's `error_cb` in `evhttp_connection_fail_` would be a good idea.

**Comment by azat** [comment]
Making `evhttp_send_*` return an `int` (error) instead of `void` and return the error in this case is a good thing I guess.
Calling `error_cb`, indeed is a good idea.

Can you add a patch?

**Comment by azat** [comment]
Patch from #566 applied
