### ISSUE TITLE
evhttp_connection_get_addr doesn't work for incoming connections

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#510]
evhttp uses `bufferevent_setfd` to associate the incoming connection with the bufferevent, but never calls `bufferevent_socket_set_conn_address`, so `evhttp_connection_get_addr` returns the wrong thing.

**Comment by azat** [comment]
@ghazel nice catch!

Can you send a patch? I think that adding `bufferevent_socket_set_conn_address` just after `bufferevent_setfd` in `http.c` will be correct. And it will be great if you can add a unit test too.

Thanks.

**Comment by ghazel** [comment]
It might be clearer if `conn_address` were renamed to `cached_peername` or some such, but I'll leave that for a future patch.

**Comment by azat** [comment]
Closing this one in favor to #595
