### ISSUE TITLE
libevent\include\event2/util.h(187): fatal error C1017: invalid integer constant expression

### ISSUE THREAD

**Issue by owen200008** [libevent/libevent#511]
someone have the same issue?
it compile success in linux,android, but can not compile in windows
i use the order 
cmake .. -G "Visual Studio 15" -DEVENT__DISABLE_OPENSSL=TRUE -DEVENT__DISABLE_BENCHMARK=TRUE -DEVENT__DISABLE_TESTS=TRUE
and it have the error
libevent\include\event2/util.h(187): fatal error C1017: invalid integer constant expression

how can i solve？

**Comment by owen200008** [comment]
/* The size of 'void *', as computer by sizeof */
#define EVENT__SIZEOF_VOID_P

**Comment by owen200008** [comment]
change to nmake include file？

**Comment by azat** [comment]
Hi @owen200008 

Can you please tell me what commit sha do you try to compile?
And just a minor note, maybe you have the same issues as in #436?

**Comment by owen200008** [comment]
just compile lib and dll without ssh
it is the same issues with #436
the main project use cmake to create so i want to use to the sublibs.
use cmake create libevent have this error.
now i must use nmake instand. but i hope cmake can work well

**Comment by azat** [comment]
`cmake` build should work.

Can you upload all cmake cache files somewhere? (tar.gz preferable)
For this it is better to use separate folder for cmake generated stuff:
```shell
mkdir build
cd build
cmake .. <opts>
```

**Comment by owen200008** [comment]
update the newest version it works~ 
but it also have the error.
1>Done building project "event_core_static.vcxproj" -- FAILED.
2>Done building project "event_static.vcxproj" -- FAILED.
the same error
libevent\event.c(127): error C2491: 'event_global_current_base_': definition of dllimport data not allowed

**Comment by owen200008** [comment]
now i change the code to make visible. if you solve, please tell me~ thanks.
visibility.h
...
# if defined(_MSC_VER)
#  define EVENT2_EXPORT_SYMBOL extern __declspec(dllimport)
#  define SELF_DEFINE_EVENT2_EXPORT_SYMBOL  extern
# else
#  define EVENT2_EXPORT_SYMBOL
# endif
...
#ifndef SELF_DEFINE_EVENT2_EXPORT_SYMBOL
#define SELF_DEFINE_EVENT2_EXPORT_SYMBOL EVENT2_EXPORT_SYMBOL
#endif
...

log.c
SELF_DEFINE_EVENT2_EXPORT_SYMBOL
ev_uint32_t event_debug_logging_mask_ = DEFAULT_MASK;

event.c
SELF_DEFINE_EVENT2_EXPORT_SYMBOL
struct event_base *event_global_current_base_ = NULL;

**Comment by azat** [comment]
> 1>Done building project "event_core_static.vcxproj" -- FAILED.
> 2>Done building project "event_static.vcxproj" -- FAILED.
> the same error
> libevent\event.c(127): error C2491: 'event_global_current_base_': definition of dllimport data not allowed

Yeah, I'm bear in mind that I broke this, I will test you proposal, thanks!

**Comment by azat** [comment]
Ah, I see, but there is `EVENT2_EXPORT_SYMBOL_DECL` already, I will replace `EVENT2_EXPORT_SYMBOL` with it.

**Comment by azat** [comment]
Nope, it is the opposite thing, sorry for the noise.

**Comment by lingyphone** [comment]
Hello, @azat, I am still having the same issue with the latest master branch and patches-2.1 branch when build with visual studio 15 2017 professional on windows 10 x64 for both x86 and x64 build, why?
