### ISSUE TITLE
Maximum number of connection that can be beared by libevent on the single evconnlistener instance

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#514]
HI,
Is there any maximum limit on  the number of succesful connections that can be  beared by libevent. I mean is there any threshold after which the  overall setup may show some wierd behaviour?

**Comment by ploxiln** [comment]
Here's a benchmark which has tested up to 100000 connections: http://libev.schmorp.de/bench.html

(although it's actually testing with "socketpairs": http://man7.org/linux/man-pages/man2/socketpair.2.html)

**Comment by kushal4** [comment]
ok thanks :)
