### ISSUE TITLE
multiple evhttp bind a socket has concurrence problem if has one time-consuming requset

### ISSUE THREAD

**Issue by lastorder** [libevent/libevent#515]
Create multiple event_base and evhttp, use evhttp_accept_socket to bind a  same socket.
Call event_base_dispatch  for every  event_base in independent thread.

Creat 100 concurrency client request, server use 8 thread(each thread each event_base), if every request is not time-consuming, the multiple thread will hand the request in time.

If there is one request is time-consuming, I expect the 99 request will hand in time, but it's not , many request is delay than the  time-consuming request.

**Comment by ploxiln** [comment]
A single thread / event_base was able to accept multiple connections, before the "long-running" request was fully received and started the "long-running" callback.

An example sequence: accept A, accept B, accept C, receive A, run callback for A, if A is "long-running" B and C are delayed. Meanwhile other thread / event_base can process D, E, F.

This is not a bug in libevent.

A thread running an event loop should never run a long-blocking operation. You need to have just the long-blocking work run on a separate thread. You need the event loop thread to find out when the long-blocking operation is completed by the other thread, either with polling (periodic timeouts), or with an async notification e.g. with a `pipe()` fd. Good luck.

**Comment by lastorder** [comment]
I already change the long-blocking work run on a separate thread, the problem is solved.

In the example sequence, if accept A, and A is "long-running" not return. Can B automatic accepted by other  unoccupied event_base in other thread?

**Comment by ploxiln** [comment]
As I said, the problem is that connection B was accepted by the same thread that accepted connection A, before that thread received the request from A. The unoccupied threads can accept other connections like D, but not B, because the first thread already accepted it.

For it to work the way you want, you would need to not use an event loop, just plain threads. Each thread would accept, read request, process request, loop back to accept again.

**Comment by ploxiln** [comment]
To clarify further: it is an intentional feature of event loops to be able to work on unrelated tasks in between related tasks. While waiting for the request to be received (which may take a small fraction of a second) it can make progress by accepting another connection.

**Comment by lastorder** [comment]
Ok, thank you. @ploxiln
