### ISSUE TITLE
cmake windows use add_subdirectory（libevent） error

### ISSUE THREAD

**Issue by owen200008** [libevent/libevent#516]
CMake Error at 3rd/libevent/CMakeLists.txt:1320 (file):
  file RELATIVE_PATH must be passed a full path to the directory: cmake

cmake version:3.8
libevent version: newest

cmake self is success. but fail by add_subdirectory

**Comment by azat** [comment]
I can't see how this can happen except for installing `EVENT_INSTALL_CMAKE_DIR` manually:

```cmake
cmake_minimum_required(VERSION 3.8)
set(EVENT_INSTALL_CMAKE_DIR "cmake" CACHE STRING "..." FORCE)
add_subdirectory(${PROJECT_SOURCE_DIR}/libevent)
```

```shell
libevent-include-via-cmake $ cmake
-- Looking for CTL_KERN - found
-- Looking for KERN_ARND - not found
-- Looking for KERN_RANDOM - found
-- Looking for RANDOM_UUID - found
-- OpenSSL include: /usr/include
-- OpenSSL lib: /usr/lib/libssl.so;/usr/lib/libcrypto.so
-- Generating regress tests...
CMake Error at libevent/CMakeLists.txt:1320 (file):
  file RELATIVE_PATH must be passed a full path to the directory: cmake
```

Can you provide full set of commands or a reproducer? I don't think that this is windows specific.

**Comment by owen200008** [comment]
my CMakeList.txt
if (WIN32 OR APPLE)
    cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
else()
    cmake_minimum_required(VERSION 2.8.5 FATAL_ERROR)
endif()

project(basiclibTest)

option(BASICLIBTEST_BUILD_TEST "Build BasicLibTest Exe" ON)

#build basiclib
#add_subdirectory(${PROJECT_SOURCE_DIR}/src ${PROJECT_SOURCE_DIR}/src/build)
#build libevent
set(BUILD_TESTING OFF CACHE BOOL "flags")
set(EVENT__DISABLE_BENCHMARK ON CACHE BOOL "flags")
set(EVENT__DISABLE_OPENSSL ON CACHE BOOL "flags")
set(EVENT__DISABLE_REGRESS ON CACHE BOOL "flags")
set(EVENT__DISABLE_SAMPLES ON CACHE BOOL "flags")
set(EVENT__DISABLE_TESTS ON CACHE BOOL "flags")
set(EVENT__DISABLE_THREAD_SUPPORT ON CACHE BOOL "flags")
add_subdirectory(${PROJECT_SOURCE_DIR}/3rd/libevent ${PROJECT_SOURCE_DIR}/3rd/libevent/build)

**Comment by owen200008** [comment]
error is follow:
E:\github\ccbasic\build>cmake ..
-- Looking for _GNU_SOURCE
-- Looking for _GNU_SOURCE - not found
-- Looking for CTL_KERN - not found
-- Looking for KERN_ARND - not found
-- Looking for KERN_RANDOM - not found
-- Looking for RANDOM_UUID - not found
CMake Error at 3rd/libevent/CMakeLists.txt:1320 (file):
  file RELATIVE_PATH must be passed a full path to the directory: cmake

**Comment by azat** [comment]
Hm, indeed it is not windows specific and I can't reproduce this (cmake 3.7.0):

```shell
# CMakeLists.txt
add_subdirectory(${PROJECT_SOURCE_DIR}/vagrant ${PROJECT_SOURCE_DIR}/vagrant-build)
```

```shell
/cygdrive/c/Program\ Files/CMake/bin/cmake.exe -G "Visual Studio 12" ..
fatal: Not a git repository (or any of the parent directories): .git
-- Looking for _GNU_SOURCE
-- Looking for _GNU_SOURCE - not found
-- Looking for CTL_KERN - not found
-- Looking for KERN_ARND - not found
-- Looking for KERN_RANDOM - not found
-- Looking for RANDOM_UUID - not found
-- OpenSSL include: C:/OpenSSL-Win32/include
-- OpenSSL lib: optimized;C:/OpenSSL-Win32/lib/VC/ssleay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/ssleay32MDd.lib;optimized;C:/OpenSSL-Win32/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/libeay32MDd.lib
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Generating regress tests...
-- C:\Program Files\CMake\bin\ctest.exe
--
--         ---( Libevent 2.2.0-alpha-dev )---
--
-- Available event backends: WIN32
-- CMAKE_BINARY_DIR:         C:/.cmake
-- CMAKE_CURRENT_BINARY_DIR: C:/vagrant-build
-- CMAKE_SOURCE_DIR:         C:/
-- CMAKE_CURRENT_SOURCE_DIR: C:/vagrant
-- PROJECT_BINARY_DIR:       C:/vagrant-build
-- PROJECT_SOURCE_DIR:       C:/vagrant
-- CMAKE_MODULE_PATH:        C:/vagrant/cmake/
-- CMAKE_COMMAND:            C:/Program Files/CMake/bin/cmake.exe
-- CMAKE_ROOT:               C:/Program Files/CMake/share/cmake-3.7
-- CMAKE_SYSTEM:             Windows-10.0.10240
-- CMAKE_SYSTEM_NAME:        Windows
-- CMAKE_SYSTEM_VERSION:     10.0.10240
-- CMAKE_SYSTEM_PROCESSOR:   AMD64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:            /DWIN32 /D_WINDOWS /W3
-- CMAKE_BUILD_TYPE:         Release
-- CMAKE_C_COMPILER:         C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe
-- CMAKE_AR:
-- CMAKE_RANLIB:
--
CMake Warning (dev) in C://CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/.cmake
```

And I even tried your sources, and they are also fine in my env.

Can you add some debug printing into `3rd/libevent/CMakeLists.txt` do know which variable is empty, but looks very strange to me, since `EVENT_INSTALL_CMAKE_DIR` concated from two vars, so it will have "/" in it.

**Comment by azat** [comment]
And `3.8.1` also fine, and even with space in the path.

**Comment by azat** [comment]
Closed due to long inactivity time.
