### ISSUE TITLE
CMake does not create libevent_openssl lib

### ISSUE THREAD

**Issue by semigodking** [libevent/libevent#519]
When building libevent with cmake, lib libevent_openssl is not generated.  Yes, application can link against libevent successfully without libevent_openssl in this case. If libevent is built with automake tools, libevent_openssl is generated, application must be linked against libevent_openssl. Is this difference design intent or bug of CMakeList.txt?

**Comment by azat** [comment]
This is a bug of cmake rules, but it is fixed in 72ef9d16522f88ea7848a52430b5f80d1174d710
Also please keep in mind, that autotools is considered more stable right now.

**Comment by semigodking** [comment]
Cool! Thank you!

Azat Khuzhin <notifications@github.com>于2017年6月9日周五 23:29写道：
