### ISSUE TITLE
SIG_ABRT observe

### ISSUE THREAD

**Issue by tunwei** [libevent/libevent#52]
Hi, 
I am using Libevent to write my code. My program terminated after 20 days of running.
Here is the core dump I obeseve

#0  0x00007fa23513c025 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007fa23513c025 in raise () from /lib64/libc.so.6
#1  0x00007fa23513d3d5 in abort () from /lib64/libc.so.6
#2  0x00007fa23643afc1 in ?? () from /lib64/libevent-2.0.so.5
#3  0x00007fa23643b065 in event_errx () from /lib64/libevent-2.0.so.5
#4  0x00007fa2364331b4 in _evbuffer_decref_and_unlock () from /lib64/libevent-2.0.so.5
#5  0x00007fa23643337d in evbuffer_free () from /lib64/libevent-2.0.so.5
#6  0x00007fa236434fc9 in _bufferevent_decref_and_unlock () from /lib64/libevent-2.0.so.5
#7  0x00007fa23643517d in bufferevent_enable () from /lib64/libevent-2.0.so.5
#8  0x000000000043e529 in setupConnection (listener=0x2630fc0, cfd=53, address=0x7fffd5cf2720, socklen=16, ctx=0x7fffd5cf2910)
    at mycode.c:180
#9  0x00007fa236438564 in ?? () from /lib64/libevent-2.0.so.5
#10 0x00007fa23642ebee in event_base_loop () from /lib64/libevent-2.0.so.5
#11 0x00007fa23642ee73 in event_base_dispatch () from /lib64/libevent-2.0.so.5

Does this problem belong to libevent bugs?

my libevent version is libevent_2.0.16

**Comment by ellzey** [comment]
No response for clarification for a few years. Closing.
