### ISSUE TITLE
creating several  event bases  which  maintains certain number of socket fds  each

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#521]
Hi,
I am slightly  confused  with the working  of libevent.Is there any  provision of  suppose i create several event  bases dynamically ? Then each   event  base would suppose  maintain 100 sockets each and when more than that comes it will be given to the other event base.
Thanks,
Kushal

**Comment by azat** [comment]
No, and this is not a good idea.

Since for example for epoll 100 fds per epoll-fd is not an optimum thing to
do.

Why do you need this? The only bit that came into my mind, is that you
callbacks are slow? Than it is better to process them in background
thread/thread-pool

**Comment by kushal4** [comment]
i mean can i create multiple event bases from different threads each accpeting suppose 50 sockets .Yes my callbacks are really slow could you please show me some working example here i am kinda lost here

**Comment by kushal4** [comment]
Do u mean to say like creating the event bases in seperate threads ? And  if that is the case would every event base (in these different threads)  have the ability to to maintain its own set of socket fds to poll around like in this case each event base would contain 50 sockets to poll around

**Comment by azat** [comment]
> i mean can i create multiple event bases from different threads each accpeting suppose 50 sockets .Yes my callbacks are really slow could you please show me some working example here i am kinda lost here

If you don't have a lot of clients/data, than one event base is enough. Just create thread pool and defer job to them (using socketpair for instance). So you just create socketpair() in the main thread, and it's write endpoint will be used in main thread to write information about which callback and with what arguments you need to run, and the read side of that pair will be used in thread to read this information, or of course you can use condition variables and so on (there are a lot of possible implementations).

> Do u mean to say like creating the event bases in seperate threads ? And if that is the case would every event base (in these different threads) have the ability to to maintain its own set of socket fds to poll around like in this case each event base would contain 50 sockets to poll around

If you will create event base per thread, than every event base (regardless is this main thread or not) will have it's own fd set, but anyway you need to balance between them.

**Comment by kushal4** [comment]
So in this case can polling be done on those seperate event bases? I mean each event base maintains its own fd set so can every event base poll on its own fd set and call respective read and write callbacks without interferfering with other event bases?

**Comment by kushal4** [comment]
In order to tell you my actual use case i am using it for my mqtt broker which would take thousands of connections from clients so in that scenario i have to make different event bases since my callbacks becomes too slow and in that way polling was hampered too

**Comment by kushal4** [comment]
And in this case is callinf evconnlistener_* mandatory in these cases.I guess the evconnlistener_new() function can only take one event_base so i am kinda lost here about how to implement the threading scenario here

**Comment by kushal4** [comment]
by following this method, can i create event bases dynamically? i mean in this example whenever i cross 50 connections another event base would be created and so on

**Comment by kushal4** [comment]
I have one more confusion,do i have to call event base from the main() too and start event loop or i just have to create event_base from different threads only

**Comment by ploxiln** [comment]
Keep it simple. Maybe libevent and event-driven programming in general is not the best solution to your problem. Maybe a plain thread per connection or request is better for you.

**Comment by kushal4** [comment]
yes  i am doing that but in my architechture i also need event driven programming and a mechanism if poosible about each event_base polling on small number of fdset which would make the callbacks to run faster

**Comment by kushal4** [comment]
hi,
is there any working example of using eventbases (for fixed fd set)  in  different threads.Am making more  mistakes in allocating eventbases here :(

**Comment by azat** [comment]
For sure, take a look at [this](http://archives.seul.org/libevent/users/Mar-2016/msg00046.html)

P.S. sadly `libevhtp` is not available from @ellzey repository, but there are a lot of forks on github
