### ISSUE TITLE
print-winsock-errors.c is Missing from Source

### ISSUE THREAD

**Issue by skalemkiewicz** [libevent/libevent#523]
Nmake compilation fails because print-winsock-errors.c is missing from the source tree.

Observed in 2.1.8-stable on Windows 7 using Visual Studio 2015.

**Comment by azat** [comment]
Fixed in 8d89c212587c560df8cd7089fb1a2fcd2a3dca82, and so new libevent release will contain this file.
In the mean time is it a major error for you?

**Comment by skalemkiewicz** [comment]
No, I was able to locate the file in the repo history, insert it and finish the compile process. Thanks!

**Comment by azat** [comment]
Great!

**Comment by RookieDev11** [comment]
@skalemkiewicz I am having same problem for libevent. Can you tell me how can i insert it? I tried to edit include.am by notepad++ but i am getting same error.

**Comment by skalemkiewicz** [comment]
@RookieDev11, I dont think I edited any files directly. If I remember correctly, I browsed through the repository history to find the missing file, downloaded it, copied it into the source tree, and then used the Visual  Studio interface to add the file to the project. Are you using Visual Studio or something else?

**Comment by RookieDev11** [comment]
@skalemkiewicz I have project which uses libevent library and i need to compile it on vs2017. I am getting linker error now.   error LNK2019: unresolved external symbol evutil_snprintf referenced in function. Can you tell me how to fix this please?

**Comment by THETCR** [comment]
Seriously? No release in two years and this is still a problem?
