### ISSUE TITLE
event callback which need to be called on socket error or end of file of socket usinfd event_base event mechanism

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#526]
Hi,
I am using event_base event architechture here.Previously i was using evconnlistener bufferevent architechture , where the callback was called whenever there was some error on the socket or end of file was reached.Just like that is there any mechanism of the callback with the even_base event ? If so,how do i add it

**Comment by azat** [comment]
No, you should implement it by yourself, i.e. when you got triggered on `EV_READ`/`EV_WRITE`, you should check return value of read/write (for read, if it an error, and the error is not retriable than this is an error, if it is zero then it is EOF, for the [reference](https://github.com/libevent/libevent/blob/2773a5ed5e75540d43500e054581ea1fab2132ac/bufferevent_sock.c#L200))

P.S. there is also a `EV_CLOSED` but it is not supported by all backends.

**Comment by kushal4** [comment]
ok thnx
