### ISSUE TITLE
confusion regarding adding events of different socket fd from the accept callback function

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#528]
Hi,
I have one confusion regarding addition of event in a different event base on the accept callback function.Bascically my idea is when the accept callback is fired i will add the certain number of events on a newly created event base from the accept callback function itself that is suppose from client  1-45 will be added to one event base and then 46-90 will be added to different new event base and so on but when i do this it is getting clashed with the main event base which is based on the listen socket fd .So, please guide me what should  i do in this scenario.
Thanks,
Kushal

**Comment by azat** [comment]
> 1-45 will be added to one event base and then 46-90 will be added to different new event base and so on

This is very not optimal thing to do, but go ahead if you want to.

 > getting clashed with the main event base which is based on the listen socket fd

What do you mean by this?

@kushal4 You have a lot of questions, and it will be great if you will provide some sources to describe what you are trying to do, so that we can take a look and maybe suggest some modifications.

**Comment by kushal4** [comment]
ok am sharing  you the source  here   :) 
[mqtt_broker_2.tar.gz](https://github.com/libevent/libevent/files/1153901/mqtt_broker_2.tar.gz)

I am  uploading the  file as a zip you can have a  look at  main.cpp  where i  use  the  architechture

**Comment by kushal4** [comment]
ther e u will see  that  there is  a  normal  event base  on  main() and  on the onAccept() callback  i create  event bases based  containing 400 sockets in each each  event  base
