### ISSUE TITLE
free bufferevent in event_base_free

### ISSUE THREAD

**Issue by david-holonet** [libevent/libevent#530]
I create a bufferevent, and add it to event_base, use `bufferevent_socket_new`.
And how can I free it when calling `event_base_free`?
Need I keep the bufferevent outside the event base and call `bufferevent_free` myself?

**Comment by azat** [comment]
`event_base_free()` will not free `bufferevent`, you should free it by yourself manually.
And this is basically for all structures that had been created with `*_new()`.
