### ISSUE TITLE
tv_clock_diff in struct event_base should be initialized to correct value instead of 0

### ISSUE THREAD

**Issue by JZhang2017** [libevent/libevent#533]
Hello,

I am debugging a problem with sntp from ntp 4.2.8p9 on Linux, and it seems there is bug in libevent.

Our system used ntp 4.2.6p5 before, which didn't rely on libevent and it worked. When I tried to bring in ntp 4.2.8p9 to our system, I found the sntp command executed during boot process failed:
```
linuxrc.sh: Doing ntpsync
linuxrc.sh: synchronizing time (/usr/sbin/sntp -s 169.254.100.1)
linuxrc.sh: sntp 4.2.8p9@1.3265-o Tue Nov 29 09:13:27 UTC 2016 (1)Wi
linuxrc.sh: 1970-01-01 00:00:02.496000 (+0000) +749980545.272104 +/- 499987030.181418 169.254.100.1 s10 no-leap
linuxrc.sh: adj_systime: Invalid argument
linuxrc.sh: Failed to set systemclock from NTP
linuxrc.sh: time is now: Thu Jul 13 15:51:32 UTC 2017

The time difference, 749980545 seconds, was too large between client and server, and therefore adj_systime didn't accept it. Then I tried to use "-S" option, which accepts large jump, instead of "-s" to sntp. and it set time to April, 2041 by adding half of the time difference between July 2017 and January 1970, on top of July 2017:
linuxrc.sh: synchronizing time (/usr/sbin/sntp -d -d -d -d -d -S 169.254.100.1)
linuxrc.sh: Fri Jul 14 21:19:59 UTC 2017
...
linuxrc.sh: sntp 4.2.8p9@1.3265-o Fri Jul 14 19:51:31 UTC 2017 (1)
...
linuxrc.sh: base->tv_cache.tv_sec = 2 base->tv_clock_diff.tv_sec = 0
linuxrc.sh: tv_dst.tv_sec = 2
linuxrc.sh: sntp offset_calculation: rpkt->org:
linuxrc.sh: dd13b3ff.bc637bd0  Fri, Jul 14 2017 21:19:59.735
linuxrc.sh: sntp offset_calculation: rpkt->rec:
linuxrc.sh: dd13b400.08f5ddb4  Fri, Jul 14 2017 21:20:00.035
linuxrc.sh: sntp offset_calculation: rpkt->xmt:
linuxrc.sh: dd13b400.08fabf23  Fri, Jul 14 2017 21:20:00.035
linuxrc.sh: sntp offset_calculation: dst:
linuxrc.sh: 83aa7e82.43958106  Thu, Jan  1 1970  0:00:02.264
linuxrc.sh: sntp offset_calculation:	rec - org t21: 0.299109
linuxrc.sh: xmt - dst t34: 1500067197.771076	delta: -1500067197.471968	offset: 750033599.035092
linuxrc.sh: 1970-01-01 00:00:02.264000 (+0000) +750033599.035092 +/- 500022399.356743 169.254.100.1 s10 no-leap
linuxrc.sh: time is now: Sat Apr 20 19:59:58 UTC 2041
```

The above output was got after enabling debug mode of sntp and adding some "printf"s to source code of ntp including libevent. tv_dst was returned from function, event_base_gettimeofday_cached(). The function called clock_gettime(CLOCK_MONOTONIC_COARSE, *) on my machine. We can see CLOCK_MONOTONIC_COARSE clock only measures the time from when Linux was booted. It shows that the sntp command was executed around 2 seconds after Linux was started, and at that time tv_clock_diff.tv_sec in base was 0. With tv_clock_diff.tv_sec set to 0, it wouldn't be able to derive correct wall clock time, because the time is calculated by evutil_timeradd(&base->tv_cache, &base->tv_clock_diff, tv).

After that, I tried to run the command manually:
```
linuxrc.sh: synchronizing time (/usr/sbin/sntp -d -d -d -d -d -S 169.254.100.1)
linuxrc.sh: Sat Jul 15 13:00:33 UTC 2017
...
linuxrc.sh: sntp 4.2.8p9@1.3265-o Fri Jul 14 19:51:31 UTC 2017 (1)
...
linuxrc.sh: ***gettime base->monotonic_timer.monotonic_clock = 6***
linuxrc.sh: HAVE_POSIX_MONOTONIC
linuxrc.sh: ***base->monotonic_clock = 6
linuxrc.sh: ******ts.tv_sec = 32
linuxrc.sh: ******gettime base = 1253460, tp->tv_sec = 32***
linuxrc.sh: ***Entered condition base->last_updated_clock_diff + CLOCK_SYNC_INTERVAL < tp->tv_sec***
linuxrc.sh: ***base->last_updated_clock_diff 0***
...
linuxrc.sh: base->tv_cache.tv_sec = 32 base->tv_clock_diff.tv_sec = 596a11bf
linuxrc.sh: tv_dst.tv_sec = 596a11f1
linuxrc.sh: sntp offset_calculation: rpkt->org:
linuxrc.sh: dd149071.d3137b07  Sat, Jul 15 2017 13:00:33.824
linuxrc.sh: sntp offset_calculation: rpkt->rec:
linuxrc.sh: dd149072.1b49a414  Sat, Jul 15 2017 13:00:34.106
linuxrc.sh: sntp offset_calculation: rpkt->xmt:
linuxrc.sh: dd149072.1b5258cb  Sat, Jul 15 2017 13:00:34.106
linuxrc.sh: sntp offset_calculation: dst:
linuxrc.sh: dd149071.e15e7c8d  Sat, Jul 15 2017 13:00:33.880
linuxrc.sh: sntp offset_calculation:	rec - org t21: 0.282076
linuxrc.sh: xmt - dst t34: 0.226377	delta: 0.055699	offset: 0.254227
linuxrc.sh: 2017-07-15 13:00:33.880348 (+0000) +0.254227 +/- 0.169500 169.254.100.1 s10 no-leap
linuxrc.sh: time is now: Sat Jul 15 13:00:34 UTC 2017
```

That time it was correct. because the command was run at around 32 seconds after boot. At that time, tv_clock_diff had been updated to the correct value in gettime(), which is the time difference between a CLOCK_MONOTONIC_COARSE clock and a realtime clock, since 32 seconds is longer than CLOCK_SYNC_INTERVAL or 5 seconds (condtion base->last_updated_clock_diff + CLOCK_SYNC_INTERVAL < tp->tv_sec in code).

So I think there is a bug in libevent. tv_clock_diff should be initialized to correct value instead of 0 probably in event_base_new_with_config(). Otherwise event_base_gettimeofday_cached() won't give correct time in the first CLOCK_SYNC_INTERVAL-second period after boot. The code to initialize it can be similar as the one from gettime():
```c
evutil_gettimeofday(&tv,NULL);
evutil_timersub(&tv, tp, &base->tv_clock_diff);
```

Regards,
Jianrong Zhang

**Comment by ploxiln** [comment]
libevent could probably do a better job of initialization for `event_base_gettimeofday_cached()`, but also ntp/sntp should not be using that directly or indirectly for precision timekeeping work, they should just use the libc functions or syscalls directly.

Just btw, the docs say:
> Generally, this value will only be cached while actually processing event callbacks, and may be very inaccuate if your callbacks take a long time to execute.

**Comment by JZhang2017** [comment]
Hi,

Thank you for your reply! I will ask the  people maintaining ntp and forward your recommendation. 

B.R.
Jianrong Zhang

**Comment by azat** [comment]
Closed, due to inactivity.
