### ISSUE TITLE
having "test/regress.c", line 3099:warning: assignment type mismatch

### ISSUE THREAD

**Issue by aessiet** [libevent/libevent#534]

**Comment by azat** [comment]
What the sha1 of sources do you have? I have `short what;` on [this line](https://github.com/libevent/libevent/blob/e83443ec67d45447296c2ce320620a07c88e1d32/test/regress.c#L3099)

**Comment by azat** [comment]
Anyway there are a tons of warnings (at least on win32), they will be fixed later and in a batch
