### ISSUE TITLE
how build in mac osx

### ISSUE THREAD

**Issue by hhhaiai** [libevent/libevent#535]
have not configure.sh   or  general shell。

readme has not . 

the release version has. what happen??

**Comment by ploxiln** [comment]
`configure` is generated by `./autogen.sh`

**Comment by rickywxg** [comment]
I managed to build it with cmake on my Mac OSX 10.12.5

Install openssl first if you haven't. `brew install openssl`

`configure` did not work for me because brew refused to add link for openssl.
```
$ brew link openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

My build steps with cmake:
1. export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
2. mkdir build && cd build
3. cmake ..
4. make

**Comment by jianchao-li** [comment]
Hello, @hhhaiai. I successfully built `libevent` on my macOS Mojave 10.14.1 in the following way. Actually the `README.md` has suggested to use `autoconf` but it did not provide concrete steps of how to do so.

First, you need to install some packages.

```bash
brew install autoconf automake libtool
```

Then you need to generate the `configure` file. All the following steps should be run from the root directory of `libevent`.

```bash
glibtoolize
aclocal
autoconf
autoheader
automake --add-missing
```

Then you can simply follow the steps in the `README.md`.

```bash
./configure
make
sudo make install
```

**Comment by hhhaiai** [comment]
ok  .  THX

**Comment by hhhaiai** [comment]
> I managed to build it with cmake on my Mac OSX 10.12.5
> 
> Install openssl first if you haven't. `brew install openssl`
> 
> `configure` did not work for me because brew refused to add link for openssl.
> 
> ```
> $ brew link openssl
> Warning: Refusing to link: openssl
> Linking keg-only openssl means you may end up linking against the insecure,
> deprecated system OpenSSL while using the headers from Homebrew's openssl.
> Instead, pass the full include/library paths to your compiler e.g.:
>   -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
> ```
> My build steps with cmake:
> 
> 1. export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
> 2. mkdir build && cd build
> 3. cmake ..
> 4. make

  build sucess.
thx

**Comment by hhhaiai** [comment]
> Hello, @hhhaiai. I successfully built `libevent` on my macOS Mojave 10.14.1 in the following way. Actually the `README.md` has suggested to use `autoconf` but it did not provide concrete steps of how to do so.
> 
> First, you need to install some packages.
> 
> ```shell
> brew install autoconf automake libtool
> ```
> 
> Then you need to generate the `configure` file. All the following steps should be run from the root directory of `libevent`.
> 
> ```shell
> glibtoolize
> aclocal
> autoconf
> autoheader
> automake --add-missing
> ```
> 
> Then you can simply follow the steps in the `README.md`.
> 
> ```shell
> ./configure
> make
> sudo make install
> ```

thx .My macos 10.14
