### ISSUE TITLE
Does libevent support unix domain socket ?

### ISSUE THREAD

**Issue by tanghammer** [libevent/libevent#537]
##i got some informations from here [http://www.wangafu.net/~nickm/libevent-book/](url), in Ref6_bufferevent.txt:
  Bufferevents currently only work for stream-oriented protocols like TCP. There may in the future be support for datagram-oriented protocols like UDP.
 
Does libevent support unix domain socket ?

**Comment by azat** [comment]
Sure, you can use `bufferevent_socket_connect()` with `struct sockaddr` to connect to it.

**Comment by tanghammer** [comment]
i test libevent with stream-oriented unix domain socket,it seems okay.
