### ISSUE TITLE
libevent memory leak in hhvm 3

### ISSUE THREAD

**Issue by begend** [libevent/libevent#538]
my hhvm version is : 3.0.1， libvernt version is  libevent-1.4.14b-stable.
my prof result with jemalloc as follows:
http://i2.tiimg.com/1949/8242f5547d28c4c2.png 

it seams that the evhttp_add_headers function has memory leak
![Uploading 1_5.png…]()

**Comment by azat** [comment]
I don't see any leak in `evhttp_add_headers()`, this can be leak during requires freeing. Is this results from not-exited-yet application? In this case it can be the requests that is not freed yet (but looks very unlikely).

**Comment by ploxiln** [comment]
There was at least one http related leak in 1.4.x fixed after 1.4.14b: #213 

In any case, 1.4.14b is long out of maintenance, and 2.0 and 2.1 branches likely have different leaks (if any).

**Comment by azat** [comment]
Closing this, due to inactivity
