### ISSUE TITLE
libevent link error in android ndk build

### ISSUE THREAD

**Issue by Johance2** [libevent/libevent#539]
libevent/buffer.c:495: error: undefined reference to 'LIST_END'
/libevent/bufferevent_ratelim.c:494: error: undefined reference to 'LIST_END'
libevent/bufferevent_ratelim.c:513: error: undefined reference to 'LIST_END'
but LIST_END is an macro not function

**Comment by azat** [comment]
Yep, looks like missing header, maybe some `#ifdef` changes the code.

But, AFAIR I built libevent successfully in android ndk (docker), which version of libevent do you tried?

**Comment by Johance2** [comment]
#define EVENT__VERSION "2.1.8-stable"
i built libevent successfully in android ndk.
but link failure。  $(call import-module,libevent) 
other version is ok

**Comment by azat** [comment]
First you wrote that libevent didn't link? What fixes the issue for your?
I don't familiar with android ndk, but what `call import-module` reports?

**Comment by azat** [comment]
P.S. [this](https://github.com/libevent/libevent/issues/475#issuecomment-284256518) is how I built it

**Comment by luznicky** [comment]
The same problem occurs when linking against uClibc. uClibc's 'sys/queue.h` is missing LIST_END macro. This problem is not recognized and although there is 'compat/sys/queue.h' in libevent, this is not used.
