### ISSUE TITLE
[err] http.c:686: Assertion req != NULL failed in evhttp_connection_fail_

### ISSUE THREAD

**Issue by szhem** [libevent/libevent#54]
Hi there,

Trying to develop a http client with timeouts `assertion req != NULL` occurs from time to time. 

It's difficult to say what steps are required to reproduce the error, but I suppose it's occurs after calls to `evhttp_cancel_request`.

1. After the call to `evhttp_cancel_request` the request is cleaned up in `evhttp_connection_fail_`
1. Then somehow `evhttp_connection_fail_` is called for the second time for the already cleaned up request

Here is the backtrace

    #0  0x00007fa36a0e9425 in raise () from /lib/x86_64-linux-gnu/libc.so.6
    No symbol table info available.
    #1  0x00007fa36a0ecb8b in abort () from /lib/x86_64-linux-gnu/libc.so.6
    No symbol table info available.
    #2  0x00007fa36ac8f53b in event_exit (errcode=-559030611) at log.c:107
    No locals.
    #3  0x00007fa36ac8f8e8 in event_errx (eval=-559030611, fmt=0x7fa36acb1018 "%s:%d: Assertion %s failed in %s") at log.c:164
            ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fff8c717030, reg_save_area = 0x7fff8c716f70}}
    #4  0x00007fa36aca35c6 in evhttp_connection_fail_ (evcon=0xd4b230, error=EVCON_HTTP_EOF) at http.c:686
            errsave = 114
            req = 0x0
            cb = 0
            cb_arg = 0x7fff8c717080
            __func__ = "evhttp_connection_fail_"
    #5  0x00007fa36aca4c7a in evhttp_error_cb (bufev=0xd4b3d0, what=32, arg=0xd4b230) at http.c:1380
            evcon = 0xd4b230
            req = 0x0
            __func__ = "evhttp_error_cb"
    #6  0x00007fa36aca4d0e in evhttp_connection_cb (bufev=0xd4b3d0, what=32, arg=0xd4b230) at http.c:1409
            evcon = 0xd4b230
            error = 1791534691
            errsz = 4
            __func__ = "evhttp_connection_cb"
    #7  0x00007fa36ac757d8 in bufferevent_run_eventcb_ (bufev=0xd4b3d0, what=32) at bufferevent.c:265
            p = 0xd4b3d0
    #8  0x00007fa36ac7bec4 in bufferevent_socket_connect (bev=0xd4b3d0, sa=0xd4edf0, socklen=16) at bufferevent_sock.c:428
            bufev_p = 0xd4b3d0
            fd = 23
            r = -1
            result = -1
            ownfd = 0
    #9  0x00007fa36ac7bfd3 in bufferevent_connect_getaddrinfo_cb (result=0, ai=0xd4edc0, arg=0xd4b3d0) at bufferevent_sock.c:461
            bev = 0xd4b3d0
            bev_p = 0xd4b3d0
            r = 0
    #10 0x00007fa36ac9e642 in evdns_getaddrinfo_gotresolve (result=3, type=0 '\000', count=0, ttl=60, addresses=0x0, arg=0xd4e5b0) at evdns.c:4367
            i = 32767
            req = 0xd4e5b0
            other_req = 0xd4e5a0
            data = 0xd4e550
            res = 0x1400d4e000
            sin = {sin_family = 29360, sin_port = 35953, sin_addr = {s_addr = 32767}, sin_zero = "\000;\310j\243\177\000"}
            sin6 = {sin6_family = 29376, sin6_port = 35953, sin6_flowinfo = 32767, sin6_addr = {__in6_u = {
                  __u6_addr8 = "\336\375\307j\243\177\000\000\350\232\324\000\000\000\000", __u6_addr16 = {64990, 27335, 32675, 0, 39656, 212, 0, 0}, __u6_addr32 = {
                    1791491550, 32675, 13933288, 0}}}, sin6_scope_id = 13930656}
            sa = 0xd50040
            socklen = 13933288
            addrlen = 0
            addrp = 0x3
            err = -2
            user_canceled = 0
            __func__ = "evdns_getaddrinfo_gotresolve"
    #11 0x00007fa36ac93a3b in reply_run_callback (d=0xd50040, user_pointer=0xd4e5b0) at evdns.c:799
            cb = 0xd50040
            __func__ = "reply_run_callback"
    #12 0x00007fa36ac800aa in event_process_active_single_queue (base=0xd490a0, activeq=0xd494f0, max_to_process=2147483647, endtime=0x0) at event.c:1476
            ev = 0x0
            evcb = 0xd50040
            count = 2
            __func__ = "event_process_active_single_queue"
    #13 0x00007fa36ac80364 in event_process_active (base=0xd490a0) at event.c:1538
            activeq = 0xd494f0
            i = 0
            c = 0
            endtime = 0x0
            tv = {tv_sec = 13931328, tv_usec = 13930656}
            maxcb = 2147483647
            limit_after_prio = 2147483647
    #14 0x00007fa36ac80ac0 in event_base_loop (base=0xd490a0, flags=0) at event.c:1761
            n = 2
            evsel = 0x7fa36aebcbc0
            tv = {tv_sec = 0, tv_usec = 116012}
            tv_p = 0x7fff8c717390
            res = 0
            done = 0
            retval = 0
            __func__ = "event_base_loop"
    #15 0x00007fa36ac803ec in event_base_dispatch (event_base=0xd490a0) at event.c:1572
    No locals.
    #16 0x0000000000403dba in ev2_module_start () at ../src/ev2_module.c:124
            rv = 0
    #17 0x0000000000403a2b in main () at ../src/ev2_main.c:10
    No locals.

**Comment by ellzey** [comment]
master in libevent's github world is trunk in svn. It's the alpha. Not git'ish, but it is what it is. Also, it seems to be fixed. Yay, closing!
