### ISSUE TITLE
Invalid pointer-is-not-null check in bufferevent_socket_connect

### ISSUE THREAD

**Issue by ivmai** [libevent/libevent#542]
Looking into 659d54d5304c476f5cf0ec502235e376e1d2d8a1 I see the following code
 struct bufferevent_private *bufev_p = EVUTIL_UPCAST(bev, struct bufferevent_private, bev);
 ...
 if (!bufev_p) return -1;

But bufev_p cannot be null. Probably the code should be fixed to:  if (!bev) return -1;

**Comment by azat** [comment]
Hi @ivmai - nice catch.

Yeah this is wrong, but none of other functions there check's for `bev != NULL`, so I suggest removing it completely, do you want to send a patch or should I fix it myself?

**Comment by ivmai** [comment]
Hello @azat 
I think that such small code defects are better to be fixed by the original commit authors or maintainers. So I'd prefer you to fix it. But please add "Contributed-By: Ivan Maidanski <i.maidanski@samsung.com>" (or "Signed-off-by: Ivan Maidanski <i.maidanski@samsung.com>") line to the commit message. Thank you

**Comment by azat** [comment]
Thanks! Fixed, upstream commit is a10a6f4ed918ea1432820d99e9373f37f906d6f0

BTW are you using some static analyzer or just noticed this manually during reading sources?

**Comment by ivmai** [comment]
I'm using a static analyzer (some proprietary tool developed by Samsung). The issue was detected during Android source inspection (https://android-review.googlesource.com/#/c/platform/external/libevent/+/157766/).
