### ISSUE TITLE
[help]why evhttp cannot get  "delete"request body?

### ISSUE THREAD

**Issue by sandr2013** [libevent/libevent#544]
I make the "delete" request vir libcurl,like this:
CURL *curl_delete;
CURLcode res;
curl_delete = curl_easy_init();
if (curl_delete)
{
	curl_easy_setopt(curl_delete, CURLOPT_VERBOSE, 1L);
	curl_easy_setopt(curl_delete, CURLOPT_CUSTOMREQUEST, "DELETE");
	curl_easy_setopt(curl_delete, CURLOPT_POSTFIELDS, "xxxxxxxxxxxxxxxxxxxx");
	curl_easy_setopt(curl_delete, CURLOPT_URL, "http://192.168.1.100:9999/place");  
	res = curl_easy_perform(curl_delete);
	curl_easy_cleanup(curl_delete);
}
then I receive the data vir evhttp_request_get_input_buffer,like this:
struct evbuffer *input_buf;
input_buf = evhttp_request_get_input_buffer(req);
printf( "put <<<<\n" );
while (evbuffer_get_length(input_buf))
{
	int n;
	char cbuf[128];
	n = evbuffer_remove(input_buf, cbuf, sizeof(cbuf));
	if (n>0)
	{
		(void)fwrite(cbuf, 1, n, stdout);
	}
}
but there is no data .When I make the "POST" request ,it's OK. HOW evhttp work with "DELETE"?

**Comment by sandr2013** [comment]
Thanks for your reply.So I just use "delete" with message in URI.
Thanks again.

**Comment by azat** [comment]
@sandr2013 you libevent now allows body for DELETE (but of course there is no stable release with this patch yet, but this should be a problem though)
