### ISSUE TITLE
http connection establish callback

### ISSUE THREAD

**Issue by submarineblue** [libevent/libevent#549]
As for http connection, we have close callback, but in some cases, we also need connection establish callback to notify us after re-connecting the remote host successfully.
Any plans about adding this callback?

**Comment by azat** [comment]
Could your provide an example what for this can be useful?

P.S. sorry for the delay, got lost in mailbox.

**Comment by NathanFrench** [comment]
> Could you provide an example what for this can be useful?

I'm guessing state-management, or simply informational.

While I get it, I'm not sure on why this cannot be done at the app level, and not the library level.

It's been almost a year without much interest; I'd say we box this for now.
