### ISSUE TITLE
The libevent-2.1.8-stable.tar.gz file is missing cmake

### ISSUE THREAD

**Issue by fquinner** [libevent/libevent#551]
The uploaded release tarball from the releases page `libevent-2.1.8-stable.tar.gz` looks like it doesn't contain cmake lists source. The one that github generate from source looks fine though.

**Comment by azat** [comment]
I guess it will be added in the next release (since current is already released), for the discussion see #502

**Comment by azat** [comment]
(closing this one, in favor to #502)
