### ISSUE TITLE
AppVeyor CI is not working properly

### ISSUE THREAD

**Issue by KindDragon** [libevent/libevent#555]
Readme.md refers to the appveyor in the fork

**Comment by azat** [comment]
Sorry for the delay, yes it was done on purpose, I guess because subscription was added to nmathewson user at first. But since subscription expired for nmathewson anyway, I will fix this.

**Comment by azat** [comment]
And yes, there is only [nmathewson/Libevent](https://ci.appveyor.com/project/nmathewson/libevent) and no [libevent/libevent](https://ci.appveyor.com/project/libevent/libevent)
