### ISSUE TITLE
Port event_rpcgen.py to Python 3

### ISSUE THREAD

**Issue by Aerdan** [libevent/libevent#558]
I've ported `event_rpcgen.py` to Python 3 in order to eliminate it as a required dependency on Python 2: https://freki.aerdan.org/py3_rpcgen.diff

And a port for `test/check-dumpevents.py`: https://freki.aerdan.org/py3_dumpevents.diff

**Comment by azat** [comment]
Great!

Maybe you can you make it python2-3 compatible (and also remove some commented code) and send via pull-request? (since libevent can be configured on a lot of platforms and some them are pretty old).

**Comment by Aerdan** [comment]
The scripts should work on Python 2 as well, as patched; it's just a matter of calling the interpreter manually rather than via the shebang.

PR incoming.

**Comment by azat** [comment]
Then maybe just make `#!/usr/bin/env python` in shebang?

**Comment by Aerdan** [comment]
Wouldn't help, the wrapper script calls Python itself. So the PR I made has been modified.
