### ISSUE TITLE
CONNECT rejects requests that fail uri parsing

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#572]
`evhttp` fails when a `CONNECT` request has an authority that fails URI parsing:

```
> CONNECT 61000047.r.bat.bing.com:443 HTTP/1.1
> Host: 61000047.r.bat.bing.com:443
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 400 Bad Request
< Content-Type: text/html
< Connection: close
< Date: Mon, 13 Nov 2017 10:12:40 GMT
< Content-Length: 94
< 
```

However, `CONNECT` requests don't use URIs. They use `host:port` authorities: https://tools.ietf.org/html/rfc7231#section-4.3.6

The problem seems to be that `evhttp_parse_request_line` calls `evhttp_uri_parse_with_flags` even for `CONNECT` calls. Humorously, requests like `CONNECT google.com:443 HTTP/1.1` succeed because the parser thinks "google.com" is the `scheme`, and the path is `443` (as if it was `google.com://443`). The `61000047.r.bat.bing.com` example above fails because `scheme_ok` doesn't allow the scheme to start with a digit.

**Comment by azat** [comment]
Closed by 65eb529
