### ISSUE TITLE
event_base_loopbreak does not break

### ISSUE THREAD

**Issue by mm-at** [libevent/libevent#573]
Hi everybody,
 
I create a event base from my main thread and start a "event_base_loop" in a new thread.
From the main thread I try to stop the new thread in order to quit properly.

Unfortunately event_base_loopbreak does not end.
I test the same when no events have been added in the base --> same result.
The only way I found to force quit, is to add a periodical event to "unblock" the "loopbreak". See my source code below.
Is the correct way to stop an event_base_loop? Is there an another manner?

thanks

```javascript
#include <boost/thread.hpp>
#include <iostream>
#include <string>
#include <unistd.h>



void start_dispatch(struct event_base* base)
{
  int ret = event_base_loop(base, EVLOOP_NO_EXIT_ON_EMPTY);
  std::cout << "[MAIN] loop returned with ret " << ret << std::endl;
}

void timer_cb(evutil_socket_t fd, short what, void * arg)
{
  struct event* evt = *(struct event**)arg;
  struct timeval tv = {1, 0};
  evtimer_add(evt, &tv);
  std::cout << "cucu" << std::endl;
}

int main()
{

  struct event_base* base = event_base_new();

  // Creation of a 1s timer in order to be able to stop
  // with the event_base_loopbreak function
  // If this timer is not started, the loopbreak returns 0
  // but the event_base_loop does not stop...
  struct event* evt;
  evt = evtimer_new(base, &timer_cb, &evt);
  struct timeval tv = {1, 0};
  evtimer_add(evt, &tv);

  boost::thread dispatch_thread(start_dispatch, base);
  std::cout << "[MAIN] dispatch started" << std::endl;

  /* these functions have been added to help to understand why loopbreak does not quit */
  int event_nb = event_base_get_num_events(base, EVENT_BASE_COUNT_ADDED);
  std::cout << "[MAIN] Nb of added events in base: " << event_nb << std::endl;
  event_nb = event_base_get_num_events(base, EVENT_BASE_COUNT_ACTIVE);
  std::cout << "[MAIN] Nb of active events in base: " << event_nb << std::endl;

  int lb = event_base_loopbreak(base);
  std::cout << "[MAIN] loopbreak returned " << lb << std::endl;
  sleep(1);
  dispatch_thread.join();
  event_free(evt);
  event_base_free(base);
  std::cout << "[MAIN] finito" << std::endl;
  return 0;
}
```

**Comment by mm-at** [comment]
Hi azat,
You 're right, this solve my issue.
The only thing which make me strange for me, is that when I tested my programm with valgrind, the event_base_loopbreak makes me quit properly even without the timer callback.
Any idea of the reason?

Nevertheless, use_pthreads is the correct way.
Thanks for that

**Comment by azat** [comment]
Well valgrind runs your multi-threaded program in a single thread, [1]
to follow.
  [1]: http://valgrind.org/docs/manual/manual-core.html#manual-core.pthreads

**Comment by Streamlet** [comment]
notice that you specified: EVLOOP_NO_EXIT_ON_EMPTY
event_base_loopbreak only break current runonce-work in the loop, but don't stops the loop.
try use event_base_loopexit instead?
