### ISSUE TITLE
reset bufferent  timeout to some other value

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#575]
Is it possible suppose that on the  accept() callback i give some read and write timeout value and then based on a certain packet recieved i again reset the timeout value to another one,in that case case will the timeout value be updated on the latest one or the old one would be retained?

**Comment by azat** [comment]
What do you mean my *write timeout* for accept() ?

If I understand you correctly, then you just need regular timer event, and reset it once you need it (in accept callback, and if you use listener then in it's callback).

If you will have any follow up questions, please provide a 50-100L sample, that will help a lot.

**Comment by kushal4** [comment]
Thanks 
I think i have got it 

<b>
int bufferevent_set_timeouts(struct bufferevent *bufev,
    const struct timeval *timeout_read, const struct timeval *timeout_write);
</b>
by read timeout and write timeout  i meant the last two parameters of  bufferevent_set_timeouts function.

**Comment by azat** [comment]
But how does this connected to `accept()` ?

**Comment by azat** [comment]
So basically if you need a timeout for accept() you can write something like this:

```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include <event2/event.h>
#include <event2/listener.h>

void cb(struct evconnlistener *lev, evutil_socket_t fd, struct sockaddr *sa, int socklen, void *arg)
{
    puts("accept");
}
void bump(int fd, short events, void *arg)
{
    event_base_loopbreak(arg);
    puts("timedout");
}

int main(int argc, char **argv)
{
    struct sockaddr_in sin;
    memset(&sin, 0, sizeof(sin));
    sin.sin_family = AF_INET;
    sin.sin_addr.s_addr = htonl(0x7f000001); /* 127.0.0.1 */
    sin.sin_port = htons(3080); /* "You pick!" */

    struct event_base *base = event_base_new();
    struct evconnlistener *lev = evconnlistener_new_bind(
        base, cb, 0, 0, -1, (struct sockaddr *)&sin, sizeof(sin));
    assert(lev);
    evconnlistener_enable(lev);

    struct timeval tv = { .tv_sec = 1 };
    struct event *timer = evtimer_new(base, bump, base);
    evtimer_add(timer, &tv);

    puts("enter loop");
    event_base_dispatch(base);
    puts("loop finished");

    evconnlistener_free(lev);
    event_base_free(base);
    return EXIT_SUCCESS;
}
```

and the output will be:
```
$ gcc -g3 -levent_core test.c -o test && ./test |& ts
Nov 28 01:55:15 enter loop
Nov 28 01:55:15 timedout
Nov 28 01:55:15 loop finished
```

**Comment by azat** [comment]
@kushal4 does you still have problems with this?

**Comment by kushal4** [comment]
Sorry for late reply. The problem was resolved
