### ISSUE TITLE
evconnlistener_free() closes already established connections

### ISSUE THREAD

**Issue by kgraefe** [libevent/libevent#577]
I implemented a TCP server that handles only one connection at a time. While a client is connected I want it to refuse all subsequent connections on TCP level (hence, not accept and close immediately).

With libevent release-2.0.22-stable accomplished that by calling `evconnlistener_free()` within my `evconnlistener_cb()`. Recently I upgraded to libevent-2.1.8-stable and found that a695a720cda892c270736d127333d73553842094 breaks that behavior. With the new version, the established connection will be closed as soon as my callback returns.

**Comment by kgraefe** [comment]
I believe that this commit is just wrong: if `lev->cnt` is not `1` after the callback, `new_fd` will still never be closed in `listener_read_cb()`. So in that case it is the responsibility of user's code to close the file descriptor (which is fine). But why shouldn't it be in the other case? And how does the user's code know?

**Comment by azat** [comment]
@kgraefe thanks for pointing to this! I reverted that patch and also wrote a small test (though it requires to run under `valgrind --track-fds=yes` or smth like this)

**Comment by azat** [comment]
[Mailing list message](http://archives.seul.org/libevent/users/Oct-2017/msg00003.html)
