### ISSUE TITLE
the function `evhttp_uriencode` may have a memory leak.

### ISSUE THREAD

**Issue by lixiangyun** [libevent/libevent#584]
The beginning of function `evhttp_uriencode` alloc a memory ;

https://github.com/libevent/libevent/blob/416b48ba7a0b44407b7a053bd21830aa75d7162f/http.c#L3072

But the next `return (NULL);` three places have not free this memory;
https://github.com/libevent/libevent/blob/416b48ba7a0b44407b7a053bd21830aa75d7162f/http.c#L3081-L3100

**Comment by azat** [comment]
Indeed, nice catch!
I just pushed the fix for it.

Thanks again,
Azat.
