### ISSUE TITLE
evhttp_request_set_header_cb() unusable

### ISSUE THREAD

**Issue by jcoffland** [libevent/libevent#588]
Maybe I'm missing something but as far as I can tell there is no way to use ``evhttp_request_set_header_cb()`` for incoming connections.  You can set request callbacks on an ``evhttp`` using either ``evhttp_set_cb()`` or ``evhttp_set_gencb()``.  These callbacks are invoked in ``evhttp_handle_request()``.  ``evhttp_handle_request()`` is set as the main callback (``req->cb``) on new ``evhttp_request``s in ``evhttp_request_new()`` which is called by ``evhttp_associate_new_request_with_connection()``.  ``req->cb`` is called in a number of places but notably in ``evhttp_connection_done()``.  ``evhttp_connection_done()`` is not called unless there is an error or the entire request body has been read.  Therefore, since the first user callback is not invoked until after the request body is loaded, it is impossible to call ``evhttp_request_set_header_cb()`` in time to have it invoked.  Unless I'm missing something.

I believe the solution to add a function ``evhttp_set_header_cb()`` which sets the callback on the ``evhttp``.  Then in ``evhttp_request_new()`` copy the callback to the request.  If you like I would be willing to submit a PR for this.

**Comment by jcoffland** [comment]
I noticed this comment in the code which may be relevant:
```
	/*
	 * Callback added for forked-daapd so they can collect ICY
	 * (shoutcast) metadata from the http header. If return
	 * int is negative the connection will be closed.
	 */
	int (*header_cb)(struct evhttp_request *, void *);
```

**Comment by azat** [comment]
Does `evhttp_set_newreqcb()` will solve this for you? It was introduced in 727bcea130eb4beea9b1ea53604b9807f6819a9a and this means that you will have to compile libevent from sources, likely this is very easy thing to do.

**Comment by jcoffland** [comment]
I'll check it out.

I've also implemented functionality which limits the maximum number of simultaneous connections to an ``evhttp`` instance.  Is this something you'd be interested in a PR for?  The code is petty simple and I've carefully mimicked your coding style.

**Comment by azat** [comment]
Does `evhttp_set_newreqcb()` works for you?

**Comment by jcoffland** [comment]
What I really wanted was to limit the number of connections so a request callback doesn't quite address that since there can be multiple requests per connection.  Also, ``evhttp_set_newreqcb()`` is called before the HTTP headers are read so it does not allow you to drop a connection based on the header contents or requested path.

**Comment by jcoffland** [comment]
But on further reflection ``evhttp_set_newreqcb()`` does give me the opportunity to set ``evhttp_request_set_header_cb()`` before it's too late.  So I would say it does solve this issue.

**Comment by azat** [comment]
Yep, that what I was talking about. So can you close this? (anyway we have #592)
