### ISSUE TITLE
[warn] Epoll ADD(1) on fd 1 failed.  Old events were 0; read change was 1 (add); write change was 0 (none): Bad file descriptor

### ISSUE THREAD

**Issue by tengliu0929** [libevent/libevent#594]
When I use libevent to code, when I send message using curl, it then return not immediately.Then I check the error , the error is below:
[warn] Epoll ADD(1) on fd 1 failed.  Old events were 0; read change was 1 (add); write change was 0 (none): Bad file descriptor
I can't understand why epoll add fd 1 . I doubt that the function epoll_wait run out of waittime,but I check the source code, I can't find any answers。Does this is a bug for libevent 2?

**Comment by azat** [comment]
Not the one that I heard of. Can you share a sample to reproduce?

**Comment by ploxiln** [comment]
It sounds like you're using libcurl in a way intended for synchronous/threaded applications, and it is internally using epoll(), and by default it will send the response body to stdout (fd 1).

**Comment by tengliu0929** [comment]
@ploxiln Yes, exactly this circumstance.I use a http server which base on bufferevent, when I Post a message,  then this problem occur. When I daemon the process, this problem likely solved,But I konw, this way never be the right way to solve this problem ,can you give me some suggestion to solve this problem?  Thanks a lot

**Comment by ploxiln** [comment]
You could try to use [evhttp_make_request](http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/http_8h.html#a88c4f63045dc6567f8220d6d37426924) instead of libcurl. It should also be possible to use the curl "multi" interface in order to use the libevent event loop instead of curl using its own: https://curl.haxx.se/libcurl/c/libcurl-multi.html

**Comment by tengliu0929** [comment]
@azat Sorry for that I can't share this cause these samle is not mine, only I can do is supply with some screenshot for you. 
Sorry, I have tried uploading some screenshots , but I failed. Sorry for that

**Comment by tengliu0929** [comment]
@ploxiln I think this can not solve my problem ,cause I use curl tool  to manually test the program,  not curl library, I think the better way is how to avoid fd 1 being added to epoll, though I don't konw this way right or wrong.

**Comment by ploxiln** [comment]
That's easy the, you'll want to specify

```
        -o, --output <file>
              Write  output  to  <file> instead of stdout.
```

and probably `--silent --show-error` as well

**Comment by tengliu0929** [comment]
@ploxiln This does work, but in libevent ,how does epoll avoid add fd 1 or 0 or 2 to epoll file descriptor, if this work , does this also be a method to solve this problem?

**Comment by ploxiln** [comment]
That really depends on your application - I don't think libevent uses stdin/stdout/stderr automatically.

**Comment by NathanFrench** [comment]
The standard I/O streams are not static nor special.

If you close stdin/stdout/stderr somewhere (as with many forked applications), the file descriptor number is allowed to be reused.

My guess is the above, stdin/stdout are closed, not dup'd, and reused by a valid socket.

**Comment by azat** [comment]
Closed due to inactivity for a long time.
