### ISSUE TITLE
EV_READ / EV_WRITE conflict with libev

### ISSUE THREAD

**Issue by lws-team** [libevent/libevent#596]
Both libev and libevent have `EV_READ`, `EV_WRITE` and perhaps others in their public namespace

```
/usr/include/event2/event.h:#define EV_READ		0x02
/usr/include/event2/event.h:#define EV_WRITE	0x04
```

/usr/include/ev.h

```
  EV_READ     =            0x01, /* ev_io detected read will not block */
  EV_WRITE    =            0x02, /* ev_io detected write will not block */
```

libevent using preprocessor defines is particularly problematic for projects that include both headers, since it silently redefines the libev ones, breaking ev functionality.  It may seem esoteric to have multiple event loops, but some libraries find themselves having to support it and select which one at runtime.

I would like to suggest solving this by a) duplicating EV_* to EVENT_*, b) changing them to be defined in an enum, and c) making the original EV_* defines be conditional on there being no definition of "LIBEVENT_AVOID_LIBEV_CONFLICT" or so.  I can provide a patch if it sounds reasonable, or happy to consider any better ideas.

**Comment by ploxiln** [comment]
A bit of a complication is that libev intentionally provides an "event.h" and the core libevent api: http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#LIBEVENT_EMULATION

**Comment by lws-team** [comment]
Never mind... I asked on the libev list about aligning / cleaning these conflicting definitions and got called an arrogant beginner.  I adapted my project's cmake to not allow runtime choice between libev and libevent, and added a documentation about it suggesting if people have a choice they avoid libev.  So it remains broken.
