### ISSUE TITLE
bufferevent_socket_connect() and bufferevent_socket_connect_hostname() missing event callback or return code to user

### ISSUE THREAD

**Issue by boytm** [libevent/libevent#597]
1. When socket() failed in bufferevent_socket_connect() , the event callback should be called also in bufferevent_socket_connect_hostname().   
eg. when use bufferevent_socket_connect_hostname() to resolve and connect an IP address，but process have a smaller ulimit open files,  socket() fails always but caller is not notified.
2. Make bufferevent_socket_connect()'s behavior more consistent: function return error then no callback, function return ok then error passed by event callback.

This affect libevent 2.0.22 and 2.1.8 both.

**Comment by azat** [comment]
Closing this one in favor to #600
