### ISSUE TITLE
sample https-client can't resolve localhost

### ISSUE THREAD

**Issue by ddiss** [libevent/libevent#598]
sample/https-client initialises a evhttp connection context with a NULL evdns context. This means that HTTP(S) server name resolution ignores /etc/hosts, which is normally responsible for providing a localhost alias.

I have a simple patch that create a evdns context with EVDNS_BASE_INITIALIZE_NAMESERVERS , but I wonder whether the behaviour for evhttp_connection_base_bufferevent_new(evdns_base=NULL) should change, such that it processes etc/hosts. Feedback appreciated.

**Comment by azat** [comment]
This does not works, because it tries to go through the ipv6 address, while you server on localhost does not listen on ipv6 address.

**Comment by azat** [comment]
Here is a solution how you can prefer ipv4 over ipv6, for glibc only:
- `sed -i 's/::1/#::1/' /etc/hosts`

Also it worth noticing that changing `/etc/hosts` will change the behavior only for hosts there (obviously), to change defaults for all `getaddrinfo()` (that is used by libevent, if you have worked one, and if you have glibc it likely your case), then you can also do: 
- `sed -i 's@#precedence ::ffff:0:0/96  100@precedence ::ffff:0:0/96  100@' /etc/gai.conf`

**Comment by ddiss** [comment]
This has me a little confused, as I did some stracing of the current master sample/https-client binary, and hadn't seen it access /etc/hosts . I'll recheck this and respond here.
