### ISSUE TITLE
Problem building on Mingw

### ISSUE THREAD

**Issue by monkins1010** [libevent/libevent#604]
Hi im trying to build in mingw latest. I get:

```
listener.c: In function 'start_accepting':
listener.c:567:16: error: 'ERROR_IO_PENDING' undeclared (first use in this function)
   if (error != ERROR_IO_PENDING) {
                ^~~~~~~~~~~~~~~~
listener.c:567:16: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [listener.lo] Error 1
```

probably a user noob error , but lib usb installed and other things just not this thanks

Chris

**Comment by azat** [comment]
Hi!

Sorry for the enormous delay!
Can you verify attached patch?

Thanks!

**Comment by azat** [comment]
After fixing #649 I can confirm that mingw build should work, IOW I guess this can be closed.

**Comment by slavadba** [comment]
Hi,

I have the same problem  - but I cant find listener.c in my MInGW installation folder on Windows 8.1
Can you help?

**Comment by slavadba** [comment]
Maybe I fixed this - added #include <winerror.h> befor #include <winsock2.h> in my C file
