### ISSUE TITLE
VS2015/2017 X64 conflict with " Use MFC in a Static Library" on debug mode

### ISSUE THREAD

**Issue by isdqwq** [libevent/libevent#607]
Whether it is master(08a0d36) or Release 2.1.8 code

At **win10 x64 os** ,build libevent library with **cmake and vs2015/2017 ,and get x64 library**.
and **create new MFC project with vs2015 and set  "Use of MFC"-> "Use MFC in a Static Library"**
and will build failed on **x64 mode**.
and look like as below

```
1>event.lib(evutil.obj) : error LNK2019: unresolved external symbol __imp__getpid referenced in function evutil_weakrand_seed_
1>event.lib(evutil_rand.obj) : error LNK2001: unresolved external symbol __imp__getpid
1>event.lib(evutil.obj) : error LNK2019: unresolved external symbol __imp__fstat64 referenced in function evutil_read_file_
1>event.lib(buffer.obj) : error LNK2019: unresolved external symbol __imp_memchr referenced in function evbuffer_find_eol_char
1>event.lib(buffer.obj) : error LNK2019: unresolved external symbol __imp_close referenced in function evbuffer_file_segment_free
1>OLDNAMES.lib(close.obi) : error LNK2001: unresolved external symbol __imp_close
1>event.lib(buffer.obj) : error LNK2019: unresolved external symbol __imp_read referenced in function evbuffer_file_segment_materialize
1>OLDNAMES.lib(read.obi) : error LNK2001: unresolved external symbol __imp_read
1>event.lib(buffer.obj) : error LNK2019: unresolved external symbol __imp__fstat64i32 referenced in function evbuffer_file_segment_new
```

To Fix this issue, must select "Use of MFC" to "Use MFC in a Shared DLL"

![image](https://user-images.githubusercontent.com/16586516/37453912-276ca3ce-2874-11e8-82bc-90b70bb4719c.png)

question.
  how to build MFC in a static library with libevent x64 library

**Comment by azat** [comment]
I think that the problem here is that since 7182c2f561570cd9ceb704623ebe9ae3608c7b43 cmake tries to compile both static and shared libraries at the same time, while there are one set of headers.

So can you please get last libevent from git (you can even download .zip archive from github) and try to compile it? Maybe ce3af533f1b11c4b302d404483f28660eb5d7190 will be enough to fix this issue, if not then this requires some deep looking into it.

**Comment by isdqwq** [comment]
Hi azat  
the last code which master(08a0d366073eacf800027725891c2f668f2f0144) or  Release 2.1.8 ,both have this issue.
and vs2017 can't build 7182c2f 
libevent\include\event2\util.h(187): fatal error C1017: invalid integer constant expression
as you said the old libevent

**Comment by azat** [comment]
Maybe my reply was confusing, but I wanted you to try ce3af53, is it possible?

**Comment by isdqwq** [comment]
Hi @azat 
  I just try the last code on master (c57f5c34903b02c6e7378865f71a2b83a5befb96)
build libevent with vs2017
for debug library libevent , build MFC project with mfc static library mode ,it's work OK both debug and release
but release libevent libary build MFC project with mfc static library mode, both get same error for debug or release

`1>event.lib(evutil.obj) : error LNK2019: unresolved external symbol __imp__getpid referenced in function evutil_weakrand_seed_
1>event.lib(evutil_rand.obj) : error LNK2001: unresolved external symbol __imp__getpid
1>event.lib(evutil.obj) : error LNK2019: unresolved external symbol __imp__fstat64 referenced in function evutil_read_file_
1>event.lib(buffer.obj) : error LNK2019: unresolved external symbol __imp_close referenced in function evbuffer_file_segment_free
1>OLDNAMES.lib(close.obi) : error LNK2001: unresolved external symbol __imp_close
1>event.lib(buffer.obj) : error LNK2019: unresolved external symbol __imp_read referenced in function evbuffer_file_segment_materialize
1>OLDNAMES.lib(read.obi) : error LNK2001: unresolved external symbol __imp_read
1>event.lib(buffer.obj) : error LNK2019: unresolved external symbol __imp__fstat64i32 referenced in function evbuffer_add_file
`

**Comment by isdqwq** [comment]
for  ce3af53

libevent (Debug):
x64_MFC (Static library ) +MFC (DEBUG/Release)  FAIL.
x64_MFC (share library ) +MFC (DEBUG/Release)  PASS

libevent (Release):
x64_MFC (Static library ) +MFC (DEBUG/Release)  FAIL.
x64_MFC (share library ) +MFC (DEBUG/Release)  PASS

**Comment by isdqwq** [comment]
Hi @azat 
the last code on master (c57f5c34903b02c6e7378865f71a2b83a5befb96) 

libevent (Debug):
x64_MFC (Static library ) +MFC (DEBUG/Release) PASS.
x64_MFC (share library ) +MFC (DEBUG/Release) PASS

libevent (Release):
x64_MFC (Static library ) +MFC (DEBUG/Release) PASS.
x64_MFC (share library ) +MFC (DEBUG/Release) PASS

so the Last ocde is work on,and fix this issue,  thanks

**Comment by azat** [comment]
Refs: #702
