### ISSUE TITLE
Need macro or convenience function for creating user-triggered macros

### ISSUE THREAD

**Issue by pprindeville** [libevent/libevent#609]
The libevent book talks about user-triggered macros (R4: Working with events) but doesn't refer to any canonical way to do this.

Can a macro or convenience function be added to do exactly this?

**Comment by azat** [comment]
So basically you want something like this (and related) helpers (`static inline` or `#define`)?

```
static inline struct event *evtrigger_new(struct event_base *base, event_callback_fn fn, void *arg)
{ return event_new(base, -1, 0, fn,arg); }
```

You already tried to do this in #423 (and asked in #420), but with introducing another `EV_*` for this, which looks useless, since it works without it.

As for this helpers, I'm not against them.

**Comment by pprindeville** [comment]
I don't think any of the headers currently have inline functions, do they?

**Comment by pprindeville** [comment]
See PR #647.

**Comment by azat** [comment]
> I don't think any of the headers currently have inline functions, do they?

Yeah, you are right! (ugh)

**Comment by azat** [comment]
Patch from #647 - merged. Closing this one.
