### ISSUE TITLE
Base not woken up when deleting last event

### ISSUE THREAD

**Issue by mistotebe** [libevent/libevent#623]
To handle graceful shutdown correctly, I do the following for each dispatcher thread:
- create a sentinel event with `sentinels[thread_id] = event_new( base, -1, EV_READ, cb, NULL ); event_add( sentinels[thread_id] );` that is never triggered
- when the server is told to start shutdown, the signal thread removes the above event
- once all other events disappear from the event base, it will naturally return and the thread can be joined
- when all dispatcher threads have been joined, the process can exit and no work has been lost

The problem is when shutdown is initiated and there is a thread that is completely idle (no other events but the designated sentinel). Removing the sentinel event at that point won't notify the event base and it will wait there forever. If we need a sentinel to be an event that can never be triggered except by user code, there is no event type whose deletion would trigger a notification on the dispatching thread.

In libevent 2.1, a workaround is to call `event_loop_continue`, but that is not available in 2.0. A small program to reproduce this follows:

```C
#include <stdio.h>
#include <unistd.h>
#include <pthread.h>

#include <event2/event.h>
#include <event2/thread.h>

void
cb( evutil_socket_t fd, short what, void *arg )
{
	return;
}

void *
worker( void *arg )
{
	struct event_base *base = arg;

	printf( "Worker: Starting up\n" );
	if ( event_base_dispatch( base ) == 1 ) {
		printf( "Worker: Successfully exited when running out of events\n" );
	}
}

int
main( int argc, char **argv )
{
	struct event_base *base;
	struct event *event;
	pthread_t tid;

	evthread_use_pthreads();

	base = event_base_new();
	event = event_new( base, -1, EV_READ, cb, NULL );
	event_add( event, NULL );

	printf( "Main thread: starting worker\n" );
	pthread_create( &tid, NULL, worker, base );
	sleep(1);

	printf( "Main thread: removing last pending event\n" );
	event_del( event );

#if (EVENT__NUMERIC_VERSION >= 0x02010000)
	if ( argc > 1 ) {
		printf( "Main thread: signalling base\n" );
		event_base_loopcontinue( base );
	}
#endif

	pthread_join( tid, NULL );
	printf( "Main thread: worker finished, cleaning up\n" );

	event_free( event );
	event_base_free( base );
}
```

**Comment by mistotebe** [comment]
Also, of note is the fact that removing the last timeout event does not notify the base either, so it might take a while before it would notice and exit on its own, potentially triggering any timeout logic that told the process to shut down.

**Comment by azat** [comment]
Well I will strongly recommend to use 2.1 stable release.

But if you can't, you can [add](https://gist.github.com/azat/a251a7b792f6cbd9d45583ce2495402a) `event_active(event, 0, 1)` before `event_del()` this will activate last event and notify event base in worker thread since after it will execute event's callback there will be no more events and it will exit.

P.S. the reason why `event_del()` does not do this, is because the fd is not real.

**Comment by mistotebe** [comment]
Even if dealing with 2.1, this is an issue.

In the example, you activate the event, so event_del has no effect since that makes it no longer pending then. I understand that event_del decides not to notify the base, since the event doesn't deal with a real fd, that's the behaviour I think is buggy.

So shouldn't libevent check if this makes the event count reach zero and notify the base regardless of whether the event we're removing pertains to a real fd/signal?

**Comment by azat** [comment]
> that's the behaviour I think is buggy

It is an optimization for multi-threaded app with lots of timers (ba8a17714ead9f36424c4ecc21c009735d1408e5)

> So shouldn't libevent check if this makes the event count reach zero and notify the base regardless of whether the event we're removing pertains to a real fd/signal?

Yep, this is the thing we can do, something like referenced patch
