### ISSUE TITLE
Requests with OPTIONS type being rejected by libevent

### ISSUE THREAD

**Issue by backendjavadeveloper** [libevent/libevent#629]
I am trying to create a server, which will be listening on port 80. Things work okk (i.e. my callbacks are invoked correctly) if the incoming requests is of type GET/POST/PUT/DELETE. But when the browser sends a preflight CORS request (of type OPTIONS), LibEvent is responding with a 501 and code control doesn't even reach the callback function in c++.

Can you please suggest on what is missing here??? I am blocked coz of this.

**Comment by ploxiln** [comment]
Use `evhttp_set_allowed_methods()` - http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html/http_8h.html#a2779135d52b7524415e11448079bfc8f

**Comment by backendjavadeveloper** [comment]
Thanks for the answer. I need to support multiple types i.e. GET/POST/OPTIONS. So if I use the above mentioned method, the second argument of this method only accepts 1 TYPE as the input.
How do I pass multiple types to this function?

Tried these -
evhttp_set_allowed_methods(m_Server,EVHTTP_REQ_GET);
evhttp_set_allowed_methods(m_Server,EVHTTP_REQ_POST);
evhttp_set_allowed_methods(m_Server,EVHTTP_REQ_OPTIONS);
Using above approach, the last statement will override the existing value. 

Can you please help??

**Comment by backendjavadeveloper** [comment]
nvm, I was able to figure that out. Thanks for all the help :)

this worked  
evhttp_set_allowed_methods(server,
            EVHTTP_REQ_GET |
            EVHTTP_REQ_POST |
            EVHTTP_REQ_OPTIONS)
