### ISSUE TITLE
bufferevent_read() returns too early.

### ISSUE THREAD

**Issue by mengyaoss77** [libevent/libevent#631]
```c
struct content {
  char *buf;
  size_t len;
  size_t size;
  bool complete;
};

void readcb(struct bufferevent *bev, void *ctx){
  struct content *ct = (struct content *)ctx;
  char buf[BUFFSIZE];  //#define BUFFSIZE 4096
  size_t readn;
  while (1) {
    readn = bufferevent_read(bev, buf, BUFFSIZE);
    if (readn <= 0) {
      ct->complete = true;
      break;
    }
    if (ct->size < ct->len + readn) {
      ct->buf = (char *)realloc(ct->buf, (ct->size + BUFFSIZE)*sizeof(char));
      ct->size += BUFFSIZE;
    }
    cout << "readn: " << readn << endl;
    memcpy(ct->buf + ct->len, buf, readn);
    ct->len += readn;
  }
  
  if (ct->complete) {
    cout << ct->buf << "strlen: " << ct->len << endl;
    cout << "ct->size" << ct->size << endl;
  }
}
```

When I tried to send 4097 bytes data with ```c write(int fd, void *buf, size_t size); ``` ,
the bufferevent_read() returned 0 while it received 4096 bytes data and then the callback function returned.(My program decided it had finished received all data but it wasn't) .
Then, the callback function was immediantly called one more time to receive the remain 1 byte data.

How can I know whether my program has finished receiving the data？

Sorry for my poor English.

**Comment by NathanFrench** [comment]
> How can I know whether my program has finished receiving the data？

This is not the job of libevent to know when your data is finished receiving, as this can vary protocol to protocol.

In the case above, libevent is doing things right, you sent 4097 bytes, read in 4096, and since the socket is still readable with 1 byte remaining, it will call the read callback again (and again until it is no longer readable).

A better approach would be something like:

```C
void readcb(bev, ....) {
    size_t len = evbuffer_get_length(evbuffer_get_input(bev));
    char *buf = malloc(len); // or on the stack char buf[len];

    ....

    readn = bufferevent_read(bev, buf, len);
    ....
}
```

**Comment by mengyaoss77** [comment]
@NathanFrench
Thanks for your reply.
I tried your way ``` size_t len = evbuffer_get_length(evbuffer_get_input(bev)) ```,
but this  returned 4096 in my situation.  Maybe bufferevent can't do the job well.
I give up using Bufferevent and change my code into the normal event, and it uses *fd* to read/write data, it works.

**Comment by azat** [comment]
So If I understand you correctly you should just add length of the payload in you protocol, otherwise there is no guarantee that you read all data in the message.

i.e. something like this (totally untested):

```c
void readcb(struct bufferevent *bev, void *arg)
{
    struct evbuffer *buf = evbuffer_get_input(bev);
    size_t length = evbuffer_get_length(buf);
    int size = 0;
    if (length < sizeof(int)) {
        return;
    }
    length -= 4;
    /* endianness issue */
    evbuffer_remove(buf, &size, sizeof(size));
    assert(size > 0);
    if (length < size) {
        return; /* not enough data */
    }

    evbuffer_write(buf, STDOUT_FILENO);
}
```

and writing
```c
void write(int fd, char *data, int len)
{
    write(fd, &len, sizeof(len));
    write(fd, data, len);
}
```

**Comment by mengyaoss77** [comment]
@azat Sorry I miss the message before. 
I  considered your method, but it maybe make the program more complex. And it can't work well on 
 the situation that between big-endian and small-endian devices. So I prefer to use the way with normal event callback.
