### ISSUE TITLE
rpc_struct.h Missing definition for TAILQ_ENTRY

### ISSUE THREAD

**Issue by babyaaaaaa** [libevent/libevent#633]
when use libevent lib in my project  it will has an compile error : TAILQ_ENTRY

**Comment by NathanFrench** [comment]
> Worst... Compiler... Ever...

But in all seriousness, your compiler gave you nothing other than the word "TAILQ_ENTRY"?

**Comment by azat** [comment]
If you include `rpc_struct.h` directly then you will get this error, since it does not includes `sys/queue.h`. Just fixed it (for now by just inlining the same definition as in `event.h`, later we should clean this up)
