### ISSUE TITLE
taking incoming chunked data problem - chunk_cb isn't called

### ISSUE THREAD

**Issue by Elunyfay** [libevent/libevent#634]
Hello, kind peoples! I'm trying to write http server with **evhttp** class which must be able to take chunked requests. I've found function "**evhttp_request_set_chunked_cb**(evhttp_request *request, void *params);" that simply sets "**req->chunk_cb** = myfunction;"
My problem - **the function I've set is never called**. Only universal **evhttp->gencb** is called.

I've used code of "lightweight libevent webserver less than in 40 lines" as base for my program https://kukuruku.co/post/lightweight-http-server-in-less-than-40-lines-on-libevent-and-c-11/ 
That has a few threads, each with 1) EventBase => 2) EvHttp configured with 1) evhttp_set_allowed_methods 2) maxHeadersSize, maxBodySize 3) evhttp_set_gencb main callback for all incoming requests 4) bound on socket.

Function **set_chunked_cb** requires **evhttp_request*** so I'm setting it's value from gencb callback function (in OnRawRequest). My second c# application sends first chunked block 1024b, then gencb is called once, then I see this first part of data, set chunked_cb and... that's all. I'm waiting for chunked_cb being called, but it doesn't.

Where am I wrong? I've tryed for a few mounths before asking, but stuck still.
[http_server.cpp.txt](https://github.com/libevent/libevent/files/1983338/http_server.cpp.txt)

**Comment by azat** [comment]
In an nut shell - you cannot use `evhttp_request_set_chunked_cb()` for input requests (your case with web server), only for output requests.

This is so because once your `gencb` called all request already received from the client and no more io will be done until you will reply to it. And this is a long-standing issue - libevent's http server read all request before pass it to the user.

There was a plan about merging libevhtp (BTW you can try use it instead) in #261, but it stalled for a 2years+.

P.S. please use markdown

**Comment by NathanFrench** [comment]
Oh yeah, libevhtp. 

It seems as if it's pretty easy to [stream chunked data](https://github.com/criticalstack/libevhtp/blob/develop/examples/example_chunked.c) with it, and that's an advanced (new'ish) example.

**Comment by Elunyfay** [comment]
Somebody has build it on Windows sucessfully? I'm making linux/windows code. Tryed for one week, yet didn't get it.

**Comment by NathanFrench** [comment]
@Elunyfay can you head over to https://github.com/criticalstack/libevhtp/issues/new and paste the output of your build? It should work in WIN, want to document your problems.

Thanks!

**Comment by moihn** [comment]
What I've done to stream the server side input stream is to setup callback on the input buffer of evhttp_request.
```
void request_input_buffer_cb(evbuffer* buffer, const evbuffer_cb_info* info, void* arg)
{
    if (info->n_added > 0)
    {
        // do something with buffer who has all received chunk
        // note the buffer is the same input buffer as in gencb()/cb() callbacks function,
       // so if you process from front and move processed data out, they will not
       // be available in the gencb()/cb() function's request object. This makes the same effect
       // as streaming processing input request body chunk by chunk.
    }
}

int new_request_cb(req, arg)
{
            evbuffer *input = evhttp_request_get_input_buffer(req);
            evbuffer_add_cb(input, request_input_buffer_cb, handler);
}
evhttp_set_newreqcb(m_httpd, new_request_cb, arg);
