### ISSUE TITLE
can't support openssl ASYNC mode 

### ISSUE THREAD

**Issue by dclock123** [libevent/libevent#641]
Dear,  
    We plan to use intel QAT accelerator card to improve HTTPS performance. Our application architect is apps + libevent + openssl( QAT supported). For best performance, openssl(QAT supported) must work in ASYNC mode, otherwise the performance is even worse than cpu computation.  As HTTPS apps are more and more popular and now intel QAT is a popular hardward accelerator solution. We strongly request libevent to support openssl ASYNC mode. Please take consideration, thanks a lot.

pre discussion as below:  
https://github.com/libevent/libevent/issues/403

dclock123

**Comment by azat** [comment]
Hi @dclock123 

Right now this is not in the top-priority list (and actually there is a lot of more-major/less-specific issues that requires attention), but if you want to contribute this to libevent this is always welcome.

I'm closing this for now, since we have #403
