### ISSUE TITLE
win32 autotools build failure (appveyor)

### ISSUE THREAD

**Issue by azat** [libevent/libevent#649]
https://ci.appveyor.com/project/nmathewson/libevent/build/2.2.0.478/job/rwy5jpu0i5elv985

```
./include/event2/event-config.h:542:28: error: two or more data types in declaration specifiers
 #define socklen_t unsigned int
```

https://github.com/libevent/libevent/pull/646#issuecomment-398932285

**Comment by pprindeville** [comment]
Any ideas on what this is about?

**Comment by azat** [comment]
In short I think that `<ws2tcpip.h>` is missing (while detecting of `socklen_t`), I will confirm this and get back

**Comment by azat** [comment]
(waiting for https://ci.appveyor.com/project/azat/libevent/build/2.2.0.3/job/18v3y8y5597lo8by)

**Comment by pprindeville** [comment]
So that was it?  Good job chasing it down.  Really bizarre compiler warning, though.

**Comment by pprindeville** [comment]
How long before we can kill off WIN32?

**Comment by azat** [comment]
>How long before we can kill off WIN32?

If by "kill off win32" you mean "stop supporting win32 by libevent", then the answer is "never", since it is kind of the libevent "thing" -- be so cross platform/os

**Comment by pprindeville** [comment]
Sure, but when do platforms or releases become obsolete?
