### ISSUE TITLE
Need getnameinfo() for symmetry

### ISSUE THREAD

**Issue by pprindeville** [libevent/libevent#653]
Having asynchronous `getaddrinfo()` info is handy, but sometimes you need asynchronous name-to-address mapping too, for instance, in trying to apply a name-based ACL to an incoming connection, etc.

Shouldn't be too different from the current `getaddrinfo()` code.

Do you need to handle CNAME's?  Yes, I guess you can try to look up a PTR and get back a CNAME which you then need to lookup (per RFC-2317).

**Comment by azat** [comment]
So you are saying about wrapper around `evdns_base_resolve_reverse()`, like `evdns_getaddrinfo()` around `evdns_base_resolve_ipv4()`/`evdns_base_resolve_ipv6()`?
