### ISSUE TITLE
Need struct evconnlistener static initializers

### ISSUE THREAD

**Issue by pprindeville** [libevent/libevent#656]
If you can have a `struct event` which is static and which gets initialized via `event_assign()`, then a homologous interface to `struct evconnlistener` and initializing those (without heap allocation) would be handy as well for heap-constrained systems or where you have bounded execution-time and don't want to have to walk the heap's free list.

**Comment by NathanFrench** [comment]
This would mean exposing internal structures; something we have been trying to get away from for some time (this includes `struct event;`)

If your code uses `event2/event_struct.h`, it is considered "legacy" and is not supported:

```C
/** @file event2/event_struct.h
 
  Structures used by event.h.  Using these structures directly WILL harm
  forward compatibility: be careful.
 
  No field declared in this file should be used directly in user code.  Except
  for historical reasons, these fields would not be exposed at all.
 */
```

**Comment by azat** [comment]
> bounded execution-time and don't want to have to walk the heap's free list.

If you hot path is "creating the listener", then you are in trouble anyway.

Plus I'm agree with @NathanFrench we are trying to avoid exposing structures (since this means that you cannot simply reorder/add fields in/to them, because this will break ABI compatibility)
