### ISSUE TITLE
evrpc_request_cb core dump

### ISSUE THREAD

**Issue by CaseZheng** [libevent/libevent#660]
![default](https://user-images.githubusercontent.com/17766535/42614324-f88d8c0a-85d7-11e8-886c-1501f9ca0328.png)
![default](https://user-images.githubusercontent.com/17766535/42614331-06472e8c-85d8-11e8-937d-76cf83a0138c.png)

**Comment by azat** [comment]
Thanks for details (even though they are on screenshots)!
Fixed in the referenced patch (with regression test).
