### ISSUE TITLE
bufferevent_openssl.c Errors

### ISSUE THREAD

**Issue by slytherin20** [libevent/libevent#662]
**Hello  I'm trying to install libevent-2.0.21-stable but I'm getting a lot of errors.I have OpenSSL version 1.1.0h version in my system and I'm using Ubuntu 18.04.
I'm getting the following error:** 
bufferevent_openssl.c: In function 'bio_bufferevent_new':
bufferevent_openssl.c:106:3: error: dereferencing pointer to incomplete type 'BIO {aka struct bio_st}'
  b->init = 0;
   ^~
bufferevent_openssl.c: At top level:
bufferevent_openssl.c:228:1: error: variable 'methods_bufferevent' has initializer but incomplete type
 static BIO_METHOD methods_bufferevent = {
 ^~~~~~
bufferevent_openssl.c:79:27: warning: excess elements in struct initializer
 #define BIO_TYPE_LIBEVENT 57
                           ^
bufferevent_openssl.c:229:2: note: in expansion of macro 'BIO_TYPE_LIBEVENT'
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^~~~~~~~~~~~~~~~~
bufferevent_openssl.c:79:27: note: (near initialization for 'methods_bufferevent')
 #define BIO_TYPE_LIBEVENT 57
                           ^
bufferevent_openssl.c:229:2: note: in expansion of macro 'BIO_TYPE_LIBEVENT'
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^~~~~~~~~~~~~~~~~
bufferevent_openssl.c:229:21: warning: excess elements in struct initializer
  BIO_TYPE_LIBEVENT, "bufferevent",
                     ^~~~~~~~~~~~~
bufferevent_openssl.c:229:21: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:230:2: warning: excess elements in struct initializer
  bio_bufferevent_write,
  ^~~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:230:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:231:2: warning: excess elements in struct initializer
  bio_bufferevent_read,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:231:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:232:2: warning: excess elements in struct initializer
  bio_bufferevent_puts,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:232:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:233:2: warning: excess elements in struct initializer
  NULL /* bio_bufferevent_gets */,
  ^~~~
bufferevent_openssl.c:233:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:234:2: warning: excess elements in struct initializer
  bio_bufferevent_ctrl,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:234:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:235:2: warning: excess elements in struct initializer
  bio_bufferevent_new,
  ^~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:235:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:236:2: warning: excess elements in struct initializer
  bio_bufferevent_free,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:236:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:237:2: warning: excess elements in struct initializer
  NULL /* callback_ctrl */,
  ^~~~
bufferevent_openssl.c:237:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:228:19: error: storage size of 'methods_bufferevent' isn't known
 static BIO_METHOD methods_bufferevent = {
                   ^~~~~~~~~~~~~~~~~~~
Makefile:793: recipe for target 'bufferevent_openssl.lo' failed
make[2]: *** [bufferevent_openssl.lo] Error 1
make[2]: Leaving directory '/home/slytherin20/libevent-2.0.21-stable'
Makefile:857: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/slytherin20/libevent-2.0.21-stable'
Makefile:592: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ploxiln** [comment]
openssl-1.1 support is available in libevent-2.1 releases
https://github.com/libevent/libevent/commit/3e9e0a0d46e4508e8782ec3787c6d86bab63046d

**Comment by slytherin20** [comment]
I solved the issue by installing current version of the openssl.
