### ISSUE TITLE
Event callback not fired when 2 fin packet sent simultaneously

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#665]
Hi,
I am sending 2 Fin packet to the server which implements libevent simultaneously.but both of the callbacks are not triggered simultaneously.In order to prevent delay time ,I am using detached thread to the codebase within the event callbavk.Please suggest me as to how both of the fin packets will be handled simultaneously by the callback.
PS:- fin packet as usual is sent from 2 different sockets and thus close is initiated from both clients simultaneously

**Comment by kushal4** [comment]
I am also setting BEV_OPT_DEFFERED_CALLBACK option to the buffer event in order to fire the event callbacks in the queue as mentioned in the documentation but still it fires only one callback

**Comment by NathanFrench** [comment]
Two different fins for one socket? Can you use `strace` to make sure the kernel isn't discarding the other?

**Comment by kushal4** [comment]
No actually fin is sent for 2 different sockets and the fin packet is captured in Wireshark too.can u suggest me work around code in order to catch these 2 sockets FIN. There is a slight microseconds delay between Fin packets sent by 2 sockets

**Comment by kushal4** [comment]
No actually fin is sent for 2 different sockets and the fin packet is captured in Wireshark too.can u suggest me work around code in order to catch these 2 sockets FIN. There is a slight microseconds delay between Fin packets sent by 2 sockets

**Comment by NathanFrench** [comment]
Technically you won't see a "fin" packet - you would see a socket error. Do you see a socket error? Can you please run `strace -f <yourbin>` or paste the relevant code here?

**Comment by kushal4** [comment]
sorry  I  think  there was a fault  in  my code i  triggered the wrong way to  the callback.Its working  now.If  i face any issue  any  further , i will post  the details here.
Thanks :)
