### ISSUE TITLE
evutil_found_ifaddr() filters invalid v4 addresses incompletely

### ISSUE THREAD

**Issue by nianxuejie** [libevent/libevent#668]
V4 address like "169.254.*.*",that is invalid as 127.0.0.1

**Comment by azat** [comment]
> V4 address like "169.254.*.*",that is invalid as 127.0.0.1

Hm, this cannot be true, since all it does is checking the first octet:
  (gdb) p/x (in_addr_t)inet_addr("169.156.0.0")
  $1 = 0x9ca9
  (gdb) p/x (in_addr_t)inet_addr("127.0.0.1")
  $2 = 0x100007f
  (gdb) p (unsigned)ntohl($2)>>24
  $10 = 127
  (gdb) p (unsigned)ntohl($1)>>24
  $12 = 169

Can you post an example?
BTW how you get into this *static* function?

**Comment by nianxuejie** [comment]
I do not understand what you mean. This is the 2.1.8 code:
`/* Macro: True iff the IPv4 address 'addr', in host order, is in 127.0.0.0/8
 */
#define EVUTIL_V4ADDR_IS_LOCALHOST(addr) (((addr)>>24) == 127)

/* Macro: True iff the IPv4 address 'addr', in host order, is a class D
 * (multiclass) address.
 */
#define EVUTIL_V4ADDR_IS_CLASSD(addr) ((((addr)>>24) & 0xf0) == 0xe0)

static void
evutil_found_ifaddr(const struct sockaddr *sa)
{
	const char ZEROES[] = "\x00\x00\x00\x00\x00\x00\x00\x00"
	    "\x00\x00\x00\x00\x00\x00\x00\x00";

	if (sa->sa_family == AF_INET) {
		const struct sockaddr_in *sin = (struct sockaddr_in *)sa;
		ev_uint32_t addr = ntohl(sin->sin_addr.s_addr);
		if (addr == 0 ||
		    EVUTIL_V4ADDR_IS_LOCALHOST(addr) ||
		    EVUTIL_V4ADDR_IS_CLASSD(addr)) {
			/* Not actually a usable external address. */
		} else {
			event_debug(("Detected an IPv4 interface"));
			had_ipv4_address = 1;
		}
	} else if (sa->sa_family == AF_INET6) {
		const struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)sa;
		const unsigned char *addr =
		    (unsigned char*)sin6->sin6_addr.s6_addr;
		if (!memcmp(addr, ZEROES, 8) ||
		    ((addr[0] & 0xfe) == 0xfc) ||
		    (addr[0] == 0xfe && (addr[1] & 0xc0) == 0x80) ||
		    (addr[0] == 0xfe && (addr[1] & 0xc0) == 0xc0) ||
		    (addr[0] == 0xff)) {
			/* This is a reserved, ipv4compat, ipv4map, loopback,
			 * link-local, multicast, or unspecified address. */
		} else {
			event_debug(("Detected an IPv6 interface"));
			had_ipv6_address = 1;
		}
	}
}
`

**Comment by nianxuejie** [comment]
Sorry， this is the first time I answered a question.
If my device has only an IP like "169.254.70.77", then the function of evutil_found_ifaddr could not filter  
the IP.  The function of evutil_check_interfaces gave me the result that my device has an IPv4 interface , but this is an invalid IP.
You said "an example" what I think just the two function . P.S. Excuse my poor English.

**Comment by azat** [comment]
Can you post output of the `ip a` (or something like this, if you have !linux)?

**Comment by azat** [comment]
And also output for (or analogs):
- `ip r g 18.244.0.188`
- `ip r g 2001:4860:b002::68`

**Comment by nianxuejie** [comment]
mac osX . when it was connected to an NAT64 hotspot (ipv6-only)

**Comment by nianxuejie** [comment]
************************ipv6-only************************

ipv6:::1
ipv6:fe80::1
ipv6:fe80::14eb:45f9:9b18:e160
ipv6:2001:2::aab1:1465:2620:d206:d109
ipv6:2001:2::aab1:d4c9:80ac:ade1:6f6e
ipv6:fe80::30e9:b7ff:fe3e:cba2
ipv6:fe80::b276:b10d:f766:d4a4
ipv6:fe80::eac4:6370:6b85:eb25
ipv6:fe80::14c2:efd4:7078:82d3
ipv4:127.0.0.1
ipv4:169.254.70.77

**Comment by nianxuejie** [comment]
The device only has ipv6 interface, actually.

**Comment by ploxiln** [comment]
169.254.0.0/16 is "link local" address https://en.wikipedia.org/wiki/Link-local_address#IPv4

It is reachable by other computers on the LAN. For ipv4, it is typically used as a fall-back if dhcp can't get an address. All ipv6 interfaces have a link-local address (fe80:...)

I guess it's arguable whether it's practically ever working or used in ipv4 networks, or whether some people could theoretically be using it to communicate on their LAN.
