### ISSUE TITLE
bufferevent_socket_connect, is there a timeout time setting for the interface

### ISSUE THREAD

**Issue by yanchuang12** [libevent/libevent#669]
bufferevent_socket_connect, is there a timeout time setting for the interface. sometimes I call the bufferevent_socket_connect , It will take a long time to return（success or not）.  I've been looking for a long time. I didn't find it. 
I want to set a timeout time for this interface. Is there a good way to do it. 
thanks all.

**Comment by azat** [comment]
Hm, can you share more details/reproducer?
Since a general there is connect() over non-blocking socket.

**Comment by yanchuang12** [comment]
now ,the bufferevent set the tcp socket non blocking， kernel set connect timeout is 75s. but the time is too long ,  I want connect timeout a smaller.  is there a interface to do this.
bufferevent_set_timeouts can set read/write timeout, I can use it？， only to connect

**Comment by azat** [comment]
I'm not sure that I do understand what you are asking for.

So if you are saying that `bufferevent_socket_connect()` can take too long, it sounds to me that this is either some very tricky. But I think that you meant that not the `bufferevent_socket_connect()` takes too long, but time to the first read/write, in this case regular read/write timeout will work just fine.

**Comment by yanchuang12** [comment]
thanks, I mean first read/write to the listen socket. it meaning new connection. I solve it
