### ISSUE TITLE
How to know a event_base_loop handled all events and hanged on dispatch

### ISSUE THREAD

**Issue by tanyifeng** [libevent/libevent#670]
Is there any way to detect whether event_base_loop handled all events and hanged on dispatch ?

I'm trying to let event_base_loop exit automatically when it totally finished a request, or check the finished status and call event_base_loopexit to cancel event_base_loop, I can not find an appropriate interface to detect the finished status in event.h.

Can I use event_base_get_num_events(thread->evbase, EVENT_BASE_COUNT_ADDED) to accomplish this, or can you give me some advice ?

**Comment by azat** [comment]
Since you closed nmathewson/Libevent#163, I guess you already realized
that you event_base_loop() will exit (indeed) from the loop once there
will be no more events (without EVLOOP_NO_EXIT_ON_EMPTY)?
All you should do is avoid EV_PERSIST or delete events from the base
once you process them.

**Comment by tanyifeng** [comment]
Great! Thanks very much.

**Comment by azat** [comment]
Closing for now, if you still have questions, fill free to reopen.
