### ISSUE TITLE
BEV_EVENT_EOF represent read zero or write zero, is there other condition

### ISSUE THREAD

**Issue by yanchuang12** [libevent/libevent#675]
The client requests data from nginx, such as requesting 100M data, but nginx returns 50M data, and then 
The client triggered event（BEV_EVENT_EOF）， this is not normal.
the network is good, is there a bug in libevent? I hope not. 

can you tell me the condition of libevent trigger event BEV_EVENT_EOF

**Comment by ploxiln** [comment]
In this case EOF was probably caused by the connection being closed, possibly because of a timeout on the nginx side: http://nginx.org/en/docs/http/ngx_http_core_module.html#send_timeout

**Comment by yanchuang12** [comment]
yes , I think the same with you , but I need to test to confirm it , thanks all
