### ISSUE TITLE
Need inotify() support

### ISSUE THREAD

**Issue by pprindeville** [libevent/libevent#676]
Sometimes work comes in the form of network connections, and sometimes in the form of work files in a work queue directory.  `inotify()` provides a straightforward means to detect files being created in a work queue directory.

Obviously, this would be Linux specific.

But it could be named more generically so that if other OSes provided a similar mechanism in the future, that could be added on as well.

**Comment by azat** [comment]
I do not really sure what was meant by this by @pprindeville, but you
can monitor descriptor that is returnd by inotify_init() using epoll and
hence libevent.

As for API that would allow somethink like this:
  bufferevent_socket_connect_path("/path/to/unix-sockets")

is:
- too specific (name me such *general* use cases)
- doing too much work (it's like if cat(1) will know how to sort(1)
  files)
- hence a lot of things can go wrong there
- should be 100% user-specific code (if any)

**Comment by azat** [comment]
I'm closing this for now (since I don't see this as API in libevent, plus I'm trying to clean the issues), but if you want to discuss this, please share your thoughts!
