### ISSUE TITLE
evbuffer_read() null at 200ms 1G LAN connection

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#682]
hi,
I am facing this issue infrequently ,when I am running 4 clients with payload nearly 64bytes.The payload comes from each socket at 200ms duration.Before the read callabck of the socket is fired,am getting a segfault from evbuffer_read() present in bufferevent_sock.c.Sorry I couldn't reproduce the stack trace,since its occuring like once.
Thanks,
Kushal

**Comment by azat** [comment]
> bufferevent_sock.c.Sorry I couldn't reproduce the stack trace,since its occuring like once

Then sorry, I don't think that somebody can help you with this, except for basic advice like:
- look through your code
- if you program has multiple threads, then use appropriate libevent's API (evthread_use_pthreads()/BEV_OPT_THREADSAFE/evbuffer_enable_locking())
- run under valgrind (memcheck/drd/helgrind)
- sanitizers (asan/tsan)

Or write some stress test to reproduce it and come back with the core dump or at least stacktrace.

**Comment by kushal4** [comment]
Sorry,Please give me some time to reproduce this situation since it occurs once in a while as soon i get this situtation again,I will print the stracktrace here

**Comment by kushal4** [comment]
I need some suggestions here,I am getting it from my read callback which is running in the main thread but am spwning multiple  threads after the data has been read from the buffer in the read callback

**Comment by azat** [comment]
So what is the order? Do you get SIGSEGV before creating that "multiple threads"? If so it will be far more easier to find (fro my POV)

Anyway suggestions are always the [same](https://github.com/libevent/libevent/issues/682#issuecomment-412785272)

I think you will find a lot of interesting things if you run your program under `valgrind` with `drd`/`helgrind` tool or (and I would prefer this one personally) recompile your program with `-fsanitize=thread` and run it
