### ISSUE TITLE
Issue with 2.1.8 stable, data transfer hang / very high latency

### ISSUE THREAD

**Issue by nicboul** [libevent/libevent#687]
Hi,

I've been using 2.0.22 without any problem. I started to use 2.1.8 and my data transfer just hang after a while. I bisected the commits and found the problematic commit is this one: 

commit da52933550fd4736aa1c213b6de497e2ffc31e34 (HEAD)
Author: Azat Khuzhin <a3at.mail@gmail.com>
Date:   Fri Nov 13 16:00:39 2015 +0300

I can clearly reproduce the bug with this exact commit, if I checkout the commit before, everything is fine. I don't have a piece of code to show the exact problem, my setup is rather complex, but if you fix it I can easily try your patch.

Cheers,
Nick

**Comment by azat** [comment]
Hi Nick!

Can you describe this a little bit?

- Are you using BEV_OPT_DEFER_CALLBACKS?
- Are you using watermarks?
- If you just revert this commit only (not checkout up to
  da52933550fd4736aa1c213b6de497e2ffc31e34^), does it hang?
- How you data transfer looks like? You are using both:
  BUFFEREVENT_SSL_CONNECTING (for client) and BUFFEREVENT_SSL_ACCEPTING
  (for server)?

**Comment by nicboul** [comment]
Hi, Thank you for your reply.
Meanwhile I've continued to modify the code in my software, and now I just can't reproduce it anymore. I tried to  go back in my commits to simulate it again without any luck. I think I will just close it and if I manage to reproduce it again, I will open a more detailed ticket.

Thanks,
Nick
