### ISSUE TITLE
There a memory leaks problem on windows with libevent2.1.8-stable version

### ISSUE THREAD

**Issue by public-rtos** [libevent/libevent#688]
Hi, 
I download the libevent-2.1.8-stable version, and complie it by nmake VC9 on windows, and then got the libevent.lib, libevent_core.lib and libevent_extras.lib.
Then I create a vs2008 win32 console project and add the libevent lib file use the http server and TCP server function, all the function are works very well, there nothing wrong happened.
I have got following memory leaks when I add following code and after I stop debug function at vs2008 IDE:
#define _CRTDBG_MAP_ALLOC 
#include <crtdbg.h>
...
int main( int argc, char**argv )
{
_CrtSetDbgFlag ( _CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF ); 
...
evthread_use_windows_threads();
base = event_base_new();
...
...
event_base_dispatch(base);
...
}
Detected memory leaks!
Dumping objects ->
{258} normal block at 0x003929F0, 28 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 
{257} normal block at 0x003929F0, 28 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 
{256} normal block at 0x003929F0, 28 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 
{255} normal block at 0x003929F0, 28 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 
Object dump complete.
and when I comment the evthread_use_windows_threads() function the memory leaks problem no happened.

I belive there a must a bug with evthread_use_windows_threads() function, maybe there need a another function to free something resource.
I am sorry I have poor English and I don't confirm if I correctly expressed what I mean, but I hope to slove this problem.

B&RGDS
Bill Liu
Canton, China

**Comment by azat** [comment]
@public-rtos any news?
