### ISSUE TITLE
bufferevent_ssl's get stuck when handlers read <= 1024 bytes

### ISSUE THREAD

**Issue by nacl** [libevent/libevent#690]
Hello!

I'm encountering some strange behavior when using libevent's OpenSSL integration.

`bufferevent`'s created using `bufferevent_openssl_socket_new()` get stuck on
high read watermarks when we read 1024 bytes or less off the underlying `struct
evbuffer` in a single read event call.  If the amount read is greater than 1024
bytes, the watermark operates correctly and the `bufferevent` never gets stuck.

By "stuck", I mean that the `bufferevent` for the event in question stops firing.

This does not occur if we use `bufferevent_openssl_filter_new()` on top of a
normal `bufferevent`, or do not use the OpenSSL integration at all.

An example can be found [here](https://gist.github.com/nacl/cfcc35714c33b31e5a129f5e6500c577), which is based on the TLS echoserver example in the libevent
book.  I have tested this on Ubuntu 16.04, amd64 platform, against libevent
version 2.0.21 and 2.1.8, and the latest in master, and it can be reproduced in
all of them.

The problem can be reproduced by running the attached program with no arguments,
then connecting to it with `openssl s_client` in a way that will make it hit the
watermark, e.g:

```
openssl s_client -connect localhost:9999 < /dev/zero > /dev/null
```

The program briefly shows spikes in CPU and bandwidth usage upon new connections
in this case before they both go to sleep.

**Comment by azat** [comment]
Hi!

Thanks for an example!

This happens because openssl bufferevent layer can read more then it
should (IOW it can read slightly more then the current watermark
allows), and later read will be suspended because:
  size >= bufev->wm_read.high

And hence you read callback will never be called again.

This can be trivially fixed. I will get back once the patch will be
ready.

**Comment by azat** [comment]
@nacl could you verify that issue is gone after recompiling libevent from master?
