### ISSUE TITLE
expose evhttp read/write timeout API

### ISSUE THREAD

**Issue by ochinchina** [libevent/libevent#692]
evhttp expose API evhttp_connection_set_timeout() to set timeout for socket connection phase and does not expose API to set the read & write timeout (currently hard code to HTTP_READ_TIMEOUT/HTTP_WRITE_TIMEOUT).

If possible to expose two APIs like: evhttp_read_set_timeout() and evhttp_write_set_timeout() to set the READ&WRITE timeout?

**Comment by azat** [comment]
Hm, with non-zero timeout passed to evhttp_connection_set_timeout_tv()
it will install read/write timeout for bufferevent (via
bufferevent_set_timeouts()).

It will use HTTP_READ_TIMEOUT/HTTP_WRITE_TIMEOUT only if you passes zero
timeout.

**Comment by ochinchina** [comment]
@azat pass non-zero timeout to evhttp_connection_set_timeout_tv() will set the timeout for connect, read & write operations. I want to set different timeout for the connect, read & write operation. For example, set 2 seconds timeout for connect, and set 20 seconds for read operation, and set 10 seconds for write operation.

**Comment by azat** [comment]
On Mon, Oct 01, 2018 at 01:18:38AM -0700, Steven Ou wrote:
> @azat pass non-zero timeout to evhttp_connection_set_timeout_tv() will set the timeout for connect, read & write operations.

Yep. Do you have time to contribute this?

Also please note that in *general* such timeouts is not what regular
client to install. Suppose you install read timeout to 10 seconds.  And
if server will respond every 9.9(9) seconds one byte at a time then you
will still read each byte every 9.9(9) second (up until
evhttp_set_max_headers_size()/evhttp_set_max_body_size()).
That said that in general timeout that is more common is timeout for all
reads not for one particular.

But this is in general only, maybe just timeout for one read will be
enough for your needs.

**Comment by azat** [comment]
@ochinchina do you still interested in this timeouts?

**Comment by ochinchina** [comment]
@azat Yes, I'm still interested in this timeout

**Comment by azat** [comment]
@ochinchina implemented in upstream, take a look (if it not too late)
