### ISSUE TITLE
How to limit bufferevent's input/output buffer memory footprint?

### ISSUE THREAD

**Issue by zfl9** [libevent/libevent#694]
I am writing the http-tunnel proxy program (using bufferevent). Because the http-tunnel proxy needs to manage a pair of TCP connections at the same time (`client <-> proxy`, `proxy <-> server`), when one of the connections has data readable, the corresponding read callback will write the data to the other connection. 

The pseudo code looks like this:
```c
void forward_data_cbfunc(bev, arg) {
    bufferevent_write(arg->bev, bufferevent_get_input(bev));
}
```

He works very well, but I am having a tricky problem now, because the network speed of the `client <-> proxy` is much slower than the `proxy <-> server`, which causes the client's bufferevent's output buffer size to grow unlimitedly. (This is especially noticeable when downloading large files, basically occupying 300~500M of memory)

But after looking at the libevent book, I still haven't found a suitable way to limit bufferevent's input/output buffer memory usage.

So, if you can help me solve this problem, I would be grateful. Thank you! ~

**Comment by zfl9** [comment]
For example, I want to limit the input buffer size between `proxy <-> servers` to 1M, and the output buffer size between `client <-> proxy` is also 1M. What should I do? Thank you

**Comment by zfl9** [comment]
I actually tested it. The `client <-> proxy` only has a download speed of `7MB/s`, but the `proxy <-> server` has a download speed of `30MB/s`. The speed of the two is inconsistent and the `client <-> proxy` connected output buffer swells instantly and quickly runs out of memory, causing the proxy to be killed by the system.

**Comment by azat** [comment]
On Wed, Sep 26, 2018 at 08:52:07PM -0700, zfl9 wrote:
> But after looking at the libevent book, I still haven't found a suitable way to limit bufferevent's input/output buffer memory usage.

Take a look at bufferevent_setwatermark().

**Comment by zfl9** [comment]
I noticed setwatermark(), but it doesn't seem to work? Because the data is written from the server end and immediately written to the client side, so I should think, how to limit the size of the output buffer of the client side?

**Comment by zfl9** [comment]
How do I use setwatermark() correctly, it seems that I can only limit the size of the input buffer (read high water mark), thank you!

**Comment by azat** [comment]
> How do I use setwatermark() correctly, it seems that I can only limit the size of the input buffer (read high water mark), thank you!

Indeed (at least without bufferevent filter, filters handles write
watermarks too).

But even read high watermark is enough for your needs if you will move
transfering of you data out from readcb to writecb. I've modified the
le-proxy.c for your (and installs watermark to 1 byte) and it transfers
one byte at a time (you can verify this with `strace -ereadv,writev`):

  https://gist.github.com/azat/e41af4d8b9b063b4ddd6a439ce5f66a3

Albeit this requires triggering events manually, so I guess that the
first option is preferable (but I don't know too much about your
protocol, hence it's up to you to decide).

**Comment by zfl9** [comment]
Thank you for your patience, I will take a closer look at the two solutions you gave me!

**Comment by zfl9** [comment]
Thank you, use method one to solve the problem successfully, thank you very much!
