### ISSUE TITLE
evhttp_send_reply in subthread.

### ISSUE THREAD

**Issue by 404517981** [libevent/libevent#695]
Accept http request on main thread,then put this task  to job thread.When job is finished,The task is move to send-thread(call "evhttp_send_reply" associate to libevent resource)."evhttp_send_reply" doesn't work.Only next request coming,  evhttp_send_reply can send msg to client in this timepoint.

**Comment by azat** [comment]
On Sat, Sep 29, 2018 at 05:35:44AM -0700, Eazism wrote:
>    Accept http request on main thread,then put this task  to job thread.When job is finished,The task is move to send-thread(call "evhttp_send_reply" associate to libevent resource)."evhttp_send_reply" doesn't work.Only next request coming,  evhttp_send_reply can send msg to client in this timepoint.

I'm not quite undestand you. Can you provide source code?

Also please verify that you:
- enable threading for libevent (for pthreads you need
  evthread_use_pthreads())
- bufferevent (that is in http) uses BEV_OPT_THREADSAFE (you can
  manually create bufferevent via evhttp_set_bevcb())
- next patches presented in your libevent version:
  306747e51c1f0de679a3b165b9429418c89f8d6a ("Fix crashing http server when callback do not reply in place from *gencb*")
  5ff8eb26371c4dc56f384b2de35bea2d87814779 ("Fix crashing http server when callback do not reply in place")

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by 404517981** [comment]
follow your recommand.call evthread_use_xxx，It work now! Thx

**Comment by azat** [comment]
On Sun, Sep 30, 2018 at 08:09:57AM -0700, Eazism wrote:
> follow your recommand.call evthread_use_xxx，It work now! Thx

Please note that you have to update libevent if you do not have patches
that has been referenced in the previous commit.
