### ISSUE TITLE
How do I specify the path to the openssl library?

### ISSUE THREAD

**Issue by zfl9** [libevent/libevent#696]
I don't want to use the openssl library installed by the package manager, so how do I specify the path to the openssl library when I use `./configure`? For example `--with-openssl=/opt/openssl-1.1.0` (actually it doesn't work)?

**Comment by azat** [comment]
- autotools can use pkg-config, and/or you can/should export LDFLAGS/CFLAGS
  (https://github.com/libevent/libevent/blob/master/Vagrantfile#L259-L261)

- cmake has OPENSSL_ROOT_DIR option (i.e. cmake
-DOPENSSL_ROOT_DIR=/opt/openssl)

**Comment by zfl9** [comment]
Well, thanks for the answer, use CFLAGS, LDFLAGS to work properly.
