### ISSUE TITLE
libevent won't build in a subdir

### ISSUE THREAD

**Issue by hstenn** [libevent/libevent#697]
Libevent 2.1.8-stable does not build in a subdir because it's missing $(srcdir)/ in front of the test/test.sh calls.  This problem would have been found if the package was built using 'make distcheck'.

**Comment by azat** [comment]
It is fixed in cf7f5b0dc484152ae3be7ea6ba57552595891608, but there is no release that contains this patch.
And you right that there should be (and not only because of this patch, there are a lot of fixes for 2.1.8), I was going to make a release with fixes in the nearest feature.

**Comment by hstenn** [comment]
Thanks very much, Azat!

**Comment by azat** [comment]
2.1.9-beta released in 9c75c24caa7689c010864579e27b159665c8dd63, closing
