### ISSUE TITLE
Correct handling for DNS replies with no data.

### ISSUE THREAD

**Issue by nmathewson** [libevent/libevent#70]
"libevent can't properly detect dns replys with no data.
                 evdns.c,reply_parse:1006,reply_parse(). datalength (RDLENGTH).
                 have_answer defined as true for any data with zeroed RDLENGTHs"

(Reported by skruffy in IRC)

**Comment by ellzey** [comment]
Still an issue? 

- [ ] yes
- [ ] no

Should we wait until I finish libldns integration before any more heavy lifting in the dns part of town?

- [x] yes (Mark's vote)
- [ ] no

**Comment by NathanFrench** [comment]
After careful review of this specific report, it's hard to say *exactly* what was being spoken of. 

`NODATA` is set when an authoritative server responds to a request that exists, but under a different type. (I.e., a lookup of `IN A ipv6.example.com.`, where the `dname` `ipv6.example.com.` *exists*, but is not of type `A`. RFC states that there is a clear delineation between the two values NX and NODATA for cache reasons.

We would need a more clear example to actually complete this. I suggest we close for now.
