### ISSUE TITLE
sample/le-proxy.c:33:10: fatal error: 'openssl/ssl.h' file not found on mojave

### ISSUE THREAD

**Issue by ronnie8778** [libevent/libevent#700]
Hi I have problem while installing libevent on Mac Mojave.

/Library/Developer/CommandLineTools/usr/bin/make  all-am
  CC       sample/le-proxy.o
sample/le-proxy.c:33:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sample/le-proxy.o] Error 1
make: *** [all] Error 2

**Comment by azat** [comment]
There is some problem with locating headers for openssl, though it looks
like there is no problem for openssl libs.
There are similar issues opened here, take a look through them, and if you
will not be able to resolve this, get back with full build log (uploaded
somewhere).

**Comment by ronnie8778** [comment]
Hi Azat, where should I get the build log?

**Comment by azat** [comment]
Well, it depends on how did you built it.
Usually just redirect all output of the make/cmake/autogen.sh/configure to
the file.

>

**Comment by ronnie8778** [comment]
Hi Azat, 

When I run configure I got the following:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-apple-darwin18.0.0
checking host system type... x86_64-apple-darwin18.0.0
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking whether gcc needs -traditional... no
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin18.0.0 file names to x86_64-apple-darwin18.0.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin18.0.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for library containing inet_ntoa... none required
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking for library containing clock_gettime... none required
checking for clock_gettime... yes
checking for library containing sendfile... none required
checking for WIN32... no
checking for CYGWIN... no
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for library containing inflateEnd... -lz
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /opt/local/bin/pkg-config
checking if pkg-config is at least version 0.15.0... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking ifaddrs.h usability... yes
checking ifaddrs.h presence... yes
checking for ifaddrs.h... yes
checking mach/mach_time.h usability... yes
checking mach/mach_time.h presence... yes
checking for mach/mach_time.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/in6.h usability... no
checking netinet/in6.h presence... no
checking for netinet/in6.h... no
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking port.h usability... no
checking port.h presence... no
checking for port.h... no
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking sys/devpoll.h usability... no
checking sys/devpoll.h presence... no
checking for sys/devpoll.h... no
checking sys/epoll.h usability... no
checking sys/epoll.h presence... no
checking for sys/epoll.h... no
checking sys/event.h usability... yes
checking sys/event.h presence... yes
checking for sys/event.h... yes
checking sys/eventfd.h usability... no
checking sys/eventfd.h presence... no
checking for sys/eventfd.h... no
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/queue.h usability... yes
checking sys/queue.h presence... yes
checking for sys/queue.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/sendfile.h usability... no
checking sys/sendfile.h presence... no
checking for sys/sendfile.h... no
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/timerfd.h usability... no
checking sys/timerfd.h presence... no
checking for sys/timerfd.h... no
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking for sys/sysctl.h... yes
checking for TAILQ_FOREACH in sys/queue.h... yes
checking for timeradd in sys/time.h... yes
checking for timercmp in sys/time.h... yes
checking for timerclear in sys/time.h... yes
checking for timerisset in sys/time.h... yes
checking whether CTL_KERN is declared... yes
checking whether KERN_RANDOM is declared... no
checking whether RANDOM_UUID is declared... no
checking whether KERN_ARND is declared... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether time.h and sys/time.h may both be included... yes
checking for accept4... no
checking for arc4random... yes
checking for arc4random_buf... yes
checking for eventfd... no
checking for epoll_create1... no
checking for fcntl... yes
checking for getegid... yes
checking for geteuid... yes
checking for getifaddrs... yes
checking for getnameinfo... yes
checking for getprotobynumber... yes
checking for gettimeofday... yes
checking for inet_ntop... yes
checking for inet_pton... yes
checking for issetugid... yes
checking for mach_absolute_time... yes
checking for mmap... yes
checking for nanosleep... yes
checking for pipe... yes
checking for pipe2... no
checking for putenv... yes
checking for sendfile... yes
checking for setenv... yes
checking for setrlimit... yes
checking for sigaction... yes
checking for signal... yes
checking for splice... no
checking for strlcpy... yes
checking for strsep... yes
checking for strtok_r... yes
checking for strtoll... yes
checking for sysctl... yes
checking for timerfd_create... no
checking for umask... yes
checking for unsetenv... yes
checking for usleep... yes
checking for vasprintf... yes
checking for getservbyname... yes
checking for getaddrinfo... yes
checking for F_SETFD in fcntl.h... yes
checking for select... yes
checking for poll... yes
checking for kqueue... yes
checking for working kqueue... yes
checking for epoll_ctl... no
checking waitpid support WNOWAIT... no
checking for port_create... no
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint64_t... yes
checking for uint32_t... yes
checking for uint16_t... yes
checking for uint8_t... yes
checking for uintptr_t... yes
checking for fd_mask... yes
checking size of long long... 8
checking size of long... 8
checking size of int... 4
checking size of short... 2
checking size of size_t... 8
checking size of void *... 8
checking size of off_t... 8
checking for struct in6_addr... yes
checking for struct sockaddr_in6... yes
checking for sa_family_t... yes
checking for struct addrinfo... yes
checking for struct sockaddr_storage... yes
checking for struct in6_addr.s6_addr32... no
checking for struct in6_addr.s6_addr16... no
checking for struct sockaddr_in.sin_len... yes
checking for struct sockaddr_in6.sin6_len... yes
checking for struct sockaddr_storage.ss_family... yes
checking for struct sockaddr_storage.__ss_family... no
checking for struct so_linger... no
checking for socklen_t... yes
checking whether our compiler supports __func__... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking size of pthread_t... 8
checking for library containing ERR_remove_thread_state... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating libevent.pc
config.status: creating libevent_openssl.pc
config.status: creating libevent_pthreads.pc
config.status: creating libevent_core.pc
config.status: creating libevent_extra.pc
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: creating evconfig-private.h
config.status: evconfig-private.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

And when I run make command, I got the following:
/Library/Developer/CommandLineTools/usr/bin/make  all-am
  CC       sample/le-proxy.o
sample/le-proxy.c:33:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [sample/le-proxy.o] Error 1
make: *** [all] Error 2

I check the issue was fixed for Sierra MAC OS with the latest version of libevent, not sure about this for Mojave.

**Comment by azat** [comment]
On Sun, Oct 21, 2018 at 07:22:56PM -0700, ronnie8778 wrote:
> Hi Azat, 
> 
> When I run configure I got the following:

This is not the first time you run it, hence some variables got cached
and no check had been performed, so no messages for them.

P.S. please use markdown for such long posting, since this makes the
issue unreadable.

> And when I run make command, I got the following:
> /Library/Developer/CommandLineTools/usr/bin/make  all-am
>   CC       sample/le-proxy.o
> sample/le-proxy.c:33:10: fatal error: 'openssl/ssl.h' file not found
> #include <openssl/ssl.h>
>          ^~~~~~~~~~~~~~~
> 1 error generated.
> make[1]: *** [sample/le-proxy.o] Error 1
> make: *** [all] Error 2

Are you using brew/ports?
Maybe you missed "brew link"?

It looks like you just using libssl.so/libcrypto.so that is shipped with
osx, does it provide any headers?

I guess that the problem here is you do not have any pkg-config or
pkg-config for openssl, hence next commands do not report anything or
"command not found"
  pkg-config --libs openssl
  pkg-config --flags openssl
And since our m4/libevent_openssl.m4 depends on pkg-config we cannot
find headers, while we do find libraries, since we use AC_SEARCH_LIBS()
but not AC_CHECK_HEADER(), but we should add it with predefined include
paths.

Do you know where openssl/ssl.h is located on your system?
Can you find it and post the output (i.e. "find / -path */openssl/ssl.h")?

Maybe next one?
  /Library/Developer/CommandLineTools/usr/include/openssl/ssl.h

If so you can do something like this get it work:
  CFLAGS=-I/Library/Developer/CommandLineTools/usr/include make -j

> I check the issue was fixed for Sierra MAC OS with the latest version of libevent, not sure about this for Mojave.

And strictly speaking this is not the libevent issue, but the
environment in which you built it.

**Comment by ronnie8778** [comment]
Hi Azat,

Thanks for reminding to use markdown.

1. I am using brew. Do I need to use brew link to link to the openssl folder?

1. When I run 
`$pkg-config --libs openssl`
it shows the following
`$-L/opt/local/lib -lssl -lcrypto
`
`$pkg-config --flags openssl`
it gave me the following result
`$Unknown option --flags`

1. When I run find **_/ -path */openssl/ssl.h,_** I got the following, 
```
/opt/vagrant/embedded/include/openssl/ssl.h
/opt/local/include/openssl/ssl.h
```

4. I didn't see anything inside `/Library/Developer/CommandLineTools/usr/include/`, there is no ssl folder there

**Comment by ronnie8778** [comment]
Hi Azat,

Now I rerun 
`pkg-config --cflags openssl`
it shows me the following, there isn't `openssl/ssl.h `though
`-I/opt/local/include`

I run` make CFLAGS=-I/opt/local/include` it seems fine, I run `sudo make install ` there was no error as well.

**Comment by azat** [comment]
On Mon, Oct 22, 2018 at 09:53:12PM -0700, ronnie8778 wrote:
> Hi Azat,
> 
> Now I rerun 
> `pkg-config --cflags openssl`
> it shows me the following, there isn't `openssl/ssl.h `though
> `-I/opt/local/include`

So you got the following?
  $ pkg-config --cflags openssl
  -I/opt/local/include
(you mixed your thoughts with the output of the pkg-config I guess)

If this is correct then I don't understand why autoconf did not find it
since it uses this command. Did you run ./configure with pkg-config
available in PATH? Can you post output of
  "pkg-config --atleast-pkgconfig-version 0.15.0"

> I run` make CFLAGS=-I/opt/local/include` it seems fine, I run `sudo make install ` there was no error as well.

That is good news, even though I do not understand the root cause of the
problem (at first I though that we do not have enough list of default
include dirs for openssl).

**Comment by ploxiln** [comment]
By the way, "/opt/local" is not where homebrew puts stuff. That must be from something else. Also, homebrew does not put the pkgconfig files for openssl in a place where they are automatically found. To use the homebrew openssl, you need to set `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` e.g.

```
$ PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig pkg-config --cflags openssl
-I/usr/local/Cellar/openssl/1.0.2p/include
```

macOS includes an inappropriately old version of openssl libraries, for binary compatibility with old software, and this has been the case for many years now, since at least OS X 10.8:

```
$ ls -l /usr/lib/libssl*
-rwxr-xr-x  1 root  wheel  392912 Jul  4 05:07 /usr/lib/libssl.0.9.7.dylib
-rwxr-xr-x  1 root  wheel  630144 Jul  4 05:06 /usr/lib/libssl.0.9.8.dylib
-rw-r--r--  1 root  wheel  947104 Jul  4 05:06 /usr/lib/libssl.35.dylib
-rw-r--r--  1 root  wheel  890800 Jul  4 05:07 /usr/lib/libssl.43.dylib
lrwxr-xr-x  1 root  wheel      15 Sep 25 01:31 /usr/lib/libssl.dylib -> libssl.35.dylib
```

Vagrant includes its own build of ruby, with its own vendored dependencies, including openssl. You don't want to try to link against that.

If on macOS , if you don't already know exactly what you're doing, you probably want to use the homebrew-install openssl and you want to use it via `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig`
