### ISSUE TITLE
add openssl1.1 into travis-ci matrix

### ISSUE THREAD

**Issue by azat** [libevent/libevent#705]

**Comment by azat** [comment]
It is not that easy right now, due to some internal issues in travis-ci (old ubuntu, and enable to update dpkg without sudo)

**Comment by ygj6** [comment]
I found that the default version of openssl in Ubuntu 18.04 (Bionic Beaver) is 1.1.1, and travis can now run projects on it.
https://github.com/ygj6/libevent/commit/ad9edb49bb15fb725cc6ba0391900a0957ede08c

**Comment by azat** [comment]
@ygj6 indeed, applied thanks!
