### ISSUE TITLE
make https request failed with bufferevent_openssl_socket_new function 

### ISSUE THREAD

**Issue by suohd** [libevent/libevent#706]
# Environment description
1. My version of  libevent is 2.0.21 .
2. epollops is epoll.
3. Run a client program on operating system centos6.2.
4. Network topology is as flow:

  PC1(Client)----------------->Router2-----X-->
    |----------------------------->Router1--------|------------->HTTPS SERVER

  _the client program randomly selects a route to communicate with the HTTPS server, but the client cann't reach the HTTPS server through the Router2 _
# Description of my problem phenomena

1. My client program accesses an HTTPS service.
2. The request can only be made three shakes of TCP, But the client does not send the SSL negotiation package until the connection is disconnected. 
3. I found that whenever the FD of the socket created was 14, the request could only complete three TCP handshake interactions, and the client would no longer send SSL negotiation messages.
4.  show the base - > IO content is  as follows: 
```
p base->io
$1 = {entries = 0x7f2a7ac4e8c8, nentries = 32}
(gdb) p $1->entries
$2 = (void **) 0x7f2a7ac4e8c8
(gdb) p (struct evmap_io **)$2
$3 = (struct evmap_io **) 0x7f2a7ac4e8c8
(gdb) p $3[14]
$4 = (struct evmap_io *) 0x7f2a772d7898
(gdb) p $3[14][0]
$5 = {events = {tqh_first = 0x7f2a7ac17b98, tqh_last = 0x7f2a7ac17c60}, nread = 1, nwrite = 1}
(gdb) p $3[14][0].events.tqh_first
$6 = (struct event *) 0x7f2a7ac17b98
(gdb) p $3[14][0].events.tqh_first[0]
$7 = {ev_active_next = {tqe_next = 0x0, tqe_prev = 0x7f2a7ac471f8}, ev_next = {tqe_next = 0x7f2a7ac16c98, tqe_prev = 0x7f2a7ac17c30}, ev_timeout_pos = {ev_next_with_common_timeout = {tqe_next = 0xffffffff, tqe_prev = 0x0}, min_heap_idx = -1}, ev_fd = 14, ev_base = 0x7f2a7acfc008, _ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f2a7ac17c60}, ev_timeout = {tv_sec = 60, tv_usec = 0}}, ev_signal = {ev_signal_next = {tqe_next = 0x0, tqe_prev = 0x7f2a7ac17c60}, ev_ncalls = 60, ev_pncalls = 0x0}}, ev_events = 18, ev_res = 1, ev_flags = 0, ev_pri = 3 '\003', ev_closure = 2 '\002', ev_timeout = {tv_sec = 278972, tv_usec = 530810}, ev_callback = 0x7f2a85932a60 <be_openssl_handshakeeventcb>, ev_arg = 0x7f2a7ac17b88}
```

6. I found the following questions:

- The values of both variables nread  and nwrite  are 1 in '$3[**14**][0]', but there is only one read event member in the linked list in '$3[14][0].events.tqh_first[0]', as shown below:
`_ev = {ev_io = {ev_io_next = {tqe_next = 0x0, tqe_prev = 0x7f2a7ac17c60}`

- Ev_flags = 0, why does this happen? 

# I did the following test:

1. Modify the contents of the variable '$3[14][0]' through GDB, as follows:
> (gdb) p $3[14][0]
> $5 = {events = {tqh_first = 0x7f2a7ac17b98, tqh_last = 0x7f2a7ac17c60}, nread = 1, nwrite = 1}

> set $5->nread = 0
> set $5->nwirte = 0
> set $5->events.tqh_first  = 0
> set  $5->events.tqh_last = &$5->events.tqh_first

> (gdb) p $3[14][0]
> $5 = {events = {tqh_first = 0x, tqh_last = 0x7f2a7ac17XXXXX}, nread = 0, nwrite = 0}

2. Successfully resending HTTPS requests. 

#  The main process of this client program is as follows:

> struct evhttp_connection *evcon = NULL;
> static SSL_CTX *__cld_ssl_ctx__ = NULL;
> SSL *ssl;
> SSL_SESSION* sess;
> struct bufferevent *bev;
> __cld_ssl_ctx__ = SSL_CTX_new(SSLv23_method());
> ssl = SSL_new(__cld_ssl_ctx__);
> bev = bufferevent_openssl_socket_new(ev_base, -1, ssl,
> 				BUFFEREVENT_SSL_CONNECTING,
> 				BEV_OPT_CLOSE_ON_FREE|BEV_OPT_DEFER_CALLBACKS);
> 				
> evcon = evhttp_connection_base_bufferevent_new(ev_base, dns_base,
> 				bev, address, port);
> 				
> req = evhttp_request_new(request_cb, (void*)((__u64)s->index));
> 
> evhttp_make_request(...)
>

**Comment by azat** [comment]
Hi!

> my client program accesses an HTTPS service

So you have openssl client (`BUFFEREVENT_SSL_CONNECTING`)

> and the newly created socket FD is 14

So you are state that for libevent fd 14 is special?

> Ev_flags = 0, why does this happen?

I would say that somebody called [`event_assign()`](http://www.wangafu.net/~nickm/libevent-2.0/doxygen/html/event_8h.html#afade5e4859dee5b85d502e5594a05cf0) for the event in active/pending state (not you I guess, since this is internal bufferevent for the libevent openssl), and this could and will corrupt internal structures.

> My libevent version is 2.0.11.

It is too damn old, can you upgrade to the 2.1.8? (in 2.1 there was a lot of changes to bufferevent openssl)
Well I would suggest you give the master a try (since there was some openssl fixes since 2.1.8)
If this not an option (even though I would strongly recommend you to use 2.1 over 2.0, since later is kind of EOL), could you try last 2.0.22?


P.S. please use `markdown`

**Comment by suohd** [comment]
Thank you very much for your reply. In my test environment, the probability of this problem is relatively high. At present, I can not change the libevent version, I can only try to avoid it.

**Comment by azat** [comment]
>  I can only try to avoid it.

Are you planing to share some details with us, or I can simply close this?

**Comment by ploxiln** [comment]
If you can't change libevent version, you would not be able to use a fix implemented in libevent anyway ...

**Comment by azat** [comment]
Indeed, reopen once you will have some details or/and ready to test some debug patches.
