### ISSUE TITLE
Which version of libevent do you use?

### ISSUE THREAD

**Issue by azat** [libevent/libevent#707]
[![](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/1.4.x)](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/1.4.x/vote)
[![](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/2.0.x)](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/2.0.x/vote)
[![](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/2.1.x)](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/2.1.x/vote)
[![](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/upstream)](https://api.gh-polls.com/poll/01CTPESEWDXR9FPX69BK409GE0/upstream/vote)

**Comment by sclei** [comment]
2.1.10

**Comment by azat** [comment]
This poll is not available anymore. Closing (since you cannot see results).
