### ISSUE TITLE
BUG: evhttp can not callback with Windows and IOCP

### ISSUE THREAD

**Issue by redfox1999** [libevent/libevent#709]
BUG: evhttp can not callback with Windows and IOCP

CAN NOT callback
```

void http_req_gencb(struct evhttp_request* req, void* arg) {

	struct evbuffer* buf = evbuffer_new();
	evbuffer_add_printf(buf, "<H1>Hello world!</H1>");
	evhttp_send_reply(req, HTTP_OK, "OK", buf);
	evbuffer_free(buf);
}

int main()
{
	WSADATA wsdata = {};
	WSAStartup(0x0202, &wsdata);

	evthread_use_windows_threads();
	struct event_config* cfg = event_config_new();
	event_config_set_flag(cfg, EVENT_BASE_FLAG_STARTUP_IOCP);
	event_config_set_num_cpus_hint(cfg, 8);
	struct event_base* base = event_base_new_with_config(cfg);
	event_config_free(cfg);
	
	struct evhttp* http = evhttp_new(base);
	evhttp_bind_socket(http, "0.0.0.0", 8001);
	evhttp_set_gencb(http, http_req_gencb, http);

	event_base_dispatch(base);

	event_base_free(base);

	WSACleanup();
    return 0;
}
```

**Comment by azat** [comment]
@redfox1999 hi, thanks for the report!
Can you do a bisect?

**Comment by azat** [comment]
I looked into this again, and I found the problem (listener), but other issues appear, will get back as soon as they will be fixed.

**Comment by azat** [comment]
So long story short, can you please test libevent from the following [repo](https://github.com/azat/libevent/pull/new/http-iocp-fixes)?
```
  https://github.com/azat/libevent http-iocp-fixes
```

(for you to fetch up to 29f90e2f)

**Comment by azat** [comment]
It is not applied to the upstream yet, I will close the issue once it will be rebased/merged.
Thanks for testing!

**Comment by azat** [comment]
Rebased and merged, could you again verify libevent from upstream?

And please note that previous patch set was incomplete, since **at least** next patches was missing:
- 2bf673a467ad412771419ea131cf2b3a9da740eb
- 908e710d40fb30cc68b515cce435a026c7ecc62a
