### ISSUE TITLE
Loop duration and wakeup delay statistics

### ISSUE THREAD

**Issue by htuch** [libevent/libevent#710]
We (Envoy; https://github.com/envoyproxy/envoy) would like to start collecting histograms on the epoll (or more generally, event loop) duration. This will help us to identify badly behaving event handlers in extensions to Envoy. In addition, we'd like to track wakeup delay; specifically the time between when the event manager blocks for the next wakeup and when the wakeup occurs, to get an idea of kernel load.

The existing libevent event loop (http://www.wangafu.net/~nickm/libevent-book/Ref3_eventloop.html) doesn't really support this, even if we run with EVLOOP_ONCE.

I'm interested in hearing from libevent folks how we could best add this support; we don't mind taking on this work item but would like some guidance on the best fit to libevent's API. I think libev/libuv could support this with their check/prepare/idle watchers, but maybe there is something lighterweight to add to libevent.

CC @mattklein123
Related discussion in https://github.com/envoyproxy/envoy/issues/4952

**Comment by azat** [comment]
Hi!

>The existing libevent event loop doesn't really support this, even if we run with EVLOOP_ONCE.

If I understand you correctly then you can achieve this with `EVLOOP_ONCE|EVLOOP_NONBLOCK`?

But I like the idea of adding an ability to hook into the event loop, I think this can be useful (and not only for this specific use-case). Plus it is pretty common to run `event_base_dispatch()` (i.e. without `EVLOOP_ONCE|EVLOOP_NONBLOCK`).

Some questions/thoughts that should be resolved first:
- should it be one hook per base or multiple hooks? (I guess multiple hooks can be useful here, but not in general though)
- new hooks API or new event flag like `EV_BASE_PRE`/`EV_BASE_POST`/`EV_BASE_IDLE`/`YOUR_NAME_IT` (I don't like the idea of adding this as a new event flags, since events are added to the queues and has priorities while this hooks do not need this)

>we don't mind taking on this work item
Are you willing contributing this patch to the libevent, am I understand you right? That would be great!

**Comment by htuch** [comment]
@azat I'm wondering how would you use `EVLOOP_NONBLOCK` for this? The idea is you want to know when the event loop is ready to run, i.e. have it sleep, and when the wakeup occurs start timing. You then want to stop timing when the event loop is done. The first part of this is the tricky part IMHO in the current libevent loop.

I can work on the patch for this, sure, since I think it's going to be able to unblock our ability to get at these stats.

I think what we want is the prepare/check hooks that libev offers, see https://metacpan.org/pod/distribution/EV/libev/ev.pod#ev_prepare-and-ev_check-customise-your-event-loop!.

We would have the API:
```
struct event_watcher* event_watcher_check_new(struct event_base *, callback);
struct event_watcher* event_watcher_prepare_new(struct event_base *, callback);
void event_watcher_free(struct event_watcher *);
```

Supporting multiple check/prepare per base should be reasonable with this resource model. I agree we should not overload event flags; this is an event loop hook rather than an event type.

**Comment by azat** [comment]
> @azat I'm wondering how would you use `EVLOOP_NONBLOCK` for this? The idea is you want to know when the event loop is ready to run, i.e. have it sleep, and when the wakeup occurs start timing. You then want to stop timing when the event loop is done. The first part of this is the tricky part IMHO in the current libevent loop.

You right it wouldn't (confused by EVLOOP_ONCE mention).

> We would have the API:
> ```
> struct event_watcher* event_watcher_check_new(struct event_base *, callback);
> struct event_watcher* event_watcher_prepare_new(struct event_base *, callback);
> void event_watcher_free(struct event_watcher *);
> ```

Looks reasonable (based on my current understanding).

**Comment by NathanFrench** [comment]
This may relate. If it's helpful, cool, if not, no biggie.

I have been working to get some high-resolution profiling statistics myself. So I started adding dtrace probes to various hotspots.

https://github.com/libevent/libevent/compare/master...NathanFrench:dtrace

I put an example script in there to show off some timing histograms.

**Comment by mergeconflict** [comment]
Hi @azat, I've put up a PR (#793) per @htuch's design (we share an office). We're pretty confident it provides what Envoy will require. Let us know what you think, thanks!

/cc @mattklein123
