### ISSUE TITLE
evhttp_connection->bufev being used after free?

### ISSUE THREAD

**Issue by adityamarella** [libevent/libevent#712]
bufev is freed here
https://github.com/libevent/libevent/blob/26ef859aa707fda72ce530bf761d1c41a76f67b7/http.c#L1233

accessed here 
https://github.com/libevent/libevent/blob/26ef859aa707fda72ce530bf761d1c41a76f67b7/http.c#L1239

and here
https://github.com/libevent/libevent/blob/26ef859aa707fda72ce530bf761d1c41a76f67b7/http.c#L1242

This looks like a bug to me, feel free to close the issue if it is not.

**Comment by azat** [comment]
The `evcon->fd` should be `-1` if `evcon->bufev` is `NULL`
Since the only case where it is possible is `evhttp_connection_base_bufferevent_new()` (and to be more precise we are obtaining fd from the bufev, so no bufev no fd)

So we are safe here.

**Comment by azat** [comment]
So you was right, this is **possible** in some **tricky cases** (you need at least one more thread for this) but in general this should not be happen due to the nature of `bufferevent_free()` - it does not free the memory itself, it schedule the finalizer that will be run from the event loop (that's why it works before without any issues)

P.S. sorry for the overlook

**Comment by adityamarella** [comment]
Thanks for the response! 

Couple of questions:
1. Does `evhttp_connection_free()` also schedule the finalizer to free the `evconn` object?
2. Does `event_base_loopbreak()` wait for the finalizer to finish before breaking the loop? I understand it waits for the current event to finish but the finalizer event could be enqueued and not currently running, what happens then? Does this cause memory leak?

**Comment by azat** [comment]
> 1. Does `evhttp_connection_free()` also schedule the finalizer to free the `evconn` object?

There are no finalizers for evhttp_connection_free(), only bufferevent
uses this.

You can grep by finalize:
  $ gg finalize_ -- :^test :^include :^event.c :^*.h
  bufferevent.c:static void bufferevent_finalize_cb_(struct event_callback *evcb, void *arg_);
  bufferevent.c:  event_callback_finalize_many_(bufev->ev_base, n_cbs, cbs,
  bufferevent.c:      bufferevent_finalize_cb_);
  bufferevent.c:bufferevent_finalize_cb_(struct event_callback *evcb, void *arg_)

(gg stands for 'git grep')

> 2. Does `event_base_loopbreak()` wait for the finalizer to finish before breaking the loop? I understand it waits for the current event to finish but the finalizer event could be enqueued and not currently running, what happens then? Does this cause memory leak?

event_base_loopbreak() only installs "event_break" flag and immediatelly
exist, so no it does not free anything.

But finalizers will be run by:
- during event_base_loop() is running
- in event_base_free() (but not in event_base_free_nofinalizers())
