### ISSUE TITLE
Read timeout while writing large files with evhttp_send_reply_chunk_with_cb

### ISSUE THREAD

**Issue by Preved7** [libevent/libevent#715]
Hi!
I am streaming huge amount of data (> 10 GB) with evhttp_send_reply_chunk_with_cb.
Right now if i set any timeout with evhttp_set_timeout, it sets both read and write timeout for the underlying connection.
During evhttp_write_buffer you do not disable EV_READ, so it means that we are actually trying to read something and the read timeout is applicable. Currently i have read timeout = wrtite timeout = 10 sec set and the connection gets dropped after 10 sec of writing due to **read** timeout.
If i disable EV_READ during evhttp_write_buffer and recompile libevent, everything seems working ok.

Can I disable EV_READ during evhttp_write_buffer? What are the consequences of doing so?
Another option could be to clear only the read timeout after i start writing. Is this a better solution to my problem?

**Comment by azat** [comment]
Hi!

We monitor EV_READ to detect any close events.
I think that #692 is what you need?

**Comment by azat** [comment]
Hi @Preved7 

In upstream there is `evhttp_set_read_timeout_tv()` and separate `evhttp_set_write_timeout_tv()` for this
