### ISSUE TITLE
Q: while(1) loop in listener.c listener_read_cb()

### ISSUE THREAD

**Issue by wongsyrone** [libevent/libevent#719]
The while(1) loop consumes lots of CPU time. Can we implement it in this way?

1. apply EV_READ|EV_PERSIST to the listener socket event
2. do accept() in the listener_read_cb()
3. if we got any error, check if we are under non-blocking mode, if accept() returns -1 and errno set to EAGAIN/EWOULDBLOCK, simply return and wait for next read event. if other errno being set, report the error.
4. if we got any error and under normal mode, just report the error.
5. pass client socket fd to user callback

**Comment by wongsyrone** [comment]
There is one situation I encounter:

- set nonblocking for listener fd
- pass the listener fd to evconnlistener_new()
- set errcb via evconnlistener_set_error_cb() and call event_base_loopbreak() in the errcb

It might went to the errcb when evutil_accept4_() returns -1 with EAGAIN.

**Comment by azat** [comment]
Hi!

> The while(1) loop consumes lots of CPU time. Can we implement it in this way?

Can you elaborate how it can consume "lots of CPU time"? It is already break from the loop on error (see below).

> apply EV_READ|EV_PERSIST to the listener socket event

Already

> do accept() in the listener_read_cb()

Already

> if we got any error, check if we are under non-blocking mode

*There is no need to check "under non-blocking mode", there should be any `EAGAIN`/`EWOULDBLOCK` if fd does not have `O_NONBLOCK`.*

> if accept() returns -1 and errno set to EAGAIN/EWOULDBLOCK, simply return and wait for next read event. if other errno being set, report the error.

This is how it works right [now](https://github.com/libevent/libevent/blob/f8d510f61777bcb194b945163b84047969a46cef/listener.c#L406)

> set errcb via evconnlistener_set_error_cb() and call event_base_loopbreak() in the errcb
It might went to the errcb when evutil_accept4_() returns -1 with EAGAIN.

Interesting. Are you sure that this is `errno` (there is `UNLOCK()` hence I guess `futex(2)` before, and it can return `EAGAIN`) from `accept4()`? Can you post minimal `strace -f` output?

**Comment by azat** [comment]
> there is UNLOCK() hence I guess futex(2) before, and it can return EAGAIN

*But I bet that you callback (that is installed with `evconnlistener_set_error_cb()`) calls something that adjust `errno`*

**Comment by wongsyrone** [comment]
Thanks for the detailed explanation, I implemented it in this way https://github.com/wongsyrone/transocks-wong/blob/a6de63b51c28c14038e1bc608224da130cd7caff/src/listener.c#L13 , I'm still investigating the issue.

**Comment by azat** [comment]
> Thanks for the detailed explanation, I implemented it in this way https://github.com/wongsyrone/transocks-wong/blob/a6de63b51c28c14038e1bc608224da130cd7caff/src/listener.c#L13 , I'm still investigating the issue.

Hm, no `errno` changes. So `strace -f` log to follow will be great.

**Comment by azat** [comment]
I'm not sure that I follow [this](https://github.com/wongsyrone/transocks-wong/commit/ae19a50fba956e0025bd11a40f8b7c7e7be13ccb)
Could you share minimal strace output of your program when you experience a while (1) loop that eats a lot of CPU (I guess you except a lot of accept() calls there) and trigger error_cb even when error is EAGAIN?

**Comment by azat** [comment]
Great!
