### ISSUE TITLE
A question about libevent with openssl (https client)

### ISSUE THREAD

**Issue by zfl9** [libevent/libevent#725]
```c
SSL *ssl = SSL_new(sslctx);
bev = bufferevent_openssl_socket_new(base, -1, ssl, BUFFEREVENT_SSL_CONNECTING, BEV_OPT_CLOSE_ON_FREE);
bufferevent_enable(bev, EV_READ | EV_WRITE);
bufferevent_socket_connect(bev, (struct sockaddr *)&addr, sizeof(addr));
int sockfd = bufferevent_getfd(bev); // a
do_something(sockfd); // b
```
The above code is a short paragraph I extracted from the application. The problem is that, in most cases, the `fd` returned by the statement `'a'` is normal (not -1), but sometimes the statement `'a'` returns an fd of `-1`, causing the statement `'b'` to execute incorrectly. why? **Why `bufferevent_getfd()` returning -1?** It has been confirmed that it is not a problem of `rlimit`（ulimit） resource limitation. In fact, when there is a problem, the number of sockets applied by the application is very small, only a dozen.（Linux）.

I want to confirm, after `bufferevent_socket_connect()` return, can I immediately call `bufferevent_getfd()` to get the requested sockfd? Is there any problem with this?

**Comment by wongsyrone** [comment]
I think you should use `bufferevent_setcb()` and call `bufferevent_getfd()` in the callback as `bufferevent_socket_connect()` is non-blocking.

**Comment by zfl9** [comment]
Thank you for your kindness, this is very helpful! @wongsyrone

**Comment by wongsyrone** [comment]
If you are not sure, you can check an example here: https://github.com/wongsyrone/transocks-wong/blob/master/src/socks5.c#L236
