### ISSUE TITLE
In windows IOCP mode ,libevent lost data

### ISSUE THREAD

**Issue by ww1999520** [libevent/libevent#728]
sorry to trouble u again, i'm tring to build a http server base on libevent in IOCP mode for windows os,
  when i almost finish it,i did the test,, i found that some package from the client lost, I created a new project to verify if i use libevent library  incorrecttly,but it still lost package, when i use the tool wireshake to pick up the data,i found the data has been send to the server successfully, but libevent didin't call the read_callback i registed...I don't know how to resolve the problem,
  what i tyied:
  i tried print the data in libevent source code,found that,data has being in the evbuffer,but read_complete wasn't called....
(note: i tried the newest master code and build it ,the problem still exist)

the attach is my test codes,
i did the test in local area network...
client has only one thread, it simulate http client, i send post data to server,uri increase by 1,like /abc/1   /abc/2 .... /abc/10000,and the http request is fixed length,
when server recv the data, return a 404 code http error to client, when client recv the respond ,it close the socket and begin anoth circlulation....

**Comment by ww1999520** [comment]
//server codes
#include <WinSock2.h>
#include <Windows.h>
#include <event2/event.h>
#include <event2/thread.h>
#include "event2/http.h"
#include "event2/buffer.h"
#include "event2/http_struct.h"
#include "event2/listener.h"
#include "event2/bufferevent.h"
#include <string>
using namespace std;


#pragma comment(lib,"ws2_32.lib")

void init_listen_address_(const string& _strip,unsigned short _iport,sockaddr_in* addr);
event_base* libevhttp_init_event_base();
void libevhttp_accept_socket_cb(struct evconnlistener *listener, evutil_socket_t nfd, struct sockaddr *peer_sa, int peer_socklen, void *arg);
void libevhttp_read_cb(struct bufferevent *bev, void *arg);
void libevhttp_write_cb(struct bufferevent *bev, void *arg);
void libevhttp_event_cb(struct bufferevent *bev, short what, void *arg);

int main()
{
	string strip = "192.168.1.201";
	sockaddr_in addr;
	init_listen_address_(strip,40000,&addr);
	event_base* base = libevhttp_init_event_base();
	evconnlistener* __listener = evconnlistener_new_bind(base, libevhttp_accept_socket_cb,base,
		LEV_OPT_REUSEABLE|LEV_OPT_CLOSE_ON_EXEC|LEV_OPT_CLOSE_ON_FREE,
		-1, (struct sockaddr*)&addr,sizeof(struct sockaddr_in));

	event_base_dispatch(base);
	//for test ,so resource not recycled...
	return 0;
}

//timeval tv_read;
void libevhttp_accept_socket_cb(struct evconnlistener *listener, evutil_socket_t nfd, struct sockaddr *peer_sa, int peer_socklen, void *arg)
{
	sockaddr_in* address = (sockaddr_in*)peer_sa;
	event_base* base = (event_base*) arg;

	bufferevent* __bev = bufferevent_socket_new(base, nfd,BEV_OPT_CLOSE_ON_FREE|BEV_OPT_THREADSAFE);
	bufferevent_enable(__bev, EV_READ | EV_PERSIST);
	bufferevent_setcb(__bev, libevhttp_read_cb, NULL, libevhttp_event_cb, NULL);
}

string strreturn = "404 NOT FOUND\r\n"
"Content-Type: text/html\r\n"
"Connection: close\r\n"
"Content-Length: 90\r\n\r\n"
"<HTML><HEAD>\n"
"<TITLE>404 NOT FOUND</TITLE>\n"
"</HEAD><BODY>\n"
"<H1>NOT FOUND</H1>\n"
"</BODY></HTML>\n";

void libevhttp_read_cb(struct bufferevent *bev, void *arg)
{

	evbuffer* evbuff = bufferevent_get_input(bev);
	//I printed the debug info here,but the data lost,read_cb wasn't called...
	//only care the first url part
	char buff[64];
	unsigned char* buffrecv = evbuffer_pullup(evbuff,29);
	buff[0] = 'c';buff[1] = 'b';buff[2] = ' ';
	memcpy(buff + 3,buffrecv,32);buff[32] = 0;
	printf(buff);
	bufferevent_write(bev,strreturn.c_str(),strreturn.length());
	//clear evbuffer,
	evbuffer_drain(evbuff,evbuffer_get_length(evbuff));
}

void libevhttp_write_cb(struct bufferevent *bev, void *arg)
{
}

void libevhttp_event_cb(struct bufferevent *bev, short what, void *arg)
{
	bool bneedclose = false;
	if(what & BEV_EVENT_EOF) bneedclose = true;
	else if(what & BEV_EVENT_ERROR) bneedclose = true;
	else if(what & BEV_EVENT_TIMEOUT) bneedclose = true;
	if(bneedclose) bufferevent_free(bev);
}

void init_listen_address_(const string& _strip,unsigned short _iport,sockaddr_in* addr)
{
	memset(addr, 0, sizeof(struct sockaddr_in));
	addr->sin_family = AF_INET;
	if(!_strip.empty()) addr->sin_addr.s_addr=inet_addr(_strip.c_str());//服务器IP地址
	addr->sin_port = htons(_iport);
}

event_base* libevhttp_init_event_base()
{
#ifdef WIN32
	WSADATA wsaData;
	WSAStartup(MAKEWORD(2, 2), &wsaData);
	evthread_use_windows_threads();
#endif
	event_config* cfg = event_config_new();
	if(cfg == NULL)
	{
		return NULL;
	}
	event_config_set_flag(cfg, EVENT_BASE_FLAG_STARTUP_IOCP); //EVHTTP 不支持IOCP ，LIBEVENT 支持 
	event_config_set_num_cpus_hint(cfg,1);//最多给4个
	//-----设置libevent事件，每当socket出现可读事件，就调用on_accept()------------x
	event_base* base = event_base_new_with_config(cfg);//基于 iocp
	event_config_free(cfg);
	return base;
}

**Comment by ww1999520** [comment]
//client codes
#include<WINSOCK2.H>
#include<STDIO.H>
#include<iostream>
#include<string>
#include <process.h>
using namespace std;
#pragma comment(lib, "ws2_32.lib")


volatile long inow;
volatile long itotal;
int ithreads;
//HEvent ev;
int icount;

string strip;
unsigned short iport;

void __cdecl thread_cb(void* arg)
{
	char buffsend[4096] = "POST /abc/         HTTP/1.1\r\n"
		"PlatFormID: 44612301\r\n"
		"Content-Length: 65\r\n\r\n"
		"{\"oper\":\"systemdictquery\",\"cond\":{\"dictType\":2,\"dictStatus\":0}}\r\n";
	int ilensend = strlen(buffsend);
	SOCKET sclient;

	sockaddr_in serAddr;
	serAddr.sin_family = AF_INET;
	serAddr.sin_port = htons(iport);
	serAddr.sin_addr.S_un.S_addr = inet_addr(strip.c_str());
	long ilnow;

	char recData[4096];
	char buffindex[16];
	int ret;
	do 
	{
		++ilnow
		ret = sprintf(buffindex,"%d",ilnow);
		memcpy(buffsend + 10,buffindex,ret);
		sclient = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
		if(sclient == INVALID_SOCKET)
		{
			printf("invalid socket,dw:%d !\n",WSAGetLastError());
			continue ;
		}

		if(connect(sclient, (sockaddr *)&serAddr, sizeof(serAddr)) == SOCKET_ERROR)
		{
			printf("connect error !");
			closesocket(sclient);
			continue ;
		}

		ret = 0;
		int iread(0);
		do 
		{
			ret = send(sclient, buffsend, ilensend, 0);
			if(ret < 0)
			{
				break;
			}
			iread += ret;
		} while (ret < ilensend);

		if(ret < 0)
		{
			printf("send failed,dw:%d...\n",WSAGetLastError());
			closesocket(sclient);
			continue;
		}

		ret = 0;
		
		do
		{
			iread = recv(sclient, recData, 4096, 0);
			if(iread == 0)
			{
				//printf("iread = 0, inow:%d,dw:%d...\n",inow,WSAGetLastError());
				break;
			}
			if(iread < 0)
			{
				//printf("iread:%d,inow:%d,dw:%d...\n",iread,inow,WSAGetLastError());
				break;
			}

			ret += iread;
		} while (ret < 171);
		recData[ret] = 0;

		closesocket(sclient);

		if((ilnow % 1000) == 0)	printf("inow:%d...\n",ilnow);
	} while ( ilnow < icount);
	//ev.notify();
	//printf("inow:%d,dw:%d...\n",inow,WSAGetLastError());
}

int main()
{
	WSADATA wsaData;
	WSAStartup(MAKEWORD(2, 2), &wsaData);

	//ev.init();
	inow = 0;itotal = 0;
	ithreads = 1;
	icount = 150000;//will try 150000 times
	strip = "192.168.1.201";
	iport = 40000;
	thread_cb(NULL);

	//DWORD dw = GetTickCount();
	//for (int i = 0 ;i < ithreads ; ++i)
	//{
	//	_beginthread(thread_cb,0,0);
	//}
	//for test ,event structure is not fitable,so i did deadly cycle wait...
	while (true)
	{
		::Sleep(10000);
	}
	//ev.wait();
	//dw = GetTickCount() - dw;

	//::Sleep(5000);
	//printf("icount:%d,cost:%u,ithread:%d\n",HCommonFun::InterlockedIncrementM(&itotal) - 1,dw,ithreads);
	system("pause");
	WSACleanup();
	return 0;
}

**Comment by azat** [comment]
Hi!

No issues with regular select()?

**Comment by azat** [comment]
Also could you please post sha1 commit of libevent tree?
(And please please use markdown)

**Comment by ww1999520** [comment]
yeah,i tried about 10 or more times running the client,for about 2000000 times "connect->send->recv-> close" flow ,the client never got stuck,but when i tried iocp mode ,it got stuck large probabilitily...
  i'm sorry, what's sha1 commit? it meant the version of libevent ?
first i tried the latest release version:libevent-release-2.1.8-stable.zip
it still exist.....
i will try to use markdown,sorry, i'm unfamiliar with git.....

**Comment by ww1999520** [comment]
yeah,when i didn't set EVENT_BASE_FLAG_STARTUP_IOCP flag ,i tried about 10 or more times running the client,for about 2000000 times "connect->send->recv-> close" flow ,the client never got stuck,but when i tried iocp mode ,it got stuck large probabilitily...
 i'm sorry, what's sha1 commit? it meant the version of libevent ?
 first i tried the latest release version:libevent-release-2.1.8-stable.zip
 it still exist.....
 i will try to use markdown,sorry, i'm unfamiliar with git.....

**Comment by ww1999520** [comment]
sorry azat,i use libevent incorrectly,

i called bufferevent_enable EV_READ before bufferevent_setcb,this may cause the problem.....sorry to trouble u....
