### ISSUE TITLE
CMake can't link ${LIBEVENT_SHARED_LIBRARIES} variable in windows

### ISSUE THREAD

**Issue by seamine** [libevent/libevent#731]
First. I has built the libevent from master branches in windows successfully,
Then Install it to default path,  The path is C:\Program Files (x86)\libevent
Finally, In my cmake project ,  add
```cmake
find_package(libevent)
include_directories(${LIBEVENT_INCLUDE_DIRS})
target_link_libraries(${LIBEVENT_SHARED_LIBRARIES})
```

cmake work well,   my project is test_http_server ,  test_http_server.c is the copy of http_server.c
from libevent project.

there appears link error, I think the reason  the LIBEVENT_SHARED_LIBRARIES variable not found.
Because I open the project properties page in VC IDE,  Linker/Input/Addtional Dependencies page has no libevent library 
references.

Environment:
OS: Windows 10 Pro x64 
Compiler:  MSVC 19.16.27024.1(Visual Studio 2017 15.9.3)

the following is the build log:

<pre>
1>------ Build started: Project: test_http_server, Configuration: Debug Win32 ------
1>test_http_server.obj : error LNK2019: unresolved external symbol _evutil_snprintf referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evutil_inet_ntop referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evutil_ascii_strcasecmp referenced in function _guess_content_type
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_base_dispatch referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_config_new referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_config_free referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_config_set_flag referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_config_set_num_cpus_hint referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_base_new_with_config referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_base_free referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_enable_debug_logging referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_base_loopbreak referenced in function _do_term
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_new referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_free referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _event_add referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_new referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_bind_socket_with_handle referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_bound_socket_get_fd referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_free referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_set_cb referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_set_gencb referenced in function _main
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_send_error referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_send_reply referenced in function _dump_request_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_request_get_uri referenced in function _dump_request_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_request_get_command referenced in function _dump_request_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_request_get_input_headers referenced in function _dump_request_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_request_get_output_headers referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_request_get_input_buffer referenced in function _dump_request_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_add_header referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_uridecode referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_uri_get_path referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_uri_parse referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evhttp_uri_free referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evbuffer_new referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evbuffer_free referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evbuffer_get_length referenced in function _dump_request_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evbuffer_remove referenced in function _dump_request_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evbuffer_add_file referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evbuffer_add_printf referenced in function _send_document_cb
1>test_http_server.obj : error LNK2019: unresolved external symbol _evthread_use_windows_threads referenced in function _main
1>D:\code\UnitedReader\build\bin\Debug\test_http_server.exe : fatal error LNK1120: 40 unresolved externals
</pre>

**Comment by azat** [comment]
> I think the reason the LIBEVENT_SHARED_LIBRARIES variable not found.

Indeed, and this is now how cmake exports works.

Right now you should use one of the following:
- `event_{lib}_shared` 
- `event_{lib}_static`

Where `{lib}` is one of the following (on windows):
- `core`
- `extra`
- `openssl`

Although an alias `event_{lib}` for `event_{lib}_shared` would make sense, will be added later.

(and this is for proper libevent installed, i.e. `LibeventTargets.cmake` for `cmake`, and of course of you want tip for debugging first you should look into that file)

*P.S.: please do not force us to read monotonic descriptions, and use markdown at least*

**Comment by seamine** [comment]
Thanks your reply,  The problem has resolved, Thanks again!!
