### ISSUE TITLE
android issue

### ISSUE THREAD

**Issue by manang** [libevent/libevent#734]
Hi,
i'm trying to compile libevent for android and I have the following error:
 error: no member named '__ss_family' in 'struct __kernel_sockaddr_storage'; did you mean 'ss_family'?

Solutions?

**Comment by manang** [comment]
I correct it commenting passing to cmake the following commands:
-DEVENT__HAVE_WAITPID_WITH_WNOWAIT_EXITCODE=1
-DEVENT__DISABLE_SAMPLES=1

**Comment by azat** [comment]
Hi!

Can you share log of cmake and `CMakeCache.txt` (from the clean build without passing `-D`) ?

P.S. `struct __kernel_sockaddr_storage` does not looks like public structure, can you show it's type? (like `ptype` command in `gdb`)

**Comment by manang** [comment]
No,
I did not solve totally.
with linux environment I can compile libevent, with mac osx environment I have the same errors.
I've attached CMakeError.log and CMakeOutput.log
[CMakeOutput.log](https://github.com/libevent/libevent/files/2671111/CMakeOutput.log)
[CMakeError.log](https://github.com/libevent/libevent/files/2671112/CMakeError.log)

**Comment by azat** [comment]
>I've attached CMakeError.log and CMakeOutput.log too:

You forgot to attach:
- `CMakeCache.txt`
- and plain output of the cmake

**Comment by NathanFrench** [comment]
Can you also paste the output of `/Users/angelomantellini/android-sdk_cicn_clang/build_armv7-a/libevent/CMakeFiles/CheckTypeSize/EVENT__HAVE_STRUCT_SOCKADDR_STORAGE.c`?

**Comment by azat** [comment]
> Should we put that second check behind a `if (NOT EVENT__HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY)`?

Indeed

**Comment by manang** [comment]
tomorrow I will send you the log.
sorry for the delay

**Comment by azat** [comment]
>tomorrow I will send you the log.

So just to remember, please send us:
- `CMakeCache.txt`
- `/Users/angelomantellini/android-sdk_cicn_clang/build_armv7-a/libevent/CMakeFiles/CheckTypeSize/EVENT__HAVE_STRUCT_SOCKADDR_STORAGE.c` (or relative path if you changed the location of the build)

And according to cmake logs it looks like there is no sockaddr_storage definition, so how then __ss_family is used?

I remember that I compiled under android without any issues, maybe this pops up due darwin host (I tried under linux)

**Comment by azat** [comment]
Closed due to inactivity, feel free to reopen, once you will provide requested details
