### ISSUE TITLE
Cannot configure static runtime

### ISSUE THREAD

**Issue by ofersadgat** [libevent/libevent#737]
I am building libevent with a CMakeFile:

```
ExternalProject_Add(event-cmake
  GIT_REPOSITORY https://github.com/libevent/libevent.git
  DEPENDS openssl-cmake
  UPDATE_COMMAND ""
  PREFIX ${EVENT_ROOT_DIR}
  CMAKE_ARGS "${CMAKE_ARGS};-DEVENT__DISABLE_OPENSSL=TRUE;-DCMAKE_INSTALL_PREFIX=${EVENT_ROOT_DIR};-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE};-DEVENT__DISABLE_REGRESS=TRUE;-DEVENT__LIBRARY_TYPE=STATIC"
)
```

The problem is that even though it builds a static library, it does it with a dynamic runtime. This means that all projects that link with this also have to use a dynamic runtime. protobuf allows you to choose what runtime it gets linked with via the folllowing:

```
  if (MSVC AND protobuf_MSVC_STATIC_RUNTIME)
    foreach(flag_var
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
      if(${flag_var} MATCHES "/MD")
        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MD")
    endforeach(flag_var)
  endif (MSVC AND protobuf_MSVC_STATIC_RUNTIME)
```
It would be nice if libevent had a similar option. Thanks!

**Comment by azat** [comment]
Thanks for the report!

`EVENT__MSVC_STATIC_RUNTIME` cmake option had been introduced.

CI: https://ci.appveyor.com/project/azat/libevent/build/job/4m26g1tor8wlagk8)

**Comment by ofersadgat** [comment]
Thanks!
