### ISSUE TITLE
why struct evhttp_uri is an internal structure?

### ISSUE THREAD

**Issue by chenyahui** [libevent/libevent#739]
`struct evhttp_uri` is defined on http.c，so any user can‘t see the internal structure of  evhttp_uri? 

why don't put it on http_struct.h?

**Comment by azat** [comment]
It is incapsulated to make changes ABI compatible.

**Comment by chenyahui** [comment]
so，I have to redefine `struct evhttp_uri` in my project? if not, it will report `incomplete type error`

**Comment by azat** [comment]
What for? You should use pointer, and bunch of getters/setters

**Comment by chenyahui** [comment]
Ok, it can work, thanks. but so strange that I get a struct data but can't use it directly.
