### ISSUE TITLE
how to use `bufferevent_set_timeouts`, according to the book guidelines, this not working

### ISSUE THREAD

**Issue by zfl9** [libevent/libevent#742]
how to use:
```c
udpbev = bufferevent_openssl_socket_new(base, -1, ssl, BUFFEREVENT_SSL_CONNECTING, BEV_OPT_CLOSE_ON_FREE);

struct timeval tv = {5, 0};
bufferevent_set_timeouts(udpbev, NULL, &tv);

bufferevent_setcb(udpbev, NULL, NULL, udp_sendreq_cb, NULL);
bufferevent_enable(udpbev, EV_READ | EV_WRITE);
bufferevent_setwatermark(udpbev, EV_READ, 0, BUFSIZ_FOR_BEV);
printf("%s [udp] connecting to %s:%d\n", loginf(ctime), servhost, servport);
while (bufferevent_socket_connect(udpbev, (struct sockaddr *)&servaddr, sizeof(servaddr)) != 0) {
    printf("%s [udp] socket error: (%d) %s\n", logerr(ctime), errno, strerror_r(errno, error, 64));
    sleep(1);
}
```

event_function:
```c
...
if (events & BEV_EVENT_TIMEOUT) {
    printf("%s [udp] write timeout: %s:%d\n", logerr(ctime), servhost, servport);
}
...
```

debug output:
```
# The first attempt to send
(I deliberately set the iptables rule at the gateway to discard its packets) and did not trigger a timeout event

[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x19ce860 (fd 7), res 2, callback 0x406b80
[debug] event_process_active: event: 0x19ce860, EV_READ   call 0x406b80
2019-01-04 16:01:36 INF: [udp] recv 55 bytes data from 192.168.1.5:11902
[debug] event_remove_timer_nolock: event: 0x1a8d830
[debug] event_add: event: 0x1a8d8a8 (fd 8),  EV_WRITE  EV_TIMEOUT call 0x4304d4
[debug] Epoll MOD(5) on fd 8 okay. Old events were 2; read change was 0 (none); write change was 1 (add); close change was 0 (none)
[debug] event_add: event 0x1a8d8a8, timeout in 5 seconds 0 useconds, call 0x4304d4
2019-01-04 16:01:36 INF: [udp] send 55 bytes data to 8.8.8.8:53
[debug] timeout_next: event: 0x1a8d8a8, in 5 seconds, 0 useconds
[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x1a8d8a8 (fd 8), res 4, callback 0x4304d4
[debug] event_process_active: event: 0x1a8d8a8,  EV_WRITE  call 0x4304d4
[debug] event_add: event: 0x1a8d8a8 (fd 8),  EV_WRITE  EV_TIMEOUT call 0x4304d4
[debug] event_add: event 0x1a8d8a8, timeout in 11194 seconds 604464 useconds, call 0x4304d4
[debug] event_del: 0x1a8d8a8 (fd 8), callback 0x4304d4
[debug] Epoll MOD(1) on fd 8 okay. Old events were 6; read change was 0 (none); write change was 2 (del); close change was 0 (none)
[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x19ce860 (fd 7), res 2, callback 0x406b80
[debug] event_process_active: event: 0x19ce860, EV_READ   call 0x406b80

# The second attempt to send, like the original result, did not trigger any timeout event
2019-01-04 16:01:41 INF: [udp] recv 55 bytes data from 192.168.1.5:11902
[debug] event_remove_timer_nolock: event: 0x1a8d830
[debug] event_add: event: 0x1a8d8a8 (fd 8),  EV_WRITE  EV_TIMEOUT call 0x4304d4
[debug] Epoll MOD(5) on fd 8 okay. Old events were 2; read change was 0 (none); write change was 1 (add); close change was 0 (none)
[debug] event_add: event 0x1a8d8a8, timeout in 5 seconds 0 useconds, call 0x4304d4
2019-01-04 16:01:41 INF: [udp] send 55 bytes data to 8.8.8.8:53
[debug] timeout_next: event: 0x1a8d8a8, in 5 seconds, 0 useconds
[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x1a8d8a8 (fd 8), res 4, callback 0x4304d4
[debug] event_process_active: event: 0x1a8d8a8,  EV_WRITE  call 0x4304d4
[debug] event_add: event: 0x1a8d8a8 (fd 8),  EV_WRITE  EV_TIMEOUT call 0x4304d4
[debug] event_add: event 0x1a8d8a8, timeout in 11199 seconds 607524 useconds, call 0x4304d4
[debug] event_del: 0x1a8d8a8 (fd 8), callback 0x4304d4
[debug] Epoll MOD(1) on fd 8 okay. Old events were 6; read change was 0 (none); write change was 2 (del); close change was 0 (none)
```

According to the libevent book and api instructions, I think this should work. My intention is that if the packet is not sent out for more than 5s (perhaps because of packet loss or other network reasons), the BEV_EVENT_TIMEOUT event will be triggered, but there is no Any timeout event, please help me, I have been bothered for a long time, how can I use it correctly with regard to the use of this function?

How do I set the write data timeout time? That is, I send a packet to the peer, and then I want to set the 5s send timeout. If the duration is not exceeded, the TIMEOUT event is triggered.

thank!

**Comment by azat** [comment]
>udpbev = bufferevent_openssl_socket_new(base, -1, ssl, BUFFEREVENT_SSL_CONNECTING, BEV_OPT_CLOSE_ON_FREE);

Does it work with `bufferevent_socket_new()`?

*All bufferevents except the one that handles regular sockets handles timeouts differently, and I guess that this is the case.*

Refs: #470

**Comment by zfl9** [comment]
That means that bufferevent_set_timeouts is not suitable for openssl based-socket?

**Comment by zfl9** [comment]
According to your prompt, I wrote a simple netcat/telnet program and set the 5s send timeout, but it still doesn't work when I test it!
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <event2/event.h>
#include <event2/bufferevent.h>
#include <event2/buffer.h>
#include <event2/util.h>

#define BUFF_SIZE 4096
static void *buffer_ev = NULL;
static void *buffer_bev = NULL;
static struct event_base *base = NULL;

void ev_read_cb(int fd, short events, void *arg);
void bev_read_cb(struct bufferevent *bev, void *arg);
void bev_event_cb(struct bufferevent *bev, short events, void *arg);

int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "usage: %s <addr> <port>\n", argv[0]);
        return 1;
    }

    char *servhost = argv[1];
    int   servport = strtol(argv[2], NULL, 10);

    base = event_base_new();
    buffer_ev = malloc(BUFF_SIZE);
    buffer_bev = malloc(BUFF_SIZE);

    struct bufferevent *bev = bufferevent_socket_new(base, -1, BEV_OPT_CLOSE_ON_FREE);
    bufferevent_setcb(bev, bev_read_cb, NULL, bev_event_cb, NULL);
    bufferevent_enable(bev, EV_READ | EV_WRITE);

    struct timeval tv = {5, 0};
    bufferevent_set_timeouts(bev, NULL, &tv);

    struct event *ev = event_new(base, 0, EV_READ | EV_PERSIST, ev_read_cb, bev);
    event_add(ev, NULL);

    printf("connecting to %s:%d ...\n", servhost, servport);
    bufferevent_socket_connect_hostname(bev, NULL, AF_INET, servhost, servport);
    event_base_dispatch(base);

    event_base_free(base);
    free(buffer_ev);
    free(buffer_bev);

    return 0;
}

void bev_event_cb(struct bufferevent *bev, short events, void *arg) {
    (void) arg;

    struct sockaddr_in servaddr = {0};
    socklen_t addrlen = sizeof(struct sockaddr_in);
    getpeername(bufferevent_getfd(bev), (struct sockaddr *)&servaddr, &addrlen);

    if (events & BEV_EVENT_CONNECTED) {
        printf("connected to %s:%d\n", inet_ntoa(servaddr.sin_addr), ntohs(servaddr.sin_port));
        return;
    }

    if (events & BEV_EVENT_TIMEOUT) {
        fprintf(stderr, "send timeout: %s:%d\n", inet_ntoa(servaddr.sin_addr), ntohs(servaddr.sin_port));
    }

    if (events & BEV_EVENT_ERROR) {
        int dnserror = bufferevent_socket_get_dns_error(bev);
        if (dnserror != 0) {
            fprintf(stderr, "dns error: %s\n", evutil_gai_strerror(dnserror));
        } else {
            fprintf(stderr, "got error: (%d) %s\n", errno, strerror(errno));
        }
    }
    
    if (events & (BEV_EVENT_EOF | BEV_EVENT_ERROR | BEV_EVENT_TIMEOUT)) {
        printf("close socket: %s:%d\n", inet_ntoa(servaddr.sin_addr), ntohs(servaddr.sin_port));
        bufferevent_free(bev);
    }
}

void bev_read_cb(struct bufferevent *bev, void *arg) {
    (void) arg;

    struct evbuffer *input = bufferevent_get_input(bev);
    int remaining = evbuffer_get_length(input);

    if (remaining <= BUFF_SIZE) {
        bufferevent_read(bev, buffer_bev, remaining);
        write(1, buffer_bev, remaining);
    } else {
        for (int i = 0, cnt = remaining / BUFF_SIZE; i < cnt; ++i) {
            bufferevent_read(bev, buffer_bev, BUFF_SIZE);
            write(1, buffer_bev, BUFF_SIZE);
        }
        bufferevent_read(bev, buffer_bev, remaining % BUFF_SIZE);
        write(1, buffer_bev, remaining % BUFF_SIZE);
    }
}

void ev_read_cb(int fd, short events, void *arg) {
    (void) fd; (void) events;
    int length = read(0, buffer_ev, BUFF_SIZE);
    bufferevent_write(arg, buffer_ev, length);
}
```

The test steps are as follows:
1. `ncat -lk 127.0.0.1 8080`: Listen to local 8080 port, netcat
2. `./netcat-raw 127.0.0.1 8080`: Run my test program and connect to ncat 127.0.0.1:8080
3. The connection is successful, and I just knocked a few characters and sent it to ncat normally.
4. Then I use iptables to send the packet to 127.0.0.1:8080/tcp to DROP, hit a few more characters, and press Enter. Oddly, set_timeouts still doesn't work!

This is the output of the program:
```
$ ./netcat-raw 127.0.0.1 8080
connecting to 127.0.0.1:8080 ...
connected to 127.0.0.1:8080
hello
=======
world
^C
```
Hello is knocked before the drop, it proves that the program is ok, the world is knocked after the drop, I waited for a minute, and there is no send timeout prompt!

Can you tell me what is the problem, is it my use? still is? The system tested was linux. The libevent version is the latest last-release version. thanks!

**Comment by zfl9** [comment]
> The read timeout will trigger if the bufferevent waits at least timeout_read seconds while trying to read read. The write timeout will trigger if the bufferevent waits at least timeout_write seconds while trying to write data.
> 
> Note that the timeouts only count when the bufferevent would like to read or write. In other words, the read timeout is not enabled if reading is disabled on the bufferevent, or if the input buffer is full (at its high-water mark). Similarly, the write timeout is not enabled if if writing is disabled, or if there is no data to write.

**Similarly, the write timeout is not enabled if if writing is disabled, or if there is no data to write.**
what the meaning of `if there is no data to write` ?Does evbuffer_output be empty?Or is the socket send buffer empty?Or how?

**Comment by zfl9** [comment]
Sorry, I seem to understand the effect of the bufferevent_set_timeouts api. I thought it was the timeout for the socket to send data (that is, similar to the TCP retransmission timer, each packet will have a retransmission timer. If the timer expires, And when the number of timeouts reaches the maximum, it will report the socket timeout error to the upper application and disconnect the socket connection), but I took a closer look at the libevent book and api comments today and found that it is completely different from what I understand.

Do you know that you can set this type of timeout in libevent? The reason I need to set this timeout is because my application received a notification from the other party's tcp window size = 0, telling me that I can't send data to the other party, and the currently held socket will constantly ask the other party tcp window size. Whether it has been updated, this inquiry process lasted for one day, and there was no result, which caused my application to be unable to know that the connection is no longer available. I hope that some similar attacks can be avoided by some means.

**Comment by azat** [comment]
>According to your prompt, I wrote a simple netcat/telnet program and set the 5s send timeout, but it still doesn't work when I test it!

Sorry wrong path (didn't read the issue carefully, plus it overlapped with the referenced issues in my head).

> what the meaning of if there is no data to write ?Does evbuffer_output be empty?Or is the socket send buffer empty?Or how?

- output buffer is empty
- ratelimit
- watermarks
- ...


> Do you know that you can set this type of timeout in libevent?

You can just add one more evtimer.

But you should not retry sending data again in this case, since it can be held somewhere in the path, you should just reconnect/close the socket.

>closed this 18 minutes ago

Anyway looks like you already figure this out.
