### ISSUE TITLE
bufferevent_openssl.c:125:7

### ISSUE THREAD

**Issue by hdatma** [libevent/libevent#746]
test

bufferevent_openssl.c:125:7: warning: implicit declaration of function 'BIO_get_init' is invalid in C99 [-Wimplicit-function-declaration]
                if (BIO_get_init(b) && BIO_get_data(b))
                    ^
bufferevent_openssl.c:125:7: warning: this function declaration is not a prototype [-Wstrict-prototypes]

**Comment by azat** [comment]
Which version of libevent are you trying to compile?
And which version of openssl you using to build libevent?
Also can you please post full logs of the build (from scratch, i.e. without any old caches)

**Comment by hdatma** [comment]
note: bufferevent_openssl.c did not define BIO_get_init before using it

libevent 2.1.8-stable
libressl 2.8.3

> make
  GEN      test/rpcgen-attempted
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       sample/dns-example.o
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_filter.lo
  CC       bufferevent_pair.lo
  CC       bufferevent_ratelim.lo
  CC       bufferevent_sock.lo
  CC       event.lo
  CC       evmap.lo
  CC       evthread.lo
  CC       evutil.lo
  CC       evutil_rand.lo
  CC       evutil_time.lo
  CC       listener.lo
  CC       log.lo
  CC       select.lo
  CC       poll.lo
  CC       kqueue.lo
  CC       signal.lo
  CC       evdns.lo
  CC       event_tagging.lo
  CC       evrpc.lo
  CC       http.lo
  CCLD     libevent.la
  CCLD     sample/dns-example
  CC       sample/event-read-fifo.o
  CCLD     sample/event-read-fifo
  CC       sample/hello-world.o
  CCLD     sample/hello-world
  CC       sample/http-server.o
  CCLD     sample/http-server
  CC       sample/http-connect.o
  CCLD     sample/http-connect
  CC       sample/signal-test.o
  CCLD     sample/signal-test
  CC       sample/time-test.o
  CCLD     sample/time-test
  CC       sample/le-proxy.o
  CC       libevent_openssl_la-bufferevent_openssl.lo
bufferevent_openssl.c:125:7: warning: implicit declaration of function 'BIO_get_init' is invalid in C99 [-Wimplicit-function-declaration]
                if (BIO_get_init(b) && BIO_get_data(b))
                    ^
bufferevent_openssl.c:125:7: warning: this function declaration is not a prototype [-Wstrict-prototypes]
2 warnings generated.
  CCLD     libevent_openssl.la
  CCLD     sample/le-proxy
  CC       sample/https-client.o
  CC       sample/hostcheck.o
  CC       sample/openssl_hostname_validation.o
  CCLD     sample/https-client
  CC       test/bench.o
  CCLD     test/bench
  CC       test/bench_cascade.o
  CCLD     test/bench_cascade
  CC       test/bench_http.o
  CCLD     test/bench_http
  CC       test/bench_httpclient.o
  CCLD     libevent_core.la
  CCLD     test/bench_httpclient
  CC       test/test-changelist.o
  CCLD     test/test-changelist
  CC       test/test-dumpevents.o
  CCLD     test/test-dumpevents
  CC       test/test-eof.o
  CCLD     test/test-eof
  CC       test/test-closed.o
  CCLD     test/test-closed
  CC       test/test-fdleak.o
  CCLD     test/test-fdleak
  CC       test/test-init.o
  CCLD     test/test-init
  CC       test/test-ratelim.o
  CCLD     test/test-ratelim
  CC       test/test-time.o
  CCLD     test/test-time
  CC       test/test-weof.o
  CCLD     test/test-weof
  CC       test/regress-regress.o
  CC       test/regress-regress.gen.o
  CC       test/regress-regress_buffer.o
  CC       test/regress-regress_bufferevent.o
  CC       test/regress-regress_dns.o
  CC       test/regress-regress_et.o
  CC       test/regress-regress_finalize.o
  CC       test/regress-regress_http.o
  CC       test/regress-regress_listener.o
  CC       test/regress-regress_main.o
  CC       test/regress-regress_minheap.o
  CC       test/regress-regress_rpc.o
  CC       test/regress-regress_testutils.o
  CC       test/regress-regress_util.o
  CC       test/regress-tinytest.o
  CC       test/regress-regress_thread.o
  CC       test/regress-regress_zlib.o
  CC       test/regress-regress_ssl.o
  CC       evthread_pthread.lo
  CCLD     libevent_pthreads.la
  CCLD     test/regress
  CCLD     libevent_extra.la

**Comment by hdatma** [comment]
openssl defines BIO_get_init
libressl does not.

**Comment by azat** [comment]
> libressl does not.

Indeed, then you need next patch - 28b8075400c70b2d2da2ce07e590c2ec6d11783d
Since you already compiling libevent from sources I think this won't be a problem for you to try? Plus I would recommend you to give upstream master a try (instead of cherry-picking that particular patch)

**Comment by azat** [comment]
@hdatma have you tried the above?

**Comment by hdatma** [comment]
It is not based on 2.1.8.

**Comment by azat** [comment]
>It is not based on 2.1.8.

Not sure that I'm following you

If you mean that you cannot apply that patch on top of 2.1.8, then try to apply all next patches:
- 28b80754 Fix build with LibreSSL 2.7
- c2c08e02 Add missing includes into openssl-compat.h
- d057c45e Unbreak build with LibreSSL after openssl 1.1 support added

Or you can:
- wait until 2.1.9-beta will be release
- compile libevent from upstream (`https://github.com/libevent/libevent.git master`)

**Comment by hdatma** [comment]
The git cloned version is quiet on the above matter.

 I got this one instead:

http.c:3279:11: warning: assigning to 'char *' from 'const char [1]' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                value = "";
                                      ^ ~~
