### ISSUE TITLE
libevent.a(event.o):relocation R_x86_64_32 against'.rodata' cannot be used when making a shared object；recompile with -fPIC

### ISSUE THREAD

**Issue by elisium7** [libevent/libevent#752]
when i run ./configure-->make-->make install and get the static lib ,then use it in my project(rocketmq-client-cpp),it failed and promts that recompile with -fPIC,the version is 2.0.22-stable

can anyone tell me whether  this static lib was  compiled with -fPIC,or how can I get a new static lib with -fPIC?

**Comment by azat** [comment]
> can anyone tell me whether this static lib was compiled with -fPIC

No

> or how can I get a new static lib with -fPIC?

I guess next command will do the trick:

```shell
make clean # since we do not check `CFLAGS` changes
CFLAGS=-fPIC make -j V=1
```

And use `V=1` to verify that there is `-fPIC` flag, but if you are using 2.0.x then I think you do not need it, since it is not quiet by default.

**Comment by azat** [comment]
Closing it for now, feel free to reopen if you still have questions
