### ISSUE TITLE
how to set the proper low watermark parameter for bufferevent_setwatermark

### ISSUE THREAD

**Issue by danielstock** [libevent/libevent#754]
because of the poor banwidth or other reason, one single client packet , (for example, 80 bytes in all )  might arrive in two stages,  first 70 bytes, and then 10 bytes.
if i set the  low watermark as 20 bytes,  the first arrived 70 bytes will trigger the read callback, what about the left 10 bytes?
the read callback would not be triggered until new packet comes?

**Comment by azat** [comment]
> the read callback would not be triggered until new packet comes?

Yes, the read callback will not be triggered until another 70 bytes will be available.

And I would say that this is not the case for low watermarks, are you sure you need it here?

**Comment by danielstock** [comment]
@azat  thanks.   then what's the default low watermark?
is it 0?  so that the read callback would be invoked when there is data available.

**Comment by azat** [comment]
> is it 0?

Yep

**Comment by danielstock** [comment]
@azat   thanks
