### ISSUE TITLE
Signed release archive does not contain cmake build files (release 2.1.8 and 2.0.23)

### ISSUE THREAD

**Issue by smarek** [libevent/libevent#755]
This issue is related to #551 which was closed back in 2017, however it seems that newer release 2.0.23 signed archive still doesn't contain cmake files

Would it be possible for maintainers to re-release the signed archives with cmake files, without waiting for next release?

Thank you

**Comment by azat** [comment]
> 2.0.23

2.0.x will not contain cmake rules, since 2.0.x never had cmake support (and it can be not that simple to backport it, plus everyone who uses 2.0.x should consider using 2.1.x)

> Would it be possible for maintainers to re-release the signed archives with cmake files, without waiting for next release?

For me release archive should me immutable, but right now I'm working on 2.1.9-beta, and it will contain cmake rules.

**Comment by smarek** [comment]
Ok, thank you for clarification, as I'd like to integrate stable release, you can, with explanation, release the archive with different name under the same github release (ie. libevent-2.1.8-stable-cmake.tar.gz + libevent-2.1.8-stable-cmake.tar.gz.asc)

What do you think?

**Comment by azat** [comment]
> What do you think?

I don't like this idea too much, since it requires extra testing anyway

> I'd like to integrate stable release

Well, 2.1.9 will be beta, but if there will be no problems reported for a 2-4 weeks, I will be glad to release 2.1.10-stable. Does this sound good for you?

**Comment by smarek** [comment]
Cool, thank you!
