### ISSUE TITLE
cmake-vs-autotools

### ISSUE THREAD

**Issue by azat** [libevent/libevent#760]
- [ ] `libevent-2.2` VS `libevent.2.2` (`-version-info` and `-release`) (#838)
- [x] include/event2/bufferevent_ssl.h is conditionally installed by cmake but not autotools (5388a002f5ad3bdfc756584dc58485fc3db135d0)

**Comment by jbeich** [comment]
- `include/event2/bufferevent_ssl.h`  is conditionally installed by cmake but not autotools

**Comment by azat** [comment]
> include/event2/bufferevent_ssl.h is conditionally installed by cmake but not autotools

Fixed in 5388a002f5ad3bdfc756584dc58485fc3db135d0, thanks!
