### ISSUE TITLE
libevent2 http server detecting client close

### ISSUE THREAD

**Issue by ideawu** [libevent/libevent#78]
I write a simple web server that handles long-polling, which means the server doesn't send a full HTTP response to the client(web browser, curl, etc), but only sends HTTP headers and hang the connection.

I use command line curl to product a request to the server, it prints out HTTP response headers well, and curl hangs as expected. Then I press CTRL+C to terminate the curl process. But the server never knows this close(on_disconnect() is never called).

Some of the codes:

```
void request_handler(struct evhttp_request *req, void *arg){
    // only send response headers, and one piece of chunked data
    evhttp_send_reply_start(req, HTTP_OK, "OK");
    evbuffer_add_printf(buf, "...\n");
    evhttp_send_reply_chunk(req, buf);
    // register connection close callback
    evhttp_connection_set_closecb(req->evcon, on_disconnect, sub);
}

void on_disconnect(struct evhttp_connection *evcon, void *arg){
    printf("disconnected\n");
}

evhttp_set_gencb(http, request_handler, NULL);
```

**My question is, how to detect this kind of client close(a TCP FIN received)? Is this a bug?**

------------------

Someone tells:

> When evhttp_read_header() in libevent's http.c is done reading the HTTP headers from the client, it disables any future read events by calling bufferevent_disable(..., EV_READ). However, read events need to be enabled for the underlying bufferevent to report EOF. That's why the bufferevent never tells libevent's HTTP code when the client closes the connection. - http://stackoverflow.com/questions/18743948/libevent2-http-server-how-to-detect-client-close/18776728?noredirect=1#18776728

**Comment by azat** [comment]
Hi @ideawu 

You can just try to write to that socket and you will get an error, however I think that this is not correct to do so (i.e. try to write to detect EOF), so I prepared 2 patches (regression test and a patch for http layer) that must this issue, but I need more time to dig into this deeper (to validate that this patch will not give side-effects).

**Comment by ideawu** [comment]
According to the answer on StackOverflow, re-enable EV_READ on the connection works:

```
bufferevent_enable(req->evcon->bufev, EV_READ);
```

**Comment by azat** [comment]
I'm talking about fixing this in libevent, I don't think that this will cause any regression.
