### ISSUE TITLE
Libevent won't build

### ISSUE THREAD

**Issue by sntdevco** [libevent/libevent#783]
I'm trying to build libevent and I keep getting an error with the Makefile:
**make: *** No rule to make target 'Makefile.am'. needed by 'Makefile.in'. Stop.**
System information:
- Ubuntu 18.04.2 LTS
- Kernel Version: 4.15.0-45-generic
- gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
- **Trying to build:** 2.1.8-stable (downloaded from releases)

Any resolution?

**Comment by azat** [comment]
You need to run `./configure`, more details [in readme](https://github.com/libevent/libevent/tree/5ee507c889b019e9296f48e4f133c439e3040c9e#1-building-and-installation-in-depth)

**Comment by azat** [comment]
*(And please do not post screenshots over plain text)*

**Comment by sntdevco** [comment]
> _(And please do not post screenshots over plain text)_

Will take care the next time 😨 
> You need to run `./configure`, more details [in readme](https://github.com/libevent/libevent/tree/5ee507c889b019e9296f48e4f133c439e3040c9e#1-building-and-installation-in-depth)

I have already done that, but I still get this error

**Comment by azat** [comment]
>I have already done that, but I still get this error

This was irrelevant (my mistake).

By some reason you do not have `Makefile.am`, and this is the file that we have in git, so maybe you removed it manually? And where did you get this archive?

AFAIR you are trying to compile 2.1.8-stable (since you replaced the screenshot with the text, while the later do not contain this information, so correct me if I'm wrong), and I just verified the 2.1.8-stable archive and it is there:

```
wget -q -O- https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz | tar -ztf- | fgrep Makefile.am
libevent-2.1.8-stable/Makefile.am
```

**Comment by sntdevco** [comment]
> By some reason you do not have `Makefile.am`, and this is the file that we have in git, so maybe you removed it manually? And where did you get this archive?
> 
> AFAIR you are trying to compile 2.1.8-stable (since you replaced the screenshot with the text, while the later do not contain this information, so correct me if I'm wrong), and I just verified the 2.1.8-stable archive and it is there
I have downloaded it again from GitHub, I ran ./configure and then make but I still get the same error, what could be wrong? I am not deleting any Makefiles but I still get this error

**Comment by sntdevco** [comment]
I don't know why, but it's pretty funny that libevent built and installed now, after the 5th time I downloaded it from GitHub. I'm guessing the download wasn't successful. It's good and running now :smile:
