### ISSUE TITLE
Someone has the same core information??

### ISSUE THREAD

**Issue by jacksu** [libevent/libevent#790]
(gdb) bt
#0 0x000000000043ce8b in htparser_run ()
#1 0x00000000004358f5 in htp__connection_readcb_ ()
#2 0x00007f5a10d6c24c in bufferevent_run_deferred_callbacks_locked (cb=Unhandled dwarf expression opcode 0xf3
) at bufferevent.c:149
#3 0x00007f5a10d7611f in event_process_active_single_queue (base=0x2be3b650, activeq=0x2d975020, max_to_process=2147483647, endtime=0x0) at event.c:1675
#4 0x00007f5a10d76bef in event_process_active (base=0x2be3b650, flags=0) at event.c:1738
#5 event_base_loop (base=0x2be3b650, flags=0) at event.c:1961
#6 0x000000000040c365 in main (argc=Unhandled dwarf expression opcode 0xf3
) at ors/ranker.cc:74

**Comment by azat** [comment]
This one looks like [evhtp](https://github.com/criticalstack/libevhtp)
