### ISSUE TITLE
problem build with mingw

### ISSUE THREAD

**Issue by 18959263172** [libevent/libevent#800]
Hi guys,I build libevent on mingw and msys2,and When I try to link the .a file,It report a  error,
D:/projects/cUtils/./libevent/lib\libevent.a(evutil.c.obj):evutil.c:(.text+0xda4): undefined reference to `gai_strerrorA'

my libevent version is 2.1.9

**Comment by 18959263172** [comment]
the cmakeFiles I use as below:

cmake_minimum_required(VERSION 3.12)
project(cUtils)
find_library(WS2_32_LIBRARY ws2_32)

set(CMAKE_CXX_STANDARD 11)
include_directories(./libevent/include)
link_directories(./libevent/lib)
link_libraries(libevent.a libevent_core.a libevent_extra.a)
#include_directories()
add_executable(cUtils main.cpp debug.cpp window.cpp window.h Base.h)
message(info ${WS2_32_LIBRARY})
target_link_libraries(cUtils ${WS2_32_LIBRARY})

**Comment by azat** [comment]
Can you try to move `target_link_libraries(cUtils ${WS2_32_LIBRARY})` before `link_libraries(libevent.a libevent_core.a libevent_extra.a)`?

And also please share verbose make output.

**Comment by 18959263172** [comment]
D:/projects/cUtils/./libevent/lib\libevent.a(evutil.c.obj):evutil.c:(.text+0xda4): undefined reference to `gai_strerrorA'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[3]: *** [CMakeFiles\cUtils.dir\build.make:119: cUtils.exe] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:72: CMakeFiles/cUtils.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:84: CMakeFiles/cUtils.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:117: cUtils] Error 2

the output is

**Comment by 18959263172** [comment]
and I try remove WS_32 link in front of  libevent,it does'n help

**Comment by azat** [comment]
That is not verbose output, verbose output should contain executed commands

Try one of the following-
- `make V=1`
- `make VERBOSE=1`

**Comment by 18959263172** [comment]
my platfowm is win7 64bit

**Comment by azat** [comment]
Hm, I don't see any `-l<lib>` in this output, I need to see the order of the passed libraries, since the libraries should be searched. From gcc man:

           It makes a difference where in the command you write this option; the linker searches and processes libraries and object files in the order they are specified.  Thus, foo.o -lz bar.o searches library z after file foo.o but before bar.o.  If bar.o refers to
           functions in z, those functions may not be loaded.


> link_libraries(libevent.a libevent_core.a libevent_extra.a)

Also you should pass library names to `link_libraries()`, i.e. `event_core` instead of `libevent_core.a`

Can you try to link against `.dll`s and see if this will make difference for you?

**Comment by 18959263172** [comment]
thank you ,I change 
`link_libraries(libevent.a libevent_core.a libevent_extra.a)`
to 
`target_link_libraries(cUtils event event_core  event_extra)`
and it could be built,but it crashed when I run it,and just report 
During startup program exited with code 0xc0000135.

**Comment by 18959263172** [comment]
I only call event_base_new() for test 
` struct event_base *base;
    struct evconnlistener *listener;
    struct event *signal_event;
    struct sockaddr_in sin;

    Cpp11Test tst;

    vector <Cpp11Test> vTest;

    base = event_base_new();
    if (!base) {
        fprintf(stderr, "Could not initialize libevent!\n");
        return 1;
    }
    for (auto v : vTest){

    }`

**Comment by 18959263172** [comment]
sloved,I remove the dll it needed to the build folder and it worked
