### ISSUE TITLE
evhttp accept no client in ios when unlock the screen

### ISSUE THREAD

**Issue by nobody0101** [libevent/libevent#808]
I write a local http server, and it works, but when I try this, bug happened, the step is:
1. open app 
2. request local http server is ok
3. lock the iphone screen
4. unlock iPhone again and request local http server
5. nothing happened, no socket accept again, no request received!
by the way, timer event also find , bug the evhttp is not ok, the code is :

```c

int httpserver_start(int port, int nthreads, int backlog) {
    int r;
    signal(SIGPIPE, SIG_IGN);
    evthread_use_pthreads();
    int nfd = httpserver_bindsocket(port, backlog);
    if (nfd < 0) return -1;
    pthread_t ths[nthreads];
    for (int i = 0; i < nthreads; i++) {
        struct event_base *base = event_init();
        if (base == NULL) return -1;
        struct evhttp *httpd = evhttp_new(base);
        if (httpd == NULL) return -1;
        r = evhttp_accept_socket(httpd, nfd);
        if (r != 0) return -1;
        evhttp_set_gencb(httpd, httpserver_GenericHandler, NULL);
        r = pthread_create(&ths[i], NULL, httpserver_Dispatch, base);
        if (r != 0) return -1;
        pthread_detach(ths[i]);
    }
    return 0;
}

void* httpserver_Dispatch(void *arg) {
    // timer event always ok
    event_assign(&timeoutBreak, (struct event_base*)arg,
                 -1, EV_PERSIST, heart_event_timeout_cb, arg);
    struct timeval tv;
    evutil_timerclear(&tv);
    tv.tv_usec = 0;
    tv.tv_sec = 2;
    event_add(&timeoutBreak, &tv);
    // net event
    event_base_dispatch((struct event_base*)arg);
    return NULL;
}

void httpserver_GenericHandler(struct evhttp_request *req, void *arg) {
   // bug:  not call when iPhone unlock again
}

int httpserver_bindsocket(int port, int backlog) {
    int r;
    int nfd;
    nfd = socket(PF_INET, SOCK_STREAM, 0);
    if (nfd < 0) return -1;
    evutil_make_socket_nonblocking(nfd);
    evutil_make_listen_socket_reuseable(nfd);
    evutil_make_listen_socket_reuseable_port(nfd);
//    int one = 1;
//    r = setsockopt(nfd, SOL_SOCKET, SO_REUSEADDR, (char *)&one, sizeof(int));
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(port);
    socklen_t addrlen = sizeof(addr);
    r = ::bind(nfd, (struct sockaddr*)&addr, addrlen);
    if (r < 0) return -1;
    r = listen(nfd, backlog);
    if (r < 0) return -1;
//    int flags;
//    if ((flags = fcntl(nfd, F_GETFL, 0)) < 0 ||
//        fcntl(nfd, F_SETFL, flags | O_NONBLOCK) < 0)
//        return -1;
    return nfd;
}

```

thank you

**Comment by nobody0101** [comment]
anybody knows?

**Comment by azat** [comment]
Hi!

>event_init()

while calling event_init() will give you want you want this is deprecated API, and you should use event_base_new() instead

>evutil_make_listen_socket_reuseable_port()

right now it is a no-op on non-linux (and it is a bug in libevent, will fix it later today).
but this should not affect your case, since you do not bind multiple sockets to one addr:port
(calling accept() for one fd from multiple threads without any options)

> timer event always ok

I guess that if something wrong will happen there then event loop will not be stopped because of the timer, but this is not the root cause just consequences


>evhttp accept no client in ios when unlock the screen

sounds like ios/osx issue not the libevent

does osx has something like strace (linux) or dtruss (osx)? if so, can you attach with it to the program and take a look what happends after lock/unlock?

**Comment by nobody0101** [comment]
thank you for reply, I write a simple Event lib to test this problem, and result is the same, so, it is iOS issue, I don't know what happened, it looks like kqueue had clean the event, when unlock the iPhone, I add an accept event, it still not work, until I restart the http local server
by the way, I will check this problem on osx later
