### ISSUE TITLE
AF_UNIX since windows10

### ISSUE THREAD

**Issue by azat** [libevent/libevent#814]
https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

**Comment by ygj6** [comment]
Indeed, UNIX domain socket can be used on Win10. 
I only found that it can be used in the `evutil_ersatz_socketpair_` function:
https://github.com/ygj6/libevent/commit/f1a5df06a9d4852bc8314d14c1bf178b16ecd0ab

**Comment by ygj6** [comment]
Indeed, UNIX domain socket can be used on Win10.
I only found that it can be used in the evutil_ersatz_socketpair_ function:
https://github.com/ygj6/libevent/commit/7353356a54d23f316e404b840a0f095d2cdac5f2

After applying this patch, the test case `regress listener error` in `regress_listener.c` failed. The reason is that the AF_UNIX file descriptor is passed to the `evconnlistener_new` function. I think it need some repairs.

**Comment by ygj6** [comment]
Now, I don't think it's necessary to check `afunix.h` in `configure.ac`. I removed it and only kept the cmake-checking part.
Here is the new patch: https://github.com/ygj6/libevent/commit/25379fdc3faf28efbfc0698c6b55ba88af06eee8
@azat Is it ok? could you give me some ideas?

**Comment by ygj6** [comment]
Besides,  the testcase `regress_listener_error` in `regress_listener.c` failed, the backtrace is:
```
regress_listener_error() -> regress_listener.c
evconnlistener_new() -> listener.c
evconnlistener_new_async()
new_accepting_socket()
```
`new_accepting_socket()` does't support `AF_UNIX`, see this:
```
if (family == AF_INET)
	addrlen = sizeof(struct sockaddr_in);
else if (family == AF_INET6)
	addrlen = sizeof(struct sockaddr_in6);
else
	return NULL;
```
Therefore, I disabled this testcase on Win10

**Comment by azat** [comment]
>@azat Is it ok?

Can you please send this as a PR, to have CI runs on it (since I don't like to run windows vms)

>new_accepting_socket() does't support AF_UNIX, see this:

So, can you fix new_accepting_socket() ? That will be useful feature I guess

**Comment by azat** [comment]
>Now, I don't think it's necessary to check afunix.h in configure.ac

Indeed

**Comment by azat** [comment]
>could you give me some ideas?

Looked briefly and everything looks good, but listener support for the AF_UNIX on windows will be great!
