### ISSUE TITLE
"Cannot find source file: WIN32-Code/getopt.c" in release-2.1.9-beta

### ISSUE THREAD

**Issue by YihaoPeng** [libevent/libevent#815]
I tried to build v2.1.9-beta in Windows, but got the following error:
```
CMake Error at CMakeLists.txt:932 (add_executable):
   Cannot find source file:
     WIN32-Code/getopt.c
```

I think this is because the following files are missing:

`cd WIN32-Code`
`wget https://raw.githubusercontent.com/libevent/libevent/master/WIN32-Code/getopt_long.c https://raw.githubusercontent.com/libevent/libevent/master/WIN32-Code/getopt.h https://raw.githubusercontent.com/libevent/libevent/master/WIN32-Code/getopt.c`

I downloaded them manually and built libevent successfully.

**Comment by azat** [comment]
Thanks for reporting this! Next release (2.1.10) will contain those files (will send a patch in a couple of hours)
