### ISSUE TITLE
in windows, there is 12ms delay with libevent-master version

### ISSUE THREAD

**Issue by nickeylau** [libevent/libevent#817]
in windows, there is 12ms delay with libevent-master version
![image](https://user-images.githubusercontent.com/33596170/57903606-57d2a080-78a1-11e9-9fdb-39bd0996bd42.png)

in release-2.0.21-stable, it is well.
![image](https://user-images.githubusercontent.com/33596170/57903720-de877d80-78a1-11e9-857d-b79cf3b506fd.png)

time-test.c

```c
#include <sys/types.h>

#include <event2/event-config.h>

#include <sys/stat.h>
#ifndef _WIN32
#include <sys/queue.h>
#include <unistd.h>
#endif
#include <time.h>
#ifdef EVENT__HAVE_SYS_TIME_H
#include <sys/time.h>
#endif
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>

#include <event2/event.h>
#include <event2/event_struct.h>
#include <event2/util.h>

#ifdef _WIN32
#include <winsock2.h>
#endif

struct timeval lasttime;

int event_is_persistent;

static void
timeout_cb(evutil_socket_t fd, short event, void *arg)
{
	struct timeval newtime, difference;
	struct event *timeout = arg;
	double elapsed;

	evutil_gettimeofday(&newtime, NULL);
	evutil_timersub(&newtime, &lasttime, &difference);
	elapsed = difference.tv_sec +
	    (difference.tv_usec / 1.0e6);

	printf("timeout_cb called at %d: %.3f seconds elapsed.\n",
	    (int)newtime.tv_sec, elapsed);
	lasttime = newtime;

	if (! event_is_persistent) {
		struct timeval tv;
		evutil_timerclear(&tv);
		tv.tv_sec = 2;
		event_add(timeout, &tv);
	}
}

int
main(int argc, char **argv)
{
	struct event timeout;
	struct timeval tv;
	struct event_base *base;
	int flags;

#ifdef _WIN32
	WORD wVersionRequested;
	WSADATA wsaData;

	wVersionRequested = MAKEWORD(2, 2);

	(void)WSAStartup(wVersionRequested, &wsaData);
#endif

	if (argc == 2 && !strcmp(argv[1], "-p")) {
		event_is_persistent = 1;
		flags = EV_PERSIST;
	} else {
		event_is_persistent = 0;
		flags = 0;
	}

	/* Initalize the event library */
	base = event_base_new();

	/* Initalize one event */
	event_assign(&timeout, base, -1, flags, timeout_cb, (void*) &timeout);

	evutil_timerclear(&tv);
	tv.tv_sec = 2;
	event_add(&timeout, &tv);

	evutil_gettimeofday(&lasttime, NULL);

	event_base_dispatch(base);

	return (0);
}
```

**Comment by azat** [comment]
Hi!

> in windows, there is 12ms delay with libevent-master version

I cannot confirm this (tested 2.0.23, 2.0.21 and upstream)
Can you share more details on your build environment and command that had been used for building libevent?

> time-test.c

Just a [link](https://github.com/libevent/libevent/blob/3b1864b625ec37c3051512845982f347f4cc5621/sample/time-test.c) to the source file was enough

**Comment by nickeylau** [comment]
thks for reply!
environment: window7 debug x64
git clone https://github.com/libevent/libevent.git
replace the code of 'test/test_time.c' with time-test.c

cd libevent
md build
cd build
cmake -G "Visual Studio 12 Win64" -DEVENT__DISABLE_OPENSSL=ON -DEVENT__DISABLE_OPENSSL=STATIC ..

then use visual studio build libevent.sln,  start /test/test-time.exe, 
the interval time is 2 seconds, there is 12 delay 

![image](https://user-images.githubusercontent.com/33596170/58331701-458dcf00-7e6c-11e9-9848-e7c4d07b5545.png)

---------------------------------------------------------------------------------
then i fetch the veriosn of 2.0.21-stable, and build with command:
nmake /f Makefile.nmake,  
start /test/test-time.exe, it is well

**Comment by nickeylau** [comment]
I find a change in version 2.1.2-alpha (18 Nov 2012)
o Implement a GetTickCount-based monotonic timer for Windows (d5e1d5a)

![image](https://user-images.githubusercontent.com/33596170/58395358-4dbb5980-807a-11e9-9c2a-df91d28566c0.png)

GetTickCount does not have good precision if i tries to debug timings. It could have 1 or even 10 ms precision.
I have a try with _ftime or QueryPerformanceCounter/QueryPerformanceFrequency on windows.

**Comment by azat** [comment]
Hm, interesting, but when I measured this I had the same delays for the 2.0.x.
Can you share some numbers?

**Comment by nickeylau** [comment]
i try to revert the function gettime in event.c to the 2.0.21-stable, it will be ok.

static int
gettime(struct event_base *base, struct timeval *tp)
{

EVENT_BASE_ASSERT_LOCKED(base);

	if (base->tv_cache.tv_sec) {
		*tp = base->tv_cache;
		return (0);
	}

#if defined(_EVENT_HAVE_CLOCK_GETTIME) && defined(CLOCK_MONOTONIC)
	if (use_monotonic) {
		struct timespec	ts;

		if (clock_gettime(CLOCK_MONOTONIC, &ts) == -1)
			return (-1);

		tp->tv_sec = ts.tv_sec;
		tp->tv_usec = ts.tv_nsec / 1000;
		if (base->last_updated_clock_diff + CLOCK_SYNC_INTERVAL
		    < ts.tv_sec) {
			struct timeval tv;
			evutil_gettimeofday(&tv,NULL);
			evutil_timersub(&tv, tp, &base->tv_clock_diff);
			base->last_updated_clock_diff = ts.tv_sec;
		}

		return (0);
	}
#endif

	return (evutil_gettimeofday(tp, NULL));
}

![image](https://user-images.githubusercontent.com/33596170/58423565-02c83300-80c8-11e9-8000-ffd1216791c9.png)

**Comment by nickeylau** [comment]
i try to revert the function gettime in event.c to the 2.0.21-stable, it will be ok.

static int
gettime(struct event_base *base, struct timeval *tp)
{

EVENT_BASE_ASSERT_LOCKED(base);

	if (base->tv_cache.tv_sec) {
		*tp = base->tv_cache;
		return (0);
	}

#if defined(_EVENT_HAVE_CLOCK_GETTIME) && defined(CLOCK_MONOTONIC)
	if (use_monotonic) {
		struct timespec	ts;

		if (clock_gettime(CLOCK_MONOTONIC, &ts) == -1)
			return (-1);

		tp->tv_sec = ts.tv_sec;
		tp->tv_usec = ts.tv_nsec / 1000;
		if (base->last_updated_clock_diff + CLOCK_SYNC_INTERVAL
		    < ts.tv_sec) {
			struct timeval tv;
			evutil_gettimeofday(&tv,NULL);
			evutil_timersub(&tv, tp, &base->tv_clock_diff);
			base->last_updated_clock_diff = ts.tv_sec;
		}

		return (0);
	}
#endif

	return (evutil_gettimeofday(tp, NULL));
}

![image](https://user-images.githubusercontent.com/33596170/58423565-02c83300-80c8-11e9-8000-ffd1216791c9.png)


> Hm, interesting, but when I measured this I had the same delays for the 2.0.x.
> Can you share some numbers?

**Comment by azat** [comment]
Have you tried `EVENT_BASE_FLAG_PRECISE_TIMER`?
(or set `EVENT_PRECISE_TIMER` env var)

```
/** Ordinarily, Libevent implements its time and timeout code using
    the fastest monotonic timer that we have.  If this flag is set,
    however, we use less efficient more precise timer, assuming one is
    present.
 */

```

**Comment by nickeylau** [comment]
@azat it`s effective, thanks!

**Comment by azat** [comment]
Great!
