### ISSUE TITLE
libevent crashed at the evhttp_clear_headers（） in android device

### ISSUE THREAD

**Issue by zealda** [libevent/libevent#818]

**Comment by zealda** [comment]
I use http api for httpclient，and i found an crash on evhttp_clear_headers or EVUTIL_TOLOWER_ when it is on the online env. the cash rate at 0.01%. special used is that ,i will evhttp_connection_free the connnection at chunk_cb or done_cb, wherther someone meet this ?, the crash stack:

EVUTIL_TOLOWER_
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/evutil.c:2313
evhttp_find_header
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:1857
evhttp_is_connection_close
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:466
evhttp_is_request_connection_close
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:475
bufferevent_readcb
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/bufferevent_sock.c:221
event_process_active_single_queue
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/event.c:1647
event_process_active
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/event.c:1742
client_download_manager
/root/work/p2p/release/douyu/1.2.36/android/jni/../../proxy/download.c:434


evhttp_clear_headers
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:1872 (discriminator 1)
evhttp_request_free
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:3991
evhttp_connection_done
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:860
evhttp_read_body
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:1039
evhttp_get_body
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/http.c:2228
bufferevent_trigger_nolock_
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/bufferevent-internal.h:411
bufferevent_readcb
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/bufferevent_sock.c:212
event_process_active_single_queue
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/event.c:1647
event_process_active
/root/work/p2p/release/douyu/1.2.36/android/jni/../../libp2p/../android/extern/libevent/event.c:1742
client_download_manager
/root/work/p2p/release/douyu/1.2.36/android/jni/../../proxy/download.c:434

**Comment by azat** [comment]
Hi!

>wherther someone meet this ?

This should not happens of course.

So here are some questions to begin with:
- Which version of libevent do you use?
- Can you run program under valgrind?

**Comment by azat** [comment]
@zealda can you provide details from the comment above?
