### ISSUE TITLE
windows cmake build errors - no found some libraries, functions, macros

### ISSUE THREAD

**Issue by SC5Shout** [libevent/libevent#819]
Hi, I cannot build the library on windows, because there are not found libraries, functions and macros like 

`-- Looking for sys/devpoll.h - not found`
`-- Looking for getaddrinfo - not found`

and this error:

```cpp
CMake Error at C:/Users/Michał/Desktop/cmake-3.14.4-win64-x64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Users/Michał/Desktop/cmake-3.14.4-win64-x64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/Michał/Desktop/cmake-3.14.4-win64-x64/share/cmake-3.14/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  CMakeLists.txt:814 (find_package)
```

my build settings
open cmd
`cd libevent-master/build`
`cmake -G "visual studio 16 2019" libevent-master`

how can I build it properly?

**Comment by azat** [comment]
Hi!

> -- Looking for sys/devpoll.h - not found
> -- Looking for getaddrinfo - not found

This is not a problem, we just detect if we have this functions (on all platforms) and if not we provide our own (for getaddrinfo case) and ignore one or more libevent backends (devpoll case).

>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
 > OPENSSL_INCLUDE_DIR)

And this is a problem, as the message says you should set OPENSSL_ROOT_DIR (`cmake -DOPENSSL_ROOT_DIR=/path/to/openssl-root`).

But also you can turn off openssl support (if you do not have openssl library installed), like this `cmake -DEVENT__DISABLE_OPENSSL=OFF`

**Comment by azat** [comment]
Closing for now, please reopen if you still cannot compile
