### ISSUE TITLE
System with 4000 to 8000 interfaces using libevent evdns will have slow resolve performance

### ISSUE THREAD

**Issue by jeremyerb** [libevent/libevent#834]
On a system with 4000 interfaces, or more, libevent evdns will have rather poor resolve performance.  Function, evdns_getaddrinfo calls evutil_adjust_hints_for_addrconfig_, which will call evutil_check_interfaces,

This should be only done once, but have_checked_interfaces is never set to true.    So every time we will try to get all IP addreses for all interfaces, which on most systems goes un-notices, except for systems with 4000+ interfaces with 4000+ IP addresses.

In evutil_adjust_hints_for_addrconfig_, it maybe a good idea to set have_checked_interfaces=1, after we call evutil_check_interfaces.

**Comment by jeremyerb** [comment]
Here is a little test script to create a bunch of VLAN tagged interfaces, and bridge them together.  You will require eth6 and eth7, modify how you desire.  Even without adding an IP Address to any of these interfaces the problem will exhibit itself.


for ((i=1000; $i<3000; i++)); do
        ip link add link eth6 name eth6.$i type vlan id $i
        ip link add link eth7 name eth7.$i type vlan id $i
        brctl addbr br$i
        brctl addif br$i eth6.$i
        brctl addif br$i eth7.$i
done

**Comment by azat** [comment]
> but have_checked_interfaces is never set to true

Nice catch! Do you want to send a patch? Or I can fix this by myself of course.

**Comment by jeremyerb** [comment]
Created a pull request that will flag the have_checked_interfaces to true.  I was thinking it maybe better to also check that either have_ipv4 or have_ipv6 are true before we set this, but I think that logic gets complicated.   User code can call the check interfaces with the force_check if they expect the system interfaces or IP stack to change.
