### ISSUE TITLE
libevent for normal file io

### ISSUE THREAD

**Issue by Tigerly** [libevent/libevent#835]
I'm a beginner of libevent, now I'm trying to response for a normal file's read/write status based on libevent. For example, if a normal file (test.txt) has been modified, it can trigger an event.
I try to get the file descriptor by using "fileno()" like:

```
fp=fopen("test.txt","r");

...

fd=fileno(fp);

event_set(&ev_test, fd, EV_READ|EV_PERSIST,on_test, NULL);

event_add(&ev_test, NULL);

event_dispatch();

...
```

When I run it, it always complains:
[warn] Epoll ADD(1) on fd 6 failed. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none): Operation not permitted.

My question is:
how can I use libevent for the normal file's I/O?

Thanks in advance!

**Comment by azat** [comment]
> [warn] Epoll ADD(1) on fd 6 failed. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none): Operation not permitted.

epoll/poll/.. does not support regular files, so the answer is "you cannot"

You can replace file with pipe and this will work, so suppose your program `a.out` accept file as a argument, you can use smth like this (in bash 4+) `a.out <(cat file.txt)` this will be translated to `a.out /dev/fd/63` (by bash) and `/dev/fd/63` is a pipe here (which will be written by bash).

Or you can use inotify `IN_MODIFY`
