### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by cmachacacordova** [libevent/libevent#837]
Goodnight.
I can not compile libevent in windows. I try to compile but the error appears:

C:\[HOME]\libevent-2.1.10-stable\buffer.c(3062): error C2065: 'PROT_READ': identificador no declarado [C:\[HOME]\libevent-2.1.10-stable\build\event_shared.vcxproj]
C:\[HOME]\libevent-2.1.10-stable\buffer.c(3069): error C2065: 'MAP_PRIVATE': identificador no declarado [C:\[HOME]\libevent-2.1.10-stable\build\event_shared.vcxproj]

I'm new to c ++ but I've been programming java for 3 years now.

Thank you.

**Comment by azat** [comment]
Hi!

Windows do not have mmap() and the code in question is guarded with `#if defined(EVENT__HAVE_MMAP)` so looks like you have `mmap()`

Can you share whole cmake build directory?
I.e.

```shell
mkdir build
cd build
cmake .. <opts>
```

And upload the `build` folder here (I guess that you env has some extra includes, that has mmap() definition)

**Comment by azat** [comment]
@cmachacacordova any news?

**Comment by azat** [comment]
Closing. @cmachacacordova feel free to reopen once you will have any news
