### ISSUE TITLE
README for libevent 

### ISSUE THREAD

**Issue by heaven-hq** [libevent/libevent#841]
When I downloaded the 2.1.8 version from the first Assert "libevent-2.1.8-stable.tar.gz"，opened  and found that there was no README file.

I thought there was no such file ,was going  to add it , later , very happy to find this file in the third and fourth assets ( Source code(zip) 、Source code(tar.gz) ).

Next，I checked version 2.1.10、2.1.9、2.1.5 ,etc ，had the same situation.

I wonder if the tool filters out the README file when packing libevent-x.x.x-stable.tar.gz, or does not pack the file based on other considerations?

**Comment by azat** [comment]
> or does not pack the file based on other considerations?

No, just nobody cares about this till now, will fix shortly, thanks for the report!
