### ISSUE TITLE
FindOpenSSL bug on cmake 3.1.0

### ISSUE THREAD

**Issue by ygj6** [libevent/libevent#845]
My platform is **MacOS 10.13.5**, This problem only happens on **Mac**.

As written in the file `CMakeLists.txt`, the minimum required version of cmake is 3.1 ：
```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
```
So I built this project with cmake-3.1.0, but I got the following errors:
```
CMake Error at /usr/local/cmake-3.1.0/share/cmake/Modules/FindOpenSSL.cmake:293 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:824 (find_package)


CMake Error at /usr/local/cmake-3.1.0/share/cmake/Modules/FindOpenSSL.cmake:294 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:824 (find_package)


CMake Error at /usr/local/cmake-3.1.0/share/cmake/Modules/FindOpenSSL.cmake:296 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:824 (find_package)


CMake Error at /usr/local/cmake-3.1.0/share/cmake/Modules/FindOpenSSL.cmake:298 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:824 (find_package)
```

I googled this error and got this answer:
https://bugs.archlinux.org/task/43688

It is a bug in FindOpenSSL.cmake on cmake-3.1.0 and fixed on cmake-3.1.2 .
Of course, It was successful when rebuilding with cmake-3.1.2 .
So I suggest setting the minimum version required for cmake to 3.1.2 or higher.

**Comment by azat** [comment]
@ygj6 hi!
Thanks for the great report!
Fixed in the referenced patch.
