### ISSUE TITLE
CMAKE failed for building static lib

### ISSUE THREAD

**Issue by deryck1031** [libevent/libevent#853]
Getting below cmake error when building static libraries:

**CMake Error:
  Error evaluating generator expression:
    $<TARGET_FILE_DIR:event_openssl_shared>
  No target "event_openssl_shared"
CMake Error:
  Error evaluating generator expression:
    $<TARGET_FILE_DIR:event_pthreads_shared>
  No target "event_pthreads_shared"**

`
    if (NOT WIN32)
        install(FILES
            "$<TARGET_FILE_DIR:${LIB_NAME}_shared>/${LIB_LINK_NAME}"
            DESTINATION "lib"
            COMPONENT lib)
    endif()
`

above code is looking for shared lib, so failed for static lib.

**Comment by ploxiln** [comment]
What version of what OS are you using? macOS 10.14? Ubuntu 18.04?
What version of cmake are you running?

**Comment by deryck1031** [comment]
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)

cmake version is 3.13.2

**Comment by azat** [comment]
669a53f3 breaks the build for static-only build, i.e. `cmake -DEVENT__LIBRARY_TYPE=static`, and I guess that @deryck1031 uses it.

The issue has been fixed in upstream, @deryck1031 can you please pull (or apply 55d1e20e manually) and confirm that it fixes the issue for you?

**Comment by deryck1031** [comment]
just tried the latest build.  no issue found.  Thank you very much...
