### ISSUE TITLE
There is a low probability that a NULL reference occurs.

### ISSUE THREAD

**Issue by heaven-hq** [libevent/libevent#855]
The evbuffer_add_cb function of the Buffer.c file is defined as follows:
```
struct evbuffer_cb_entry *
evbuffer_add_cb(struct evbuffer *buffer, evbuffer_cb_func cb, void *cbarg)
{
	struct evbuffer_cb_entry *e;
	if (! (e = mm_calloc(1, sizeof(struct evbuffer_cb_entry))))
		return NULL;
	EVBUFFER_LOCK(buffer);
	e->cb.cb_func = cb;
	e->cbarg = cbarg;
	e->flags = EVBUFFER_CB_ENABLED;
	LIST_INSERT_HEAD(&buffer->callbacks, e, next);
	EVBUFFER_UNLOCK(buffer);
	return e;
}

It has a very small probability of returning NULL.When evbuffer_setcb function called it,
I think it's better to have a null protection,or may have chance to cause NULL reference.
```
void
evbuffer_setcb(struct evbuffer *buffer, evbuffer_cb cb, void *cbarg)
{
	EVBUFFER_LOCK(buffer);

	if (!LIST_EMPTY(&buffer->callbacks))
		evbuffer_remove_all_callbacks(buffer);

	if (cb) {
		struct evbuffer_cb_entry *ent =
		    evbuffer_add_cb(buffer, NULL, cbarg);
		ent->cb.cb_obsolete = cb;
		ent->flags |= EVBUFFER_CB_OBSOLETE;
	}
	EVBUFFER_UNLOCK(buffer);
}
```
It's a small problem, because the chances of occurrence are too small, maybe it can be ignored.

**Comment by azat** [comment]
>I think it's better to have a null protection

Nice catch, indeed!

>It's a small problem, because the chances of occurrence are too small, maybe it can be ignored.

It shouldn't. Everything should be stable.

We will glad to accept a patch! Or you just want this to be fixed?

**Comment by azat** [comment]
P.S. this can be even tested by using custom memory allocation functions (see `event_set_mem_functions()`) via `test/regress_buffer.c`

**Comment by heaven-hq** [comment]
Thanks for the test suggestions . I am glad to send patch and contribute to community.
