### ISSUE TITLE
The sender sends the data too fast, and the buffer of the bufferevent receiver loses a small amount of data.

### ISSUE THREAD

**Issue by sclei** [libevent/libevent#864]
- Host environment: CentOS 6.7
- Libevent version: 2.1.10 stable  
- Client: webbrowser's websocket client ,java's websocket client

The client uses the 'for loop' to continuously send data to the server, and the bufferevent on the server triggers the read callback function. I separate the glued packets in the callback function. The basic principle is to use ‘evbuffer_copyout_from’ to pre-read the header of a packet without changing the contents of the input buffer. If the input buffer data is large enough for a packet size, I call ‘evbuffer_drain’ to remove the pre-read header portion and continue reading the real data portion.
When the client blocks a few milliseconds after each transmission cycle, each time it is sent, it will trigger a return function, and the data received by the server has no problem.
If I use the for loop on the client without adding a rate limit to continuously send data, the input buffer of the bufferevent of the server may lose some data.
The specific performance is: each time the callback function is executed, I receive a part of the data, including several packages, or sometimes add an incomplete package, but I only deal with the complete package, but leave the incomplete package to the next once. When the callback function finishes processing a complete package, I will look at the length of the input buffer. I will return immediately after a callback function is executed.**When a new callback function is executed, I find that no new data is read from the operating system for a long time. take. I am sure there is still data not being read, and the client did send it.** After the callback function returns for a while, the callback function will be called again, and **the data in the input buffer has some errors, only the data that was not read last time is correct.**  After analysis, some data is lost after the end of the data that was not read last time. **Is it necessary to read all the data of the last buffer before new data is read?**
I currently receive a long connection from a client in a single thread, and after processing a package, I use the thread pool to reply to the client. Event_base has use_pthreads enabled, bufferevent has ‘BEV_OPT_THREADSAFE | BEV_OPT_CLOSE_ON_FREE | BEV_OPT_DEFER_CALLBACKS’ enabled, and tried edge triggering and level triggering with the same effect;

**Comment by azat** [comment]
Hi!

> Is it necessary to read all the data of the last buffer before new data is read?

No.

Sounds like this can be reproduced without code around, can you provide a sample/reproducer?

P.S. and all known issues with evbuffer corruptions has been addressed up to 2.1.10, so you should not be affected by them.

**Comment by sclei** [comment]
I reused the evhttp 's fd in new  bufferevent and toke a mistake to call 'bufferevent_disabled' with 'NULL' as the second parameter ,  the old buffereventi race with the new to read the data left by the new bufferevent.
I have found the cause and fixed my code ,I will close this issue.
Thx for your reply and contribution!
