### ISSUE TITLE
Specify Python version

### ISSUE THREAD

**Issue by Devious2** [libevent/libevent#867]
I have two versions of Python  installed on RHEL how can i specify to use Python version 3

**Comment by ygj6** [comment]
You can simply make a symlink for python3
```
ln -s /path/to/your/python3 /usr/bin/python
```

Otherwise, you can set `PATH` environment variable:
```
export PATH=/path/to/your/python3:$PATH
```

**Comment by Devious2** [comment]
It is still giving me this `Could NOT find PythonInterp: Found unsuitable version "2.7.5", but required is at least "3" (found /usr/bin/python)`

**Comment by Devious2** [comment]
for sym link it is giving me `failed to create symbolic link ‘/usr/bin/python’: File exists`

**Comment by Devious2** [comment]
i am still a rookie to linux, Is there a way i can make changes in cmakelist.txt to make it accept Python3?

**Comment by azat** [comment]
Please post the output of:
- `python --version`
- `python3 --version`

**Comment by Devious2** [comment]
python --version  2.7.5
python3 --version 3.7.4

**Comment by azat** [comment]
Does `cmake -DPython_ADDITIONAL_VERSIONS=3` fixes it?

**Comment by azat** [comment]
And actually libevent supports python2 too, can you please post the whole log and which version of libevent do you have?

**Comment by Devious2** [comment]
libevent 2.1.11 i am using.

```
[root@rhel76_2 build]# /opt/cmake/bin/cmake -DPython_ADDITIONAL_VERSIONS=3 ..
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- OpenSSL include: /usr/local/ssl/include
-- OpenSSL lib: /usr/local/ssl/lib/libssl.a;/usr/local/ssl/lib/libcrypto.a
-- Could NOT find PythonInterp: Found unsuitable version "2.7.5", but required is at least "3" (found /usr/bin/python)
-- Generating regress tests...
CMake Error: File /home/testuser/LibeventLib/libevent-2.1.11-stable/cmake/Uninstall.cmake.in does not exist.
CMake Error at CMakeLists.txt:1501 (configure_file):
  configure_file Problem configuring file


--
--         ---( Libevent 2.1.11-stable )---
--
-- Available event backends: EPOLL;SELECT;POLL
-- CMAKE_BINARY_DIR:         /home/testuser/LibeventLib/libevent-2.1.11-stable/build
-- CMAKE_CURRENT_BINARY_DIR: /home/testuser/LibeventLib/libevent-2.1.11-stable/build
-- CMAKE_SOURCE_DIR:         /home/testuser/LibeventLib/libevent-2.1.11-stable
-- CMAKE_CURRENT_SOURCE_DIR: /home/testuser/LibeventLib/libevent-2.1.11-stable
-- PROJECT_BINARY_DIR:       /home/testuser/LibeventLib/libevent-2.1.11-stable/build
-- PROJECT_SOURCE_DIR:       /home/testuser/LibeventLib/libevent-2.1.11-stable
-- CMAKE_MODULE_PATH:        /home/testuser/LibeventLib/libevent-2.1.11-stable/cmake/
-- CMAKE_COMMAND:            /opt/cmake/bin/cmake
-- CMAKE_ROOT:               /opt/cmake/share/cmake-3.15
-- CMAKE_SYSTEM:             Linux-3.10.0-957.el7.x86_64
-- CMAKE_SYSTEM_NAME:        Linux
-- CMAKE_SYSTEM_VERSION:     3.10.0-957.el7.x86_64
-- CMAKE_SYSTEM_PROCESSOR:   x86_64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:             -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -Wstrict-prototypes -fno-strict-aliasing -Wmissing-prototypes -Winit-self -Wmissing-field-initializers -Wdeclaration-after-statement -Waddress -Wnormalized=id -Woverride-init -Wlogical-op -Wwrite-strings
-- CMAKE_BUILD_TYPE:         Release
-- CMAKE_C_COMPILER:         /usr/bin/cc (id GNU, clang 0, GNUC 1)
-- CMAKE_AR:                 /usr/bin/ar
-- CMAKE_RANLIB:             /usr/bin/ranlib
--
-- Configuring incomplete, errors occurred!

```

**Comment by Devious2** [comment]
> Does `cmake -DPython_ADDITIONAL_VERSIONS=3` fixes it?

No it does not

**Comment by azat** [comment]
>No it does not

Because it is not fatal error

>CMake Error: File /home/testuser/LibeventLib/libevent-2.1.11-stable/cmake/Uninstall.cmake.in does not exist.

This one is fatal, see #863 and #868

**Comment by Devious2** [comment]
sorry for my ignorance exactly what do i have to change?

**Comment by azat** [comment]
- Download [this archive](https://github.com/libevent/libevent/archive/release-2.1.11-stable.tar.gz)
- Clone the git repository, instead of downloading tarballs

**Comment by Devious2** [comment]
Thank you @azat

**Comment by Devious2** [comment]
Hi Azat, i am getting issue related to ```
Linking C executable bin/https-client
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
```
i have checked online i have to pass -ldl so is there a way to pass that while cmake ?

**Comment by azat** [comment]
This is not related to python version anyhow, let's discuss this on [gitter](https://gitter.im/libevent/libevent) and please use proper markdown or do not use it at all (since it is very hard to read such messages)
