### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by Devious2** [libevent/libevent#868]
CMake Error: File /home/testuser/LibeventLib/libevent-2.1.11-stable/cmake/Uninstall.cmake.in does not exist. ho

**Comment by azat** [comment]
Already fixed in #863 (and there is no new release with this fix yet, but you can use git)

P.S. Please [search the issue](https://github.com/libevent/libevent/issues?utf8=%E2%9C%93&q=uninstall+) before posting new one

**Comment by kishans12** [comment]
Thank you for prompt reply and sorry for the inconvenience caused.
