### ISSUE TITLE
Is it possible to call `bufferevent_write()` to write data immediately after a successful call to `bufferevent_socket_connect()`?

### ISSUE THREAD

**Issue by zfl9** [libevent/libevent#874]
After I successfully call the `bufferevent_socket_connect()` method, is it allowed to call `bufferevent_write()` immediately to write tcp data? Or, I have to wait until `event_cb`'s `BEV_EVENT_CONNECTED` is triggered before calling `bufferevent_write()` to write data?

Of course: I understand that a successful return of `bufferevent_socket_connect()` simply means that the tcp connection is in progress, but it does not mean that the connection has been established. But I want to know how inside bufferevent handles this situation? Look forward to your reply!

**Comment by zfl9** [comment]
Do I have to wait until event_cb's BEV_EVENT_CONNECTED event fires before I can call bufferevent_write()?

**Comment by azat** [comment]
No, you shouldn't, you can call bufferevent_write() at any time 

Actually it will just append data to buffer, and the buffer will be drained to fd once it will be possible

**Comment by zfl9** [comment]
So, after I create the bufferevent object, I can call bufferevent_write() to write the data at any time. No matter if the underlying connection is already established, libevent will send the data after the connection is established and writable, right?

**Comment by azat** [comment]
Yes

**Comment by zfl9** [comment]
thanks.
