### ISSUE TITLE
How to set underlying socket fd option when use evhttp

### ISSUE THREAD

**Issue by hhb1029** [libevent/libevent#875]
Hi，

I'm trying to use http.h for an http client. I use `bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE)` to new `struct bufferevent` with my own fd, so I can set fd option by `setsockopt`, however it seems doesn't work.

This fd set in `struct bufferevent` will be close when make connection by function `evhttp_connection_reset_`

https://github.com/libevent/libevent/blob/1c573ab3a9037c560981ea325170ca6044c2dff6/http.c#L1439-L1449

Is there any idea to set underlying fd option ？

**Comment by azat** [comment]
Right now there is no ability to do this cleanly.
There is #795 but there are some caveats.

**Comment by hhb1029** [comment]
Is it possible to trigger a callback before establishing a connection just like trigger `evcon->closecb` before close fd ?

**Comment by azat** [comment]
If you are asking about callback between `socket()` and `connect()`, than no, there is no such callback right now.

What socket options do you need?

**Comment by hhb1029** [comment]
I want to set `TCP_NODELAY` to turn off Nagle’s Algorithm. 

When I use `bufferevent_openssl_socket_new` for https test, I found http message will be sent separately from the http header and the http body. However the http server does not reply ack immediately after receiving the http header. The client does not send the http body until the server responds with ack after 40ms timeout.

This will affect the performance of the client, and I found turn off Nagle’s Algorithm can avoid this problem.

**Comment by luochen52** [comment]
@hhb1029 Hi, friend, I met the same problem as your's, my request sometime had 40ms+ delay, so, could you tell me that has you solved it or not, and if yes how to do? Thanks

**Comment by hhb1029** [comment]
@luochen52 I'm sorry, I didn't solve this problem, 40ms delay is acceptable in my project. You can use HTTP instead of HTTPS，this problem does not exist with HTTP.

**Comment by azat** [comment]
FWIW the problem with SSL can be fixed by pullup the buffer - 98b0b1e6004e572a0e96acf86947da1c4e5e02a8, I'm going to get back to this change in the nearest feature

**Comment by luochen52** [comment]
@hhb1029 @azat Thanks, I need HTTPS in my project but I'd like not to change ths source code of  libevent. I found an other way to solve this problem, I thought it works but not proved yet, I will be back here if it works. However, a new release version of libevent that solved this problem  is preferred.

**Comment by azat** [comment]
>This fd set in struct bufferevent will be close when make connection by function evhttp_connection_reset_

Removed in afa66ea4, see https://github.com/libevent/libevent/blob/afa66ea4200a018bfc59abef8c2ffa11ef2b8363/http.c#L2746-L2755

**Comment by azat** [comment]
>@hhb1029 @azat Thanks, I need HTTPS in my project but I'd like not to change ths source code of libevent. I found an other way to solve this problem, I thought it works but not proved yet, I will be back here if it works. However, a new release version of libevent that solved this problem is preferred.

@hhb1029 Added `BUFFEREVENT_SSL_BATCH_WRITE` in a490172d6938943ce5af81e147a64b3f14870144

**Comment by hhb1029** [comment]
@azat I got it!
