### ISSUE TITLE
complie error in windows with vs2017

### ISSUE THREAD

**Issue by ugenehan** [libevent/libevent#878]
compile version 2.1.10 is successful with command cmake -G "Visual Studio 15 2017" ,while errors have occured with version 2.1.11.
CMake Warning at CMakeLists.txt:1492 (message):
  The doxygen target will not support since doxygen command was not found!
/cmake/Uninstall.cmake.in does not exist.
CMake Error at CMakeLists.txt:1498 (configure_file):
  configure_file Problem configuring file

**Comment by azat** [comment]
Please take a look at https://github.com/libevent/libevent/issues/863#issuecomment-517917989

P.S. and please use the search before posting new issues
