### ISSUE TITLE
fd leak

### ISSUE THREAD

**Issue by zmldndx** [libevent/libevent#88]
libevent version: libevent-2.0.21-stable.tar.gz
thrift version: thrift-0.8.0.tar.gz
use very simple nonbloking server and related client, when client thread num is more than thread_num in server's thread_manager, and the network causes many receive timeout in client, it will cause fd leak.
I do not know whether it's my wrong usage or bug.

server code:

``` C++
    shared_ptr<aicidclickHandler> handler(new aicidclickHandler());
    shared_ptr<TProcessor> processor(new aicidclick::aicidclickProcessor(handler));
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());    
    shared_ptr<ThreadManager> threadManager = ThreadManager::newSimpleThreadManager(64); //thread num
    shared_ptr<PosixThreadFactory> threadFactory = shared_ptr<PosixThreadFactory> (new PosixThreadFactory());
    threadManager->threadFactory(threadFactory);
    threadManager->start();
    TNonblockingServer server(processor, protocolFactory, 18601, threadManager);
    try{
        server.serve();
    }
    catch(TException e){
        exit(-1);
    }
    return 0;

client code(thread function):
    boost::shared_ptr<TSocket> sock = boost::shared_ptr<TSocket>(new TSocket("10.0.2.21", 18601));
    sock->setConnTimeout(40);
    sock->setRecvTimeout(10); //make receive timeout
    sock->setSendTimeout(40);
    boost::shared_ptr<TTransport> transport = boost::shared_ptr<TFramedTransport>(new TFramedTransport(sock));
    boost::shared_ptr<TProtocol> protocol = boost::shared_ptr<TBinaryProtocol>(new TBinaryProtocol(transport));
    aicidclick::aicidclickClient client = aicidclick::aicidclickClient(protocol);
    idclick::AdResponse resp;
    while(1) {
        try {
            if (!transport->isOpen()) {
                transport->open();
            }
            client.GetAdResponse(resp, g_req);
        } catch (TException &tx) {
            FATAL("ERROR: %s", tx.what());
            transport->close();
        }
    }
    return NULL;
```

server threadmanager's thread num is 64, client's thread num is 120, call for a while, kill some client's thread, with a monitor to observ using "lsof |grep server|grep "can't identify protocol | wc -l" ", you'll find the number goes up and will not return to 0 if you killall client

**Comment by logicouter** [comment]
I have resolved this problem by increasing the number of io threads and worker threads.

**Comment by ellzey** [comment]
`usleep` is, and always will be __THE BIGGEST HACK EVER__ when it comes to socket IO.


How about nanosleep, OMG, that fixes it too! The reality is, at a sustained burst of data, check out top, and you will see lot's of processes in the D state. This is not a fix, this is a hack of hacks. If I still worked there and saw that, I would... Well I wouldn't do anything; I wasn't allowed to work on libevent..

My old coworker wrote an entire article on this after schooling her on this issue

https://medium.com/@fun_cuddles/opening-files-in-node-js-considered-harmful-d7de566d499f#.2k8z5v9a0

__SLEEP_IS_NEVER_THE_SOLUTION__
