### ISSUE TITLE
例子中的 http-connect 该传啥参数能起来呢。 

### ISSUE THREAD

**Issue by Goujay** [libevent/libevent#884]
我是这么传的http://localhost:9995/index.html http://localhost:9995/index.html

**Comment by Goujay** [comment]
![QQ截图20190822122204](https://user-images.githubusercontent.com/24580849/63485842-79ae7580-c4d7-11e9-806e-4c92fe14db72.png)

**Comment by azat** [comment]
Please write in English your question.

**Comment by heaven-hq** [comment]
@Goujay Suggest you upload a link that can be opened, and described in English.
