### ISSUE TITLE
ABI checker on CI

### ISSUE THREAD

**Issue by azat** [libevent/libevent#887]

**Comment by ygj6** [comment]
I came out of a solution for adding ABI checker on CI, but Step1, Step2, and Step3 may need your help. I can provide some code for Step4

Solution
Step1: We need a brand new git branch gh-pages for storing documents.
Step2: Use github to generate a personal access token, referencing: [generate token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line) 
	   Then use the personal access token to configure GITHUB_API_TOKEN on the Travis-ci configuration page for CI update abi_check results.
	   Reference: [travis settings](https://docs.travis-ci.com/user/environment-variables#defining-variables-in-repository-settings)
 Step3: Configure GitHub Pages, you can view the abi_check comparison result through url.
Step4: Modify [.travis.yml](https://github.com/ygj6/libevent/commit/90dfe09f2a1ef3cd3a53eb720c93f4b9a3815460) to add the abi_check tasks;
	   Add [abi_check.sh](https://github.com/ygj6/libevent/commit/05cd2ba9256e32355eef8a93c6eaef3f91bc17a6), which includes abi dependency installation and executable instructions to generate abi_check report;
	   Add [libevent.json](https://github.com/ygj6/libevent/commit/05cd2ba9256e32355eef8a93c6eaef3f91bc17a6) to provide libevent version configuration for abi_check.
	   
Usage
     1. Support triggering the abi-tracker task in CI when the source code of the master branch is modified
	 2. Support stand-alone usage of scripts and parameters, such as executing ./abi_check.sh, which by default compare the last three versions of the abi-tracker comparison results.

Result
The final result and can be viewed at [here](https://ygj6.github.io/libevent/abi-check/timeline/libevent/index.html)

**Comment by azat** [comment]
>Step1: We need a brand new git branch gh-pages for storing documents.

I don't like the idea of creating separate branch for this, and even though I don't see any possibility to overcome this for now, I want to be 100% sure that we cannot avoid this (I was thinking about separate repository). And personally I, want to integrate all this information to libevent.org website.

And actually I think that for now simply checking ABI compatibility and fail the pipeline will be enough (although it will be great to integrate this somewhere).

>Add abi_check.sh, which includes abi dependency installation and executable instructions to generate abi_check report;
>Add libevent.json to provide libevent version configuration for abi_check.

Great! I will take look anytime soon

> The final result and can be viewed at here

Nice!

**Comment by azat** [comment]
@ygj6 so I rebased your patch, and there is no packages for archlinux, so I will need sometime to add them, in the mean time can you take a look at does abi-monitor is required? I thought that we should pass versions from tags, no?

**Comment by ygj6** [comment]
> cp -r $(ls | grep -v ABI) ${ABI_CHECK_ROOT}/${ABI_CHECK_WORKSPACE}/src/libevent/current/

This line got an error.
The purpose of the original line is to copy the master branch into the `current` directory.
```
cp -r $(ls | grep -v ABI) ${ABI_CHECK_ROOT}/${ABI_CHECK_WORKSPACE}/src/libevent/current/
```
 The code in the `current` directory will be compiled to libraries that will be analyzed and compared to the latest version.
Now I think I don't need to exclude `ABI`.  Just copy all files to the `current` directory.
> drop package installations

By default, there are no required packages in travis CI. But if you don't plan to integrate it into travis, you can drop them.

> does abi-monitor is required

`abi-monitor -get ` is for downloading git branches
`abi-monitor -build ` is for compiling master and git branches
I think they are required.

**Comment by azat** [comment]
>This line got an error.

I didn't check it, but in my version there is `find`+`xargs`

>The purpose of the original line is to copy the master branch into the current directory.

Then why not just use `git archive`?

>By default, there are no required packages in travis CI. But if you don't plan to integrate it into travis, you can drop them.

I do plan, but they can be installed via `addons.apt` (and AFAICS mostly all of them are packaged by ubuntu and debian)

Besides even these packages won't be there, it is better to create [docker image (building at this moment, so not available yet)](https://hub.docker.com/r/iamazat/lvc-debian) instead of having these steps in the abi checker script, abi checking should be abi checking, no packages installing and configuration.

>abi-monitor -get is for downloading git branches

Why not simply `git checkout`?

When I played with this, I just used `abi-compliance-checker`.
We don't need the same reports as [here](https://abi-laboratory.pro/index.php?view=timeline&l=libevent), we simply need to check that it is abi compatible for now

**Comment by ygj6** [comment]
> Then why not just use git archive?

`git archive` does work, but you should perform an extra step to unzip the output file.

> but they can be installed via addons.apt

It's a good idea since travis supports `docker pull`.

> Why not simply git checkout?

`abi-monitor/abi-tracker` can do the same thing as `abi-dumper/abi-compliance-checker`. You can use either of these two combinations .  Sometimes, `abi-dumper/abi-compliance-checker` is more flexible and can give you more individualized results, even if more operations are needed. If use the latter, branches should be downloaded or git-checkout in advance.

In general, I agree with you.

**Comment by azat** [comment]
>git archive does work, but you should perform an extra step to unzip the output file.

but `cp` will copy lot's of stuff, like files generated by build system, and I don't see any problem in piping `git archive`, i.e. `git archive HEAD | tar -tf-` or `git archive HEAD | tar -xf- -C /new/path`

>abi-monitor/abi-tracker can do the same thing as abi-dumper/abi-compliance-checker

I need to take a closer look I guess

**Comment by azat** [comment]
Besides from image on [docker hub](https://hub.docker.com/r/iamazat/lvc-debian/tags), I also added image on the [github package registry](https://github.com/azat/docker-images/packages/21812?version=latest) via github actions (actually github actions can replace travis-ci, but not now, since they are in beta)

**Comment by azat** [comment]
Ok, I've applied this forgotten patch (735c891e), but only some bits still need to add auto deploy via ci, will do later

**Comment by azat** [comment]
[Done](https://libevent.org/abi/)
