### ISSUE TITLE
Can the asynchronous http requests based on libevent be implemented?

### ISSUE THREAD

**Issue by gladsnow** [libevent/libevent#889]
Recently I  use the libevent's http functions to implement the  asynchronous http client.
I have tried some methods，but the results are unsatisfactory. Is there a better way to achieve the asynchronous http client? Thanks in advance.

**Comment by azat** [comment]
>I have tried some methods，but the results are unsatisfactory

Can you share some code and describe what the problem is?

**Comment by gladsnow** [comment]
Sorry,I couldn't share the code because of the code is belong to my company. I can talk about my ideas.
1.I create an event loop by using a thread , and add a socket connection to the loop. 
2. I use the connection to make many requests by calling evhttp_make_request() repeatedly.
3. When the http server can't work, I  still make many requests by calling evhttp_make_request() . I find that the memory of the program is constantly increasing.How can I solve this problem?
Maybe my approach is wrong. Do you have a better way to implement the asynchronous http client?

**Comment by azat** [comment]
>1.I create an event loop by using a thread , and add a socket connection to the loop.
>2. I use the connection to make many requests by calling evhttp_make_request() repeatedly.

It is better to schedule requests from the same thread and also only after previous one finished

>When the http server can't work, I still make many requests by calling evhttp_make_request() 

So IOW you just need to stop making requests if the server did not respond? Then you just need to write it.

**Comment by gladsnow** [comment]
> So IOW you just need to stop making requests if the server did not respond? Then you just need to write it.

I mean that when the http server suddenly stop responding, the http client doesn't know the http connection is broken. In the case, the http client  continues to send requests to the http server.
According to my business requirements，no matter what state the http server is in，I need to allow the http client to send asynchronous requests. So what shoud I do for implementing the http requests based on libevent? Give me some advice please. Thanks.

**Comment by azat** [comment]
> According to my business requirements，no matter what state the http server is in，I need to allow the http client to send asynchronous requests. So what shoud I do for implementing the http requests based on libevent? Give me some advice please. Thanks.

Before you wrote:

> 1.I create an event loop by using a thread , and add a socket connection to the loop.
> 2. I use the connection to make many requests by calling evhttp_make_request() repeatedly.

So AFAICS the problem is that you do not re-create connection, and once
the connection will be reseted the *current* request will fail, but
if there will be more requests pending an attempt to establish
connection will be made again (see also evhttp_connection_set_retries(),
but this is only for connection stage)

You can use evhttp_request_set_error_cb() to detect failures, and take
appropriate actions (i.e. reschedule the request).

**Comment by gladsnow** [comment]
I get it. Thank you very much.
