### ISSUE TITLE
warning: sysctl is not implemented and will always fail

### ISSUE THREAD

**Issue by Jingzhao123** [libevent/libevent#890]
Hi, 
When i build the libevent, there is always a warning. Just like that:
```
CMakeFiles/event_core_shared.dir/evutil_rand.c.o: In function `arc4_stir':
evutil_rand.c:(.text+0x460): warning: sysctl is not implemented and will always fail
```
I check the document carefully. I found that the official doc does not suggest using the "sysctl" function:
http://man7.org/linux/man-pages/man2/sysctl.2.html
They suggest that "Glibc does not provide a wrapper for this system call; call it using syscall(2)." 
Is any one encounter this problem ?
Configurations:
OS:Ubuntu 18.04
Kernel: 4.18.20
arch: aarch64

**Comment by ploxiln** [comment]
It's a fallback that is typically never attempted on linux:

```c
arc4_seed(void)
{
	int ok = 0;
	/* We try every method that might work, and don't give up even if one
	 * does seem to work.  There's no real harm in over-seeding, and if
	 * one of these sources turns out to be broken, that would be bad. */
#ifdef TRY_SEED_WIN32
	if (0 == arc4_seed_win32())
		ok = 1;
#endif
#ifdef TRY_SEED_URANDOM
	if (0 == arc4_seed_urandom())
		ok = 1;
#endif
#ifdef TRY_SEED_PROC_SYS_KERNEL_RANDOM_UUID
	if (arc4random_urandom_filename == NULL &&
	    0 == arc4_seed_proc_sys_kernel_random_uuid())
		ok = 1;
#endif
#ifdef TRY_SEED_SYSCTL_LINUX
	/* Apparently Linux is deprecating sysctl, and spewing warning
	 * messages when you try to use it. */
	if (!ok && 0 == arc4_seed_sysctl_linux())
		ok = 1;
#endif
```

So if `/dev/urandom` is accessible, or if `/proc/sys/kernel/random/uuid` is accessible, it doesn't actually try the sysctl libc call. So if you can ignore the compiler warning, it's fine :)

Anyway, that sysctl strategy should probably be replaced by `getrandom()` if available.

**Comment by azat** [comment]
Replaced with `getrandom`, @ploxiln thanks for the suggestion and @Jingzhao123 thanks for the report!

**Comment by ploxiln** [comment]
very nice, thanks @azat 

By the way, OpenBSD and MacOS have a `getentropy()` syscall that is very similar, and I just noticed that glibc also offers this function, for which it uses `getrandom()` underneath: http://manpages.ubuntu.com/manpages/bionic/man3/getentropy.3.html

But `arc4_seed()` is probably fine as-is if the bsd sysctl method still works fine on those OS anyway.

**Comment by azat** [comment]
>MacOS have a getentropy() 

There are some issues on osx sierra at least (see #398), so let's keep it as-is for now, to avoid introducing yet another build switch.
