### ISSUE TITLE
evmap_io_active_ CPU 100%

### ISSUE THREAD

**Issue by caiqinghua** [libevent/libevent#893]
1. version: libevent-2.1.11-stable
2. problem: evmap_io_active_ CPU 100%
3. perf top info
Samples: 79K of event 'cpu-clock', Event count (approx.): 12176596951
Overhead  Shared Object          Symbol
  91.09%  libevent-2.1.so.6.0.2  [.] evmap_io_active_

**Comment by azat** [comment]
Can you please attach somewhere output of the following:
`strace -ffqq -p <pid> |& head -n1000 >| log` or `perf trace -e -p <pid>`

And also describe your use case

**Comment by caiqinghua** [comment]
1. os: 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64  GNU/Linux
2. use case: client has a conn
void Client::runThreadWriteSocket() {
  LOG(INFO) << "start libevent write socket thread";

  sleep(5);
  while (running_) {
          usleep(1000);
          char buf[32];
          memset(buf, 0x55, 32);
          conn->bufferevent_write(bev_, buf, len);
  }
}

bool Client::init() {
  thread_ = thread(&Client::runThreadWriteSocket, this);
  return true;
}
3. log
[pid  1824] restart_syscall(<... resuming interrupted nanosleep ...>) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0
[pid  1824] nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0

4. perf top
Samples: 17K of event 'cpu-clock', Event count (approx.): 4141570270
Overhead  Shared Object          Symbol
  94.83%  libevent-2.1.so.6.0.2  [.] evmap_io_active_

**Comment by caiqinghua** [comment]
And if i change bufferevent_write interval from 1ms to 1s, problem haven't occur until now.

**Comment by caiqinghua** [comment]
If we change

**Comment by azat** [comment]
```
usleep(1000);
char buf[32];
memset(buf, 0x55, 32);
bufferevent_write(conn->bev_, buf, len);
```

This bit does not looks sane, if you use event-driver programming, then it is better to write to the socket only when it is available for reading
