### ISSUE TITLE
Android O crashed because of seccomp prevented call to disallowed arm64 system call 0

### ISSUE THREAD

**Issue by Harrison-2019** [libevent/libevent#895]
with latest libevent, compiled with NDK-R20, Android O crashed because of seccomp prevented call to disallowed arm64 system call 0. I found syscalls in epoll_sub.c
```javascript
int epoll_create(int size)
{
#if !defined(__NR_epoll_create) && defined(__NR_epoll_create1)
	if (size <= 0) {
		errno = EINVAL;
		return -1;
	}
	return (syscall(__NR_epoll_create1, 0));
#else
	return (syscall(__NR_epoll_create, size));
#endif
}

int epoll_ctl(int epfd, int op, int fd, struct epoll_event *event)
{

	return (syscall(__NR_epoll_ctl, epfd, op, fd, event));
}

int epoll_wait(int epfd, struct epoll_event *events, int maxevents, int timeout)
{
#if !defined(__NR_epoll_wait) && defined(__NR_epoll_pwait)
	return (syscall(__NR_epoll_pwait, epfd, events, maxevents, timeout, NULL, 0));
#else
	return (syscall(__NR_epoll_wait, epfd, events, maxevents, timeout));
#endif
}
```
could you please fix this problem?

**Comment by ploxiln** [comment]
Many libc provided functions are wrappers for syscalls. All processes use syscalls to get data into or out of the process, via files or network or whatever.

These things here are fallbacks which are used in the case that the libc which is present does not have the epoll functions, but was built with linux headers that have the epoll syscall numbers defined ... this is probably a very historical case. I suppose that android's bionic libc might be a special case for this, but it does not seem likely, this is pretty old linux functionality now.

What is quite unlikely is "system call 0". That really must just be a bug somewhere, maybe in the toolchain. It is probably related to some other syscall made through some libc function. We'll need more information from someone using this toolchain, like a backtrace from the point of the seccomp crash.

(I wonder if the `0` is just an artifact of how seccomp rejects syscalls ... I dunno)

**Comment by azat** [comment]
>with latest libevent

Please answer the following questions:
- which one? commit sha, tag, ...
- which build system did you use, cmake/autotools? (for cmake epoll_sub is not used and for autotools we check epoll availability)
- so it is likely that you uses autotools, can you verify the same [sample](https://github.com/libevent/libevent/blob/095c8ae11121c302f0bd9a896be6ff0a84b7c51f/configure.ac#L595-L611), did seccomp reject it?

> What is quite unlikely is "system call 0".

Agree with @ploxiln , can you provide backtrace?

**Comment by Harrison-2019** [comment]
> > with latest libevent
> 
> Please answer the following questions:
> 
> * which one? commit sha, tag, ...
> * which build system did you use, cmake/autotools? (for cmake epoll_sub is not used and for autotools we check epoll availability)
> * so it is likely that you uses autotools, can you verify the same [sample](https://github.com/libevent/libevent/blob/095c8ae11121c302f0bd9a896be6ff0a84b7c51f/configure.ac#L595-L611), did seccomp reject it?
> 
> > What is quite unlikely is "system call 0".
> 
> Agree with @ploxiln , can you provide backtrace?

Sorry, I cannot provider the exact backtrace. I first use libevent-2.0.21 for compiling, but failed when running on Android O device, crashed because of seccomp filter.  I found this filter on Android device has a whitelist of syscalls, and epoll functions like epoll_create with arm64 architecture is not listed. I guess that's why it returns system call 0. The compile toolchain I used is from NDK-r20, aarch64-linux-android-4.9. **I wonder if there is anyway to avoid use syscall functions, could you please give me some suggestions?**

Android seccomp filter whitelist and blacklist 
https://github.com/aosp-mirror/platform_bionic/tree/master/libc

Same issue in other project
https://github.com/Tencent/matrix/issues/227

**Comment by ploxiln** [comment]
From `SECCOMP_BLACKLIST_APP.TXT`:

> The final seccomp whitelist is SYSCALLS.TXT - SECCOMP_BLACKLIST.TXT + SECCOMP_WHITELIST.TXT

`SYSCALLS.TXT` contains `epoll_create1`, `epoll_ctl`, and `__epoll_pwait` for "all" architectures.
The BLACKLIST files do not contain any epoll related functions. `SECCOMP_WHITELIST_APP.TXT` contains `epoll_create` for 32-bit x86, arm, mips.

Presumably, programs compiled for 64-bit should be recent/modern enough to use `epoll_create1`. The libevent Changelog says that starting with version 2.1.1 libevent prefers `epoll_create1`. I guess you should try libevent-2.1.11

**Comment by Harrison-2019** [comment]
> From `SECCOMP_BLACKLIST_APP.TXT`:
> 
> > The final seccomp whitelist is SYSCALLS.TXT - SECCOMP_BLACKLIST.TXT + SECCOMP_WHITELIST.TXT
> 
> `SYSCALLS.TXT` contains `epoll_create1`, `epoll_ctl`, and `__epoll_pwait` for "all" architectures.
> The BLACKLIST files do not contain any epoll related functions. `SECCOMP_WHITELIST_APP.TXT` contains `epoll_create` for 32-bit x86, arm, mips.
> 
> Presumably, programs compiled for 64-bit should be recent/modern enough to use `epoll_create1`. The libevent Changelog says that starting with version 2.1.1 libevent prefers `epoll_create1`. I guess you should try libevent-2.1.11

thank you, I've already tried 2.1.11, but the problem happened again. I found the toolchain's epoll.h do not have a function like
 int __epoll_pwait:epoll_pwait(int, struct epoll_event*, int, int, const sigset64_t*, size_t)  all
. It seems this funtion was an unique function in Android System, I cannot find a solution to solve this problem, I wonder if I can use some other ways instead of syscalls. do you have any ideas? Thanks
