### ISSUE TITLE
Crash in iocp/bufferevent/bufferevent_connect_fail on Windows

### ISSUE THREAD

**Issue by JoakimSoderberg** [libevent/libevent#90]
When running the bufferevent_connect_fail regress test with IOCP, there's a crash on this line:
https://github.com/libevent/libevent/blob/master/bufferevent.c#L689

The callback arg passed to this function is a NULL pointer in this case. I tried to make sense of where in the code this is happening but couldn't find the cause.

It works fine with the non-iocp regress test.

In both tests, the argument is set here correctly:
https://github.com/libevent/libevent/blob/master/event.c#L2921

**Comment by ellzey** [comment]
@JoakimSoderberg we've moved everything over to github.com/libevent/libevent for CI and other build stuff.

Easy one for me :wine_glass:

Closing
