### ISSUE TITLE
The timer cannot be triggered immediately for the first time?

### ISSUE THREAD

**Issue by X-Crack** [libevent/libevent#900]
This is a project based on libevent.

https://github.com/X-Crack/evcc/blob/master/source/event/event_timer.cc

In the use of timers, I found that the timer was created and waited for a timeout before triggering the second time.

If you set it up for a long time, you have to wait a long time.

Is there a way to trigger the first time a timer is created?

Thanks very much. I hope my friends can help me.

**Comment by azat** [comment]
>In the use of timers, I found that the timer was created and waited for a timeout before triggering the second time.

And what are you expecting?

**Comment by X-Crack** [comment]
@azat 

Forgive my English level.   ^_^


Timer, triggered immediately after creation, rather than waiting for a specified time.

But this situation is limited to the first time.

**Comment by azat** [comment]
> Timer, triggered immediately after creation, rather than waiting for a specified time.

Can you give a reproducer (50-100 lines of code that shows the problem
without your wrappers)?

**Comment by X-Crack** [comment]
This is not a mistake.

And I'm asking you for a way to trigger the timer immediately after it's created.

There's no problem with libevent itself!

I think it's my own problem.

**Comment by X-Crack** [comment]
@azat 

`
#include <event-internal.h>
#include <event2\event.h>
#include <event2\event_compat.h>
#include <event2\event_struct.h>
#include <event2\listener.h>
#include <event2\util.h>
#include <event2\thread.h>

void timer_printf(int fd, short flags, void* v)
{
	std::cout << "Hello World!\n";
}

int main()
{
	event_config* cfg = event_config_new();

	struct event_base * event_base = event_base_new_with_config(cfg);
	event_config_free(cfg);

	struct event* event = new struct event;

	event_assign(event, event_base, INVALID_SOCKET, EV_TIMEOUT | EV_PERSIST, timer_printf, 0);

	event_base_set(event_base, event);

	// Output once in 30 seconds
	timeval tv;
	tv.tv_sec = 30;
	tv.tv_usec = 0;

	event_add(event, &tv);
	event_base_loop(event_base, 0);
	return 0;
}
`

If you execute the code once, you will find "Hello World!" The output will take 30 seconds.





Instead of immediate output after creation

**Comment by azat** [comment]
>And I'm asking you for a way to trigger the timer immediately after it's created.

Got it, you can use `event_active(ev, 0)` for this (see also #872)

**Comment by X-Crack** [comment]
event_active

The method, though, can respond immediately.

But the second time will wait for ms*2

**Comment by azat** [comment]
>But the second time will wait for ms*2

This looks hackish and there is no (and should not be) such method for this.

You can manually set timeout to TIMEOUT*2 and once the really EV_TIMEOUT will be triggered change the timeout

**Comment by X-Crack** [comment]
You misunderstood me.

The event_activity method can activate the event immediately.

However, for the second execution, the time to wait for the previous execution*2

That's 60 seconds before you can actually output the second time.

**Comment by azat** [comment]
>However, for the second execution, the time to wait for the previous execution*2

- `event_active(ev, 0, 0)` will trigger event and the next time it will be triggered after timeout
- `event_active(ev, EV_TIMEOUT, 0)` will trigger event and the next time it will be triggered after timeout*2

The devil is in details, when event trigered with `EV_TIMEOUT` another timeout slice added unconditionally, whether it is triggered by real timeout or via `event_active`.

**Comment by azat** [comment]
```c
#include <event2/event.h>

void timer_printf(int fd, short flags, void* v)
{
    puts("Hello World!");
}

int main()
{
    struct event_base * event_base = event_base_new();
    struct event* event = event_new(event_base, -1, EV_TIMEOUT | EV_PERSIST, timer_printf, 0);

    // Output once in 30 seconds
    struct timeval tv;
    tv.tv_sec = 1;
    tv.tv_usec = 0;

    event_add(event, &tv);
    event_active(event, 0, 0);
    event_base_loop(event_base, 0);
    return 0;
}
```

```sh
$ stdbuf -o0 ./a.out |& ts
Sep 22 15:42:41 Hello World!
Sep 22 15:42:42 Hello World!
Sep 22 15:42:43 Hello World!
```

**Comment by azat** [comment]
And here are some notes for your example:
- never use internal incudes (only if you 100% sure what you are doing)
- keep include list short (you only need `<event2/event.h>`)
- use `event_new` over `new`/`malloc`, to not depends on ABI changes (i.e. `sizeof(struct event)`)
- you do not need cfg there
- you do not need `event_base_set` there

**Comment by X-Crack** [comment]
Thank you very much for your help. I understand it thoroughly.
