### ISSUE TITLE
Does libevent only support socket type fd event under epoll method?

### ISSUE THREAD

**Issue by changchengx** [libevent/libevent#901]
In below program, the event_root will be NULL if EV_FEATURE_FDS is set in event_cfg.
Does libevent only support socket type fd event  under epoll method?

```c
#include <stdio.h>
#include <event2/event.h>

int main(int argc, char **argv)
{
    struct event_config* event_cfg = event_config_new();
    event_config_avoid_method(event_cfg, "select");
    event_config_avoid_method(event_cfg, "poll");
    event_config_require_features(event_cfg, EV_FEATURE_ET | **EV_FEATURE_FDS**);

    struct event_base* event_root = event_base_new_with_config(event_cfg);
    event_config_free(event_cfg);

    printf("%p\n", event_root);

    return 0;
}
```

**Comment by azat** [comment]
EV_FEATURE_FDS is supported only by the following methods:
- devpoll
- kqueue
- select
- poll

EV_FEATURE_ET is supported only by:
- kqueue
- epoll

And since you are on linux, you will not have any available method.

epoll do not support it internally regular fds, from `epoll_ctl(2)`:

```
       EPERM  The target file fd does not support epoll.  This error can occur if fd refers to, for example, a regular file or a directory.
```

**Comment by changchengx** [comment]
>EPERM  The target file fd does not support epoll.  This error can occur if fd refers to, for example, a regular file or a directory
>
I'm not sure this is right or not.
In Ceph storage project, a regular file is also changed by epoll_ctl
https://github.com/ceph/ceph/blob/master/src/msg/async/EventEpoll.cc#L72

**Comment by changchengx** [comment]
@azat 
So, If I want to select using epoll & monitor regular file (not socket file), It's not better to use libevent, right?

**Comment by azat** [comment]
>In Ceph storage project, a regular file is also changed by epoll_ctl

are you sure that it is called for regular files?

>So, If I want to select using epoll & monitor regular file (not socket file), It's not better to use libevent, right?

This is not about libevent, it is about epoll, epoll internally do not allow this.

**Comment by changchengx** [comment]
> are you sure that it is called for regular files?
Sorry, not exactly.
It use eventfd API to "eventfd  object" and then changed the attribute by epoll_ctl
Could I also register the "eventfd object" created by eventfd to libevent to monitor it?

**Comment by azat** [comment]
>Could I also register the "eventfd object" created by eventfd to libevent to monitor it?

Yes, you can register any fd that is supported by backend, and epoll supports it.

**Comment by changchengx** [comment]
Thanks a lot.
