### ISSUE TITLE
Time basis for timers? Artificial time counting?

### ISSUE THREAD

**Issue by timwoj** [libevent/libevent#903]
I’m working on the Zeek project (https://github.com/zeek/zeek) and we’re investigating switching from our internally-written event loop over to use something like libevent. One of the features of our existing hand-written loop is that we can trigger it using an artificial time base, which allows us to move time forward based on the timestamps of packets in a packet capture. Timers can then fire based on the packet times instead of wall-clock time, and we get repeatable results when using such files as if they were still live data.

Does something like that already exist in libevent or cauld it be easily added? I dug through the code a little bit today and it seems possible to add it, but I thought I’d ask before I went too far with it.

**Comment by X-Crack** [comment]
@timwoj 
Yes, you can easily use timer

**Comment by azat** [comment]
>Timers can then fire based on the packet times instead of wall-clock time, and we get repeatable results when using such files as if they were still live data.

IIUUC, you have smth like this:
- now=10
- p1 rel_time=1
- p2 rel_time=2

And you need to trigger p1 in now+1, and p2 in now+2, than you just use `event_add(ev, tv=packet.rel_time)`

If you have absolute times, you need to convert them into the relatives and do the same.

**Comment by timwoj** [comment]
Perhaps I'm misunderstanding what you mean, but that still means the timers will fire somewhat relative to the wallclock time. The problem is that I need time to advance as we get new packet data in. Just setting a timer based on the relative time difference between current wallclock time and the last packet we received doesn't guarantee that the timer will always fire at the same time as if the packet data was live.

**Comment by azat** [comment]
>The problem is that I need time to advance as we get new packet data in

Hm, maybe I misunderstood you, but instead of changing the time you can change the timeout, no?

>Just setting a timer based on the relative time difference between current wallclock time and the last packet we received doesn't guarantee that the timer will always fire at the same time as if the packet data was live

I guess that you are not talking about timers error here, can you give an example?

**Comment by ploxiln** [comment]
I think timwoj wants to run a sort of simulation at faster-than-real-time, by occasionally causing the "clock" to jump forward X seconds in an instant, which effectively causes all pending events with timeouts to have X seconds subtracted from their timeout (and some of them may become active immediately).

For example: the program reads some input from a trace with timestamp included, and sees that the timestamp indicates it should now be 0.5 seconds later than the previous input. Instead of waiting 0.5 seconds of real time, it wants to immediately jump the "clock" forward 0.5 seconds, reducing all pending timeouts by 0.5 seconds, immediately.

(I'm not sure if this is in-scope for libevent.)

**Comment by azat** [comment]
>Instead of waiting 0.5 seconds of real time, it wants to immediately jump the "clock" forward 0.5 seconds

Well triggering timers from the event loop will always have some delay (and it depends on factors like callback speed), so if this must be close to real-time, then event loop is not a great idea.
But if it is not the case, then all you need to do is just substract delta from all pending events.

>it seems possible to add it

@timwoj if it will not takes too much time can you send us a patch?
Or you can show what you have now in zeek?

**Comment by timwoj** [comment]
Sorry for a bit of a delay on getting back to this.

> I think timwoj wants to run a sort of simulation at faster-than-real-time, by occasionally causing the "clock" to jump forward X seconds in an instant, which effectively causes all pending events with timeouts to have X seconds subtracted from their timeout (and some of them may become active immediately).

That's effectively it, yes. The packet data has timestamps in it, and I want to set the time based on those timestamps.

> If it will not takes too much time can you send us a patch?

This is pretty rough, but it gets the point across: https://gist.github.com/timwoj/4d4d4d156f598036e6ce43316bd022ce

Included is the patch and a simple driver that reads from a pcap file and updates the time based on the incoming data. You'll need libpcap installed to build the driver.

Looking at it again though, it might just not be possible the way want. Currently we increment the time as the data is received, but before firing timers or processing the data. I'd probably have to keep maintaining time manually and firing timers manually, which might just negate the whole point of changing libevent to do it for me.

**Comment by timwoj** [comment]
We ended up going a different direction with this. I'm going to close this out.
