### ISSUE TITLE
HTTP client with UNIX socket

### ISSUE THREAD

**Issue by laanwj** [libevent/libevent#907]
I noticed that 737d1beb14423dc212b0c53edf536b3172c87571 added the ability to bind the HTTP server to a UNIX socket.

Is there a way to do the same but for the client?

A long time ago I submitted a PR (#479) for some code I used to make HTTP requests over a UNIX socket, but this wasn't accepted. Maybe my approach was wrong, but I'm still looking for a way to do this.

**Comment by azat** [comment]
Fixed in https://github.com/libevent/libevent/pull/322
