### ISSUE TITLE
CMake, static library is not built, bug?

### ISSUE THREAD

**Issue by Barricade** [libevent/libevent#919]
`cd "$LIBEVENT_CMAKE_PATH" `
`cmake -DCMAKE_INSTALL_PREFIX:PATH="$LIBEVENT_BUILD_PATH" "$LIBEVENT_PATH"`
`cmake --build "$LIBEVENT_CMAKE_PATH" --target install --config Release`
`ls "$LIBEVENT_BUILD_PATH/lib" # contains only dylib files (should contain static libraries too?)`
Mac OS

**Comment by Barricade** [comment]
Seems to be fixed in https://github.com/libevent/libevent/commit/236762a30d3e49bde8256876758539be4b4788a8

**Comment by azat** [comment]
>Seems to be fixed in 236762a

Does not looks correct, since this is a fix for MSVC only, and it's doing exactly opposite thing, but if you do not observe the issue using libevent from upstream let's consider this as fixed
