### ISSUE TITLE
CMake, at installation @rpath in install_name is always replaced with absolute path, bug?

### ISSUE THREAD

**Issue by Barricade** [libevent/libevent#920]
At installation `@rpath` in install_name is replaced with absolute path. How can I prevent this?
`cd "$LIBEVENT_CMAKE_PATH"`
`cmake -DCMAKE_INSTALL_PREFIX:PATH="$LIBEVENT_BUILD_PATH" "$LIBEVENT_PATH"`
`cmake --build "$LIBEVENT_CMAKE_PATH" --target install --config Release`
`otool -D "$LIBEVENT_BUILD_PATH/lib/libevent-2.1.7.dylib"`
`Result: /Users/barricadenick/build/libevent-2.1.11-macos/lib/libevent-2.1.7.dylib`
`Expected result: @rpath/libevent-2.1.7.dylib <- the same as in zlib, libpng, SDL, etc`
Mac OS

**Comment by Barricade** [comment]
Why do we need this line?
https://github.com/libevent/libevent/blame/master/cmake/AddEventLibrary.cmake#L100
It seems to break this behavior.

**Comment by ygj6** [comment]
If use `@ rpath`, downstream users must also passively set it up, which can cause trouble for people.
It is considered that install the libraries to the *standard* path (e.g. `/usr/local/`) mechanically and don't move it to other path, and then, `@rpath` is not needed.

P.S. I installed `zlib`, `libpng` and `SDL` with brew on Mac, and test them with `otool -D`,  there is no `@rpath` in shared library id at all. What is the difference between our operations?

**Comment by Barricade** [comment]
If I build and install SDL 2.0.10 and libpng 1.6.37 from source with cmake (3.15.4), then there is @rpath in them. zlib 1.2.11 uses old cmake, so I'll have to pass CMAKE_POLICY_DEFAULT_CMP0042=NEW, to make it with @rpath too.
I agree that in standard path it must be without @rpath in it. But I would like to have a way to install it with @rpath and without it.

**Comment by ygj6** [comment]
Have you tried `install_name_tool`?  It should  be able to change `@rpath` manually.

**Comment by Barricade** [comment]
Yes, I know this tool

**Comment by Barricade** [comment]
There already exists the flag in cmake to control replacement of @rpath with full path: MACOSX_RPATH, but setting INSTALL_NAME_DIR manually overrides the effect of MACOSX_RPATH.

**Comment by ygj6** [comment]
If really want to set `@rpath`, I suggest you set it with the following command:
```
install_name_tool -id /path/to/xxx.dylib @rpath/xxx.dylib xxx.dylib
```
then use `otool -L xxx.dylib` to check if the command works.

When using xxx.dylib in your project, the following error will occur if you do nothing on `rpath`:
`dyld: Library not loaded: @rpath/xxx.dylib`

There are two options to fix it:
- add `-Wl,-rpath /path/containing/xxx.dylib` to `LDFLAGS`
If build with cmake, try this: `set(CMAKE_INSTALL_RPATH "/path/containing/xxx.dylib")`

- use `install_name_tool` command to add `rpath` for your program
`install_name_tool -add_rpath /path/containing/xxx.dylib yourprogram`

Enter `otool -l yourprogram` and look at the `LC_RPATH` section where the value you added should be in.

But in short, these are all your own operations. I would like to keep libevent libraries as they are.

**Comment by zakalawe** [comment]
This is also causing me problem. The issue is that the full path to the build machine  is included in the generated CMake export files and pkg-config .pc files it would be very useful to have at least the option to have an @rpath enabled build on macOS.

We build libEvent on a Jenkins machine, but want to use the created binaries at different prefixes on other developer machines. This works fine for other libraries (DBus, FreeType, etc) but fails for libEvent due to the absolute path.

**Comment by SpaceIm** [comment]
I agree that this line should be removed, it makes the shared libs non-relocatable on macOS, and it defeats default behavior of CMake.
In conan package manager, this line is removed because absolute paths are a no-go.

**Comment by mdavidsaver** [comment]
A note which may help others.  6349e94a0a4fe361ad78921ff84bfe3be94b2028 adds a file `PreLoad.cmake` which can override the implied default of `CMAKE_SKIP_INSTALL_RPATH` to `ON` (skipping RPATH).  This caused me some confusion until I realized that `PreLoad.cmake` is a magic file name for CMake (`strace -e trace=%file cmake ...` shows this file being opened).

**Comment by azat** [comment]
>This caused me some confusion until I realized that PreLoad.cmake is a magic file name for CMake

Yes, it is non-documented feature, but there is an issue in cmake issue tracker to [document it](https://gitlab.kitware.com/cmake/cmake/-/issues/17231).

_Though they do not recommend to use it..._
