### ISSUE TITLE
Regression test failures on CentOS6 (glibc-2.12)

### ISSUE THREAD

**Issue by johnsalmon** [libevent/libevent#924]
This is  very similar to issue #749.

I compiled the latest master on CentOS6 and ran regressions.   I get 8 failures, all similar to:

```
  FAIL /d/nyc/salmonj-0/scratch0134/salmonj/repos/libevent/test/regress_dns.c:1402: assert(be_outcome[3].dnserr == default_error): -5 vs -11
  [bufferevent_connect_hostname_emfile FAILED]
```

It looks like glibc-2.12 has similar characteristics to MacOS in #749:  It doesn't return EAI_SYSTEM when its sytem calls fail with EMFILE.  I confirmed as much the test program below.  Note though, that in the test below, the value returned is -2 (EAI_NONAME), but in the regression test, it's -5 (EAI_NODATA).

I wonder if this test is more trouble than it's worth?  Is seems far more likely to produce error reports like this one and #749 than to uncover genuine bugs in libevent.

```
$ cat /etc/redhat-release 
CentOS release 6.8 (Final)
$ rpm -q glibc
glibc-2.12-1.192.el6.x86_64
glibc-2.12-1.192.el6.i686
```

```c
$ cat gaiemfile.c
#include <sys/time.h>
#include <sys/resource.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <stdio.h>
#include <unistd.h>
#include <assert.h>

int main(int argc, char **argv){
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    assert(fd>0);
    struct rlimit file = {fd, fd};
    assert(0==close(fd));
    assert(0==setrlimit(RLIMIT_NOFILE, &file));
    struct addrinfo* ai;
    int ret = getaddrinfo("notaname.example.com", NULL, NULL, &ai);
    printf("ret=%d %s\n", ret, gai_strerror(ret));

    return 0;
}
```

```
$ gcc gaiemfile.c
$ ./a.out
ret=-2 Name or service not known
```

**Comment by azat** [comment]
>I wonder if this test is more trouble than it's worth? Is seems far more likely to produce error reports like this one and #749 than to uncover genuine bugs in libevent.

Thanks for the report and details!
That was the regression (so not a great idea to simply remove the test), but the expected error can be relaxed, see 4436287.
