### ISSUE TITLE
Dead loop in event_base_loop after some period of time

### ISSUE THREAD

**Issue by Hujinyong** [libevent/libevent#928]
After running of some period of time (2-12 hours) a thread can get stuck consuming 100% cpu, this behavior  is 100% reproducible on 2.1.8-stable version.

Following are logs with EVENT_DEBUG_ALL enabled.

win32select.c: select returned 1
win32select.c: select returned 1
event_active: 02C54F90 (fd 588), res 2, callback 0F452640
event_active: 02C73C68 (fd 656), res 2, callback 0F452640
event_process_active: event: 02C54F90, EV_READ   call 0F452640
event_process_active: event: 02C73C68, EV_READ   call 0F452640
win32select.c: select returned 1
timeout_next: event: 02D04B98, in 2 seconds, 270000 useconds
event_active: 02C54F90 (fd 588), res 2, callback 0F452640
win32select.c: select returned 1
event_process_active: event: 02C54F90, EV_READ   call 0F452640
event_active: 02C73C68 (fd 656), res 2, callback 0F452640
win32select.c: select returned 1
event_process_active: event: 02C73C68, EV_READ   call 0F452640
event_active: 02C54F90 (fd 588), res 2, callback 0F452640
timeout_next: event: 02D04B98, in 2 seconds, 270000 useconds
event_process_active: event: 02C54F90, EV_READ   call 0F452640
win32select.c: select returned 1
win32select.c: select returned 1
event_active: 02C73C68 (fd 656), res 2, callback 0F452640
event_active: 02C54F90 (fd 588), res 2, callback 0F452640
event_process_active: event: 02C73C68, EV_READ   call 0F452640
event_process_active: event: 02C54F90, EV_READ   call 0F452640
timeout_next: event: 02D04B98, in 2 seconds, 270000 useconds
win32select.c: select returned 1
win32select.c: select returned 1
event_active: 02C54F90 (fd 588), res 2, callback 0F452640
event_active: 02C73C68 (fd 656), res 2, callback 0F452640
event_process_active: event: 02C54F90, EV_READ   call 0F452640
event_process_active: event: 02C73C68, EV_READ   call 0F452640
win32select.c: select returned 1
timeout_next: event: 02D04B98, in 2 seconds, 270000 useconds
event_active: 02C54F90 (fd 588), res 2, callback 0F452640
win32select.c: select returned 1
event_process_active: event: 02C54F90, EV_READ   call 0F452640
event_active: 02C73C68 (fd 656), res 2, callback 0F452640
win32select.c: select returned 1
event_process_active: event: 02C73C68, EV_READ   call 0F452640
event_active: 02C54F90 (fd 588), res 2, callback 0F452640

**Comment by azat** [comment]
Hi!

There is a "similar" report, #911 but your looks different, at least by the following reasons:
- you have windows, and `win32select.c` is used
- you don't have bad fd error

So, back to your issue, there are always two active events (EV_READ), and this means that you do not read from them, and they will be always reported until you will read all data from the fds. Do you have any idea what this fds refers to?

>this behavior is 100% reproducible on 2.1.8-stable version

Any version that does not affected?

**Comment by Hujinyong** [comment]
Create an eventlistener as:

struct evconnlistener* _create_evlistener(struct event_base *base, void *ctx, int port, evconnlistener_cb cb)
{
    struct evconnlistener *listener;
    char local_ipport[128] = {0};

    sprintf(local_ipport, "0.0.0.0:%d", port);

    struct sockaddr_storage listen_on_addr;
    memset(&listen_on_addr, 0, sizeof(listen_on_addr));
    int socklen = sizeof(listen_on_addr);

    if (evutil_parse_sockaddr_port(local_ipport,
        (struct sockaddr*)&listen_on_addr, &socklen) < 0)
    {
        return NULL;
    }

    listener = evconnlistener_new_bind(base, cb, ctx,
        LEV_OPT_CLOSE_ON_FREE|LEV_OPT_CLOSE_ON_EXEC|LEV_OPT_REUSEABLE,
        -1, (struct sockaddr*)&listen_on_addr, socklen);

    return listener;
}

This thread can get stuck consuming 100% cpu with the following logs:
win32select.c: select returned 1
event_process_active: event: 02C73C68, EV_READ call 0F452640
event_active: 02C54F90 (fd 588), res 2, callback 0F452640

Where callback 0F452640 is evthread_notify_drain_default.

**Comment by azat** [comment]
>win32select.c: select returned 1
>win32select.c: select returned 1
>event_active: 02C54F90 (fd 588), res 2, callback 0F452640
>event_active: 02C73C68 (fd 656), res 2, callback 0F452640

What I missed in the previous log is that it is multi threaded, do you enable multi-threading support in libevent?

i.e.

```c
evthread_use_windows_threads();
```

And also create listener with the following flag `LEV_OPT_THREADSAFE` (just in case, since I don't know a lot about your program)

>Where callback 0F452640 is evthread_notify_drain_default.

Hm, interesting, can you add a breakpoint on it and check will it be called or not? (it should according to "event_process_active", but it reads all data in the callback, so either fd is wrong or it does not called, because of some corruption - this is only my guess of course)

>This thread can get stuck consuming 100% cpu with the following logs:

Also, can you check any other versions? (compiler from sources or older release)

**Comment by Hujinyong** [comment]
Yes, multi-threading is enabled by calling evthread_use_windows_threads(), and listener is created with LEV_OPT_THREADSAFE flag.
