### ISSUE TITLE
[CMakeLists] add option EVENT__EXTERNAL_OUTPUT_DIRECTORY

### ISSUE THREAD

**Issue by irov** [libevent/libevent#931]
add option settings like EVENT__EXTERNAL_OUTPUT_DIRECTORY

```
if(not EVENT__EXTERNAL_OUTPUT_DIRECTORY)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)
endif()
```

Thanks!

**Comment by azat** [comment]
Can you elaborate the purpose of introducing this?

**Comment by irov** [comment]
> Can you elaborate the purpose of introducing this?

Hello, 
i build dependence for project [hummingbird](https://github.com/irov/hummingbird) and current project setup this OUTPUT directory.

```
#dependencies jansson
if(HUMMINGBIRD_DEPENDENCE_JANSSON)
    message("================jansson================")
    set(USE_URANDOM OFF CACHE BOOL "USE_URANDOM" FORCE)
    set(USE_WINDOWS_CRYPTOAPI OFF CACHE BOOL "USE_URANDOM" FORCE)
    set(JANSSON_STATIC_CRT ON CACHE BOOL "JANSSON_STATIC_CRT" FORCE)
    set(JANSSON_EXAMPLES OFF CACHE BOOL "USE_URANDOM" FORCE)
    set(JANSSON_BUILD_DOCS OFF CACHE BOOL "JANSSON_BUILD_DOCS" FORCE)
    set(JANSSON_WITHOUT_TESTS ON CACHE BOOL "JANSSON_WITHOUT_TESTS" FORCE)    
    set(JANSSON_INSTALL OFF CACHE BOOL "JANSSON_INSTALL" FORCE)    

    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/jansson/jansson.h ${HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY}/jansson/include/jansson.h COPYONLY)
    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/jansson/jansson_config.h ${HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY}/jansson/include/jansson_config.h COPYONLY)
    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/jansson/dump.c ${HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY}/jansson/src/dump.c COPYONLY)

    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/jansson/CMakeLists.txt ${HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY}/jansson/CMakeLists.txt COPYONLY)

    ADD_SUBDIRECTORY(${HUMMINGBIRD_DEPENDENCIES_SOURCE_DIRECTORY}/jansson ${HUMMINGBIRD_DEPENDENCIES_TEMP_DIRECTORY}/jansson)
endif()
```

but libevent CMakeLists.txt redirect my OUTPUT directory

**Comment by azat** [comment]
>but libevent CMakeLists.txt redirect my OUTPUT directory

libevent's variables should be visible only inside libevent, can you show the chain of your includes? or post the minimal `CMakeLists.txt` that will show the issue

**Comment by irov** [comment]
> libevent's variables should be visible only inside libevent, can you show the chain of your includes? or post the minimal `CMakeLists.txt` that will show the issue

```
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin2)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib2)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib2)

SET(EVENT__LIBRARY_TYPE STATIC CACHE STRING "EVENT__LIBRARY_TYPE" FORCE)
SET(EVENT__DISABLE_OPENSSL ON CACHE BOOL "EVENT__DISABLE_OPENSSL" FORCE)

ADD_SUBDIRECTORY(libevent)
```

**Comment by azat** [comment]
`CMAKE_RUNTIME_OUTPUT_DIRECTORY` is not overwritten for me, are you sure that you are have exactly this? which cmake version?

```cmake
CMAKE_RUNTIME_OUTPUT_DIRECTORY = /tmp/cmake-libevent/bin2
...
-- 
--         ---( Libevent 2.2.0-alpha-dev )---
-- 
...
CMAKE_RUNTIME_OUTPUT_DIRECTORY = /tmp/cmake-libevent/bin2
```

**Comment by irov** [comment]
> `CMAKE_RUNTIME_OUTPUT_DIRECTORY` is not overwritten for me, are you sure that you are have exactly this? which cmake version?
I set this setting before adding libevent [ADD_SUBDIRECTORY]. Now we are building a library. We will not see the assembly in the expected place. Because libevent/CMakeLists.txt redirected the assembly to another location. If we look at other projects and assemblies, this options is not set or is hidden under the cmake option

**Comment by azat** [comment]
>Now we are building a library.

I was thinking about your library, not libevent, got it now, sorry, will be fixed shortly.
