### ISSUE TITLE
How to send/receive data after evttp_send_reply() ?

### ISSUE THREAD

**Issue by RokerHRO** [libevent/libevent#932]
I've registered a callback function via `evhttp_set_cb()`. Inside of the callback function I create and send the reply via `evhttp_send_reply(…)` but how can I keep the connection open and read from and send to the peer after that?

(I am implementing a simple WebSocket server, so the connection might be open for a quite long time)

**Comment by azat** [comment]
>Inside of the callback function I create and send the reply via evhttp_send_reply(…) but how can I keep the connection open

Do you send `Connection: close` or use `HTTP/1.0`?

>(I am implementing a simple WebSocket server, so the connection might be open for a quite long time)

You can use http layer of the libevent only to handle initial handshake (parse input headers, send response), but after you will need to switch to binary protocol, for this you will have to "steal" fd from the `evhttp_connection`, and this is not possible yet (since this fd is cached, see #795, in the connection and you cannot do it that simple, yes you can copy the structure and modify it, but this is hackish).

Also, as usual, you can simply search for "libevent websocket" in google and find some implementations (that do not use http directly) that may helps you.

**Comment by RokerHRO** [comment]
Thank you for you quick reply!

> Do you send `Connection: close` or use `HTTP/1.0`?

I set the header "Connection: Upgrade" as required by the WebSocket protocol spec.

> You can use http layer of the libevent only to handle initial handshake (parse input headers, send response), but after you will need to switch to binary protocol, for this you will have to "steal" fd from the `evhttp_connection`, and this is not possible yet (since this fd is cached, see #795, in the connection and you cannot do it that simple, yes you can copy the structure and modify it, but this is hackish).

I'll try it. :-)

> Also, as usual, you can simply search for "libevent websocket" in google and find some implementations (that do not use http directly) that may helps you.

I found https://github.com/caosiyang/websocket but – albeit the source have .cpp extension and it uses C++ std::string – it looks quite low-level C-style and, to be honest, I very like that evhttp does the whole HTTP protocol stuff (that I use in my server process anyway).

So it would be very nice if evhttp would get a clean and proper API to get the connection object and do my own data transfer on it after the HTTP stuff is done.

**Comment by azat** [comment]
>I set the header "Connection: Upgrade" as required by the WebSocket protocol spec.

So I guess that the server does not close the socket?

>So it would be very nice if evhttp would get a clean and proper API to

Clean API is another task, and at first glance I think that simply adding upgrading to websocket should not be that hard (but will requires some coding), want to try?

But to be honest libevent's HTTP API should be revisited at least/replaced (refs #261) to make it optimal first (and hence I'm not sure that such API should be added, but at least we can resolv #795, that will allow to implement it over http layer).

> get the connection object and do my own data transfer on it after the HTTP stuff is done.

Okay, I will get back to #795, but please don't expect that this will in the nearest feature.

**Comment by RokerHRO** [comment]
> > I set the header "Connection: Upgrade" as required by the WebSocket protocol spec.
> 
> So I guess that the server does not close the socket?

I don't know. At the moment the callback function does `evhttp_send_reply()` and has a big `//TODO: get the connection object and transfer it to the WebSocket event loop` and returns.

I don' t know what evhttp does in this case. ;-(

> > So it would be very nice if evhttp would get a clean and proper API to
> 
> Clean API is another task, and at first glance I think that simply adding upgrading to websocket should not be that hard (but will requires some coding), want to try?

Sure I'll try. But I need the low-level connection object (or anything I can read from/send to).
What can I do inside the evhttp callback function – or after leaving the cb function – after the call to `evhttp_send_reply()` on that connection and how?
 
> But to be honest libevent's HTTP API should be revisited at least/replaced (refs #261) to make it optimal first (and hence I'm not sure that such API should be added, but at least we can resolv #795, that will allow to implement it over http layer).
> 
> > get the connection object and do my own data transfer on it after the HTTP stuff is done.
> Okay, I will get back to #795, but please don't expect that this will in the nearest feature.

I'll dig into the libevent / event_http sources and perhaps I'll get some ideas tomorrow.

Thank you for your replies so far. :-)

**Comment by azat** [comment]
> But I need the low-level connection object

I was talking about patching libevent to add this

>What can I do inside the evhttp callback function

You need to detach the fd (and most likely buffers, since there can be pending data already) from the http and use it for websocket operations.

**Comment by azat** [comment]
Closing, please reopen/create-new-one if you have any other quetsions

**Comment by RokerHRO** [comment]
Huh? Why closed? The problem is still not solved. I still have no official way to send data or use the connection (or socket?) to process the WebSockets protocol after the HTTP reply. :-(

**Comment by azat** [comment]
Ok, reopening, but it can take awhile...

**Comment by RokerHRO** [comment]
Thank you. It is okay when it takes some time, but it should not be forgotten. :-)

**Comment by ploxiln** [comment]
It's possible to use something like https://github.com/nodejs/http-parser to manually manage parsing from a libevent bufferevent or raw tcp connection fd, and then it's easy to "take over" the connection for your own websockets implementation.

It is also possible to use [libwebsockets](https://github.com/warmcat/libwebsockets) with libevent: https://libwebsockets.org/lws-api-doc-v3.2-stable/html/group__context-and-vhost.html#gga41c2d763f78cc248df3b9f8645dbd2a5a03a942e8640c79711af917335560f3db https://github.com/warmcat/libwebsockets/blob/v3.2.1/minimal-examples/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c

**Comment by RokerHRO** [comment]
@ploxiln: Thank you. I only use libevent because it gives me ev_http which does the nasty HTTP stuff for me. If I have to write my own HTTP stack, there is no longer any benefit for me to use libevent at all. :-/

Thank you for your "minimal examples", but they are not as minimal as I expected: They use their own event loops to be independent from the underlaying event handling library (and let you choose between 3 different event handling libraries). That is far more complex than I need! :-(

Just give me an (official or inofficial) API to get the fd of the HTTP connection and "release" it from  the ownership or responsibility of ev_http would be enough for me and my needs, I think.

**Comment by ploxiln** [comment]
I'll admit that libwebsockets is quite annoying to figure out and use, given the many features and options which are not relevant to websockets. I say this from experience, because I have used libwebsockets in a (proprietary server-side) libevent based application, which uses a single (libevent) event loop, and also uses evhttp to serve some simple admin/stats endpoints on another port, and also serves rtsp (its primary job, implemented mostly from scratch, using my [fork of http-parser](https://github.com/ploxiln/http-parser) plus a lot of connection and stream management code).

I noticed that evhttp's spiritual successor libevhtp (see #261) has a function [evhtp_connection_take_ownership()](https://github.com/criticalstack/libevhtp/blob/develop/include/evhtp/evhtp.h#L1359) which you may find useful.

The one option that probably will not work, is waiting for someone else to just add this one feature to evhttp. But no one will feel bad if you find a different library which works better for you :)

**Comment by azat** [comment]
>I noticed that evhttp's spiritual successor libevhtp (see #261) has a function evhtp_connection_take_ownership() which you may find useful.

Actually it is not that hard to add such API, and indeed it will allow such things, @RokerHRO are you interesting in implementing this? Or should I take a look?

**Comment by RokerHRO** [comment]
@azat: I tried to do that but did not succeed. :-( So if you would give it a try, I'd appreciate it and also test it when finished. :-)

**Comment by RokerHRO** [comment]
@azat: I tried to do that but did not succeed. :-( So if you would give it a try, I'd appreciate it and also test it when finished. :-)

**Comment by azat** [comment]
>So if you would give it a try

Ok, I will take a look (but I think that I will have time for this only on weekends)

**Comment by RokerHRO** [comment]
@azat: Thank you. :-)

**Comment by ploxiln** [comment]
_libevhtp_ is a separate library. Please see #261 and https://github.com/criticalstack/libevhtp for more information.

**Comment by RokerHRO** [comment]
> _libevhtp_ is a separate library. Please see #261 and https://github.com/criticalstack/libevhtp for more information.
Okay, my questions are too vague. #261 was closed, but unfortunately there are no informations whether it is "Done" or "Rejected" or "Postponed" etc.

And it is not clear whether, when libevhtp will not be integrated in libevent, whether ev_http is still supported and improved or deprecated and users should move to libevhtp (e.g. because ev_http was only intended as a "demo server", not for real-wordl usage etc.)

**Comment by ploxiln** [comment]
evhttp is convenient if you are already using libevent, and reasonably efficient. It is still maintained, bugs are still fixed here and there. However, it is not the fastest http server out there, it is not the most flexible http server out there, it is probably not the most robust http server out there (imagine a popular web service with millions of entities on the public internet making strange requests and attacks). But it's pretty good for what it does.

libevhtp is faster and more flexible for the server-side. Probably more robust. There was a lot of interest in using it to replace evhttp, including from the libevent maintainers, but the will to do the work of porting it to support the full existing evhttp api has fizzled, and it won't happen any time soon. But you can still use it explicitly.

I would not expect evhttp to get additional features any time soon. While it is maintained, and gets bug fixes, it is a somewhat crufty code base, and very few people have both the expertise and motivation to add features to it.

**Comment by RokerHRO** [comment]
@ploxiln : Thank you for your fast and comprehensive answer. :-)
I'll try to switch to libevhtp (I'll see how complicated it will be), because I need some features (e.g. #932 and #1013) that are not available in ev_http in the foreseeable future.
