### ISSUE TITLE
release-2.1.11-stable cmake broken

### ISSUE THREAD

**Issue by XeroChen** [libevent/libevent#933]
here is the content from CMakeLists.txt
> ...
> configure_file(${PROJECT_SOURCE_DIR}/cmake/Uninstall.cmake.in
>                ${PROJECT_BINARY_DIR}/Uninstall.cmake  
>                @ONLY)

> add_custom_target(uninstall
>                   COMMAND ${CMAKE_COMMAND} -P ${PROJECT_BINARY_DIR}/Uninstall.cmake)
> ...  

BUT There is no `cmake/Uninstall.cmake.in` in released `release-2.1.11-stable.tar.gz`

**Comment by azat** [comment]
Fixed in f05ba671931e2b4e38459899f6f63f79f99869fe, but there is still no release with that patch included, will think about this

**Comment by anatol** [comment]
I see the same issue. Thank you @XeroChen for filing the ticket.
