### ISSUE TITLE
Test cases failed because sleep function is too slow on Mac

### ISSUE THREAD

**Issue by ygj6** [libevent/libevent#940]
There are many test cases related to nanosleep/usleep function. They test the performance of timing roughly similar to the following code:
```
gettimeofday(&start);
evutil_usleep_(100000usec);   // sleep 100000 microsecond (or 100 millisecond).
gettimeofday(&end);
diff = end - start;
assert(80000 < diff && diff < 120000); 
```
This code runs successfully on my own computer (Linux, Windows and Mac).
On travis-CI, it only succeeded on Linux and Windows, but not on Mac(The `diff` is likely to be greater than 120000).
In travis [result](https://travis-ci.org/libevent/libevent/jobs/630804094), there are 133 failures, 124 of which are sleep related.
I guess the issue is caused by the Mac virtual machine which travis used. But there is no evidence to prove it.

**Comment by azat** [comment]
>I guess the issue is caused by the Mac virtual machine which travis used. But there is no evidence to prove it.

Same here, and there is not not too much we can do, but here are some thoughts:
- timers bias can be calculcated to overcome this (like in 8a34869984c470fb243fc9587c469b316add2f7e for `test-ratelim`)
- I tried github actions and they looks ok, and AFAIR there is macos support, so we can give it a try (or other CI platforms)
- Investigate travis-ci a little bit more (although I think that this is a dead end)

P.S. It will be great to make the tests pass under osx
P.P.S. I used [osx in virtualbox](https://github.com/libevent/libevent-extras/blob/f920064247cdbc56cae93079f03bd0c9209665f0/Vagrantfile#L225) and the tests passed there (at some point at least)

**Comment by ygj6** [comment]
I wrote the project [`github-actions-example`](https://github.com/ygj6/github-actions-example) to test sleep functions in github actions. Unfortunately it also failed on Mac. The result is [here](https://github.com/ygj6/github-actions-example/runs/378887791).

**Comment by azat** [comment]
@ygj6 can you also check [appveyor](https://www.appveyor.com/docs/macos-images-software/) ?

**Comment by azat** [comment]
>1/1 Test #1: main .............................Child aborted***Exception:  56.64 sec

[Failed](https://ci.appveyor.com/project/azat/osx-timers/builds/30057939) too

**Comment by ygj6** [comment]
> can you also check appveyor ?

I still failed: https://ci.appveyor.com/project/ygj6/github-actions-example

> timers bias can be calculcated to overcome this

I will try later.
