### ISSUE TITLE
Convert travis-ci/appveyor to github actions

### ISSUE THREAD

**Issue by azat** [libevent/libevent#945]
#### Pros:
- windows/osx/linux in one place
- may fix tests under osx
- can be used to build docker images
- according to [doc](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits) allows **20 concurrent jobs** (although only **5 for osx**), while [travis-ci](https://travis-ci.com/plans) allows only **3 concurrent jobs** and **no parallelism across various OS'es**

Closes: #940
Closes: #758 
Refs: #887

**Comment by ygj6** [comment]
I plan to write the following files in `.github/workflows`:
- linux.yml   (build and test on linux)
- windows.yml (build and test on windows)
- mac.yml (build and test on mac)
- doxygen.yml (generate documentation with doxygen on linux)
- coverage.yml (generate coverage report on linux)

**Comment by azat** [comment]
Ok, great, thanks!

FWIW: Looks like [I found](https://github.com/azat-archive/osx-timers/commit/03795ae74d5148ba4be2937b1b0762efc87a6887) how to fix issue under osx

And AFAICS osx vms on github actions anyway works better (at least scheduled faster) then on travis-ci

**Comment by azat** [comment]
I will finish with patches with timers for libevent and leave github actions to you

**Comment by azat** [comment]
@ygj6 are you planning to do this in the nearest feature?

**Comment by ygj6** [comment]
I have written these files and am still debugging.
