### ISSUE TITLE
http-connect.c not working

### ISSUE THREAD

**Issue by chenjianjian** [libevent/libevent#946]
http-connect.c not working, the 'connect_cb' function only be called in timeout.
The libevent version is 2.0.21
The wireshark packets :

CONNECT 172.28.79.3:9209 HTTP/1.1
Host: 172.28.79.3:9209
Proxy-Connection: keep-alive

HTTP/1.1 200 Connection Established
Proxy-agent: nginx

**Comment by azat** [comment]
>http-connect.c not working, the 'connect_cb' function only be called in timeout.

Can you post `strace.log` after running `strace -s1000 -o strace.log http-connect ...` ?

>The libevent version is 2.0.21

Can you switch to 2.1.x?

**Comment by chenjianjian** [comment]
I switch to 2.1.11. The debug log:
[debug] Attempting connection to 112.49.37.56:5906

[debug] evhttp_add_header: key: Host val: 172.28.79.3:80

[debug] evhttp_add_header: key: Proxy-Connection val: keep-alive

[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d8c0 (fd -1), callback 0x7f82bbd39120
[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d8c0 (fd -1), callback 0x7f82bbd39120
[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d8c0 (fd -1), callback 0x7f82bbd39120
[debug] event_add: event: 0x1b6d8c0 (fd -1),  EV_WRITE  EV_TIMEOUT call 0x7f82bbd39120
[debug] event_add: event 0x1b6d8c0, timeout in 45 seconds 0 useconds, call 0x7f82bbd39120
[debug] event_del: 0x1b6d8c0 (fd -1), callback 0x7f82bbd39120
[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd38f30
[debug] event_add: event: 0x1b6d8c0 (fd -1),  EV_WRITE  EV_TIMEOUT call 0x7f82bbd39120
[debug] event_add: event 0x1b6d8c0, timeout in 45 seconds 0 useconds, call 0x7f82bbd39120
[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d8c0 (fd -1), callback 0x7f82bbd39120
[debug] event_add: event: 0x1b6d8c0 (fd 6),  EV_WRITE  EV_TIMEOUT call 0x7f82bbd39120
[debug] Epoll ADD(4) on fd 6 okay. Old events were 0; read change was 0 (none); write change was 1 (add); close change was 0 (none)
[debug] event_add: event 0x1b6d8c0, timeout in 45 seconds 0 useconds, call 0x7f82bbd39120
[debug] event_add: event: 0x1b6d8c0 (fd 6),  EV_WRITE  EV_TIMEOUT call 0x7f82bbd39120
[debug] event_add: event 0x1b6d8c0, timeout in 45 seconds 0 useconds, call 0x7f82bbd39120
[debug] timeout_next: event: 0x1b6d8c0, in 45 seconds, 0 useconds
[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x1b6d8c0 (fd 6), res 4, callback 0x7f82bbd39120
[debug] event_process_active: event: 0x1b6d8c0,  EV_WRITE  call 0x7f82bbd39120
[debug] event_add: event: 0x1b6d8c0 (fd 6),  EV_WRITE  EV_TIMEOUT call 0x7f82bbd39120
[debug] event_add: event 0x1b6d8c0, timeout in 11730347 seconds 407258 useconds, call 0x7f82bbd39120
[debug] evhttp_connection_cb: connected to "112.49.37.56:5906" on 6

[debug] event_add: event: 0x1b6d8c0 (fd 6),  EV_WRITE  EV_TIMEOUT call 0x7f82bbd39120
[debug] event_add: event 0x1b6d8c0, timeout in 50 seconds 0 useconds, call 0x7f82bbd39120
[debug] event_del: 0x1b6d840 (fd 6), callback 0x7f82bbd38f30
[debug] evhttp_write_buffer: preparing to write buffer

[debug] event_add: event: 0x1b6d840 (fd 6), EV_READ   EV_TIMEOUT call 0x7f82bbd38f30
[debug] Epoll MOD(5) on fd 6 okay. Old events were 4; read change was 1 (add); write change was 0 (none); close change was 0 (none)
[debug] event_add: event 0x1b6d840, timeout in 50 seconds 0 useconds, call 0x7f82bbd38f30
[debug] event_add: event: 0x1b6d8c0 (fd 6),  EV_WRITE  EV_TIMEOUT call 0x7f82bbd39120
[debug] event_add: event 0x1b6d8c0, timeout in 50 seconds 0 useconds, call 0x7f82bbd39120
[debug] event_del: 0x1b6d8c0 (fd 6), callback 0x7f82bbd39120
[debug] Epoll MOD(1) on fd 6 okay. Old events were 6; read change was 0 (none); write change was 2 (del); close change was 0 (none)
[debug] event_del: 0x1b6d8c0 (fd 6), callback 0x7f82bbd39120
[debug] event_add: event: 0x1b6d840 (fd 6), EV_READ   EV_TIMEOUT call 0x7f82bbd38f30
[debug] event_add: event 0x1b6d840, timeout in 50 seconds 0 useconds, call 0x7f82bbd38f30
[debug] timeout_next: event: 0x1b6d840, in 50 seconds, 0 useconds
[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x1b6d840 (fd 6), res 2, callback 0x7f82bbd38f30
[debug] event_process_active: event: 0x1b6d840, EV_READ   call 0x7f82bbd38f30
[debug] event_add: event: 0x1b6d840 (fd 6), EV_READ   EV_TIMEOUT call 0x7f82bbd38f30
[debug] event_add: event 0x1b6d840, timeout in 11730352 seconds 411258 useconds, call 0x7f82bbd38f30
[debug] evhttp_add_header: key: Proxy-agent val: nginx    **--- http 200 was received**

[debug] evhttp_read_header: start of read body for (null) on response_code:6,type:200 128

[debug] evhttp_get_body_length: bytes to read: -1 (in buffer 0)

[debug] timeout_next: event: 0x1b6d840, in 50 seconds, 0 useconds
[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x1b6d840 (fd 6), res 2, callback 0x7f82bbd38f30
[debug] event_process_active: event: 0x1b6d840, EV_READ   call 0x7f82bbd38f30
[debug] event_add: event: 0x1b6d840 (fd 6), EV_READ   EV_TIMEOUT call 0x7f82bbd38f30
[debug] event_add: event 0x1b6d840, timeout in 11730372 seconds 435855 useconds, call 0x7f82bbd38f30
[debug] event_del: 0x1b6d840 (fd 6), callback 0x7f82bbd38f30
[debug] Epoll DEL(1) on fd 6 okay. Old events were 2; read change was 2 (del); write change was 0 (none); close change was 0 (none)
[debug] event_add: event: 0x1b6d840 (fd 6), EV_READ   EV_TIMEOUT call 0x7f82bbd38f30
[debug] Epoll ADD(1) on fd 6 okay. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none)
[debug] event_add: event 0x1b6d840, timeout in 50 seconds 0 useconds, call 0x7f82bbd38f30
connect_cb, response_code:200.     **-- I add the debug log**
[debug] timeout_next: event: 0x1b6d840, in 50 seconds, 0 useconds
[debug] epoll_dispatch: epoll_wait reports 1
[debug] event_active: 0x1b6d840 (fd 6), res 2, callback 0x7f82bbd38f30
[debug] event_process_active: event: 0x1b6d840, EV_READ   call 0x7f82bbd38f30
[debug] event_add: event: 0x1b6d840 (fd 6), EV_READ   EV_TIMEOUT call 0x7f82bbd38f30
[debug] event_add: event 0x1b6d840, timeout in 11730372 seconds 435855 useconds, call 0x7f82bbd38f30
[debug] event_del: 0x1b6d840 (fd 6), callback 0x7f82bbd38f30
[debug] Epoll DEL(1) on fd 6 okay. Old events were 2; read change was 2 (del); write change was 0 (none); close change was 0 (none)
[debug] event_del: 0x1b6d840 (fd 6), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d8c0 (fd 6), callback 0x7f82bbd39120
[debug] event_del: 0x1b6d840 (fd 6), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d8c0 (fd 6), callback 0x7f82bbd39120
[debug] event_base_loop: no events registered.
[debug] event_callback_finalize_many_: 3 events finalizing
[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d8c0 (fd -1), callback 0x7f82bbd39120
[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd38f30
[debug] event_del: 0x1b6d840 (fd -1), callback 0x7f82bbd34f70
[debug] event_base_free_: 1 events freed
[debug] event_base_free_: 0 events freed
[debug] event_base_free_: 1 events were still set in base

**Comment by azat** [comment]
>http-connect.c not working

Does it works via, say, `curl`? Smth like this `curl --proxy http://172.28.79.3:9209 libevent.org` (untested)

>The debug log:

Ok, but this is not an `strace` log, can you provide it?

`strace -s1000 -tt -o strace.log http-connect`

*added `-tt`, will help a little*

**Comment by azat** [comment]
Never mind, I guess I found the problem - it should not read any body for CONNECT response, will be fixed soon.

**Comment by azat** [comment]
@chenjianjian can you verify libevent from the upstream? (and you need to compile the library too, since not only http-connect had been changed)

**Comment by chenjianjian** [comment]
It’s OK，3Q
