### ISSUE TITLE
cmake uninstall target interferes with other projects

### ISSUE THREAD

**Issue by Su1c1d0** [libevent/libevent#947]
I'm building libevent as ExternalProject along with GLFW and it so happens, that GLFW has already defined an uninstall target prior to adding libevent. (https://github.com/glfw/glfw/blob/master/CMakeLists.txt:364)
If I swap the two it works fine. However, it would be a good practice if libevent checks for the existence of an uninstall target prior to creating one and doesn't break configuration stage, much like GLFW does:
```
if (NOT TARGET uninstall)
   add_custom_target...
endif()
```

**Comment by azat** [comment]
>if (NOT TARGET uninstall)

Sure, do you want to submit a PR?

**Comment by Su1c1d0** [comment]
Sure
