### ISSUE TITLE
Cygwin: Failed to new bufferevent with BEV_OPT_THREADSAFE flag.

### ISSUE THREAD

**Issue by langson6502** [libevent/libevent#950]
#### Testing envirnoment:
- Windows 10 64-bits + Cygwin 3.1.2 x86_64
- libevent-2.1.8-stable

#### Steps to build libevent:
- `tar -zxvf libevent-2.1.8-stable.tar.gz`
- `cd libevent-2.1.8-stable; mkdir build; cd build`
- `../configure --prefix=/usr`
- `make; make install`

#### Testing code:
```
#include <stdio.h>
#include <event2/event.h>
#include <event2/thread.h>
#include <event2/bufferevent.h>

int main(int argc, char *argv[]) {
    struct event_base *evbase;
    struct bufferevent *buffev;
    
    printf("libevent version: %s\n", event_get_version());
    
    if (evthread_use_pthreads() != 0) {
        fprintf(stderr, "evthread_use_pthreads() failed!\n");
        return -1;
    }
    
    evbase = event_base_new();
    if (!evbase) {
        fprintf(stderr, "event_base_new() failed!\n");
        return -1;
    }
    
    buffev = bufferevent_socket_new(evbase, -1, BEV_OPT_THREADSAFE | BEV_OPT_CLOSE_ON_FREE);
    if (!buffev) {
        fprintf(stderr, "bufferevent_socket_new(...) failed!\n");
        event_base_free(evbase);
        return -1;
    }
    
    fprintf(stdout, "success!\n");
   
    bufferevent_free(buffev);
    event_base_free(evbase);
    return 0;
}
```
#### Build the code and test:
- `gcc test.c -levent -levent_pthreads`
- `./a.exe`
```
libevent version: 2.1.8-stable
bufferevent_socket_new(...) failed!
```

I have also tested on other platforms (Linux and Android) and libevent versions (v2.0.21, v2.0.22 and v2.1.11-stable), **and built as static libraries with `../configure --disable-shared --prefix=/usr` on Cygwin, they are all okay**:
```
libevent version: 2.1.8-stable
success!
```

I debug the code, and found a strange thing, this is probably related to the DLL libraries, but why?
- `evthread_use_pthreads --> evthread_set_lock_callbacks --> fill evthread_lock_fns_`
- `bufferevent_socket_new --> bufferevent_init_common_ --> bufferevent_enable_locking_ --> EVTHREAD_ALLOC_LOCK --> evthread_lock_fns_.alloc is NULL --> Failed.`

**Comment by azat** [comment]
Hi! Can you try the attached patch?

**Comment by langson6502** [comment]
I tried, but no help.

**Comment by langson6502** [comment]
Interesting!!! 
If I link the exe with `-levent_core`, not `-levent`, the issue is gone.

So, I did a deep research and finally find the reason.

Here is the dependencies of the libevent DLLs on Cygwin by a tool called Dependencies (https://github.com/lucasg/Dependencies).
![image](https://user-images.githubusercontent.com/7908776/72888461-8ebe5780-3d48-11ea-81fd-4678f1b0e372.png)

According to 
> https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-data#variable-scope

> Variables that are declared as global in a DLL source code file are treated as global variables by the compiler and linker, **but each process that loads a given DLL gets its own copy of that DLL's global variables.** The scope of static variables is limited to the block in which the static variables are declared. As a result, each process has its own instance of the DLL global and static variables by default.

In our case, if the exe is link with `-levent -levent_pthreads`, `evthread_use_pthreads()` fills the `evthread_lock_fns_` instance in `cygevent_core-2-1-6.dll` (which is load by `cygevent_pthreads-2-1-6.dll`), but `bufferevent_socket_new(..)` accesses the `evthread_lock_fns_` instance in `cygevent-2-1-6.dll`, that instance has not been initialized yet.

However, link with `-levent_core -levent_pthreads` will only instantiate one copy of `evthread_lock_fns_`.

In order to fix this issue, I suggest compiling all stuff into one `cygevent.dll`, or separating them to `cygevent_core.dll, cygevent_pthreads.dll, ...`

**Comment by azat** [comment]
>If I link the exe with -levent_core, not -levent, the issue is gone.

Without referenced patch?

Your investigation is indeed correct.

But after the attached patch `evthread_lock_fns_` should be only in `event_core` and `event` (but you should use only one of them, and `event` is deprecated).

The reason here is that `event_pthreads` is linked with `event_core`, and if you will link your program with `event` then you will have two copies if that symbol and such issues will arise.

**Comment by langson6502** [comment]
Yes, with your patch referenced.

From now on, I will link with `-levent_pthreads` and `-levent_core`, not `-levent`, on Cygwin.

Thank you very much!

**Comment by azat** [comment]
>Yes, with your patch referenced.

Ok, will apply it, thanks!
