### ISSUE TITLE
use of EVENT_BASE_FLAG_PRECISE_TIMER enables both CLOCK_MONOTONIC and timerfd 

### ISSUE THREAD

**Issue by meeusr** [libevent/libevent#958]
Hello

I'm using libevent on Linux (different kernel versions and architectures).

While looking into the output of an strace command, I observed that epoll_wait was called a lot of times with a very short timeout (1 or 2ms) while we do not have such a small timers running and no events were received on the registered FDs.
After adding some traces I observed that in some cases, the epoll_wait times-out and when handling the timers afterwards, not any timer was not expiring yet because "now" was bigger than the timeout value of the first timer.

After further code-study I came to the conclusion that the root-cause of this behavior was the CLOCK_MONOTONIC_COARSE clock. By passing the flag EVENT_BASE_FLAG_PRECISE_TIMER to my baseloop to use CLOCK_MONOTONIC instead my problem seems to be resolved. But in this configuration also the timerfd is used, which  is not what I want. I only want to use the CLOCK_MONOTONIC instead of CLOCK_MONOTONIC_COARSE. 
I tested this by commenting out the timerfd feature and the problem is also solved.

Now the question is: why is EVENT_BASE_FLAG_PRECISE_TIMER combining both the use of CLOCK_MONOTONIC and timerfd? Would it not be more logical to have 2 configuration flags?

Thanks
Ronny

**Comment by azat** [comment]
Hi!

>After adding some traces I observed that in some cases, the epoll_wait times-out and when handling the timers afterwards, not any timer was not expiring yet because "now" was bigger than the timeout value of the first timer.

Can you provide simple reproducer?

>After further code-study I came to the conclusion that the root-cause of this behavior was the CLOCK_MONOTONIC_COARSE clock.

Looks like it is

>By passing the flag EVENT_BASE_FLAG_PRECISE_TIMER to my baseloop to use CLOCK_MONOTONIC instead my problem seems to be resolved. But in this configuration also the timerfd is used, which is not what I want. I only want to use the CLOCK_MONOTONIC instead of CLOCK_MONOTONIC_COARSE.

Is timerfd a problem for you? The reason it is used here because epoll_wait has millisecond precision

**Comment by meeusr** [comment]
Hello 

> 
> > After adding some traces I observed that in some cases, the epoll_wait times-out and when handling the timers afterwards, not any timer was not expiring yet because "now" was bigger than the timeout value of the first timer.

Here I made a mistake I think: now is SMALLER than the timeout value of the first timer. 

> 
> Can you provide simple reproducer?
> 

I just adapted the test/test-time.c file to use only 1 timer with a fixed timeout of 50ms instead of a random value. For the both the main and the callback function are adapted.

Next I start the test application and perform an strace on the application. 
After running it for some time you will observe the following:
epoll_wait(3, [], 32, 50)               = 0
epoll_wait(3, [], 32, 1)                = 0
epoll_wait(3, [], 32, 50)               = 0
The additional epoll_wait with the timeout of 1 is triggered because 'now' is too old.

> > After further code-study I came to the conclusion that the root-cause of this behavior was the CLOCK_MONOTONIC_COARSE clock.
> 
> Looks like it is
> 
> > By passing the flag EVENT_BASE_FLAG_PRECISE_TIMER to my baseloop to use CLOCK_MONOTONIC instead my problem seems to be resolved. But in this configuration also the timerfd is used, which is not what I want. I only want to use the CLOCK_MONOTONIC instead of CLOCK_MONOTONIC_COARSE.
> 
> Is timerfd a problem for you? The reason it is used here because epoll_wait has millisecond precision

Yes, I would prefer to use CLOCK_MONOTONIC instead of CLOCK_MONOTONIC_COARSE only, without timerfd. In this way we have have a better granularity without the overhead of the timerfd.
So we would have 3 options:
- CLOCK_MONOTONIC_COARSE : least overhead but sometimes an additional loop (see strace)
- CLOCK_MONOTONIC : more overhead with msec precision
- timerfd: even better precision but most probably also more overhead.

Ronny

**Comment by azat** [comment]
Sorry for the delay, now there is `EVENT_BASE_FLAG_EPOLL_DISALLOW_TIMERFD` flag, that can be set using `event_config_set_flag()`
