### ISSUE TITLE
libevent allows blocking fds in the event loop

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#96]
Sure, the developer responsible should be frowned at until the blocking call returns. But, libevent could either mark all fds as nonblocking when they are registered for events, or assert that they are already nonblocking, possibly in debug mode only.

**Comment by ellzey** [comment]
We have to look out for `LEV_OPT_LEAVE_SOCKETS_BLOCKING` sockets now.

**Comment by azat** [comment]
I think that the purpose of the `LEV_OPT_LEAVE_SOCKETS_BLOCKING` is that you pass fd somewhere else, IOW you should not add this fd to the event base.

So I assume that we can apply nmathewson/Libevent#90

Objections? @nmathewson @NathanFrench

**Comment by NathanFrench** [comment]
Nope. Looks good here.
