### ISSUE TITLE
How to distinguish http and https request?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#963]
Does it exist some public api to do this?

**Comment by azat** [comment]
You cannot do this in a sane way right now, but there is a quirk if you need it "right now", by using `bufferevent_openssl_get_allow_dirty_shutdown` (it checks that the `bufferevent` is an openssl one).

```c
static void
http_request_done(struct evhttp_request *req, void *bev)
{   
    fprintf(stderr, "SSL: %s\n", bufferevent_openssl_get_allow_dirty_shutdown(bev) == -1 ? "no" : "yes");
}
```

Or if you are using `arg` of the request cb, then you can use `evhttp_request_set_header_cb`, but if you are using even it's `arg`, then you can obtain the `bufferevent` from the request's connection (it is better to use header cb, to get more confidence that the connection is still there):

```c
evhttp_request_set_header_cb(http_request_header_cb, NUL);

static int
http_request_header_cb(struct evhttp_request *req, void *bev)
{
    struct evhttp_connection *evcon = evhttp_request_get_connection(req);
    if (evcon) {
        struct bufferevent *bev = evhttp_connection_get_bufferevent(evcon);
        fprintf(stderr, "SSL: %s\n", bufferevent_openssl_get_allow_dirty_shutdown(bev) == -1 ? "no" : "yes");
    }
    return 0;
}
```

**Comment by azat** [comment]
>You cannot do this in a sane way right now

It is pretty easy to add, are you interested? Or should I?

**Comment by okayabc** [comment]
Can you add a field to represent http or https request in struct evhttp_request and add an interface to access this field in the following version so as to make things more clear?

**Comment by azat** [comment]
Sure, will be done!

**Comment by okayabc** [comment]
Thank you very much! Wait the new version.

**Comment by ploxiln** [comment]
You mean, for an http server, right?

How I handle this is, I create two separate `struct evhttp *` contexts, one for listening on port 80, one for port 443. For the one listening on port 443, I have to call `evhttp_set_bevcb()` to create the ssl-type bufferevent.

For each I add a handler with `evhttp_set_gencb(ctx, http_req_cb, (void*)proto);` where proto is the string "http" or "https". So when my callback is called, the user-data `void *arg` gives "http" or "https".

**Comment by okayabc** [comment]
Is it possilbe to add an bhttps field to struct struct evhttp_request like the following screenshot mentioned in evhttp_parse_request_line function of http.c? 
![libevent 增加个头域](https://user-images.githubusercontent.com/4360696/75603091-37a96080-5b06-11ea-83a8-fc83d957417d.png)

**Comment by azat** [comment]
@okayabc do you need this for the server?

As for your suggestion this will not work, since you will not have scheme there, since HTTP/1.1 request looks like:

```
GET / HTTP/1.1
Host: foobar
```

So it does not have full URI in the headers, so for the server you can simply use @ploxiln suggestion

**Comment by okayabc** [comment]
Ok, i see. Ask an irrelevant problem, if i start a thread ro run libevent server,  what's the TPS value when  receiving http request , https request?

**Comment by azat** [comment]
>what's the TPS value when receiving http request , https request?

I don't know what do you mean by TPS, but I will assume that this is transaction-per-second (IOW requests-per-second).

Just measured on my laptop (single threaded server):
- **http**: **30k** (and I'm pretty sure that it can works better, ~twice)
- **https**: **1k** (*ugh*), I did not look a lot into this, just plain http+openssl server (lot's of libcrypto in perf top, so I think that this can work better, but requires more time)

**Comment by azat** [comment]
Single-threaded server, keep-alive:
- http: ~54k
- https: ~30k

**Comment by azat** [comment]
Also note that:
- this is simple echo server
- using `SO_REUSEPORT` can be scaled linearly
- I don't think that this is the upper limit, but requires more time to confirm this

**Comment by okayabc** [comment]
keep-alive means long connnection?
About https, your laptop is 1k, what the values https: ~30k from?

**Comment by azat** [comment]
>keep-alive means long connection?

Yes

>About https, your laptop is 1k, what the values https: ~30k from?

I used single-threaded http server using libevent, and got the following:

| setup                | rps |
|----------------------|-----|
| http, no keep-alive  | 30k |
| https, no keep-alive | 1k  |
| http, keep-alive     | 55k |
| https, keep-alive    | 30k |

**Comment by okayabc** [comment]
So the value of https TPS  when establishing a new connection per request is not very high, if i want achieve more TPS, what should i do?

**Comment by azat** [comment]
- run https server in a thread pool (using `SO_REUSEPORT` it is pretty easy to do)
- [ssl session cache](https://vincent.bernat.ch/en/blog/2011-ssl-session-reuse-rfc5077)
- take a look at ciphers
- and also take a look at [NGINX-SSL-Performance.pdf](https://www.nginx.com/wp-content/uploads/2014/07/NGINX-SSL-Performance.pdf)

**Comment by okayabc** [comment]
Ok, thank you very much!
