### ISSUE TITLE
configure: getaddrinfo requires ws2tcpip.h on Windows

### ISSUE THREAD

**Issue by luke-jr** [libevent/libevent#966]
The configure script fails to pick up `getaddrinfo` when building for Windows because the check doesn't include the required `<winsock2.h>` and `<ws2tcpip.h>` per [Microsoft's documentation](https://docs.microsoft.com/en-gb/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo):

> **Note**  Ensure that the development environment targets the newest version of *Ws2tcpip.h* which includes structure and function definitions for **addrinfo** and **getaddrinfo**, respectively.

Hackily adding the includes to `configure` makes the build succeed using `getaddrinfo`, but presumably something more portable should be done.

Without using the native `getaddrinfo`, `evutil_getaddrinfo` fails to lookup IPv6 address literals such as `::1` (as [documented by Microsoft for `gethostbyname`](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-gethostbyname)).

**Comment by ygj6** [comment]
On which platform are you running the project?  `MinGW`,`Cygwin` or something else?
Our CI has `MinGW` related tests, but some issues have not been resolved, and I have not paid much attention to it. Now it seems I should deal with it.

**Comment by luke-jr** [comment]
We build using Ubuntu's MinGW toolchain (`g++-mingw-w64`).

**Comment by sipsorcery** [comment]
Looks like the same problem exists with the cmake Windows script as well. Checking out the latest source and running cmake on it doesn't detect the `getaddrinfo` function:

````
Looking for fcntl
Looking for fcntl - not found
Looking for getaddrinfo
Looking for getaddrinfo - not found
Looking for getnameinfo
Looking for getnameinfo - not found
````
I'm not that familiar with cmake but I had a quick look in the `CheckFunctionExistsEx` includes and added the line:
`set(CMAKE_REQUIRED_INCLUDES winsock2.h ws2tcpip.h)`
to this block in the `CmakeLists.txt` file:
````
# Winsock.
if(WIN32)
    set(CMAKE_EXTRA_INCLUDE_FILES winsock2.h ws2tcpip.h)
   set(CMAKE_REQUIRED_INCLUDES winsock2.h ws2tcpip.h)
    set(CMAKE_REQUIRED_LIBRARIES  ws2_32.lib shell32.lib advapi32.lib)
    set(CMAKE_REQUIRED_DEFINITIONS -FIwinsock2.h -FIws2tcpip.h)
endif()
if (SOLARIS)
    set(CMAKE_REQUIRED_LIBRARIES socket nsl)
endif()
````

Which resulted in:
````
Looking for fcntl
Looking for fcntl - not found
Looking for getaddrinfo
Looking for getaddrinfo - found
Looking for getnameinfo
Looking for getnameinfo - not found
````
And in the cmake generated `event-config.h`:
````
/* Define to 1 if you have the `getaddrinfo' function. */
#define EVENT__HAVE_GETADDRINFO 1
````

**Comment by ygj6** [comment]
The same as `getnameinfo()`. I am troubleshooting other functions.

**Comment by ygj6** [comment]
The following performance was found after testing with `mingw-w64` on Ubuntu-18.04:
*Build for 64 bit*
```
./configure --host=x86_64-w64-mingw32
checking for getnameinfo... yes
checking for getprotobynumber... yes
checking for inet_ntop... yes
checking for inet_pton... yes
checking for getaddrinfo... no
checking for struct linger... no
```
there are two issues:
- `AC_CHECK_FUNCS` can find `getaddrinfo`, but `AC_LINK_IFELSE` without headers does not.
- `AC_CHECK_TYPES` can not find `struct linger` without headers.

*Then build for 32 bit*
```
./configure --host=i686-w64-mingw32 
checking for getnameinfo... no
checking for getprotobynumber... no
checking for inet_ntop... no
checking for inet_pton... no
checking for getaddrinfo... no
checking for struct linger... no
```
there are also two issues:
- `AC_CHECK_FUNCS` can not find `getaddrinfo`
- `AC_CHECK_TYPES` can not find `struct linger` without headers.

In fact, all of the above functions or structures are available on WIndows 8.1+ or Windows Server 2003+.

Solution:
- Replace `AC_CHECK_FUNCS` with `AC_CHECK_DECL`, which can check functions with extra headers
- Add necessary headers to `AC_CHECK_TYPES` when checking `struct linger`

Just like this [patch](https://github.com/ygj6/libevent/commit/aa73ea56f346c62fa3a7e6f4e126730e23311576).

In the end, I got the correct check result:
```
./configure --host=x86_64-w64-mingw32   # or i686-w64-mingw32
checking whether getnameinfo is declared... yes
checking whether getprotobynumber is declared... (cached) yes
checking whether getservbyname is declared... (cached) yes
checking whether inet_ntop is declared... (cached) yes
checking whether inet_pton is declared... (cached) yes
checking whether getaddrinfo is declared... (cached) yes
checking for struct linger... yes
```

**Comment by azat** [comment]
>Just like this patch.

@ygj6 just apply it and we can close the issue after I guess, thanks for taking a look!

**Comment by ygj6** [comment]
Cmake has the same problem. The following functions exist on Windows but cannot be found:
```
gettimeofday
getnameinfo
getprotobynumber
inet_ntop
inet_pton
getaddrinfo
putenv
timerclear
timercmp
timerisset
strtoll
```
I will try to use `CheckSymbolExists` instead of `CheckFunctionExistsEx`.

In addition, `signal.h` and `strings.h` are checked, but their results are never used. Maybe we should remove them.

**Comment by sipsorcery** [comment]
@ygj6 I tried `CheckSymbolExists` and it didn't work. Using `set(CMAKE_REQUIRED_INCLUDES winsock2.h ws2tcpip.h)` as per my comment a few above this did work.

**Comment by ygj6** [comment]
Thank you for reminding me. But I don't want to continue using `CheckFunctionExistsEx`. These two files, `CheckFunctionExistsEx.cmake` and `CheckFunctionExistsEx.c` , were copied from the cmake repository, and the original files have been committed for more than 10 years.
`CheckFunctionExistsEx.cmake` -> [CheckFunctionExists.cmake](https://github.com/Kitware/CMake/blob/8e9a6becccc739e8135d5a3b303e8bf125fe3015/Modules/CheckFunctionExists.cmake)
`CheckFunctionExistsEx.c` -> [CheckFunctionExists.c](
https://github.com/Kitware/CMake/blob/fad91fb77038a243711677e904314ff0f283a68c/Modules/CheckFunctionExists.c)

I plan to remove these two files and use `CheckFunctionExists`  provided by cmake modules to check functions. @azat What do you think of this?

**Comment by ygj6** [comment]
And these files:
`CheckPrototypeDefinition.cmake` -> [CheckPrototypeDefinition.cmake](https://github.com/Kitware/CMake/blob/4f252abea5f1d17c60f6ff115c9c44cc0b6f1df6/Modules/CheckPrototypeDefinition.cmake)
`CheckPrototypeDefinition.c.in` -> [CheckPrototypeDefinition.c.in](https://github.com/Kitware/CMake/blob/4f252abea5f1d17c60f6ff115c9c44cc0b6f1df6/Modules/CheckPrototypeDefinition.c.in)
`FindGit.cmake` -> [FindGit.cmake](https://github.com/Kitware/CMake/blob/29383b4b85fc0f728a166a9d4e8abf123f862212/Modules/FindGit.cmake)

We cannot enjoy the benefits of cmake upgrade against these files

**Comment by azat** [comment]
>I plan to remove these two files and use CheckFunctionExists provided by cmake modules to check functions. @azat What do you think of this?

@ygj6 yes please!
