### ISSUE TITLE
Android cross compile of static binary with dependency to libevent fails

### ISSUE THREAD

**Issue by HLXEasy** [libevent/libevent#968]
Hi there,

I'd like to (cross-)compile a static Tor binary, which includes respectively depends on libevent. All works nice for the pure gcc build. As soon as I try to cross-compile for Android, the build fails. 

I'm building with CMake and figured out, that it looks like missing include files on the build directory. If I copy over the content of the libevent include folder into the include folder on the build directory after the build of libevent but before the build of the Tor binary, Tor's configure step finds libevent and the build is successful. 

What confuses me: The include folder is exactly the same on the gcc build and the build is working there as Tor's configure step works as expected. So I'm not sure where the problem is. Any hint would be much appreciated!

Note: My build uses @azat 's libevent fork (but I can't open issues there).

**Comment by azat** [comment]
> As soon as I try to cross-compile for Android, the build fails

Any logs?
I guess you are talking about this error?

>Tor's configure step finds libevent and the build is successful.

Can you post logs?

>that it looks like missing include files on the build directory

Which ones?

>Note: My build uses @azat 's libevent fork

It is ok if you are testing something (some of my patches for instance), but please don't use my fork for production builds, this is my playground, IOW something can be broken there (or removed later - and breaks ABI compatibility)
Anyway everything that worth it I'm merging into official upstream, so you can simply switch to it (and if you are using some branch and you are sure that the upstream does not includes some patch, please report this and I will take a look)

>but I can't open issues there

I closed ability to open issues there (this was done by intention, since nobody look at my fork while any issues should be public, and it is better to give issues as much attention ad we can)

**Comment by HLXEasy** [comment]
Hi and thx for the fast reply! 

> Any logs?
> I guess you are talking about this error?

I will provide all requested details as soon as possible.


> > Note: My build uses @azat 's libevent fork
> 
> It is ok if you are testing something (some of my patches for instance), but please don't use my fork for production builds, this is my playground, IOW something can be broken there (or removed later - and breaks ABI compatibility)
> Anyway everything that worth it I'm merging into official upstream, so you can simply switch to it (and if you are using some branch and you are sure that the upstream does not includes some patch, please report this and I will take a look)

Thx, very good to know. I will switch back to the upstream and prepare the requested logs.

**Comment by HLXEasy** [comment]
Hi @azat,

I switched back to upstream version of libevent but as expected that makes no difference. Here some more details. 

The Tor configure log ends with these lines:

```
checking for pthread_condattr_setclock... yes
checking whether free(NULL) works... cross
checking for libevent directory... 
```

The Tor configure error log contains this:

```
configure: WARNING: We found the libraries for libevent, but we could not find the C header files.  You may need to install a devel package.
configure: WARNING: On Debian, you can install headers for libevent using "apt-get install libevent-dev"
configure: error: Missing headers; unable to proceed.
```

If I put the following line into BuildTor.cmake, the build runs through:

`file(COPY ${libevent_SOURCE_DIR}/include DESTINATION ${TOR_LIBTOR_PREFIX}/../libevent/)`

The folder `${TOR_LIBTOR_PREFIX}/../libevent/` is the location where libevent is installed during the build. Libevent in general is included this way:

```
    set(OPENSSL_SSL_LIBRARY ssl_lib ${CMAKE_DL_LIBS} CACHE STRING "" FORCE)
    set(OPENSSL_CRYPTO_LIBRARY crypto_lib CACHE STRING "" FORCE)
    add_subdirectory(external/libevent)
```

But the build of static Tor is pita. The same copy step is necessary for libzstd, otherwise Tor couldn't find libzstd. :-/

If you want to give it a try yourself:

```
git clone --branch cmake-migration https://github.com/spectrecoin/spectre.git
./autogen.sh                                    # Initialize Git submodules
./scripts/cmake-build-android_arm64.sh -h       # Just show help
./scripts/cmake-build-android_arm64.sh -f -t    # Fullbuild including Tor
```

**Comment by azat** [comment]
Hi!

>If you want to give it a try yourself:

Quick question, can I compile without boost?

**Comment by HLXEasy** [comment]
Hi!

> Quick question, can I compile without boost?

Ok, I've setup a dedicated branch where everything else is just disabled. So only Tor with its dependencies will be built:

´´´
git clone --branch justTorWithDepsButNothingElse https://github.com/spectrecoin/spectre.git
./autogen.sh                                    # Initialize Git submodules
./scripts/cmake-build-android_arm64.sh -h       # Just show help
./scripts/cmake-build-android_arm64.sh -f -t    # Fullbuild including Tor
´´´

**Comment by azat** [comment]
FWIW: your script apparently writes files outside build tree, not a friendly

**Comment by azat** [comment]
So just like I though, you are passing `--with-libevent-dir=${libevent_BINARY_DIR}` while this is 100% right, since it contains only auto-generated headers, but you need also headers fom `${libevent_SOURCE_DIR}/include`, to make it work actually you need to pass path to the installed directory not build directory (i.e. run `cmake -DCMAKE_INSTALL_PREFIX=$PWD/libevent-install && make -j install` and then use `$PWDD/libevent-install` for `--with-libevent-dir`

**Comment by HLXEasy** [comment]
> FWIW: your script apparently writes files outside build tree, not friendly

There should nothing be written outside build dir what's not explained on the help output of the script. If so, please let me know! Thx in advance. Ah well, there's one exception: `scripts/.buildconfig` but this file is explicitly listed on .gitignore and must stay outside build dir as it could be modified to developers needs. Do you have another suggestion how to handle this a better way?

Regarding this:

> So just like I though, you are passing `--with-libevent-dir=${libevent_BINARY_DIR}` while this is 100% right, since it contains only auto-generated headers, but you need also headers fom `${libevent_SOURCE_DIR}/include`, to make it work actually you need to pass path to the installed directory not build directory (i.e. run `cmake -DCMAKE_INSTALL_PREFIX=$PWD/libevent-install && make -j install` and then use `$PWDD/libevent-install` for `--with-libevent-dir`

Now I'm confused. How should I tell CMake to install libevent during build of the whole project? There's just _one_ CMake call to configure the whole thing followed by the call to build everything. Would you suggest to split this into separate parts?


> And the reason it works for non cross-compiled build I guess because you have libevent installed in the system
> 
> (and this phrase confused me, that's why I wanted to take a look)

Absolutely possible! Thank you very much for these pointers into the right direction.

**Comment by azat** [comment]
>There should nothing be written outside build dir what's not explained on the help output of the script. If so, please let me know! Thx in advance. Ah well, there's one exception: scripts/.buildconfig but this file is explicitly listed on .gitignore and must stay outside build dir as it could be modified to developers needs.

Ok to keep outside build dir I guess, but not outside source dir, so what I've seen till now:
- `git config --global` usage
- `~/Archives` as default for various stuff (instead of `GITDIR/...`)

>How should I tell CMake to install libevent during build of the whole project? There's just one CMake call to configure the whole thing followed by the call to build everything. Would you suggest to split this into separate parts?

Looks like this will the most sane solution (you can add `make install` for lievent into tor CONFIGURE_COMMAND, but not sure that this will 100% correct in most cases, since cmake did not finished yet)

*P.S. you can also pass different include paths to tor, but I don't think that this will be correct*

**Comment by HLXEasy** [comment]
Hi

> Ok to keep outside build dir I guess, but not outside source dir, so what I've seen till now:
> 
> * `git config --global` usage

Ah ok, that's from the [viaduck upstream project](https://github.com/viaduck/openssl-cmake) and these changes will be reverted after the build. But still unclear, why they do this on a global level.


> * `~/Archives` as default for various stuff (instead of `GITDIR/...`)

Well, I want to use the archives not only on this Git clone, there'y much more inside than just the dependencies from this build. But thanks, will think about a better solution.


> > Would you suggest to split this into separate parts?
> 
> Looks like this will the most sane solution

I'm working on this solution now but run straight into another issue. :-/

I have two steps. The first builds and install OpenSSL as before into the directory `${BUILD_DIR}/usr/local/`. That's working so far. Now I try to build libevent like this:

```
cmake \
    -DANDROID=1 \
    -DANDROID_PLATFORM=${ANDROID_API} \
    -DANDROID_NDK_ROOT=${ANDROID_NDK_ROOT} \
    -DANDROID_ABI=${ANDROID_ABI} \
    -DCROSS_ANDROID=ON \
    -DCMAKE_ANDROID_API=${ANDROID_API} \
    -DCMAKE_ANDROID_ARCH_ABI=${ANDROID_ABI} \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_TOOLCHAIN_CMAKE} \
    \
    -DOPENSSL_ROOT_DIR=${BUILD_DIR}/usr/local/lib \
    -DOPENSSL_INCLUDE_DIR=${BUILD_DIR}/usr/local/include \
    -DOPENSSL_CRYPTO_LIBRARY=crypto \
    -DOPENSSL_SSL_LIBRARY=ssl \
    -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/usr/local \
    ${BUILD_DIR}/../external/libevent
```

The configure step runs through and "finds" OpenSSL:

```
-- Found OpenSSL: /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent/crypto (found version "1.1.0l")
-- OpenSSL include: /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/usr/local/include
-- OpenSSL lib: /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent/ssl;/home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent/crypto
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /home/spectre/Archives/Android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/libz.a (found version "1.2.7")
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.5", minimum required is "3")
-- Generating regress tests...
--
--         ---( Libevent 2.2.0-alpha-dev )---
--
-- Available event backends: EPOLL;SELECT;POLL
-- CMAKE_BINARY_DIR:         /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent
-- CMAKE_CURRENT_BINARY_DIR: /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent
-- CMAKE_SOURCE_DIR:         /home/spectre/coding/spectre/external/libevent
-- CMAKE_CURRENT_SOURCE_DIR: /home/spectre/coding/spectre/external/libevent
-- PROJECT_BINARY_DIR:       /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent
-- PROJECT_SOURCE_DIR:       /home/spectre/coding/spectre/external/libevent
-- CMAKE_MODULE_PATH:        /home/spectre/coding/spectre/external/libevent/cmake/
-- CMAKE_COMMAND:            /home/spectre/cmake-3.15.2-Linux-x86_64/bin/cmake
-- CMAKE_ROOT:               /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15
-- CMAKE_SYSTEM:             Android-1
-- CMAKE_SYSTEM_NAME:        Android
-- CMAKE_SYSTEM_VERSION:     1
-- CMAKE_SYSTEM_PROCESSOR:   x86_64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:            -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -Wstrict-prototypes -fno-strict-aliasing -Wmissing-prototypes -Winit-self -Wmissing-field-initializers -Wdeclaration-after-statement -Waddress -Wwrite-strings -Wno-unused-function
-- CMAKE_BUILD_TYPE:         Release
-- CMAKE_C_COMPILER:         /home/spectre/Archives/Android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang (id Clang, clang 1, GNUC 1)
-- CMAKE_AR:                 /home/spectre/Archives/Android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar
-- CMAKE_RANLIB:             /home/spectre/Archives/Android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ranlib
--
-- Configuring done
-- Generating done
```

But the build fails with this:

```
[ 15%] Built target event_extra_shared
Scanning dependencies of target test-ratelim
[ 15%] Building C object CMakeFiles/test-ratelim.dir/test/test-ratelim.c.o
make[2]: *** No rule to make target 'ssl', needed by 'bin/test-ratelim'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:640: CMakeFiles/test-ratelim.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Please let me know if you need further details, your help is very much appreciated!

**Comment by azat** [comment]
>    -DOPENSSL_CRYPTO_LIBRARY=crypto \
>    -DOPENSSL_SSL_LIBRARY=ssl \

Hm, it should find openssl without these lines, since you set `OPENSSL_ROOT_DIR`, but it looks wrong, it is root so it should contain path to all the upper level (i.e. at least `$OPENSSL_ROOT_DIR/{lib,include}` should exists)

P.S. maybe you will need to run `install` target for openssl to (if it has something on the install stage)

**Comment by HLXEasy** [comment]
Hi,

thx for the fast response.

If I configure with this:

```
cmake \
    -DANDROID=1 \
    -DANDROID_PLATFORM=${ANDROID_API} \
    -DANDROID_ABI=${ANDROID_ABI} \
    -DCMAKE_ANDROID_API=${ANDROID_API} \
    -DCMAKE_ANDROID_ARCH_ABI=${ANDROID_ABI} \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_TOOLCHAIN_CMAKE} \
    \
    -DOPENSSL_ROOT_DIR=${BUILD_DIR}/usr/local \
    \
    -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/usr/local \
    ${BUILD_DIR}/../external/libevent
```

Configure steps fails with this:

```
...
-- Check size of struct linger
-- Check size of struct linger - done
CMake Error at /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  CMakeLists.txt:847 (find_package)
```

So I add the two vars like this:

```
cmake \
    -DANDROID=1 \
    -DANDROID_PLATFORM=${ANDROID_API} \
    -DANDROID_ABI=${ANDROID_ABI} \
    -DCMAKE_ANDROID_API=${ANDROID_API} \
    -DCMAKE_ANDROID_ARCH_ABI=${ANDROID_ABI} \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_TOOLCHAIN_CMAKE} \
    \
    -DOPENSSL_ROOT_DIR=${BUILD_DIR}/usr/local \
    -DOPENSSL_INCLUDE_DIR=${BUILD_DIR}/usr/local/include \
    -DOPENSSL_CRYPTO_LIBRARY=crypto \
    \
    -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/usr/local \
    ${BUILD_DIR}/../external/libevent
```

Now it fails with this:

```
--
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENSSL_SSL_LIBRARY (ADVANCED)
    linked by target "test-ratelim" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "test-dumpevents" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "test-weof" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "event-read-fifo" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "event_openssl_shared" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "event_openssl_static" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "watch-timing" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "time-test" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "test-fdleak" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "bench_http" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "https-client" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "hello-world" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "signal-test" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "http-connect" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "http-server" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "becat" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "dns-example" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "bench_cascade" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "test-time" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "regress" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "test-changelist" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "bench" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "test-eof" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "le-proxy" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "bench_httpclient" in directory /home/spectre/coding/spectre/external/libevent
    linked by target "test-init" in directory /home/spectre/coding/spectre/external/libevent

-- Configuring incomplete, errors occurred!
```

So I also set OPENSSL_SSL_LIBRARY:

```
cmake \
    -DANDROID=1 \
    -DANDROID_PLATFORM=${ANDROID_API} \
    -DANDROID_ABI=${ANDROID_ABI} \
    -DCMAKE_ANDROID_API=${ANDROID_API} \
    -DCMAKE_ANDROID_ARCH_ABI=${ANDROID_ABI} \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_TOOLCHAIN_CMAKE} \
    \
    -DOPENSSL_ROOT_DIR=${BUILD_DIR}/usr/local \
    -DOPENSSL_INCLUDE_DIR=${BUILD_DIR}/usr/local/include \
    -DOPENSSL_CRYPTO_LIBRARY=crypto \
    -DOPENSSL_SSL_LIBRARY=ssl \
    \
    -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/usr/local \
    ${BUILD_DIR}/../external/libevent
```

Configure runs through:

```
...
-- Found OpenSSL: /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent/crypto (found version "1.1.0l")
-- OpenSSL include: /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/usr/local/include
-- OpenSSL lib: /home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent/ssl;/home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/libevent/crypto
...
```

But the build error stays:

```
[ 15%] Built target event_extra_shared
Scanning dependencies of target test-ratelim
[ 15%] Building C object CMakeFiles/test-ratelim.dir/test/test-ratelim.c.o
make[2]: *** No rule to make target 'ssl', needed by 'bin/test-ratelim'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:640: CMakeFiles/test-ratelim.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by azat** [comment]
You should set only `OPENSSL_ROOT_DIR`, if you set the libraries manually then it won't find them (since it does not add path where those libraries are into search path)

That said that you need to investigate why setting only that variable is not enough:

```
CMake Error at /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
```

I guess this is because it does not expect `include` and `lib` folders (so I was wrong).

The following value should work `${BUILD_DIR}/usr/local/lib;${BUILD_DIR}/usr/local/include` (this works because internally FindOpenssl.cmake works with lists and `;` is the list delimiter)

P.S. I think you can avoid all of the above by installing `CMAKE_SYSROOT` to `${BUILD_DIR}`

**Comment by HLXEasy** [comment]
Unfortunately that's not working:
```
cmake \
    -DANDROID=1 \
    -DANDROID_PLATFORM=${ANDROID_API} \
    -DANDROID_ABI=${ANDROID_ABI} \
    -DCMAKE_ANDROID_API=${ANDROID_API} \
    -DCMAKE_ANDROID_ARCH_ABI=${ANDROID_ABI} \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_TOOLCHAIN_CMAKE} \
    \
    -DOPENSSL_ROOT_DIR=${BUILD_DIR}/usr/local/lib;${BUILD_DIR}/usr/local/include \
    \
    -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/usr/local \
    ${BUILD_DIR}/../external/libevent
```

Results in this:

```
-- Check size of struct linger
-- Check size of struct linger - done
CMake Error at /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/spectre/cmake-3.15.2-Linux-x86_64/share/cmake-3.15/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  CMakeLists.txt:847 (find_package)
```

Regarding `CMAKE_SYSROOT`: It's already set on the referenced toolchain file:

```
set(CMAKE_SYSROOT "${ANDROID_TOOLCHAIN_ROOT}/sysroot")
```

**Comment by azat** [comment]
You've escaped the `';` properly, yes? (don't see this in the snippet)
And also you cleaned the cache before, right?

So if the following file pattern exists, this should work:
- `${BUILD_DIR}/usr/local/lib/lib{ssl,crypto}.so`
- `${BUILD_DIR}/usr/local/include/openssl/opensslv.h`

You can try to debug this with the simple `CMakeLists.txt`

P.S. I tried and it finds openssl correctly.

```
$ find /tmp/local -type l
/tmp/local/include/openssl
/tmp/local/lib/libcrypto.so
/tmp/local/lib/libssl.so
$ cmake -DOPENSSL_ROOT_DIR='/tmp/local/lib;/tmp/local/include' ..
...
-- Found OpenSSL: /tmp/local/lib/libcrypto.so   
OPENSSL_LIBRARIES: /tmp/local/lib/libssl.so;/tmp/local/lib/libcrypto.so
OPENSSL_INCLUDE_DIR: /tmp/local/include
...
```

**Comment by HLXEasy** [comment]
Hi

I don't know what you mean with escaping the semicolon!? I tried your example `';` from above as well as with backslash but that makes no difference. 

Anyway, it's working on plain Linux build but not working as soon as I switch to crosscompiling. So if I configure with

```
cmake \
    -DOPENSSL_ROOT_DIR=${BUILD_DIR}/usr/local/lib;${BUILD_DIR}/usr/local/include \
    \
    -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/usr/local \
    ${BUILD_DIR}/../external/libevent
```

ssl and crypto is found and the proper path it shown on the log. But if I configure like this:

```
cmake \
    -DANDROID=1 \
    -DANDROID_PLATFORM=${ANDROID_API} \
    -DANDROID_ABI=${ANDROID_ABI} \
    -DCMAKE_ANDROID_API=${ANDROID_API} \
    -DCMAKE_ANDROID_ARCH_ABI=${ANDROID_ABI} \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_TOOLCHAIN_CMAKE} \
    \
    -DOPENSSL_ROOT_DIR=${BUILD_DIR}/usr/local/lib;${BUILD_DIR}/usr/local/include \
    \
    -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/usr/local \
    ${BUILD_DIR}/../external/libevent
```

the configure step fails. If I take a look into CMakeCache.txt for the plain Linux build, then there's this (comments removed):

```
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/home/spectre/coding/spectre/cmake-build-cmdline/usr/local/lib/libcrypto.so
OPENSSL_INCLUDE_DIR:PATH=/home/spectre/coding/spectre/cmake-build-cmdline/usr/local/include
OPENSSL_ROOT_DIR:UNINITIALIZED=/home/spectre/coding/spectre/cmake-build-cmdline/usr/local/lib;/home/spectre/coding/spectre/cmake-build-cmdline/usr/local/include
OPENSSL_SSL_LIBRARY:FILEPATH=/home/spectre/coding/spectre/cmake-build-cmdline/usr/local/lib/libssl.so
...
pkgcfg_lib__OPENSSL_crypto:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
pkgcfg_lib__OPENSSL_ssl:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so
```

Interesting point: The last two entries point to the system OpenSSL libs!?

For the Android build it looks like this:
```
OPENSSL_CRYPTO_LIBRARY:FILEPATH=OPENSSL_CRYPTO_LIBRARY-NOTFOUND
OPENSSL_INCLUDE_DIR:PATH=OPENSSL_INCLUDE_DIR-NOTFOUND
OPENSSL_ROOT_DIR:UNINITIALIZED=/home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/usr/local/lib;/home/spectre/coding/spectre/cmake-build-android-cmdline_x86_64/usr/local/include
OPENSSL_SSL_LIBRARY:FILEPATH=OPENSSL_SSL_LIBRARY-NOTFOUND
...
pkgcfg_lib__OPENSSL_crypto:FILEPATH=pkgcfg_lib__OPENSSL_crypto-NOTFOUND
pkgcfg_lib__OPENSSL_ssl:FILEPATH=pkgcfg_lib__OPENSSL_ssl-NOTFOUND
```

**Comment by azat** [comment]
>Regarding CMAKE_SYSROOT: It's already set on the referenced toolchain file:

This is the problem, so `find_*` cmake macroses respects `CMAKE_SYSROOT`, while your paths do not inside `CMAKE_SYSROOT`, you can fix this with setting the following variables:

- `CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=NEVER`
- `CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=NEVER`

(i.e. `-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=NEVER`)

**Comment by HLXEasy** [comment]
Hi,

thx a lot, you're a CMake genius! I refactored the whole build as suggested, so now each dependency is built on its own and separately, which makes the whole thing way more understandable too.

Thx again, I've learned a lot!
