### ISSUE TITLE
configure: error: openssl is a must but can not be found. You should add the directory containing `openssl.pc' to the `PKG_CONFIG_PATH' environment variable, or set `CFLAGS' and `LDFLAGS' directly for openssl, or use `--disable-openssl' to disable support for openssl encryption

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#972]
When i use ./configure, it report the above error.

**Comment by azat** [comment]
So it cannot find openssl pkgconfig.
Do you know where do you have `openssl.pc`? If so add it to the `PKG_CONFIG_PATH`

Which environment do you have (os, version, ..) ?

**Comment by okayabc** [comment]
I haven't find openssl.pc in server. I use suse12.5

**Comment by azat** [comment]
I'm not sure (I never used opensuse) but maybe you need to install smth like `openssl-devel`?

**Comment by okayabc** [comment]
After install openssl-devel, this solves.
