### ISSUE TITLE
Does libevent can relate the request and response according to some header field?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#973]
For example, i send two request A and B, due to the asynchronous feature of libevent, the result will report in corresponding callback function. If  the request to the host is not reachable, so the two error response C and D will be reported. Then how can i relate reponse C/D to which request A/B?

**Comment by azat** [comment]
You can pass different context for this requests (`evhttp_request_new`)

**Comment by okayabc** [comment]
You mean when i create a new struct evhttp_request pointer though evhttp_request_new, if the response callback which has the evhttp_request pointer as the argument  is reported, then i can validate whether the two evhttp_request pointer is the same.

**Comment by azat** [comment]
Yes (in the simplest manner, but it is better to have some context not just pointer for each request)

**Comment by okayabc** [comment]
If using context to do this, it will add computation cost.

**Comment by azat** [comment]
I don't think that this cost will be significant against the background

**Comment by azat** [comment]
But anyway, problem solved, can be closed?

**Comment by okayabc** [comment]
Can you give me an example how to add some context?

**Comment by azat** [comment]
Something like this pretty obvious example (not sure that I fully understand what example do you want, so please be more precise, and not only here but in your issues too, if this is not what you was asking for)

```c
struct request_ctx
{
    int id;
};

struct request_ctx a = malloc(sizeof(struct request_ctx));
a->id = 1;
evhttp_request_new(.., a);

struct request_ctx b = malloc(sizeof(struct request_ctx));
b->id = 1;
evhttp_request_new(.., b);
```

**Comment by okayabc** [comment]
Ok, i see. Thx!
