### ISSUE TITLE
Support of DNS requests via TCP

### ISSUE THREAD

**Issue by seleznevae** [libevent/libevent#979]
At the moment libevent `evdns` module doesn't support TCP transport. Such functionality might be useful in case dns responses are rather big and their sizes exceed the DNS protocol's original 512-byte limit.
At the moment we are working on implementing TCP transport in `evdns`. And we will be pleased if such functionality was added to the upstream repository.
So my question is about current plans on `evdns` module evolution.
Is `evdns` module functionality is somehow frozen or open for extending? Will our possible future patches with implementation of TCP transport for `evdns` be welcomed?

**Comment by azat** [comment]
Hi!

>At the moment libevent evdns module doesn't support TCP transport. Such functionality might be useful in case dns responses are rather big and their sizes exceed the DNS protocol's original 512-byte limit.

Indeed

>At the moment we are working on implementing TCP transport in evdns. And we will be pleased if such functionality was added to the upstream repository.

I don't see any problems in merging such functionality (with proper tests)
P.S. There was an attempt in #99, but it has some issues.

>Is evdns module functionality is somehow frozen or open for extending?

Well evdns is very basic/compact/tiny implementation right now (it lacks of lots of features, tcp/dnssec/#6), but it is not frozen, just nobody have time for it (sigh)

>Will our possible future patches with implementation of TCP transport for evdns be welcomed?

Of course!
