### ISSUE TITLE
How to add self define header to response?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#981]
I use evhttp_request_get_output_headers before calling evhttp_send_error,  it doesn't work, but use evhttp_send_reply, i can see the self defined header.

**Comment by ploxiln** [comment]
It looks like, if you want to add headers, you must ue `evhttp_send_reply()` and not `evhttp_send_error()` (you can still send any kind of error response you want using `evhttp_send_reply()`). This is because `evhttp_send_error()` calls `evhttp_send_page_()` which does:

```c
	evhttp_clear_headers(req->output_headers);
	evhttp_add_header(req->output_headers, "Content-Type", "text/html");
	evhttp_add_header(req->output_headers, "Connection", "close");
```

**Comment by okayabc** [comment]
But i use evhttp_send_reply not ok, if i comment 
evhttp_clear_headers(req->output_headers); and still use evhttp_send_error, is it ok?

**Comment by azat** [comment]
In this case you will need to recompile libevent (since that `evhttp_clear_headers` is in libevent code)

**Comment by okayabc** [comment]
Yes. I have validated that this is a problem  of postman, i send a 301 reply, postman will automatically to redirect to a new address. If i turn off redirect off, i will see the added header.
