### ISSUE TITLE
Why gencb_http_handler blocks http_request_done in different thread?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#982]
I starts two thread A and B to run libevent event_base_dispatch. In thread A which receives a http request from thread B via  gencb_http_handler callback calls evhttp_send_reply immediately and then calls Sleep(5000). In thread B after five seconds, the http_request_done  callback justs receive the response, what's thre reason of why not receive responce from thread A immediately?

**Comment by azat** [comment]
evhttp_send_reply just schedules the reply to do it from the event loop, so if you call sleep, then you simply block the whole thread, and hence it will not enter the loop and won't reply until sleep will finish

**Comment by okayabc** [comment]
But i first call evhttp_send_reply then sleep. If evhttp_send_reply is synchronous, it will send response immediately and doesn't such problem.  Do you mean evhttp_send_reply is asynchronous, after calling it then sleep it will block the event loop?

**Comment by azat** [comment]
>If evhttp_send_reply is synchronous

It is only schedules the reply (the reply itself will be done from the event loop, IOW when the callback will be finished), so it is async
