### ISSUE TITLE
How to send a raw http protocol text through evhttp_connection ?

### ISSUE THREAD

**Issue by tech-a-go-go** [libevent/libevent#985]
Hi @azat again,

Is it possible to send something like the following raw http protocol text through evhttp_connection to the server so that I can skip using evhttp_add_header, evbuffer_add ? 
I have evhttp_connection in my hand using this source https://github.com/libevent/libevent/issues/975#issue-585500786 .
```c++
http_request =
	    "GET /large HTTP/1.1\r\n"
	    "Host: localhost\r\n"
            ....
	    "\r\n";
```
I've checked the http_multi_line_header_test in regress_http.c comes with libevent source but it doesn't use evhttp_connection.

I've tried bufferevent_setcb, bufferevent_write with evhttp_connection ... but no luck.
My code didn't even send a ACK packet to the server. (checked with wireshark)
 
Or can I get the inner raw connection from evhttp_connection and send the http protocol text ?? no ??

Cheers

**Comment by azat** [comment]
And why do you need `evhttp_connection`, if you want to write HTTP requests by yourself, then you should just use bufferevent

**Comment by tech-a-go-go** [comment]
@azat 

Ok, I will work on it.

Thank you!
