### ISSUE TITLE
How to turn on SO_REUSEPORT option?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#994]
I don't know whether this option is opened or not. If not, how to turn on?

**Comment by azat** [comment]
If you curious about how to do this for listeners, then it has `LEV_OPT_REUSEABLE_PORT`

**Comment by okayabc** [comment]
Yes, i have seen this #define LEV_OPT_REUSEABLE_PORT (1u<<7), i mean whether the compliled library turns on this option? If not, how to add LEV_OPT_REUSEABLE_PORT to which file?

**Comment by azat** [comment]
>i mean whether the compliled library turns on this option?

It is not enabled by default, you need to pass then during creation of the listener `evconnlistener_new/evconnlistener_new_bind`

Have you take a look into [documentation](http://libevent.org/doc/listener_8h.html#a29076ec56e051fb75aa48f30cf9111ee) or [book](http://www.wangafu.net/~nickm/libevent-book/Ref8_listener.html)?

**Comment by okayabc** [comment]
Currently, the TPS of https is not very high when using jmeter to do pressure test, approximately 500, If i start two process with SO_REUSEPORT option, will the TPS value double?

**Comment by azat** [comment]
[Yes](https://github.com/libevent/libevent/issues/963#issuecomment-593092382)

**Comment by azat** [comment]
Consider using chat (gitter/irc) for this type of questions (since it is not that large and after ther may be something unrelated to the original issue in comments)

**Comment by okayabc** [comment]
I think some instant messagers will be better, such as telegram or riot.

BTW, my service call evhttp_bind_socket_with_handle interface, how to set LEV_OPT_REUSEABLE_PORT  flag, can you give some suggestion?

**Comment by ploxiln** [comment]
> my service call evhttp_bind_socket_with_handle

That won't work, because you need to somehow specify the `SO_REUSEPORT` flag while the socket is being bound / port is being opened.

So as azat suggested you could instead do something like:

```c
const char *addr = "0.0.0.0";
uint16_t port = 8080;

struct sockaddr_in saddr = {
	.sin_family = AF_INET,
	.sin_port = htons(port),
};
inet_pton(AF_INET, addr, &saddr.sin_addr);

struct evconnlistener* listener = evconnlistener_new_bind(
    base, callback, NULL, LEV_OPT_REUSABLE_PORT, -1,
    (struct sockaddr *)&saddr, sizeof(saddr)
);
evhttp_bind_listener(http, listener);
```

Alternatively, you could open and bind the socket fd manually, without any libevent helpers, and then use `evhttp_accept_socket()`.
