### ISSUE TITLE
Why sevice has set SO_REUSEPORT option, only one service exist?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#995]

**Comment by okayabc** [comment]
Reproduction steps:
1) Dupliacate the service
2) Set the two services use the same port
3) Start the two  services
4）The former started service not exist，only the latter started service exist.

**Comment by ploxiln** [comment]
This is not related to libevent, this is related to your service manager software.

(If SO_REUSEPORT is not properly specified, you would expect the first one to start, and the second one to fail, rather than the other way around. But this seems to be mostly about the service manager.)

**Comment by okayabc** [comment]
I have manually added this line:

 if (evutil_make_listen_socket_reuseable_port(fd) < 0)
     goto out;

after

if (reuse) {
    if (evutil_make_listen_socket_reuseable(fd) < 0)
        goto out;
}

in function create_bind_socket_nonblock and compiled the library again.

The phenomenon is the first starts successfully before the second starts， when the  second starts successfully the first one disappear without core file generated and can‘t find it using ps command

**Comment by ploxiln** [comment]
By the way ... you really should not modify libevent itself.

**Comment by okayabc** [comment]
Yes，i see. But i haven't found effectively way to solve this because i use create_bind_socket_nonblock  to create socket in order to verify SO_REUSEPORT work。
