### ISSUE TITLE
a handle leak occurred, double CreateFileMapping in evbuffer_add_file(), work on windows

### ISSUE THREAD

**Issue by Hiyeyan** [libevent/libevent#999]
when i call evbuffer_add_file(), the evbuffer_file_segment_materialize() function will double call, In evbuffer_file_segment_materialize(), the seg->contents are not set on windows mapping file, I suggest judge seg->is_mapping == 1 when define _WIN32 to fix the bug

**Comment by azat** [comment]
But it is already set, no?
https://github.com/libevent/libevent/blob/f0b3160f8ce7fbd411493dcd023f562f4f9d17ee/buffer.c#L3113

**Comment by azat** [comment]
Closing, due to lack of reply, feel free to reopen
